### ISSUE TITLE
Discussion of cost of super mixin breaking change

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#10]

**Comment by leafpetersen** [comment]
cc @vsmenon @dgrove @Hixie @lrhn @munificent @mit-mit 

This issue is for discussion and analysis of the potential breakage incurred by removing support for the old experimental class based super mixins (#7).

**Comment by leafpetersen** [comment]
Some initial data.

Regexp based searching is somewhat unreliable for this, since it's a property of both the use and the definition of a class.  I did some grepping of internal code and of github, looking for classes which had `Mixin` in their name, and which extended something other than `Object`.   Github search results are [here](https://github.com/search?q=language%3Adart+%22class%5C+%5Cw%2AMixin%5Cw%2A%5C+extends%22&type=Code).  Suggestions on how to refine this search welcome, but based on poking around in that query, most results are `ListMixinWorkAround` (cc @jmesserly :) which is a false positive, or old forks of obsolete SDK code.

**Comment by leafpetersen** [comment]
I also hacked the analyzer to look for
 - Uses of super mixins (no false positives)
 - Classes which make a super call and `Mixin` in their name (possibility of false positives).

I downloaded the top 20 or so flutter/pub packages by popularity, and ran my hacked analyzer on them **including the transitive closure of the dependencies** and found no examples of super mixins defined outside of the flutter framework.  

I'll test out more packages from github, suggestions on other code bases to run on, or other ways of finding code to test out?  

After a bit more independent poking, I would like to propose that I mail flutter-dev:
  - describing the proposed change
  - explaining why we believe this will be essentially non-breaking
  - soliciting either known counter-examples, or publicly available codebases that people would like me to analyze for breakage.

@Hixie @dgrove, thoughts?

**Comment by Hixie** [comment]
SGTM.

**Comment by munificent** [comment]
If we really can't find *any* uses of super mixins outside of the two (is that all?) classes in Flutter, does this feature really carry its weight? Could those mixins in Flutter be changed to use explicit delegation instead and then we get a simpler feature?

I think dedicated mixin syntax is still a good idea, but that would let us sidestep all of the confusing semantics and syntax around specifying the superclass constraints on the mixin, and avoid the implementation and code size challenges of implementing mixins that contain super calls.

**Comment by yjbanov** [comment]
> If we really can't find any uses of super mixins outside of the two (is that all?) classes in Flutter

There are more than two. Here's a few examples: `SingleTickerProviderStateMixin`, `TickerProviderStateMixin`, `SchedulerBinding`, `GestureBinding` (basically all `*Binding` classes), `ContainerRenderObjectMixin`, `RenderBoxContainerDefaultsMixin`, `RenderObjectWithChildMixin`, `ContainerParentDataMixin`.

I also estimated about 80 usages just inside the framework and core widgets. I don't have an estimate for user code.

**Comment by Hixie** [comment]
Yeah we use this a lot. I also use it in my private code at home, though that obviously won't show up on the radar. I suspect people outside of the Flutter team don't use it because nobody knows about it, not because it's not desireable. It's a great feature.

**Comment by bwilkerson** [comment]
> I'm running the analyzer with --show-package-warnings, which I believe means that I am checking the transitive closure of the import graph (but probably not checking files which are in reachable packages but not reachable from the import graph, is that right @bwilkerson?)

Correct.

**Comment by leafpetersen** [comment]
Ok, we have our first winners! dartdoc, file, and charts_flutter all use super mixins.

Interestingly neither of the first two actually uses `super` calls: they just mix in classes which have a non-Object super-class.

The dartdoc package (cc @jcollins-g) seems to define one super-mixin here:
https://github.com/dart-lang/dartdoc/blob/master/lib/src/model.dart#L1195

The file package (cc @tvolkert) defines several around forwarding, here (ForwardingFile, ForwardingDirectory, ForwardingLink):
https://github.com/google/file.dart/blob/master/packages/file/lib/src/forwarding/forwarding_file.dart#L12

The charts_flutter package has at least one definition (FlutterPanBehavior) here:
https://github.com/google/charts/blob/master/charts_flutter/lib/src/behaviors/zoom/pan_behavior.dart#L68

The charts_flutter example is the only one I've found so far that actually uses super calls in a mixin.

**Comment by tvolkert** [comment]
Yep, `package:file` definitely uses this.  Happy to convert it to use the new syntax when available.

**Comment by yjbanov** [comment]
@leafpetersen good catch! `RenderBoxContainerDefaultsMixin` is not a super-mixin but merely a regular mixin, which your script correctly detected. I updated my comment https://github.com/dart-lang/language/issues/10#issuecomment-411585959

**Comment by Hixie** [comment]
I'm actually surprised to see any usage outside Flutter, given that this isn't documented at all as far as I know.

**Comment by leafpetersen** [comment]
> I'm actually surprised to see any usage outside Flutter, given that this isn't documented at all as far as I know.

Me too.  :)  

Ok, I've run a global presubmit on internal code.  The only definitions of super mixins that I see are in file, charts_flutter, and flutter.  Externally, there's dartdoc as well.

The file examples seem fully compatible with the super mixin proposal.  There are no incompatible uses of the `ForwardingXXX` classes on github.

The charts_flutter example (FlutterPanBehavior) is used internally in a way that is mildly inconsistent with the proposal (it is instantiated as a class here: https://github.com/google/charts/blob/master/charts_flutter/lib/src/behaviors/zoom/pan_behavior.dart#L47), but this is trivial to fix internally there, and there are no uses on github at all outside of the package:  https://github.com/search?q=FlutterPanBehavior&type=Code .

I think this is looking quite good in terms of breaking change cost.  I'll mail out to flutter-dev today soliciting additional feedback and examples.

**Comment by leafpetersen** [comment]
Just a note: I searched github for `extends CLASS` with CLASS replaced with each of the super mixin classes identified [here](https://github.com/dart-lang/language/issues/10#issuecomment-411917347) to understand whether there was a concern with losing the ability to extend these classes directly.  I found no code which extends any of these outside of flutter itself, or the flutter2js package.

**Comment by leafpetersen** [comment]
Mail to flutter-dev went out here:  https://groups.google.com/forum/#!topic/flutter-dev/dU6rwPVO-WA .

**Comment by yjbanov** [comment]
Should we record somewhere that Flutter currently ignores `MIXIN_INFERENCE_INCONSISTENT_MATCHING_CLASSES` [in one place](https://github.com/flutter/flutter/blob/eda03e2586b186ffcf8ea2d4424232710dbb7c81/packages/flutter/lib/src/widgets/dismissible.dart#L190). Not sure if it's a big risk.

**Comment by mit-mit** [comment]
@leafpetersen I think we can close this now?

**Comment by leafpetersen** [comment]
Closing this, since this feature has landed.
