### ISSUE TITLE
confusion about type parameter scope in dart spec 2.2

### ISSUE THREAD

**Issue by mrd2242** [dart-lang/language#1001]
In dart spec 2.2 section **9.2 "Formal Parameters"**, it says:

> The formal type parameter list of a function declaration introduces a new
scope known as the function’s type parameter scope. The type parameter scope 
of a generic function f is enclosed in the scope where f is declared. Every formal
type parameter introduces a type into the type parameter 
 scope.
> 
and
> If it exists, the type parameter scope of a function f is the current scope for
the signature of f, and for the formal type parameter list itself; otherwise the
scope where f is declared is the current scope for the signature of f
> 
I'm confusing about "If it exists, the type parameter scope of a function f is the current scope for
the signature of f". 

for a sample code:
```
main() {
  print(foo<String>("bar"));
}

T foo<T>(T a) {
  return a;
}
```
The type parameter scope of function foo is enclosed in global scope, and the signature of foo is in the type parameter scope, why foo is  accessible in main function?

**Comment by mrd2242** [comment]
![image](https://user-images.githubusercontent.com/18226209/83418820-c5bf1b00-a456-11ea-8104-b7ab6770009c.png)

I'm not clear yet.  I draw a picture, is it right?  Because foo's body scope is nested in , and `foo`  is 
 in top-level scope ,could  i  access `foo ` in foo's body scope?

**Comment by eernstg** [comment]
As @lrhn explained, the fact that the name `foo` is syntactically part of the signature of `foo`, and the signature of `foo` is in the type parameter scope of `foo` does not imply anything about where the name `foo` is available. The name `foo` is added to the library namespace, and this makes it available for lookup in the outermost scope of that library, aka the library scope. The body scope of `foo` is nested (indirectly) inside the library scope, so `foo` can be accessed in foo's body scope.

A type variable like `X` must be available for lookup in the bounds of the type variables as well as in the parameter types and return type. This is the reason why the type parameter scope must be the current scope for the signature.

**Comment by lrhn** [comment]
Yes, that image is correct for the scopes containing `main`, `foo` and `X`.

**Comment by mrd2242** [comment]
Thank you all.  But i would complain about the spec, it's hard to understand.😭

**Comment by eernstg** [comment]
Thanks! A language specification will always be a specialized document, and the need for precision and detail will probably inevitably make it hard to read. We are working on making it easier, however, and if you look at the ['In-progress specification'](https://spec.dart.dev/DartLangSpecDraft.pdf) you will see, for instance, that it contains diamond symbols in the right margin for each index entry&mdash;so you can scan the right margin for diamonds and quickly find, say, the spot where 'type parameter scope' is defined.

**Comment by mrd2242** [comment]
I think there could be some diagrams to illustrate, so that, for example, the very nested scopes would be easily understood .
