### ISSUE TITLE
NNBD spec's flags for weak/strong checking is wrong

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#1008]
Today, the Dart VM does not accept either the `--no-sound-null-safety` flag nor the `--sound-null-safety` flag, documented [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#weak-and-strong-semantics):

```none
$ ~/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dart --enable-experiment=non-nullable --no-sound-null-safety lib/a.dart 
Setting VM flags failed: Unrecognized flags: sound-null-safety
$ ~/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dart --enable-experiment=non-nullable --sound-null-safety lib/a.dart 
Setting VM flags failed: Unrecognized flags: sound-null-safety
```

It does, however, accept `--no-null-safety` and `--null-safety`, which are documented in `--help --verbose` as "Respect the nullability of types in casts and instance checks."

I suspect the solution in resolving the discrepancy is to change the spec, but please Transfer this to the sdk repo if the solution will be to change the flag in `dart`.

**Comment by leafpetersen** [comment]
Implementation issue, already tracked [here](https://github.com/dart-lang/sdk/issues/41497).
