### ISSUE TITLE
unconditional assert(foo is Bar) doesn't seem to affect the analyzer's opinion of foo's type

### ISSUE THREAD

**Issue by Hixie** [dart-lang/language#1013]
Consider:

``` dart
abstract class A { }
class B extends A { void test1() { } }

void main() {
  A a = new B();
  assert(a is B);
  a.test1();
}
```

Analyzer says:

```
[warning] The method 'test1' is not defined for the class 'A' (test.dart, line 7, col 5)
```

...but it should know at that point that "a" is actually a "B", which has "test1".

**Comment by srawlins** [comment]
Since this issue is not just about static analysis, but about expectations for runtime behavior (that `a`'s type promotes to `B`, and that `a.test1()` does not raise any static or runtime error), I've moved this to the *language* repository.

**Comment by eernstg** [comment]
Then I think it's appropriate to mention why promotion justified by an `assert` is not likely to become part of the language.

Promotion is a sound mechanism, and the argument passed to `assert` is not evaluated unless assertions have been enabled, so when `a is B` occurs as an assertion it cannot justify a promotion of the type of `a`.

However, with null-safety you can rely on a more sophisticated flow analysis, which may be an acceptable replacement for the promotion-by-assertion:

```dart
void main() {
  num n = 42;
  n as int;
  n.isEven; // No error: it is known that `n` has type `int`.
}
```

**Comment by Hixie** [comment]
`n as int` looks like a no-op. If we can't use `assert` for this purpose (though I still think that's the most idiomatic), we could introduce a new construct, like `contract(n is int);` or something, where one can describe runtime assertions that should even be checked in release mode if the compiler can't prove them to be true always. We can start with only allowing expressions of the form `variable is Type`, and maybe in the future extend it to other things that the compiler could sometimes prove, like `variable != null`.

I think in some past thread we discussed a `promote` construct, as in: `promote n as int` or some such, which would be similar to `contract` above but maybe better in that it very specifically says what is being intended here.

**Comment by leafpetersen** [comment]
This will work in null safety:

```
void promote(Object x) {}

void main() {
  num n = 42;
  promote(n as int);
  n.isEven;
}
```

I can see adding something primitive to make this slightly more idiomatic at some point, but honestly, this feels pretty close and requires no language support.

**Comment by Hixie** [comment]
What does it compile down to?

**Comment by leafpetersen** [comment]
> What does it compile down to?

Any of our production compilers should inline away the function, leaving just `n as int`.

**Comment by Hixie** [comment]
I guess I can live with that. :-)

**Comment by lrhn** [comment]
No plans to make `assert` do promotion.
