### ISSUE TITLE
Get generic , main and subtypes type in dart ?

### ISSUE THREAD

**Issue by anuragvohraec** [dart-lang/language#1017]
Describe the problem you are trying to solve, why is it hard to solve today?

I have an object like MyObject<String,SomeOtheClass>, I wanted string value for the main type [MyObject] and sub types [String, SomeOtherClass]
There is no way currrently to do that, I would have have to convert to String and then manually parse it .

**Comment by mateusfccp** [comment]
I can't understand what you mean.

**Comment by anuragvohraec** [comment]
> I can't understand what you mean.

How do I get the main type and subtype of a Generic Object in dart, For ex Type1<Type2>, I just want the Type1 separatly and Type2 separatly.

I want the main type and subtype of a generic type in Flutter. So for example if I have List<int>, I want the List and int both separately. If I do <int>[1,2,3].runtimeType , it gives me List<int>. But what if I am only intrested in List or int portion of that information.

I am creating a type compartor for sorting my data, based on there types. [say in DB where in different datatypes are pushed in].
But as I don't have a finer control on what are the types of data I have, I can't effectively sort them as desired.

**Comment by lrhn** [comment]
Dart does not provide any way to do type destructuring at run-time. A run-type type is an opaque object unless it itself provides a way to access its type arguments.

So, for the "how do I ..." question, the answer is that you don't because you cannot.

Now, if it is your own class, then you can add functionality which exposes the type arguments as other type arguments;
```dart
class MyObject<T> {
  void callWithT(void Function<S>() callback) => callback<T>();
  // ...
}
```
Then, if you have an object `o` with run-time type `MyObject<String>`, you can do
```dart
MyObject<Object> o = MyObject<String>();
o.callWithT(<T>() {
   // T is available here and will be bound to the String type.
});
```
That won't help you deconstruct `List<int>`, though.

You are also asking for `List` without the `int`. That doesn't make sense in Dart because `List` is not a type by itself. It's a generic class, so it only becomes a type when it gets a type argument. You may treat the `List<dynamic>` type as representing the `List` class itself, but it's not really true.

**Comment by anuragvohraec** [comment]
> Dart does not provide any way to do type destructuring at run-time. A run-type type is an opaque object unless it itself provides a way to access its type arguments.

Yes and that is why I have reqeust for new lang feature in Dart.
This is specially required if one is designing a database, say a JSON data store.
And you wanted to compare:
{"phone": "91234567890"} to {"phone":{"mobile":"9876543210"}

> You are also asking for `List` without the `int`. That doesn't make sense in Dart because `List` is not a type by itself. It's a generic class, so it only becomes a type when it gets a type argument. You may treat the `List<dynamic>` type as representing the `List` class itself, but it's not really true.

I can get List inference by "is" operator, but to get a complete list of generic and main types is what I am requesting for.

**Comment by lrhn** [comment]
The known language feature that would get closest to this is "open type" functionality or type-based *dynamic* pattern matching. They would allow you to write something like (with made-up syntax):

```dart
  switch (o)  {
    case List<var T> l:  .... know that `l` is a `List<T>` and have access to `T` as well.
    case Map<var K, var V> m:  ... know that `m` is a `Map<K,V>` and have access to `K` and `V`.
     ...
  }
```
You won't be able to get to a type that you don't already know exists, you would only be able to ask whether something is, say, a `List` of something, and if so what that something is.

It would necessarily be a run-time operation.

**Comment by binlly** [comment]
Same issure.

**Comment by Levi-Lesches** [comment]
Just for archival purposes, I guess: 


> This is specially required if one is designing a database, say a JSON data store.
> And you wanted to compare:
> ```dart
> {"phone": "91234567890"} 
> // and
> {"phone": {"mobile": "9876543210"}}
> ```

To do this, don't focus on the types themselves. Instead, test the object itself using `is`: 
```dart
final Map<String, dynamic> json1 = {"phone": "91234567890"};
final Map<String, dynamic> json2 = {"phone": {
  "mobile": "9876543210", 
  "work": "0123456789"
}};

class PhoneContact {
  String mobile;  // required 
  String? work;  // optional
  PhoneContact(this.mobile, [this.work]);

  factory PhoneContact.fromJson(Object json) {
    if (json is String) return PhoneContact(json);
    else if (json is Map) return PhoneContact(json ["mobile"], json ["work"]);
    else throw ArgumentError();
  }
}

void main() {
  PhoneContact contact1 = PhoneContact.fromJson(json1);  // has mobile number only
  PhoneContact contact2 = PhoneContact.fromJson(json2);  // has work number only
}
```
