### ISSUE TITLE
Move set literal "working" proposal to accepted?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/language#1025]
https://github.com/dart-lang/language/blob/master/working/0036%20-%20Set%20Literals/0037%20-%20Math-Braced%20Set%20Literals%20-%20lrhn.md

**Comment by lrhn** [comment]
I'm not sure whether we want the initial proposal in "accepted". It's not the actual design, so it's only for historical curiosity. That is, it's not the thing that was actually accepted.

**Comment by kevmoo** [comment]
Or archive?

It'd be nice if we kept this repo clean so folks can parse what's happening

**Comment by kevmoo** [comment]
Done!

**Comment by kevmoo** [comment]
https://github.com/dart-lang/language/tree/main/accepted/2.2/set-literals
