### ISSUE TITLE
Partial null-promotion not working.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1031]
Example:
```dart
int defaultCompare(Object? e1, Object? e2) => ...;

void sort<E>([int compare(E e1, E e2)?]) {
  compare ??= defaultCompare;
  ... use compare ...
}
```
This looks like it should work and make `compare` non-nullable. 
It doesn't because the type of `defaultCompare` is not a type of interest, so we don't promote *not event to non-nullable*.

I think we should. I wrote this code assuming it would work, so I think users will expect the same.

That is, if an assignment would not *type* promote because the assigned type is not one of interest, it should still be able to *null* promote as long as the RHS is non-nullable.

(I could add `as int Function(E, E)` to the RHS to fix it, and likely get an Analyzer warning about an unnecessary cast).

@leafpetersen @stereotype441

**Comment by leafpetersen** [comment]
@lrhn Can you give a complete repro?  I specified the behavior that you describe a while ago (that the non-null version of a type of interest is a type of interest), and I believe @scheglov has implemented it.  The following has no errors on bleeding edge:

```dart
int defaultCompare(Object? e1, Object? e2) => 3;

void sort<E>([int compare(E e1, E e2)?]) {
  compare ??= defaultCompare;
}
```

**Comment by lrhn** [comment]
I don't know what I was doing yesterday, because the same thing worked today (and I did not recompile).
So, all is well and this was a false alarm. Sorry about that.
