### ISSUE TITLE
Consider changing the language to reduce problems with "break" at the end of switch cases.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#1034]
(Split off from dart-lang/sdk#26673).

Some users have complained that "break" is required at the end of a switch case, wishing for this to be the default behavior (rather than the current behavior, which is to generate a runtime error unless the switch case in question is the last case in the switch).

Other users have complained that "break" is required at the end of a switch case where the analyzer can prove that the "break" is unreachable.

Also, it appears that analyzer doesn't actually require a "break" at the end of the last case in a switch; however, a strict reading of the language spec seems to say that it should.  "Fixing" the analyzer to follow the spec in this case would likely create a lot of nuisance warnings, forcing users to introduce a lot of do-nothing "break" statements.

It seems like this area of the spec might be worth revisiting.

**Comment by srawlins** [comment]
@eernstg Did this come up in the Null Safety design re: flow analysis?

**Comment by eernstg** [comment]
I think we should close this issue: It's concerned with the situation in 2016, and the rules in [flow-analysis.md](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md) along with this sentence from the [null-safety spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings) makes it obsolete: 'It is an error if any case of a switch statement except the last case (the default case if present) may complete normally'.
