### ISSUE TITLE
Flow analysis: consider restricting closure demotion to variables that are assigned "later"

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#1045]
@natebosch wondered why this didn't work:
```dart
void stuff({void Function()? x}) {
  x ??= () {}; // Promotes x to non-nullable void Function()
  x(); // ok, promoted
  otherStuff(x); // ok, still promoted
  otherStuff(() => x()); // Error since x is nullable
}

void otherStuff(void Function() f) {
  f();
}
```
The reason `x` doesn't retain its promotion in the closure `() => x()` is because flow analysis makes some conservative assumptions when analyzing closures.  In this particular case, it sees that an assignment to `x` exists somewhere in `stuff`, and conservatively assumes the assignment might assign any value, and might happen any time before the closure is invoked; under those assumptions it's not safe to retain the promotion, so it demotes the type back to `void Function()?`.

But in principle we could do better.  If we can determine that (as in this case) the assignment can't possibly happen *after* the closure is created, then it should be safe to retain the promotion.  There's a precedent for doing this sort of thing--for example at the top of a loop, we don't just demote all variables, we demote just those that are assigned within the body of the loop.  We could similarly say that when entering a closure, we only demote those variables that are assigned "later" in the function.  The tricky bit is to define a conservative approximation of "later" that is useful without being too difficult to calculate (in particular we can't make use of flow analysis itself).

I'm going to be working on flow analysis in early Q3.  I'll try to make time to think about this.

**Comment by lrhn** [comment]
This is something I had always hoped we'd do.

I guess we'll need some kind of dominates/dominated analysis (which is very closely related to flow analysis) to show that the closure creation doesn't dominate or potentially dominate any assignment (it's either dominated by or mutually exclusive with all assignments to the variable in question).

**Comment by leafpetersen** [comment]
@stereotype441 any plans to work on this, or shall I close it out?

**Comment by stereotype441** [comment]
Let's close it out.  I don't think there will be time for it to rise to the top of the priority queue.
