### ISSUE TITLE
inference not working with `is!` and `||`

### ISSUE THREAD

**Issue by benoitskipr** [dart-lang/language#1054]
inference after an `is` is such a nice feature in Dart, but I've noticed it does not work when inverted like this :

```dart
  Error err = Error();

  // err is inferred as a ArgumentError, so invalidValue is accessible
  if (err is ArgumentError && err.invalidValue == "xx")
    print("works");

  // "the getter 'invalidValue' isn't defined for the type 'Error'"
  if (err is! ArgumentError || err.invalidValue == "xx")
    print("doesn't compile");
```

it's a bit far-fetched and barely readable, but it could/should work, right ?

you can fiddle with it [here in dartpad](https://dartpad.dartlang.org/a1445ac29aecc7f68d46ec13fab0cce7)

**Comment by leafpetersen** [comment]
The upcoming Null Safety release fixes this.  Once null safety is released and you've migrated your code to it, the above will work.
