### ISSUE TITLE
Generators returning `void` is no longer an error

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1059]
Consider the following program:

```dart
void h() sync* { }
main() => h();
```

This program causes a compile-time error with the CFE, but no errors in the analyzer. The reported error is "Functions marked 'sync*' can't have return type 'void'", which seems to be a useful rule, because it is difficult to make the case that a generator returning `void` is useful.

In [generalized-void.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generalized-void.md) we had the following rule:

> It is a compile-time error if a function marked `async*`
> or `sync*` has return type void.

The behavior of the CFE is consistent with this rule.

My interpretation is that this rule should have been included when 'generalized-void.md' was integrated into the language specification, but that didn't happen.

Given that the CFE is already enforcing this rule, it should not be a breaking change to re-introduce it, so I'd recommend that we adjust the specification to have this rule, and ask for an implementation of the rule in the analyzer.

@leafpetersen, @munificent, @lrhn, @natebosch, @stereotype441, @jakemac53, WDYT?

**Comment by eernstg** [comment]
Created PR https://github.com/dart-lang/language/pull/1060; when I have feedback here, I'll either delete that PR (if the feedback is negative) or request a review of that PR (if it is positive).

**Comment by lrhn** [comment]
Seems reasonable to disallow `void` generators. 

Unlike `async` functions, a generator has no effect if its return value is ignored, so the entire function body could be replaced by `{}` without changing behavior. We don't make dead code an error, but in this case I'm willing to make an exception.

**Comment by stereotype441** [comment]
SGTM

**Comment by eernstg** [comment]
Thanks! -- got the feedback, landed #1060.

**Comment by eernstg** [comment]
@johnniwinther, just FYI: The CFE reports a compile-time error for a generator function returning `void` (e.g., `Functions marked 'sync*' can't have return type 'void'.`). The spec has just been updated to specify this behavior. So if there are any issues requesting that the CFE should stop reporting this error (because that's what the spec used to imply), those issues are now obsolete.

**Comment by natebosch** [comment]
Do we have an issue filed to add this error in the analyzer?

**Comment by stereotype441** [comment]
> Do we have an issue filed to add this error in the analyzer?

Not that I'm aware of.  Filing one now

**Comment by stereotype441** [comment]
> > Do we have an issue filed to add this error in the analyzer?
> 
> Not that I'm aware of. Filing one now

Scratch that, it's here: https://github.com/dart-lang/sdk/issues/32192, and it looks like it's already been taken care of.
