### ISSUE TITLE
Implementation issue for null safe numbers

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#1078]
This is the implementation issue for "null safe numbers", as specified in https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/number-operation-typing.md.

Brief summary: prior to NNBD, we had a few special typing rules for numbers (e.g. `int + int` has type `int`, even though `int.operator+` has type `num Function(num)`), but there were a lot of gaps that were filled in practice by implicit downcasts (such as `double + double`, which has type `num`).  With NNBD, we're removing implicit downcasts, so we want to enhance these typing rules to avoid forcing people to introduce silly casts like `double d = (1.0 + 2.0) as double;`.  We also want to make some corresponding changes to inference contexts so that e.g. `double x = 1 + await Future(() => 2.5);` works.

The new rules will only be used on NNBD opted-in code; opted-out code will follow the old spec.

- [x] feature specification (waiting on https://github.com/dart-lang/language/pull/1065)
- [x] language tests
- [x] CFE https://github.com/dart-lang/sdk/issues/42577
- [x] analyzer https://github.com/dart-lang/sdk/issues/42629

The integration of the feature spec into the language specification does not block this issue; that effort is tracked in https://github.com/dart-lang/language/issues/1198.

**Comment by mit-mit** [comment]
@stereotype441 looks like the analyzer part is done now?

Did we update the spec yet?

**Comment by eernstg** [comment]
Extensions and other pre-null-safety topics are being integrated into the language specification and a stable 2.8 language specification is expected within weeks. Integration of null-safety related topics including null safe numbers will occur after that point.

**Comment by mit-mit** [comment]
Is everything done except for the spec update? In that case, I'd prefer to close out this issue and track the spec update elsewhere as that doesn't block beta.

**Comment by eernstg** [comment]
Moved the language specification integration out of the subtask list. @stereotype441, you closed dart-lang/sdk#42629 about a week ago, so I marked that one as done.

**Comment by stereotype441** [comment]
> Moved the language specification integration out of the subtask list. @stereotype441, you closed [dart-lang/sdk#42629](https://github.com/dart-lang/sdk/issues/42629) about a week ago, so I marked that one as done.

@eernstg correct, thanks!

**Comment by mit-mit** [comment]
Did some quick validation with:

```dart
void main() async {
  int? i;
  var x = 42.remainder(1); // Type is `num`
  expectsDouble(x); // Used to be implicit downcast.
}

void expectsDouble(double d) {}
```

With Dart 2.9.0-dev.19: "The argument type 'num' can't be assigned to the parameter type 'double'."

With 2.10.0-7.3.beta: No error.

**Comment by mit-mit** [comment]
Closing as done
