### ISSUE TITLE
Optional parenthesis in control flow headers

### ISSUE THREAD

**Issue by marcelgarus** [dart-lang/language#1082]
Currently, control flow looks like this:

```dart
if (isTrue) {
  // do stuff
}

for (final item in list) {
  // do stuff
}

switch (fruit.color) {
  case Color.red: // do stuff
  case Color.yellow: // do stuff
}

do {
  // do stuff
} while (condition);

for (var i = 0; i < 10; i++) {
  // do something
}
```

Without parenthesis around the control flow headers, it would look much cleaner (similar to Rust):

```dart
if isTrue {
  // do stuff
}

for final item in list {
  // do stuff
}

switch fruit.color {
  case Color.red: // do stuff
  case Color.yellow: // do stuff
}

do {
  // do stuff
} while condition;

for var i = 0; i < 10; i++ {
  // do stuff
}
```

(You can argue about the beauty of the last example, but I like it. Built-in range functionality would make code like this more beautiful anyways, but that's an issue for another time.)

I don't think there's a reason to keep around the parenthesis – they add more visual boilerplate and inferring the control flow header is trivial (just look for the next `{` while continuing matching parenthesis so as to not match anonymous functions or for the `;` in case of `do-while`).

This also aligns better with the semantics of the control flow structures. For example, `for-in` is a built-in structure although it seems like the header with `in` is passed to the `for` control flow.

---

Usually, in `for-in`-loops the value isn't changed inside the flow, so one possible improvement would be to also implicitly add a `final` keyword. This would make the code even cleaner:

```dart
for item in list {
 // do something
}
```

**Comment by marcelgarus** [comment]
Sadly, I just discovered https://github.com/dart-lang/language/issues/350. And fair enough, inline if as in `if (condition) something` would become more complicated.

**Comment by NatoBoram** [comment]
That could be resolved [this way](https://github.com/dart-lang/language/issues/350#issuecomment-853149167), wouldn't it?
