### ISSUE TITLE
Should `Object` parameter be a valid override of `dynamic*` parameter in mixed-mode code.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1094]
Null Safety makes `Object` a subtype of `dynamic` in null safe code, but not in legacy code.

The current subtyping rules do not allow `dynamic*` as a subtype of `Object`.
(The only rule which applies is "Left Legacy", and that reduces to `dynamic` <: `Object` which is not true.)

That matters in contravariant positions where migration might change `dynamic*` to `Object` rather than `dynamic`, but out-of-order migration doesn't allow an `Object` parameter to override a `dynamic*` parameter. (In covariant positions, like return types, changing `dynamic` to a non-`dynamic` type is a breaking API change, in contravariant position it's not).

This problem occurs for `operator==`.
```dart
// Legacy code
class Super {
  bool operator==(dynamic x) => ...;
}
// Null safe code
class Sub implements Super {
  bool operator==(Object x) => ...;
}
```
(And it is happening: https://github.com/dart-lang/sdk/issues/42687).

Should we change the rules so that `dynamic* <: Object`?

It would be consistent with `dynamic` being seen as `Object`-with-a-flag (or `Object?`-with-a-flag in null safe code). It has the same subtype relations as `Object` in legacy code, so `dynamic*` should have the same subtype relations as `Object*`.

So, should we add one extra rule to the typing rules, say:
> **Left Legacy Dynamic**: If *T0* is `dynamic*`, then *T0* <: *S0* iff `Object` <: *S0*

... because legacy dynamic is equivalent to `Object*`, not to `Object?`.

(It actually seems like the front end allows the override).

**Comment by leafpetersen** [comment]
This is not planned.
