### ISSUE TITLE
Initializing formal subtype error is specified with a variable defined in unrelated text.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#1108]
https://github.com/dart-lang/language/blob/2c70f53b9de33145f452f2ec6cc96ad78eee5e92/specification/dartLangSpec.tex#L2988..L2990

> An \Index{initializing formal} has the form \code{\THIS{}.\id}, where \id{} is the name of an instance variable of the immediately enclosing class.
...
> If an explicit type is attached to the initializing formal, that is its static type.
> Otherwise, the type of an initializing formal named \id{} is $T_{id}$, where $T_{id}$ is the type of the instance variable named \id{} in the immediately enclosing class.
> It is a compile-time error if the static type of \id{} is not a subtype of $T_{id}$.

_T\_{id}_ is only specified in the "Otherwise" case, but the compile-time error can only be found in the "If an explicit type is attached" case.

**Comment by eernstg** [comment]
Indeed! This and several other imprecisions at this location in the language specification are handled in PR #1110.
