### ISSUE TITLE
No compile time error in Dart when a method is given a parent class in place of its subclass

### ISSUE THREAD

**Issue by atreeon** [dart-lang/language#1124]
The following gives a runtime error on the last line but why do I not receive a compile time error?

Why is this? `fnSub` (last line) accepts a type of `Sub` but here I'm passing it a type of `Parent` and it compiles. Ok, I do get a runtime error but I'd have thought this should have given me a compile time error. Is this a bug in Dart or am I misunderstanding the limitations of the type system or have I just gone crazy?
```

class Parent {}

class Sub implements Parent {
  String get blah => "blah";
}

String fnSub(Sub sub) => sub.blah;

String aProblem(Parent parent) => fnSub(parent);
```

https://dartpad.dev/acd2767cd42371deae0644fa66e8c602

https://stackoverflow.com/questions/63198365/no-compile-time-error-in-dart-when-a-method-is-given-a-parent-class-in-place-of

**Comment by leafpetersen** [comment]
Dart currently allows "implicit" downcasts, as you observe above in your example.  The upcoming (opt-in) null safety release will remove this behavior.  In the mean time, you can also [customize](https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks) your use of the analyzer to forbid these silent downcasts.

**Comment by iapicca** [comment]
@leafpetersen 
will be downcast prevented completely?
I think sometimes it could be useful

```dart

class FooModel {FooModel(String title, String subtitle);}
class BarModel {BarModel(String main, List<FooModel> foos);}

class FooModelHelper extends FooModel {
  FooModelHelper(Map<String,dynamic> map)
     : super(map['title'],map['subtitle'],); 
}

class BarModelHelper extends BarModel {
  BarModelHelper(Map<String,dynamic> map)
      :
        super(
         map['main'],
          <FooModel>[
            for (Map<String,dynamic> m in map['foos']) FooModelHelper(m)
          ],
        );

}


```

**Comment by leafpetersen** [comment]
> @leafpetersen
> will be downcast prevented completely?

Downcasts from `dynamic` will be permitted by default, but otherwise yes.
