### ISSUE TITLE
Anomaly with static checks on uninitialized final field

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1131]
Cf. https://github.com/dart-lang/sdk/issues/42844. Consider the following program:

```dart
class A {
  final Never n;
  factory A() = B;
}

class B implements A {
  Never get n => throw 1;
}

class C = Object with A;

void main() {
  print(C().n); // Prints 'null'.
}
```

This program is currently (4d16efc562bf9df09a802cc9c0c73ca2f0bbabed) accepted by the common front end, which is consistent with the language specification and with the updates in the null-safety specification.

However, it is a soundness violation to evaluate `C().n` to null because it has the declared type `Never`.

Also, it is surely an oversight, because it is an error to leave the final instance variable uninitialized as soon as there is one or more generative constructors in `A`. The rule which enforces initialization of final instance variables is in the 'Initializer lists' section, and it is explicitly only applicable when there is at least one generative constructor.

The analyzer already reports an error in this situation, so the proposed addition of an error would be non-breaking.

Cf. https://github.com/dart-lang/language/pull/1130.

**Comment by leafpetersen** [comment]
I disagree that this is not covered by the existing spec (though maybe the spec is not as we would like it?)  I believe that the following text from the feature spec applies:

```
It is an error if a mixin declaration or a class declaration with no generative constructors
declares an instance variable with a potentially non-nullable type and no initializer expression
unless the variable is marked with the `late` modifier.
```

And indeed, the analyzer flags `n` as an error above.

**Comment by eernstg** [comment]
Right, there is this rule in the null safety spec about a variable with a potentially non-nullable type, and that's the case where it would be unsound to initialize to null and omit the error. And it is not a soundness violation in legacy code. So I agree that the soundness issue doesn't exist after all.

However, I don't see any rules covering the following variant:

```dart
class A {
  final dynamic n;
  factory A() = B;
}

class B implements A {
  dynamic get n => throw 1;
}

class C = Object with A;

void main() {
  print(C().n); // Prints 'null'.
}
```

So what we have is not a soundness violation, but the following anomaly: There is a compile-time error for every situation where a final instance variable remains uninitialized after object construction, _except_ in this situation (no generative constructors + derivation of a mixin + nullable type such that the other rule doesn't kick in).

The rule which ensures this property is specified in the section about initializer lists in the language specification (so it's implied that the enclosing class has such a constructor), and the PR #1130 adds a rule which covers the forgotten case where no generative constructors exist. 

The PR fixes this anomaly, which is needed if we want to claim that "the language ensures that final instance variables are initialized during instance creation, so they won't be null just because you forgot to initialize them (null safety: not even the ones with a nullable type)".

> And indeed, the analyzer flags `n` as an error above.

That's what I thought as well, but it actually only reports the error with null safety, and accepts the program with no issues without null safety, for the `Never` as well as the `dynamic` variant. So the change is in principle breaking if we apply it to legacy code (although this kind of class is probably a rare exception).

So we could change #1130 to leave the language specification unchanged and update the null safety specification to cover the `final` case as well:

```
It is an error if a mixin declaration or a class declaration with no generative constructors
declares an instance variable with no initializing expression which is final or whose type
is potentially non-nullable, unless the variable is marked with the `late` modifier.
```

This change would be non-breaking and have no implementation associated, because the analyzer reports this error already.

**Comment by eernstg** [comment]
Spec change landed [here](https://github.com/dart-lang/language/commit/028a4ffe21a76cf44851e3daadab369ab59f7031).

**Comment by eernstg** [comment]
Test landed in https://github.com/dart-lang/sdk/commit/becf615d11ec703ddafdbb1f2abc460f8a06ad20.
