### ISSUE TITLE
Super-bounded type definition needs to be updated in the null safety release

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1132]
I believe we are missing an update to the definition of super-bounded types for null safety: https://github.com/dart-lang/sdk/issues/42196 .

@eernstg do you agree?  If so, would you mind making a PR and updating the relevant tests?

cc @scheglov

**Comment by eernstg** [comment]
Spec update proposal [here](https://github.com/dart-lang/language/pull/1133).

**Comment by eernstg** [comment]
Tests under review [here](https://dart-review.googlesource.com/158397).

**Comment by eernstg** [comment]
Implementation issue https://github.com/dart-lang/sdk/issues/43524 closed, links to several other related issues mentioned in #1133, all closed. Tests still under review.

**Comment by eernstg** [comment]
Tests landed Dec 28 2020, done.
