### ISSUE TITLE
What is this? fartlang.org

### ISSUE THREAD

**Issue by brilliapps** [dart-lang/language#1148]
Just wanted to notify you but didn't know where. I found this website fartlang.org
Not sure how i got to this page 
ht tps : //far tlan g.o rg/gui des/langu age.html
Seems like "d" was replaced to "f". 
You just can remove this issue after you know what it is.

**Comment by srawlins** [comment]
It's a parody website. Not built by Googlers.

**Comment by brilliapps** [comment]
Ok, thank you for the info, i just damaged the link to the page from my first post on this issue, so it is not indexed easily by search engines, **You can close or rather remove this "issue" if you can.** I had some fun reading stuff on that page though :)
