### ISSUE TITLE
Implementation issue for the generalized type alias feature

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#115]
[Edit Feb 2021: The implementation issue needs to be in the SDK repo, so we will use https://github.com/dart-lang/sdk/issues/44951 as the implementation issue for non-function type aliases. Deleted the check boxes below to avoid duplication and confusion.]

This issue is for tracking implementation of the generalized type alias feature:

Request issue: https://github.com/dart-lang/language/issues/66
Feature issue: https://github.com/dart-lang/language/issues/65
Main SDK tracking issue: https://github.com/dart-lang/sdk/issues/44951

Feature specification:
https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md

Implementation plan:
https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/implementation-plan.md

[List of tasks and check boxes deleted: See https://github.com/dart-lang/sdk/issues/44951]

**Comment by srawlins** [comment]
I think there are some important missing items from the check list. Considering grok (now Kythe), Cider, and Angular are in Phase 0, these should probably be Phase 0:

* analysis_server **core features** (Go To Definition, Find References, Sort Declarations)
* analysis_server auto-complete (name, constructors)
* analyzer: include generalized type alias test cases in existing diagnostic tests (invalid assignment, type alias application in places like `catch`, `extends`, constructor redirection, unnecessary cast with `as`, unused type aliases, invalid access to a `@protected` constructor, member, etc)
* linter: consider existing lints; add test cases and application to generalized type alias

**Comment by eernstg** [comment]
Thanks, added those items to the list.

**Comment by eernstg** [comment]
Closing this issue, the new implementation issue for this feature is https://github.com/dart-lang/sdk/issues/44951.
