### ISSUE TITLE
Private enum entries are allowed but problematic

### ISSUE THREAD

**Issue by ryanheise** [dart-lang/language#1151]
Dart allows you to define this:

```dart
enum Options {
  _hiddenOption,
  foo,
  bar,
}
```

But outside of the library, switching over the enum entries is problematic:

```dart
switch (option) {
  case foo:
  case bar:
}
```

The API docs will not reveal that there is an unhandled case, but the linter will tell you that there is a missing case. The IDE will offer to insert the missing case, but the inserted case will not compile.

Private enum entries are potentially useful to represent options that are used only internally by the library. I had a use for this while creating a wrapper for Android's Audio Usage enumeration:

```dart
enum AudioUsage {
  unknown,
  media,
  voiceCommunication,
  voiceCommunicationSignalling,
  alarm,
  notification,
  notificationRingtone,
  notificationCommunicationRequest,
  notificationCommunicationInstant,
  notificationCommunicationDelayed,
  notificationEvent,
  assistanceAccessibility,
  assistanceNavigationGuidance,
  assistanceSonification,
  game,
  // Usage value to use when feeding audio to the platform and replacing "traditional" audio
  // source, such as audio capture devices.
  _virtualSource,
  assistant,
}
```

Although, my use case would be somewhat handled by #158 which would allow me to explicitly assign `assistant` the numeric value 16 rather than 15 even if `_virtualSource` were omitted from the enum.

(Reference: Section 6.2 and Section 13 of the [Dart Language Specification](https://dart.dev/guides/language/specifications/DartLangSpec-v2.2.pdf))

**Comment by lrhn** [comment]
There is no inherent problem with allowing privately named enum values when the use-case calls for it.
It does mean that noone outside the library can do an exhaustive switch, but if the enum is intended for input to the library, then that's likely fine.
I see no reason to disallow private enum values. It might break existing code, and it's easy to just not introduce any when creating an enum. It's completely consistent behavior that the value is inaccessible.

If there is an issue, it is that the language requires switches to be exhaustive even when impossible.
That's not *clearly* a bug. It could be argued that the user might want to be warned that the switch is non-exhaustive, so they will add a `default:` clause.
In practice, a private enum member is probably going to be kept inside the library declaring it, perhaps as a default value, sentinel value or just a value that is available only after some necessary computation.
We could, and possibly should, change the spec to say that an enum-typed switch is exhaustive when all *accessible* enum values are covered.

If there is a clear bug, it's in a the auto-complete which tries to generate references to inaccessible constants. It should probably generate something like:
```dart
  // WARNING: enum contains inaccessible declarations, switch is not exhaustive.
```
That's an SDK issue, though.

(We could also allow *static declarations* inside enum declarations. That could make private enum declarations be more useful:
```dart
enum Color {
  _red,
  _green,
  _blue;
  static const sanguine = _red;
  static const ruby = _red;
  static const verdant = _green;
  static const emerald = _green;
  static const cerulean = _blue; 
  static const topaz = _blue;
}
```
It won't help with deciding exhaustiveness, though, so it's more likely that we'd want enum aliasing instead:
```dart
enum Color {
  sanguine,
  verdant,
  cerulean,
  ruby = sanguine,
  emerald = verdant,
  topaz = cerulean;
} 
where the system can tell that which names are considered part of the enum.)

**Comment by ryanheise** [comment]
> We could, and possibly should, change the spec to say that an enum-typed switch is exhaustive when all _accessible_ enum values are covered.

It is not clear to me from the spec how an exhaustive switch is checked. For example, consider these two examples:

```dart
// Example A
switch (dealWithIt()) {
  case Options.foo: ...
  case Options.bar: ...
}
// Example B
bool baz() {
  switch (dealWithIt()) {
    case Options.foo: return true;
    case Options.bar: return false;
  }
}
```

Let's say that there are only two enum values `foo` and `bar`. Currently, the first example is considered exhaustive while the second example is not. I think this is inconvenient, since it can be statically determined that Example B is exhaustive, too, and the failure to do so results in twisted coding patterns to insert an unnecessary default case.

Now let's say that there is also a 3rd hidden enum value, and the library function `dealWithIt` happens to return it (because there is nothing in the language that prevents it from doing so). I think ideally again both examples would be treated consistently and would be statically determined to not be exhaustive and alert the programmer.

**Comment by lrhn** [comment]
The seconds example should be considered as exhaustive as the first. Both have cases for all enum values of `Options`, and whether it's exhaustive should not depend on the content of the branches at all.

I can see that DartPad gives a warning for the second function. It must do that because the current Dart specification doesn't understand that control might never continue after a `switch` statement, and the function needs to always return a `bool`.
If you try the same code in https://nullsafety.dartpad.dev/ then you get the new-and-improved control flow analysis which removes that warning.

**Comment by ryanheise** [comment]
Ah, so that's why that happened. It's nice this is solved in the new control flow analysis.

Then, regarding the present issue, if there is a hidden enum value, then I believe a default case should be required rather than considering "an enum-typed switch [be] exhaustive when all accessible enum values are covered". Especially in Example B, but also in Example A for consistency.

**Comment by munificent** [comment]
> We could, and possibly should, change the spec to say that an enum-typed switch is exhaustive when all _accessible_ enum values are covered.

Wouldn't that open a soundness hole with null safety?

```dart
// a.dart
enum A {
  _hidden,
  visible
}

A makeHidden() => A._hidden;

// b.dart
import 'a.dart';

int test(A a) {
  switch (a) {
    case A.visible: return -1;
  }
  // No return. OK because switch is exhaustive.
}

main() {
  int i = test(makeHidden());
  print(i); // ???
}
```

**Comment by lrhn** [comment]
@munificent 
That's a good point. I was thinking that being exhaustive or not was just a hint, but if we use it for soundness, then we do have to cover all cases.

**Comment by lrhn** [comment]
We do not plan to change anything at the language level.
A private enum member might be deliberate and useful in cases where other libraries are not expected to do any switching over the values (for example, they are only used as parameters on functions going into the library, not provided as values out of the library). So, we don't want to disallow private enum members.
On the other hand, since we base flow analysis on whether a switch is exhaustive, we cannot optimistically assume that situation, so a switch over an enum is only exhaustive if it handles *all* the values, even the inaccessible ones (meaning it will need a `default` case).
That's the current state, so we won't need a language change.

It might be valuable if a non-exhaustiveness warning mentions that you will need a `default` because some enum values are inaccessible (and that the quickfix won't create invalid code).

**Comment by Levi-Lesches** [comment]
I'm not having this issue, but I was wondering, would it be more reasonable to only allow private enum members in private enums? That way, you could more-or-less ensure that any switches are exhaustive where it matters, and where you can't access the private member, you can't access the enum as a whole.
