### ISSUE TITLE
Privates fields should get promoted

### ISSUE THREAD

**Issue by Hixie** [dart-lang/language#1167]
One can statically prove that this code does not have a null dereference risk:

```dart
class A {
  int _foo;

  void test() {
    if (_foo != null)
      print(_foo + 1);
  }
}
```

As far as I can tell, there is no way, even with `implements` and `noSuchMethod` and other shenanigans, for `_foo` to ever be null on the line with the `print`.

cc @leafpetersen who pointed out that some similar cases aren't so cut and dry because privates can be implemented using noSuchMethod.

**Comment by Hixie** [comment]
The amount of time I see code like the following while doing the framework migration really makes me wish we could do this even if it only works in narrow cases.

```dart
  // _dependencies is a private member of this class
  final bool hadDependencies = (_dependencies != null && _dependencies!.isNotEmpty) || _hadUnsatisfiedDependencies;

  // _dependencies is a private member of this class
  _dependencies ??= HashSet<InheritedElement>();
  _dependencies!.add(ancestor);

  // _flutterError is a private final field set in the constructor
  if (_flutterError == null)
    properties.add(StringProperty('message', message, quoted: false));
  else
    properties.add(_flutterError!.toDiagnosticsNode(style: DiagnosticsTreeStyle.whitespace));

  // _child is a private field of the class
  if (_child != null)
    visitor(_child!);

  // _inheritedWidgets is a private field
  if (incomingWidgets != null)
    _inheritedWidgets = HashMap<Type, InheritedElement>.from(incomingWidgets);
  else
    _inheritedWidgets = HashMap<Type, InheritedElement>();
  _inheritedWidgets![widget.runtimeType] = this;
```

**Comment by leafpetersen** [comment]
See [here](https://github.com/dart-lang/language/issues/1187) for a quick proposal on syntax for a forced promotion operator to allow unsound (runtime checked) promotion .

**Comment by Hixie** [comment]
I don't think we should need new syntax for the cases I list above. They're all entirely safe cases as far as I can tell. I can see an argument that it would lead to questions about "why does it work here but not in this identical-seeming case", but I think we can actually answer that question (maybe even literally in the analyzer, part of the message could be something like "could not guarantee that type didn't change after call to X on line Y column Z" or whatever).

**Comment by leafpetersen** [comment]
> I don't think we should need new syntax for the cases I list above.

Not all of those examples can be safely done, but we could try to identify a set of criteria that are safe in existing dart.  It would look something like:
  - final, private field
  - accessed as an implicit or explicit `this` call
  - some set of restrictions to ensure that mixin shenanigans don't happen (e.g. no other fields with this name in the library)

This would only cover one or two of your cases above though, since several of them are not final.

**Comment by Hixie** [comment]
I'm curious what shenanigans could invalidate the cases I've described above. Can you elaborate?

**Comment by leafpetersen** [comment]
> I'm curious what shenanigans could invalidate the cases I've described above. Can you elaborate?

I missed listing under the criteria above the obvious one: that the field is not overridden in a subclass.  But with mixins, you can essentially induce a non-local override.   That is, if I have:

```
class A {
  final int _privateField = 3;
}

class B {
  int _backingStore = 0;
  int get _privateField => _backingStore++;
}
```

Then another library can do the following:

```
class C extends A with B {
}

void main() {
  new C()..test()..test()..test();
}
```

This prints out:
```
0
1
2
```

So to do sound promotion, you need to ensure that mixin overrides can't happen in this way.

**Comment by Hixie** [comment]
yikes. that seems like a footgun. Can we make it a violation to mix in a type that would have a private field collision without having indicated with "extends" or "on" and @override that it's intentional? This seems like it would cause many more problems (and missed optimisation opportunities) than just this minor issue with field promotion...

**Comment by leafpetersen** [comment]
> yikes. that seems like a footgun. Can we make it a violation to mix in a type that would have a private field collision without having indicated with "extends" or "on" and @override that it's intentional? This seems like it would cause many more problems (and missed optimisation opportunities) than just this minor issue with field promotion...

We attempted to do so as part of Dart 2, but we only half succeeded.  The analyzer actually emits an error on the code above, as we had specified for Dart 2, but the CFE doesn't.  That does mean that it should be easy to patch this up.  I have a vague sense though that there's another tricky way to induce this that we'd also have to patch up, but I can I can't page it in right now.

**Comment by leafpetersen** [comment]
I filed an issue with a concrete proposal for this [here](https://github.com/dart-lang/language/issues/2020), I'm going to close this out.
