### ISSUE TITLE
consider rename pragma to Pragma?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1174]
it's not consitstent to annother annotation class name, and int, double, num..

**Comment by lrhn** [comment]
It's deliberately made lower-case to make the annotation look like a modifier.

Annotations can be either constants `@foo` or constant creation `@Foo(args)`. This causes inconsistency in capitalization.
The `pragma` annotation was made lower-case to match `@foo`, even with arguments.

There are no current plans to rename it.
