### ISSUE TITLE
how can i define a void return type lambda

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1179]
() {print(3);} return type is Null, i think return should be void

**Comment by eernstg** [comment]
The return type of a function literal is determined by inference (there is no syntactic location where it can be specified). With null safety the return type will be `void` in the case where the context type has a return type of `void` (but note that this is a recent change, so it will take some time before it's implemented and available):

```dart
// With null safety.

void main() {
  void Function() f = () { print(3); };
  print(f.runtimeType); // Prints `() => Null`, but will print '() => void'.
}
```

So you will get the ability to get the return type `void`. However, for all proper subtypes of `void` (that is, all types which are not top types), the return type in the context type for the function literal is only used as a constraint, and the inferred return type will be based on the type of the returned expressions.

```dart
void main() {
  num Function() f = () => 3;
  print(f.runtimeType); // Prints '() => int'.
}
```

**Comment by Silentdoer** [comment]
() {print(3); return;} will be void Function() ?

**Comment by eernstg** [comment]
No, when the function body execution is completed by executing `return;`, the function also returns null, and the inferred return type of a function literal like `() {print(3); return;}` will be `Null Function()`.

The point is that a function literal will get the "best" possible type (a subtype of all the possible typings) for the return type, based on the expressions actually returned. The only exception is that `void` _from the context_ will override the actually returned expressions, such that we can get the desired errors: "The context will receive this function literal, and it will ignore the returned result, so we had better emit the diagnostic messages for that situation in the same way as we do for a named function declaration".
