### ISSUE TITLE
how can i define a private constructor

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1184]
a class can not be initialize by other lib.

**Comment by eernstg** [comment]
The concept you need to use for that is a 'named constructor', that is, a constructor whose name is not just the class name but a name with two parts, like `Classname.secondPart`:

```dart
class C {
  C._(); // This constructor is private.
}
```

When there is a constructor the default constructor is not generated, so this means that it can _only_ be created by code in the same library (which could be done in at least a couple of ways: `new C._()` and, if `C` has a suitable supertype, with a redirecting factory).

I think there is no remaining issue to deal with so I'll close the issue. Note that questions about the language could go to StackOverflow.
