### ISSUE TITLE
Help with language specific bit rotations

### ISSUE THREAD

**Issue by SoraKatadzuma** [dart-lang/language#1190]
From what I understand about the language, integers are 64bit integers and all binary operations are performed unsigned. If this is true then all bit shift operations will 0 fill on overflow. Which seems to be accurate, because performing `1 << 78` and `1 >> 78` both produce 0 as the result. If the bits wrapped, the expected values would be 0x4000 and 0x4000000000000, respectively.

In C++ I'd normally do:
```cpp
uint32_t roll(uint32_t value, size_t length) noexcept {
  return (value << length) | (value >> (-length & 31));
}

uint32_t rolr(uint32_t value, size_t length) noexcept {
  return (value >> length) | (value << (-length & 31));
}
```

But this doesn't play well in Dart:
```dart
extension IntBitRoll on int {
  int roll(int length) {
    return (this.toUnsigned(64) << length) | (this.toUnsigned(64) >> (-length & 63));
  }

  int rolr(int length) {
    return (this.toUnsigned(64) >> length) | (this.toUnsigned(64) << (-length & 63));
  }
}

void main() {
  int value_l = 1.roll(78);
  print("Result: 0x${value_l.toRadixString(16)}"); // Result: 0x0, expected: 0x4000
}
```

This is unintended behaviour and it seems that no matter what I do or change around, I can't get the bits to rotate with a number higher than 64. Coming from you guys, is there any way I can perform these bit rotations? And preferably without the use of %?

**Comment by SoraKatadzuma** [comment]
I just tried this on the website, and it works actually, my SDK must be out of date, sorry to bother you guys!

**Comment by SoraKatadzuma** [comment]
This solution that I provided and tested on the dart.dev website works for lengths less than 64, but not with 78. Any suggestions, also sorry for closing and reopening

**Comment by mraleph** [comment]
You need to mask `length` in the first shift as well. Try this instead:

```dart
extension IntBitRoll on int {
  int roll(int length) {
    return (this.toUnsigned(64) << (length & 63)) | (this.toUnsigned(64) >> (-length & 63));
  }

  int rolr(int length) {
    return (this.toUnsigned(64) >> (length & 63)) | (this.toUnsigned(64) << (-length & 63));
  }
}

void main() {
  int value_l = 1.roll(78);
  print("Result: 0x${value_l.toRadixString(16)}"); // Result: 0x0, expected: 0x4000
}
```

The reason it works for you in C++ is actually accidental: underlying hardware on Intel and ARM masks shift amount with word size-1. So `a << b` is essentially `a << (b & 31)` if `a` is 32-bit. Your C++ code would not work on PowerPC which has an underlying shift behaving like Dart. Note by the way that in C++ shifting by amount greater than bit-width is undefined behaviour (would be detected by `-fsanitize=shift` for example, see https://godbolt.org/z/h5js83). 

Another thing to note is that Dart integers behave differently between Web and native: bitwise operations are 32-bit when Dart is compiled to JavaScript. If you need to write portable Dart code between Web and native then it is recommended to use package fixnum which has [Int64](https://pub.dev/documentation/fixnum/latest/fixnum/Int64-class.html) class (however this would result in less efficient code).

Finally I highly encourage you to use other channels to ask questions (e.g. StackOverflow, Discord, Gitter). This repository is for tracking Dart language evolution issues.

**Comment by SoraKatadzuma** [comment]
Ah, that makes sense, thank you for the response anyway. I wasn't exactly sure where to ask it, so I thought I would come to the source
