### ISSUE TITLE
Update needed in rule for UP on F-bounded type variables

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1193]
The following program demonstrates that we can have a variable of type `Object` that stores the value null, running with sound null safety:

```dart
bool b = true;

class C<X extends C<X, X>?, Y extends C<Y, Y>?> {
  X x;
  C(this.x);
  Object m(X x, Y y) {
    // UP(X extends C<X, X>?, Y extends C<Y, Y>?) ==
    // C<Object, Object>?.
    var z = b ? x : y;
    if (z == null) throw 0;
    return z.x;
  }
}

class D<X> extends C<D<X>?, D<X>?> {
  D(): super(null);
}

main() {
  var d = D<Null>();
  Object o = d.m(d, null);
  print("o == $o"); // 'o == null'.
}
```

I believe that this behavior is correct according to the specification of the least upper bound, cf. [this section](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md#upper-bounds), but the use of `Object` should be updated to `Object?` in the 4 rules about type variables and promoted type variables, in order to maintain soundness for this example.

Apart from the soundness issue, it is also unfortunate that the type obtained by substitutions like `[Object/X1]` is not well-bounded (`C<Object, Object>` is not a correctly super-bounded type). That's fixed by using `Object?` for the cases where the type variable occurs in a covariant position.

However, when it occurs in a contravariant position we may get an unsoundly special type:

```dart
bool b = true;

void f(Object o) {}

class C<X extends void Function(X)?> {
  X x;
  C(this.x);
  void m() {
    // UP(X extends void Function(X)?, void Function(Object)) ==
    // void Function(Object)?.
    var z = b ? x : f;
    if (z == null) return;
    z(42); // `z` unsoundly has type `void Function(Object)`.
  }
}

main() {
  var c = C<void Function(Function?)?>((Function? f) => f?.call());
  c.m(); // Dynamic error because `42` isn't a `Function?`.
}
```

This issue wouldn't be eliminated by changing `Object` to `Object?`.

We might need to consider using instantiation to bound when that yields a supertype of the bound of the type variable (that works in almost all situations, and we can fall back to a more general type like `Object?` when it doesn't work). That is, if we're approximating the bound for `X` then we'd replace contravariant occurrences of `X` by `Never` and other occurrences of `X` by `Object?`, and then we'd check that the resulting type is a supertype of the specified bound, assuming the specified bound.

**Comment by eernstg** [comment]
[This PR](https://github.com/dart-lang/language/pull/1195) makes the adjustments proposed above, plus a couple of further adjustments where the `UP` of a function type and another type may incorrectly discard nullability.

**Comment by leafpetersen** [comment]
Where are we with this?

**Comment by eernstg** [comment]
Tests ready for review [here](https://dart-review.googlesource.com/c/sdk/+/166101). Note that we may need to resolve https://github.com/dart-lang/language/issues/1250 in order to determine exactly what's the right expectation in a couple of cases.

**Comment by eernstg** [comment]
#1250 gave rise to PR #1254, https://github.com/dart-lang/language/commit/ae340c7dcc62d375bd8df9fd4cb0d669d84478d2, settling the rules for `FutureOr`. Implementation issues dart-lang/sdk#43716, dart-lang/sdk#43717, tests landed as https://github.com/dart-lang/language/commit/87dd7c03e14856c8e089ca27a02af205b8d665f5.

**Comment by eernstg** [comment]
#1250 gave rise to PR #1254, https://github.com/dart-lang/language/commit/ae340c7dcc62d375bd8df9fd4cb0d669d84478d2, settling the rules for `FutureOr`. Implementation issues dart-lang/sdk#43716, dart-lang/sdk#43717, tests landed as https://github.com/dart-lang/language/commit/87dd7c03e14856c8e089ca27a02af205b8d665f5.
