### ISSUE TITLE
Spec: Move <constructorInvocation> into <primary>

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#1199]
As far as I can tell, every place in the spec that uses `<primary>` has a matching clause that accepts `<constructorInvocation>`. I believe we can simplify things and have the same grammar by moving `<constructorInvocation>` into `<primary>` itself:

```
postfixExpression ::= assignableExpression postfixOperator
| primary selector*

assignableExpression ::= primary assignableSelectorPart
| super unconditionalAssignableSelector
| identifier

primary ::= thisExpression
| "super" unconditionalAssignableSelector
| functionExpression
| literal
| identifier
| newExpression
| constObjectExpression
| constructorInvocation
| "(" expression ")"
```

**Comment by eernstg** [comment]
Good catch! Done in https://github.com/dart-lang/language/pull/1204 and https://dart-review.googlesource.com/c/sdk/+/161708/.
