### ISSUE TITLE
Triple-shift operator

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#120]
Dart integers are now 64-bit signed numbers. That makes the `>>>` logical down-shift operator useful again. (It existed once, but with arbitrary size integers, the it didn't make sense to do unsigned shifiting any more).

This is a request for the `>>>` operator. It makes sense in other cases too (like the Int64 class).

Associated [feature specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/triple-shift-operator/feature-specification.md) has more details.

Implementation issue: https://github.com/dart-lang/language/issues/478

**Comment by rashedmyt** [comment]
@lrhn In the 2nd para of the Background section in feature-specification, it is mentioned that dart integers are unsigned 64 bit which is the opposite of what said in the above comment..

**Comment by lrhn** [comment]
Thanks, good catch. That should definitely be *signed* 64-bit integers.
Fixed.

**Comment by creativecreatorormaybenot** [comment]
@lrhn I think this can be closed now 🙌 

https://github.com/dart-lang/language/issues/478#issuecomment-889181121
