### ISSUE TITLE
May be can support a easy way to operate map?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1215]
like javascript, a object can obj.x = 'xxx', obj.y = 8...(if has no field/key, return undefined, in dart can be null);
in dart obj can be a Map<String, dynamic>, but map['x'] = 'xxx' is so  inconvenient;
should we support a operator for map? such as map->x = 8 is map.put('x', 8), map->x is map.get('x', 8)?

**Comment by lrhn** [comment]
That operator would then take the *identifier* following `->` and convert it to a `String` (or `Symbol`, depending on the map's static key type?), and do `[thatValue]` on the map.
Would it work for other things than identifiers? Would `map->2` do `map["2"]` or `map[2]`? The latter would probably be more useful, but less consistent.

That's a very specific functionality just to do lookups in `String`-keyed maps. It doesn't provide anything you can't already do, just a slightly more convenient (but less consistent) way of doing it.
It's unlikely to be useful for anything else.

All in all, I don't think it's likely that we'll do this. There are many other features with better cost/benefit ratios that we'd want to do first, and even then, doing lookup on maps with fixed string keys shouldn't be something you're doing all the time. It's really just for JSON, and we'd prefer to have other ways to make JSON easier to parse into something useful.

**Comment by Silentdoer** [comment]
i think it's just for String, map->2 is map['2']

**Comment by Silentdoer** [comment]
or map->identifier just can be a variable name identifier?

**Comment by Silentdoer** [comment]
OK, thank you for your response.

**Comment by Silentdoer** [comment]
Hi, i have rethink this issue, i think this is a very useful feature for dart's dynamicity, like dynamic obj = {}, (obj will implict be a map<dynamic, dynamic>), obj->0 = 8; is obj[0] = 8, obj->sss = "sss"; is obj["sss"] = "sss", and obj = 8, then obj.runtimeType is int, it suport an ability like javascript; and may be can support a keyword or operator like `as` keyword for infer map's key to class's field name;

**Comment by mateusfccp** [comment]
I don't really see any benefit of this. Also, using `dynamic` is mostly harmful, so I wouldn't want to have an easy access to `Map<dynamic dynamic>`.
