### ISSUE TITLE
dynamic should not assignable to Null?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1217]
print(currentMirrorSystem().dynamicType.isAssignableTo(reflectType(Null)));
it's prints true;
but:
dynamic sf = null;
Null ss = sf;  // tips: A value of type 'dynamic' can't be assigned to a variable of type 'Null'.
it's not consistent.

print(reflectType(Null).isAssignableTo(reflectClass(String)));
it's prints true;
and:
Null kks = null;
String st = '';
st = kks;  // it's ok
it's consistent.

**Comment by lrhn** [comment]
Dart currently allows implicit downcasts from a supertype to a subtype.
A value of type `dynamic` *is* assignable to a variable of type `Null`.
The "tip" is most likely the result of your project having chosen to enable the "no implicit casts" lint, not something inherent to the language.

(With null safety, general implicit downcasts goes away, and you will only allow implicit downcasts from `dynamic`.)
