### ISSUE TITLE
NNBD: How to increment/decrement a nullable expression using the operators ++/--?

### ISSUE THREAD

**Issue by simphotonics** [dart-lang/language#1221]
What is the syntax for incrementing/decrementing a nullable expression (such as the value of a map entry) using the prefix/postfix operators `++` or `--` ? I am getting the error shown below. 

```Console
$ dart --version
Dart SDK version: 2.9.3 (stable) (Unknown timestamp) on "linux_x64"
```

```Dart
final map = <int, int>{};
var index = 0;
...

if (map[index] == null){
  map[index] = 1;
}else{
  map[index] = map[index]! + 1;  // This works.
   ++map[index]!; // Missing selector such as '.identifier' or '[0]'. Try adding a selector.dart(missing_assignable_selector)
   ++(map[index]!); // Missing selector such as '.identifier' or '[0]'. Try adding a selector.dart(missing_assignable_selector)
   map[index]! += 1; // Missing selector such as '.identifier' or '[0]'. Try adding a selector.dart(missing_assignable_selector)
}
```
It seems that the expression `map[index]!` is not assignable.

**Comment by eernstg** [comment]
This discussion has been raised in https://github.com/dart-lang/language/issues/1113. There is currently no mechanism which will allow you to combine null checks (`!`) with increment/decrement, but please continue the discussion there.

**Comment by simphotonics** [comment]
Thank you for pointing out #1113.
