### ISSUE TITLE
In null-safe code, clarify `as T` (versus `!`)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/language#1225]
I have a bunch of legacy code I can't currently change or migrate that looks like this:

```dart
List<Function> _registeredFactories = [];

void registerFactory(Function function) {
  _registeredFactories.add(function);
}
```

Currently we resolve it something like like this:

```dart
List<Object> resolveFactories() {
  var result = <Object>[];
  for (var f in _registeredFactories) {
    // In our actual code we use Function.apply, but it doesn't seem related to this use-case.
    result.add(f());
  }
  return result;
}
```

To opt-in to null-safety I've written something like this:

```dart
List<Object> resolveFactories() {
  return [
      for (var f in _registeredFactories) {
        f() as Object
      }
  ];
}
```

This ... seems to work. My intention here is to allow opted-out code (existing users) to continue to return `null` as a valid value, but that as part of opting-in to null-safety the factory functions will no longer be allowed to return `null`. This ... seems to work, but I wanted to clarify if (a) it was intentional, and (b) if my train of thought here is correct/valid/a good idea.

/cc @jakemac53 @natebosch who were helping me internally.

**Comment by leafpetersen** [comment]
Yes, this will work as described.  As long as there is any opted out code in the program (i.e. you are running in weak mode), `as Object` is a no-op.  When you switch to strong mode, any code that has been passing null there and getting away with it will start getting cast failures.

**Comment by matanlurey** [comment]
Thanks!
