### ISSUE TITLE
Using `!identical(foo, null)` should promote

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/language#1226]
This was more surprising than anything while migrating existing code.

(I was able to change it to `foo != null` to unblock myself, but more an FYI for the team to review)

**Comment by leafpetersen** [comment]
@stereotype441 WDYT?  This doesn't seem super high value, but if it's fairly trivial to support, we might consider trying to slip it in as a post-beta/pre-stable fix?

**Comment by stereotype441** [comment]
> @stereotype441 WDYT? This doesn't seem super high value, but if it's fairly trivial to support, we might consider trying to slip it in as a post-beta/pre-stable fix?

It's easy going to be super-easy or it won't; it all depends on whether the resolution of the `identical` is available at the time that it's needed by flow analysis.  I'll go ahead and add it to my list to work on this in the post-beta timeframe, and if it's trivial I'll go ahead and do it.

**Comment by matanlurey** [comment]
FWIW, having filed this issue - I don't think it's that important - https://github.com/dart-lang/language/issues/1226#issuecomment-693034800 is more important to me as a resolution

**Comment by stereotype441** [comment]
FYI @bwilkerson @pq regarding the idea of a hint (https://github.com/dart-lang/language/issues/1226#issuecomment-693034800)

**Comment by pq** [comment]
It sounds reasonable to me but @bwilkerson has been thinking about these  kinds of hints more recently so I'd love his input.  Needless to say, happy to implement if it's a go.

**Comment by bwilkerson** [comment]
We require that hints have zero false positives, and it isn't clear to me that it's aways wrong (as opposed to just suboptimal) to use `identical` to compare to `null`, even if we were to limit that to conditions where promotion would otherwise have occurred.

I wouldn't have any problem making it a lint.

**Comment by stereotype441** [comment]
Fix is out for review: https://dart-review.googlesource.com/c/sdk/+/174760.
This will cause one warning in Google3, so I'm planning to first land https://github.com/google/built_collection.dart/pull/222 to avoid an internal build failure.

**Comment by stereotype441** [comment]
Fixed in 6a097edc48d9ec20da9d6e6b586b37b63eb05812.
