### ISSUE TITLE
Create alias to the current file

### ISSUE THREAD

**Issue by feinstein** [dart-lang/language#1234]
I describe my problem [here](https://stackoverflow.com/questions/63999112/dart-name-collision-resolution/63999533), basically, I have a file in Dart that looks like this:

```dart
library myLibrary;

bool myFunction(String s) => s == null;

extension StringExtensions on String {
  bool get myFunction=> myFunction(this);
}
```

Where I want to add extensions to previous existing functions, with the same name.

The Dart compiler complains about this, as it can't see the outer `myFunction()` name, just the getter, inside `StringExtensions`.

I would like to suggest a feature were we could alias the current file, maybe using `library myLibrary as a;` so then we could use `a` for fixing name collisions.

**Comment by munificent** [comment]
Yeah, I think what @feinstein is requesting here is almost exactly supported by having a library import itself with a prefix, so I think this is safe to close. @feinstein, let me know if you disagree and we can re-open.

**Comment by feinstein** [comment]
Agreed. It's neat to be able to import the file itself, I thought this would make a circular reference. 

Thanks guys.

**Comment by feinstein** [comment]
(And I just realized this was issue 1234 😅)
