### ISSUE TITLE
The compiler could have better inference on types by previous if()

### ISSUE THREAD

**Issue by feinstein** [dart-lang/language#1243]
Consider this code:

```dart
void main() {
  f<Data>(Data()..id = 'id'..name = 'name');
}

void f<T>(T value) {
  if (value is! Identifiable) {
    throw ArgumentError();
  }
  
  print(value.id); // compiler error here!
}

class Identifiable {
  String id;
}

class Data implements Identifiable {
  String id;
  String name;
}
```

In the line `if (value is! Identifiable) {` the compiler should know that any `T` that's not an `Identifiable` will be rejected, as there's an exception being thrown there (same would go for an `assert`). This way I could use `print(value.id);` without the compiler complaining that `id` doesn't belong to `value`.

This code works though:

```dart
if (value is Identifiable) {
  print(value.id);
}
```

So the functionality is already there, it could just be improved.

**Comment by lrhn** [comment]
Good news. We are doing *exactly* that as part of the Null Safety language update.
You can preview it at https://nullafety.dartpad.dev/

**Comment by feinstein** [comment]
@lrhn awesome! Can't wait for the release!
