### ISSUE TITLE
[Request] New enhancement for spread operator

### ISSUE THREAD

**Issue by ressanoid** [dart-lang/language#1253]
Greetings 

I'm looking into dartpad and trying the spread operator in some flutter project and I'm trying this below code
```
void main() {
List<int> s = [0,1,3];
  List<String> sd = ["a","b","c","d"];
  print(sd[...s]);
}
```

what I want to do is instead of looping through all the elements I want to get the  sd[0] , sd[1], sd[3] values to be printed

don't know if that's a thing yet in dart but I would appreciate if it's there.

what I did so far to make it happen is this

```
void main() {
  List<int> s = [0, 1, 3];
  List<String> sd = ["a", "b", "c", "d"];
  List<String> temp = [];
  print(sd.asMap().keys.map((k){
    
    if(s.contains(k)){
     temp.add(sd[k]);      
    }else{     
      //skip value
    }
/*I made this extra step toSet().toList() to remove duplicates
what I want is to remove the null values so as a work around I
made temp with the same type to hold the values then print it out*/
  }).toSet().toList()); 
  print(temp);
}
```

,,,,,,,,
Output
[null]
[a, b, d]
,,,,,,,

Thanks 👍

**Comment by munificent** [comment]
I concur with Lasse. It's an interesting idea, but I think of too limited use.
