### ISSUE TITLE
[NNBD] Provide a way to check if a type is nullable

### ISSUE THREAD

**Issue by pedromassango** [dart-lang/language#1258]
I'm not sure if this currently exist but I didn't found anything by looking at the docs. Also not sure if here is the right place for this proposal!

In Kotlin we are able to check whether a type is nullable or not. 
Wondering if currently there is a way of doing that and if not we can consider this as a proposal.

In Kotlin we can achieve this by using reflections:
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/-k-type/is-marked-nullable.html

We can have [TypeMirror](https://api.dart.dev/stable/2.10.1/dart-mirrors/TypeMirror-class.html).`isNullable` or `isMarkedNullable` which is `true` if the type was declared with a question mark (nullable) or `false` otherwise.

**Comment by leafpetersen** [comment]
If I understand correctly, you're asking about reflective support in dart:mirrors for nullable types?  Note that for non-reflective uses `null is T` works for this.

**Comment by pedromassango** [comment]
> null is T

@leafpetersen  what if I want to check an actual property?

```dart

String? foo;

// somewhere in my code


if (foo.isNullable) {
  ...
}
```

I actually need this to build a linter related to nullable return types. See https://github.com/dart-lang/linter/issues/2352.

Cc @kevmoo

**Comment by leafpetersen** [comment]
Lints are generally written using the analyzer APIs, which is more like a compiler model than a code generation model.  I'm not sure what you're looking for here, but I don't think this is a language feature request.  Perhaps follow up in the lint issue?
