### ISSUE TITLE
Nullable return types and async, async* and sync* functions

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#1262]
The analyzer currently accepts the following code in a null safety enabled library:
```
Stream<int>? f() async* {}
```

My understanding is that the `async*` modifier will guarantee that a non-null stream is returned. Is the analyzer's behavior correct? If so, is there any value to allowing a nullable return type in this case? If there's no value in allowing it, should the specification explicitly specify this error or should we have a hint in the analyzer for this case?

**Comment by lrhn** [comment]
The behavior is correct. A nullable `Stream<int>?` is a valid return type for a function which returns either a `Stream<int>` or `null`.
It's just as correct as `Stream<int>? f() => Stream<int>.empty();` or `int? g() => 0;`.

Whether there is a value depends on which function type you are trying to satisfy. If you want your class to have `Stream<int>? f()` as a member signature, then that's what you have to write.
You can add a hint, but it can cause false positives if the type is used for anything else (like subclassing or propagated to somewhere else using inference).

**Comment by bwilkerson** [comment]
Thanks. I had forgotten the subclassing case. That argues strongly against a hint.
