### ISSUE TITLE
Named parameter with default value, with different names in the constructor and class body

### ISSUE THREAD

**Issue by mapokapo** [dart-lang/language#1266]
_**Disclaimer:** This issue is related to Flutter, but I am adding it to the dart-lang repository as I find this problem more closely related to the actual language, not Flutter_

### The problem

In Flutter, suppose we have a class as follows:
```
class MyWidget extends StatelessWidget { // Could also be StatefulWidget
  final String _name;
  final bool _flag;

  MyWidget(this.name);
}
```

Now, suppose we want to make the `_flag` property assigned using the shorthand named parameter assignment syntax, but with a default value of `true`.
If we try to do something like this:
```
MyWidget(this.name, { this._flag = true }):
```
there are 2 problems:

1. Flutter will complain that named parameters mustn't start with an underscore (`_`), but if we ignore that warning,
2. The way to initialize `MyWidget` would be `MyWidget("Test name", _flag: false)` which is ugly because of the underscore.
AFAIK, there is no way to solve this. A simple way to bind a parameter named `flag` in the constructor to a property named `_flag` is necessary.

To fix this, you might try doing something like this:
```
class MyWidget extends StatelessWidget {
  final String _name;
  bool _flag;

  MyWidget(this.name, { bool flag = true }) {
    this._flag = flag;
  }
}
```
but there are also problems with this approach:

1. Flutter will complain about the `_flag` property not being `final` due to `MyWidget` extending `StatelessWidget`, which is immutable, and
2. Requires a constructor body for what will oftentimes be the only named property with a default value in the entire constructor/class

I haven't found any resources regarding this problem after searching on Google, so I'm making this issue for both myself and others that stumble into this.

**Comment by toysonlocation** [comment]
Would this work?

```
class MyWidget extends StatelessWidget {
  final String _name;
  bool _flag;

  MyWidget(name, {bool flag = true}) : _name = name, _flag = flag; 
}
```

**Comment by lrhn** [comment]
Yes, the initializer list is what you'd use for this problem.

The `this.foo` constructor parameter is called an "initializing formal parameter", but it can be seen as a shorthand for a normal parameter and an initializer list entry. That is:
```dart
class C {
  int foo;
  C(this.foo);
}
```
is mostly equivalent to
```dart
class C {
  int foo;
  C(final int foo) : foo = foo; // aka `: this.foo = foo;`
}
```
You can use the initializing formal as a shorthand when the parameter has the same name as the field it's going to initialize.

(There are some subtle differences when the constructor has a body, because `this.foo` does not introduce a variable which is visible in the body, but `final int foo` does. It rarely matters.)

**Comment by mapokapo** [comment]
I suppose an initializer list might work as a way to assign the  `this._flag` property to the supplied named parameter `flag`
