### ISSUE TITLE
immutable keyword for classes 

### ISSUE THREAD

**Issue by moneer-muntazah** [dart-lang/language#1269]
Hello everyone,

I'm working on a big flutter application, and I have a lot of models that look like this:

```dart
import 'package:flutter/foundation.dart';

@immutable
class Address {
  final String id;
  final String firstName;
  final String lastName;
  final String email;
  final String phoneNumber;
  final String country;
  final String state;
  final String city;
  final String zipCode;
  final String street;
  final List<String> streetList;
  final String county;
  final String district;
  final String cardNumber;
  Address(
      {this.id, this.firstName,
      this.lastName,
      this.email,
      this.street,
      this.streetList,
      this.city,
      this.state,
      this.country,
      this.district,
      this.phoneNumber,
      this.zipCode,
      this.county,
      this.cardNumber});
}
```

is it possible to have an immutable key word like so:
 ```dart
immutable class Address {
  String id;
  String firstName;
  String lastName;
  String email;
  String phoneNumber;
  String country;
  String state;
  String city;
  String zipCode;
  String street;
  List<String> streetList;
  String county;
  String district;
  String cardNumber;
}
```

Such that I don't have to write the constructor, or final on each property.

I realize that I could cut down the boilerplate by listing similar types in one line, but in practice, I have annotations on my
properties so I can't do that.

Thank you all :)

**Comment by lrhn** [comment]
It's definitely possible. I think this is actually pretty close to "data classes" (#314), so I'll close it as a duplicate.
Might also be supported by something like #698. The feature-set is definitely on the table, the specific design is likely to be more general than just immutability.
