### ISSUE TITLE
If-null Expressions evaluate both sides, but should not

### ISSUE THREAD

**Issue by SteveAlexander** [dart-lang/language#1270]
The language spec version 2.2 says:

> 16.25 If-null Expressions
> 
> An *if-null expression* evaluates an expression and if the result is the null
> object (16.4), evaluates another.
> `<ifNullExpression> ::= <logicalOrExpression> (‘??’ <logicalOrExpression>)*`
> Evaluation of an if-null expression *e* of the form *e1* `??` *e2* proceeds as follows:
> Evaluate *e1* to an object *o*. If *o* is not the null object (16.4), then *e* evaluates
> to *o*. Otherwise evaluate *e2* to an object *r*, and then *e* evaluates to *r*.
> The static type of *e* is the least upper bound (19.10.2) of the static type of
> *e1* and the static type of *e2*.

Reading this, I would expect *e2* to remain unevaluated if *e1* is null.

To give a specific example, I would expect the following program would output `X` and `null`. It does not — it outputs `X` and `Unhandled exception: NoSuchMethodError: The method 'toUpperCase' was called on null.`.

```dart
void main() {
  String x = "x";
  String y = null;
  print(x ?? x.toUpperCase());
  print(y ?? y.toUpperCase());
}
```

Intuitively, I would expect `x ?? y` to be equivalent to `x == null ? null : y`. The following program shows this is not so.

```dart
void main() {
  String y = null;
  print(y == null ? null : y.toUpperCase());
  print(y ?? y.toUpperCase());
}
```

I would expect this to output `null` and `null`. It does not — instead it outputs `null` and `Unhandled exception:
NoSuchMethodError: The method 'toUpperCase' was called on null.`

I am running the examples on Dart SDK version 2.10.2.

**Comment by SteveAlexander** [comment]
Obviously, this is a contrived example, in that one could write

```dart
print(y?.toUpperCase());
```

However, I came across this working on some Flutter code, something like:

```dart
return SomeWidget(
  thing: y ?? SomeOtherWidget(y)
);
```

In this case, `SomeOtherWidget` doesn't like being constructed with a null, and also, why should the runtime spend the extra cycles trying to make it?

**Comment by eernstg** [comment]
>  I would expect `e2` to remain unevaluated if `e1` is null.

That would be non-null: The point is that `??` allows us to provide `e2` as an "alternative" value which will be used in case `e1` is null.

**Comment by SteveAlexander** [comment]
You're right, I have this exactly backwards :-)
