### ISSUE TITLE
Make ?. short-circuit.

### ISSUE THREAD

**Issue by feinstein** [dart-lang/language#1273]
Right now if I have a long chain of calls, where one of the objects can be `null`, I have to use `?.` for all of the calls, e.g.:

```dart
initialValue: widget.hotel?.telephones?.entries
                          ?.map((entry) => Telephone(entry.key, entry.value))
                          ?.toList(),
```

It would be nice if `?.` could just "short-circuit", that meaning if we used one `?.`, from that point to the right everything should be considered as if it was using `?.` as everything there could be `null` at any point.

IMO if a dev placed one `?.` he understands his value could be `null` from that point forward.

**Comment by leafpetersen** [comment]
This [has been implemented](https://dart.dev/null-safety/understanding-null-safety#smarter-null-aware-methods) as part of the upcoming null safety release, which will roll out soon as an opt in language change.

**Comment by feinstein** [comment]
Oh, great to know!
