### ISSUE TITLE
Records: expose named/optional fields through an extension getter instead of a static method

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#1275]
This was probably considered, but it might be nice to expose these static methods:

```dart
abstract class Record {
  static Iterable<Object?> positionalFields(Record record);
  static Map<Symbol, Object?> namedFields(Record record);
}
```

Instead as an extension on the Record class:

```dart
extension RecordInfo on Record {
  external Iterable<Object?> get positionalFields;
  external Map<Symbol, Object?> get namedFields;
}
```

This would be easier use, `myRecord.positionalFields` vs `Record.positionalFields(myRecord)`, and it would prevent grabbing a tearoff of these methods.

One bonus of preventing a tearoff is that the compilers should be able to easily know exactly where and how these getters are invoked (and on what record types), and potentially optimize/treeshake better with that knowledge.

**Comment by munificent** [comment]
> This would be easier use, `myRecord.positionalFields` vs `Record.positionalFields(myRecord)`, and it would prevent grabbing a tearoff of these methods.

You can tear off extension methods too, so I don't think this would buy us anything.

**Comment by jakemac53** [comment]
> You can tear off extension methods too, so I don't think this would buy us anything.

But we can make it a getter, which afaik you can't tear off?

**Comment by munificent** [comment]
Ah, right. I could be wrong, but I don't *think* that buys us much in terms of optimization affordances.

**Comment by jakemac53** [comment]
The thinking is that we would know exactly where all the invocations of this method are, and could potentially optimize away all the metadata required to power this feature when it isn't used.

You could still definitely circumvent this though by calling these getters on something typed `Record` or `dynamic` etc.
