### ISSUE TITLE
Provide a contravariant `is`-like operator

### ISSUE THREAD

**Issue by mateusfccp** [dart-lang/language#1280]
## Motivation

When using the `is` operator with generic types, the operator considers the types covariantly. This is the expected behavior in most cases.

However, there are times that we may want to check covariantly.

Example:
```dart
import 'package:test/test.dart';

class Superclass<T> {
  final T _value;

  const Superclass(this._value);
}

abstract class Sumtype {}

class Variant implements Sumtype {
  const Variant();
}

class AnotherVariant implements Sumtype {
  const AnotherVariant();
}

Superclass<Sumtype> foo() => const Superclass(Variant());

void main() {
  final bar = foo();
  print(bar is Superclass<Variant>);
}
```

In this case, although my `foo()` function could return `Variant` or `AnotherVariant`, as both are subtypes of `Sumtype`, the `is` operator will always check against the supertype `Sumtype`, which will always result in `false`.

## Proposal

This may be related to #524, but #524 will only allow variance declaration on classes.

I propose it to be extended so one may be able to explicitly check covariantly with `is`. For example:

```dart
void main() {
  final bar = foo();
  print(bar is Superclass<contravariant Variant>);
}
```

Or any other syntax, as long as it is possible.

**Comment by eernstg** [comment]
The example works as if you had written `const Superclass<Sumtype>(Variant())`, because inference gives priority to the context type (here: the return type of `foo`).

So it's actually not the `is` operator that checks against anything other that what is written, it is the object returned from `foo` which has the declared return type rather than the type `Subclass<Variant>` that it could have had if the returned expression had been evaluated in a different context (e.g., without a context type).

If you write the type argument explicitly, as in `const Superclass<Variant>(Variant())`, then the program prints 'true'.

I think you may then not need any special variants of `is`.

**Comment by mateusfccp** [comment]
@eernstg Thanks for your answer.

I know that by explicitly returning `Superclass<Variant>(Variant())` instead of `Superclass(Variant())` it would print `true`. This was just a minimal example, but I think it would be beneficial to be possible to contravariantly check for type, so I opened this request.

But I also understand if the team finds it to be an unnecessary feature.

**Comment by eernstg** [comment]
If you want `bar is Superclass<contravariant Variant>` to evaluate to true if `bar` is an object with dynamic type `T` that implements `Superclass<S>` for some `S` such that `Variant <: S` then there is no immediate way to get the same thing with existing constructs, and it is perhaps not even possible without reflection. (I'm assuming Dart of today, that is, class type parameters are always covariant.)

But even if you are able to determine that a given object has a dynamic type with that property, you wouldn't be able to use it for anything other than whatever you could do with a `Superclass<Object>` (or `Superclass<Object?>`, with null safety). So it's not likely to be very useful to extend the type system to include that kind of type.

Of course, it might still be useful for reasons that have nothing to do with the statically known interface. Is there a situation where it would be helpful to have the knowledge that is implied?

```dart
if (bar is Superclass<contravariant Variant>) {
  ... // What extra useful knowledge do we have here, and how would it be used?
}
```

**Comment by mateusfccp** [comment]
I came across this problem when testing, I needed to test that a function with a given argument would return a specific subtype of a `Sumtype`. I don't know of another case that would benefit from this, tho.
