### ISSUE TITLE
feature: Kotlin like extension properties

### ISSUE THREAD

**Issue by quanghd96** [dart-lang/language#1286]
Extension properties is very useful and convenient. Can you develop it?
https://kotlinlang.org/docs/reference/extensions.html#extension-properties

**Comment by leafpetersen** [comment]
Can you expand on what you are asking for?  Dart supports extension getters and setters (just as kotlin does), and does not support extension fields (which I believe kotlin also does not).  Example:

```dart
extension E on int {
  int get twice => 2*this;
}

void main() {
  print(3.twice);
}
```
