### ISSUE TITLE
Should override checks for mixed-in abstract members be omitted?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1287]
Consider the following library:

```dart
mixin M1 {
  void m();
}

abstract class A {
  void m();
}

mixin M2 implements A {}

class C {
  void m([arg]) {}
}

class D1 = C with M1; // Error.
class D2 = C with A; // Error.
class D3 = C with M2; // OK.
```

The code illustrates that if we have a mixin like `M1` with an abstract declaration, we get a compile-time error when that mixin is mixed-in with a class where the interface already has a more specific signature for the given member.

Concretely, `void m()` is an incorrect override error when `M1` is mixed-in with `C` because `C` has the member signature `void m([dynamic])` already.

The mixin derived from `A` works similarly.

However, the mixin `M2` and class `D3` illustrate that this error can be eliminated by moving the offending declaration from the mixin into a superinterface.

Note that the error is not required, because an abstract declaration does not participate in overriding. It is sufficient to treat it the same way as a member signature which is contributed by a superinterface.

Hence, we could omit the override error for abstract declarations, such that applying both `M1` or `M2` to `C` would work.

The work-around (of moving the abstract declaration into a superinterface) is of course available, but it should be applied to the mixin in order to allow an unknown and extensible set of clients to use it. This favors a style where mixins never have any abstract members: Abstract declarations should always be moved to some superinterface (e.g., an abstract class which was created just for this purpose), such that no mixin application will have any of these spurious override violation errors.

We might as well eliminate those errors proactively in the language, and thus allow mixin authors to freely add abstract declarations to mixins as needed.

@munificent, @lrhn, @natebosch, @jakemac53, @leafpetersen, @stereotype441, WDYT?

**Comment by stereotype441** [comment]
Seems reasonable to me.  I use the pattern of adding abstract methods to a mixin a lot, and I have always thought of it as telling the compiler "whatever class this gets mixed into, had better accept the following call".  Although it's never come up for me in practice, I don't believe I would ever wanted an error if the class it gets mixed into is *more* accepting than required.

**Comment by eernstg** [comment]
Closing this issue as a duplicate of #1288. @stereotype441, I copied your comment above into #1288 such that it doesn't get lost.
