### ISSUE TITLE
Records: Should record positional and named fields be allowed to intermix?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1304]
[This proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/records-feature-specification.md) specifies a syntax which segregates named and positional fields in records.  Is this choice deliberate?  Why?  For argument lists, it's been a strong request to allow them to be mixed, so why not do so from the start in records (and maybe relax the restriction on argument lists at the same time?).

**Comment by lrhn** [comment]
Hear, hear. 
For tuple types it makes sense to preserve the current parameter list type format, but we should allow named-arguments anywhere for argument lists *and* tuples.

**Comment by munificent** [comment]
Good call. Done.
