### ISSUE TITLE
Records: Consider replacing `DestructureN` with `Destructure<T extends Record>`

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1310]
[This proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/records-feature-specification.md) proposes a set of nominal destructuring interfaces that classes can implemented, and some records implement.  These interfaces take the form `DestructureN<T0, ..., TN>` where `N` is the number of positional fields, and `Ti` is the type of the ith field.  The interface defines `N` getters named `field0`, ..., `fieldN`.

Instead of defining this as a set of interfaces, why not define this as an injection into the tuple type?  That is, define a single interface:

```
abstract class Destructure<T extends Record> {
  T get destructure;
}
```

Every record of type `T` now implements `Destructure<T>` simply by returning itself.  Any class can implement `Destructure<T>` simply by providing a getter which maps into the appropriate record type.

**Comment by munificent** [comment]
I considered this but I worried about the performance overhead of having to copy on destructuring. But if you're not worried about that, I'm not either. We do essentially have the overhead of allocating an Iterator on every for-in, so this is arguably no worse.

For positional fields, I like your suggestion. For named fields, though, I think it would be useful if all classes could implicitly be used in named destructuring just by desugaring to getter calls on the underlying instance without having to explicitly opt in at the class declaration. Also, I wouldn't want classes to waste cycles creating massive records with every named field someone *might* want to access, including some that may be slow to calculate. The nice thing about desugaring named field destructuring to getter calls on the underlying instance is that you only compute the fields the user actually requests.

We could perhaps say that destructuring an object works like:

1. If the object is a real record type, do some built-in primitive destructuring.
2. Else, if it's a user defined class:
    1. If at least one positional field is being destructured and the class does not implement `Destructure<T>` for some record type R, compile-time error.
    2. If the number of positional fields being destructured does not match the positional field arity of R, compile-time error.
    3. Call `destructure` on the object, yielding value `r`.
    4. Extract the positional fields.
    5. For each named field being destructured:
        1. If R declares a field with that name, access it.
        2. Else, call the corresponding getter on the original object.

The last two are the interesting bits. They would let a class explicitly expose named fields to be destructured if the class wants but any uknown names fallback to getters.

Thoughts?

**Comment by leafpetersen** [comment]
> I considered this but I worried about the performance overhead of having to copy on destructuring. But if you're not worried about that, I'm not either. We do essentially have the overhead of allocating an Iterator on every for-in, so this is arguably no worse.

It's hard to say without knowing more about what you intend these interfaces to be for.  In the polymorphic case, I'm actually not sure that allocating a short lived object to return k fields will be significantly slower than k polymorphic virtual getter calls.  And in the monomorphic case, we should expect (hope) that the allocation will be eliminated by inlining.

**Comment by leafpetersen** [comment]
> 5\. For each named field being destructured:
>     
>     1. If R declares a field with that name, access it.
>     2. Else, call the corresponding getter on the original object.

Yes, this seems plausible.

**Comment by leafpetersen** [comment]
> The last two are the interesting bits. They would let a class explicitly expose named fields to be destructured if the class wants but any unknown names fallback to getters.

Thinking about this a bit more, one of the things I like about this is that helps to address a concern I have with the `Destructure` interface, which is that I don't think it really works well with subclassing.  If I have a `Point`, I want to be able to destructure it into `x` and `y`, but if I subclass it to `ColorPoint`, then I also want to be able to destructure the `color` field.  But I can't make `ColorPoint` implement `Destructure<int, int, int>` if `Point` implements `Destructure<int, int>`.

I do still think this might be a bit of a difficult point for this, and I have to admit I'm still not clear how central you intend these interfaces to be to the eventual design.

**Comment by tatumizer** [comment]
I'm thinking of this: what if someone writes:
```
class Foo implements (int, int, {bar: String}) {
   int get field0 => 0;
   int get field1 => 1;
   String bar = "Hello"; 
}
var (x, y, {bar}) = Foo();
```
The User will expect this program to work. If it doesn't, explaining the reason would be difficult. Indeed, the type is structural; all the fields forming the structure are defined... Then why doesn't it work?

**Comment by munificent** [comment]
> Thinking about this a bit more, one of the things I like about this is that helps to address a concern I have with the `Destructure` interface, which is that I don't think it really works well with subclassing. If I have a `Point`, I want to be able to destructure it into `x` and `y`, but if I subclass it to `ColorPoint`, then I also want to be able to destructure the `color` field. But I can't make `ColorPoint` implement `Destructure<int, int, int>` if `Point` implements `Destructure<int, int>`.

It can as long as it doesn't need to change the types of the fields already implemented by the Point class. (In other words, it generally works fine as long as its adding new fields to the end of the tuple). Dart allows this now:

```dart
abstract class Destructure2<T0, T1> {
  T0 get field0;
  T1 get field1;
}

abstract class Destructure3<T0, T1, T2> {
  T0 get field0;
  T1 get field1;
  T2 get field2;
}

class Point implements Destructure2<int, int> {
  final int x, y;

  Point(this.x, this.y);

  int get field0 => x;
  int get field1 => y;
}

class ColorPoint extends Point implements Destructure3<int, int, int> {
  final int c;

  ColorPoint(int x, int y, this.c) : super(x, y);

  int get field2 => c;
}

main() {
  Destructure3<int, int, int> d = ColorPoint(1, 2, 3);
}
```

I *think* this behavior is intended. My recollection is that a class can implement multiple interfaces that have overlapping members as long as the members are all type compatible with each other.

This actually works better using getters than it would with having a single `T get destructure` member because then Point and ColorPoint would both try to implement that same member but with different incompatible types for T.

> I do still think this might be a bit of a difficult point for this, and I have to admit I'm still not clear how central you intend these interfaces to be to the eventual design.

Not very central. It's basically just the protocol that pattern matching desugars to. Once I have pattern matching written down a little better, we can circle back on this.

**Comment by leafpetersen** [comment]
> I _think_ this behavior is intended. My recollection is that a class can implement multiple interfaces that have overlapping members as long as the members are all type compatible with each other.

Ah right - I'm not sure why I was thinking they would collide.  I do think there are still concerns with compositionality though.  If you have two things that each implement `Destructure2` at unrelated types and then you bring them together via `implements` or `with`, you end up with an error.

**Comment by lrhn** [comment]
That's also true if you have something implementing a `Point<T>` class at two different types.
Maybe we can loosen that when we get variance, so something implementing both `Foo<in int>` and `Foo<in double>` is OK if it also implements `Foo<in num>`, or both `Bar<out int>` and `Bar<out num>` because the former is always substitutable for the latter.
Or maybe we can't. We'll see.

**Comment by leafpetersen** [comment]
> That's also true if you have something implementing a `Point<T>` class at two different types.

Yes, and maybe this is no more than that, but I'm not sure.  If this ends up being a key part of using classes in interesting ways, then I can imagine it being very standard for a class to implement `Destructure`, in a way that implementing `Point` is not.  But maybe it's not an issue - again, it comes down to how central the `Destructure` interfaces end up being, which it sounds like perhaps not very.

**Comment by munificent** [comment]
Closing this since I've removed the `Destructure_n_` interfaces completely in https://github.com/dart-lang/language/pull/2230. At some point, if we want to support user-defined positional destructuring, this question may come back, but I suspect that will come in a later version of the feature.
