### ISSUE TITLE
Problem: IDE doesn't give much help for the return type of anonymous Function type arguments

### ISSUE THREAD

**Issue by natebosch** [dart-lang/language#133]
```dart
void doStuff(int Function(String)) {}

void main() {
  doStuff((a) {});
}
```

Here I have passed a `Null Function(String)` to something expecting an `int Function(String)` and I don't get any static help. There are a few aspects that are potentially confusing to me:

- As a user I expect that what I had written was a `void Function(String)` instead of `Null Function(String)` since I don't typically write functions with a `Null` return type.
- I expect that downward inference would have pushed the type `int Function(String)` to that closure, but it doesn't. In dart2js at least the runtime type is `Null Function(String)`. It _does_ do downward inference on argument types (It's not `Null Function(dynamic)`), but not the return type.

This is likely going to have an impact on NNBD when `Null Function(String)` will stop being a subtype of `int Function(String)`, so it may either make this a non-issue, or could cause additional pain during the migration.

Ideally I'd like a hint from the analyzer that what I had written will not work if `doStuff` expected to be able to use a return value.

**Comment by srawlins** [comment]
Looks like https://github.com/dart-lang/sdk/issues/28233

**Comment by jmesserly** [comment]
yup. I landed a fix, but it broke too much internal code and was rolled back. I didn't understand why a hint broke things, or why my fix was rolled back, so I left it for someone that understands it better.

**Comment by natebosch** [comment]
With null safety we do get help with this.

https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=body_might_complete_normally#body_might_complete_normally
