### ISSUE TITLE
\ matches in \w only Regex

### ISSUE THREAD

**Issue by CoderUni** [dart-lang/language#1340]
My output prints `match` when I run the function below. The regex doesn't match when I run it in regex validation sites like [regex101](https://regex101.com/). The `\` in the text shouldn't match with the Regex: `^[\w]+$`

```dart
void main() {
  String text = "aB\c123";
  if (RegExp(r"^[\w]+$").hasMatch(text)) {
    print("match");
  } else {
    print("does not match");
  }
}
```

**Comment by mateusfccp** [comment]
The `\c` in the `text` variable is an escaped character.

If you use `r"aB\c123"` as the value of text or `"aB\\c123"` you will get the expected result.
