### ISSUE TITLE
Dart core improvement

### ISSUE THREAD

**Issue by halimpuckjava** [dart-lang/language#1342]
hi

1.  introduce Singleton 
2.  destruction

**Comment by mateusfccp** [comment]
Would you care to explain in details what is your proposal?

Singleton type already exists, which is `Null`.

Singleton pattern, although I don't recommend, can be easily done by making a class with a static single instance. Example: https://stackoverflow.com/questions/12649573/how-do-you-build-a-singleton-in-dart

**Comment by munificent** [comment]
I'm going to close this because there isn't really much to go on here.
