### ISSUE TITLE
Does the analyzer need `--sound-null-safety` / `--no-sound-null-safety`?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1346]
It seems likely that we need to adjust the definition of canonicalization of the values of constant expressions, or we need to allow the analyzer to take the execution modes with sound null checking (`--sound-null-safety`) vs. unsound null checking (`--no-sound-null-safety`) into account.

### Issue

The static analysis of Dart programs with null safety is mostly identical for the two execution modes. However, there is a difference in the treatment of constant expressions: With unsound null checking, the type arguments passed to collection literals and constructor invocations [are treated](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#const-evaluation-and-canonicalization) as legacy types, and with sound null checking they are treated as the given types without any transformations. This makes a difference for canonicalization:

```dart
const xs = <Never>[];
const ys = <Null>[];
const z = identical(xs, ys)? 1 ~/ 0 : 0;

void main() {}
```

This program is accepted with no errors by `dartanalyzer` (commit a9d212b94aa73472824f4218a567a8e004575112 as well as 2.12.0-96.0.dev). It is also accepted by `dart` (same versions) with sound null checking, but it encounters a compile-time error with unsound null checking. This is consistent with the fact that the type `Never` is considered to denote the same type as `Null` when encountered in a legacy library (it does not mean `Never*`).

## Possible resolution

If it is considered impractical to let the analyzer have such modes then we'd need to make sure that canonicalization never differs with sound and unsound null checking.

The only situation where we have the choice is with an entry point where every directly or indirectly imported library enables null safety (that is, in a purely null safe program): With a mixed-version program we can only use unsound null checking.

So when do types `S` and `T` differ, but when "treated as a legacy type" they do not differ?

I believe that it may be sufficient to say that "`T` treated as a legacy type" denotes the type `S` where:

- If `T` is atomic then `S` is `T*`.
- If `T` is `FutureOr<T1>` then `S` is `FutureOr<S1>*` where `S1` is the result of treating `T1` as a legacy type.
- If `T` is a parameterized type `T0<T1, .. Tk>` then `S` is `T0<S1, .. Sk>*` where `Sj` is the result of treating `Tj` as a legacy type, `1 <= j <= k`.
- (Similar structural rules for type variables, intersections, function types, etc.)

So we're adding `*` everywhere, but we're _not_ treating `Never` as another name for `Null`. 

This means that `<Never>[]` in legacy code and `<Never>[]` in code with null safety will _not_ be canonicalized to the same object.

But when `Never` does not occur in two types `S`, in opted-in code, and `T`, in legacy code, and `S` and `T` are spelled identically (and occur in equivalent binding environments, such that `SomeName` doesn't resolve to two distinct declarations), then the meaning of `T` and the result of treating `S` as a legacy type are identical. This ensures that we'll have the desired stability of canonicalization in mixed-version programs, except for types containing `Never`.

At the same time, when `S` and `T` occur in a purely null safe program, in equivalent binding environments, it is not possible for them to become the same type when treated as legacy types, unless they are already the same type.

This is trivially true when no normalization is applied and the resulting types are compared for equality in a manner that we usually call 'textual'.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by leafpetersen** [comment]
I commented here: https://github.com/dart-lang/sdk/issues/44246 .  On the subject of how to deal with the lack of modality in the analyzer, there must already be some infidelity in the analyzer const evaluation from the lack of this.  e.g. `const <int?>[] is List<int>` returns false in the analyzer regardless of mode.  We may have to accept a similar level of infidelity here.

**Comment by eernstg** [comment]
> there must already be some infidelity in the analyzer const evaluation ...
> `const <int?>[] is List<int>` returns false in the analyzer regardless of mode

This would continue to hold if we interpret 'treated as legacy types' as an operation that recursively adds `*` to type arguments passed to collection literals and constant object expressions (and does nothing else). In particular, we don't add `*`s to make it `... is List<int*>` (not to mention `... is List<int*>*`, which would be wrong in any case because `null is List<int>` should return false in legacy code).

So I hope that we can actually avoid the infidelity. Granted, it does prevent canonicalization of `const <Never>[]` in legacy code and `const <Never>[]` in opted-in code, but I think avoiding the infidelity would be quite desirable. As an aside, the opted-in code could use `const <Null>[]` in order to canonicalize with some legacy code where `const <Never>[]` or `const <Null>[]` is used.

**Comment by RedBrogdon** [comment]
If the decision made here seems likely to have impact for DartPad, please drop me a line. 😄

**Comment by leafpetersen** [comment]
I have a proposal for how to deal with canonicalization [here](https://github.com/dart-lang/language/pull/1389).  I don't see a way around having different semantics in sound and unsound mode, but I believe that with appropriate pragmatic choices this can be safely ignored in the analyzer. @scheglov we should discuss how exactly you want to tackle this and whether you see any issues.

**Comment by scheglov** [comment]
Sounds good. We can discuss this during our upcoming meeting this Tuesday.

**Comment by eernstg** [comment]
Today, the canonicalization of constants evaluating to reified types or type arguments of constants is specified in the [null safety feature specification](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md).
