### ISSUE TITLE
val instead of final

### ISSUE THREAD

**Issue by pedromassango** [dart-lang/language#135]
In kotlin we use `val` to mark a property as final, would be good if you change `final` to `val` as we already have the `var` keyword that is a brother of `val`.

**Example:**

```
final name = 'Pedro'
var age = 21
```
**We can use in this way:**
```
val name = 'Massango'
var age = 21
```

> _Short form is always better because we type less letters_

**Comment by eernstg** [comment]
Note that this can be considered as a response to the request in #136.
