### ISSUE TITLE
Should const evaluation normalize type arguments?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1350]
Consider the following program:

```dart
import 'dart:async';

const xs = <Object?>[];
const ys = <FutureOr<Object?>?>[];
const z = identical(xs, ys)? 1 ~/ 0 : 0;

void main() {}
```

This program compiles and runs with no errors with `dart` (from commit 74be6670c9b5fff68caec4112f13216031c4b0fc and in version 2.12.0-96.0.dev), both with `--sound-null-safety` and with `--no-sound-null-safety`.

But with the analyzer, a compile-time error is reported:

```
ERROR|COMPILE_TIME_ERROR|CONST_EVAL_THROWS_IDBZE|/usr/local/google/home/eernst/lang/dart/scratch/202012/n008.dart|5|30|6|Evaluation of this constant expression throws an IntegerDivisionByZeroException.
```

This shows that constant evaluation in the analyzer performs [normalization](https://github.com/dart-lang/language/blob/master/resources/type-system/normalization.md) on the type arguments passed to expressions that are subject to constant expression evaluation, but no such normalization takes place in the common front end.

We should decide on which of these behaviors is correct, and ask "the other" implementation to make adjustments.

**Comment by leafpetersen** [comment]
I have proposed to do normalization of type arguments to constant constructors for the purposes of canonicalization [here](https://github.com/dart-lang/language/pull/1389).
