### ISSUE TITLE
Problem: Overriding covariant fields in combination with null safety breaks soundness

### ISSUE THREAD

**Issue by burakemir** [dart-lang/language#1358]
```dart
class Foo {
  covariant double? _zoo = 3.14;
  
  set zoo(covariant double? o) {_zoo = o;}
  double? get zoo => _zoo;
}

class Bar extends Foo {
  @override double _zoo = 2.3;
  @override set zoo(double o) {_zoo = o;}
  double get zoo => _zoo;
}

void main() {
  Foo x = Bar();
  x.zoo = null;  // Accepted, but will break at runtime.
  print("Never reached.");
}
```
Uncaught Error: TypeError: null: type 'JSNull' is not a subtype of type 'double'

https://nullsafety.dartpad.dev/c6ec42e4a1d1d94132a0fc51f61b7365

**Comment by eernstg** [comment]
This is working as intended: The whole purpose of marking a formal parameter `T p` of a method `m` as `covariant` is to allow overriding declarations of `m` to specify a proper subtype of `T` as the type of `p`.

In particular, the parameter of the `zoo` setter in `Bar` has type `double` even though it may be the implementation which is invoked when the static receiver type is `Foo` where the parameter type is `double?`, so it seems safe statically to pass `null`, but it will fail at run time. It would have been a bug (and it would allow us to break the heap invariant) if the assignment were _not_ failing at run time.

You could say that the whole mechanism is then nothing other than a cast:

```dart
class Foo {  
  set zoo(double? o) { /*some implementation*/ }
  double? get zoo => null;
}

class Bar extends Foo {
  set zoo(double? o) { o as Null; /*Rest of implementation*/ }
  double get zoo => 0.0;
}

void main() {
  Foo x = Bar();
  x.zoo = null;  // Accepted, but will also throw.
  print("Never reached.");
}
```

The difference is somewhat subtle: With `covariant` we maintain the invariant that the parameter types are related (so a parameter `p` which is covariant may have a declared type which is a subtype or a supertype of each of its corresponding parameter types in superinterfaces, but it can't be completely unrelated to any of them), so at run time we will perform a downcast or an upcast relative to the statically known type, not a "stupid cast".

Secondly, the covariant parameter type is known at the call site when the receiver type is sufficiently special. This means that the dynamic error will only occur when the dynamic type of the receiver is a proper subtype of the statically known receiver type.

These things won't restore static type safety, of course, but they do make the use of this kind of "extra type checks on a parameter" a bit safer and more predictable than the simple `p as T` at the beginning of the body.

**Comment by burakemir** [comment]
Right, thanks for the explanation. 

I did expect that in general something has to give when using "covariant" and lead to runtime errors, but - not being used to covariant annotation - I somehow didn't realize that the behavior I am seeing is exactly that runtime check.
