### ISSUE TITLE
What is the status of reified generics in methods?

### ISSUE THREAD

**Issue by dmdashenkov** [dart-lang/language#1372]
This doc states that trying to use a generic type as a type literal causes an error if the type is declared in a method.
https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/doc/GENERIC_METHODS.md#using-generic-method-type-parameters
I've navigated to this doc from the [language tour](https://dart.dev/guides/language/language-tour#using-generic-methods).

However, the following code works for me:
```dart
QueryRequest<M> select<M extends GeneratedMessage>() {
    var type = M;
    return QueryRequest._(this, type);
}
```
Tested on:
 - 2.11.0-213.1.beta (beta) (Wed Oct 14 10:49:52 2020 +0200) on "macos_x64";
 - 2.10.4 on Windows x64;
 - 2.10.4 (stable) on "linux_x64".

I cannot find the announcement for the behaviour change anywhere. Is this a glitch or is the doc missing or am I missing something?

**Comment by eernstg** [comment]
Functions in Dart (including instance methods) may declare type parameters, and the actual type arguments are reified at run time, just like other type parameters.

@munificent, `GENERIC_METHODS.md` and `GENERIC_METHOD_COMMENTS.md` seem to describe the situation as of 2016 or so. Can they be marked as obsolete, or perhaps even deleted?

@kwalrath, I think the language tour document has just one link to this directory, namely https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/doc/GENERIC_METHODS.md#using-generic-method-type-parameters. We should remove that link; it is not obvious to me which document is the optimal target for a link at that point.

**Comment by lrhn** [comment]
The unreified function type parameters were a temporary feature during the development of Dart 2.0, where we allowed the syntax before introducing the semantics. It's having features like that which made us introduce language versioning for null safety :)

**Comment by dmdashenkov** [comment]
@eernstg, @lrhn thank you for the clarification.

**Comment by osa1** [comment]
Should this be closed? It seems like the link from the language tour to the outdated documentation has been removed.

**Comment by eernstg** [comment]
I think we can close this. @parlough, @munificent, please reopen if you disagree.
