### ISSUE TITLE
DateTime.add(const Duration(days: 1)) fails for November 1, 2020

### ISSUE THREAD

**Issue by kovalyovi** [dart-lang/language#1373]
I was using [DartPad](https://dartpad.dev) to answer a question on StackOverflow and I was messing with dates and noticed that if you add `Duration(days: 1)` to the November 1, 2020 date (2020-11-01), it adds 23 hours instead of 24. To reproduce just run this code:

```lang-dart
void main() {
  var date = DateTime(2020,10,30);
  
  for (var i = 0; i < 6; i++) {
    print(date.add(Duration(days: i)));  
  }
}
```
The output is as below
```
2020-10-30 00:00:00.000
2020-10-31 00:00:00.000
2020-11-01 00:00:00.000
2020-11-01 23:00:00.000
2020-11-02 23:00:00.000
2020-11-03 23:00:00.000
```

Is it an expected behavior or why it's doing that?

**Comment by kovalyovi** [comment]
Just as an update: the problem is with calculating hours between 1 and 2 
```
void main() {
  var date = DateTime(2020,11,1);
  
  for (var i = 0; i < 4; i++) {
    print('Added hours: $i: ${date.add(Duration(hours: i))}');  
  }
}
```

```
Added hours: 0: 2020-11-01 00:00:00.000
Added hours: 1: 2020-11-01 01:00:00.000
Added hours: 2: 2020-11-01 01:00:00.000
Added hours: 3: 2020-11-01 02:00:00.000
```

**Comment by lrhn** [comment]
Most likely reason: Daylight savings. You are adding 24 hours (`Duration(days: 1)` is the same as `Duration(hours: 24)`), but that day is 25 hours long in your local time zone.

Always use UTC dates if you want to work with calendar dates.

**Comment by kovalyovi** [comment]
@Irhn thank you for the idea. However, when you add `Duration(days: 1)` I guess you assume it will be the next day no matter what (not 24 hours from the previous one) unless the core idea is different...

**Comment by lrhn** [comment]
A `Duration` is a fixed number of milliseconds. It doesn't know about calendar days, or that they differ in length.

**Comment by kovalyovi** [comment]
I see. I guess the `UTC` date is the way to go. Thank you for the clarification and such a quick response!
