### ISSUE TITLE
Late initialized pattern matched variables.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1380]
See [proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#late-and-static-variables-in-pattern-declaration).

The proposal states that a `late` pattern-matched/destructured declaration which introduces more than one variable, is initialized on the first read of any variable.
That doesn't answer what happens if you *assign* to one of the variables.
Example:
```dart
int say(int n) {
  print(n);
  return n;
}

main() {
  late var (a, b) = (say(1), say(2));
  a = 42;
  print("here");
  b; // Does this read make sense?
}
```

I'm tending towards enforcing that all *destructured* variables must/will be `final`.

It's not entirely clear to me what the connection is between variables introduced by destructuring and the "whole".
If you do:
```dart
typedef Point = ({int x, int y});
var Point(x: var x, y: var y) p  = (x: 0, y: 0);
// p is (x:0, y:0), x is 0, y is 0.
x  = 42; // Does this change p?
p = (1, 2); // Does this change x and y?
```

The sanest (IMO) approach is that the declaration introduces three independent variables, and the assignment initializes all three. Later assignments are not destructuring because they are not assigned to the same pattern.

With that, it makes sense that reading a late variable forces its initialization. It doesn't answer what happens if another variable from the same destructuring has been initialized by assignment. 

And if the declaration had been `late var Point(x: var x, y: var y) p = ...`, then assigning to `p` would also not initialize `x` and `y`.
I have no solid solution for this, other than somehow disallowing partial initialization, whether by disallowing assignment entirely, or by not allowing assignment to late variables with an initializer until it has been read (which is different from no-pattern initializers).

**Comment by tatumizer** [comment]
Is this indeed a valid syntax?
```
var ({int x, int y}) (x: var x, y: var y) p  = (x: 0, y: 0);
```
Really?

**Comment by lrhn** [comment]
Not as I read it. The type before the property matchers must be an identifier. That's why I introduced the `typedef`.
(But I've only read it once, there are probably details I'm getting wrong).

**Comment by munificent** [comment]
> The proposal states that a `late` pattern-matched/destructured declaration which introduces more than one variable, is initialized on the first read of any variable.
> That doesn't answer what happens if you _assign_ to one of the variables.

Ah, good point! I think the most useful/flexible behavior is that accessing any *uninitialized* late variable declared in a pattern evaluates the initializer and then initializes all *uninitialized* variables. I'll leave this issue open to discuss and think about that more. We could also simply disallow `late` for pattern variables. It's unlikely to be a very useful combination.

> I'm tending towards enforcing that all _destructured_ variables must/will be `final`.

I think that's too restrictive and unnecessary. Destructured variables are just variables and mutable variables are useful.


> It's not entirely clear to me what the connection is between variables introduced by destructuring and the "whole".
> If you do:
> 
> ```dart
> typedef Point = ({int x, int y});
> var Point(x: var x, y: var y) p  = (x: 0, y: 0);
> // p is (x:0, y:0), x is 0, y is 0.
> x  = 42; // Does this change p? no
> p = (1, 2); // Does this change x and y? no
> ```

This technically isn't supported by the proposal. The syntax doesn't include a way to capture a value in some variable while also destructuring it. There's nothing like Haskell's `@` patterns or F#'s `as` in the proposal. I'm not opposed to it, I just couldn't find a syntax. (Both `@` and `as` already mean other things, for example.)

> The sanest (IMO) approach is that the declaration introduces three independent variables, and the assignment initializes all three. Later assignments are not destructuring because they are not assigned to the same pattern.

Right. We're not adding "references" or anything like that. It's just sugar for declaring variables and initializing them with the result of accessing properties on some object.

> And if the declaration had been `late var Point(x: var x, y: var y) p = ...`, then assigning to `p` would also not initialize `x` and `y`.

Right.

> Is this indeed a valid syntax?
> 
> ```
> var ({int x, int y}) (x: var x, y: var y) p  = (x: 0, y: 0);
> ```
> 
> Really?

No, it's not. You can do:

```dart
var ({int x, int y}) p  = (x: 0, y: 0);
```

Which is just a normal typed variable declaration but with an essentially superfluous `var` before it. And you can do:

```dart
var (x: var x, y: var y)  = (x: 0, y: 0);
```

Which is a record pattern that destructures the two fields to new variables. But you can't munge those two things together.

**Comment by lrhn** [comment]
Even if the above code isn't valid, it's still a problem to have `late` non-`final` declarations.

The proposal *does* allow a `late` non-`final` binder declaration of the form:
```dart
late var (x, y) = (1, 2);
```
It's clear that reading either `x` or `y` will require evaluating the initializer expression and do the destructuring.
However, since it uses `var`, not `final`, it appears to be possible to assign to `x` or `y` before reading the other.
So, assume we do:
```dart
y = 4;
print(x); // prints 1?
print(y); // prints 2 or 4?
```
Will writing to one variable initialize the other? 
That seems impossible because we don't have a value for the other one, but we could force initialization of both, by evaluating the initializer expression first and initializing both variables, just before we do the write to an uninitialized variable.
This would be a new behavior, we don't generally do anything on writes of late variables, and it would mean the initializer is evaluated even if we don't want it to, say for `x = 0; y = 0;`.
So, that seems like a no-go.

So, we *need* to initialize `y` when it is read above, and then *probably* not write to `x` when it has already been assigned to.
That complicates late-init which currently doesn't check before writing to a variable.

All in all, it might be better to disallow `late` for non-`final` declarations.

**Comment by munificent** [comment]
This is addressed now by not allowing patterns in `late` variables, top-level variables, or static fields.
