### ISSUE TITLE
Type checking fails at runtime instead of compile time

### ISSUE THREAD

**Issue by ILAgent** [dart-lang/language#1382]
Given code

    List<int> rawList = [0, 1, 2];
    BuiltList<int> list = rawList.map((n) => n * 2);

compiles successfully but fails at runtime with the error

> type 'MappedListIterable<int, int>' is not a subtype of type
> 'BuiltList<int>'

I don't see any reason why it can't be checked on compile stage.

**Comment by tatumizer** [comment]
Have you tried dart version with null safety?

**Comment by ILAgent** [comment]
Thank you, `implicit-casts: false` moves the error onto compile stage! But IMHO that behaviour should be by default.

**Comment by Cat-sushi** [comment]
[Understanding null safety | Dart](https://dart.dev/null-safety/understanding-null-safety#using-nullable-types "Understanding null safety | Dart")

> So with null safety we are removing implicit downcasts entirely.

**Comment by ILAgent** [comment]
Thank you for information. Hope I'll be able to move my project to null-safety soon.

**Comment by lrhn** [comment]
The behavior is correct and expected prior to null safety, and will be a static error with null safety.
So, "fixed!"
