### ISSUE TITLE
How do I return the generic type T of MyClass<T> ?

### ISSUE THREAD

**Issue by MilesAdamson** [dart-lang/language#1388]
Is such a method possible in dart without mirrors? I cannot use mirrors in flutter

```
Type getGeneric(LoadEntitiesAction action){
  // LoadEntitiesAction might be LoadEntitiesAction<Task>, LoadEntitiesAction<Unit>, ect...
  // if it's LoadEntitiesAction<Unit>, return Unit
  // if it's LoadEntitiesAction<Task>, return Task, ect...
}
```

**Comment by tatumizer** [comment]
```dart
Type getGeneric<T>(List<T> list)=>T;
main() {
  print(getGeneric([1,2])); // int
  print(getGeneric([1.5,2.5])); // double
}
```

**Comment by leafpetersen** [comment]
There are several different things you might be asking here that affect the answer.

As @tatumizer describes above, you can decompose the static type into a runtime type object using inference as described above, but it won't help if you don't have a precise static type for the object (that is, if you have something with static type `LoadEntitiesAction<int>` the approach above will get you `int`, but if you have a `LoadEntitiesAction<dynamic>` it will get you `dynamic`, even if the actual instance is a `LoadEntitiesAction<int>`). 

Do you really just want a `Type` object?  Those aren't very useful.  Or do you want to actually get the runtime type as a type?  If you control the class in question ('LoadEntitiesAction`) in the sense that you can add methods to it, you can do either as follows

```dart
class LoadEntitiesAction<T> ... {
    // Other class methods here....
   Type getGenericAsTypeObject() => T;
   R getGenericAsType<R>(R Function<S>() k) => k<T>();
}
```

Note that for the "type" version we must use an explicit continuation for the computation on the generic type, which is a significant limitation.

If you do not control the class in question, there is no way to get at the generic type as a type, and only limited ability to get at the type as Type object.  For the latter, if there is only a delimited set of concrete runtime types that you care about, then you can just check:

```dart
Type getGeneric(LoadEntitiesAction action){
   if (action is LoadEntitiesAction<Unit>) return Unit;
   if (action is LoadEntitiesAction<Task>) return Task;
}
```

Obviously, this isn't generic in the sense that you have to know the set of types you want to compare against.  Also, be careful with subtype relationships:  if `Task` is a subtype of `Unit`, then the code above will return `Unit` for a `LoadEntitiesAction<Task>` instance.

**Comment by MilesAdamson** [comment]
```
Type getGenericAsTypeObject() => T;
```

Thanks, that was so simple not sure why I couldn't figure it out. I do control `LoadEntitiesAction` so this is all I needed
