### ISSUE TITLE
Async methods in abstract methods

### ISSUE THREAD

**Issue by steeling** [dart-lang/language#1393]
Dart's docs say to use abstract classes as interfaces https://dart.dev/samples#interfaces-and-abstract-classes

However I can't describe an abstract method that is async? This seems like a major flaw. Sure, I can return a Future, but what if I want to explicitly perform and await for other async operations?

**Comment by mateusfccp** [comment]
If you are providing an implementation for the function, you can use `async` normally.

If you are providing a stub function to be implemented, like an interface, you can use `Future`, and then use `async` on the function implementation.

Example:
```dart
abstract class Interface {
  Future<void> function1() async {
    await Future.value(10);
  }

  Future<void> function2();
}

class Extender extends Interface {
  @override
  Future<void> function2() async {
    await Future.value(10);
  }
}

class Implementer implements Interface {
  @override
  Future<void> function1() async {
    await Future.value(10);
  }

  @override
  Future<void> function2() async {
    await Future.value(10);
  }
}
```

**Comment by steeling** [comment]
Ah that makes sense, thanks for explanation!
