### ISSUE TITLE
Binders and matchers and being irrefutable/refutable

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1404]
See [pattern proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#late-and-static-variables-in-pattern-declaration).

The proposal characterizes binders as "irrefutable" and matchers as "refutable" in the sense that binders must be used in places where there is no possible control flow in the non-matching case (other than throwing, which is obviously always possible, but Dart is generally moving away from language features which give no warning at compile-time and throws at run-time).

However, it then has list and map *binders*, even though a collection binder is very much refutable. A pattern of `var [x, y] = list;` cannot match unless the list has length 2 (precisely or at least, depending on the choice of syntax). Similarly for map binders, the static type does not ensure that the binding succeeds, it's like an implicit downcast to a subset of list values.
That makes those unsuitable as a binders, and they should probably be removed. 

This leaves only tuple/record matching as a `declarationBinder`. Which is fair, tuples are generalizations of single values where the static type fully describes the contents, lists and maps are not.

On the other hand, the `_` wildcard matcher is a matcher, not a binder. That means it cannot be used inside a binder, disallowing the otherwise reasonable `var (first, _) = pair;`. It *should* probably be a binder (it's also completely irrefutable, so that matches the description).

(I guess a type matcher can also be irrefutable if the type matches: `var Foo(bar: var bar) = theFoo;` is irrefutable if `theFoo` has static type `Foo`. I can see that being useful in destructuring objects of any type.)

**Comment by lrhn** [comment]
Had a thought on how to generalize patterns a little. Just writing it down for reference.
The idea is to not split into "binders" and "matchers" as separate incompatible categories, just specify that only some patterns are allowed in "binding" contexts, based on recursively not containing refutable patterns (where "type patterns" are considered irrefutable if guaranteed by the static type).

----

```
pattern ::= `_`                                 ## Wildcard **irrefutable**
          | `(` patterns `)`                    ## Record pattern
          | (`var` | `final` | `final`? type) identifier ## Binding **irrefutable**
          | typePattern identifier?             ## Type pattern
          | `this` `.` identifier                      ## Binding pattern only in constructor parameters.
          | typeArgumentPattern? 
               `[` listPatterns? `]`            ## List pattern **refutable**
          | typeArgumentPattern?
               `{` (mapPattern | mapPatterns) `}`
                                                ## Map pattern **refutable**
          | expression                          ## value pattern **refutable**
          
// The `expression` pattern must not start with `[` or `{`.
          
typePattern ::= typeName typeArgumentPattern? propertyMatcher?          
          
patterns ::= pattern (`,` pattern)+

typeArgumentsPattern ::= `<` typePatterns `>`
typePatterns ::= typePattern | typePattern `,` typePatterns
typePattern ::= `var` identifier | type | typeName typeArgumentsPattern
// Ambiguous on `List<int>`, treat as `type`, not `typeName<type>`

listPatterns ::= 
   pattern |                                 ## Single final element
   `...` (`var` | `final`) identifier |      ## Rest binding
   pattern `,` listPatterns                  ## Next element

mapPatterns ::= mapPattern (`,` mapPattern)+
mapPattern ::= constantExpression `:` pattern

propertyMatcher ::= `{` (propertyPattern | propertyPatterns) `}`
propertyPattern ::= identifier `:` pattern
propertyPatterns ::= propertyPattern (`,` propertyPattern)+
```

A pattern is irrefutable if it doesn't contain any refutable (sub-)pattern.

Only an irrefutable record, type or binding pattern can be used in a "declaration" like `pattern = 42;`.

Patterns can be used in binding declarations: `pattern = value;`, parameter declarations, in `is` and `as` expressions and as `case` expressions (where any value must be constant). Maybe even in `catch (pattern)`.

## Examples:

```dart
var x = 42;
var point = (1, 2);
(var x, var y) = point;
class Point { final int x,y; Point({this.x,this.y});}
var cPoint = Point(x: 2, y: 4);
Object o = cPoint;
if (o is Point{x: 2, y: var y} p) { 
  // p is Point, y == 4.
}

z as List{length: 4, first: 1}; // aka z as [_, _, _, 4]
                                   
switch (o) {
  case Point{x: var x, y: var y}: return (x, y);
  case (int x, int y): return (x, y);
  case String s: return parsePoint(s);
}          
if (list is List<List<var T>>) {
  List<T> flatten = [for (var l in list) ...l];
}
```

**Comment by tatumizer** [comment]
```
if (list is List<List<var T>>) {
  List<T> flatten = [for (var l in list) ...l];
}
```
What is the static type of `flatten`? List of what?

**Comment by lrhn** [comment]
@tatumizer That's a very good question. And the answer is straightforward: It's precisely `List<T>`!

We have introduced a new type variable, `T`, with no bound, so and all we know about `T` is that it'll be some type at run-time.
It's precisely the same kind of static type as the type of `result` in:
```dart
List<T> flatten<T>(List<List<T>> lists) {
  List<T> result = [for (var l in lists) ...l]; // What is the static type of `result`? It's precisely `List<T>`!
  return result;
}
```

**Comment by tatumizer** [comment]
@lrhn: do you allow patterns like this?
```
if (list is List<List<var T extends Foo>>) {  // note "extends Foo"
  List<T> flatten = [for (var l in list) ...l];
}
```
If not, there's no parity between this code and a normal generic code like yours. Example:
```
List<Foo>? flattenedList() {
  var  list=... get list from somewhere
  if (list is List<List<var T extends Foo>>) {
    List<T> flatten = [for (var l in list) ...l];
    return flatten;
  }
  return null;
}
```
Though the compiler doesn't know T in advance, at least it knows that T extends Foo! Generic code always takes advantage of this knowledge.

**Comment by lrhn** [comment]
@munificent [asked](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#:~:text=Can%20type%20patterns%20have%20bounds?) about whether we should allow bounds. It think we should. It makes sense if you can ask `x is List<List<num>>` and `x is List<List<var T>`, you should be able to do the combined `x is List<List<var T extends num>>`.

**Comment by tatumizer** [comment]
Nitpick: calling T a `var` entails a natural question: why I can define this `var` in the context of "if", but not directly?
E.g. you need to be able to explain to the user why the following is wrong:
```
var T=String;
List<T> list=[];
```

**Comment by lrhn** [comment]
Easily. Type variables can *only* be declared inside `<` and `>`. It's not a *value variable*, it's a *type variable*, completely different things, like it always has been in Dart.

What `List<var T>` means is that the pattern introduces and binds a *new* `T`, rather than using an existing type variable like `List<T>` does. The distinction is necessary when both are possible. In a `class C<T> { ... }` you don't need to say that `T` introduces a new variable. 

Patterns occur in a weird position between declarations and expressions because they can both declare a *required* structure (type, arity of lists, actual values), and destructure into *new* variables.
That's why `[x, var y]` should (IMO) be a pattern matching a two element list where the first element is the *value* `x` and the second element, whatever it is, becomes the value of the new variable `y`. Or, same thing with a type matcher: `Point(x: x, y: var y)`. And why I also want to be able to do both binding and testing at the same time, so you can write:
```dart
Point(x: var x, y: var y) p = generatePoint();
```

(Hmm, maybe we need a for-where loop: `for (Point(x: 0, y: var y) p of somePoints) ...` only do something for points which match the pattern!)
Point(x:

**Comment by tatumizer** [comment]
WRT your last example: there should be a systematic way to handle potential failures of destructuring. Even in the simplest case of `(var x, var y)=list;` the operation may fail if the list is shorter than 2 elements. We've already encountered a degenerate case of "destructuring" in `iterable.first` and friends. Somebody proposed `tryFirst` as a solution, but this solution is not general enough to cover the general destructuring under discussion. Switch (like the one in your example) is way too verbose for simple cases. Maybe a variant of "try" (or "guard", or something) can be introduced for this purpose?
```
if (try Point(0, var y) = generatePoint()) {
   //...
}
```

**Comment by lrhn** [comment]
That's looks exactly like what you can do with:
```dart
switch (generatePoint()) {
  case Point(x: 0, y: var y): /// ...
}
```
so I think we have that covered. OR do you just want a shorter syntax for a one-case switch?

**Comment by tatumizer** [comment]
Yes, shorter syntax please! :-)
The word "switch" strongly suggests that we are going to consider several cases. I've never seen a switch with just a single case before. Such a construct will make a reader of the program suspect that the author, upon writing a single case, was distracted by something (zoom call?) and then forgot where he left off. Certainly a cause for concern. So it's not just about shorter syntax, but about the difference in semantics between "switch" and "if".

But there's a bigger problem that can't be addressed with a shorter syntax: a problem of scope. Whatever variables we define inside any block, exist only in this block. Very often, we need variables that outlive the block, and then there's no choice but to declare them before the block. E.g..
```dart
var input;
try {
   input = File.open(....);
} finally {
  if (input!=null) input.close();
}
```
There's no way around it. But the proposal for patterns doesn't allow binding previously declared variables. This will lead to "Russian doll" style of programming with deeply nested ifs and switches. Not sure there's any cure for this.

**Comment by lrhn** [comment]
The shorter version would be `if (generatedPoint() is Point(x: x, y: var y)) //...` except that it can't (currently) bind `p` as well. I'd suggest allowing `is Point(x: x, y: var y) p` to both test and bind the entire value (which also allows the degenerate `if (something is Point p) ...`).

**Comment by tatumizer** [comment]
But what about other patterns? What is the guarded version of
```
[var x, var y] = list;
```
?

**Comment by lrhn** [comment]
*I* would say that it has to be `if (list is [var x, var y]) ...`, and that it has to be guarded because the assignment is not statically guaranteed to succeed, and we don't want to introduce run-time errors. 
If you really, really *want* the run-time error, use `list as [var x, var y];`. The `as` is universally recognized as "run-time error may happen here".
(The current proposal differs, hence this issue).

**Comment by tatumizer** [comment]
I am not sure "is"/"as" help much in a more general case:
```
if (list is [var x, var y] || list is [var z]) {
   // what are the values of x, y, z here?
   // some of them are certainly undefined!
}
```

**Comment by lrhn** [comment]
The `||` here means that the code inside the body cannot assume that either condition has succeeded, so it gets access to none of the variables. No surprise there. You really should just do `if (list is List && list.isNotEmpty && list.length <= 2) { var x = list.first;  ... }`.

A pattern match is an assertion/check about a specific single structure. If it doesn't match, you know nothing except that it didn't match. There is no partial matches.
(If you *want* that, then you'd have to have callbacks inside the pattern, for each part, so that you can do a partial match and do something for that, even if the rest doesn't match. Not sure that's a good idea, though).

**Comment by tatumizer** [comment]
> The || here means that the code inside the body cannot assume that either condition has succeeded, so it gets access to none of the variables.

My point is that such a program should *probably* be rejected statically. Language has to allow writing a pattern without binding. E.g.
```dart
if (list is [_, _] || list is [_]) {
  //...
}
```
Is this idea in the cards?

> If you want that, then you'd have to have callbacks inside the pattern, for each part, so that you can do a partial match and do something for that, even if the rest doesn't match. Not sure that's a good idea, though.

Certainly not :-)

**Comment by tatumizer** [comment]
Is this a valid pattern? `[var x, x]` - matches a list having two first entries equal to each other.

**Comment by lrhn** [comment]
I'd allow it :)

The current proposal does not allow non-constant variables to be used to match values, only literals and constants.

**Comment by tatumizer** [comment]
Just curious: what is the justification for `const` restriction? I'm guessing that in the old `switch`, the *cases* have to be const expressions to allow for a possibility of optimization via a jump table. That switch, therefore, is NOT equivalent to a sequence of ifs - the order in which the tests are performed is not guaranteed. (BTW, I'm not sure jump tables are implemented in dart today, but it's a matter of optimization).  But in the pattern `switch`, the tests can be done only sequentially. What's the point of `const` restriction then?

**Comment by munificent** [comment]
> However, it then has list and map _binders_, even though a collection binder is very much refutable. A pattern of `var [x, y] = list;` cannot match unless the list has length 2 (precisely or at least, depending on the choice of syntax).

By that same token, then, we should have made the return type of `operator []` on `List` be `E?`. :) We didn't, so there seems to be an implication that when pulling elements out of a list, you know what you're doing. Or, said another way, out of bounds errors are mostly a programmatic error and not a runtime error.

Given that, I think it's reasonable (and practically useful) to have list binders, even if they may throw. After all, the code you would write instead would throw too:

```
var a = list[0];
var b = list[1];
```

My argument for map binders is a little less strong since `operator []` does return `V?` for maps. But, for what it's worth, it is often annoying that you have to use `!` after map accesses where you know the key is present. I agree with your point that we're trying to overall move away from runtime errors, but this is a place where I think users should know what they are doing and in practice a runtime failure would indicate a bug.

> The idea is to not split into "binders" and "matchers" as separate incompatible categories, just specify that only some patterns are allowed in "binding" contexts, based on recursively not containing refutable patterns (where "type patterns" are considered irrefutable if guaranteed by the static type).

I tried several times to get a proposal like that to hang together and have a nice syntax, but ultimately failed. The key issue is around bare identifiers. It's really nice if an identifier binds a variable in some contexts but is a constant pattern in others:

```dart
var (e, f) = (1, 2);

switch (tuple) {
  case (e, pi): print('contained some mathematical constants');
}
```

Splitting the pattern grammar into separate binding and matching contexts allows an identifier to be a variable declaration in the former and a constant pattern in the latter. It's what Swift does too. All the other languages I looked at either didn't support named constant patterns at all and only *literal* patterns (because magic numbers are great, I guess?) or used something hacky like *identifier case* to distinguish between variables and constants.

**Comment by lrhn** [comment]
> I tried several times to get a proposal like that to hang together and have a nice syntax, but ultimately failed. The key issue is around bare identifiers. It's really nice if an identifier binds a variable in some contexts but is a constant pattern in others:

That might be my main point of opposition. I think it would be better to be entirely consistent, and require `var` on every new variable, and only have one syntax for everything, rather than optimize for brevity in some places at the cost of conceptual complexity that must be understood by developers.

So, I'm fine with having to write `(var e, var f) = (1, 2);`. (I am now. Maybe I'll hate it after having to do it for a few months. Usability tests might be needed.)

> All the other languages I looked at either didn't support named constant patterns at all and only literal patterns (because magic numbers are great, I guess?) or used something hacky like identifier case to distinguish between variables and constants.

That is a point. We use lower-case letters for constants too, so I guess `pair is (var x, y)` should work. Still not sure having two parallel and almost equivalent syntax categories is worth it.

**Comment by munificent** [comment]
I'm going to close this because I think we've addressed the high level point by reorganizing the proposal into a single unified pattern grammar, but feel free to re-open if there's still other changes in here we want to keep discussing.
