### ISSUE TITLE
Leading `var`/`final` in binders.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1405]
See [pattern proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#late-and-static-variables-in-pattern-declaration).

The proposal requires binders to be prefixed by `var` or `final`. 
That means you have to do either:
```dart
var (a, b) = pair;
```
or
```dart
final (a, b) = pair;
```
but cannot make one variable vary and the other be final.

Would it be possible to instead do:
```dart
(var a, final b) = pair;
```
The parser would need to be able to recognize this as a pattern, but it's on the left of a `=`, so it has to be a pattern in order to be assignable. Even if we allow `_` as a binder, `(_, _, var x) = triple;` or even `(_, _) = pair;` would work. If there is no identifer before the `=`, it's parsed as a pattern. (Probably harder to parse that way, but not impossible. Easier if all compound patterns are tuple patterns because then the assignment is always of the form `(...) = e` and our parser knows how to find the matching paren when parsing, so when it sees a `(`, it can check if the matching `)` is followed by `=`, and then it's a binding declaration).

This would also give symmetry with *matchers*, where `switch (list) { case (x, var y): ...}` matches a pair where the first value is equal the value of `x` and the second value is bound to the new variable `y`. 
That is, in matchers we write `var` inside the pattern, in binders we don't. I think that could get confusing to users. (Although we do allow a leading `var` as shorthand in matchers, we could do that for binders too, but then it's a shorthand, not the only option).

Also, we could allow `(var x, var y) = p` as an expression instead of only as a "statement". We have the usual issues about scopes of variables introduced in the middle of an expression, but we could probably use the same solution as always (scope is entire block, must only be used where definitely assigned). That also suggests allowing `(var x = e)` as an expression, which would be awesome. 😉

**Comment by munificent** [comment]
Yeah, I think this is doable, though I don't know if I find it highly compelling. I really like having a leading keyword before declarations and I'm not sure if allowing burying them inside other patterns harms readability (and parseability) so much that it cancels out the value.

Perhaps we could just allow `var` inside a `final` binder in order to override the `final`-ness? So you'd do:

```dart
final (var a, b) = pair;
```

That looks pretty weird too, though... Honestly, I don't think mutable destructured locals are going to be particularly common in code that also uses `final` for locals, so it probably doesn't carry its weight.

Also, I suspect at some point we may want "extract binders" that let you do user-defined destructuring, like:

```dart
var Cartesian(x, y) = somePoint;
```

If we had that, I think it would be pretty weird to also allow:

```dart
Cartesian(var x, var y) = somePoint;
```

The pattern grammar is pretty tricky as it is, so I'm hesitant to add more complexity to it.

> Even if we allow `_` as a binder, `` or even `(_, _) = pair;` would work.

For those, can't you just do:

```dart
var (_, _, x) = triple;
var (_, _) = pair;
```

Granted, the latter is a little more verbose than what you suggest, but it's also useless so...

**Comment by lrhn** [comment]
Doing the `var (x, y) = point;` looks convenient, but also potentially confusing. Even considering having multiple levels with overriding suggests to me that it's on the wrong track entirely. 
I think I'd prefer to *only* have `var` on the actual variable, so it's only going to be `(var x, var y) = point;`. Simple to explain, if you need to introduce a new variable, you write `var` in front of that.

That generalizes to refutable patterns, where some of the parts are not binding. There you need to be able to introduce *values* as matchers, even values stored in variables.

Example:
```dart
extension PairX<X, Y> on Pair<X, Y> {
  bool isScond(Y y) {
    switch (this) {
      case (_, y): return true; 
      default: return false;
    }
  }
}
```

Or, probably less speculative, example:
```dart
switch (point) {
  case (0, var y): // y axis 
  case (var x, 0): // x axis
  case (var x, x): // x/y diagonal!
  case (var x, -x): // other diagonal
  case (var x, var y): // rest
}
```

**Comment by munificent** [comment]
> Doing the `var (x, y) = point;` looks convenient, but also potentially confusing.

It's the syntax supported by [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), [Swift](https://www.hackingwithswift.com/example-code/language/what-is-destructuring), [Kotlin](https://kotlinlang.org/docs/destructuring-declarations.html), [Scala](https://stackoverflow.com/questions/2776651/scala-tuple-deconstruction) and others so it can't be that bad. :)

I do strongly feel we should allow this syntax exactly as written. I think we'd be pretty far off the beaten path if we didn't.

> That generalizes to refutable patterns, where some of the parts are not binding.

Matcher patterns in the proposal do support this. :) You can embed a [variable inside a binder](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#variable-matcher).

> Or, probably less speculative, example:
> 
> ```dart
> switch (point) {
>   case (0, var y): // y axis 
>   case (var x, 0): // x axis
>   case (var x, x): // x/y diagonal!
>   case (var x, -x): // other diagonal
>   case (var x, var y): // rest
> }
> ```

Yes, the proposal supports exactly that syntax.

**Comment by munificent** [comment]
After weighing all of the many many trade-offs, I think we've finally decided not to go in this direction, as of 8a9b9a8a74a49e13c625e5208bab201d8a4f0e76.
