### ISSUE TITLE
allow abstract class constructors usage inside the class definition

### ISSUE THREAD

**Issue by nt4f04uNd** [dart-lang/language#1409]
```dart
abstract class Sort<T> {
  const Sort({
    @required this.feature,
    @required this.orderAscending,
  })  : assert(feature != null),
        assert(orderAscending != null);

  final T feature;
  final bool orderAscending;

  Sort copyWith({T feature, bool orderAscending}) {
    return Sort(
      feature: feature ?? this.feature,
      orderAscending: orderAscending ?? this.orderAscending,
    );
  }
}
```

i was supposing this is allowed, but turns out it's currently impossible to use abstract class constructors inside it

![image](https://user-images.githubusercontent.com/39104740/104852158-29c12180-590a-11eb-9d57-d33057c94e93.png)

**Comment by nt4f04uNd** [comment]
ok i guess didn't think of this too much
if i extend such class later and use this such method, i actually will get the abstract class instance instance which is not allowed
i should close this right?

**Comment by lrhn** [comment]
Absolutely right 👍
