### ISSUE TITLE
Remove LateInitializationError from NNBD specification

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#1412]
NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#late-fields-and-variables) contains mentions of `LateInitializationError` class which was removed according to the https://github.com/dart-lang/sdk/issues/44361#issuecomment-737672074

**Comment by lrhn** [comment]
Fixed by https://github.com/dart-lang/language/issues/1401
