### ISSUE TITLE
Final function parameter

### ISSUE THREAD

**Issue by NatoBoram** [dart-lang/language#1419]
> Include a permanent link to the error if possible.

https://dart.dev/guides/language/language-tour

I recently found out it was possible to include `final` in function parameters.

```dart
/// Handler for the footer leading checkbox
void _onCheck(final bool value) {
  setState(() {
    _checked = value;
  });
}
```

However, this feature is not documented anywhere and it's ~~impossible~~ very difficult to find any information regarding this obscure topic.

Since the variable being passed to the function was already declared elsewhere and could be `var`, what are all the impacts of using `final` in function parameters?

<details>
<summary>Relevant search results</summary>

* [https://stackoverflow.com/q/24357220](https://stackoverflow.com/q/24357220/5083247)
* [https://stackoverflow.com/q/65905573](https://stackoverflow.com/q/65905573/5083247)

</details>

**Comment by parlough** [comment]
Dart has pass by value semantics so declaring a parameter as `final` simply means that variable declaration cannot be reassigned. If you don't define it as final and reassign the variable, it will only modify the variable local to that method scope, not the one you passed in.

**Comment by munificent** [comment]
Yes, as @parlough says, putting `final` on a parameter simply means that *within the body of that function*, the parameter cannot be reassigned. It's honestly kind of a pointless feature. I don't think it's something we deliberately designed with explicit intention so much as it falls out of the fact that parameter syntax uses the same grammar as variable declarations.

**Comment by TheKashe** [comment]
> It's honestly kind of a pointless feature

Just curious, why? Aren't local final variables as pointless by that logic?

I think it would even make sense for parameters to be final - rather than var - by default.

**Comment by munificent** [comment]
I think it would be reasonable to make parameters and local variables final *by default*, like Rust does. But, in general, I kind of like that Dart defaults to assignable for parameters and locals. Most functions are short enough (or *should* be), that knowing whether or not a parameter or local is reassigned is very easy to tell even if not explicitly annotated.

In return for defaulting to assignable, it means that new Dart users have fewer features to learn before they can write code that does what they want. The first time they try to assign to a parameter or local, it just works. They don't have to go and learn the difference between `let`/`val` and `var`.

**Comment by TheKashe** [comment]
> it means that new Dart users have fewer features to learn before they can write code that does what they want.

That's an interesting perspective. I'm using Dart/Flutter to teach my daughter programming and I'm trying my best not to teach her anti-patterns from the get go.

While defaulting to `var` can get you to the short term goal faster (does it?), it probably will create long term problems, specially with the population who "assign (a value) to a parameter or local, (and) it just works".

Then again, I could see how defaulting to final could be frustrating for developers coming from JS or Python.

**Comment by munificent** [comment]
> I'm trying my best not to teach her anti-patterns from the get go.

You may find it easier to focus on teaching her one "level" of concept at a time. If she's at the level of just trying to make code do what she wants, it will probably be easier for her to absorb concepts at that level if she's not also being taught "here's the right way to do things".
