### ISSUE TITLE
Proposal: Import path mapping

### ISSUE THREAD

**Issue by DevNico** [dart-lang/language#1424]
I'd like to propose a new feature that's basically [typescript path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) in dart. Currently I have a lot of relative imports to files that are one, two or three directories higher up leading to a lot of `../../` etc. style imports. Having the ability to define shorthand paths for certain directory would make imports look a lot nicer.

As an example app structure I have:
```
lib/
--- api/ 
--- db/
--- model/
--- state/
--- views/
       --- widgets/
       --- page1/
       --- page2/
       page1.dart
       page2.dart
```
In a `tsconfig.json` I could define something like:
```json
{
  "baseUrl": ".",
  "paths": {
    "@*": ["lib/*"],
    "@widgets": ["lib/views/widgets/]
  }
}
```
Which in turn would let me import files from the api folder as `@api/weather.dart`. When considering that I might import this file from a location like `lib/state/weather/weather.dart`, the @ syntax is a lot nicer.

I would like to be able to define path mappings like in the above tsonfig example in dart. Maybe in the `analysis_options` file?

**Comment by lrhn** [comment]
How often would using an absolute API be sufficient?
In this case, if you could just `import '/api/weather.dart';`, it seems like it would solve the problem.
That won't make `/views/widgets` as directly accessible, though, you'd still need the `/views` prefix.

There is the problem that `@` is a valid character in URIs already, so it's technically breaking to make it mean something else. I doubt anyone has actual paths with `@` in them, but ... well, there's always one!
Alternative characters which cannot occur inside a relative path would be `#` and `?`.

**Comment by DevNico** [comment]
Even though the absolute path syntax would already be nice as you said it doesn't solve every case. That's why I'd prefer the flexibility some kind of path mapping would give you.

**Comment by MrCreeper1008** [comment]
you can already do it currently with `import 'package:my_package/api/...';`

**Comment by DevNico** [comment]
That's true but I as many others am following the convention of having relative imports only for files in the same package and mixing import styles is a bad idea.

**Comment by lrhn** [comment]
With the next release, I hope that you'll be able to do `import '/api/...';` without writing the `package:mypackageName` in front.
I'd consider that a relative import too. (Package-relative, not directory relative, but still relative! You don't need to hard-code the package name, which is the real problem with doing absolute package imports into the current package).

**Comment by nguyenxndaidev** [comment]
> With the next release, I hope that you'll be able to do `import '/api/...';`

@lrhn Is there a plan for that? which release will we have this feature? I am really waiting for this.

I don't like to have `../` in imports because it's too fragile when moving files/directories around.

For importing code from the same project, I don't like to use `package:mypakcagename` because of some reasons:
* too verbose
* mixing with imports from dependent packages
* if I change package name, I need to refactor everywhere with the new package name

**Comment by nguyenxndaidev** [comment]
I also like the idea of stealing path mapping from typescript. It's really helpful to organize internal modules easily in big projects.

We should avoid using [URI reserved characters](https://en.wikipedia.org/wiki/Percent-encoding#Reserved_characters).

My idea is to have tilde import `~:api/weather.dart`. `~:api` means from home of `api` module.

You see that, `~:mymodulename` looks similar to `package:mypackagename`.

**Comment by lrhn** [comment]
@nguyenxndaidev 

I personally tend to prefer `../foo.dart` to `/qux/foo.dart`. They can both fail if something moves, the latter if the target file moves, the former if either source or target file move ... but not of both move together. 

The fix to `package:` URI resolution has landed, but I'm not sure when it will be released (2.13 or 2.14). Be careful depending on it if your package doesn't require that SDK level.

**Comment by nguyenxndaidev** [comment]
> I personally tend to prefer `../foo.dart` to `/qux/foo.dart`. They can both fail if something moves, the latter if the target file moves, the former if either source or target file move ... but not of both move together.

@lrhn yes, you are right. I updated my previous comment regarding this aspect. But other aspects are still valid to have different methods to imports.

**Comment by j-vasil** [comment]
If there was a tool (vscode extension? auto-format option?) that allowed one to automatically switch between using relative and absolute paths for importing, this issue might be less important since everyone could choose their preferred style.  It shouldn't be difficult even if there were different files with the same name in two different directories (`../abc/foo.dart` and `../def/foo.dart`) [aside: And perhaps the developer should be warned about that situation anyway?].  A more difficult decision might be whether or not the list should be resorted after the change.

**Comment by nguyenxndaidev** [comment]
> If there was a tool (vscode extension? auto-format option?) that allowed one to automatically switch between using relative and absolute paths for importing

I am using IntelliJ and we have this feature already, but it doesn't work well yet).
Even if it works, it only solves a minor issue. 

There are many more important things we want too:
* readability
* refactoring with less (or even without) changing import paths
* better organization and isolation of separated parts, which is really important for team working

**Comment by rrousselGit** [comment]
It's worth noting that you can use `export` to do something very similar today.

```dart
// lib/alias.dart

export 'src/very/long/path.dart';
```

Then do:

```dart
import 'package:my_package/alias.dart';
```

**Comment by chgibb** [comment]
Please don't bring the insanity of JavaScript path aliases to Dart. This is what packages (and path dependencies), libraries, and re-exports are all already for.

**Comment by nguyenxndaidev** [comment]
> It's worth noting that you can use `export` to do something very similar today.
> 
> ```dart
> // lib/alias.dart
> 
> export 'src/very/long/path.dart';
> ```
> 
> Then do:
> 
> ```dart
> import 'package:my_package/alias.dart';
> ```

agree, but it would be nice if we have `/alias.dart` so the import is separated from the list of external packages in the importing list.

Another issue is how to force importing `/alias.dart` and prevent importing from `src/very/long/path.dart`.
Maybe adding a rule to `analysis_options.xml` to report warning/error for this case?
