### ISSUE TITLE
Allow multiple fields in print()

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/language#1430]
Disclaimer: I couldn't find a duplicate for this issue. I can't believe no one has ever requested this.

I believe Dart could/should allow `print("variable is", variable)` syntax. Right now, the mental model is very confusing: I start with `print(variable)`, then if I want to name it I get something like `"variable is"variable` and then, there is the decision, do I use string interpolation or add a comma? The comma is the easiest way, but it won't work because Dart doesn't support it.

I also develop in JavaScript/TypeScript, Java, Kotlin, and others, and Dart is the only language I record that doesn't allow you to keep adding variables in the print method. Even [Swift supports this](https://stackoverflow.com/a/62715536/4418073).

The current workaround is very weird: `['The values are:', x, y, z].forEach(print);` (from [here](https://stackoverflow.com/a/26755757/4418073)).

**Comment by tatumizer** [comment]
`print` with N parameters requires a more general feature: varargs, which was discussed earlier on many occasions over the years.
Latest incarnations of the discussion:
https://github.com/dart-lang/language/issues/1014
#53
(`print` in dart is just a regular function, not an intrinsic or macro - it can't receive any special treatment not available to other functions; hence the need of varargs as a general mechanism).

**Comment by bernaferrari** [comment]
oh, the good old `varargs`. I guess that was what I was looking for! Sorry and thanks!
