### ISSUE TITLE
How to make my own custom Map

### ISSUE THREAD

**Issue by maxime-aubry** [dart-lang/language#1438]
Hello.

I try to create a custom map in my library.

I tried two differents ways, both of them does not work.

First way :
``` dart
abstract class CustomMap implements Map<String, CustomType> {
  external factory CustomMap();
}
```

exception:
> NoSuchMethodError: No constructor 'CustomMap.' with matching arguments declared in class 'CustomMap'.

Second way :
``` dart
abstract class CustomMap extends HashMap<String, CustomType> {
  factory CustomMap() => HashMap.identity();
}
```

exception:

> type '_IdentityHashMap<dynamic, dynamic>' is not a subtype of type 'CustomMap'

Could you help me please ?
Thanks

**Comment by Cat-sushi** [comment]
You can define your own Map with `MapBase` and `MapMixin` in the `dart:collection` package.
But, you have to implement `keys`, `operator[]`, `operator[]=`, `remove` and `clear`.
Those are core features of built-in `Map`, so you can't obtain performance at `Map` level.

Can you agree to my proposal? #1437

**Comment by maxime-aubry** [comment]
Thanks.
I will try this.

**Comment by Cat-sushi** [comment]
If you like, upvote my proposal #1437

**Comment by munificent** [comment]
> First way :
> 
> ```dart
> abstract class CustomMap implements Map<String, CustomType> {
>   external factory CustomMap();
> }
> ```

Using `external` isn't what you want unless you are writing a custom embedder and intend to implement that constructor in something like C++ or JavaScript.

> Second way :
> 
> ```dart
> abstract class CustomMap extends HashMap<String, CustomType> {
>   factory CustomMap() => HashMap.identity();
> }
> ```

So it looks like you want to define your own Map class that reuses the behavior of identity HashMap? The HashMap class itself isn't intended to be subclassed. (All of its constructors are factory constructors.)

Your best option is probably to use explicit delegation like:

```dart
class CustomMap extends MapBase<String, CustomType> {
  final Map<String, CustomType> _map = HashMap.identity();

  CustomType operator [](Object key) => _map[key];
  void operator []=(String key, CustomType value) => _map[key] = value;
  void clear() => _map.clear();
  Iterable<String> get keys => _map.keys;
  CustomType remove(Object key) => _map.remove(key);
}
```
