### ISSUE TITLE
square brackets aren't escaped in inline code block with single backtick

### ISSUE THREAD

**Issue by nguyenxndaidev** [dart-lang/language#1442]
```
/// Generate RegExp with pattern `^[abc]$`
```

is shown as below:

```
Generate RegExp with pattern ^<code>abc</code>$
```

**Comment by srawlins** [comment]
This sounds like a bug for the dartdoc package or the markdown package, or possible for IntelliJ or something. When you say "is shown as", where do you see this? At pub.dev for a package? In your IDE? Can you show an example?

**Comment by nguyenxndaidev** [comment]
> This sounds like a bug for the dartdoc package or the markdown package, or possible for IntelliJ or something. When you say "is shown as", where do you see this? At pub.dev for a package? In your IDE? Can you show an example?

You are right, dartdoc generates html file with correct doc. It should be IDE issue.
