### ISSUE TITLE
Q1 2021 Small Features Tracking Issue

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1447]
This tracks the implementation of the Q1 2021 small features release [specified here](https://github.com/dart-lang/language/tree/master/accepted/future-releases/small-features-21Q1).  This release consists of the following three features:
 - [Triple shift](https://github.com/dart-lang/language/issues/120) operator added, and implemented on the int class.
 - [Generic function type](https://github.com/dart-lang/language/issues/496) restrictions removed.
 - [Generic annotation](https://github.com/dart-lang/language/issues/1297) support.

SDK implementation [tracking issue](https://github.com/dart-lang/sdk/issues/44911).

**Comment by mit-mit** [comment]
@leafpetersen can this be closed now?
