### ISSUE TITLE
Include a way to get whether a generic type is nullable

### ISSUE THREAD

**Issue by jonaird** [dart-lang/language#1459]
Sometimes you want to know whether a generic type is non-nullable so you can allow certain actions when it is. For example to implement ListMixin, you need to implement the length setter. If the new length is greater than the current length, the new length is set with null values: 

```
void set length(int newLegth){
  if(newLength > length) 
   //set the new length but only if the generic type E is nullable
  else ...
}
```

You can work around this by checking if the last character of the toString of the generic type is '?' which works but seems a bit hacky: 
 
```
extension IsNullable on Type {
  bool get isNullable => toString()[toString().length - 1] == '?';
}
```

**Comment by natebosch** [comment]
```dart
bool isNullable<T>() => null is T;

void main() {
  print(isNullable<String>());
  print(isNullable<String?>());
}
```

**Comment by lrhn** [comment]
I think we can consider that feature as available.
