### ISSUE TITLE
Anonymous extension with type arguments intended?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1460]
Consider the following program:

```dart
extension <X extends num> on X {
  num get gulv => this.floor();
}

void main() {
  print(42.8.gulv);
}
```

This program is accepted by `dartanalyzer` and executed by `dart` with no errors. The surprising fact is that the extension has no name, but it has type arguments.

We could interpret this to mean that it has a fresh, private name, say `_Extension1237`, and the declaration would then desugar to the following:

```dart
extension _Extension1237<X extends num> on X {
  num get gulv => this.floor();
}
```

We could also decide that it is a compile-time error to have type arguments when there is no name.

The reason why this issue comes up now is that it causes an ambiguity problem for the extension types feature which is currently being [discussed](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Aextension-types):

```dart
// A typical declaration of an extension type:
extension type SomeName<X extends num> on X {
  num get gulv => this.floor();
}

// A regular extension named `type` or an extension type with no name?
extension type <X extends num> on X {
  num get gulv => this.floor();
}
```

If we decide that it is a compile-time error for an extension declaration (the ones we've had since version 2.6) to have type arguments but no name then we'd report this as an SDK issue and ask for an implementation of the error. Otherwise we'd need to make `type` a built-in identifier, or we would need to use a different syntax entirely for extension types.

**Comment by leafpetersen** [comment]
> We could interpret this to mean that it has a fresh, private name, say `_Extension1237`, and the declaration would then desugar to the following:

This is explicitly how anonymous extensions are described in the [feature specification](https://github.com/dart-lang/language/blob/master/accepted/2.7/static-extension-methods/feature-specification.md#syntax):

```
 If an extension declaration omits the name identifier, its equivalent to an extension declaration with a fresh private name.
```

I would certainly have expected this to work.  For example:

```
extension<T> on List<T> {
  T get second => this[1];
}
```
 
There are also a substantial number of tests both in the language and co19 repo which use this feature.  I think this is clearly WAI.
