### ISSUE TITLE
how to use null safety with factory?

### ISSUE THREAD

**Issue by dancheng99** [dart-lang/language#1463]
```
class A {
 late String _name;

  static A? _instance;

  A._(this._name);

  factory A([String n = 'A']) {
    if (A._instance == null) {
      A._instance = A._(n);
    }

    return A._instance!;
  }

  get name => _name;
}



--------------------------------
import 'A.dart';

main(List<String> args) {
  A a1 = A('HelloWorld');
  print(a1.name);
}


---------------------------------
error is:
PS D:\workspace\flutterstudy> dart "d:\workspace\flutterstudy\lib\Basedart\factory\A.dart"
lib/Basedart/factory/A.dart: Warning: Interpreting this as package URI, 'package:app/Basedart/factory/A.dart'.
lib/Basedart/factory/A.dart:2:8: Error: Expected ';' after this.
  late String _name;
       ^^^^^^
lib/Basedart/factory/A.dart:2:15: Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
Try adding the name of the type of the variable or the keyword 'var'.
  late String _name;
              ^^^^^
lib/Basedart/factory/A.dart:4:11: Error: This requires the null safety language feature, which is experimental.
You can enable the experiment using the '--enable-experiment=non-nullable' command line option.
  static A? _instance;
          ^
lib/Basedart/factory/A.dart:8:14: Error: 'String' isn't a type.
  factory A([String n = 'A']) {
             ^^^^^^
lib/Basedart/factory/A.dart:2:8: Context: This isn't a type.
  late String _name;
       ^^^^^^
lib/Basedart/factory/A.dart:2:3: Error: Type 'late' not found.
  late String _name;
  ^^^^
lib/Basedart/factory/A.dart:2:3: Error: 'late' isn't a type.
  late String _name;
  ^^^^
lib/Basedart/factory/A.dart:13:23: Error: This requires the null safety language feature, which is experimental.
You can enable the experiment using the '--enable-experiment=non-nullable' command line option.
    return A._instance!;

```

why not working?

**Comment by leafpetersen** [comment]
What is the error you're seeing?  That code passes static analysis for me.

**Comment by dancheng99** [comment]
> What is the error you're seeing? That code passes static analysis for me.



> What is the error you're seeing? That code passes static analysis for me.

import 'A.dart';

main(List<String> args) {
  A a1 = A('HelloWorld');
  print(a1.name);
}


---------------------------------
error is:
PS D:\workspace\flutterstudy> dart "d:\workspace\flutterstudy\lib\Basedart\factory\A.dart"
lib/Basedart/factory/A.dart: Warning: Interpreting this as package URI, 'package:app/Basedart/factory/A.dart'.
lib/Basedart/factory/A.dart:2:8: Error: Expected ';' after this.
  late String _name;
       ^^^^^^
lib/Basedart/factory/A.dart:2:15: Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
Try adding the name of the type of the variable or the keyword 'var'.
  late String _name;
              ^^^^^
lib/Basedart/factory/A.dart:4:11: Error: This requires the null safety language feature, which is experimental.
You can enable the experiment using the '--enable-experiment=non-nullable' command line option.
  static A? _instance;
          ^
lib/Basedart/factory/A.dart:8:14: Error: 'String' isn't a type.
  factory A([String n = 'A']) {
             ^^^^^^
lib/Basedart/factory/A.dart:2:8: Context: This isn't a type.
  late String _name;
       ^^^^^^
lib/Basedart/factory/A.dart:2:3: Error: Type 'late' not found.
  late String _name;
  ^^^^
lib/Basedart/factory/A.dart:2:3: Error: 'late' isn't a type.
  late String _name;
  ^^^^
lib/Basedart/factory/A.dart:13:23: Error: This requires the null safety language feature, which is experimental.
You can enable the experiment using the '--enable-experiment=non-nullable' command line option.
    return A._instance!;

**Comment by leafpetersen** [comment]
Your code is not being treated as opted in to null safety.  You need to set the sdk constraint in your pubspec.yaml to `2.12.0-0` and run `pub get` to opt into null safety.

**Comment by dancheng99** [comment]
> Your code is not being treated as opted in to null safety. You need to set the sdk constraint in your pubspec.yaml to `2.12.0-0` and run `pub get` to opt into null safety.

environment:
  sdk: ">=2.10.0 <3.0.0"

analysis_options.yaml

analyzer:
 enable-experiment:
 - non-nullable

dart sdk  2.10.5

must be 2.12.0-0？

--------
void main(List<String> args) {
  int? a = 1;
  a = null;
  print(a);
}

but this can working

**Comment by leafpetersen** [comment]
The feature was still in an experimental state in the 2.10 release.  Your best option is to upgrade to a 2.12 beta sdk, and set your sdk lower bound constraint to 2.12.0-0.

If you want to keep running this on a pre-release build using the experiment flag, note that only the analyzer looks at analysis_options.yaml.  All other tools (e.g. running code from the command line) need the experiment flag passed explicitly with --enable-experiment=non-nullable.

**Comment by dancheng99** [comment]
> The feature was still in an experimental state in the 2.10 release. Your best option is to upgrade to a 2.12 beta sdk, and set your sdk lower bound constraint to 2.12.0-0.
> 
> If you want to keep running this on a pre-release build using the experiment flag, note that only the analyzer looks at analysis_options.yaml. All other tools (e.g. running code from the command line) need the experiment flag passed explicitly with --enable-experiment=non-nullable.

I’m truly grateful for your help
