### ISSUE TITLE
work more lower-level in dart codes

### ISSUE THREAD

**Issue by EhsanAramide** [dart-lang/language#1469]
Add more functionalities to work with gc , objects lifecycle , references and context managers like in python and java
``` python
# in python like this
class Ehsan:
    def  __init__(self):
          pass

    def __del__(self):
          print('delete instance')

    def __enter__(self):
          print('enter method')

    def __exit__(self, exc_type, exc_value, exc_traceback):
          print('exit method for releases resources')
```
and work with references can make dart better at embedded systems like go embedded extension or Java ME. I mean make dart more suitable for embedded systems

**Comment by lrhn** [comment]
The `__enter__` and `__exit__` interacts with the `with obj as id: ...` feature to create a scope for the object. It's unrelated to garbage collection, and is more like a C# `using` statement. Dart could add something like that. We don't have an `IDisposable` interface or `__exit__` operator, but we could add an `operator exit()` declaration and a `with x = ... { ... }` declaration thing (better syntax needed).

We have the `__init__`, that's just a constructor. As for `__del__`, I'm very wary about allowing any interaction with garbage collection. It won't work when compiled to JavaScript. It might risk people creating programs which depends on a specific garbage collection implementation, it might cause extra overhead in the garbage collector, and it might risk objects being kept alive longer (adding to memory pressure).

**Comment by listepo** [comment]
> we could add an `operator exit()` declaration and a `with x = ... { ... }` declaration thing (better syntax needed).
@lrhn it sounds good
