### ISSUE TITLE
Cannot run with sound null safety, because the following dependencies don't support null safety

### ISSUE THREAD

**Issue by esDotDev** [dart-lang/language#1475]
Problem: I would like to write some NNBD code which relies on some legacy package, but I can't seem to make it work. 

In this example, `statsfl` is a legacy lib, we want to use NNBD in our own code, we don't care that `statsfl` is legacy internally.

If I have a pubspec like this:
```
environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  statsfl:
```

And some code like this:
```
import 'package:flutter/material.dart';
// ignore: import_of_legacy_library_into_null_safe
import 'package:statsfl/statsfl.dart';

void main() {
  runApp(MaterialApp(
    builder: (_, __) => _MyPage(),
  ));
}

class _MyPage extends StatefulWidget {
  @override
  __MyPageState createState() => __MyPageState();
}

class __MyPageState extends State<_MyPage> {
  int i = 10;

  @override
  Widget build(BuildContext context) {
    return StatsFl(child: Container(color: Colors.orange));
  }
}
```

We would expect it to build, but it doesn't, throwing: 
```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:
 - package:statsfl
```
Note: I'm sure where exactly to log this bug as it straddles Flutter and Dart SDKs.

**Comment by mateusfccp** [comment]
You can pass `--no-sound-null-safety` as parameter.

For example:
```
$ dart --no-sound-null-safety run
$ flutter run --no-sound-null-safety
```

However, this is not ideal. The ideal is to wait for all dependencies to migrate to null-safety.

**Comment by esDotDev** [comment]
Ah I see, so the runtime flag is required to build or run in this unsound mode. Thanks! Is there any sort of project specific flag I can enable so I don't need to pass this for the lifetime of my project? Or some guidance on how to configure tooling btns to pass these flags automatically?

A bit of an aside, Idealism runs up against pragmatism on a daily basis in the trenches :D Many libs have no active maintainers, and the last thing we want to do mid-production, is take over someone else's migration. At the same time, it be very nice to to start writing our own NNBD code _today_. 

We have existing apps with 50 deps, it's just not feasible to worry about all of them, it's also not a big win for the effort. Packages are generally not having null reference errors, and by far the biggest win for developer productivity with nnbd is within our own /lib code, so it's a relatively huge lift, for no real rewards from devs POV.

**Comment by leafpetersen** [comment]
@esDotDev In general, we don't recommend using null safety until your dependencies are all migrated, but as long as you aren't planning to publish the code on pub (which gets into semver issues) we do support running in this mode.  Just be aware that at any point, upgrading your deps may break you (since they may now be opted in, causing new errors in your null safe code that was depending on previously non-null safe libraries).  You can of course downgrade your deps again, or just fix the errors.  We do recommend publishing null safe packages as a major version bump, so you can also use version constraints on your packages to mitigate this, assuming authors follow our recommendations.

To your question, the easiest way to avoid having to pass the `--no-sound-null-safety` flag explicitly is to opt out your entry point (only) out of null safety by marking the file which contains `main` with `// @dart=2.9`.  This will cause the system to auto-detect that you are not fully migrated, and it will run in unsound mode.

Note: you will not be able to use null safety syntax in the file containing main, since it is opted out, so you will either need to "un-migrate" it, or else move your real `main` to a different file and make your entry point a dummy `main` file (opted out as described above) which does nothing but calls your real main, which can then be opted in:

real_main.dart
```dart
// This contains my real entry point, and is opted in
void realMain(...) {
   // Do real stuff, using null safety features 
};
```

main.dart
```dart
// This contains a dummy entry point, and is opted out
// @dart=2.9
import 'real_main.dart';
void main(...) { // Can't use null safety features in this file
  realMain(...);
}
```

**Comment by iulian0512** [comment]
the docs are not explicit enough, after reading them i understood that using // @dart=2.9 in a dart file part of a flutter project it allows you to use "non null safe" packages in that file only. but it seems that in order to compile the project with "non null packages" you got to place that comment in the main file.
in the docs 
"4. Add a language version comment to the top of any Dart files that you don’t want to consider during your current migration:"
source: https://dart.dev/null-safety/unsound-null-safety

**Comment by StevenWung** [comment]
How can I set **--no-sound-null-safety** in Xcode?

**Comment by esDotDev** [comment]
> In general, we don't recommend using null safety until your dependencies are all migrated,_

Why? This makes sense for plugin developers, because the plugin might be used in a pure null-safe project. But it doesn't make any sense for **app** developers. Many times there are 5% of your  plugins you can't upgrade, and there are still loads of benefits in the meantime to upgrade your /lib code.

> Just be aware that at any point, upgrading your deps may break you (since they may now be opted in, causing new errors in your null safe code that was depending on previously non-null safe libraries). 

How? nnbd are always under a major version, as long as we stick on legacy versions, there is no way anything can just break.

> Note: you will not be able to use null safety syntax in the file containing main, 

Ah, this is where I got confused as the docs don't make any distinction here. They say to use this param to enable opt out opf sound-safety, but when you do it, it changes your entire file to legacy which is not expected. Cool trick about moving main though.

**Comment by esDotDev** [comment]
Also, fwiw, you can set this up in Android Studio easily enough: 
![image](https://user-images.githubusercontent.com/736973/112493424-c3141600-8d47-11eb-837c-04e19de00d6d.png)

**Comment by exeptionerror** [comment]
[[Solved] Cannot run with sound null safety because dependencies don’t support null safety](https://fluttercorner.com/cannot-run-with-sound-null-safety-because-dependencies-dont-support-null-safety/)

**Comment by MianJawadAhmad** [comment]
How can we set in xcode?

**Comment by qq326646683** [comment]
How can we set in android studio, not for flutter, is for native?

**Comment by Siddhisa** [comment]
I am still not being able to run it even after using these commands dart --no-sound-null-safety run, flutter run --no-sound-null-safety. I have tried putting //dart=2.9 on top of my main file as well. I am really stuck while using the provider packet.


Launching lib/main.dart on Android SDK built for arm64 in debug mode...
Running Gradle task 'assembleDebug'...
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/delegate_widget.dart:194:18: Error: Superclass has no method named 'inheritFromElement'.
    return super.inheritFromElement(ancestor, aspect: aspect);
                 ^^^^^^^^^^^^^^^^^^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/provider.dart:259:19: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        ? context.inheritFromWidgetOfExactType(type) as InheritedProvider<T>
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/provider.dart:260:19: Error: The method 'ancestorInheritedElementForWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorInheritedElementForWidgetOfExactType'.
        : context.ancestorInheritedElementForWidgetOfExactType(type)?.widget
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/siddhisabanerjee/FlutterDev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/siddhisabanerjee/FlutterDev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hainey** [comment]
This is for run&debug configuration
how to do same thing for build configuration?

**Comment by CyrilHu** [comment]
> How can we set in xcode?

For Xcode, it will configure this automatically after you run `flutter run` once. 
or run `flutter build ios --debug --config-only --no-sound-null-safety`

explain: `flutter run` added `User-Defined` `Build Settings` `EXTRA_FRONT_END_OPTIONS=--no-sound-null-safety` in Flutter/Generated.xcconfig

> How can we set in android studio, not for flutter, is for native?

For Android Studio run native code when you open `android` folder with Android Studio 
add `extra-front-end-options=--no-sound-null-safety` in your `gradle.properties` file

explain: https://stackoverflow.com/a/67751484

**Comment by flutterq** [comment]
[[Already Solved] Cannot run with sound null safety because dependencies don't support null safety](https://fluttercorner.com/cannot-run-with-sound-null-safety-because-dependencies-dont-support-null-safety/)

**Comment by tvanhuu** [comment]
> > How can we set in xcode?
> 
> For Xcode, it will configure this automatically after you run `flutter run` once.
> or run `flutter build ios --debug --config-only --no-sound-null-safety`
> 
> explain: `flutter run` added `User-Defined` `Build Settings` `EXTRA_FRONT_END_OPTIONS=--no-sound-null-safety` in Flutter/Generated.xcconfig
> 
> > How can we set in android studio, not for flutter, is for native?
> 
> For Android Studio run native code when you open `android` folder with Android Studio
> add `extra-front-end-options=--no-sound-null-safety` in your `gradle.properties` file
> 
> explain: https://stackoverflow.com/a/67751484

>> thank solution. It's work for me
