### ISSUE TITLE
Small features Q1 2021: ensure that spec covers mixed mode and inference.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1476]
@srawlins raised several questions that we should be sure are covered both by the small features spec and by our tests. 

For code that has an old language version, I believe that we want the following semantics:
  - It is an error to use a generic function type (GFT) as a bound
  - It is an error to use a GFT as an **explicit** type argument
  - It is not an error for instantiate to bound to produce a GFT as a type argument
    - This can only occur if the type was defined in an opted in library
  - It is not an error for inference to propagate a type which uses a GFT as a type argument into an opted in library
    - For example, if an opted in library defines a symbol `x` with type `List<SOME_GFT>`, then `var y = x` in an opted out library can safely infer type `List<SOME_GFT>` for `y`.
  - It is not an error for an opted out library to export a symbol from an opted in library which uses a GFT as a type argument
  - Local type inference should continue to produce the same results: `[f]` where `f` has a GFT should continue to infer as `List<Function>` in opted out libraries

For code that is defined in an opted in library, we should make it explicit that:
  - Local type inference should not approximate function types.   `[f]` where `f` has a GFT should infer as `List<GFT>` in opted in libraries

@lrhn can you make sure that this is covered by the spec, assuming you agree with the above?

cc @eernstg @srawlins @johnniwinther @stefantsov @scheglov @devoncarew

**Comment by lrhn** [comment]
About:
> It is not an error for inference to propagate a type which uses a GFT as a type argument into an opted in library
> For example, if an opted in library defines a symbol `x` with type `List<SOME_GFT>`, then `var y = x` in an opted out library can safely infer type `List<SOME_GFT>` for `y`.

I'm not sure what this covers exactly, or if it makes sense.

If the opted-in library has a `SOME_GFT y = ...;`, is `var x = [y];` valid? How about `List<SOME_GFT> y = ...;` and `var x = [y.first]`? 
Where do we draw the line between inference taking the GFT "from the other library"? 
Only when we inline the *entire* type from the opt-in library in the resulting type?

What about (opted-in) `List<SOME_GFT> y = ...;` and (opted-out) `var x1 = [y]; var x2 = y[0]; var x3 = [...x2];`. 
* Is `x1` an error? (Likely no, it just plugs the entire type of `y` into a list to become `List<List<SOME_GFT>>`). 
* Is `x2` an error? It's just the `List<SOME_GFT>` which came from `y`, but it's going through an opted-out variable. 
* Is `x3` an error? It uses the `SOME_GFT` from before, and creates a new list with the same type argument.

If `x2` is an error, then it means that *copying a value into an opt-in library is an error*.
```dart
var z = [y]; // valid
var y2 = y;
var z2 = [y2]; // invalid
```
I think this will be too confusing to users.

I'd think I'd prefer to just say that it's an error in an opted out library if a type occurs, inferred or not, where a GFT is a type argument.
Or, alternative I haven't though through yet, to make it an error to use a GFT as argument to a class/mixin/extension/type-alias declared in an opted-out library, but not for a type declared in an opt-in library, no matter where the instantiation is.  Then it's a property of the *receiver* that it doesn't accept GFTs, not the instantiation point, which is an arbitrary place in code.

Also:

> It is not an error for instantiate to bound to produce a GFT as a type argument
> This can only occur if the type was defined in an opted in library

I'm not sure that's true if we allow inference to move GFT types into an opted out library:
```dart
// opted out:
import "optin.dart" as optin;

class C<T> {
  int foo<X extends T>(X x) => ...;
}
main() {
 var x = optin.createCofGFT();
 x.foo();
}
```
Here the rule above would allow `x` to have type `C<SOME_GFT>`, and then `x.foo()` would instantiate-to-bound `X` as `SOME_GFT`, even though all the code of `C` is opted out.

> Local type inference should continue to produce the same results: `[f]` where `f` has a GFT should continue to infer as `List<Function>` in opted out libraries

That's not what we currently do. We actually infer `List<GFT>`, then we make that a compile-time error. Not a great user experience.

**Comment by leafpetersen** [comment]
> I'm not sure what this covers exactly, or if it makes sense.

The point of this is issue is that one way or the other, we need to define the semantics, and test that it is implemented consistently.  I'm open to alternative proposals.  

> If the opted-in library has a SOME_GFT y = ...;, is var x = [y]; valid? 

yes

> How about List<SOME_GFT> y = ...; and var x = [y.first]?

yes

My (initial) proposal is that the following things are errors in an opted out library:
  - Explicitly passing a GFT as a type argument
  - Explicitly using a GFT as a bound
  - And nothing else

> What about (opted-in) `List<SOME_GFT> y = ...;` and (opted-out) `var x1 = [y]; var x2 = y[0]; var x3 = [...x2];`.
> 
> * Is `x1` an error? (Likely no, it just plugs the entire type of `y` into a list to become `List<List<SOME_GFT>>`).
> * Is `x2` an error? It's just the `List<SOME_GFT>` which came from `y`, but it's going through an opted-out variable.
> * Is `x3` an error? It uses the `SOME_GFT` from before, and creates a new list with the same type argument.

No, no, and no.

> If `x2` is an error, then it means that _copying a value into an opt-in library is an error_.
> 
> ```dart
> var z = [y]; // valid
> var y2 = y;
> var z2 = [y2]; // invalid
> ```
> 
> I think this will be too confusing to users.

This is 100% true of any feature we ship using language versioning.  If you copy something that uses `[...x]` from a 2.4 library to a 2.0 library, you will get an error.


> > It is not an error for instantiate to bound to produce a GFT as a type argument
> > This can only occur if the type was defined in an opted in library
> 
> I'm not sure that's true if we allow inference to move GFT types into an opted out library:
> 
> ```dart
> // opted out:
> import "optin.dart" as optin;
> 
> class C<T> {
>   int foo<X extends T>(X x) => ...;
> }
> main() {
>  var x = optin.createCofGFT();
>  x.foo();
> }
> ```
> 
> Here the rule above would allow `x` to have type `C<SOME_GFT>`, and then `x.foo()` would instantiate-to-bound `X` as `SOME_GFT`, even though all the code of `C` is opted out.

This is fine.  The type `C<GFT>` comes from an opted in library.  I think you're misunderstanding the goal here.  The goal is not to ensure that GFTs don't end up in opted out libraries in places that they couldn't before.  The goal is to ensure that opted out libraries can't use GFTS in a way that won't work on old implementations. I don't see any issue with the above, from that standpoint.  

> That's not what we currently do. We actually infer `List<GFT>`, then we make that a compile-time error. Not a great user experience.

Actually, this is the only thing that saves you from being **forced** to accept my proposal above.  :)  You're right, I missed that two errors were emitted in my test code.  If this is done uniformly, then we have the option of taking a different approach from what I specify, assuming that there are no other places where approximation is done.  If we ever do approximate, then we need to be sure that old code continues to approximate in exactly the same way.

Again, I'm happy to see an alternative proposal, but we need to specify what happens in the cases I mention, and test for it.  I've laid out my proposal above, happy to take alternatives.  Note that we have fairly limited time to resolve this.

**Comment by lrhn** [comment]
My alternative proposal for interoperation between non-migrated (opt-out) and migrated (opt-in) "generic metadata" code:

In an opt-out library:
* It is a compile-time error to use a generic function type (GFT) as a bound.
* It is a compile-time to use a GFT as a type argument. *This includes inferred types*.
* It is not an error for an opted out library to *export* a symbol from an opted in library which uses a GFT as a type argument

Then you *can* pass GFTs as type arguments to opt-out declared generics, if they accept `Function`, but if an opt-out library depends on an opt-in library, then they need to opt in as well, or avoid type inference.

**Comment by leafpetersen** [comment]
> * It is a compile-time to use a GFT as a type argument anywhere. _This includes inferred types_.

And to be explicit, it also includes instantiate to bound.

This proposal is also fine by me.  @eernstg @srawlins thoughts?

**Comment by lrhn** [comment]
Yes, I consider instantiation-to-bound part of inference (it fills in a missing type argument).

About:
> The goal is to ensure that opted out libraries can't use GFTS in a way that won't work on old implementations. I don't see any issue with the above, from that standpoint.

It's possible to write:
```dart
var x = <T>(T x) => x;
var l = [x];
```
today and get an error. It does not use any explicit GFT as type argument, only the inferred one for the list literal/`l` variable.

If that begins working, if we only trigger on explicit occurrences, then a purely @dart=2,9 program would work on the new SDK and fail on the old SDK. That's why I think we should also make inferred types errors, no matter where parts of the inferred type comes from. Tracking whether a GFT comes from an opt-in library is likely impossible (if not quite Turing complete, then probably still intractible).

**Comment by leafpetersen** [comment]
> It's possible to write:
> 
> ```dart
> var x = <T>(T x) => x;
> var l = [x];
> ```
> 
> today and get an error. It does not use any explicit GFT as type argument, only the inferred one for the list literal/`l` variable.

Yes, this is covered exactly by the last bullet in my proposal.  As you point out, I got the current behavior wrong but the point is, local type inference continues to behave the same in opted out libraries.

**Comment by srawlins** [comment]
I have no implementation issues with this proposal. Local type inference continues to behave the same in opted out libraries.

**Comment by lrhn** [comment]
I'm not sure what "local type inference" means. If it's just inference inside a function body, then it's not sufficient to affect:
```dart
// top-level declarations.
final x = <T>(T x) => x;
final l = [x];
// or even
const x2 = someGenericFunctionDeclaration;
const l2 = [x2];
```
which are all inferred today and become compile-time errors because of the inferred `List<GFT>` type.

If it means "inference local to a library", then I'm not sure what that applies to (or rather, what it doesn't). The type of an expression, which is what we are doing inference from, is always local. Even if the expression happens to refer to a value declared in a different library, the expression itself occurs in the current library, and its static type is a local property (the type of a variable expression might differ from the type of the declaration it refers to, the latter is null-safe and the former is not).

So, I think "keep doing what we currently do for explicit declarations and for inferred types" in an opt-out library boils down to disallowing GFTs as type arguments and type parameter bounds anywhere in the library, whether the type it's part of is wholly or partly inferred, instantiate-to-bounds'ed, or written explicitly.

**Comment by leafpetersen** [comment]
> I'm not sure what "local type inference" means. If it's just inference inside a function body,

Local type inference is the process that fills in missing type parameters to generic methods and classes, and fills in the parameter and return types of function literals.

> disallowing GFTs as type arguments and type parameter bounds anywhere in the library, whether the type it's part of is wholly or partly inferred, instantiate-to-bounds'ed, or written explicitly.

I think this is fine.  To reiterate then, this is the following modification of your proposal above:

In the source code of an opted-out library:

- It is a compile-time error to use a generic function type (GFT) as a bound.
- It is a compile-time to use a GFT as a type argument anywhere. 
  - This includes inferred types
  - This includes types produced by instantiate to bounds
  - This include referring to typedefs which use a GFT as a type argument anywhere
- It is not an error to refer to or use a symbol from an opted in library which uses a GFT as a type argument or bound.
- It is not an error to export a symbol from an opted in library which uses a GFT as a type argument or bound.

**Comment by lrhn** [comment]
Yes. That LGTM!
