### ISSUE TITLE
Do We Really Need The Var Keyword In For-In-Loops?

### ISSUE THREAD

**Issue by fweth** [dart-lang/language#1480]
Is there a good reason for why e.g. `[for (i in [1, 2, 3]) i + 1]` isn't allowed (needs type or `var`) but `[1, 2, 3].map((i) => i + 1)` is fine (while `[1, 2, 3].map((var i) => i + 1)` is also possible)?  I know that I can always just `var` when I'm too lazy to specify a type, but somehow I don't like that style.  And I think the `[for (... in ...) ...]` notation has a nicer structure for reability than `[...].map((...) => ...)`, but if the type name is too long it becomes a bit convoluted.  Also, the values are just taken from the list, so their types should be already fully determined from the context as far as I can see.

[EDIT] BTW, I think it would be nice to write a function body in collection for, like `[for (var i in [1, 2, 3]){i += 1; return i;}]`

**Comment by leafpetersen** [comment]
> Is there a good reason for why e.g. `[for (i in [1, 2, 3]) i + 1]` isn't allowed (needs type or `var`)

It is allowed, it just means something different - specifically, it means re-use an existing variable named `i` instead of introducing a new one:

```dart
void main() {
  int i = 0;
  [for (i in [1, 2, 3]) i + 1];
  print(i);
}
```

cc @munificent for any comment on imperative code in element bodies.
