### ISSUE TITLE
Sum throw types

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/language#1487]
Related: https://github.com/dart-lang/language/issues/68 https://github.com/dart-lang/language/issues/349 https://github.com/dart-lang/language/issues/83

The ability to sum throw types for functions would make errors much more useful in Dart. In practice I see a lot of developers just not handle errors or go to great lengths to catch everything and rethrow them as an uber-error with a string enum and string message.

As I recall, Swift has the ability to sum error types, removing types that have been explicitly caught, and adding rethrow types in their place. This feature might look something like this in dart.

```dart
void main() {
  try {
    /// This would have a return type of [String]
    /// and a sum throw type of [BarException] or [BazException]
    final result = throwsBarBaz('');
  } switch (e) {
    case BarException:
      print('bar exception!');
      break;
      
    case BazException:
      print('baz exception!');
      break;
  }
}

/// Return type of [String]
/// Throw type of [FooException] or [BarException]
String throwsFooBar(String e) {
  if (e == 'foo')
    throw FooException();
  else if (e == 'bar')
    throw BarException();
  else
    return e;
}

/// Return type of [String]
/// Throw type of [BarException] or [BazException]
String throwsBarBaz(String e) {
  try {
    final firstPass = throwsFooBar(e);
    if (firstPass == 'baz')
      throw BazException();
    else
      return e;
  } on FooException {
    return 'foo';
  }
}

class FooException {}

class BarException {}

class BazException {}

```

**Comment by munificent** [comment]
Is the request here a better syntax for catching different types, or to have some kind of static checking of thrown types like checked exceptions? If it's just the former, you can already have multiple `on` clauses:

```dart
void main() {
  try {
    /// This would have a return type of [String]
    /// and a sum throw type of [BarException] or [BazException]
    final result = throwsBarBaz('');
  } on BarException catch (e) {
      print('bar exception!');
  } on BazException catch (e) {
    print('baz exception!');
  }
}
```

The current syntax is actually even shorter than your proposal. :)

If it's to have static checking of them, well there's #984. But that was closed because I think the world has generally decided that checked exceptions are a bad idea.

**Comment by lukepighetti** [comment]
Yes, this is for checked exceptions, so I will close in favor of #984
