### ISSUE TITLE
what the hell is that

### ISSUE THREAD

**Issue by mjc224000** [dart-lang/language#1495]
Describe the problem you are trying to solve, why is it hard to solve today?
Avoid describing the problem in terms of your preferred solution - you may want
to file a separate feature request issue related to this problem. If you'd like
a feature which exists in another language, describe the use cases.
![image](https://user-images.githubusercontent.com/26533672/110063634-78395b00-7da6-11eb-9b6c-75aed836eceb.png)
i think flutter  chose a wrong language

**Comment by mraleph** [comment]
This is not the right place to file an implementation issue. If you are experiencing an issue with your Flutter installation, start by filing a bug at https://github.com/flutter/flutter repo.
