### ISSUE TITLE
Null safety with increment and decrement operators

### ISSUE THREAD

**Issue by cirediew** [dart-lang/language#1496]
How to mark a variable non null with using the increment `++` and  decrement `--` operators?
Or is that only possible via the 'regular' way  `i = i! +1;`?

```dart
int? i;

void main() {
  i = 12;
  ++i!; //error
  i!++; //error
  --i!; //error
  i!--; //error

  i = i! + 1; //no error

  print(i);
}
```

**Comment by tatumizer** [comment]
This is not *the only* way. You can write it as `i!;i++` :-)

**Comment by mateusfccp** [comment]
@tatumizer It's not possible. `i` won't be promoted to non-nullable because it's not local.

**Comment by leafpetersen** [comment]
This is currently not supported directly.  [This](https://github.com/dart-lang/language/issues/1113) issue tracks the request to support `i!++` and friends.
