### ISSUE TITLE
Null safety inference ignores null check on map values

### ISSUE THREAD

**Issue by esDotDev** [dart-lang/language#1498]
Even though there is an explicit null check, this code will still not compile: 
```
final key = "foo";
final params = {key: "0"};
if (params[key] != null) {
  print(int.parse(params[key])); // requires ! to run
}
```

**Comment by tatumizer** [comment]
The compiler doesn't know much about the inner workings of the objects and their methods. What is knows about the variable `params` is that it implements the interface of Map (which includes `operator []`). The fact that each call to `params[key]` returns the same value every time is way over the head of the compiler. And in general, `Map` isn't obligated to return the same value - you can easily write your own Map implementation that returns different values on subsequent calls for the same key.

What's worse is that even if the compiler was that smart, then the logic behind the conclusion that the value stays the same would be quite brittle anyway: a small change to the code could break it. E.g. consider:
```
final key = "foo";
final params = {key: "0"};
String get s { params.remove(key); return ""; }
if (params[key] != null) {
  print(int.parse(s + params[key])); // the value of params[key] is null now
}
```

**Comment by esDotDev** [comment]
Ya, makes sense. Fairly ideal use case for ! operator then I suppose :) Thanks for clarifying!
