### ISSUE TITLE
Missing must have language features

### ISSUE THREAD

**Issue by CXCubeHD** [dart-lang/language#1506]
First to make sure, I don't think that Dart is that bad, but it really lacks a lot of must have features! If you guys don't add those following features, then the language will stay trash. But other than that, here we go :D

These are my suggestions and pls pls implement them if u want dart to be a good language

**1. Add Namespaces**

A big problem in C is that there is no way to instantiate the code. So if a developer decides to name a struct "CoolStruct" then other devs are forced not to use the same name.  C++ mostly fixed that by adding **namespaces** (for example std).
```
namespace A {
	class X {
		...
	}
}

namespace B {
	class X {
		...
	}
}

void main() {
	var x1 = A.X; // or A::X if u want, I like A.X more
	var x2 = B.X;
}
```

**2. Add default types like byte, char, short, long**

Ik some of u guys might say that you already have that, but it is a shame that the compiler gives me an error when I try to make this default types. HOW DOES THIS LANGUAGE NOT HAVE IT?

**3. Add Pointers**

Even though many people will not use that often, it is always good to have them. Even C# has them, and it kinda works there.

**4. Don't make a Java clone**

Java makes me aggressive, just don't make dart like Java. I was dreaming once of a wonderful language that doesn't have those C++ include errors and that is kinda like C++ and / or C#. And that's why I am writing that here. I WANT Dart to be a good language, I want my dreams to come true, and you can make that happen. But pls, don't make Dart to be like Java, Java is trash, not only because of the vm and poor performance, but also because of the language itself. Make it more like C# or C++, those are great languages, and that's because so many users use them.

**5. Why the hell can't I box a class?"**

It's a shame that I can't put a class into another class >:(

**6. Static Classes?**

Add static classes, they can be so useful :)*

**7. Add the ability to make fixed size arrays, just like in C, C++ or C#**

Would be nice if you could make fixed size arrays:
```
int i[3] = [0, 2, 3];
```

**8. Add UNSIGNED datatypes**

This is a must have, without this a language is trash (*java cough cough*)
```
unsigned int i = 10;
uint i2 = 99; // AND THIS PLS
```

**9. Add Macros like #region #define #if ...**
```
#define CoolMacro

...

#ifdef CoolMacro
int i = 10;
print(i);
#endif

...

#undef CoolMacro

#define MacroFunction(x) print(x);

MacroFunction("Hello World :D")
```

**10. Add the ability to overload operators from classes**

This is pretty self-explanatory.

**11. WHY IS THERE NO FUNCTION OVERLOADING?**

You have to be kidding me...
Even Java has that :(

**12. Make @override as a token and not as an annotation**

Not this:
```
@override
void MyFunc() { ... }
```
But this:
```
override void MyFunc() { ... }
```

**13. Add make overriding more as like a virtual function, just like in C#**

**14. Fix the problem in Flutter (the Dart language)**

When I try to access functions from a TextButton.onPressed function in flutter, then I can not access this or any other member, why the hell can't I do that? WHY? I can do that in every other language but not dart >:(

**15. Getters and Setters are very good implemented compared to C#**

Good Job 👍🏻 

**16. Accessing the base class should not be super but rather base instead, it makes more sence and there are less letters to write**

**17. Inheritable Constructors**

like in C++
```
class MyClass : public MyBaseClass
{
	using MyBaseClass::MyBaseClass;
}
```
(this might be wrong, I am not sure if that is 100% correct)

**18. Class References**

like in C++
```
MyClass& myClassRef = *myClassPtr;
```

**19. Change the dumb naming convention**

I really HATE the java naming convention! Member / Function names should start with an uppercase letter and only function / method variable names should be a lowercase lettter! The Java naming convention is really ugly, and if this stays in the dart language then it will be ugly too, pls change it now before it is to late!

Those are my suggestions that would make sence / would make this language a good language. If you are a part from the dev team then an answer would be nice. Normally I would say don't take it that serious, but this time u really should do that in order to compete with other languages. I hope that this will give you a vision on what the people really want :D

**Comment by leafpetersen** [comment]
> First to make sure, I don't think that Dart is that bad, but it really lacks a lot of must have features! If you guys don't add those following features, then the language will stay trash.

@CXCubeHD This post is riding the edge of disrespectfulness, and I'd like to ask that you keep it classy here.  It's totally legit to have opinions and share requests here, but we are strongly committed to keeping our issue tracker a respectful , and non-antagonistic place (and we have, and will take action to ensure this if necessary).  I **do** appreciate that you took time to be concrete and detailed though.  I don't think this issue is useful for tracking requests in its current form, I'd encourage you to file specific issues (after checking for existing issues, since many of these are already covered) for things that you feel strongly about.  Thanks!
