### ISSUE TITLE
kotlin 'when' conditional operator equivalent in dart

### ISSUE THREAD

**Issue by karthickr95** [dart-lang/language#1509]
Need a kotlin like 'when' conditional operator.

Need a optional break statement and when like concise syntax, because it is less boilerplate and like a  modern language. And a when or switch expression statement.

**Comment by mit-mit** [comment]
Moving to the /langauge repo, which is the main tracker for language evolution

**Comment by rodrigost23** [comment]
Isn't this a duplicate of #27?

**Comment by mit-mit** [comment]
Yes, that appears to be the case, @munificent ?

(Part of the reason for moving was to ensure things weren't duplicated, so thanks for the headsup @rodrigost23 )

**Comment by munificent** [comment]
It's always hard to decide which language issues are duplicates. If the request is just some kind of multi-way branching expression, then, yeah. But if @karthickr95 is specifically requesting syntax very close to Kotlin's then maybe not. In this case, though, I think it's similar enough to close as a duplicate.
