### ISSUE TITLE
Support generic arguments for (named) constructors

### ISSUE THREAD

**Issue by nex3** [dart-lang/language#1510]
Sometimes constructors need to have generics that don't appear in the class itself in order to fully express their type relationships. `new Map.fromIterable()` is a good example:

``` dart
Map.fromIterable(Iterable elements, {K key(element), V value(element)});
```

If `elements` has a generic type, the `key()` and `value()` callbacks are guaranteed to be passed an argument of that type, but there's currently no way to express that. Using generic types here blocks inference and makes it very difficult to use this API in strong mode. I propose that we be able to declare:

``` dart
Map.fromIterable<E>(Iterable<E> elements, {K key(E element), V value(E element)});
```

which would be called like `new Map<String, String>.fromIterable<int>(...)`. This syntax allows the user to omit the generic argument to the constructor while retaining it for the class itself if desired.

**Comment by mit-mit** [comment]
Moving to the main language repo

**Comment by eernstg** [comment]
Note that this issue (when located in the SDK repo) was already mentioned as one of the existing proposals for exactly this feature in https://github.com/dart-lang/language/issues/647#issuecomment-547080731. So we may wish to close one of these as a duplicate of the other one, to avoid fragmenting the discussion and the support.

**Comment by mit-mit** [comment]
Good point, let's continue the discussion in https://github.com/dart-lang/language/issues/647
