### ISSUE TITLE
Suggested addition for null safety

### ISSUE THREAD

**Issue by drpond1** [dart-lang/language#1524]
I am still in the middle of upgrading my code for null safety, but I have a recommendation about handling it.   I very much like the ability to specify my intent when specifying a type.   So I generally like your new approach.   Also, the recommendations about how to use it do seem to work in everything I have tried. 

However,  there are lots of cases where  the compiler
 cannot  infer that a non-nullable object has been defined before use.   I can create fake objects to initialize such a variable when the real initialization should be later.  
However,  it makes the code less readable and has some useless initialization when the object is complex.   I could use "late"...  but I much prefer to only use "late" when the argument about why the variable does not need to be initialized is non-trivial.   Having lots of useless null checks is  not appealing.     So I have a suggestion.

Suggestion:
    Have the compiler create a predefined constant object of type "Never",   say "never".     That object would be defined to throw an "attempt to invoke a method on an un-initialized variable" for all methods.     The programmer can use "never" for  initializing any variable that is "a bit late" and use "late" in other cases.  That is, they can use "never" when the argument of why something gets initialized is very simple.
  Now,  an exception could occur later than using a late object, because the never object can get assigned to other non-nullable variables.  But using values that are legal, but not real initializations has a similar issue (probably worse).    If used appropriately,  it will be easy to read the code and will have little extra overhead.  

  It is possible that the compiler could automatically make a never assignment when a non-nullable variable was not "promptly" initialized in object initialization.  This would make the code cleaner,  but would eliminate some compile time error messages that perhaps it should have kept.  So requiring that never be assigned explicitly is fine.

 There is a conflict with how Never is now used in that one could potentially return never in a function that was of type Never.   This  could  invalidate the compiler being able to tell that code was unreachable (because the function never returns).   So there would have to be a distinction  between "NeverReturns" and "Never".  

 I am not an expert on this topic,  and perhaps there is a reason this option was considered and rejected.  If so, a short response would be appreciated.

**Comment by mateusfccp** [comment]
@drpond1 Could you provide minimum examples of cases where the compiler can't infer that a non-nullable object has been defined before its first use?

**Comment by drpond1** [comment]
Seems to have lost my answer.  this might end up being a duplicate.

The typical case happens when I use boolean flags.  For example:

  bool  found=false;
  num  widgets;


  switch (..) {
        cases ....
        case ..
           found=true;
           widgets=62;
           ..
      cases ,,,
}
   if (found) {
       sitgglywiggly+= widgets;
}

  The compile can't tell that widgets is defined in all cases where found is true.
   So,  I just use  widgets=fakeInt for now.      num? widgets  would suggest widgets could be set to null,  so I won't do that.    late num widgets  suggests a complex analysis,  even though I can easily tell widgets is defined.    This works fine,  no real need to have the compiler be smarter.

   But note that if I could use never.   I would have the benefit that
      there would be an excpetion thrown at stigglywiggly if my analysis was wrong and widgets was not set.  There is no need for adding  a check for null pointer either.

**Comment by drpond1** [comment]
I can't get github to save my comments.   arg

**Comment by mateusfccp** [comment]
@drpond1 You can reopen it.

**Comment by drpond1** [comment]
I suppose I should mention that any proposed change should not happen as I have written things, in order to minimize disruptions to users.

Keep  "Never"  as meaning  never returns..
Introduce a new name for the bottom type,  and add a constant that aways throws for that type.

This way the only external change you have to make is updating the documentation describing
Never as a return "type" of a procedure.

**Comment by lrhn** [comment]
We already had an object which could substitute for all types, and which threw on any attempt to call methods on it: `null`.
People asked for a way to *avoid* the possibility of having those unpredictable run-time errors, so I don't see us introducing a new bottom-type-sentinel.

The bottom-type-sentinel value can't be of type `Never` because that type is defined to be empty. An expression of type `Never` *never* evaluates to a value, which is why we can use that in type promotion. Having a bottom type *below* `Never` breaks that too, because that value still has type `Never`. A type *above* `Never` with that property would be possible, but unlikely.

Let's say we introduce one, then people will ask to be able to *choose* whether to allow the sentinel or not. That's effectively what we have today with `Null`.

The one thing you don't get today is the ability to just use the value as if it's safe, and get the run-time error if it happens to be null.
So, what if you could define a variable as `String! x;` which is *nullable*, but allows you to call methods on the variable anyway, implicitly inserting a `!` (like in Swift)? Opt-in null-unsafety. Would that be a solution?

**Comment by drpond1** [comment]
I should have avoided the term "bottom type".   I also realize that my use of 
Never and never is a bit confusing,  because it is not the same as the current Dart
Never.  
 I am not an expert in this field, so I don't know whether what I proposed is possible.     However,  it looks very close to something that already exists.    

Haskell has the type Empty with the element undefined.  It also has Nothing and Maybe.  But, it is just speculation on my part as to whether what I am proposing is sound.   Also,  I am not sure to what extent it  conforms to an extension of the Dart semantics.

...
Ok.  Let me switch sides for a moment.

  A strong counter argument to my proposal  would say that  all of this is unnecessary because I could use "late" .    I just need to use some convention
that indicates that it is "just a bit late".  The added null checking is not a practically
  significant issue and my proposal has unnecessary assigns.   Code clarity is not an issue.   Any correctness argument failure shows up at the same or earlier in the code execution compared to my proposal.   Plus,  a programmer can still use fakeInt, fakeBool,  etc.  

Well, at least I think this might be the case.

**Comment by drpond1** [comment]
There are some cases where using late is not going to work.
For example,  you can't do the equivalent of
   List l = [never, never, never, 42]
     ( I should probably switch to saying 
       [uninitialized,  uninitialized, uninitialized, 42])

In such situations  one can use  List<num?>  l  = [null, null, null, 42]
   or  List<num> l =[fakeInt, fakeInt, fakeInt, 42];
The programmer just needs to be extra careful about unintended occurrences of null or using values that have not really been initialized.

**Comment by lrhn** [comment]
Correct. This is exactly what `null` is there for, and null safety was introduced in order to make people need to be extra careful about unintended occurrences of `null`. With null safety, you can't be *surprised* by the `null`, because the type tells you that it can be there. You can still write `l[0]!` if you just want to crash if `l[0]` is not initialized. The only catch is that you can *write* a `null` deliberately.
(You can use `[null, null, null, 42].cast<int>()` to get a `List<int>` which doesn't allow writing `null`, and which throws if you read an uninitialized entry).

**Comment by drpond1** [comment]
Thank you for describing the cast approach.

Two new points.
1.   There is another flaw in my proposal.
      The DART code needs to be able to translate into javascript, c, and possibly other languages.    Introducing a new value into a value type would require introducing
 new types  that would have the appropriate behavior for the translated code
     (e.g., class Late<E> which throws with a 
   get value.)  But if the point is to reduce spurious null checks,  this is likely going to be worse than using late.
   If someone really wants this behavior,  they may as will explicitly setup a Late class in DART and instead of the proposed int a=undefined  use   Late< int> a=Late();  But really
   they probably want late int a;

 2.  Despite all of my previous remarks, there is a real danger in using an initialized variable when the real initialization happens later in potentially different ways. 
     a=3  or a=fakeInt both have 
 potential problems.     in either case an unexpected value might propagate to somewhere else before the initialization method is invoked.    This is a case for using late with an unassigned value, even though you know the value can't be null.  
  (Of course, if initialization happens in one way  don't reset it in the initialization method and don't use fakeInt)    So  fakeInt is an approach that should often be avoided.
  (There are some circumstances where it may make sense -- such as  where you need to re-initialize a complicated object. )

**Comment by drpond1** [comment]
One final comment:

Better late than never.
