### ISSUE TITLE
Fix the link in Control Flow Collections spec

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#153]
See https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/feature-specification.md

> It's arguably better than the above code, but it's not obvious or terse. Adding spread syntax would let you do:

Fix the weblink address here, plaese

**Comment by munificent** [comment]
Done: https://github.com/dart-lang/language/commit/085440addcb3d6d66a323f394d977ca18c758a6d
