### ISSUE TITLE
Generic extending doesn't work as expected

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/language#1535]
The code below doesn't compile

```
class A {
  const A();
  
  A copyWith() {
    return A();
  }
}

class B<T extends A> {
  T value;
  
  B([this.value = const A()]) {
    value = value.copyWith();
  }
}
```

The version is the one from https://dartpad.dev/

**Comment by mraleph** [comment]
@cedvdb `T` can be a subclass of `A`, so you can't initialise a value of type `T` with a value of type `A` (e.g. consider that `A` is `Iterable` and `T` is `List`), so this is working as intended.

**Comment by natebosch** [comment]
https://github.com/dart-lang/sdk/issues/28477 requests the ability to refer to the "this" type of a class. There is a long discussion about the complications that might come with it.
