### ISSUE TITLE
Control Flow Collections Syntax for set literals

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#154]
[Control Flow Collections feature specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/feature-specification.md) in Syntax section describes syntax changes for list and map literals. Shouldn't it do the same for set literals?

**Comment by munificent** [comment]
It does now. :)

**Comment by sgrekhov** [comment]
@munificent, I still don't see any mention of set literals in Syntax section [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/feature-specification.md#syntax). Do I see the wrong spec?

**Comment by munificent** [comment]
Oops, sorry. You're right. The dynamic semantics are in there, but I forgot to update the grammar.
