### ISSUE TITLE
Dart is REALLY bad at inferring generic types

### ISSUE THREAD

**Issue by JohnGalt1717** [dart-lang/language#1542]
There is a whole series of problems that you can't solve right now because of Dart's failure to infer generics well like other languages and another series of problems where you're violating DRY because you're having to state the obvious generic types.

For instance:

```
class ActivePage<TPage extends Widget, TParameters extends PageParameters>
    extends Page<TPage> {
  final NavPageRoute<TPage, TParameters> route;
  final Map<String, String?>? parameters;

  ActivePage(this.route, {TParameters? parameters})
      : this.parameters = parameters?.toMap(),
        super(
          key: parameters == null
              ? ValueKey(route.route)
              : ValueKey(
                  "${route.route}?${Uri(queryParameters: parameters.toMap()).query}"),
        ) {
    assert(TPage != Widget);
  }
...
}

class NavPageRoute<TPage extends Widget, TParameter extends PageParameters>
    extends BaseRoute {
  final Iterable<String> parameters;
  final TParameter Function(Map<String, String?> map)? mapParameters;
  final TPage Function(TParameter params)? createPage;

  NavPageRoute(
      {required String route,
      this.parameters = const [],
      this.mapParameters,
      this.createPage})
      : super(route: route) {
    assert((this.parameters.isEmpty && this.mapParameters == null) ||
        (this.parameters.isNotEmpty && this.mapParameters != null));
  }
}
...
}
```
In this example ActivePage should KNOW it's TPage and TParameter types because It was passed BOTH into the route property.  C#, and Java both do this correctly. Even Typescript doesn't have an issue.  This is an outright blocker because if you have a function that passes in a NavPageRoute you can't get a strongly typed ActivePage back without also knowing the types.

Here's another example different problem:

```
class FieldModelBuilder<TModel extends FormModel>
    extends ModelBuilder<TModel, BaseEvent> {
  final FieldModelRebuild rebuildWhen;
  final Iterable<FieldModel<dynamic, dynamic>> Function(TModel form)? fields;
  const FieldModelBuilder(
      {this.rebuildWhen = FieldModelRebuild.change,
      this.fields,
      required TModel form,
      required Widget Function(BuildContext context, TModel form,
              BaseEvent? previousEvent, BaseEvent? event)
          builder,
      Function(BaseEvent? previous, BaseEvent? current)? listener,
      bool Function(TModel model, BaseEvent? previous, BaseEvent? current)?
          buildWhen});

}

```

In this case TModel is known because of the required parameter form which is of type TModel, yet dart passes an object into the buildWhen when called.  The property is early bound and thus determines the type (and if there was a conflict in a definition somewhere it should just error at compile time) and the function is late bound and thus should take the TModel. Even if you defined TModel in your implementation of the constructor the form property and the params of the buildWhen and builder methods would always have to agree.  But Dart doesn't know this and returns Object.

There are other cases I have run into but these are the 2 most obvious. The first is a really big problem because of how the Navigator 2 is structured and because there is no (real or static) reflection in dart.

Please improve the type inference on generics so that it can pick up and handle both of these cases.

**Comment by leafpetersen** [comment]
> In this example ActivePage should KNOW it's TPage and TParameter types because It was passed BOTH into the route property. C#, and Java both do this correctly. Even Typescript doesn't have an issue. This is an outright blocker because if you have a function that passes in a NavPageRoute you can't get a strongly typed ActivePage back without also knowing the types.

@JohnGalt1717 I can't parse out what you feel should work and what you feel doesn't work here.  Specifically to your example, if you call the `ActivePage` constructor with a typed first parameter, type inference will infer the type arguments to `ActivePage` for you.  If you have an example where you don't feel like it is doing so, a small repro would help me clarify what is going wrong.  I don't really understand where you're going with the `NavPageRoute` part of your question.  

More generally:
  - The type inference that Dart 2 does is almost identical to what C# does - it's based on the same theoretical framework (Scala also uses the same framework).  There are a couple of places around higher order functions (think the "fold" pattern) where we could do better by adopting some additional heuristics from C#, there are open issues tracking this.
  - Java type inference is, as best I know, substantially more limited than what Dart does.
  - TypeScript type inference on the other hand is *substantially* more powerful than what Dart does, at significant cost to compile times.  I'm a huge fan of the choices that TypeScript made *for its domain* but I'm quite comfortable with the choices that Dart has made for its domain.

Reading your question, I'm not entirely sure that you really mean this to be about inference, but again, I can't find enough specifics in your question to really figure out what you're asking here.

**Comment by JohnGalt1717** [comment]
@leafpetersen   In both examples given with the latest beta and the official v2.0 of flutter, Dart is NOT inferring the generics. It always has both parameters as the extends base definition. 

ie. in the ActivePage example TPage is always widget and TParameters is always PageParameters upon inspection and specifically, even if it was an inspection issue, using getIt to type match and create the right type, fails because it's attempting to create Widget and PageParameters instead of the specific implementations UNLESS the Generic types are explicitly defined on ActivePages.

In the second example, all TModel in the function definitions (buildWhen and builder) are always dynamic.

This: 

```
FormFieldModelBuilder<ContentForm>(
        form: viewModel.content,
        builder: (context, model, previousEvent, event) => TextIcon(
          text: Text(model.name.value),
          icon: Icon(FontAwesomeIcons.book),
        ),
      ),
```

Works.

This:

```
FormFieldModelBuilder(
        form: viewModel.content,
        builder: (context, model, previousEvent, event) => TextIcon(
          text: Text(model.name.value),
          icon: Icon(FontAwesomeIcons.book),
        ),
      ),

```
Does not. the model parameter in the builder: line is dynamic upon inspection and the Text(model.name.value) has a compile time error that it's Object? and thus it needs ! and .name doesn't exist. Even though viewModel.content is the explicit type of ContentForm.

Hence if it *should* be inferring types in these examples, then it's a bug that it isn't.

The same code written in C# results in the C# compiler correctly inferring the generics based on the parameters being passed in, both in the direct singular generic example of the FieldModelBuilder and the double generic inference for ActivePage based on the property.

If it matters here's my analysis_options.yaml file:

```
include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_assignment: error
    missing_return: error
    dead_code: info
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/generated_plugin_registrant.dart"

```

Hope that helps?

**Comment by kasperpeulen** [comment]
@leafpetersen Here is another example, very simple, just a regular map for a functor, but Dart won't infer the function parameter. This is not a higher-order function, just a regular function that accepts a callback.

```dart
Iterable<R> map<T, R>(Iterable<T> iterable, R Function(T t) transform) sync* {
  for (var t in iterable) {
    yield transform(t);
 }
}

void main() {
  // dart infers i as Object?
  print(map([1,2,3], (i) => i + 1));
}
```

**Comment by leafpetersen** [comment]
@kasperpeulen @JohnGalt1717 Thanks for the examples.  Yes, this is the case I mentioned above where we do not implement a heuristic that C# does implement.  Specifically (from memory, sorry if I get this somewhat wrong) they treat function typed parameters to a function as edges in a graph from the argument type to the result type and then topo sort the resulting graph and infer the parameters in that order.  This allows the inference result from the first argument of `map` in your example to flow into the second argument.  Essentially the heuristic says "Ah, in order to infer `R` from `transform`, we first need to infer `T` from `iterable`, so we'll start with the first parameter, then feed the result into the second parameter".  We do not (yet) implement this.

This is tracked [here](https://github.com/dart-lang/language/issues/731).

I'll close this out as a dup of that issue in favor of continuing further discussion there.  Feel free to re-open this if there are more pieces than are captured there.

**Comment by JohnGalt1717** [comment]
I agree that that likely addresses the second case, but I don't believe it addresses the first.  ActivePage should have known types because the first parameter fulfills all of the parameters by definition of what's passed in. There's no function involved, it simply isn't using the genertic parameters of the object passed in, which is clearly defined to define ActivePage. This is a major issue if you ever wanted to create a strongly typed navigation system with known parameters because without this you can't create the route definitions that map to the active page that generates the widget.

**Comment by leafpetersen** [comment]
> I agree that that likely addresses the second case, but I don't believe it addresses the first. ActivePage should have known types because the first parameter fulfills all of the parameters by definition of what's passed in.

@JohnGalt1717 I'm sorry, but I really do need more information to be able to help you here.  There are no uses of the ActivePage constructor in the code snippet that you posted, so I simply have no way of reconstructing what you are seeing.  To help further, I really need at least a concrete example of the code you see not being inferred - and it would be **vastly** more helpful to get a small self-contained snippet similar to what @kasperpeulen posted above.

**Comment by JohnGalt1717** [comment]
@leafpetersen 

```
final pageRoute = NavPageRoute<SomeInheritedWidget, SomeIneritedParameters>("/hi");

final activePage = ActivePage(pageRoute);
```

Will assert because TPage = widget when it should be SomeInheritedWidget.


Here's what SomeInheritedWidget is, just in case it isn't clear.
```
class SomeInheritedWidget extends StatelessWidget {
...
}
```

And SomeInheritedParameters is just:

```
abstract class PageParameters {
...
}

class SomeInheritedParameters extends PageParameters {
...
}

```

This however works:

```
void main(List<String> arguments) {
  final secondary = Secondary<Error, Error>();

  final primary = Primary(secondary: secondary);
}

class Primary<TObj extends Object, TObj2 extends Object> {
  final Secondary<TObj, TObj2> secondary;
  Primary({required this.secondary}) {
    assert(TObj != Object);
    assert(TObj2 != Object);
  }
}

class Secondary<TObj extends Object, TObj2 extends Object> {}
```

Whereas the above example does not.

**Comment by leafpetersen** [comment]
@JohnGalt1717 I put together a minimal closed example based on your fragments of code as follows:

```dart
class Widget {}
class StatelessWidget extends Widget {}

class ActivePage<TPage extends Widget> {
  final NavPageRoute<TPage> route;
  ActivePage(this.route) {
    assert(TPage != Widget);
    print(TPage);
  }
}

class NavPageRoute<TPage extends Widget> {
  NavPageRoute();
}

class SomeInheritedWidget extends StatelessWidget {}

void main() {
  final pageRoute = NavPageRoute<SomeInheritedWidget>();
  final activePage = ActivePage(pageRoute);
}
```

This code prints "SomeInheritedWidget" as expected.  I'm really not sure what else I can do for you here unless you can give me a complete example that I can reproduce your issue with.
