### ISSUE TITLE
Null handling deficiencies

### ISSUE THREAD

**Issue by JohnGalt1717** [dart-lang/language#1543]
Right now the dart analyser when faced with this:

```
final String? someValue;
...

String newValue = someValue == null ? 'test' : someValue;
```

Will error with nullability because it will tell you that you need to assert that someValue is not null right before the ;.  It's obviously not null and any trinary operator case like this should automatically be handled and known.

Second case:

Consider the following function definition:

`final bool Function()? someFunction;`

In every other language with null safety that I could find I can execute it conditionally like this: 

`someFunction?() ?? someothervalue;`

Dart doesn't allow that, but does allow it if the parent is null with the ?. operator.  It should allow the ?() syntax as this gets rid of a TON of cases of having to use the trinary operator.

Third Case:

```
asert(someObject != null);

CallSomething(someObject.someProperty);
```

Because of the assert someObject is known from this point forward to be not null and shouldn't require the ! assertion.

Fourth:

There are numerous cases of If statements where a property must not be null as a result but in the body of the IF it won't know that it can't be null and require ! when it's not possible and you've already handled it.

Please consider correcting all of these cases so that we can stop using ! when it really isn't needed. Thanks!

**Comment by tatumizer** [comment]
Issues 1 and 4 are the same issue, it's under discussion right now  (several threads - you can find them)
Issue 2: the syntax is someFunction?.**call**()
Issue 3: assert is not a normal runtime operator. Valid only during debugging.

**Comment by JohnGalt1717** [comment]
Ok on #1, and #4,
#2, ok... that's kinda gross and very not discoverable....
#3, ok, what's the suggested way of making the assertion other than when you first hit it? (this happens with GetIt and factoryParams that have to be nullable because of no reflection.)

**Comment by tatumizer** [comment]
Simply write `someObject!;` as a separate statement.
Assuming it's a local variable, of course. Otherwise, refer to 1) and 4) :-)

**Comment by natebosch** [comment]
For more discussion on 1 and 4 see https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields

2 - I'm not sure if we have an existing issue requestiong `nullableFunction?()` syntax. @leafpetersen are you aware of one? Should we file a new one?

3 - Assertions won't impact flow analysis because they might not happen, and since the null safety is sound it can't be used for flow analysis if it won't necessarily run. You can either use `someObject!;` as mentioned, or `if (someObject == null) throw  StateError('someObject should not be null here');`

**Comment by tatumizer** [comment]
@natebosch: where do you think I learned the syntax for `foo?.call()` ? Pretty sure I learned it from @leafpetersen ! LOL

**Comment by Cat-sushi** [comment]
cf. [#376](https://github.com/dart-lang/language/issues/376#issuecomment-567167570 "Should null-aware subscripting use `?[` or `?.[` syntax? · Issue #376 · dart-lang/language")
>  - There is concern about generalizing this. Specifically:
>      - We will almost certainly want to add a null aware call operator. Whatever we choose for null aware subscript, we will almost certainly want null aware call to be the same. That implies that we either have a?[b] and f?(x, y) and f?<T, S>(x, y) or we have a?.[b] and f?.(x, y) and f?.<T, S>(x, y). We would almost certainly have to resort to the same tokenization hack to avoid ambiguities here as well (e.g. {f?(x):y}).

**Comment by leafpetersen** [comment]
> 2 - I'm not sure if we have an existing issue requestiong `nullableFunction?()` syntax. @leafpetersen are you aware of one? Should we file a new one?

This is tracked [here](https://github.com/dart-lang/language/issues/404).

**Comment by natebosch** [comment]
Closing since I think there isn't anything left to track here. Please follow https://github.com/dart-lang/language/issues/404 and the various proposals at https://github.com/dart-lang/language/labels/field-promotion
