### ISSUE TITLE
null assignable to non-nullable variable

### ISSUE THREAD

**Issue by constorux** [dart-lang/language#1556]
I feel like the following should not be possible (as it assigns `null` to a non-nullable variable).

```dart
Map map = <String, String?>{'hello': null};
String id = map['hello']; // or map['bye'];
```
Nonetheless this first fails at runtime.
_(Excuse me in case this is expected behavior and I simply misunderstood dart null-safety)_

**Comment by tatumizer** [comment]
As soon as you change `Map map = <String, String?>{'hello': null};` to `var map = <String, String?>{'hello': null};`,
analyzer shows an error. The compiler treats "Map map" as a synonym of "Map<dynamic,dymanic> map". Obviously, this declaration takes precedence over whatever type is declared for the map literal. E.g. if you say `num x=5;` - you are explicitly telling the compiler to treat it as "num". Whan you say "Map", you are kind of telling the compiler that you want Map<dynamic>. 
More about it in [this comment](https://github.com/dart-lang/language/issues/1549#issuecomment-808898816) - the entire thread is about this issue.

**Comment by leafpetersen** [comment]
Right - this is a consequence of two things:
  - We still allow implicit downcasts from dynamic
  -  We treat raw types like `Map` with no type arguments as meaning implicitly instantiated with `dynamic`, i.e. `Map<dynamic, dynamic>`.

For the former, you can currently use `--no-implicit-downcasts` in your analysis_options.yaml to have the analyzer warn on this.

For the latter, [this issue](src/dart-repo/sdk/tests/co19/src/Language/Generics/) tracks some inference improvements we could do  (note the last paragraph of the opening comment).
