### ISSUE TITLE
Add supertype and interface of all enum types.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1566]
Dart `enum` declarations introduce a new type which implements only `Object`.
Enum types do have a common signature (a single `int get index` member), but not shared named interface.

We should introduce an interface (abstract class) named `Enum` which enum types extend, and which nothing else can implement.
That will allow genericity over enums, like `class EnumMap<T extends Enum, V> implements Map<T, V> { ... }`.
It can also be a place to hang static helper functions/a target for extension methods.

One issue with this is that you can instantiate that class with `EnumMap<Enum, int>` and not actually specify a specific enum. The class may mix enums of different types then, and get confused.

If we declare it as `abstract Enum<T extends Enum<T>>` we make it harder using `Enum` as a raw type, and we make it possible to later use the element type for something (probably mainly for extension methods).

**Comment by srawlins** [comment]
See also https://github.com/dart-lang/sdk/issues/35496 (duplicate? 15 upvotes), https://github.com/dart-lang/language/issues/1336 (duplicate?), https://github.com/dart-lang/language/issues/1007 (duplicate?)

**Comment by lrhn** [comment]
Good search there! This is a proposal for a concrete feature which solves the problems of those issues.

**Comment by kevmoo** [comment]
This shipped in 2.14 – right @lrhn ? Can close?

**Comment by lrhn** [comment]
Fixed!
