### ISSUE TITLE
Infer type in scope after function termination

### ISSUE THREAD

**Issue by jepperaskdk** [dart-lang/language#1573]
Apologies if this is already covered in an existing issue, but I'm not sure what to search for.
My question concerns how Dart infers the type of a variable, given testing the type.

Below, I test for `x is SubClass` and x is inferred as type `SubClass` in the scope enclosed by the test.
But testing for `x is! SubClass`, followed by a termination of the function (throw/return), does not infer the type as `SubClass` in the lines following.
I'm wondering if this is by design or could be implemented?
If types are inferred on scope basis, then I understand that this will be tricky.. and since it could perhaps change multiple times in the same scope.

Thanks in advance.

```
class Base {
  int a;
}

class SubClass extends Base {
  int b;
}

void myFunction(Base x) {
  if (x is SubClass) {
    int b = x.b;        // fine, x inferred as SubClass inside
  }

  if (x is! SubClass) {
    throw Exception('...'); // termination
    // return;    // or return
  }

  // Shouldn't dart know that x IS SubClass in scope now (after the above termination)
  int b = x.b;  // The getter 'b' isn't defined for the type 'Base'.
}
```

**Comment by lrhn** [comment]
It will work when you switch to Dart 2.12. The "Null Safety" release also improves promotion.

You can see that this code is not written for null safety since the `int a;` field would be non-nullable and uninitialized, which is a compile-time error with null safety.

**Comment by jepperaskdk** [comment]
Awesome - yes, it works with 2.12! Thanks.
