### ISSUE TITLE
accessin data in variable from another

### ISSUE THREAD

**Issue by arielszy** [dart-lang/language#1576]
hi. this threat has the purpose of knowing if theres a way to do this or adding in a future dart version.
this is what am trying to do:

var a='data';
var name ='a';

print(a);// output 'data'
print(name);//output 'a'
print('$a');// output 'data'
print('$name');// output 'a'

print('$$name');// output should be 'data' like in php

i want to do this in dart.

**Comment by lrhn** [comment]
There is no way in Dart to access a local variable at runtime using its name as a string (or any other representation of the name).

For an instance, class or top-level variable, you can potentially find it if you have access to the `dart:mirrors` library, which you won't have for any ahead-of-time compiled platform or for Flutter.

There is no plan to allow such reflective access in the future. Historically, Dart has moved *away* from features which require you to retain source names and declarations at run-time. They make it much harder to optimize away unused parts of a program when it's not statically detectable which variables are actually accessed.

**Comment by munificent** [comment]
Closing this because the question is answered.
