### ISSUE TITLE
Constructor tear off proposal implies use site eta-expansions

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1585]
[This section](https://github.com/dart-lang/language/blob/master/working/0216%20-%20constructor%20tearoffs/proposal.md#consequences) of the constructor tear-off proposal implies that an eta-expansion is done at every use site:

```dart
class C {
  final int? a, b, c, d, e, f, g, h, i, j, k, l, m;
  C({this.a, this.b, this.c, this.d, this.e, this.f, this.g, this.h, this.i, this.j, this.k, this.l, this.m});
}
...
 void Function() f = C.new; 
 // equivalent to:
 //    = (int? a, int? b, int? c, int? d, int? e, int? f, int? g, int? h, int? i, int? j, int? k, int? l, int? m) =>
 //      C(a: a, b: b, c: c, d: d, e: e, f: f, g: g, h: h, j: j, l: l, m: m);
```

This is misleading, since I don't think this has the right semantics, and is in any case not what I would suggest as an implementation strategy.  A more accurate description might be to describe it as being equivalent to the following:

```dart
class C {
  final int? a, b, c, d, e, f, g, h, i, j, k, l, m;
  C({this.a, this.b, this.c, this.d, this.e, this.f, this.g, this.h, this.i, this.j, this.k, this.l, this.m});
  C.new$tearoff((int? a, int? b, int? c, int? d, int? e, int? f, int? g, int? h, int? i, int? j, int? k, int? l, int? m) =>
       C(a: a, b: b, c: c, d: d, e: e, f: f, g: g, h: h, j: j, l: l, m: m);
}
...
 void Function() f = C.new$tearoff; 
```

**Comment by lrhn** [comment]
I believe it says that it can be implemented as a static function tear-off in the following section. If we defined canonicalization correctly, that should always be a valid implementation strategy.
I'll see if I can improve the wording.
