### ISSUE TITLE
Extension "auto import" as a language feature

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1595]
Cf. https://github.com/dart-lang/sdk/issues/38894, where this topic is being discussed in terms of tool support.

Consider the following program:

```dart
// ----- This is 'n023lib2.dart'.
class C {
  void classMethod() {}
}
extension E on C {
  void extensionMethod() {}
}

// ----- This is 'n023lib.dart'.
import 'n023lib2.dart';

C f() {
  var c = C();
  c.classMethod(); // OK.
  c.extensionMethod(); // OK.
  return c;
}

// ----- This is 'n023.dart'.
import 'n023lib.dart';

void main() {
  var c = f();
  c.classMethod(); // OK.
  c.extensionMethod(); // Error!
}
```

The behavior is as specified, but the outcome is that (1) `C` seems to have members `classMethod` and `extensionMethod` when imported directly. But (2) only the member `classMethod` survives when `C` is the type of an expression using an imported entity, but the extension `E` isn't imported directly.

In other words, **class instance members survive, but extension members get lost, for a receiver whose type is not imported**.

This is a serious deviation from the mental model that we may otherwise like to apply: "An extension adds members to a type".

Maybe we could change the extension rules such that an extension `E` is _accessible_ to a receiver of type `T` when that type is declared in a library where `E` is accessible. (Note that we're not talking about the location where the type itself is declared, e.g., we are not talking about `dart:core` when `T` is `int`; we are talking about the location where it is specified that that receiver has type `T`, possibly as a type `T0` with type variables that are replaced by actual type arguments in order to come up with `T`.)

For instance, if `x` is a top-level or instance getter declared in _L1_ to have return type `T`, and `E` is imported into _L1_ or declared in _L1_, then if `x` is used in _L2_ != _L1_ then `x.foo()` may be resolved as `E0(x).foo()` where `E0` denotes `E` (even though `E` is not imported into _L2_, so there is no surface syntax that denotes `E`).

Similarly when `f` is a top-level function or instance method declared in _L1_ where `E` is imported into _L1_, then `f(42).foo()` may be resolved as `E0(f(42)).foo()`, where `E0` denotes `E`, if the return type of `f` (possibly after inference) matches the on-type of `E`. The point is again that the return type of `f` is declared at a location where `E` is in scope.

Note that this differs from the proposals in https://github.com/dart-lang/sdk/issues/38894, because they are concerned with getting tool support for importing `E`. For instance, we could have two expressions `x` and `y` with the same type, but they could be imported from two different libraries, and then they could have different sets of accessible extensions. If we simply auto-import all the extensions as we go, we may create an ambiguity because this will make the same set of extensions accessible for `x` and `y`.

Of course, the ugly question about the treatment of private declarations arises here, just as it does for class interfaces: If `_E` (or an anonymous extension) is declared in _L1_, should we be able to invoke members of `_E` in _L2_ on `x`, just because `x` is also declared in _L1_? I'd say "no!", and prevent access to the members of private/anonymous extensions using this mechanism. Hah. ;-)

**Comment by kasperpeulen** [comment]
I think just allowing people to write:

c.exte... 

And now get autocompletion for extensionMethod and when applying the autocompletion gettingauto import, sounds good enough to me.

I think the mental model of extension method should be that it is just a static/top level function, but much easier to write and compose (and even overload). 

It basically makes it possible to use pure functions allmost as powerful as functions in FP languages.

**Comment by eernstg** [comment]
@kasperpeulen wrote:
> .. get autocompletion for `extensionMethod` and when applying the
> autocompletion getting auto import, sounds good enough to me.

The reason why I'm exploring the idea that we could handle this issue with something other than regular imports is that those additional imports could pollute the namespace with a lot of extra elements that we wouldn't otherwise have. That could cause conflicts, or it could simply make completion lists so long that they are inconvenient to use.

Here is an approach using extension types (they do not exist, yet, but we're [considering them](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification.md)):

```dart
// ----- This is 'libA.dart'.
extension type Age on int show int {
  bool get isTeen => 12 < this && this < 20;
}
class Person {
  Age get age => 42; // Returns an `int`, viewed as an `Age`.
}

// ----- This is 'libB.dart'.
extension type Width on int show int {
  bool get isWide => this > 4096;
}
class Bitmap {
  Width get width => 1024; // Returns an `int`, viewed as a `Width`.
}

// ----- This is 'main.dart'.
import 'libA.dart';
import 'libB.dart';

void main() {
  Person p = ...;
  if (p.age.isTeen) print('What's up, fam?');
  else print('How do you do, ${p.name}?');
  Bitmap b = ...;
  if (b.width.isWide) ...;
}
```

The extension types `on int` are just like `int` except that they add some extra members (like `isTeen` and `isWide`). We are actually returning an `int` object from both getters, but when they are typed as those extension types, we declare that they should be extended with those particular extension methods. So we can do `p.age.isTeen`, but `b.width.isTeen` is a compile-time error, and similarly for `b.width.isWide` (OK) and `p.age.isWide` (error).

We could have declared the return type as `int` for `age` as well as `width`, and we could have declared both `isTeen` and `isWide` as regular extension methods on `int` (that is, we could have used the `extension` declarations that we have today). This would have allowed `p.age.isTeen` and `b.width.isWide`, but it would also allow `p.age.isWide` and `b.width.isTeen`.

However, if we do use an extension type to handle this situation then we are _closing_ the door for extension methods (again: today's `extension` declarations), because they apply to expressions of type `int`, and the return type of `age` is no longer `int`, it is `Age`, and similarly for `width`.

It would be nice if we could somehow enable the _relevant_ extension methods for any given expression used as a receiver, without piling on a huge number of irrelevant ones.

**Comment by eernstg** [comment]
Actually, we could simply twist the specification of extension types such that it will enable execution of extension methods based on the on-type for regular `extension` declarations:

```dart
extension OpenE on int {
  void openMethod() {}
}

extension type ClosedE on int {
  void closedMethod() {}
}

extension OtherExtension on int {
  void otherMethod() {}
}

void main() {
  OpenE openE = 42;
  ClosedE closedE = 43;

  // An `int` can use a regular extension method.
  44.otherMethod(); // OK.
  44.openMethod(); // OK, `OpenE` admits implicit invocations.
  44.closedMethod(); // Error, `ClosedE` does not admit implicit invocations.

  // `OpenE` uses the on-type to determine extension method applicability.
  openE.otherMethod(); // OK, `OtherExtension` applicable to `int`.
  openE.openMethod(); // OK.
  openE.closedMethod(); // Error, `ClosedE`/implicit.

  // `ClosedE` uses `ClosedE` to determine extension method applicability.
  closedE.otherMethod(); // Error, `OtherExtension` not applicable to `ClosedE`.
  closedE.openMethod(); // Error, `OpenE` not applicable.
  closedE.closedMethod(); // OK.
}
```

I think it makes sense for a regular `extension` to admit implicit invocations _as well as_ admitting extension method invocations based on the on-type. An `extension type` is then more strict in two ways: It does not admit implicit invocations, and it does not admit invocations of extension methods from other extensions based on the on-type.

**Comment by bwilkerson** [comment]
> ... those additional imports could pollute the namespace ...

Another possible way to minimize this problem is that when code completion needs to add an import for the extension it could include a `show` clause that only lists the extension.

I have no idea which solution is better because I haven't thought through the tradeoffs, but just wanted to mention the alternative.

**Comment by eernstg** [comment]
@bwilkerson wrote:
> it could include a `show` clause that only lists the extension

True, and it could even use a fresh import prefix, such that the extension can be denoted even in the case where its name clashes with a declaration in the current library.

**Comment by munificent** [comment]
This is a really interesting proposal. I agree that there is an unpleasant symmetry right now when accessing members on an object whose type hasn't been imported. However, I don't think this proposal is the direction we want to go.

It means that the import (not export) scope of a library now affects its *public* API. Removing an import (not export!) from a library could break external users of the library. I don't think we want to go there.

It would almost be nice if we could fix the asymmetry in the *other* direction. Make it so that *instance* members are *not* accessible unless you import the type. You can only access members on types that are in scope, period. But that would obviously be *horrendously* breaking and also probably just a catastrophic usability failure. But it would be consistent! ;)

I think the least-bad solution is probably just to make our tools have smarter support for automatically inserting imports and learn to live with a little asymmetry. Extensions are different in other ways too (for example, you can define extensions on specific *instantiations* of a generic type), so it's not the end of the world if they are different in an another minor way.

**Comment by eernstg** [comment]
@munificent wrote:
> the import (not export) scope of a library now affects its _public_ API

I think the original idea [here](https://github.com/dart-lang/language/issues/1595#issue-863920762) will not be very useful, because of the interactions with imports/exports that you mention, and more. It's too crazy. ;-)

But if an author of a function/method/getter declaration wants to bundle some extensions along with a more mundane return type then they can do it as I mentioned [here](https://github.com/dart-lang/language/issues/1595#issuecomment-824663051) using extension types. Here is the core of that example:

```dart
// ----- This is 'lib.dart'.
extension type Age on int show int { bool get isTeen => 12 < this && this < 20; }
class Person { Age get age => 42; String get name => ... }

// ----- This is 'main.dart'.
import 'lib.dart';

void main() {
  Person p = ...;
  if (p.age.isTeen) print('What's up, fam?');
  else print('How do you do, ${p.name}?');
}
```

The extension type `Age` is used to extend the `int` returned by `Person.age` with some extension methods, and they will not drop off even if the value of type `Age` is obtained in a situation where `lib.dart` has not been imported directly. This gives the author of `Person` a fair amount of power to deliver that `int` together with a specific set of extension methods that may be appropriate to use on an `int` which was obtained in this way.

**Comment by eernstg** [comment]
Closing, this wasn't a very good idea. We still want to solve the problem, though. ;-)
