### ISSUE TITLE
With the generic function types as type arguments, how do we check legacy libraries?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1603]
Cf. https://github.com/dart-lang/sdk/issues/45836 where this issue was raised.

It is an error to have a _declaration_ of a type alias in a legacy library where the 'non-function type alias' generalization is used, but it is allowed for a legacy library to import a library with null-safety enabled where such a declaration occurs, and it is OK for the legacy library to _use_ that declaration. A similar issue arises for the use of generic function types as type arguments.

Consider the following example:

```dart
// ----- This is 'lib.dart'.
class A<X> {
  void showX() => print(X);
}
class B<X> extends A<X Function<Y>()> {}
typedef F = void Function<Z>();

// ----- This is 'main.dart'.
// @dart = 2.9

import 'lib.dart';

List<A<U>> f<U>(A<U> a) => [a];

void main() {
  var b = B<int>();
  b.showX();
  A a = b;
}
```

This program is accepted by the analyzer with no errors or warnings, and it compiles and runs with no errors on `dart`, even though it contains

1. a declaration of the local variable `b` whose static type has a "forbidden" type argument in its immediate superinterface `A<void Function<Y>()>`  (because a legacy library does not support the `generic-metadata` feature), and
2. a variable declaration named `a` where the static checks on the initializing expression require a non-trivial use of a type argument which is a generic function type: `A<int Function<Y>()> <: A<dynamic>`.

Consider this variant of `main` (other declarations, imports unchanged):

```dart
void main() {
  var xs = f(b); // Error.
}
```

With this program, an error arises in both the analyzer and the CFE.

Another variant:

```dart
void main() {
  var ys = <F>[]; // Disagreement among tools.
}
```

With this program, the CFE emits a compile-time error, but the analyzer accepts the program.

So the currently implemented approach is to allow types with type arguments that are generic function types to occur in a legacy library (as the type of an expression, or a supertype of such a type), and they can take part in subtype/assignability checks that only produce a result when the subtype checker is able to handle those types.

But it is a compile-time error if type inference causes a generic function type to be introduced as an actual type argument in an expression in a legacy library, and (of course) also if such type arguments are written explicitly in a legacy library.

The 'small-features 2021Q1' feature specification does not specify the treatment of the new kind of types in a legacy library  (cf. [this section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/small-features-21Q1/feature-specification.md#allow-generic-function-types-as-type-arguments-and-bounds)).

**I'd recommend that** we keep it an error for a generic function type to occur as a type argument  in a legacy library (so both `<F>[]` as in the example above and `<void Function<Y>()>[]` is an error), also when this occurs as a result of type inference (so `f(b)` is an error), but it is not an error for an interface type to be used in a legacy library even when it has a superinterface which uses a generic function type as a type argument. **So we can handle, but not create, a type where a type argument is a generic function type, in a legacy library.**

@leafpetersen, @munificent, @lrhn, @jakemac53, @stereotype441, @natebosch, WDYT?

**Comment by lrhn** [comment]
Mixed mode is hard. 

I'd say it is still invalid to *statically* provide a generic function type as a type argument in a pre 2.14 library.

That doesn't mean you can't do it dynamically. If you have `R invoke<R, T>(R Function(T) f , T a) => f(a)` and a post 2.14 library calls `invoke(int Function(int), T Function<T>(T)>((f) => (int x) => f<int>(x), <T>(T x) => x)`, that should probably be allowed to run without any run-time checks interfering.

It was always a complication that there were subtypes of the bound that couldn't be used as type arguments, and it was only because there was no way to create a type argument with that type at all that we could globally enforce the restriction without run-time checks. We still don't want run-time checks, but we should keep all the existing static checks in legacy libraries.

**Comment by leafpetersen** [comment]
> The 'small-features 2021Q1' feature specification does not specify the treatment of the new kind of types in a legacy library (cf. [this section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/small-features-21Q1/feature-specification.md#allow-generic-function-types-as-type-arguments-and-bounds)).

I don't understand.  This [section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/small-features-21Q1/feature-specification.md#mixed-mode-programs) is intended to cover this.  What's missing?

**Comment by eernstg** [comment]
> This [section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/small-features-21Q1/feature-specification.md#mixed-mode-programs) is intended to cover this. What's missing?

My bad! I saw the [section on generic functions as type arguments](https://github.com/dart-lang/language/blob/master/accepted/future-releases/small-features-21Q1/feature-specification.md#allow-generic-function-types-as-type-arguments-and-bounds), and the [next section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/small-features-21Q1/feature-specification.md#allow--as-overridable-operator) was about `>>>`, and it didn't occur to me that there could be additional material about generic functions as type arguments outside that first section. Also, a search for 'migration' and 'legacy' gave no hits, and I thought that it was urgent to do something about it if we actually didn't have any rules about the treatment of this feature in a legacy library.

It could still make sense to take another look at this, however:

In https://github.com/dart-lang/sdk/issues/45836, we have the case where an opted-in library contains the following:

```dart
// 'lib.dart'.
class D<T> {}
typedef A = D<Function<T>()>;
```

and and opted-out library imports 'lib.dart' and contains an instance creation `A()`. It is not obvious to me whether that's 'a use of a GFT [generic function type] as a type argument' in a legacy library because that includes 'Types produced by expanding references to type aliases into their aliased type' (which makes it an error), or a use of 'a symbol from an opted in library which uses a GFT as a type argument or bound' (which makes it a non-error).

**Comment by eernstg** [comment]
The rules turned out to match the description after "I'd recommend" in the initial comment, and the issue in https://github.com/dart-lang/sdk/issues/45836 is an error. Closing.
