### ISSUE TITLE
Null safety doesn't detect nullability for class members 

### ISSUE THREAD

**Issue by shinayser** [dart-lang/language#1630]
In this code, null safety works flawlessly and auto-detects that the `someBool` variable is not null at this point:

```dart
void main(List<String> arguments) async {
  
  bool? someBool;
  
  
  if (someBool!=null) {
    IntegerWrapper(integer: someBool? 1 : 0); //Works nicely without the need of the bang (!) operator
  }
  
}
```

But here it doesn't work:

```dart
class JustSomeClass {
  final bool? someBool;

  JustSomeClass({this.someBool});

  void build() {
    // Case One
    if (someBool != null) {
      IntegerWrapper(
          integer:
              someBool! ? 1 : 0); // someBool here needs an ! to work, but why?
    }

    //Case Two
    IntegerWrapper(
      integer: someBool != null ? (someBool! ? 1 : 0) : 666, //And here too!
    );
  }
}
```

This is really bad behavior and in Flutter we use class members all the time, and having to use the bang operator for thoses cases are really bad.

Here is the IntegerWrapper class:

```dart
class IntegerWrapper {
  int integer;

  IntegerWrapper({required this.integer});
}
```

Is all this a bug or a intended behavior?

**Comment by Cat-sushi** [comment]
see [label:field-promotion](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion "Issues · dart-lang/language").

**Comment by shinayser** [comment]
Seem that this issue is already beeing commmented. I will close the issue then.
