### ISSUE TITLE
Type promotion fails in some cases

### ISSUE THREAD

**Issue by jthlim** [dart-lang/language#1653]
In the following code, the compiler fails with:

> The argument type 'Fruit' can't be assigned to the parameter type 'T' - line 11

This is despite the `if (Fruit is T)` check right before.

```dart
class Fruit {}

class Apple extends Fruit {}

class FruitList {
  final fruits = <Fruit>[];

  List<T> fruitsOfType<T>() {
    final result = <T>[];
    for (final fruit in fruits) {
      if (fruit is T) result.add(fruit);  // Fails on this line.
    }
    return result;
  }
}

```

**Comment by mateusfccp** [comment]
Type promotion does not work with fields.

You may be interested in the [field promotion](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion) label.

**Comment by jamesderlin** [comment]
> Type promotion does not work with fields.

In this case, `fruit` is a local variable.

I think that this is https://github.com/dart-lang/sdk/issues/34018.  `Fruit` and `T` are not related types, and only subtypes are promoted.

Using `List<T> fruitsOfType<T extends Fruit>()` would work.

**Comment by lrhn** [comment]
Yes, this is working as intended because the type `T` is unrelated to `Fruit`. "Promoting" `fruit` to `T` would make it not be a `Fruit` any more. The solution proposed by @jamesderlin should work, because `T` with bound `T extends Fruit` *is* a subtype of `Fruit`.

**Comment by jthlim** [comment]
While making <T extends Fruit> in this case does work, wouldn't you want this for supporting 'implements' ?

Could the representation internally support that fruit is both a T and a Fruit? i.e. could it represent the known type of 'fruit' at that stage as a class that extends Fruit and implements T ?

This should also enable a slight variation of this code:

class Aspect;

class MyObject;

class ObjectWithAspect extends MyObject implements Aspect {
  ...
}

class MyObjectList {
  final objects = <MyObject>[];

  List<T> objectsWithAspect<T>() {
    final result = <T>[];
    for (final object in objects) {
      if (object is T) result.add(object);
    }
    return result;
  }
}

Where in this case, T is NOT a subclass of MyObject, but having to write (object as T) right after checking if (object is T) seems a little messy code wise :)

**Comment by jamesderlin** [comment]
Why can't you use `List<T> objectsWithAspect<T extends Aspect>()`? `T extends Base` in generics doesn't mean that `T` literally uses `extends` in its class definition; it could use `implements` or `with`.

**Comment by jthlim** [comment]
Your suggestion: List<T> object objectsWithAspect<T extends Aspect> doesn't work?

IIUC, you're suggesting:

```
class Aspect {}

class MyObject {}

class MyObjectList {
  final objects = <MyObject>[];

  List<T> objectsWithAspect<T extends Aspect>() {
    final result = <T>[];
    for (final object in objects) {
      if (object is T) result.add(object);
    }
    return result;
  }
}
```

This produces the same error message: `The argument type 'MyObject' can't be assigned to the parameter type 'T' - line 11`

The base question I think still holds -- when I write: `if (object is T) { .... }`, then why can I not assume within the block that object is a T? The requirement that T is also a MyObject seems like an unnecessary restriction?

I was wondering whether the compiler could internally represent it as an object that is both a MyObject and T using the current type system (promoted type = MyObject implements T).

**Comment by lrhn** [comment]
When `T` has a bound, it's impossible to *promote* with the current Dart type system.
In the case:
```dart
void foo<T extends Aspect>(MyObject o) {
  if (o is T) { 
    // There exists no type which is both Aspect and MyObject which o can have here.
  }
}
```
There is no type in the Dart type system which we can promote `o` to in this example, and which allows both using methods of `Aspect` and of `MyObject` (and even if they did have a common sub-type, we wouldn't be able to assume that it was the only possible one).
So, if we changed the type of `o`, it would not longer be seen as implementing `MyObject`. Dart never "promotes" in a way which removes information, so there is nothing we can do here.

The situations where we could potentially promote is when `T` has no bound, or it has a bound which is a supertype of the other type we are promoting from. (If the type variable bound is a subtype of the original variable type, we already do promote).
That is:
```dart
void foo<T>(MyObject o) {
  if (o is T) { 
    /// Could promote o to (T & MyObject)
  }
}
```
The Dart type system has limited intersection types where all but one of the types need to be type variables.
We can express `T & MyObject` as a type which is a subtype of `T` and of `MyObject`.

We currently only promote from type variable to intersection type (when the promoted type is a subtype of the bound/previously promoted intersection type), not in the other direction, because the rule is that we only promote if the type we compare to is a subtype of the original type, or (if the original is a type variable) if the type we compare to is a subtype of the variable's bound. Here `T` is not a subtype of `MyObject`, so the rule doesn't fit.
We could technically introduce an extra rule saying that you can promote a type `S` to a type variable `X` with bound `B` if `B` <: `S`, getting `X & S` (which is a subtype of both `X` and `S` as needed). We don't currently have any plans to make such a change.

**Comment by jamesderlin** [comment]
> The base question I think still holds -- when I write: `if (object is T) { .... }`, then why can I not assume within the block that object is a T? The requirement that T is also a MyObject seems like an unnecessary restriction?

BTW, that's pretty much what I asked in https://github.com/dart-lang/sdk/issues/34018#issuecomment-782767554, so also see eernstg's reply there.

**Comment by jthlim** [comment]
> There is no type in the Dart type system which we can promote o to in this example, and which allows both using methods of Aspect and of MyObject (and even if they did have a common sub-type, we wouldn't be able to assume that it was the only possible one).

In dart, I can write:

```dart
  abstract class PromotedType implements MyObject, Aspect {}
```

Which would give PromotedType access to both MyObject and Aspect methods and not make any further assumptions? This seems like it could be representable by the current type system?

I'm not familiar enough with the language or compiler, but the compiler could generate/represent these types in flow control cases where `is SomeType` is used?

```dart
  if (myObject is UnrelatedType1) {
   // myObject can now assumed to be MyObject and UnrelatedType1
   if (myObject is UnrelatedType2) {
     // myObject can now assumed to be MyObject, UnrelatedType1 AND UnrelatedType2.
     // ie. a class that would have a definition:
     // abstract class PromotedType implements MyObject, UnrelatedType1, UnrelatedType2 {}
   }
  }
```

I have no idea how this could/might work with a generic T though.

**Comment by eernstg** [comment]
> In dart, I can write:
> 
> ```dart
> abstract class PromotedType implements MyObject, Aspect {}
> ```

Yes, but the run-time type of an object `o` in Dart is determined by the instance creation expression (so if `C` denotes a class with a suitable constructor, `C()` or `new C()` or `const C()` will yield an instance of the class `C`). The object `o` will not have any type that isn't the run-time type (here: `C`) or a supertype thereof. So if `PromotedType` isn't directly or indirectly among the classes that `C` has in its `extends`, `with`, or `implements` clause then `o is PromotedType` will yield false.

You could have used an intersection type, if they were supported in Dart:

```dart
  if (myObject is UnrelatedType1) {
    if (myObject is UnrelatedType2) {
      // `myObject` could be promoted to `MyObject & UnrelatedType1 & UnrelatedType2`,
      // and all members of those types would be available on `myObject`.
      myObject
          ..unrelatedMethod1()
          ..unrelatedMethod2()
          ..myObjectMethod();
    }
  }
```

However, Dart doesn't support intersection types except for some special cases, and it is likely to be a major effort to support intersection types in general.

For instance, what would you do if `UnrelatedType1` has a member `double Function() get foo` and `UnrelatedType2` has a member `int foo() {}` and we call `myObject.foo()`? It would work both with type `UnrelatedType1` and with type `UnrelatedType2`, but they would do different things and the result would have different types.

Surely we can sort out this kind of problem (most likely `myObject.foo()` would be a compile-time error), but it illustrates that there is a cost (in terms of language complexity, and possible run-time performance). So we might not want to have intersection types in general, and even if we do want it, there would be a lot of work to do before we have it.

**Comment by mateusfccp** [comment]
I would love to have intersection types.
