### ISSUE TITLE
Dynamically typed Dart should give no warnings

### ISSUE THREAD

**Issue by Wdestroier** [dart-lang/language#1656]
Hi! We all know that Dart supports dynamically typing.

I've recently read the effective dart guidelines ( https://dart.dev/guides/language/effective-dart/design ) and it highly discourages not typing methods parameters and return types.
"DO type annotate fields and top-level variables if the type isn’t obvious". 

DartPad gives an `info` when the function (or method) return type is not specified.
"The function main should have a return type but doesn't"

Here is an example code:
```dart
import 'dart:math';

var random = new Random();

main() => luckTest();

luckTest() {
  var number = random.nextInt(11);
  
  printLuck(number == 7);
}

printLuck(lucky) {
  if (lucky) {
    print('Today is your lucky day!');
  } else {
    print('Unlucky');
  }
}
```

Dart is a JavaScript-like language. Effectively, it was made to replace JavaScript. The simplicity of untyped languages allow fast prototyping and development. That's why Dart must have a mode to accept code which is not typed and give no warnings. Public libraries do have to type the exposed top-level functions, class methods and fields.

I hope this feature suggestion is interesting :)

**Comment by mateusfccp** [comment]
You can disable this info by [configuring your linter the way you want](https://dart.dev/guides/language/analysis-options).

The lint rule in question here is [always_declare_return_types](https://dart-lang.github.io/linter/lints/always_declare_return_types.html).

However, Dart 2, as far as I am concerned, don't have the same focus as Dart 1, and thus encourage the user to work in a more safe way.

**Comment by lrhn** [comment]
As mentioned, this is a linter hint, not a language feature. You can turn it off in a number of ways:

Add to `analysis_options.yaml`:
```
analyzer:
  errors:
    always_declare_return_types: ignore
```

Add to the Dart file, at the top:
```
// ignore_for_file: always_declare_return_types.
```
or add on the line above the warning:
```dart
// ignore: always_declare_return_types.
```

Or, you can ignore it yourself. It's just a hint, and if you are doing quick prototyping with dynamic typing, you are free to ignore any hints and warnings you get. The are just that, not errors.

**Comment by Wdestroier** [comment]
Thanks for clarifying, Mateus and Lasse
