### ISSUE TITLE
Constructor tear-off through over-generic alias - constant or not?

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1664]
If I define `typedef Extra<T, S> = List<T>;` (then I'm being silly, but it's not prohibited, so) then I can write:
```dart
void foo<X>() {
  var c = Extra<int, X>.filled; // constructor tear-off of `List<int>.filled`
}
```
* Is `Extra<int, X>.filled` a compile-time constant? (likely not, since it syntactically contains a non-constant type.)
* Is `Extra<int, X>.filled` canonicalized to the same object a `List<int>.filled`? (... maybe?)

The issue here is that we *can* statically expand the alias and recognize that the target is a compile-time constant type.

We *have not* considered whether `const Extra<int, X>.empty()` is actually a compile-time constant expression. We should have done that when we introduced class aliases. The rules for constant object creation expressions only refer to classes, not aliases, and the *class* denoted here is constant, even if the alias invocation contains unused non-constant type arguments.

So, what should we do?
I propose:
* `Extra<int, X>` is *not* considered a constant type, even if its expansion is one.
* Anything we do on that type should use the rules we use for non-constant types.

That means:
* `const Extra<int, X>()` is a compile-time error.
* `var c = Extra<int, X>.filled;` is not canonicalized with `List<int>.filled`. It's treated just like `List<Y>.filled` where `Y` happens to be bound to `int`.

I'll try to specify this in the constructor tear-off document. We might want to update the spec on constants.

**Comment by eernstg** [comment]
At first, it does sound very reasonable that we'd make `Extra<int, X>` and its ilk non-constant.

However, we do allow constants with unused non-constant parts in some cases today:

```dart
extension on bool {
  int operator -() {
    print('Side-effect!');
    return 2;
  }
}

class C {
  final Object i;
  const C(bool b): i = b ? 0 : -false;
}

void main() {
  const C(true);
}
```

Is there any specific downside to allowing `const Extra<int, X>()` and the other, similar examples?

**Comment by leafpetersen** [comment]
Note that the CFE and the analyzer currently disagree on whether `const Extra<int, X>()` is an error or not.

I'm fine with the proposal from @lrhn

**Comment by lrhn** [comment]
We do not allow a constant (direct) constructor invocation to contain non-constant argument expressions, even if those arguments do not become part of the constructed value, nor do we allow non-constant type arguments, even if those arguments do not become part of the constructed value (possible using forwarding factory constructors).
```dart
class C<T> {
  const C();
  const factory C.wot(int x) = C<Never>;
}
const c = C<int>.wot(42);  // neither value nor type becomes part of object.
```

When calling a constructor through an instantiated type alias, the question is whether we do the "is this expression constant" before or after expanding the alias. I'm proposing to do it before, so a `const Alias<TypeArgs>.name(args)` is a valid constant iff TypeArgs and args are, and `Alias.name` denotes a constant constructor.

And then extend that to tear-offs of ``Alias<TypeArgs>.name`, which is only constant iff `TypeArgs` are constant and `Alias.name ` denotes a constant constructor.

**Comment by eernstg** [comment]
Makes sense, I think your proposal is the most consistent approach.
