### ISSUE TITLE
Don't require parens on one-parameter arrow functions

### ISSUE THREAD

**Issue by gosoccerboy5** [dart-lang/language#1669]
This isn't really much of an important or huge request, but in my opinion the second is slightly more easily written and read than the first:
```dart
[1, 2, 3].map((item) => item * 2);
_fetchUserOrder().then((item) => print("User ordered $item"));
``` 
vs 
```js
[1, 2, 3].map(item => item * 2);
_fetchUserOrder().then(item => print("User ordered $item"));
```

I believe this is important because this type of pattern is often found in Dart code, especially when manipulating Futures or Iterables. In fact, a (regex) search for `\(\w+\) =>` within the Dart SDK on my computer showed that the single parameter arrow function was used 479 times.

Any opinions on if this would be a good or bad idea?

**Comment by lrhn** [comment]
I think it's a reasonable syntax that is unlikely to be a problem parsing.
It only works for a single untyped (but inferred) non-final parameter, but that's still a lot of cases.

**Comment by TimWhiting** [comment]
It makes the old parameter look like a destructuring of a unary tuple type which I imagine would be compatible with tuples / value type destructuring if it get added.

**Comment by gosoccerboy5** [comment]
Oops, duplicate of #320.
