### ISSUE TITLE
constructor should support generic like class Student<T> {Student<T>() {} Student<T>.named(T s) {} }?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1671]
```dart
class Student<T> {
    Student<T>() {
    }
    Student<T>.named(T s) {
    } 
}
```

it makes consistent with code:
```dart
var stud = Student<int>();
var stud2 = Student<int>.named(88);
var stud3 = Student(); // equals Student<dynamic>();
```

**Comment by lrhn** [comment]
The *class* is generic, so you don't need to put the type variable on the class again in the constructor.
```dart
class Student<T> {
  Student();
  Student.named(T s);
}
```
is sufficient. 

There is no advantage in allowing you to write `Student<T>()` when you can *avoid* writing that `<T>` and get the same effect.
If it was somehow possible to *restrict* the type parameters, say `Student<T extends Comparable<T>>.comparable(T s)`, then it would be useful, but that's a different feature.

For now, no plans to allow writing an unnecessary type parameter that doesn't do anything.
