### ISSUE TITLE
Using literal generic types

### ISSUE THREAD

**Issue by RaedDev** [dart-lang/language#1677]
Something like this is possible
```
Type t = String; 
```

But not like this
```
Type t = List<String>;
```

There is a work around for this case but shouldn't this code work in Dart?

**Comment by eernstg** [comment]
You can do this:

```dart
Type typeOf<X>() => X;
Type t = typeOf<List<String>>();

// If your tool chain is 2.13 or newer you can also do this:
typedef ListOfString = List<String>;
Type t = ListOfString;

// In the near future you can actually use `List<String>` as an expression:
Type t = List<String>; // Probably in Dart 2.15 or so.
```

I'll close this issue because it doesn't report on anything that works incorrectly and doesn't propose new language mechanisms.

**Comment by RaedDev** [comment]
Sorry, there's an important issue in this workaround

``` dart
Type typeOf<X>() => X;
Type t = typeOf<List<String>>();

bool a = t == <String>[].runtimeType; 
void main() => print(a); // This returns false
```

I need it to have the same value so I can use the type as a key in a map

**Comment by leafpetersen** [comment]
> ```dart
> <String>[].runtimeType;
> ```

Note that `List` is an interface, and so it is not required that the runtime type of the runtime object which implements `List` instances actually be `List`.  On dart2js, for example, the runtime type of the object above is `JSArray<String>`.
