### ISSUE TITLE
toStringAsFixed rounding bug

### ISSUE THREAD

**Issue by NikolayKantur** [dart-lang/language#1680]
When rounding doubles with a fractional part .05, I have not consistent results =(

``` List<num> numList = [ ];
  for (num i = 0; i < 19; i++) {
    numList.add(pow(10, i) + 0.05);
  }
  numList.forEach((n) {
    print('$n\t - ${n.toStringAsFixed(1)}');
  });
```
Output: 
1.05     - 1.1
10.05    - 10.1
100.05   - 100.**0**
1000.05  - 1000.**0**
10000.05         - 10000.**0**
100000.05        - 100000.1
1000000.05       - 1000000.1
10000000.05      - 10000000.1
100000000.05     - 100000000.**0**
1000000000.05    - 1000000000.**0**
10000000000.05   - 10000000000.**0**
100000000000.05  - 100000000000.1
1000000000000.05         - 1000000000000.1
10000000000000.05        - 10000000000000.1
100000000000000.05       - 100000000000000.**0**

**Comment by lrhn** [comment]
Working as intended. None of the double literals provided here are actually exactly representable as a double.
The actual double values, which are the value being rounded, are:

1.0500000000000000444089209850062616169452667236328125
10.050000000000000710542735760100185871124267578125
100.0499999999999971578290569595992565155029296875
1000.049999999999954525264911353588104248046875
10000.04999999999927240423858165740966796875
100000.050000000002910383045673370361328125
1000000.05000000004656612873077392578125
10000000.0500000007450580596923828125
100000000.04999999701976776123046875
1000000000.0499999523162841796875
10000000000.049999237060546875
100000000000.0500030517578125
1000000000000.050048828125
10000000000000.05078125
100000000000000.046875

If you check, you can see that those values are being rounded correctly.

Just how doubles work.
