### ISSUE TITLE
Canonicalization of certain function objects should be specified, not accidental

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1681]
[Edit Jun 17: Added paragraph about missing canonicalization in a case revealed by new tests.]

When `print` denotes the well-known 'dart:core' function, implementations currently evaluate `identical(print, print)` to true, and similarly for any other top-level function or static method.

In other words, we are canonicalizing function objects obtained by function closurization denoted by a constant expression that resolves to a function declaration. This is true both in the case where said constant expression occurs in a constant context, and when it occurs elsewhere. (If `print` denotes that well-known function then the expression `print` is _always_ a constant expression, but it is only required to be constant in cases like `const cPrint = print;`.)

```dart
void main() {
  // `print` has a canonical value inside/outside constant contexts.
  print(identical(print, print)); // 'true'.
  const cPrint = print;
  const cPrint2 = print;
  print(identical(print, cPrint)); // 'true'.
  print(identical(cPrint, cPrint2)); // 'true'.
}
```

Surely, it would give rise to widespread breakage if we were to change that such that, e.g., `identical(print, print)` would evaluate to false in some or all cases. So, obviously, we will not do that.

But the language specification does not indicate that those function objects are canonicalized, ever.

Note that we have made some generic function instantiations constant expressions (from [here](https://github.com/dart-lang/language/blob/69c56229ad72660b5f7aad962615f4af1f00568e/specification/dartLangSpec.tex#L8023)):

> Let _e_ be a simple or qualified identifier denoting a top-level function (9) or
> a static method (10.7) that is not qualified by a deferred prefix. If _e_ is not
> subject to generic function instantiation (17.16.1) then _e_ is a potentially
> constant and constant expression. If generic function instantiation does
> apply to _e_ and the provided actual type arguments are _T<sub>1</sub>,... , T<sub>s</sub>_ then _e_
> is a potentially constant and constant expression iff each _T<sub>j</sub>_, _j_ ∈ 1.._s_, is a
> constant type expression

Those constant tearoffs are also canonicalized by the vm, by dart2js, and by the constant evaluator of the analyzer.

However, some recently written [tests](https://dart-review.googlesource.com/c/sdk/+/202243) revealed that the canonicalization of constant tearoffs involving generic function instantiation in some cases only occur in a constant context:

```dart
class CheckIdentical {
  const CheckIdentical(Object? o1, Object? o2): assert(identical(o1, o2));
}

X f<X>(X x) => x;

void main() {
  const int Function(int) g = f; // Generic function instantiation, "f<int>".
  const int Function(int) g2 = f; // Ditto.
  print(identical(g, g2)); // 'true' on the vm and dart2js.
  CheckIdentical(g, g2); // Succeeds on the analyzer, and elsewhere.

  // But canonicalization fails to occur, in the vm at least, when the
  // constant expression is not in a constant context.
  int Function(int) g3 = f; // "f<int>".
  print(identical(g, g3)); // 'false' from `dart`, 'true' from `dart2js`.
}
```

**I would recommend that we commit to the current behavior, fix the missing case, and specify that a constant expression that evaluates to a function object is canonicalized.**

This would also cover the constant function objects denoted by terms like `f<int>` that we will have when the feature `constructor-tearoffs` has been implemented.

The alternative would be to decide that no canonicalization is guaranteed for function objects. In that case we should add commentary to the specification saying so, and we should change tests to allow both true and false results from `identical` in those cases.

@jakemac53, @natebosch, @lrhn, @munificent, @leafpetersen, @stereotype441, WDYT?

**Comment by lrhn** [comment]
Yes, absolutely. 

Top-level and static functions have always been "canonicalized" when torn off, and the value is a compile-time constant.
That has always been a guarantee.

**Comment by eernstg** [comment]
Closing: The language team decided that this kind of canonicalization should occur. It's specified in https://github/com.dart-lang/language/issues/1686, tested in https://dart-review.googlesource.com/c/sdk/+/202243, and the implementation issue is https://github.com/dart-lang/sdk/issues/46485.
