### ISSUE TITLE
Inheriting restrictions

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1697]
Comments on https://github.com/dart-lang/language/blob/master/working/modules/feature-specification.md

The restrictions described by this document are not described as inherited.

If I create a class which can only be extended, not implemented (`abstract class Foo`), I might assume that all objects satisfying `is Foo` are extending my class.
However, if nothing prevents someone else from writing `open interface class MyFoo extends Foo {}`, then they can just implement `MyFoo` and thereby get a non-`Foo`-extending implementation of `Foo`. You can also instantiate `MyFoo` and get objects which are basically equivalent to `Foo`, because we haven't changed any thing in the subclass (but it is a different subclass, and there probably isn't anything we can do to force subclasses to do something, other than having abstract members).

The issue is probably only related interface implementation, where an interface not being implementable needs to be a transitive property of all sub-interfaces. The other restrictions are between a class and its subclass, or relates to constructors of the class itself, and they are not transitive in the same way. (If you can't extend a class, you definitely won't be extending any subclasses, since there aren't any).

If a goal is to allow class hierarchies which are guaranteed to all inherit the same member implementations from a shared superclass (which is a common goal), then it should either also be an error to make a subclass an interface if the superclass is not an interface, or we need a way to state whether that restriction really should be inherited or not. The former is easier, so:

* It's a compile-time error if a class *C* is declared as `interface`, the superclass, *D*, of *C* is not declared as `interface`, and *C* and *D* are not declared in the same compilation unit.

(If they are in the same compilation unit, then we can see locally that the *C* class isn't effectively interface-sealed, there can be classes implementing *C* through *D*. Maybe unless *D* is private, and no public interface implements *D*.)

**Comment by munificent** [comment]
> If I create a class which can only be extended, not implemented (`abstract class Foo`),

For the record, that would be `open abstract class`. (Just `abstract class` gives you a class you can't do much of anything with. It might be useful if it had factory constructors, or it could simply be a namespace-like container for static members.)

> I might assume that all objects satisfying `is Foo` are extending my class.

Yes.

> The issue is probably only related interface implementation, where an interface not being implementable needs to be a transitive property of all sub-interfaces.

Ah, good catch! This is indeed an oversight on my part. Fixed in de5ec705ebd3dee64baad49d7bef654f04c4fa19.
