### ISSUE TITLE
Null safety of Future<T?> types

### ISSUE THREAD

**Issue by changlan** [dart-lang/language#1705]
I have a seemingly valid use case of Future<T?>:

```
// _first() returns a nullable value, while _alternative() does not.
Future<int?> _first() => Future.microtask(() => 0);
Future<int> _alternative() => Future.microtask(() => 0);

// try _first(), if the returned value is null, use the result from _alternative() instead.
Future<int> _main() => _first().then((x) => x ?? _alternative());
```

However, it does not type check:

```
The return type 'Object' isn't a 'FutureOr<int>', as required by the closure's context.dart(return_of_invalid_type_from_closure)
```

It is not clear to me why this error happen, as `(x) => x ?? _alternative()` clearly returns a `FutureOr<int>`. Is this expected?

**Comment by mateusfccp** [comment]
Your confusion comes by the use of  the null-coalesce operator inside an expression function.

`_first().then` expects you to return a `FutureOr<int>`. This would be the case if you did:

```dart
Future<int> _main() => _first().then((x) {
  if (x == null) { // ⬅ The expression `x` here has type `int?`
    return _alternative(); // ⬅ The expression _alternative() has type `Future<int>`
  } else {
    return x; // ⬅ The expression `x` here is promoted to `int`
  }
});
```

The code above, however is not the strict equivalent of the code you proposed.

When we use the null-coalesce operator (`a ?? b`), the expression has precedence in evaluation, and thus it will have the least upper bound between the given variable. In this case, the least upper bound between `int?` and `Future<int>` is `Object`, and thus it will be different from the type expected by the context (`int`).

Alternatively, you could also do:
```dart
Future<int> _main() => _first().then((x) async => x ?? (await _alternative()));
```

Or even use a completely imperative API:
```dart
Future<int> _main() async {
  final first = await _first();
  return first ?? await _alternative();
}
```

In both cases the `await` expression will be evaluated before the null-coalesce, and thus the static analysis know that `await _alternative()` has type `int`. The least upper bound between `int? ` and `int` is `int`, so it works as expected.

**Comment by lrhn** [comment]
@mateusfccp Almost correct, except for the typing of `??`, which does find the LUB of `int` and `Future<int>`. It's just not finding `FutureOr<int>` as you'd hope.

The type of `e1 ?? e2` should be the LUB of **NON_NULL**(*typeof*(e1)) and *typeof*(e2).
You can see that if you do:
```dart
void main() {
  int? x = (0 as dynamic); // avoid promoting to int.
  x.log;
  var y = x ?? (throw "nope");
  y.log;
}
extension <T> on T {
  T get log {
     print("${this}:${this.runtimeType}@$T");
     return this;
  }
}
```
This prints
```
0:int@int?
0:int@int
```
proving that `y` has type `int`.

For
```dart
void main() {
  int? i = (0 as dynamic);
  Future<int> f = Future.value(0);
  var x = i ?? f;
  x.log;
}
```
it prints
```
0:int@Object
```
so the "UP" (upper bound-ish value) of `int` and `Future<int>` becomes `Object`. 

If we look at [the upper bound operation](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md),
there is no rule introducing `FutureOr` from a combination of `T1` and `Future<T2>`, so getting `Object` is correct.
We won't introduce a union type by LUBs unless there is one already, like the rule:
> *  **UP**(`T1`, `FutureOr<T2>`) = `FutureOr<T3>` where `T3` = **UP**(`T1`, `T2`)

There is no similar rule for `T1` and `Future<T2>`, so we infer `Object` here instead, as specified.

The workarounds are all fine. I highly recommend never depending on returning a future directly from an `async` function, and always awaiting it first and returning the value.

**Comment by mateusfccp** [comment]
Thanks for the correction @lhrn

**Comment by Levi-Lesches** [comment]
@changlan, you can also do:
```dart
Future<int> _main() async => (await _first()) ?? (await _alternative());
```
which makes the problem a lot clearer -- removing the first `await` means you get a `Future`, which isn't null, and removing the second `await` means returning a `Future` from within a `Future`, so you get a `Future<Future<int>>`, which isn't "compatible" with `Future<int?>`. So the body returns an `int`, and since the whole thing is wrapped in an `async`, `_main` returns a `Future<int>`. 

Hope that clears things up.

**Comment by changlan** [comment]
Thanks all for the answers! As suggested, I worked around this issue by `await`ing the `Future`.

@lrhn, I wonder why there is no rule introducing `FutureOr` from a combination of `T1` and `Future<T2>`? Does it lead to unsound semantics, or is it merely a limitation of the implementation?

**Comment by mateusfccp** [comment]
> @lrhn, I wonder why there is no rule introducing `FutureOr` from a combination of `T1` and `Future<T2>`? Does it lead to unsound semantics, or is it merely a limitation of the implementation?

I don't know the technical reasons, but I would find it quite counter intuitive to be able to do what you did in your example code...

**Comment by changlan** [comment]
> > @lrhn, I wonder why there is no rule introducing `FutureOr` from a combination of `T1` and `Future<T2>`? Does it lead to unsound semantics, or is it merely a limitation of the implementation?
> 
> I don't know the technical reasons, but I would find it quite counter intuitive to be able to do what you did in your example code...

I feel that this is a common use case, that is, a preferred function that could return a nullable result and another fallback function that is guaranteed to return a valid result. 

Counter intuitive as it might seems, one might think `_first().then((x) => x ?? _fallback())` is a valid way to do so, because `x ?? _fallback()` should return a `T` (not `T?`, `x` can't be `null` because of the null-coalesce operator) or `Future<T>`, so it should satisfy the `FutureOr<T>` type from a user's perspective. Therefore I'm just curious if there is something not covered by the type system specification.

**Comment by Levi-Lesches** [comment]
> We won't introduce a union type by LUBs unless there is one already, like the rule:
> 
> > * **UP**(`T1`, `FutureOr<T2>`) = `FutureOr<T3>` where `T3` = **UP**(`T1`, `T2`)
> 
> There is no similar rule for `T1` and `Future<T2>`, so we infer `Object` here instead, as specified.

@lrhn, can you clarify 

1) Does the `UP` rule here not work for this case? Why not? 
2) Why is there no such rule for this case? And if there were, would the type system infer `FutureOr<int>` in this case?

**Comment by lrhn** [comment]
The rule

> * **UP**(`T1`, `FutureOr<T2>`) = `FutureOr<T3>` where `T3` = **UP**(`T1`, `T2`)

does not apply here because the types being UP'ed are `int` and `Future<int>`. The rule requires a `FutureOr<X>` to work, and the rules are structural, not subtype based, so it's not enough that `Future<int>` is a subtype of `FutureOr<int>`.

I don't remember the exact reason not to have a similar rule for `int`/`Future<int>`. Possibly it was because we found that allowing union types as solutions to LUB computations would too easily mask errors (it was just too easy to find a solution for any two types). On the other hand, we can always find `Object?` as solution anyway, so I'm not sure that was it.

**Comment by Levi-Lesches** [comment]
If such a rule were added, (by my guess: 
* **UP**(`T1`, `Future<T2>`) = `FutureOr<T3>` where `T3` = **UP**(`T1`, `T2`)

) would that fix this issue? Then again I see that this is very narrowly scoped and [the general advice](https://dart.dev/guides/language/effective-dart/design#avoid-using-futureort-as-a-return-type) is to avoid using `FutureOr` as much as possible anyway, so a solution using `await` is preferable.
