### ISSUE TITLE
Elvis operator or similar

### ISSUE THREAD

**Issue by Wdestroier** [dart-lang/language#1715]
Hi! Sometimes in Flutter I have to pass a widget only if a variable is not null.

Example:

```dart
return personImage == null ? null : Avatar(image: personImage);
```

I would like to suggest a language feature for this.
A syntax sugar that exists in other languages is the elvis operator:

```kotlin
return personImage ?: Avatar(image: personImage);
```

Maybe we can have the elvil operator:

return x 3:) y;

Or the happy operator:

return x :) y;

Or the inverse if null operator:

return x ¿¿ y;

Just kidding!
I wonder what could be a great looking syntax...

**Comment by Levi-Lesches** [comment]
> return x ¿¿ y;

Well, I'd hate to have to type that out!

Here's another issue with exactly the same request (`x !! y`): #361. How about closing this and subscribing there?

**Comment by Wdestroier** [comment]
Ok, sure
