### ISSUE TITLE
Cannot cast runtime type casting

### ISSUE THREAD

**Issue by vishnuagbly** [dart-lang/language#1732]
I was having an error like List<dynamic> is not a subtype of List<double> but here the problem is List<double> is determined on runtime, I am doing something like this:-
```
extension Ext<T> on List<T> {
  List<T> deepClone() {
    List<T> res = [];
    for (var value in this) {
      if (value is List) {
        res.add(value.deepClone() as T);  //List<dynamic> is not a subtype of List<double>
      } else {
        res.add(value);
      }
    }
    return res;
  }
}
```
I researched a lot and found I cannot cast it on runtime, and the problem here is I need this function for different types of lists, so I cannot create a different function for each type either, that is why I believe we can really use something like runtime typecasting, or typecasting using the Type Object?

This kind of feature can be very useful, I have found myself in a situation like this many times, where if able to use Type Object for typecasting and checking if one Type Object is a subtype of another Type Object, could be really helpful.

After some more research, I found what I looking for is maybe duck typing, but I am not sure if there are any alternatives to achieve what I am trying to do, basically what I am trying to do is cast a variable based on another variable type. 
for ex-, let's assume I have some variables named ```first``` and ```second``` then
```
second = second as first.runtimeType;
```

**Comment by Levi-Lesches** [comment]
There's another issue with discussion on this, I'll update you when I find it. I think the discussion was on deep cloning nested JSON, which led to this error.

**Comment by Levi-Lesches** [comment]
Got it, it's #1574. I think this is a duplicate of that.

**Comment by vishnuagbly** [comment]
@Levi-Lesches Thanks, It sure looks like very similar problem thanks, I will follow that issue
