### ISSUE TITLE
How to check generic R is void type?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1734]
if to check R is int, we can use: 
```dart
void ses<R>(R Function() f) {
  if (R == int) {
    print('ok11111');
  }
}
```
but use `if (R == void)` is not allowed, how can i check R is void?

**Comment by Silentdoer** [comment]
Ok, use f.runtimeType == Runnable can solve my problem, Runnable is typedef Runnable = void Function();

**Comment by Levi-Lesches** [comment]
Can I ask why you're checking for void at all? Void, by definition, is something that shouldn't be dealt with explicitly. Maybe there's a better way? Checking `.runtimeType` is hacky and doesn't allow for better type safety, and there's no explicit guarantee that the name `Runnable` won't change, as I drive think it's meant to be used like this.

**Comment by Silentdoer** [comment]
> Can I ask why you're checking for void at all? Void, by definition, is something that shouldn't be dealt with explicitly. Maybe there's a better way? Checking `.runtimeType` is hacky and doesn't allow for better type safety, and there's no explicit guarantee that the name `Runnable` won't change, as I drive think it's meant to be used like this.

i want write a task executor, task is `Callable<R>`, when R is void, i will not return a future

**Comment by Levi-Lesches** [comment]
Are you saying you'd normally return a `Future<R>`, but when `R` is void, you don't want to? If so, you probably should return `Future<void>` to keep the return type as `Future`, not `Future?`. The simplest solution in Dart usually works, although YMMV.

**Comment by mateusfccp** [comment]
`void` is a top type, so all types are `void` (although you can't directly check with `if (a is void)`). Also, the `void` type is not intended to be used. He is virtually the same as `Object`, but with the additional semantic of "something to be discarded". This is why the static analyzer will prevent you to use `void` values in many situations.

However, this kind of analysis is not exhaustive. Quoting the specification:

> _Obviously, the support for preventing developers from using objects obtained from expressions of type **void** is far from sound, in the sense that there are many ways to circumvent the rule that such an object should be discarded._
> _However, we have chosen to focus on the simple, first-order usage (where an expression has type **void**, and the value is used), and we have left higher-order cases largely unchecked, relying on additional tools such as linters to perform an analysis which covers indirect data flows._
> _It would certainly have been possible to define sound rules, such that the value of an expression of type **void** would be guaranteed to be discarded after some number of transfers from one variable or parameter to the next one, all with type **void**, explicitly, or as the value of a type parameter. In particular, we could require that method overrides should never override return type Object by return type **void**, or parameter types in the opposite direction; parameterized types with type argument void could not be assigned to variables where the corresponding type argument is anything other than **void**, etc. etc._
> _But this would be quite impractical. In particular, the need to either prevent a large number of type variables from ever having the value **void**, or preventing certain usages of values whose type is such a type variable, or whose type contains such a type variable, that would be severely constraining on a very large part of all Dart code._
> _So we have chosen to help developers maintain this self-imposed discipline in simple and direct cases, and leave it to ad-hoc reasoning or separate tools to ensure that the indirect cases are covered as closely as needed in practice._

Thus, it _is_ kind of possible (although not surely) to check if a generic type `T` is void.

Consider the following workaround example:
```dart
void test<T>() {
  if (T == voidType) {
    print('Is void!');
  } else {
    print('Is not void!');
  }
}

final voidType = _getType<void>();

Type _getType<T>() => T;
```

However, as pointed by @Levi-Lesches, you probably shouldn't do anything like this, and there is probably some other better way to do what you are wanting.
