### ISSUE TITLE
should default use this.prop to access instance field?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1737]
we can know this.prop is a class instance prop not a local variable, it is useful when read code on web site or notepad

**Comment by Levi-Lesches** [comment]
Sorry, I'm having a hard time understanding what you're asking, do you mind clarifying? Are you asking whether we should use `this.propety` instead of just `property`?

**Comment by Silentdoer** [comment]
> Sorry, I'm having a hard time understanding what you're asking, do you mind clarifying? Are you asking whether we should use `this.propety` instead of just `property`?

yes, it's my real meaning.., it's more clear when read code from web or notepad

**Comment by mateusfccp** [comment]
You can use `this` if you want, it's not a compile error. Maybe you are annoyed by the linter warning, but you can disable this rule in your `analysis_options.yaml`.

**Comment by gosoccerboy5** [comment]
If we forced Dart users to use `this.property` instead of `property` within the class, wouldn't that be a huge breaking change?

**Comment by Silentdoer** [comment]
> 
> 
> If we forced Dart users to use `this.property` instead of `property` within the class, wouldn't that be a huge breaking change?

it's just change the default linter rule, not a compile error.

**Comment by Silentdoer** [comment]
> 
> 
> You can use `this` if you want, it's not a compile error. Maybe you are annoyed by the linter warning, but you can disable this rule in your `analysis_options.yaml`.

yes, i know, i just suggest set the default analyzer rule to use this.prop.

**Comment by Levi-Lesches** [comment]
If you want to suggest a lint like that (and I could see people using it, it does make the code more clear), perhaps suggest it on [Dart's linter repo](https://github.com/dart-lang/linter/issues/new?assignees=&labels=enhancement%2C+lint+request&template=lint-request.md&title=)? Post back here if you do please.

**Comment by gosoccerboy5** [comment]
> > If we forced Dart users to use `this.property` instead of `property` within the class, wouldn't that be a huge breaking change?
> 
> it's just change the default linter rule, not a compile error.

Ohhhhhh. But, (and I don't have much programming experience so I might be wrong) isn't removing the `this` standard in other languages?
Besides,  Dart is [meant to be a terse, concise language](https://dart.dev/guides/language/effective-dart) and I feel like this would go against that.

**Comment by Levi-Lesches** [comment]
Yeah, convention is to only use `this` in cases where it's ambiguous (there's a name in a function that matches a field). Dart has initializer lists, but other languages would force you to use `this.something = something` in your constructors.
