### ISSUE TITLE
await dot syntax

### ISSUE THREAD

**Issue by AlexeyBukin** [dart-lang/language#1752]
Some asynchronous code looks bad when you use a lot of objects and properties.

```dart
var v = (await future1((await future2).property2)).property1;
```

I would like to see `(await someFuture()).property` as `someFuture().awaited.property` then code above could be rewritten as 

```dart
var v = future1(future2.awaited.property2).awaited.property1;
```

We could use `await` Instead of `awaited` to highlight it more for readability.
What do you think?

**Comment by lrhn** [comment]
See also #25.

**Comment by AlexeyBukin** [comment]
@lrhn thanks, closing
