### ISSUE TITLE
Allow multiple switch cases to be specified together

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/language#1755]
### The problem

Currently in Dart, specifying several cases that should be handled in the same way requires separate cases:

```dart
    switch (this) {
      case $e:
        return 0;
      case $j:
      case $n:
      case $q:
        return 1;
      // etc.
}
```

This is inconvenient, specially when the formatter does not allow us to put the cases on the same line to try and make things a bit more succint:

```dart
    switch (this) {
      case $e:
        return 0;
      case $j: case $n: case $q: // formatter, leave me alone
        return 1;
      // etc.
}
```

Therefore, I would like to propose a new syntax for specifying multiple cases in a way similar to Kotlin and Java 16:

### Proposed new syntax

```dart
    switch (this) {
      case $e:
        return 0;
      case $j, $n, $q:
        return 1;
      // etc.
}
```

This would make bigger switch statements much nicer. This is common in parsers and encoders.

The examples above are taken from my [Prechelt phone number encoding](https://github.com/renatoathaydes/prechelt-phone-number-encoding/blob/dart/src/dart/phone-encoder/bin/phone_encoder.dart#L94) implementation.

If Dart had this syntax, that switch would have 16 fewer lines, which is quite significant.

### Other Languages

For comparison, here's what the switch looks like in Lisp:

```lisp
(defun char->digit (ch)
  "Convert a character to a digit according to the phone number rules."
  (ecase (char-downcase ch)
    ((#\e) 0)
    ((#\j #\n #\q) 1)
    ((#\r #\w #\x) 2)
    ((#\d #\s #\y) 3)
    ((#\f #\t) 4)
    ((#\a #\m) 5)
    ((#\c #\i #\v) 6)
    ((#\b #\k #\u) 7)
    ((#\l #\o #\p) 8)
    ((#\g #\h #\z) 9)))
```

And even in Java 16:

```java
    static int charToDigit( char c ) {
        return switch ( Character.toLowerCase( c ) ) {
            case 'e' -> 0;
            case 'j', 'n', 'q' -> 1;
            case 'r', 'w', 'x' -> 2;
            case 'd', 's', 'y' -> 3;
            case 'f', 't' -> 4;
            case 'a', 'm' -> 5;
            case 'c', 'i', 'v' -> 6;
            case 'b', 'k', 'u' -> 7;
            case 'l', 'o', 'p' -> 8;
            case 'g', 'h', 'z' -> 9;
            default -> throw new RuntimeException( "Invalid char: " + c );
        };
    }
```

I think this could be a low-cost feature to add (just guessing) with a large benefits to certain kinds of applications.

**Comment by munificent** [comment]
It can be a little tricky to add support for this while also being able to have cases that match on tuple types. But it's certainly not impossible, and can definitely be useful. If we were to do something here, I think it would most likely be in the context of [pattern matching](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md).

**Comment by munificent** [comment]
The current proposal (which is still in progress, so no promises) supports `|` patterns to let you concatenate multiple patterns. You can use that in a case like so:

```dart
switch (this) {
  case $e:
    return 0;
  case $j | $n | $q:
    return 1;
   // etc.
}
```

**Comment by munificent** [comment]
Closing this because the current proposal's `|` I believe cover this use case.

**Comment by renatoathaydes** [comment]
Thanks! I appreciate the great work you and the Dart team are doing, the language is getting really nice to use.
