### ISSUE TITLE
False positive with the `late` keyword when using `const factory` constructor

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#1763]
Consider the following code:

```dart
class Base {
  Base();

  const factory Base.empty() = _Empty;

  late final property = ...
}

class _Empty implements Base {
  const _Empty();

  @override
  get property => ...
}
```

This code currently does not compile with "Can't have a late final field in a class with a const constructor.
Try removing the 'late' modifier, or don't declare 'const' constructors."

This error is caused by a `const factory`. But since this is a factory constructor, this should not have any impact.

**Comment by eernstg** [comment]
True. Considering the issue in https://github.com/dart-lang/language/pull/1764.

**Comment by eernstg** [comment]
Done in https://github.com/dart-lang/language/pull/1764.
