### ISSUE TITLE
Please realize the accessibility of the private members of the same library

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1795]
for example, i write two classes: A in a_io.dart and A in a_web.dart, A has only private constructor `A._()`, but i want class B in b.dart can call `A._()`;
I have tried using `library ab;` to declare both A(a_io, a_web) and B, but it still doesn’t work

**Comment by eernstg** [comment]
Libraries is the level of privacy granularity in Dart. A `friend` library mechanism could give you this ability to access private declarations in a different library. But this would have serious consequences for several language properties. For example, it could prevent optimization of method invocations (including instance variable read operations) based on their declaration being private.

So it could be useful to note that it is already possible to split a large amount of source code (more than you wish to have in a single file) into multiple units without using multiple libraries. For this, you can use parts:

```dart
// File 'abLib.dart'.
part 'aLib.dart';
part 'bLib.dart';

// File 'aLib.dart'.
part of 'abLib.dart';

class A {
  static B foo() => B._();
}

// File 'bLib.dart'.
part of 'abLib.dart';

class B {
  B._();
}
```

**Comment by lrhn** [comment]
We are actually considering a feature to allow access to private members from other libraries in the same package/module (https://github.com/dart-lang/language/blob/master/working/modules/private-imports.md, #1757, #1767). 

Until such, time, you need to put the two classes in the same library, which means the same file or using part files.

**Comment by Silentdoer** [comment]
> 
> So it could be useful to note that it is already possible to split a large amount of source code (more than you wish to have in a single file) into multiple units without using multiple libraries. For this, you can use parts:
> 
> ```

This may not be what i want, because I want to implement such a function:
```dart
// File 'b.dart'.
import 'b_web.dart'
  if (dart.library.io) 'b_io.dart';

abstract class B {
  void createB() {
    var b = BImpl._();
  }
}
```
