### ISSUE TITLE
How to constrain arguments cannot be anonymous function at compile time

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1798]
for example:
```dart
void submit(Function task) {
}
```
Task is not allowed to be an anonymous function, because it does not have a static lifecycle, so it cannot be sent to other isolates, So how do we prevent users from using anonymous functions at compile time?

**Comment by Levi-Lesches** [comment]
Do you mean you want `task` to be a compile-time constant? That would be #1684. I suggest you write there explaining why you would need this because IIRC they're having a hard time justifying the need for it.

**Comment by Silentdoer** [comment]
What I mean is that user cannot pass a closure to the task, because closure can not as message send to other isolate to exec

**Comment by Levi-Lesches** [comment]
Right, essentially this: 
```dart
class Task {const Task(void Function() callback);}
void temp() { }

const Task a = Task(temp);  // works, because we use an existing function
const Task b = Task(() => print("Hello"));  // closures aren't constant

**Comment by Silentdoer** [comment]
> 
> 
> Right, essentially this:
> 
> ```dart
> class Task {const Task(void Function() callback);}
> void temp() { }
> 
> const Task a = Task(temp);  // works, because we use an existing function
> const Task b = Task(() => print("Hello"));  // closures aren't constant
> ```

Can detection only be used for construction methods?

**Comment by Levi-Lesches** [comment]
Sorry, what do you mean by construction methods? Class constructors? You can't specify that a constructor can _only_ accept const parameters, but if you try creating a const object (using a const constructor), you'd only be able to pass in a const parameter. 

```dart
class Task {const Task(void Function() callback);}
void temp() { }

const Task a = Task(temp);  // works, because we use an existing function
final Task b = Task(() => print("Hello"));  // works because b isn't const 
```
