### ISSUE TITLE
spread-collections grammar update request

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#181]
The [spread-collections spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/spread-collections/feature-specification.md) updates the grammar for `mapOrSetLiteral` to
```
mapOrSetLiteral:
    'const'?  '{' spread (',' spread)* '}' ;
```
but this doesn't allow for an empty literal. It also doesn't allow for a trailing comma. I think we want the grammar to look something like
```
mapOrSetLiteral:
    'const'?  '{' (spread (',' spread)* ','?)? '}' ;
```

**Comment by bwilkerson** [comment]
@munificent

**Comment by munificent** [comment]
Thanks, I'll take a look.

**Comment by munificent** [comment]
Both the spread proposal and the in-progress unified proposal handle this correctly now, I think.
