### ISSUE TITLE
Reminder to add set literal support for control flow collections

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#182]
The [control-flow-collections spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/feature-specification.md) does not yet support using control flow elements in set literals.

**Comment by bwilkerson** [comment]
@munificent

**Comment by leafpetersen** [comment]
@munificent is working on combining the proposals.

**Comment by srawlins** [comment]
Complete?

**Comment by munificent** [comment]
Yes!
