### ISSUE TITLE
Specification of constructor tearoffs on a mixin application class may need clarification

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1830]
[Edit: Using the latest commit, the program below is accepted and working. So this issue is now only about the specification. Adjusted the text below accordingly.]

Consider the following program:

```dart
class A { A.named(); A(); }
mixin M {}

class B = A with M;

void main() {
  var f = B.named;
  var g = B.new;
}
```

The mixin application class `B` makes constructors accessible (we can do `B.named()` and `B()`) ~~but it does not support tearoffs of the same constructors. This seems inconsistent.~~ In the latest commit, the tearoffs are supported by both the analyzer and the CFE.

If we agree that these tearoffs should be allowed then we may need to clarify the topic in the constructor-tearoffs specification.

**Comment by leafpetersen** [comment]
Both those are valid constructors to call on the class `B`, right?  So given that, I can't see any justification for not allowing them to be torn off.

**Comment by eernstg** [comment]
Right, that was my reasoning as well.

**Comment by eernstg** [comment]
We could proceed directly and create an SDK issue for this immediately, and then separately make sure that the specification is adjusted as needed.

**Comment by leafpetersen** [comment]
SGTM, thanks!

**Comment by eernstg** [comment]
Haha, it works in commit 65b5125223386a4d9cdf275ff82a4853b793c9b9, so there is no need to change anything in the implementations! (And I did not create an SDK issue).

The only remaining issue is whether we'd need to adjust the specification. @lrhn, do you think this case is covered already?

**Comment by lrhn** [comment]
I think the case is covered. The mixin application specification requires the mixin application class to have those constructors. Nothing outside of that should care how those constructors came to be. Tearing them off should just work like any other constructor.

**Comment by eernstg** [comment]
SG, cf. https://github.com/dart-lang/language/pull/1832.

**Comment by eernstg** [comment]
Spec change done in https://github.com/dart-lang/language/pull/1823.
