### ISSUE TITLE
Make an alias for the "var" keyword named "be"

### ISSUE THREAD

**Issue by manyopensource** [dart-lang/language#1835]
I was having some "fun" with Kotlin and thought why not just "be" in Dart.

Examples:
```
// Define variables
be myProperVariableName;
be someFlag = ValueNotifier<bool>(true);
```

**Comment by PlugFox** [comment]
Please, stop trying to uglify the language with useless constructs and operators.

Dart, after version 2.0, trying to be strict language, not like js or kotlin or python.

**Comment by Aqluse** [comment]
It's not that kind of a language comprehensiveness I would like to see in Dart

**Comment by feinstein** [comment]
```dart
be or = !toBe ? 'that's the question' : '';
```

**Comment by manyopensource** [comment]
> ```dart
> be or = !toBe ? "that's the question" : '';
> ```

@feinstein you can't use "or" as a variable name!

**Comment by mateusfccp** [comment]
Well, I think it's a valid idea, but for `final` variables, as they are sure of who they are. For `var` they should be called `beornotbe`.

```dart
void main() {
  be name = 'Maria';
  name = 'Lucas'; // Error: name is already Maria

  beornotbe name2 = 'Maria';
  name2 = 'Lucas'; // OK!
}
```

**Comment by feinstein** [comment]
Yes you can... But if I couldn't I would call it a "poetic license".

**Comment by mateusfccp** [comment]
> ```dart
> ```dart
> be or = !toBe ? "that's the question" : '';
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> @feinstein you can't use "or" as a variable name!
> ```

Why not?

**Comment by manyopensource** [comment]
> > @feinstein you can't use "or" as a variable name!
> 
> Why not?

Who does that?

**Comment by feinstein** [comment]
.... But you can... Should you? Probably not... But you can.

**Comment by lrhn** [comment]
If we do choose to do something to change variable declarations, I'm fairly certain this won't be it. 
Adding new keywords is something that requires very good reasons.

**Comment by munificent** [comment]
> I'm fairly certain this won't `be` it.

Fixed that for you.
