### ISSUE TITLE
Syntax-sugar for async block in synchronous contexts

### ISSUE THREAD

**Issue by mateusfccp** [dart-lang/language#1858]
## Problem

Currently, for obvious reasons, we can't `await` inside a function that is not tagged as `async`.

However, there are cases where we want to call an unawaited future from within a non-`async` function. A obvious example, and that I think is the most common case for Dart programs, is Flutter's `initState`.

When this is the case, we currently have three options (that I can think of):

1. Extract the future to an `async` function:

```dart
@override
void initState() {
  super.initState();
  doAsyncThings();
}

Future<void> doAsyncThings() async {
  final result =  await future;
  // do something with result
}
```

2 . Use `.then`:

```dart
@override
void initState() {
  super.initState();
  future.then((result) {
    // do some other things with future 
  });
}
```

3. Make an auto-calling `async` function:

```dart
@override
void initState() {
  super.initState();
  () async {
    final result = await future;
    // do some other things with future 
  }();
}
```

## Proposal

Although all of the options works well, each of them has a disadvantage:

1. Sometimes we want do do something small enough that we don't want to extract it to a new function;
2. We lose the advantage that the `await` syntax gives us to write in a linear/imperative way;
3. We are able to write using `await`, but it's a little confusing, specially for newcomers.

We could provide an `async` block for synchronous contexts, so the code above could be written as:

```dart
@override
void initState() {
  super.initState();
  async {
    final result = await future;
    // do some other things with future 
  }
}
```

The block would be obviously unawaited, like all the options we have today. We don't introduce a new keyword, as we already have `async` for functions. I don't know, however, if this is something ambiguous, grammar wise.

**Comment by jakemac53** [comment]
I think the ordering here becomes pretty ambiguous/misleading, the outer block should (almost certainly) still execute synchronously, so for instance this code:

```dart
void foo() {
  print(1);
  async {
    print(2);
    await Future.delayed(Duration(seconds: 1));
    print(3);
  }
  print(4);
}
```

Should print either `1\n2\n4\n3\n` (with sync async) or `1\n4\n2\n3\n` (without sync async). That is a lot more obvious imo when you write that block as a full async closure. This way it looks like a synchronous block, but it isn't.

**Comment by munificent** [comment]
> 1. Make an auto-calling `async` function:
> 
> ```dart
> @override
> void initState() {
>   super.initState();
>   (() async {
>     final result = await future;
>     // do some other things with future 
>   })();
> }
> ```

The extra parentheses aren't needed in Dart like they are in JavaScript, so this example would just be:

```dart
@override
void initState() {
  super.initState();
  () async {
    final result = await future;
    // do some other things with future 
  }();
}
```

The proposal then is really just removing two `()`, which doesn't seem like a very large value add to me.

**Comment by mateusfccp** [comment]
> The extra parentheses aren't needed in Dart like they are in JavaScript, so this example would just be:

I didn't know it, thanks.

**Comment by lrhn** [comment]
Also, since `initState` has return type `void`, you can write it as:
```dart
@override
void initState() async {
  super.initState();
  final result = await future;
  // do some other things with future/result 
}
```
It will technically return a future, but no-one will wait for that future since they never expect it to begin with.

**Comment by mateusfccp** [comment]
Well, it seems that my proposal is not as necessary as I though it was. Closing.
