### ISSUE TITLE
Move the set literal proposal out of the `working` directory

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/language#1867]
It shipped, right?

https://github.com/dart-lang/language/blob/master/working/0036%20-%20Set%20Literals/0037%20-%20Math-Braced%20Set%20Literals%20-%20lrhn.md

CC @lrhn

**Comment by leafpetersen** [comment]
This is an older design that got superseded.  There is a link to the version we shipped at the header.  We should consider whether we want to start "archiving" old working documents that we have shipped or abandoned.

**Comment by kevmoo** [comment]
I think so!

The only problem is links "in the wild" that will 4040

**Comment by kevmoo** [comment]
SGTM!

**Comment by munificent** [comment]
Done: 2cb47134c99443484ee3436e48220cd0e40e85d5

**Comment by kevmoo** [comment]
🙏
