### ISSUE TITLE
Why does dart delay initializing static fields

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1871]
```dart
void main(List<String> args) {
  print(Uk);
  print(Uk());
  print(Uk.mm);
  // ssss output only when Uk.kk is called for the first time
  Uk.kk;
  // The second call will not output ssss
  // So when Uk.kk is executed multiple times, every time Uk.kk is executed, dartvm will judge whether Uk.kk is initialized, right?
  // If it has been initialized, the initialization function will not be called
  Uk.kk;
  // My thought is why not initialize static fields when Class is initialized like Java
  //, so that there is no need to judge whether static fields are initialized when they are called
}

class Uk {
  static int kk = () {
    print('ssss');
    return 9;
  }();

  static var mm = 444;
}
```

**Comment by Levi-Lesches** [comment]
It's lazy loading -- theoretically, if `Uk.kk` is never called, it never needs to be evaluated. I assume also that this way you can have static fields depend on each other without having to sort them to see which to evaluate first. 

Is there a reason this is a bad thing?

**Comment by rrousselGit** [comment]
More importantly, this is necessary for tree shaking of static/global variables.

If they weren't lazy loaded, Dart wouldn't be able to tree shake them, because getters & co could technically trigger side effects (like the print on your example)

**Comment by Silentdoer** [comment]
> 
> 
> It's lazy loading -- theoretically, if `Uk.kk` is never called, it never needs to be evaluated. I assume also that this way you can have static fields depend on each other without having to sort them to see which to evaluate first.
> 
> Is there a reason this is a bad thing?

What I mean is that if the static field kk is initialized along with the initialization of class Uk, then when Uk.kk is called, there is no need to check whether kk is initialized, otherwise every time Uk.kk is called, it must be checked whether kk has been initialized. it is an additional overhead?

**Comment by lrhn** [comment]
The original reasons were start-up time and predictability. 

In Dart, there is no program code which runs before the call to `main`. All code after that is run directly or indirectly as a result of running the `main` method.
That also means that static fields with initializers must be evaluated at a later point, which is why they are lazy.

**Comment by mraleph** [comment]
@Silentdoer note that classes are actually initialised lazily in Java and not eagerly as you might think... which means their static fields are in fact initialised lazily. You can check [JLS 12.4.1. When Initialization Occurs](https://docs.oracle.com/javase/specs/jls/se7/html/jls-12.html#jls-12.4.1). In reality it means that whenever a static field `C.field` is accessed in Java implementation strictly speaking needs to check if the class `C` is initialised which is not that different from what Dart does here (except that initialisation has finer granularity and is per-field in Dart).

**Comment by munificent** [comment]
Closing this because I think @lrhn and @mraleph have answered it well.
