### ISSUE TITLE
Constant-2018 update Spec contradicts to the Language Spec

### ISSUE THREAD

**Issue by iarkh** [dart-lang/language#189]
It seems like Constant-2018 update Spec (https://github.com/dart-lang/language/blob/master/accepted/future-releases/spread-collections/feature-specification.md) contradicts to the Language Spec.

Dart language specification constraints on constant expressions are additive with the constraints for all expressions. The language specification states that, for an expression of the form e1 && e2:

> It is a compile-time error if the static type of e1 may not be assigned to bool or if the static type of e2 may not be assigned to bool.

Constant update 2018 Spec reads opposite things:

> The [&&] operator is now short-circuit in constant and potentially constant expressions. It only attempts to evaluate the second operand if the first operand evaluates to [true]. This makes [false && (null as String).length] a valid constant expression.
> The second operand expression still needs to be a potentially constant expression, which is a new use of potentially constant expressions outside of [const] constructor initializer lists.

So, according to the constant update 2018 Spec, `false && (null as String).length` is a valid constant expression. And this is not so according to the Language Spec.

Please see issue https://github.com/dart-lang/co19/issues/223 for more details.

**Comment by eernstg** [comment]
I guess the 'Constant update 2018 Spec' would be [this document](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/feature-specification.md)?

It is indeed not correct that `false && (null as String).length` is a valid constant expression (nor is it a valid expression at all), it is a compile-time error as you mention.

However, said document is not a specification document (as it states at the beginning of 'Design', 'The following section summarizes the changes').

The statement should be corrected, of course, and this issue will serve to keep track of that.

But the source of information about constant expressions and their 2018 update is the language specification.

**Comment by lrhn** [comment]
Fixed.
