### ISSUE TITLE
Where can macros be applied?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#1894]
The macro proposal says macro applications use existing metadata annotation syntax, but it doesn't say whether *any* metadata annotation can be a macro application. Do we intend to support macros anywhere a metadata annotation can be written? That includes place like on individual parameters in a function, local functions, etc.:

```dart
example(@foo int param1, void Function(@foo int nestedParam) param2) {
  @foo
  localFunction() {}

  @foo int localVariable;
}
```

At the very least, we probably have to prohibit macros on local functions and variables because I don't know if those would work at all with our phased approach unless we introduce more phases.

**Comment by tatumizer** [comment]
"phased approach" can be implemented in different ways.
Suppose each macro comes with some metadata that tells what kind of information this macro needs.
Today, a typical generator doesn't need anything beyond the (const) parameters passed to it in the annotation, plus the definition of the annotated class. It may not need the details of the types used in the class, just the names. In a more general case, the macro may need to know more. If we find a way to statically express such dependencies, the system may compute the graph of dependencies and call the macros in the correct order. (Each macro has to say what information it needs, and what information it adds - e.g. "I will add a method to the same class").

In principle, there can be some "second-order" macros e.g. (strawman) a macro that creates the list of all method names of a class as a static field.  Further, there might be macros that do some global manipulations (e.g. in each method that contains "foo" in its name, insert a logging call). Those are 3rd-order macros. I don't think we need to go beyond 3rd order for practical purposes. 

The challenge is to come up with a simple formalization of these dependencies.

**Comment by munificent** [comment]
> Suppose each macro comes with some metadata that tells what kind of information this macro needs. Today, a typical generator doesn't need anything beyond the (const) parameters passed to it in the annotation, plus the definition of the annotated class. It may not need the details of the types used in the class, just the names. In a more general case, the macro may need to know more. If we find a way to statically express such dependencies, the system may compute the graph of dependencies and call the macros in the correct order. (Each macro has to say what information it needs, and what information it adds - e.g. "I will add a method to the same class").

We discussed an approach like this at length but never managed to convince ourselves that it was simple enough for macro authors to understand or flexible enough for all the potential use cases we want to support.

**Comment by Levi-Lesches** [comment]
Barring macros from being on parameters and declarations inside functions can hardly be considered "draconian". IMO, let the first release of macros be as simple as needed to get a usable feature, then worry about adding the edge cases.

**Comment by munificent** [comment]
> Roughly speaking: when the macro is called, it generates some code and subscribes to changes in a library, or a class, or a property etc. When the change occurs, the macro can be called again, and if the code it generates is identical to the previously generated one, the propagation stops here, otherwise ... it's essentially similar to how fultter works.
> 
> I think it's very likely that the problem of code generation is mathematically equivalent to some other problem we already know how to deal with.

Yes, the process you're describing is fixed-point iteration. You start with the handwritten code. You run the macro expander on it and get some new code. That may produce changes to the code which macros might care about. So you run the macro expander again on *that* code. You keep doing that until the resulting code is the same as the previous iteration (the fixed-point) and then you're done.

Algorithms that work that way do come up in compilers sometimes. We try to avoid them because the performance can be poor or unpredictable. Letting *user defined* code get involved in an iterative algorithm like this is probably asking for trouble. Consider two macros applied to the same class:

1. One that synthesizes fields to memoize each getter.
2. One that synthesizes accessors for each field.

If you try to compile that class, you'll get an infinite number of fields and getters and it will never stop.

We don't have any use cases that we know of that don't work with a much simpler fixed-phase approach, so that's what we're leaning towards. Dynamic dependency tracking is *hard*. There's a reason new frameworks come out every couple of years to "revolutionize" dependency tracking. It's clearly not a solved problem yet.
