### ISSUE TITLE
Allowing multiple unrelated bounds on generic type parameters

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#1914]
## Use case

There is a general pain point today in Dart when a function or class has a parameter or field which only allows a closed set of unrelated types. The only way to express the type is with `Object` or `dynamic`. Consider the following example:

```dart
/// An api that accepts either a String (which is parsed into a Uri), or a Uri, and reads it as a String.
String readAsString(Object stringOrUri) {...}
```

The problem with this api is that you can't statically express that the parameter must be either a String or a Uri. You have to defer the checking to runtime.

## Common solutions

Some common solutions to this in other languages are:

- Union types
- Method overloads

Both of those have been discussed in the past, but there has been a lot of pushback to each - for instance overloads have issues with dynamic dispatch and union types could complicate the type system significantly.

## Proposal

Allow a comma separated list of bounds on generic parameters. These can be totally unrelated types (and probably always would be).

The previous example then becomes:

```dart
String readAsString<T extends String, Uri>(T stringOrUri) {}
```

### Benefits

- We can avoid adding real union types to the language, while getting much of the static type safety we want from them.
- The generic type is useful - you can use it as the return type for instance. Consider this terrible function:

```dart
T add<T extends String, int>(T from, T to) => from + to;
```
  If you call this function with two ints, you get an int type back and not a union type.
  
- We could potentially use a similar idea to implement something like Intersection types (although it would likely change the syntax for this proposal as well).

### Downsides

- You don't get a reified union type that you can pass around the program. So for instance you can't make a `List<int|String>` directly.
  - ~Although weirdly  you could maybe make your own List class that behaves like one `class MyList<T extends int, String> extends ListBase<T> implements List<T> {...}`?~ Nevermind, won't work :)

**Comment by munificent** [comment]
> ```dart
> T add<T extends String, int>(T from, T to) => from + to;
> ```

How does the type checker know that `+` is allowed here? What is the static type of `from` and `to` inside the body of the function?

**Comment by jakemac53** [comment]
> How does the type checker know that `+` is allowed here? What is the static type of `from` and `to` inside the body of the function?

In practice I expect most uses of this to rely on type promotion, I just realized when writing this that both `int` and `String` had a `+` operator so it felt a bit superfluous to do any type checks.

I suppose that goes into the `Downsides` bucket - since there is no true union type here and no common supertype that implements `+` you have to do type checks or casts, and in this case multiple:

```dart
T add<T extends String, int>(T a, T b) {
  if (a is int) {
    return a + b as int;
  } else {
    return a as String + b as String;
  }
}
```

That all feels a bit roundabout - although this is a bit of a weird example, but it would represent some portion of real world code.

It would be nice if you could do some sort of `is` check on the `T` itself but we can't (it's just a `Type`). Maybe pattern matching could come to the rescue here?

**Comment by jakemac53** [comment]
> What is the static type of `from` and `to` inside the body of the function?

Forgot to answer this part but I think it would be the LUB of all the types, so in this case Object.

**Comment by sigmundch** [comment]
Right - since we don't want the runtime type system to model type unions, I'd argue that we don't want to reify them as part of the type bounds on interface and function types. That leads to scenarios, even without dynamic calls, where we can't prove that the type parameters comply with the individual bounds, but only with the effective bound.

To preserve soundness we'd need a way to insert subbound checks. Either at the callee or at every instantiation. Effectively we will have to save the type bounds, but separately from the actual type of the entity. Like covariant checks today, there may be contexts where we can prove we don't need the check and call a specialized target that omits it, but we can view that as an optimization (for example, dart2js hasn't yet implemented that optimization because our customers already use `--omit-implicit-checks` to elide the checks).

**Comment by jakemac53** [comment]
I am going to go ahead and close this for now as I think the general consensus is that in order to get the runtime behavior and general semantics we would like, it does end up being close enough to union types that it isn't significantly simpler or less costly to implement.
