### ISSUE TITLE
Can macros access DateTime.now() or Random()?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#1915]
The macro runtime environment is restricted to try to ensure that macros are pure. That means no file system and environment stuff.

What about time? It is fairly common (but annoying) for code generators to put timestamps in generated code. I assume we want to forbid that. Do we prohibit the entire DateTime class, or just `DateTime.now()`? What about time zone?

The default `Random()` constructor chooses an arbitrary usually-time-based seed if not given an explicit one. Do we just always use fixed seed when called from macros? Disallow omitting the seed? Disallow the class entirely?

**Comment by munificent** [comment]
> * A user might want to use `DateTime` to embed a build time in their executable.

This does mean that every time the macro is run, the output is different. So far, I think we've tried to obscure when and how often macros are actually executed. The IDE might be re-running them constantly as the user types code, or in the background, or whenever. The idea is that the user doesn't/can't care when they are run as long as by the time they go to run their code, the macro output is up to date with the state of the source code.

But if macros can access DateTime, it means that multiple executions of the same macro on the same input code can produce different results. That in turn might mean that users could end up caring *when* the macros get run instead of letting the IDE implicitly decide on their behalf. Are we OK with that? I don't want to find ourselves needing a "refresh macros now" button in IntelliJ.

**Comment by jakemac53** [comment]
Ultimately, I just don't think the cost/benefit analysis is worth trying to block this. Yes, people can use DateTime and Random to do bad things. But if they do they will get complaints from their users.

At most I would say we should add either a lint or maybe even an analyzer warning about doing this within macro code. And we should document against using them.

> I don't want to find ourselves needing a "refresh macros now" button in IntelliJ.

Ya we should not support something like this, and instead tell users to file issues on packages that cause them problems. In the meantime they can restart their analysis server and/or program if needed.

**Comment by tatumizer** [comment]
If the macro wants to generate unique code every time it runs (just to make a point), it can always do so without `Time.now` or `Random`. Just take `identityHashCode` of something (e.g. a parameter) - it will likely be different from that of the previous run.

There can be many sources of "randomness". Another example is `List.shuffle` (though it uses Random underneath, so won't work if Random is blocked).

**Comment by kevmoo** [comment]
At the risk of a tiny tangent, the generalized notion of API X, Y, Z are either forbidden or discouraged in context Q – even transitively – would be interesting to ponder.

Pondering package security, being able to "prove" some notion of "I know nothing in my dependency change uses dart:io or FFI" (for instance).

**Comment by leafpetersen** [comment]
Just to be sure we're on the same page - if we allow this, I don't think there's any way that we can promise that it will actually run on any given build.  Forcing all code that uses macros to be re-compiled every time a build is done seems like a non-starter to me, and trying to track uses of specific APIs seems to me to be a complication we don't need.

**Comment by jakemac53** [comment]
> Just to be sure we're on the same page - if we allow this, I don't think there's any way that we can promise that it will actually run on any given build

Correct, if you use these apis it will almost certainly not do what you expect. But it should quite consistently not do what you expect unless you only ever do whole world compiles - in which case it _will_ do what you expect anyways.

**Comment by leafpetersen** [comment]
> Correct, if you use these apis it will almost certainly not do what you expect. But it should quite consistently not do what you expect unless you only ever do fresh whole world compiles - in which case it _will_ do what you expect anyways.

@jakemac53 Makes sense.  Should we worry about people doing more reasonable things that we've considered such as using (e.g.) file IO who might run into this?  e.g. if you can use file io to read in data using a macro, editing the data file might not do what you expect.

**Comment by munificent** [comment]
> using (e.g.) file IO who might run into this? e.g. if you can use file io to read in data using a macro, editing the data file might not do what you expect.

The current thinking for that is an explicit "resource" API provided to macros where the system would track which files get read and can then re-run the macro if the file changes.

**Comment by jakemac53** [comment]
I am going to close this as resolved - we will not block the use of DateTime or Random. Use at your own peril.
