### ISSUE TITLE
Missing information in Uri.https queryParameters documentation.

### ISSUE THREAD

**Issue by koji-1009** [dart-lang/language#1919]
Uri.https queryParameters is documented `Map<String, dynamic>?`, but it is actually `Map<String, dynamic /*String|Iterable<String>*/ >?`.

```dart
/// Creates a new `https` URI from authority, path and query.
///
/// This constructor is the same as [Uri.http] except for the scheme
/// which is set to `https`.
factory Uri.https(String authority, String unencodedPath,
    [Map<String, dynamic>? queryParameters]) = _Uri.https;
```
https://github.com/dart-lang/sdk/blob/2.14.0/sdk/lib/core/uri.dart#L164

However, it is not `dynamic` type.

```dart
/// Implementation of [Uri.https].
factory _Uri.https(String authority, String unencodedPath,
    [Map<String, dynamic>? queryParameters]) {
  return _makeHttpUri("https", authority, unencodedPath, queryParameters);
}

static _Uri _makeHttpUri(String scheme, String? authority,
  String unencodedPath, Map<String, dynamic>? queryParameters) {
~~~
return _Uri(
  scheme: scheme,
  userInfo: userInfo,
  host: host,
  port: port,
  pathSegments: unencodedPath.split("/"),
  queryParameters: queryParameters);
}

/// Implementation of [Uri.Uri].
factory _Uri(
  {String? scheme,
  String? userInfo,
  String? host,
  int? port,
  String? path,
  Iterable<String>? pathSegments,
  String? query,
  Map<String, dynamic /*String|Iterable<String>*/ >? queryParameters, <- here
  String? fragment}) {
~~~
  query = _makeQuery(query, 0, _stringOrNullLength(query), queryParameters);
~~~
  return _Uri._internal(scheme, userInfo, host, port, path, query, fragment);
}

static String? _makeQuery(String? query, int start, int end,
    Map<String, dynamic /*String|Iterable<String>*/ >? queryParameters) {
~~~
  if (queryParameters == null) return null;
~~~
  queryParameters.forEach((key, value) {
    if (value == null || value is String) { <- here
      writeParameter(key, value);
    } else {
      Iterable values = value;
      for (String value in values) {
        writeParameter(key, value);
      }
    }
  });
  return result.toString();
}
```

https://github.com/dart-lang/sdk/blob/2.14.0/sdk/lib/core/uri.dart#L1412
https://github.com/dart-lang/sdk/blob/2.14.0/sdk/lib/core/uri.dart#L2140

**Comment by koji-1009** [comment]
@Levi-Lesches 
Thank you for the quick answer.
What I described is the documentation; Uri.https does not mention that it needs String or Iterable<String> instead of dynamic.
Therefore, the developer has to read the uri.dart class to figure out what the problem is.

Is there any way to add more information to the Uri.https dart doc?

**Comment by Levi-Lesches** [comment]
See where the `Uri.https` constructor is? 
 https://github.com/dart-lang/sdk/blob/4ac35a7ec8c598ba1fdd8a1835a7fd84c61d9221/sdk/lib/core/uri.dart

All the text directly above it that starts with `///` is considered documentation. Adding a sentence or two there about the accepted types would make it appear on the documentation site.
