### ISSUE TITLE
Should we allow non-literal const expressions for macro value arguments?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#1929]
Arguments to macro applications can be unevaluated expressions or values of primitive types. For the latter, only literals are supported. Do we want to expand that to allow other const expressions that are safe to evaluate before macros are expanded? If so, what expressions do we allow?

We probably need to at least allow unary `-` since otherwise there's no way to pass negative number as a value argument to a macro. :)

Do we want to allow other arithmetic operators (on literal values)?

One option is to allow any valid const expression as long as it contains no identifiers. That would let users do basic arithmetic and maybe string concatenation, but should avoid the kinds of expressions that can't be evaluated before macros are run.

**Comment by jakemac53** [comment]
In https://github.com/dart-lang/language/pull/3147 I expand the syntax to allow all constant expressions but only containing literals.

I think it significantly simplifies things to keep it limited to literals, and we can always add the ability to reference identifiers later on if necessary.
