### ISSUE TITLE
Design the full API for creating Code objects

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#1932]
The prototype has a first pass API for how users create instances of Code (or its subclasses) from strings or other fragments. We'll need to fully design this and ensure it's what we want.

**Comment by Levi-Lesches** [comment]
Related: #1934

**Comment by jakemac53** [comment]
I think the Code API in general has evolved to a point that I am comfortable with. It is relatively simple, only containing a few types to help users know what they are expected to be producing as a part of the macro apis (ie: a function body, expression, or declaration). Today they do not do any parsing to validate things, which we may want to add, but also may not be worth while. It could in any case be added later.

Later down the line, I would love to see tagged strings to make the API easier to use, but the list of parts is reasonable enough today. You do have to be careful not to accidentally stringify identifiers and things, and convert your TypeAnnotation objects to TypeAnnotationCode objects. So it isn't without gotchas but it isn't clear how to fix those things without language changes or a much more complex API (tagged strings would help a lot).

It should also be quite possible to build a different API on top of it.
