### ISSUE TITLE
How does the macro API evolve as the language changes?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#1934]
One of the major challenges of exposing a programmatic API for working with Dart syntax is that new language syntax features can force changes to that API. If we aren't careful, those could be breaking changes, which would break macros. How do we handle this?

**Comment by Levi-Lesches** [comment]
I feel like this would be a good place to discuss the pros and cons of using a `Code`-like API and outputing code as a string. From https://github.com/dart-lang/language/issues/1482#issuecomment-896306774: 

> 1. Simply, an API would have to be designed and implemented (beyond the prototype). Outputting strings to a file is simple
> 2. The arguments to a constructor like [`Declaration`](https://jakemac53.github.io/macro_prototype/doc/api/definition/Declaration-class.html) are strings anyway
> 3. The Dart team would have to update the API with new language features, syntax, and grammar before they can be used
> 4. An API cannot be type-safe if types are statically unknown, so they're just as unsafe as strings
> 5. An API has to be expressive enough to cover every single use-case. It essentially has to duplicate Dart
> 6. An API has to be easy for all developers to learn to use. Dart users already knows basic Dart
> 7. An API has to be easy to maintain. Adding one line of code to generate shouldn't mean ten more lines and deeper indentation
> 8. An API has to communicate what code it is generating. By just writing Dart code as a string, WYSIWYG
> 9. An API has to generate all its code as a string in the end anyway. Why not remove a potential layer of problems?
> 10. If generated code can be inspected by devs, it has to look good and have claer names and structure. That might mean more than just outputting functional code and running it through `dart format`.
> 
> Using an API will most definitely lead to cases where the code isn't coming out the way it was intended to, either because of fundamental limitations or user error. And when it would work, the macro source code would be hard to read and follow. Since macros generate separate files, why not have the contents of those files _be_ the source code of the macros?

**Comment by jakemac53** [comment]
Finalizing the approach here https://github.com/dart-lang/language/issues/1934.
