### ISSUE TITLE
```const``` keyword omit ```static``` keyword

### ISSUE THREAD

**Issue by LuanRoger** [dart-lang/language#1954]
Only static fields can be declared as const, so ```const``` keyword can omit ```static``` keyword:

Dart 2.14:
```dart
static const double border_radius = 5;
```
```static``` omited:
```dart
const double border_radius = 5;
```
For read-only fields there is already ```final``` keyword.

Every ```const``` would already be ```static```

**Comment by Levi-Lesches** [comment]
While it's true that there's only one valid way to interpret this (as static), I don't think it's useful to remove it. Beginners will often think they can make instance fields const, or not fully understand the difference between static and instance, so getting rid of the static keyword here would only conflate the two.
