### ISSUE TITLE
Is it an error to apply an augmentation multiple times?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1957]
The augmentation library [proposal](https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md) says:

```
Since the main library and its augmentation both point to each other, these rules imply that a given augmentation file can only be used to augment a single library.
```

This doesn't preclude using an augmentation library multiple times in the same main library.  Is this an error or accepted?  If the latter, is it augmented twice, or just once?

cc @munificent

**Comment by munificent** [comment]
Good question. I can't see any practical use for it, so I'd probably disallow. But I don't think it's semantically problematic to allow it either.

**Comment by bwilkerson** [comment]
If the effect of applying an augmentation (it sounds weird to say "importing an augmentation") is the same as if there were only one application, then the analyzer will likely have a hint / warning to mark the dead code. That doesn't mean that it needs to be a compile time error (analyzer flags lots of other forms of dead code that aren't errors) but might be a data point.

If you do disallow it, then you leave the door open to defining some semantics for it later on (though I can't think of an interesting semantics for it at the moment).

**Comment by munificent** [comment]
> If the effect of applying an augmentation (it sounds weird to say "importing an augmentation") is the same as if there were only one application,

It's not. Since an augmentation can wrap an existing function body and call the original, wrapping multiple times isn't idempotent.

**Comment by bwilkerson** [comment]
> It's not.

I think it would be more accurate to say that it doesn't have to be the same. We're able to choose the semantics that we think is best for users. That is, the spec could easily state that if an augmentation library is imported into the same base library multiple times that the augmentation is applied exactly once.

Is there a reasonable use case for wanting to apply the same augmentation multiple times?

Is it an error for two augmentation files to add top level members with the same name, or to add two members to the same class with the same name? For example:

a.dart
```dart
import augment 'b.dart';
import augment 'c.dart';

class A {}
```

b.dart
```dart
library augment 'a.dart';

class B {}
augment class A {
  void b() {}
}
```

c.dart
```dart
library augment 'a.dart';

class B {}
augment class A {
  void b() {}
}
```

If so, then I assume that the same errors would apply to importing the same augmentation library multiple times. If not, then what are the semantics of referring to one of these declarations from a library that imports `a.dart`?

**Comment by munificent** [comment]
> > It's not.
> 
> I think it would be more accurate to say that it doesn't have to be the same.

Sorry, I read you wrong the first time. I read "applying an augmentation" as "augment the same thing multiple times (with different augmentations)".

It's definitely supported to apply *different* augmentations to the *same* declaration.

> ​We're able to choose the semantics that we think is best for users. That is, the spec could easily state that if an augmentation library is imported into the same base library multiple times that the augmentation is applied exactly once.
> 
> Is there a reasonable use case for wanting to apply the same augmentation multiple times?

None that I can think of. I think the simplest solution is to just make it an error to have a duplicate `augment import` directive.
