### ISSUE TITLE
Force to use async or noasync before a call to a asynchronous function that returns void

### ISSUE THREAD

**Issue by mregnauld** [dart-lang/language#1966]
In my Flutter project, I experienced a bug that tooks me hours to fix. My app had a very weird and random behavior, until I realize that I forgot... an `await` before a call of an asynchronous function that returns void.

In other words, here is the problem.

Let's say I have a function that removes a file if it exists.

```Dart
class FileHelper
{
  static Future<void> reset() async
  {
    File file = File("path/to/file");
    if (await file.exists())
    {
      await file.delete();
    }
  }
}
```

Now, in another function, it does some work that depends on the `reset()` function above.

```Dart
Future<void> doSomeWork() async
{
  // reset:
  await FileHelper.reset():
  
  // some extra works that relies on the line above...
}
```

The problem is: if I forget the `await` right before the `FileHelper.reset()` line, it will still compile and run, even though it can lead (but not always) to a bug.

Here is my idea: if I want to call an asynchronous function (like `FileHelper.reset()`), the compiler should force me to choose between to keywords:

- `async` if I want to wait for the function to finish
- `noasync`, or `sync` if I don't want to wait for the function to finish (as it is if I don't use `async`)

Therefore I'm sure that if I forget to add the `async` keyword before a call to an async function, the compiler will let me know (as it is already the case if the function returns a value).

Thanks.

**Comment by mmcdon20** [comment]
There is a [lint rule](https://dart-lang.github.io/linter/lints/unawaited_futures.html) that should help with this scenario.

**Comment by mregnauld** [comment]
Oh ok, didn't know about that, thanks!
