### ISSUE TITLE
augmentation libraries: removing unused declarations

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#1967]
(extracted from #1953 and filed as a separate issue).

Consider the augmentation that generates hashCode getter also wants to cache the value (the object is immutable). It needs a location for storage - say, _hashCode. It has to either add a field for that or use the existing field. However, even if such a field exists, it's not clear whether it means the same thing. So the new augmentation declares a new field _hashCode_for_foo. Now the old _hashCode might become unused. This leads to the idea of a special annotation @removeIfUnused (or something equivalent)
```dart
augment class A {
  @removeIfUnused int _hashCode=0;
  augment get hashCode {
     if (_hashCode==0) _hashCode=/*compute hash code*/;
     return _hashCode;
  }
}
```
Now if the getter hashCode is eclipsed by another augmentation,  _hashCode might become unused (unless there's some other method accessing it) and can be removed.
(There might be different ways to accomplish the same effect, it's just the annotation was the first thing that came to mind)

**Comment by jakemac53** [comment]
This should just happen automatically as a part of tree shaking? But it might mean some additional rules should be added to the tree shaking algorithms in the presence of augmentations.

Specifically, if an augmentation never calls into the original function, then that original one is known to be unreachable and it should be removed. Then any normal rules should fall out from that (if it was the only thing referencing some field, that field should be removable).
