### ISSUE TITLE
Allow import of directories

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/language#1969]
The idea is not from me, and this comment https://github.com/dart-lang/language/issues/1941#issuecomment-962253073 which has some ideas that I find are worth thinking about. One of which is allowing import of directories.

The use case for me is to have to stop writing barrels. Those are annoying because when you have many files, it's hard to quickly find the barrel.
The syntax proposed was `import 'some-dir/*'`. 
This requires some sort of privacy handling where maybe files starting with _ are not imported though

**Comment by cedvdb** [comment]
I understand this is not a popular idea but any counters would be welcome, as the use case is real

**Comment by Levi-Lesches** [comment]
From a language design, as well as from the reader's viewpoint, it's certainly simpler to see each file being explicitly imported or exported. Additionally, having a file full of exports lets you as the author explicitly specify which files are public, and compile them all together in one public file that gets imported, which allows for things like "import all of Flutter's Material library" with a simple `import "package:flutter/material.dart"`. Using a wildcard will _only_ lead to more confusion, as not only does it convey no information about which libraries are meant to be used, but makes the imports brittle as they depend on which files are in the folder, with no warning when they're moved. 

From the writer's perspective, it's certainly easier to use wildcards, no question about it. 

In such a case, it's probably better if this were an IDE thing. Like, typing in `import/export "dir/` would offer a list of every file in that directory. That way it's less keystrokes but the explicitness is still there.

**Comment by cedvdb** [comment]
Thank you for your input. A big flaw in the proposal is certainly this:

> but makes the imports brittle as they depend on which files are in the folder, with no warning when they're moved
