### ISSUE TITLE
Const variable must be initialised even with const value

### ISSUE THREAD

**Issue by jopmiddelkamp** [dart-lang/language#1978]
Hi,

It should be possible to initialize a const variable with a final property of a const object. The const object gets created on compile-time so why is this happening? See the example below:

https://dartpad.dev/?id=508f480fc9edc891c645f38de5f6ec21&null_safety=true

**Comment by mateusfccp** [comment]
I'm your example, although `kExample` is constant, `kExample.x` is a non-constant.

**Comment by lrhn** [comment]
Dart `const` evaluation does not allow you to read properties (getters) of objects (with `String.length` as the only exception).

It doesn't allow that for a number of reasons, mainly that *getters* may execute user code, and that *interfaces* only contain getters and setters, not "fields". A "field" (instance variable) declaration is a way to introduce both storage an a getter and possibly setter at the same time, but the class interface only shows the getter and setter. In effect, from outside the class declaration itself, you can't tell that there is a field.

So, if you do `kExample.x`, you are doing an interface call on a getter, which can do anything. The fact that it's currently implemented using a final field is not part of the interface, and may freely be changed in a later version of the class.
Allowing you to access constant fields, but not getters, makes such a change a breaking change, and avoiding that, while making getters and setters overridable, was exactly why Dart has virtual getters and setters to begin with.

**Comment by jopmiddelkamp** [comment]
Thank you for your explanation @lrhn

**Comment by munificent** [comment]
Closing this because I think @lrhn explained well why the language works this way.
