### ISSUE TITLE
Scoping in augmentation libraries

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#1979]
The problem: augmentation library can inadvertently introduce top-level variables that eclipse the members of classes. This may lead to difficult-to-debug errors.
The root cause of the problem: augmentation libraries are generated by macros that have no knowledge of other macros or the main library they are applied to. As a result, every top-level definition (e.g. a constant or a variable) generated by a macro can potentially eclipse something that it was not supposed to eclipse, due to the priority of lexical scope over "inherited" scope.

I can't find a place in the write-up where this issue is addressed.

**Comment by lrhn** [comment]
If we compare to class overrides, then the subclass does not affect the superclass.

Maybe an augmentation library should not affect the *lexical* scoping of the augmented library. What you see is what you get.

If you want to call a top-level function that doesn't exist yet, you have to declare an abstract function signature, and let the augmentation add the implementation (or import your own library with a prefix, then do `prefix.missingMethod` so it's not a lexical lookup).
For an instance method, you either declared the abstract signature or do `this.missingMethod`, and `Class.missingMethod` for static lookups (where  `Class` exists yet).

It's still a problem with imports. If you import a library, and it doesn't introduce a `foo` declaration, and you write `foo`, with no `foo` in the lexical scope, to mean `this.foo`, then it's a problem if a later phase (even the first macro phase) introduces a new top-level `foo` in the imported library.
We probably do want to be able to import macro-created classes, if we want to macro-create built_values builders, so we can't completely ignore macro-generated top-level declarations in imports.

**Comment by tatumizer** [comment]
Actually, the proposal contains some discussion of shadowing. I'm quoting the relevant part:

> 3) Make it a compile-time error for a macro to introduce an identifier that shadows another.
> 4) Make it a compile-time error to use an identifier shadowed by one produced by a macro.

> The third choice would work but might be overly restrictive. The final option still avoids ambiguity and is a bit more permissive than the third, so we take that approach.

I think this is not an ideal choice. This error, if it occurs, is not fixable: some class has a member `x`, and some macro (unrelated to this class) introduces `x` into top-level scope - now the code that accesses `x` becomes incorrect, but it's not the fault of the code, so why is it flagged on access?
Example:
```dart
// in main.dart
class Foo extends Bar { // Bar defines a member "x"
   //...
   String toString() =>"x = $x"; // FLAGGED??? Not my fault!
}
// other stuff, where some macro is invoked, totally unrelated to Foo or Bar
// in augmentation library
int x=0;
//...
```
There's the 5th way to address the problem, which is not listed in the proposal: disallow the introduction of new variables in the augmentation library (augmenting the existing ones is OK). That is, the augmentation library can only declare new types (classes and typedefs). This solves the problem automatically: if the newly defined class name conflicts with the existing class name, the compiler will complain anyway. But functionality-wise, if the code generated by a macro really needs some new variable in the global scope, it can define it as a static member in some class.

**Comment by lrhn** [comment]
I think my idea differs from both 3. and 4. in that a macro/augmentation declaration *cannot* shadow an existing different declaration. It's simply not in the lexical scope for the unaugmented library code. There is no *conflict*, you can introduce it in the augmentation, but only the augmentation can see that declaration.

It has other issues, but it solves *that* problem.

**Comment by tatumizer** [comment]
I don't think it even solves *that* problem :-)
At least, not without some extra restrictions imposed on the generated code.
The reason is that the results of different macro invocations go into the same augmentation file (concatenated).
One macro adds `x` into top-level scope, another macro, applied to some unrelated class, may think `x` is a member of its class, and we are back to the same problem.
Maybe you meant the generated code has to always use `this.x` instead of `x`? For all instance variables? 

I'm curious: do we know any use case for a macro adding a variable into top-level scope? (I mean, really adding, as opposed to augmenting the definition of a variable from the main library).

**Comment by Levi-Lesches** [comment]
> I'm curious: do we know any use case for a macro adding a variable into top-level scope? (I mean, really adding, as opposed to augmenting the definition of a variable from the main library).

It's not a variable, but there are common requests for something like `@FunctionalWidget` to expand a function into a full-blown widget with it's own class. In this case, a new class is created, along with the identifier denoting the class.

**Comment by tatumizer** [comment]
> It's not a variable

That's quite a difference. I was talking about variables. Clearly, you can introduce new types, but they don't create a shadowing problem: dart doesn't allow one type definition to shadow another anyway.
