### ISSUE TITLE
[Request] Better Generic Type Inference Support

### ISSUE THREAD

**Issue by ragokan** [dart-lang/language#1992]
Hello, what I want to suggest is a bettter support for generics. You know, sometimes Dart automatically infers the type from the variables, but in some cases, it can't, such as in Bloc/Cubits.

```dart
class CounterCubit extends Cubit<int> {
  CounterCubit() : super(0);
}

class Example<MyCubit extends Cubit<State>, State> {
  final MyCubit cubit;
  Example(this.cubit);
  State get state => cubit.state;
}

void main(List<String> args) async {
  final example = Example(CounterCubit());
  example.cubit; // it is CounterCubit
  example.state; // it is Object? or dynamic.
}
```

Lets say that we have a class like this. The type of **example.cubit** is inferred correctly, but **example.state** is not.

![image](https://user-images.githubusercontent.com/63511519/143563719-918a4bc3-4805-47ac-8e8f-7e8011650a79.png)
![image](https://user-images.githubusercontent.com/63511519/143563745-427aa6aa-7dcd-4420-915b-8919b1ae8b09.png)

To infer the type correctly, we have to provide the type manuelly.
```dart
void main(List<String> args) async {
  final example = Example<CounterCubit, int>(CounterCubit());
  example.cubit; // it is CounterCubit
  example.state; // it is Object? or dynamic.
}
```

**Comment by Levi-Lesches** [comment]
How would you want this to work? The code doesn't declare any base class for `State`, so if you omit it Dart has nothing to go off of. It's able to infer `CounterCubit` and not just `Cubit` because you declared `MyCubit extends Cubit<State>` and you passed in a `CounterCubit` as the parameter. But there's no equivalent "hint" for the type of `State`.

**Comment by ragokan** [comment]
Yeah, I am asking about the link between **CounterCubit** and **int**. Let me close this one and discuss it on #620 and #102


> How would you want this to work? The code doesn't declare any base class for `State`, so if you omit it Dart has nothing to go off of. It's able to infer `CounterCubit` and not just `Cubit` because you declared `MyCubit extends Cubit<State>` and you passed in a `CounterCubit` as the parameter. But there's no equivalent "hint" for the type of `State`. In other words, I, as a human reader, have no idea that you want `int` because it's not actually in your code... until you manually put it in.
> 
> Unless you're asking that Dart recognize the link between `MyCubit` and `State`. You'd probably be interested in #620 and #102, which deal with the same request.
