### ISSUE TITLE
Null-safety improving request. Nullable constructor

### ISSUE THREAD

**Issue by Mehmetyaz** [dart-lang/language#1998]
Along with the advantages of null-safety, there are some challenges.
I have a small idea to make null-safety easier. Especially for API developers.

If we have a nullable and non-native type member, we need to recheck the value in `fromMap` constructor.

In ​normally, we have to do: 
```dart
class A {
 ​A({this.optionalDate});

 ​factory A.fromMap(Map<String, dynamic> data) {
   ​return A(
       ​optionalDate: data["date"] == null
           ​? null
           ​: DateTime.fromMillisecondsSinceEpoch(data["date"]));
 ​}

 ​DateTime? optionalDate;
}
```

### My Suggestion

Constructors marked as nullable may not return an instance if any non-nullable parameter is null.

I have some suggestions for marking as nullable constructor.

` int? millis;`
When this is null : 

1 ) 
`DateTime? time = ?DateTime.fromMillisecondsSinceEpoch(millis?);`
`DateTime? time = ?DateTime(year?);`
2 )
`DateTime? time = DateTime?.fromMillisecondsSinceEpoch(millis?);`
`DateTime? time = DateTime?(year?);`

**Comment by jakemac53** [comment]
Instead of nullable constructors, just use a static method that returns a nullable type:

```
class Thing {
  int value;
  
  Thing(this.value);
  
  static Thing? optional(int? value) => value == null ? null : Thing(value);
}
```

**Comment by Mehmetyaz** [comment]
> Instead of nullable constructors, just use a static method that returns a nullable type:
> 
> ```dart
> class Thing {
>   int value;
>   
>   Thing(this.value);
>   
>   static Thing? optional(int? value) => value == null ? null : Thing(value);
> }
> 
> void main() {
>   var nullableThing = Thing.optional(null);
> }
> ```

Yes, i can (and i did) but we provide the same control in this way.  Of course there are alternative ways.  Just a suggestion of mine

**Comment by Mehmetyaz** [comment]
There can be two advantages.
The first is easy typing. Secondly, language codes can be optimized to work more efficiently than our control(for every parameter like `get : null ? get`).

**Comment by jakemac53** [comment]
> The first is easy typing.

You only really save the `static` keyword (usage is the same). I don't think that really justifies a new feature.

> The first is easy typing. Secondly, language codes can be optimized to work more efficiently than our control(for every parameter like `get : null ? get`).

I don't think that the compilers can omit the null checks in this case, it probably ends up the same. If the compiler can prove an argument is null and thus the function would return null, it could still optimize away the rest of the code today and inline `null` (but probably, it should warn you instead if it can statically prove this).

**Comment by munificent** [comment]
When non-nullability was first added to Dart, we discussed allowing factory constructors to return `null` (#279, #604). Ultimately, we felt that the language was better aligned with user intuition if constructors always reliably returning an instance of the type (and not `null`). It's a constructor. That's what constructors do.

If you have an operation that might return a new instance, or might return `null`, then that's a good use case for a static method, like `int.tryParse()`, etc.
