### ISSUE TITLE
How does lambda capturing work in dart?

### ISSUE THREAD

**Issue by duzenko** [dart-lang/language#2002]
I'm confused about lambda capturing local variables. Consider the following code
```
import 'dart:async';

Future<void> main() async {
  int x = 3;
  print(x);
  final y = x;
  final timer = Timer.periodic(Duration(seconds: 1), (_) {
    print('timer $x $y');
  });
  x = 4;
  print(x);
  await Future.delayed(Duration(seconds: 1));
  timer.cancel();
}
```
It produces the following output in dartpad
```
3
4
timer 4 3
```
What is exactly being captured by lambda here? The reference to `3` or reference to `x` that is a reference to `3` itself?
I'm asking because if I pass `x` to a separate function, inside that function the `x` argument will be a copy of original `x`, while in a lambda it seems that both `x`'s are always the same.

**Comment by jakemac53** [comment]
> What is exactly being captured by lambda here? The reference to `3` or reference to `x` that is a reference to `3` itself?

The reference to `x`. Dart uses lexical scoping, so it just looks up x and y in the enclosing scope (the `main` function).

Note that for loops are a little bit weird in here - a variable defined in the for statement gets re-declared for each iteration, so this program prints (0,1,2,3...):

```dart
void main() {
  var funcs = [];
  for (var i = 0; i < 10; i++) funcs.add(() => print(i));
  for (var func in funcs) func();
}
```

> I'm asking because if I pass `x` to a separate function, inside that function the `x` argument will be a copy of original `x`, while in a lambda it seems that both `x`'s are always the same.

Correct, arguments are passed by copy - but note that variables in dart are all actually just references to an object. So if you pass `x` to a function it passes a copy of the reference to the value currently held in `x`.

This is also why the value of `y` is still 3. The line `final y = x;` stores a reference to `3` in `y`, not a reference to `x`.
