### ISSUE TITLE
[match] Exhaustive match

### ISSUE THREAD

**Issue by cindRoberta** [dart-lang/language#2007]
https://github.com/vlang/v/blob/master/doc/docs.md#match

```dart
bool number = true;

match (number) {
  true { print('one'); }
}

print(s);
// error: match must be exhaustive (add match branches for: `false` or `else {}` at the end)
```

**Comment by cindRoberta** [comment]
related to https://github.com/dart-lang/language/issues/546

**Comment by Levi-Lesches** [comment]
Could you elaborate on this?

**Comment by cindRoberta** [comment]
> Could you elaborate on this?

the `match` must mandatorily to avaliate all possible values of variable type or use else case don't match. It's common on functional programming

**Comment by Levi-Lesches** [comment]
Do you mean a switch statement?

```dart
enum Colors {red, green, blue}

void main() {
  final color = Colors.red;
  switch (color) {  // error: missing case for green and blue. 
    case Color.red: print("Red"); break;
  }
}
```

**Comment by munificent** [comment]
Hi, this is a little (well, a lot) terse to be a complete language feature request. Switch statements already do exhaustiveness checking when switching on enum types. I don't believe we do exhaustiveness checks for Booleans, but I could be wrong.

The [in-progress proposal to add pattern matching](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md) does also include exhaustiveness checking for user-defined types, though how it works is not specified yet. I don't think there is any chance we will forget exhaustiveness checking—it's fundamental—so I'm going to go ahead and close this issue.
