### ISSUE TITLE
How does extension method resolution interact with short circuiting null aware operators?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#203]
With non-nullable types, we propose to make the [null aware operators short-circuiting](https://github.com/dart-lang/language/issues/155).  I believe that at least some proposals for the extension method patterns would allow you to write the following extension:

```dart
extension NullInt on int? {
  int toDefault() => this == null ? 0 : this;
}
```

And I believe that the proposals would match this extension to `e.toDefault()` when `e` has type `int` or `int?`.  So the question is, what are the semantics of:

```dart
(null as double?)?.toInt().toDefault()
```

In particular, does this desugar using ordinary method desugaring as:

```dart
  let tmp = (null as double?) in (tmp == null) ? null : toDefault(tmp.toInt())
```

or do we treat extension methods that apply to null differently and desugar as:

```dart
  let tmp = (null as double?) in toDefault(tmp == null ? null : tmp.toInt())
```

cc @munificent

**Comment by lrhn** [comment]
We should definitely make the null-aware operator short-circuiting. 
We should also make extension methods work just like normal methods, to as great an extend as absolutely possible.

That means that
```dart
(null as double?)?.toInt().toDefault()
```
would then rewrite to:
```dart
let tmp = null as double? in tmp == null ? null : tmp.toInt().toDefault();
```
The type of `tmp.toInt()` is `int`, so it matches the `NullInt` extension's type pattern, 
and it ends up as:
```dart
let tmp = null as double? in tmp == null ? null : NullInt.toDefault(tmp.toInt());
```

**Comment by leafpetersen** [comment]
This was also discussed here:  https://github.com/dart-lang/language/issues/392 .

**Comment by leafpetersen** [comment]
This is resolved in favor of treating all method invocations (whether instance or extension) uniformly.
