### ISSUE TITLE
strict `is` which is not be allowed on unrelated types

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/language#2042]
# Proposal: 

a strict `is` where this would not be allowed:

```dart
  fn(ReadState state) {
    if (state is int) { } // state will never be an int
  }
```

# Motivation:

Modelling a state and command separation makes the code very fragile to `is` usages. `is` usage also cannot be trusted in general, but this state and command separation is more subject to `is` usages. This is easier to articulate with code.

Let's model an I/O Task,

We can have:

```dart
enum Status { unstarted, loading, completed }

class Task<I,O> {
  Status status;
  late I input;
  late O output;

  start(I input);
  complete(O output)
}
```

but you can still access the input when a task has not started yet and the compiler will not complain.

An alternative model would have command and states separation:

```dart
class Task<I,O> {
  TaskState<I,O> state;
  start(I input);
  complete(O output)
}
TaskState<I,O> {} 
TaskUnstarted<I,O> extends TaskState<I,O> {}
TaskLoading<I,O> extends TaskState<I,O> {
  I input;
}
TaskCompleted<I,O> extends TaskState<I,O> {
  I input;
  O output;
}
```

On that second snippet, accessing the input when a task is unstarted won't compile. Accessing the output when the task isn't completed won't compile.

So you can use

```dart
  if (task.state is TaskCompleted<String, Data>) {
     // access the data
  }
```

The catch is that as soon as your model change, all the `is` used on that state is a potential bug. You really won't know *for sure* after runtime really, or if you made the change yourself, or reviewed the PR and know the type did not change, but that's not what this issue is about, it's about the compiler catching bugs.

For example if this happens:

```dart
class Task<I,O> {
-  TaskState<I,O> state;
+ ReadState<I,O> state;  // let's assume that ReadState contains all the same information as TaskState but is not a subclass, it happens to be this way because the data model was still under development and not set in stone.
}
```

The if statement above won't be pass anymore anymore, ever. Which can lead to hard to debug bugs (the error might be far away from that if statement).

**Comment by Levi-Lesches** [comment]
Duplicate of https://github.com/dart-lang/linter/issues/2450?

**Comment by cedvdb** [comment]
yes closing

**Comment by cedvdb** [comment]
I'll close this for now, I'm not sure the lint works because, as stated there, `is` with unrelated type has valid uses.

**Comment by mateusfccp** [comment]
> Duplicate of https://github.com/dart-lang/linter/issues/2450?

Not a duplicate, related.
