### ISSUE TITLE
[Bug] addAll results in mutation of input Iterable under certain conditions

### ISSUE THREAD

**Issue by VKBobyr** [dart-lang/language#2043]
The following code:
```dart
void main() {
  final Set<int> someSet = {};
  final values = [1, 2, 3].where((v)=>!someSet.contains(v));
  print("values before: $values");
  someSet.addAll(values);
  print("values after: $values");
}
```

Will result in the output:
```
values before: (1, 2, 3)
values after: ()
```

Which implies that `addAll` resulted in the modification of the `values` variable.

Expected output:
```
values before: (1, 2, 3)
values after: (1, 2, 3)
```

**Details:**
- If we change the condition of `where` to `v > 0` (or any other non-`someSet`-related operation), the problem goes away.
- If we add `toList()` right after the `where` call, the issue goes away.
- This is also an issue when `someSet` is of type `List<int>`.

**Hypothesis**
It seems like there's some sort of an optimization that results in this side-effect, but it feels more like a bug than a feature

**Comment by VKBobyr** [comment]
Seems like it's caused by: https://api.flutter.dev/flutter/dart-core/Iterable/map.html

> The returned iterable is lazy, so it won't iterate the elements of this iterable until it is itself iterated, and then it will apply toElement to create one element at a time. The converted elements are not cached. Iterating multiple times over the returned Iterable will invoke the supplied toElement function once per element for on each iteration.

**Comment by Levi-Lesches** [comment]
Same thing essentially, but the correct documentation comes from [`Iterable.where`](https://api.dart.dev/stable/2.15.1/dart-core/Iterable/where.html), which is the method you use to define `values`: 

> This method returns a view of the mapped elements. As long as the returned `Iterable` is not iterated over, the supplied function `test` will not be invoked. Iterating will not cache results, and thus iterating multiple times over the returned `Iterable` may invoke the supplied function `test` multiple times on the same element.
