### ISSUE TITLE
Question: Can augmentation libraries declare parts?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2057]
https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md

> Augmentations are distinguished by a special library directive with an augment modifier[. ...] After that, an augmentation library may contain anything a regular Dart library can contain: classes, functions, constants, etc.

How about a part directive? :D Personally I hope not! Probably adds complexity for a feature which we may get to deprecate.

**Comment by srawlins** [comment]
CC @munificent @jakemac53

**Comment by jakemac53** [comment]
+1 for just disallowing parts in augmentations. In theory they could be allowed, but unless we see a really compelling reason for them I think its unnecessary.

**Comment by munificent** [comment]
My hope is that if we can do augmentation libraries and private imports then we can deprecate part files entirely. So, no, I'd like to say that augmentations can't declare parts.

**Comment by munificent** [comment]
Specified in cbca2be5e10d64b23cadaeb3acd489d3b3e1d994.
