### ISSUE TITLE
Does an augmentation function need to have the same synchrony modifier as its corresponding function?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2060]
https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md

For example, does an augmentation function for a `sync*` function also need to be declared with `sync*`? I suspect not...

CC @munificent @jakemac53

**Comment by jakemac53** [comment]
> For example, does an augmentation function for a `sync*` function also need to be declared with `sync*`? I suspect not...

I wouldn't say so no, it just needs to have the same API.

**Comment by munificent** [comment]
What Jake said. `async`, `sync*`, `async*`, and `=>` are all specifiers and implementation details of the function body, not its signature. Augmentations don't need to be consistent with them.
