### ISSUE TITLE
Can you add annotations to augment classes, mixins, extensions, functions, or variables?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2061]
https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md

I suspect, without thinking about it too much, that a macro may wish to augment a class or functions, solely in order to apply an annotation which then triggers static analysis. Or perhaps (yikes) to trigger more macros? This might be very powerful, but might be hard to define well.

Can an augmentation class be annotated? If so, does that annotation "apply" to the corresponding class?

CC @jakemac53 @munificent

**Comment by jakemac53** [comment]
This will somewhat come down to the ordering of user defined augmentations versus macro augmentations. User defined augmentation libraries would only be able to apply macros if they are applied _first_.

I think likely they will want to apply augmentations, and to the original declaration being augmented, which will essentially dictate the ordering is user defined augmentations first, then macro expansion to create the macro augmentation.

**Comment by munificent** [comment]
The [non-normative suggested compilation process](https://github.com/dart-lang/language/blob/master/working/macros/feature-specification.md#ideal-compilation-process) for the macros proposal does say that hand-authored augmentations are merged before any macros are applied.

I think it's probably reasonable to actually specify that this must be the processing order. And in that case, I think it's not problematic to allow hand-authored augmentations to add metadata annotations and/or macro applications.

I'll add a section to explicitly allow this and we'll see how it goes.
