### ISSUE TITLE
Can an augment constructor have initializers when the corresponding constructor has a super-initializer?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2062]
https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md

> A constructor marked augment replaces the body of the corresponding constructor in the main library with its body. It appends its initializer list to the original constructor's.

A super-initializer (or redirecting initializer) must go last, right? I think that's a hard requirement from back-ends...

**Comment by srawlins** [comment]
CC @munificent @jakemac53

**Comment by jakemac53** [comment]
Ya I think we should be able to put some special casing in here around super calls in initializer lists. They should always end up at the end, and there must only be at most one of them between the original declaration and augmentation combined?
