### ISSUE TITLE
What does a blank import in an augmentation library do?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2063]
https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md

In a Dart library, `import '' as foo;` imports the containing library with a prefix. What will this directive do in an augmentation library? Does it import the main library (and all augmentations)? Does it import the containing augmentation library? Can we use this syntax to help with scoping and/or private imports?

CC @jakemac53 @munificent

**Comment by jakemac53** [comment]
There is no way to import an augmentation library, since it isn't actually a library itself. I would say this should just not be allowed because I think it is likely to be confusing.

**Comment by munificent** [comment]
> In a Dart library, `import '' as foo;` imports the containing library with a prefix.

😱

> Basically it would be treated as an import of the current URI, which isn't a valid import (not a library).

+1. I don't think we need to spec this explicitly since the desired behavior (it's an error) falls out from that.
