### ISSUE TITLE
Overriden late final fields behaves odd

### ISSUE THREAD

**Issue by nielsenko** [dart-lang/language#2068]
class A {
  late final int x; // late is important
}
class B extends A {
  final int _x;
  B(this._x);

  @override
  int get x => _x;
}

void main() {
  late final int x;
  x = 1;
  // x = 2; // would be compile error

  final b = B(1);
  b.x = 2; // why not compile error?
  b.x = 3; // LateInitializationError here, not above

  // it seems B still has field from A despite override
}

**Comment by jakemac53** [comment]
> b.x = 2; // why not compile error?

There is no public setter for `x` in `B` - you are only overriding the getter. So it is assigning to the field `x` on the super class `A`. The value passed in to the constructor assigned to the private field `_x` on B. So each has only been assigned once.

**Comment by nielsenko** [comment]
But x in A is final. There is no setter to override, or?

**Comment by jakemac53** [comment]
> But x in A is final. There is no setter to override, or?

Late final fields with no initializer _do_ have a setter, because you can assign to them once.

**Comment by jakemac53** [comment]
This is actually a bit of a footgun and at least on my team we avoid public late final fields with no initializer just to avoid the appearance of a real setter.

**Comment by nielsenko** [comment]
Yes, I just shot my foot :-/
Thanks for the clarification

**Comment by jakemac53** [comment]
Ya I think this might be a good lint candidate?

**Comment by jakemac53** [comment]
Actually we already have one https://github.com/dart-lang/linter/issues/2443

**Comment by nielsenko** [comment]
Have you considered making the setter of a late final field private? Despite the getter being public?

**Comment by jakemac53** [comment]
There is was similar discussion here https://github.com/dart-lang/language/issues/1239, you could try reviving that thread? The issue I think is that there are known use cases for the current behavior. The main question is whether its worth making those use cases a lot more verbose is worth while, to make the general case less of a footgun.

At this point it would likely be somewhat breaking to make the change as we have already shipped null safety, but it would maybe be possible with language versioning so it isn't out of the question. At least the approach of making public late final fields with no initializer _invalid_ completely would be potentially viable via language versioning.

**Comment by nielsenko** [comment]
But why mark it late, if you have an initializer? Anyway, thanks for the pointer. I'll review that.

**Comment by nielsenko** [comment]
Arhh.. the initializer runs on first access
```
class B {
  var x = 0;
  late final y = x;
}
void main() {
  final b = B();
  b.x = 1;
  print(b.y);
}

```
prints 1

**Comment by jakemac53** [comment]
> But why mark it late, if you have an initializer?

This allows you to access fields on the class, which you can't do in a normal initializer.

**Comment by jakemac53** [comment]
And yes it also makes it lazy
