### ISSUE TITLE
[enhanced-enums] A value declaration is in a constant context?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2079]
With the upcoming enhanced-enums feature, we can have arguments to constructors in enum value declarations. They are desugared into the right hand side of the declaration of a `static const` variable, so presumably they'd be in a constant context?

```dart
enum E {
    v([]); // Means `v(const [])`?
  const E(_);
}
```

Currently, the analyzer fails to handle the above declaration because it reports that `Enum` does not have the required constant constructor (and this means that _no_ enhanced enum declarations will work at all), but the CFE takes the position that it is not a constant context, and hence it is an error to have `[]` because no implicit addition of `const` occurs.

I do not see any plausible future development where enum values will accept non-constant constructor arguments, so we might as well make the value declaration terms a constant context.

@lrhn, @munificent, @leafpetersen, @natebosch, @jakemac53, @stereotype441, WDYT?

**Comment by lrhn** [comment]
Agree. The proposed desugaring makes it a `const` constructor invocation. The expressions should definitely be in a `const` context.

**Comment by eernstg** [comment]
Aha, I hadn't found that bit in the spec, this means that the fact that it is not treated as a constant context is an issue on implementations: https://github.com/dart-lang/sdk/issues/48232.

So I'll close this issue.
