### ISSUE TITLE
Allow resolvable type literals in macro constructor parameters

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2091]
Today we only allow `Code` expressions and literals as arguments to macro constructors, (and soon want to allow `Identifier` as well).

But there is another use case we want to be able to support which is macros which can accept a generic type as an argument:

```dart
// generates a class that implements Foo<int>, and should be able to introspect on both `Foo` and `int`.
@GenerateClass(Foo<int>) 
```

This needs to be able to pull apart the type literal, such that it can extract both `Foo` and `int` individually, and resolve them back to their original declarations (ie: get `Identifier` instances for them). So a `Code` object won't suffice (not introspectable), and neither will `Identifier` (just a resolvable name, no type arguments).

If we want to support nullable types or function types, then we would need to support full type annotations, which wouldn't be syntactically valid arguments today, and the use case for that isn't super clear. So we may just want to support type literals (which can now at least have generic types).

cc @munificent @srawlins

**Comment by jakemac53** [comment]
One option here would be to add a `TypeLiteralCode` object, which gave you access to the parts:

```dart
class TypeLiteralCode implements Code {
  Identifier get name;
  Iterable<TypeAnnotationCode> get typeArguments;
}
```

In general we were going to move the other direction though - making `Code` objects complete black boxes, and move all the interesting parts to `Impl` classes.

**Comment by munificent** [comment]
> But there is another use case we want to be able to support which is macros which can accept a generic type as an argument:
> 
> ```dart
> // generates a class that implements Foo<int>, and should be able to introspect on both `Foo` and `int`.
> @GenerateClass(Foo<int>) 
> ```

Do you have more details on the use cases? I'm worried that we're going down the road of "macros should be able to do all possible things" and it feels to me like the complexity of the semantics is not converging to something tractable. Is there a reason the user couldn't just write:

```dart
@FillInClass
class C implements Foo<int> {}
```

?

**Comment by jakemac53** [comment]
> ```dart
> @FillInClass
> class C implements Foo<int> {}
> ```

The issue with that comes up when you want to generate multiple classes, it gets quite verbose. I can think of 3 existing use cases today for this - mockito, generated injectors (DI), generated serializers (built value).

**Comment by srawlins** [comment]
+1 to these use cases, and sometimes these have used type arguments, but its an ugly syntax then to have to make up a dummy const type just so you can stick a type arg on it, and then repeat that dummy class over and over.

**Comment by munificent** [comment]
> The issue with that comes up when you want to generate multiple classes, it gets quite verbose. I can think of 3 existing use cases today for this - mockito, generated injectors (DI), generated serializers (built value).

Can you point me to some (internal or external) concrete examples of existing codegen solutions for this? I agree reducing verbosity is good, but it might be worth making things somewhat more verbose if it leads to a simpler feature.

**Comment by jakemac53** [comment]
Here are a few concrete examples:

https://github.com/google/built_value.dart/blob/master/example/lib/serializers.dart#L27
https://github.com/dart-lang/mockito/blob/master/example/example.dart#L29
https://github.com/simolus3/moor/blob/develop/drift/example/main.dart#L57
https://github.com/google/inject.dart/blob/master/example/coffee/lib/coffee_app.dart#L16

**Comment by munificent** [comment]
Those are great, thanks. Hopefully, we'll have record types in the nearish future. I wonder if we should consider using those to represent a variadic list of types passed to a macro? I could imagine something like:

```dart
@SerializersFor<(
  Account,
  Cat,
  CompoundValue,
  Fish,
  GenericValue,
  SimpleValue,
  VerySimpleValue,
)>()
final Serializers serializers = _$serializers;
```

Of course, this raises the question of how *type arguments* to macros are interpreted. But it would at least solve the *syntactic* problem of giving you an existing well-defined way to write down a series of arbitrary type annotations.

**Comment by munificent** [comment]
> I think type arguments to macros are generally going to be difficult to support unfortunately - the types passed in will likely only exist in the users program.

I would assume that like value arguments, they would be passed to the macro as meta-objects, not actual type instantiations. (This definitely would make it weird to have them defined on the macro class itself as type parameters. We might want to do something funny like allow them to be written syntactically as type arguments on the macro application, but actually pass them to the macro's constructor as meta-value arguments. Something like a `List<TypeAnnotation> typeArguments`.)

> We should honestly probably block type arguments generally on macro classes until/unless we can specify how they would work without things getting too complicated.

+1.

**Comment by jakemac53** [comment]
The API for this has landed in https://dart-review.googlesource.com/c/sdk/+/309021. Actual support from the frontends will come later.
