### ISSUE TITLE
Allow collections of Identifiers, type literals, and literals in macro constructor parameters

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2092]
The macro spec currently says:

> [...] macros can also accept arguments as values. However, only built-in value types (int, bool, etc.) are allowed and arguments must be _simple literal expressions_.

I think we should support "collections" of built-in value types and (adjascent or as part of https://github.com/dart-lang/language/issues/2091) type literals and identifiers. "Collections" means Lists, Sets, and Maps, though I don't have thoughts on any type restrictions on the key of a Map (maybe just String? Maybe no restriction beyond "only built-in value types"?).

For example:

```
@GenerateSomething([Foo, Bar])
```

which allows access to `Foo` and `Bar` as Identifiers, or as type literals, etc.

This raises a question about spreads. Today, the typical way to write an annotation which includes a list literal which folds in elements from a constant defined elsewhere is a spread. Can we allow:

```
const classes = [Foo, Bar];
@GenerateSomething([...classes, Baz])
```

Allowing this would be consistent with the support that constant evaluation provides, but might be extremely difficult / impossible because it _requires_ constant evaluation. Maybe we could sidestep constant evaluation by saying only a subset of constant values are supported in a collection of type literals or `Identifiers`...

cc @munificent @jakemac53

**Comment by jakemac53** [comment]
Yep I was just about to file this same issue :)

**Comment by jakemac53** [comment]
This is allowed now
