### ISSUE TITLE
?? operator does not allow 'return' or 'throw'

### ISSUE THREAD

**Issue by imrhk** [dart-lang/language#2095]
In Kotlin, I have been used to `arg ?: return` to check if function argument is null or some other variable is null. If that's the case, return immediately. In android this was really helpful where I did `context ?: return` in Android apps.

I tried doing the same with ?? operator but I wasn't successful.
Like for `ScrollController? _scrollController` data member, I want to do 
`final scrollController = _scrollController ?? return` 

This basically means if variable is null, return or set the value as final where object is non-null. 

As far as the feature goes, it works for `throws` as well. Ref: https://kotlinlang.org/docs/null-safety.html#elvis-operator

**Comment by Semvrij** [comment]
Can you take a look at #2088 and #2025 ? This is probably a duplicate.

**Comment by lrhn** [comment]
Also, Dart does allow using `throw` as an expression, you just need parentheses for precedence reasons:
```dart
final scollController= _scrollController ?? (throw StateError("No scroll controller?!?"));
```

**Comment by eernstg** [comment]
@imrhk, I think the discussion in #2025 covers this issue to a very high degree. So perhaps it would be useful to close this issue, and take the discussion in #2025 instead?
