### ISSUE TITLE
Should switch expressions be allowed without a scrutinee?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#2111]
In the discussion issue on [ranges](https://github.com/dart-lang/language/issues/2105), the point was raised that there are use cases where a developer might use a switch statement or expression with some or all cases explicitly ignoring the scrutinee.  For example:

```dart
int compare(int a, int b) =>
  return switch (null) {
    case _ if (a < b) => -1
    case _ if (b < a) => 1
    default => 0
  }
```

Should we consider supporting this directly by allowing the scrutinee and/or the pattern to be elided?  For example, we could say that the pattern could be elided when a guard is present, resulting in the following:

```dart
int compare(int a, int b) =>
  return switch (null) {
    case if (a < b) => -1
    case if (b < a) => 1
    default => 0
  }
```

We could further say that the `case` is not necessary (though this may be harder to parse?):

```dart
int compare(int a, int b) =>
  return switch (null) {
    if (a < b) => -1
    if (b < a) => 1
    default => 0
  }
```

Separately we could consider allowing the scrutinee to be elided:

```dart
int compare(int a, int b) =>
  return switch {
    case if (a < b) => -1
    case if (b < a) => 1
    default => 0
  }
```

or 

```dart
int compare(int a, int b) =>
  return switch {
    if (a < b) => -1
    if (b < a) => 1
    default => 0
  }
```

This basically provides a general form of `if then else` expression, along with an alternative form of `if then else` statement which is arguably cleaner for deeply nested `if then else if` chains.

**Comment by rrousselGit** [comment]
I don't like the idea of writing `if` instead of `case if`

The `case` keyword is quite important IMO for quickly reading the switch rapidly. Without it, it could be harder to differentiate cases from an `if` condition within a case:

```dart
switch (value) {
  case 42:
    if (condition) doSomething();
  if (value > 0) => another()
  default: ...
}
```

vs:

```dart
switch (value) {
  case 42:
    if (condition) doSomething();
 case if (value > 0) => another()
 default: ...
}
```

**Comment by munificent** [comment]
My current thinking is "no". We are already talking about a *lot* of new syntax for pattern matching:

1. About a half dozen matcher pattern forms
2. Roughly the same binders that are mostly similar but not exactly in some cases
3. Changing switch statements to not require break
4. Switch expressions
5. Probably some kind of `if-case` construct
6. Record literals
7. Record types
8. Patterns in variable declarations

I think all of those are well-motivated but the overall surface area is a lot. I think there's something to be said for keeping things simple where we can. You can already write a "match everything with a guard" using `case _ if (...)` and that's probably sufficient.

**Comment by Levi-Lesches** [comment]
I was under the impression that guard statements (especially with defaults) were conveniences for switches _based_ on if statements, not that they should replace ifs altogether. Similarly, switch expressions provide a general-form ternary operator, but ternaries are just a shorthand -- not meant to replace the if statement. Compare 

```dart
int compare(int a, int b) => switch {
  if (a < b) => -1
  if (b < a) => 1
  default => 0
}
```
to the simpler and more familiar: 
```dart
int compare(int a, int b) {
  if (a < b) return -1;
  if (a > b) return 1;
  else return 0;
}
```

There is a difference between statements vs expressions, but the switch example introduces another contrast: most users are taught that switches are used in const contexts. On the other hand, if statements are traditionally used for runtime evaluation.

**Comment by leafpetersen** [comment]
> Similarly, switch expressions provide a general-form ternary operator, but ternaries are just a shorthand -- not meant to replace the if statement. Compare

I don't know what you're trying to say here.  It's true that in a return position specifically you can interchange between `return switch ...` and `switch .... ` with `return in each of the bodies, but that is not true in the general case.

> There is a difference between statements vs expressions, but the switch example introduces another contrast: most users are taught that switches are used in const contexts. On the other hand, if statements are traditionally used for runtime evaluation.

I'm not sure what you're saying here.  Switches *cannot* be used on const contexts and have nothing to do with const?

**Comment by Levi-Lesches** [comment]
> I'm not sure what you're saying here. Switches _cannot_ be used in const contexts and have nothing to do with const.

By const I just meant the things we test against have to be const. 

```dart
void main() {
  int getInt() => 1;
  switch (1) {
    case getInt(): print("Worked");  // does not, in fact, work
  }
}
```

> I don't know what you're trying to say here.

I probably made it too complicated, but I meant to say that "switches where the guards are the only thing of interest" are basically just if-statements, with the only advantage that switches may soon be expressions, whereas there is no general if-expression (besides for ternaries).

**Comment by leafpetersen** [comment]
I think this is probably not going anywhere, so closing.

**Comment by munificent** [comment]
I could definitely see us adding it in a later batch of switch changes, but probably not in the first release, no.
