### ISSUE TITLE
Breaking change request: non const expressions bug fix

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/language#212]
In Dart 2.1.1 and earlier, some Dart tools including analyzer had a bug that caused them to accept some invalid default parameter values and const constructor initializers. This bug can be fixed then may appear as a breaking change on code bases.

Bug dartbug.com/32913
CL https://dart-review.googlesource.com/c/sdk/+/91105

# Expected Impact

We expect this to be unlikely to affect all but a very very small minority of users. I saw two cases in internal code so it does happen but seems very very rare.

# intended change

Previously this example analyzed and built cleanly with all tools

```dart
callback<T>(T t) => ...; // a generic function

f<T>( // a function with a type parameter
  [
    Function(T) x // with an optional function argument referencing the type parameter
      = callback // with the default value referencing the generic function
  ]
) { ... }

// or

class C<T> { // a generic class
  final Function(T) x; // with a function-typed field that references a type parameter
  const C() // with a const constructor
    : x // with an initialzer referencing that field
      = callback; // with an expression that references the generic function
}
```dart

The exact conditions are complicated to describe, but spelled out in the later "Justification" section.

At first the fix will only affect the analyzer and DDC. The later fixes to the other tools (vm & dart2js through cfe) will not be considered breaking changes. However, this distinction may give users some "wiggle room" if they really really need it.

# Mitigation

If you are affected by this breaking change, the fix is typically to use `dynamic` and `Null` to explicitly create a callback which is assignable for all values of `T`.  (The reason this works is described here).

```dart
callbackWithParameter<P>(P p) => ...;
R callbackWithReturn<R>() => ...;

const Null Function() callbackNull = callbackWithReturn;
const Function(dynamic) callbackDynamic = callbackWithParameter;

f<T>([
  Function(T) x = callbackDynamic,
  T Function() y = callbackNull,
]) { ... }
```

This works for const constructor initializers as well as default parameter values.

Specifically for default parameter values, you also have the option of not specifying a default value and rather using `??=` in your method body to set the default. That way there is no requirement that your default value be a valid const expression.

Because the breakage is expected to be rare, I expect an announcement to be sufficient in helping the community respond.

# Justification

The problem is subtle but important for consistency with how constant values are handled. In Dart, every syntactic occurrence of a compile time expression yields one identical constant value. Dart also enforces that default parameter values and constant initializer values are const.

Here are some examples of behavior that will be unaffected:

```dart
void f() {
  const []; // Only one list is ever created, regardless of how many times f() is called
}

void f2([Map x = const {}]) { // the default value of x must be const
  ...
}

class C {
  final Map x;
  C() : x = const {}; / the initializer of x must be const
  ...
}
```

And type variables are not const (this behavior is also not changed):

```dart
class C<T> {
  const List<T> list = <T>[]; // error: T is not a constant
}
```

This is because, in accordance with the spec and implementation of const, the expression must produce one value, and `T` is a placeholder for what can be any number of values at compile time.

We missed a case, however, where type variables are inferred and results in a non-const default parameter value, or const constructor initializer:

```dart
callback<R>(R r) => ...;

f<T>([Function(T) x = callback]) { ... }

// or

class C<T> {
  final Function(T) x;
  const C() : x = callback;
}
```

Here, the type parameter `T` is implicitly applied to `callback<R>` so that the assignment can succeed. This results in a non-const value of non-const type `Function(T)`. 

This violates the design that one constant expression yields one constant value, and therefore caused different runtime failures of different kinds in different tools.

**Comment by leafpetersen** [comment]
This goes in the SDK repo.

https://github.com/dart-lang/sdk/blob/master/docs/process/breaking-changes.md#step-1-announcement
