### ISSUE TITLE
Make `augment` a reserved word in augmentation libraries and add an `augmentation of` directive.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2120]
I was chatting with @johnniwinther earlier today about an ambiguity issue during the parsing of augmentations. Generally the issue is when a parser sees:

```dart
augment foo();
``` 

Is `augment` a type called `augment` or the keyword `augment`?

We discussed on solution to this, which is to make `augment` a reserved word within augmentation libraries. And then to also add an `augmentation of <uri>;` required directive, which allows a _parser_ to know that it is parsing an augmentation library (and which library it is an augmentation of), before it sees any `augment` keywords.

**Comment by lrhn** [comment]
Being a built-in identifier should be enough to avoid an ambiguity with a type expression. On the other hand, if augmentation libraries are completely new, it's easy to add it as a reserved word from the start, and that might make things easier in the long run.

**Comment by johnniwinther** [comment]
The main problem here is whether we know that we are parsing an augmentation library. We do know it for the synthesized augmentation libraries from macro applications and libraries that we read as a consequence of having read an `import augment` declaration. But if we are just given a set of .dart files, some being libraries, some being parts, and some being augmentation libraries, we don't, and this is a mode that we currently support for libraries/parts.

**Comment by lrhn** [comment]
The way augmentation libraries are currently [specified](https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md#defining-an-augmentation), they need to start with `library augment "mainlibrary.dart";`.
That first `augment` after `library` can be a contextual keyword (since it's ambiguous with just `library augment;` until the next token). So, like part files, an augment file is clearly marked as such, and points to its main file.

**Comment by johnniwinther** [comment]
Good point. That might be enough to go on.

**Comment by lrhn** [comment]
Another option is to make `augment` a plain reserved word in language version 2.X where we introduce it.

It means any existing uses of `augment` will need to change, so there may be a migration cost.

Or make it a built-in identifier in language version 2.X, which is required for you to be allowed to write `import augment "..."` or `library augment "..."` anyway.
That will likely not cause any migration needs. No-one uses `augment` as a type name or type variable, so it's only if they use it as an import prefix, and that's easily fixed, if it happens at all.

By making it a built-in identifier in general, not only in augment libraries, we can more easily give better error messages if someone writes `augment foo()` outside of an augment library.

**Comment by jakemac53** [comment]
Note that the macro APIs themselves today have methods called `augment` :). I do also see one example internally of a function called `augment`.

I don't want to be in a situation where certain APIs can't be augmented just because they are named `augment`. So whatever solution we have I think should be able to allow members/variables to have that name. I don't care so much about disallowing _types_ from having that name, as it goes against convention anyways.

**Comment by munificent** [comment]
> you then can't refer to it in an augmentation library.

That could be addressed by https://github.com/dart-lang/language/issues/271.
