### ISSUE TITLE
Don't provide introspection methods on `Record`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2127]
The current [proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/records-feature-specification.md#the-record-class) specifies introspection methods on the `Record` class:
```dart
abstract class Record {
  static Iterable<Object?> positionalFields(Record record);
  static Map<Symbol, Object?> namedFields(Record record);
}
```
This feels a little too close to reflection for me. I'd propose to *not* have these members, and *only* allow destructuring of records through pattern matching - which the requires knowing the structure of the record statically.
(I'd also drop the `DestructureN` interfaces completely.)

Introspection giving you the *names* of fields, as symbols (because `Map.keys` can be read), and dynamic lookup on that map, *is* reflection. It converts a typed and structured value into an untyped and non-structured meta-value which can be inspected and accessed dynamically. That will make it harder to statically determine if some fields can be optimized away. If no part of the program reads the fourth element of a five-tuple, then the compiler might be able to tree-shake them all away. If you can access the elements reflectively, then that optimization, and any similar optimization I haven't thought about, gets a lot harder.

(I'd consider allowing access to record members by static name or index, as `record.name` or `record[constantIndex]`, which can be checked against the static record structure and type, but I'm also fine with not having those and relying entirely on destructuring, like `if (record is (var x, foo: var y)) ... x + y`.)

**Comment by rrousselGit** [comment]
I agree. I don't like seeing those either

To begin with, that part of the proposal doesn't seem related to the problem Records are trying to solve (pattern-related features).

And with metaprogramming, use-cases for those are also a lot rarer

**Comment by jakemac53** [comment]
I do think these APIs would be _useful_, for instance it should allow you to create a general purpose `String jsonEncode<T extends Record>()` function. I don't think it is enough to make an equivalent `jsonDecode` function though so maybe it isn't super useful.

**Comment by lrhn** [comment]
Keeping names around at runtime is only necessary when a tuple is cast to `Record` or `Object` (or above), and needs to be cast back.
Even then, you don't need the actual *names*, just a check that the *structure* is the same. 

You should be able to assign an ID (an integer, basically) to each different structure (number of positional elements, names of named elements), and only remember that a runtime. Accessing anything by name requires first matching against a specific structure, and then that name is just an index into the representation.

Say that the implementation always stores records as positional values first, named values after in alphabetical order.
Doing `record.foo` (or whichever way you extract the named `foo` value) means indexing into the record data at the position statically determined to correspond to the `foo` name. When boxed as a `Record` or `Object`, only the structure ID is needed. If you can't match that `Record` against its known structure ID, you can't access its members at all.
You can do `Record r = ...; r as (int, int)` by checking that the structure ID of the boxed record is the ID of "two positional elements, no named elements" and checking that the two positional elements (indexes guaranteed by the structure with that ID) both have type `int`.

You don't need to remember the names at all if you can only destructure known record types.

You shouldn't be able to introduce new record structures at runtime. If the `(_,_,x:_)` structure does not occur in the program source, then there is no way to get such a tuple at runtime (existing in the program source might include parameter lists, if we can get those as records).

Since records are only subtypes if they have the same structure, knowing the structure is enough. 

If we avoid reflective access, and only allow *typed* access to records, meaning we know the specific structure of the record, then names are not needed at runtime.
If we allow dynamic access or reflective access, then we need to retain names.

**Comment by jakemac53** [comment]
That does sound feasible (at least in minified mode) to get rid of the names.

**Comment by munificent** [comment]
Good call. Done.
