### ISSUE TITLE
Missing syntax for augmenting constructors

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/language#2136]
The syntax section in the [augmentation libraries proposal](https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md#syntax):

```
declaration ::= ...
  | redirectingFactoryConstructorSignature
  | constantConstructorSignature (redirection | initializers)?
  | constructorSignature (redirection | initializers)?
```

doesn't support augmenting constructors:
```
augment class Class {
  augment Class();
  augment const Class.foo();
  augment factory Class.bar() => new Class();
  augment factory Class.baz() = Class.foo;
}
```

**Comment by johnniwinther** [comment]
cc @jakemac53

**Comment by TimWhiting** [comment]
I was experimenting with the macro example in the language repo trying to create a data class macro like the `freezed` package and ran into this issue.
```
org-dartlang-augmentation:/Users/timwhiting/language/working/macros/example/bin/user_main_2.dart-2:5:9: Error: This patch doesn't match origin declaration.
augment MyClass.named(i0.String val, i0.int val2, ) => Named(val,val2,);
        ^
bin/user_main_2.dart:14:20: Context: This is the origin declaration.
  external factory MyClass.named(String val, int val2);
                   ^
org-dartlang-augmentation:/Users/timwhiting/language/working/macros/example/bin/user_main_2.dart-2:5:56: Error: Constructors can't have a return type.
Try removing the return type.
augment MyClass.named(i0.String val, i0.int val2, ) => Named(val,val2,);
                                                       ^
0:00:05.098524: failed to build!
```

**Comment by TimWhiting** [comment]
Yes I believe it is supported already through the macro system, but when parsing the resulting augmentation file the issue it complains about is the augment keyword (It is thinking that it is a return type, which is invalid for constructors).

**Comment by jakemac53** [comment]
Yes, I think the CFE doesn't yet support augmenting constructors (because of this issue), but it was probably just missed that the grammar was already defined for at least basic constructors.
