### ISSUE TITLE
[views, extension types] How do we access 'this' object?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2140]
[Views](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification-views.md) (aka [extension types](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification.md)) have been proposed to share a lot of static analysis and dynamic semantics with extension methods, based on the fact that the methods are resolved statically.

So we'd have methods with object-oriented dispatch (regular instance methods) and statically resolved methods (extension methods and view methods), yielding 2 fundamental sets of rules about what a "method" is. If view methods and extension methods are different then we'll have 3 sets of rules. Going from 2 to 3 at such a fundamental level is a significant source of complexity and potential confusion.

However, one of the differences between a view method and an extension method is that the view introduces a type, and this means that the type of `this` in a view method _could_ be the view type itself, following the rule that `this` in a class or a mixin has the type which is introduced by the enclosing declaration.

In contrast, the type of `this` in an extension method is the on-type of the enclosing `extension` declaration. In this case there is no obvious alternative, because the `extension` declaration does not introduce a type.

So let's remind ourselves about the rules for extension methods, and then consider some alternative rules that we could use with view methods.

### Scoping and Types for Extension Methods

Here is an example that illustrates the scope and type rules for the receiver of an extension method:

```dart
class C {
  void c() => print('C.c');
  void both() => print('C.both');
}

extension E on C {
  void e() => print('E.e');
  void e2() => print('E.e2');
  void both() => print('E.both');

  void test(C other) {
    c(); // 'C.c'.
    e(); // 'E.e'.
    e2(); // 'E.e2', "lexical scope always wins".
    both(); // 'E.both', "lexical scope always wins".

    this.c(); // 'C.c'.
    this.e(); // 'E.e'.
    // this.e2(); // Error, ambiguous.
    this.both(); // 'C.both', "instance method always wins".

    other.c(); // 'C.c'.
    other.e(); // 'E.e'.
    // other.e2(); // Error, ambiguous.
    other.both(); // 'C.both', "instance method always wins".
  }
}

extension E2 on C {
  void e2() => print('E2.e2');
}

void main() {
  C c = C();
  c.test(c);
  c.c(); // 'C.c'.
  c.e(); // 'E.e'.
  // c.e2(); // Error, ambiguous.
  c.both(); // 'C.both', "instance method always wins".
}
```

As we can see, the lexically enclosing scopes always dominate any other mechanism (which is also how Dart works in general), so invocations `e()`, `e2()`, and `both()` inside the declaration of `E` all resolve to the declarations from the enclosing scope.

The invocation of `c()` inside `E` is implicitly treated as `this.c()`, because no declaration named `c` is in scope. (Implicitly adding `this` as the receiver in this situation is also a general rule for Dart).

When there is an explicit receiver, the lexical scope is irrelevant: We're invoking a member with a particular name, and we can get that from the interface of the type `R` of the receiver, or as an extension method where `R` matches the on-type.

The invocation of `this.c()` inside `E` is a regular instance method invocation. The invocation of `this.e()` inside `E` is implicitly treated as `E(this).e()`, which makes it a normal implicit extension method invocation. But `this.e2()` is an error, because we have an explicit receiver of type `C`, and there's nothing that makes `E.e2` more relevant than `E2.e2`, or vice versa.

Finally, `this.both()` invokes `C.both`, because instance methods always dominate extension methods when there is a name clash.

The remaining invocations have an explicit receiver, and they all behave as mentioned already.

So the main rules here are that "the lexical scope always wins" for a plain lookup (that is, when the receiver is not specified). When the receiver is specified, the rule is "an instance method always wins over an extension method".

For a class/mixin, for a member whose name isn't in the global scope and isn't shadowed by a local declaration, there is no difference between specifying the receiver `this`, and omitting it and having it added implicitly.

But in an `extension` declaration `E`, we have a discrepancy in that `m()` and `this.m()` can invoke different methods, or the latter can be an ambiguity error.

### Scoping and Types for View Methods

The current proposal specifies that `this` in the body of a view method has the on-type of the view as its type (same as in an extension method), and "the lexical scope  always wins" when the receiver isn't specified.

The conceptual motivation for this is that `V` implements a facade for an instance of `C`, and we're implementing that facade by using the members of `C`, so `this` should have type `C`.

```dart
class C {
  void c() => print('C.c');
  void both() => print('C.both');
}

view V on C {
  void v() => print('V.v');
  void v2() => print('V.v2');
  void both() => print('V.both');

  void test(C otherC, V otherV) {
    c(); // 'C.c'.
    v(); // 'V.v'.
    v2(); // 'V.v2', "lexical scope always wins".
    both(); // 'V.both', "lexical scope always wins".

    this.c(); // 'C.c'.
    // this.v(); // Error, no such member.
    this.v2(); // 'E2.v2'.
    this.both(); // 'C.both' (it's never `V.both` for a `C` receiver).

    otherC.c(); // 'C.c'.
    // otherC.v(); // Error, no such member.
    otherC.v2(); // 'E2.v2'.
    otherC.both(); // 'C.both'.

    // otherV.c(); // Error (`show c` would make it 'C.c').
    otherV.v(); // 'V.v'.
    otherV.v2(); // 'V.v2'.
    otherV.both(); // 'V.both'.
  }
}

extension E2 on C {
  void v2() => print('E2.v2');
}

void main() {
  C c = C();
  // c.test(); // Error, no such member.
  c.c(); // 'C.c'.
  // c.v(); // Error, no such member.
  c.v2(); // 'E2.v2'.
  c.both(); // 'C.both'.

  V v = c; 
  v.test();
  // v.c(); // Error, no such member (`view V .. show c` would make it 'C.c').
  v.v(); // 'V.v'.
  v.v2(); // 'V.v2'.
  v.both(); // 'V.both'.
}
```

The main difference (comparing view methods with extension methods) is that a view method never kicks in implicitly: `V.v` can not be invoked on a receiver whose static type is `C`, only on a receiver whose static type is `V`. In this approach, the type of `this` inside the declaration of `V` is the on-type `C`. These two things determine the treatment of all invocations with an explicit receiver.

The remaining (and perhaps surprising) fact is that it is still possible to have the rule that "the lexical scope always wins". So `v()` inside `V` calls `V.v`, even though the type of `this` is `C`, and `otherC.v()` is an error (because a receiver of type `C` does not have a member named `v`).

This is achieved by looking up `v` from the call site `v()`, finding it in the enclosing scope (the body of `V`), and then implicitly adding `V(this).`. So we're still using `this` as the receiver, but we're explicitly invoking the view method, such that we still have the property that "the lexical scope always wins".

So why are we justified in thinking that `this` can be viewed as a `V`? Well, we're running a method in `V`, so the object denoted by `this` _did_ have the type `V` at the call site.

(As mentioned, we could use `view V ... show c ...` to make the method `c` available as a method of `V`, but members of the on-type are only available as members of the view if we request it explicitly.)

In any case, we still have the discrepancy that `v()` differs from `this.v()` (the latter is an error), and `both()` differs from `this.both()` (they call different methods).

### Alternative Scoping and Types for View Methods

Following the approach taken in class and mixin declarations, we could let `this` have the type of the enclosing declaration (so `this` has type `V` inside the declaration of `V`), and we could use a separate name for the object  denoted by `this`, and give that name the on-type.

So we'll use the word `on` here: We have `identical(this, on)`, but the type of `on` is the on-type of the enclosing view. We would then have the following:

```dart
class C {
  void c() => print('C.c');
  void both() => print('C.both');
}

view V on C {
  void v() => print('V.v');
  void v2() => print('V.v2');
  void both() => print('V.both');

  void test(C otherC, V otherV) {
    // c(); // Error, no such member.
    v(); // 'V.v'.
    v2(); // 'V.v2'.
    both(); // 'V.both'.

    // this.c(); // Error, no such member.
    this.v(); // `V.v`.
    this.v2(); // 'V.v2'.
    this.both(); // 'V.both'.

    on.c(); // 'C.c'.
    // on.v(); // Error, no such member.
    on.v2(); // 'E2.v2'.
    on.both(); // 'C.both'.

    otherC.c(); // 'C.c'.
    // otherC.v(); // Error, no such member.
    otherC.v2(); // 'E2.v2'.
    otherC.both(); // 'C.both'.

    // otherV.c(); // Error (`show c` would make it 'C.c').
    otherV.v(); // 'V.v'.
    otherV.v2(); // 'V.v2'.
    otherV.both(); // 'V.both'.
  }
}

extension E2 on C {
  void v2() => print('E2.v2');
}

void main() {
  C c = C();
  // c.test(); // Error, no such member.
  c.c(); // 'C.c'.
  // c.v(); // Error, no such member.
  c.v2(); // 'E2.v2'.
  c.both(); // 'C.both'.

  V v = c; 
  v.test();
  // v.c(); // Error, no such member (`view V .. show c` would make it 'C.c').
  v.v(); // 'V.v'.
  v.v2(); // 'V.v2'.
  v.both(); // 'V.both'.
}
```

The rules do seem to be more consistent when `this` has the type of the enclosing view.

On the other hand, it is possible that it gets tedious to write `on` whenever we want to call a member of the on-type on the receiver, because the implicit receiver can only be `this`, and `this` has type `V` rather than `C`.

### Discussion

We could choose the type `C` or `V` for `this`, and we could have another keyword with the other type (I used `on` because it's short, and it has the on-type of the view).

We could also allow both `this` and `on` to be implicit receivers, and try them both in that order (such that "the lexical scope still wins").

@leafpetersen, @lrhn, @munificent, @jakemac53, @stereotype441, @natebosch, WDYT?

**Comment by lrhn** [comment]
There have been multiple view ideas floating around, some which disallow casting from the `on` type to the view type (they require constructors which can maybe even validate the inputs), some which do not allow from the view type to the `on` type. Which approach is used also affects what that view itself can do to convert (unless the restriction is removed inside the view, which is a possibility.)

If we only have `this` to refer to the current value, then we have to choose one static type.
Since the lexical lookup can find view members, making `this` refer to the `on` type seems to give the most affordances. You can access both kinds of member. You can't access `this` *at* the view type, though, so if you need to call a callback with the current object at the view type, you might need to go through a constructor (or cast, if allowed).

Having two different accessors provides the most flexibility. Using `on` is a possibility, although it's not currently a reserved word. (We could make it reserved only inside view member bodies, like we do for `await` only inside `async[*]` function bodies. Since there are no existing views, that could work, but would prevent those functions from writing code `foo.on["click"].oStuff()`.)   

Another option is to use `super` for the `on` type. It's not *really* a super-class, but I think it's *similar enough*, and it's already a reserved word, and you can't use it for anything else inside a view member.

All in all, I think `this` having type `V` and `super` having type `C` (and, probably, needing to be allowed as a stand-alone expression, without a member access after it) will be consistent and understandable, and will work no matter which restrictions we put on conversion between `C` and `V`.

**Comment by eernstg** [comment]
@lrhn wrote:
> All in all, I think `this` having type `V` and `super` having type `C` .. will work

This is very nearly https://github.com/dart-lang/language/pull/1744.

Note that the use of `super` is somewhat misleading semantically: `super.foo()` in a class will statically resolve to a specific method implementation, but `super.foo()` in a view method will invoke `foo` on the underlying instance of the on-type using normal object-oriented dispatch.

So if we'd prefer to use another keyword (say, `on`) to access the on-type members then we have ways to do that which are not very disruptive:

`on` is a regular identifier (not reserved, not built-in), and we could keep it like that by implicitly introducing a final local variable named `on` at the beginning of each view member body. This allows for using the representation object directly via the name `on`, but also to access members named `on` in expressions (e.g., `someExpression.on['x']`, `on.on()`, `this.on = true`).

Name clashes with top-level declarations named `on` could be inconvenient, so we might want to allow developers to _choose_ which name to use for this purpose (`view V on T named myOn {...}`), but it might be more important to keep it simple (and always use `on`), and then to use ad-hoc workarounds to deal with name clashes, if any.

**Comment by lrhn** [comment]
Binding the name in the `on` type looks remarkably like the *pattern* `Type id`.
If/when we have patterns, maybe the `on` phrase should just be a general pattern.
```dart
view V on T id {  // Pattern matched against `T` and bound to `id`
  // refer to `id`.
}
```
or even
```dart
view Pair<X, Y> on (X _x, Y _y) { 
  X get x => _x;
  Y get y => _y;
}
```
Those patterns should be "binders" in the current pattern proposal terminology (irrefutable if the static type matches).

Maybe we can use `on <type> <identifier>?` as the syntax now, even before extending it to full patterns in the future
(@munificent for the pattern context).

**Comment by lrhn** [comment]
Agree, that was a worry that came to me too, after writing the above: It's not clear when destructuring happens because the type is a thin view on the structured object, and we don't want to allocate the extra variables.

I'd still suggest `on Type identifier` as the way to name the value at the `on`-type, with `this` showing it at the view type.
That, or `super` to refer to the `on` type. Don't like `on`, it's not even a noun.

**Comment by leafpetersen** [comment]
> I'd still suggest `on Type identifier` as the way to name the value at the `on`-type, with `this` showing it at the view type.
> That, or `super` to refer to the `on` type. Don't like `on`, it's not even a noun.

+1 Those are my preferred ways of dealing with this.

**Comment by eernstg** [comment]
Sounds good! So what's better, `super` or "specify the name you want"?

We do have the somewhat subtle semantic mismatch between `super` in a class and the use of `super` to denote `this`-with-the-on-type, but at this point I tend to think that it is even more important that `super` consistently and immediately stands out as a specific concept when we're reading the code, and there are no name clashes.

Alternatively, we'd need to adopt the habit of searching for the beginning of any `view` declaration that we're looking at, in order to see "what's the name of the on-type object in _this_ view then?", which seems to be a source of unnecessary, daily irritation.

If we do decide that `super` is the way to go then I'd go over https://github.com/dart-lang/language/pull/1744 again and ensure that everything is up to date, and then we'd have a round of reviews and get it landed.

**Comment by natebosch** [comment]
I do like `super` for this. I think I would assume the described behavior if I saw `super` used in a view.

**Comment by eernstg** [comment]
Closing: The extension types of today (Oct 2023) use `this` to denote the representation object using the extension type itself as the static type (so that's the "outside view"), and they use an author-specified name for the representation object with the representation type (the "inside view"), and that is not likely to change.
