### ISSUE TITLE
Why not allow type promotion of `this`?

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/language#2141]
The typical reason for disallowing type promotion of non-local variables is that they could be pathological getters that return inconsistent values.

`this` is non-local but cannot be a getter.  Could an exception be made to allow `this` to be promoted?  Of course, a trivial workaround is to introduce a local variable (e.g. `self`):

```dart
import 'dart:typed_data';

/// Converts a `List<int>` to a [Uint8List].
///
/// Attempts to cast to a [Uint8List] first to avoid creating an unnecessary
/// copy.
extension AsUint8List on List<int> {
  Uint8List asUint8List() {
    final self = this; // Local variable to allow automatic type promotion.
    return (self is Uint8List) ? self : Uint8List.fromList(this);
  }
}
```

(I have a vague recollection that this has been suggested already, but so far I've been unable to find an existing issue.  Maybe it was on an internal Dart discussion list that I no longer have access to.)

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/issues/1397.

**Comment by jamesderlin** [comment]
I guess I'm blind. ;)
