### ISSUE TITLE
Control flow collection and endless loops

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#215]
Please see Control flow collection feature specification, [To evaluate a collection element](https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/feature-specification.md#to-evaluate-a-collection-element) section

> 4. Else, if element is a C-style for element:
> 
> Evaluate the initializer clause of the element, if there is one.
> 
> Loop:
> 
> Evaluate the condition expression to a value condition. If there is no condition expression, use true.
> 
> If the boolean conversion of condition is not true, exit the loop.
> 
> Evaluate the body element using this procedure in the scope of the variable declared by the initializer clause if there is one.
> 
> If there is an increment clause, execute it.

If there is no conditional expression how the loop will be stopped? We have no break clause in Control flow collection, so C-style for element without conditional expression will always produce an endless collection. Why it is allowed then?

**Comment by munificent** [comment]
Oh, that's a good question.

You're right that allowing it is not practically useful in any normal sense. It does give you a way to stuff an infinite loop that may produce useful side effects into a context where only an expression is expected. If anyone were to actually *do* that, though, I wouldn't describe the result as good code.

I'm OK with making the condition mandatory. Thoughts @leafpetersen and @lrhn? If you're OK with it, I can update the proposal and tests.

**Comment by leafpetersen** [comment]
Technically you can use a "throw" as a break from the loop.  Not sure if that's a feature though.  :)

You can still write infinite loops there, and it doesn't seem to me that leaving off a condition is something you're likely to do by accident, so I'm not sure I see much benefit to ruling this out, but I don't object to doing so either.

**Comment by munificent** [comment]
Let's just leave it as-is then. We've got enough work left around the iteration protocol stuff and this proposal needs to get done soon.

**Comment by lrhn** [comment]
Agree, let's keep this precisely the same as the statement loop.

We can then consider adding `break` in the future, if that makes sense.
```dart
List<T> listWhile<T>(Iterable<T> source, bool test(T value)) =>
    [ for (var v in source) if (test(v)) v else break ]
```
(aka. `source.takeWhile(test).toList()`).
