### ISSUE TITLE
Macros: should initializing formal parameters have a type?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2151]
Today in the CFE implementation you get `dynamic` for the type when looking at a constructor parameter which is an initializing formal parameter. Technically, there is no _hand written_ type there but there is an implicit type.

My initial gut feeling is we should just surface the implicit type - but that is a bit interesting when it comes to phase 1 (type phase) macros, which cannot typically see fields. I think this is probably fine - the compiler at this point _can_ see the field, and _should_ be able to surface the type.

If we don't do this it means in phase 1 you definitely can't even get to the type at all, even if you knew it was an initializing formal parameter. Quite often this also be the same case for phase 2. That means that delegating to super constructors (where I noticed this) gets difficult or maybe even impossible.

cc @johnniwinther @scheglov @munificent

**Comment by scheglov** [comment]
Is this different than any other implicit type, e.g. top-level variable `var x = 0;`? IIRC our approach here was that we return types only if explicitly written, because type inference is not (cannot) done yet.

**Comment by jakemac53** [comment]
> Is this different than any other implicit type, e.g. top-level variable `var x = 0;`? IIRC our approach here was that we return types only if explicitly written, because type inference is not (cannot) done yet.

It is different in that it doesn't require looking at bodies to do inference - the type is explicitly written, it's just on the field.

Not being able to see the inferred types of fields with initializers is unfortunate though... I had forgotten about that.

**Comment by jakemac53** [comment]
I am going to mark this as officially a duplicate of https://github.com/dart-lang/language/issues/2154, as I think we can use exactly the same solution.
