### ISSUE TITLE
Allow a generic type to extending multiple types 

### ISSUE THREAD

**Issue by avdosev** [dart-lang/language#2161]
I have a function like "foo":
```dart
void foo<T>(T arg) {
   if (arg is String) {
      // do for String
   } else if (arg is Iterable<String>) {
     // do for Iterable<String>
   } else {
      throw UnsupportedError('type:$T unsupported')
   }
}
```
I would like to make it safer at compile time.
Maybe like this (inspired by TypeScript):
```dart
void foo<T extends Iterable<String> | String>(T arg) {
  if (arg is String) {
      // do for String
   } else if (arg is Iterable<String>) {
     // do for Iterable<String>
   }
}
```
Or is there any other way to do this?

**Comment by lrhn** [comment]
That'd be union types (#1222), 

Even if it's only allowed for bounds of type parameters, it still introduces general union types into the file system (we currently have only nullable types and `FutureOr` as specialized union types).
