### ISSUE TITLE
Multiplication Prints Wrong Answer

### ISSUE THREAD

**Issue by bichanna** [dart-lang/language#2164]
I have this code:
```
void main() {
  print(0.56 * 100);
}
```
But it prints `56.00000000000001`.

So, I tried other numbers:
```
void main() {
  print(0.56 * 100);
  print(0.55 * 100);
  print(0.54 * 100);
  print(0.22 * 100);
  print(0.17 * 100);
}
// outputs:
// 56.00000000000001
// 55.00000000000001
// 54.0
// 53.0
// 22.0
// 17.0
```
Is this a kind of bug, or am I missing anything?

I'm using a MacBook Pro 1.4 GHz Quad-Core Intel Core i5.

**Comment by Levi-Lesches** [comment]
That's a natural result of representing floating-point decimal numbers in binary. It affects all computers and languages. A common example is `0.1 + 0.2 = 0.30000000000000004`. For more information, see https://0.30000000000000004.com
