### ISSUE TITLE
MediaQuery error

### ISSUE THREAD

**Issue by Ballu1811** [dart-lang/language#2174]
Can anyone tell me how to solve this error.
![image](https://user-images.githubusercontent.com/84559920/160791476-c1999e92-4786-454e-b836-05c7b556eece.png)

**Comment by ykmnkmi** [comment]
Add `late`. [Late variables](https://dart.dev/null-safety/understanding-null-safety#late-variables).

**Comment by Ballu1811** [comment]
yes I used this but then in the below line of code the error shows that you should use static variable if have to use it

**Comment by Levi-Lesches** [comment]
```dart
static late final MediaQueryData _mediaQueryData;
```

Follow that pattern
