### ISSUE TITLE
List.firstWhere optionally finding an element is verbose with try/catch

### ISSUE THREAD

**Issue by safield** [dart-lang/language#2176]
To optionally find an element within a list based on some predicate, the only current option is...

```
var optionalElement;
try {
   myList.firstWhere((element)=> element.id == someId);
} on StateError {}
```
Currently the orElse parameter to firstWhere is useless, because it only makes sense if a default value makes sense. If there is not reasonable default value, orElse is useless.

firstWhere should simply return a nullable type, which is null if not found.

**Comment by srawlins** [comment]
You can also use https://pub.dev/documentation/collection/latest/collection/IterableExtension/firstWhereOrNull.html

**Comment by safield** [comment]
That was literally exactly what I was looking for. Cool!

**Comment by munificent** [comment]
Did you intend to re-open?
