### ISSUE TITLE
Exhaustiveness checking on absent map keys

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2177]
The exhaustiveness proposal is currently pretty hand-wavey around maps. It hints that we could treat key accesses similar to other fields but that mapping doesn't directly work. This is not exhaustive:

```dart
Map<String, bool> x = ...;
switch (x) {
  case {'k': true}: ...
  case {'k': false}: ...
}
```

In fact, this isn't either:

```dart
Map<String, bool> x = ...;
switch (x) {
  case {'k': true}: ...
  case {'k': false}: ...
  case {'k': null}: ...
}
```

Instead, what you really need is:

```dart
Map<String, bool> x = ...;
switch (x) {
  case {'k': true}: ...
  case {'k': false}: ...
  case {}: // Matches when 'k' isn't present.
}
```

That's because the runtime semantics for map patterns rely on calling `containsKey()` and not just `operator []`. So there is an extra out-of-band bit of data that exhaustiveness checking needs to handle.

I think we can probably accommodate that by treating the lifted type of a map value as a union of the underlying value type and a special "key not present" sentinel type sort of like `null` for nullable types.

In order to match that type and remove that arm from the union, an extract space must *not* have that field present.

cc @stereotype441

**Comment by munificent** [comment]
> Does the pattern `{'k': true}` match maps with more than one key? I guess it must, otherwise the cases above wouldn't even be near exhaustive for maps.

Yes, according to the current proposal, map patterns don't have to cover all keys, unlike list patterns. There's no implicit length check. I could be persuaded to make map patterns check the length and require something like `...` to allow unmatched keys. I honestly don't recall why I made map patterns work differently from lists in this regard. (It's been a while since I wrote that corner of the design.)

> Then the pattern {} matches any map, so you could just as well write default: instead of case {}:. (We'd still want to support the latter, I guess.)

`default:` matches any *object*, while `{}` matches any *map*. The latter still only matches values of type `Map`.

> We could allow `{'k': null}` to match a map with no `k` key.

That feels pretty counter-intuitive to me in a null safe language like Dart.

> That is, for a nullable value type we would then _not_ distinguish between `k` being there with a `null` value and `k` not being there. If you need that distinction, you need to ... well, I don't know. There is no way to test that a key _isn't_ there, that would need completely new syntax, like `{!'k'}` (not great!).

This is maybe a good argument for requiring `...` in map patterns to ignore keys. Because then you can at least match a map that has *these keys and no others* (assuming the implementation of Map has reasonable behavior for `length` and `containsKey()`:

```dart
case {'x': _}: ...
```

Here, we could reasonably assume the matched value does *not* have key "k" since it must have length one and contain the key "x".

> There is no way to test that a key _isn't_ there, that would need completely new syntax, like `{!'k'}` (not great!).

Yeah, I think we can simply live without this. Patterns don't need to be able to express all possible predicates on objects, just most of the useful ones.

**Comment by stereotype441** [comment]
> > There is no way to test that a key _isn't_ there, that would need completely new syntax, like `{!'k'}` (not great!).
> 
> Yeah, I think we can simply live without this. Patterns don't need to be able to express all possible predicates on objects, just most of the useful ones.

Agreed, especially since we can always do:

```dart
switch (m) {
  case {'x': _}: ...
  case {}: ... // Matches the case where the key "x" is absent!
}
```

**Comment by TimWhiting** [comment]
> If we say that a pattern like `{'x': _}` _only_ matches maps of length 1, and you have to write `...` to allow unknown keys, I worry that people are going to leave out the `...` without thinking, and then later when they try to extend their JSON objects they're going to cause breakages, and they'll blame pattern matching for having a default behavior that's not permissive enough.

I think most json objects have more than one key. This would be an interesting metric to gather, but my gut feeling is that the `...` would be required for most json objects. I would prefer to have the behavior the same as lists, so there is no confusion on the difference between maps and lists. A lint rule to always have `...` for maps matchers with constant keys could help users remember that maps are a pretty extensible data-structure and likely not to have a finite number of entries.

**Comment by mateusfccp** [comment]
> On the other hand, I bet one of the most common use cases for destructuring maps is going to be for decoding JSON objects that represent structures. And a really nice thing about JSON objects that represent structures is that unless you go out of your way to count or otherwise enumerate the key/value pairs, your code will just gracefully ignore any unexpected keys. Which tends to make JSON objects extensible in a really natural way--at any point I can invent a new field and add it to a JSON representation, and _probably_ not have to modify any pre-existing code that deals with that structure. If we say that a pattern like `{'x': _}` _only_ matches maps of length 1, and you have to write `...` to allow unknown keys, I worry that people are going to leave out the `...` without thinking, and then later when they try to extend their JSON objects they're going to cause breakages, and they'll blame pattern matching for having a default behavior that's not permissive enough.

As long as I understand your worry regarding how practical this will be, do we want to make it impossible to match maps strictly? What if the user wants to know if their map has that exact the given structure an no more? Maybe he wants to map a `{'a': 'b'}` JSON to an `A` object and a `{'a': 'b', 'pretty': true}` to a `PrettyA` object. I really don't think we should make it impossible for one to match a strict map structure...

**Comment by rrousselGit** [comment]
What would be the purpose of pattern matching on maps if it ignores unknown keys?

I can't think of a use-case where the current proposal would be useful when we could use `map.containKey`/`putIfAbsent`/... directly


Strict matching, on the other hand, could be decently useful for decoding union types without a unique key.

Say we want to deserialize:

```
{ "name": string, "age": number? } | { "name": string, "author": string }
```

then we could possibly do:

```dart
Map json
return switch (json) {
  case { "name": is String, "age": is num? } => Person.fromJson(json);
  case { "name": is String, "author": is String } => Book.fromJson(json);
}
```

**Comment by munificent** [comment]
> As long as I understand your worry regarding how practical this will be, do we want to make it impossible to match maps strictly? What if the user wants to know if their map has that exact the given structure an no more?

You could do:

```dart
switch (map) {
  case {'a': var a, 'b': var b} if (map.length == 2): ...
}
```

Feels kind of hacky to check the length explicitly, but that's essentially what a "strict" check would be doing anyway. I think it's mostly a question of what the default behavior should be: should it default to not matching if there are extra keys or matching? I suspect the latter is what fits more use cases, but it's definitely something we should try to get data on before we decide for good.

> I can't think of a use-case where the current proposal would be useful when we could use `map.containKey`/`putIfAbsent`/... directly

I mean, you could say that about pattern matching in general. It doesn't let you express anything you can't already express imperatively. It's just a (much) nicer way to express it.

Think about it like this: Look at the code you have *already* where you call `containsKey()`. In that code, how often do you also verify that the map *doesn't* have any other keys? In my code, it's not that often. In that case, ignoring extra keys in map patterns would let my migrate to use pattern matching while preserving the current behavior.

If it turns out that most code *does* check for extra keys (or would prefer to if it's easy), then, yes, it might make sense to have the default be to not ignore them.

**Comment by rrousselGit** [comment]
> I mean, you could say that about pattern matching in general. It doesn't let you express anything you can't already express imperatively. It's just a (much) nicer way to express it.

While this is technically true, at the same time I don't think pattern matching applies to _everything_.

I don't think we should expect folks to rewrite every single line of code to use pattern-matching instead. I'd expect pattern matching on Maps to be very rare.  
The primary candidates for me at records/sealed-classes. 

To begin with, Maps are typically used with dynamic keys. So writing:

```dart
Map<String, bool> x = ...;
switch (x) {
  case {'k': true}: ...
  case {'k': false}: ...
}
```

IMO has little value, because the key is a constant. The Map likely should be converted into a Record/Class instead, such that we do:

```dart
Class x = Class.fromJson(map)
switch (x) {
  case Class(k: true): ...
  case Class(k: false): ...
}
```


The only use-case I can think of for writing `case {'key': value}` is object deserialization. But even then, it's not clear to me that this is useful.  
Typical JSON decoding would likely not use pattern matching (and would be code-generated on top of that). One exception may be tagged union decoding:

```dart
switch (x) {
  case {'type': 'notification', } => Notification.fromJson(x);
  case {'type': 'book'} => Book.fromJson(x);
  default: ...
}
```

But at the same type, we can directly do:

```dart
switch (x['type']) {
  case 'notification' => Notification.fromJson(x);
  case 'book' => Book.fromJson(x);
  default: ...
}
```

So the only valid use-case I can think of is untagged unions (cf https://github.com/dart-lang/language/issues/2177#issuecomment-1085749229) – which would rely on strict matching

**Comment by munificent** [comment]
> I don't think we should expect folks to rewrite every single line of code to use pattern-matching instead. I'd expect pattern matching on Maps to be very rare.
> The primary candidates for me at records/sealed-classes.

People write lots of different kinds of code in Dart. Maps are certainly commonly used, even outside of serialization, and I expect that some reasonable fraction of map element accesses could be converted to use pattern matching. It may be that it's not a corner of the feature that's particularly relevant for the kind of code you write, but my goal is to make a feature that's useful for all Dart users and all kinds of code.

**Comment by rrousselGit** [comment]
That's not my point

I'm not saying "don't implement map pattern matching".
But to answer the question asked by this issue, understanding the use cases is important.

We're trying to figure out the default behavior. If most use-cases use strict matching, then I think the default should use strict matching.

**Comment by munificent** [comment]
I've updated the proposal to make map patterns check the length. This makes them default to being "strict", and I intend to add support for `...` syntax to disable that. This is consistent with list patterns, so I think it's the right default starting point for the proposal.

But I'm going to leave this issue open because I think it's still worth discussing what the right default is.

**Comment by munificent** [comment]
OK, closing this. Map patterns now default to strict like lists, and there is a `...` you can use to opt into looser length checks.
