### ISSUE TITLE
On the possible use of 'views' 

### ISSUE THREAD

**Issue by drpond1** [dart-lang/language#2180]
At the end of closed Issue dart-lang/sdk#48686,  [eernstg]  gives a brief description of a possible extension of adding views to DART.     This "issue" is really just a comment on what is being considered.  

What is being considered would provide the features I was specifically looking for in the example I was building.    I  like the idea of
being able to specify a  kind of JSON encoding schema and having mostly automated code generation for examining the result with the appropriate types.

 I can't really tell how well this will work in general, as I just don't have enough experience in the kinds of schema constraints that  might typically arise. 
  Perhaps you have already considered
what it would be like to use a JSON validating parser in DART that
translated a JSON encoding  with a schema into an "appropriate" typed DART object with views.     In this case,  the encoder might simply be able to infer the "appropriate" types from the schema without having to use views.  

When dealing with XML schemas it is sometimes difficult to quickly understand what is being required.  In early versions of the language called
musicXML (used for specifying musical scores),  it was often difficult to 
tell what was allowed.  In the latest version,  they have a natural language description of what is allowed with hyperlinks for the various parts.
A complex example is:   https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/note/
      There might be some capability to automatically generate a partial natural language description of the JSON schema.   To what extent this meshes with DART document generation I don't know.

**Comment by eernstg** [comment]
> optimally typed is not as simple as it might sound

That was exactly one of my points. ;-)

**Comment by drpond1** [comment]
The only cases that that I use something like what you are doing are for things that are "like" serialization from/to JSON.   If I needed to,  I could use json_serializable.    It has a simple way to handle missing keys.    
  But for what I have done so far,
I am only serializing a couple of structurally simple items and the manual method works fine.  

However,  I am interested in you work.  I would be interested in hearing about any use cases where the approach seems like it could be useful.

**Comment by eernstg** [comment]
@drpond1, I'll close this issue because it's not really reporting on anything directly actionable. You're of course welcome to create new issues as needed, or commenting on existing ones!
