### ISSUE TITLE
Assignability and pattern matching

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2184]
Dart has implicit coercions at assignment in some cases, meaning that some types are *assignable* to another type without being a subtype.
Currently that includes:
* `dynamic` being assignable to any type (implicit downcast).
* Callable objects being assignable to a function type (implicit `call` tear-off).
* Generic function types being assignable to non-generic function types (implicit instantiation).
* Generic callable objects being assignable to non-generic function types (implicit instantiated `call` tear-off).

If `A` is assignable to `B`, but `A` is not a subtype of `B`, will a *pattern match* which expects a `B` allow an `A` and introduce the implicit coercion?

Examples:
```dart
var [int a, int b] = somethingDynamic; // implicit `as List<int>`?

class C {
  int call<T>(List<T> x) {...}
}

var (int Function<T>(List<T>) f, int x) = (C(), 42); // implicit `.call`?

var (int Function(List<int>) f, int x) = (C().call, 42); // implicit `<int>`?

var (int Function(List<int>) f, int x) = (C(), 42); // implicit `.call<int>`?
```
Also,
```dart
var (double x, int y) = (1, 1);  // implicit `.0` on the first `1`?
```

(If views introduce more assignabilities, we'd have to consider those too).

Very likely this will just work, as long as the patterns introduce suitable *context types*, and we let implicit coercions always be driven by context type.

**Comment by eernstg** [comment]
I think this is just one more reason why we'd _want_ to have simple and general rules about where/how to apply coercions. ;-)

**Comment by munificent** [comment]
Yes, I think so. The proposal already [describes how a context type schema is derived for patterns](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#pattern-context-type-schema) and then how that is pushed over to the value expression. That section needs some work, but I think the basic idea is there.

**Comment by munificent** [comment]
Closing this because, as far as I know, the proposal covers this by using assignability between pattern types and matched value types, and defining a context type for the matched value. Feel free to re-open if there are corners I missed (which definitely wouldn't surprise me).
