### ISSUE TITLE
Macro bootstrap script expects zero argument constructor

### ISSUE THREAD

**Issue by TimWhiting** [dart-lang/language#2189]
@jakemac53 I was experimenting with the macro example on the language repo and ran into an error in the bootstrap script assigning to this map. It seems that there is some support for macro arguments maybe(?), but this made it so I could not experiment with them.
`Macro Function()` --> `Function` is probably how it has to change.
https://github.com/dart-lang/sdk/blob/6d543de174a229597184ee2404b7d53e328d731c/pkg/_fe_analyzer_shared/lib/src/macros/bootstrap.dart#L173

**Comment by jakemac53** [comment]
I went ahead and moved this to the language repo, as that is where everything is currently tracked. Although this is more of an implementation thing and the change will be in the SDK. So we could create a label there or something? But it might be easier to keep everything in the language repo.

**Comment by devoncarew** [comment]
Yeah, I think once we start productionizing things, we'll probably want an `area-macros` label in the sdk repo.

**Comment by jakemac53** [comment]
That sounds good to me

**Comment by jakemac53** [comment]
This should be fixed by https://dart-review.googlesource.com/c/sdk/+/240420

**Comment by jakemac53** [comment]
(but note that the CFE still doesn't support it)
