### ISSUE TITLE
Proposal: null-elimination operator - prefix "?"

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#219]
This proposal is based on ideas from several commentators from [this thread](https://github.com/dart-lang/language/issues/141). (In other words, I don't pretend these ideas are mine) :-)

Proposal: implement null-elimination operator ?expr to drop value of null, in contexts where such operation makes sense.
Examples:

* passing optional named parameters: suppose we have `foo({int x=0})`. Then the call
`foo(x: ?expr)` is equivalent to calling `foo()` if expr evaluates to null, and to foo(x: expr) otherwise 
* passing (last) optional positional parameter: suppose we have `foo([int x=0])` - then the call `foo(?expr)` is equivalent to `foo()` if expr evaluates to null, and to `foo(expr)` otherwise  (only valid for the last such parameter. I'm not sure this makes sense though - to be discussed).
* in map literals, e.g. `{ "key": ?expr }` is {} if expr evaluates to null, and `{"key": expr}` otherwise
* similarly in list literals.

Advantages:
 - allows to use full power of null-chaining null-safety features in expressions like `[ 1, 2, ?(a?.b?.c) ]`
 - solves the problem of dropping parameters while calling methods with optional parameters (improves null-safety, requires the callee to "sign" its part of non-nullability contract)

Precedents:
In a rudimentary form, we already have a device similar to null-elimination operator - with spread collections, we can write: `[ ...?list]` - when "list" is null, nothing gets inserted. The proposal is consistent with this feature and takes it just one step further: if elimination makes sense for the list, it seems logical that it should make sense for a single value, too.
 
Extra: a bit more controversial use case - in "if" statement, e.g.
`if (?x) {...}` - same as `if (x != null)`
`if (var x = ?(a?.b?.c)) { ... }` - like "let" in swift, but no new keyword is necessary, "var" works fine

**Comment by ds84182** [comment]
Still sorta on the fence when it comes to the syntax. Maybe an `if` keyword instead? `foo(x: if expr)`, `{"key": if expr}`, `yield if expr`, `return if expr`?

**Comment by andreashaese** [comment]
Maybe the syntax to express this is already there: I'm thinking of `? :`, `??`, and `_`:
```dart
a > 3 ? a : _ // only a if it's greater than 3
a ?? _ // only a if it's not null
```
I'm not aware of other languages that do this, so take that with a grain of salt. Also note that `_` currently can't be used this way, because to date `_` is a readable variable. Along with proposals like #204 this could change at some point though.

**Comment by tatumizer** [comment]
@andreashaese :
> Maybe the syntax to express this is already there

This was discussed in [the thread](https://github.com/dart-lang/language/issues/141) and was found problematic, because it introduced the concept of Nothing, which was unnecessary for the task. The question mark achieves effectively the same without ever mentioning Nothing. Some words are better when unspoken :)

@ds84182: 
> Still sorta on the fence when it comes to the syntax. Maybe an `if` keyword instead?

3 arguments against it:
- dart so far was not in love with the notions of thruthy / falsy values, and it would (arguably) be better to keep it that way.
- on the other hand, question mark is consistently used in dart in a context of nulls, and proposed ?expr notation just takes advantage of this association.
- "if" in dart already has at least 3 inconsistent forms; adding yet another one would be a bit grotesque
(though if you ask me, we are already there) :)

I think your first intuition (when you proposed ?) was good! :)

**Comment by ds84182** [comment]
@tatumizer My issue with the syntax is that it feels a question mark feels odd in a prefix position. I'd like it more if the question mark was against an another operator (e.g. a suffix to `:` and `yield`).

**Comment by tatumizer** [comment]
@ds84182 : if it's just a suffix to : or yield , then we don't have as much power from this feature - it can't be used in list literals or other potential cases where you simply don't have "another operator" to attach it to as a suffix.

It's easy to get used to it in prefix position. Initially, every new feature looks odd (e.g. ++x in C if you've never seen it before). I find this "prefix ?" a fascinating idea, I bet other languages will start copying it right away :). And it's not controversial at all, because if you use it wrongly, compiler will detect an error (e.g. if you try to say `var x =?5 + 7` - you get an error). The priority of "?" operator should be low enough for that (TBD)

**Comment by tatumizer** [comment]
> It is annoying that positional parameters can't be handled better

On second thought, null-elimination operator might be exactly the way to handle them better. For optional positional parameters, we can just agree that when "?null" means skipping this parameter and going to the next one.
E.g. if we define `f(a, [b=1, c=2])` we can call it as `f(0, ?null, 10)`. In order to avoid an awkward expression `?null`, we can allow just '?', which leads to `f(0, ?, 10)`

**Comment by andreashaese** [comment]
May I cite your previous comment? :)

> The question mark achieves effectively the same without ever mentioning Nothing.

**Comment by tatumizer** [comment]
@andreashaese : Indeed `?null` means Nothing **essentially**, but not literally. If we had a first-class notion of Nothing, then the following expression would be valid:
```
var x = [ cond? 42 : Nothing ]
```
it would achieve the same, but would pose difficult questions like "what is the type of Nothing"? "What operations are allowed on Nothing"? "Can we compare a value with Nothing?" etc. Very difficult questions that can be avoided altogether with operator ?expr.

By design, we allow ?expr only in limited number of contexts, as a sugar to "if (expr != null) expr else skip"
where skip is a verb, not a noun. Naturally, it applies only where the notion of "skip" makes sense. 
If you see it as a problem, then it's the same problem as in current proposal of if-element:
```
var list = [ if (cond) 42 ];
```
I can ask the same question: don't we have an implicit notion of "Nothing" here if the condition is false? :-)

**Comment by andreashaese** [comment]
Yes, that's exactly my concern. The concept of "Nothing" is already hidden in plain sight: `if (false) 42` and `?null` both are "Nothing literals".

With that said, "Nothing" is no data type. It's purely syntactical sugar, as you wrote. As such, it shouldn't be confused with the Optional type, or used in situations where the latter makes more sense.

**Comment by tatumizer** [comment]
@andreashaese : I don't think there can be much of confusion. The situation is exactly the same as with number zero. For various philosophical reasons, the notion of zero was frowned upon for a couple thousands years. The notion was finally accepted [around year 1600](https://www.livescience.com/27853-who-invented-zero.html). "Nothing" is a logically necessary concept: whenever you throw it out the door, it comes back through the window. :)

As for "if (cond) 42" - I think null-elimination is a more powerful concept - it has a concise expression, looks more like an operator, can be used in more contexts - e.g.  `yield ?x` looks perfectly fine to me, whereas `yield if (x!=null) x` would be totally weird, no?

**Comment by andreashaese** [comment]
> "Nothing" is a logically necessary concept: whenever you throw it out the door, it comes back through the window.

Sure, but that's an argument for `null` and the Optional type, not for "null/expression elimination".

Being able to conditionally ignore expressions would be a pure convenience feature, to make your code shorter. That's tempting in cases where it's super obvious what's happening, but I'm concerned that things like `foo(bar: ?x)` and `yield ?x` actually make your code _less_ clear, no matter the syntax.

In my opinion, many of the (valid) pain points could better be remedied with Optionals. And sometimes, a good ol' `if` is just the right tool.

**Comment by tatumizer** [comment]
I dunno. There's some charm in this operator. At first, every new feature looks a bit weird, but people get used to it and then love it. Optional chaining (\*) and other operators like '??', '??=' also need getting used to.

(\*) Patented! [See here](https://forums.swift.org/t/apple-is-indeed-patenting-swift-features/19779). Dart can counter it by patenting null-elimination, before it's too late :)

**Comment by tatumizer** [comment]
Another use case:
`int x = ?;` instead of disgusting Kotlin's "lateinit int x;`
How about *that*?

**Comment by lrhn** [comment]
It's a common theme that some expression should only be evaluated to completion if some sub-expression is non-null.

The `x?.foo` case is simple because `x` is the first expression to evaluate here.
We could also do the same for function invocations: `foo(?arg)` where it only calls the function if `arg` is non-null. The tricky case here is to delimit the expression that is short-circuited on `null`. Just shorting the entire surrounding expression is probably not useful, but eliding too little is also a problem.
Just eliding up to the nearest nullable type context would be too unpredictable.

Imagine an expression of the form `(?? any-expression(?subexpresssion))` where the entire surrounding `(??...)` expression evaluates to `null` if any `(?...)` subexpression does.
Then `a =?? b` (from #288) would be `(?? a = ?b)` and `foo(?a)` would be `(??foo(?a))`.

It's nigh unreadable, though. :)

**Comment by eernstg** [comment]
I'm a little bit worried about having a large construct and then making that construct mean something very different (namely `null`) in case there is something in the middle which happens to be absent.

```dart
var mySet = {
  canvas.drawParagraph(
      (ui.ParagraphBuilder(
        ui.ParagraphStyle(textDirection: ui.TextDirection.ltr),
      )..addText('Hello, world.'))
          .build()
            ..layout(ui.ParagraphConstraints(width: logicalSize.width)),
      ui.Offset(...)),
  ui.window.render((ui.SceneBuilder()
        ..pushClipRect(physicalBounds)
        ..addPicture(ui.Offset.zero, ?picture)
        ..pop())
      .build()),
}
```

So do we want that whole thing to happen if and only if that `picture` is not null? It may be tempting to allow such embedded `?` expressions to control a larger and larger enclosing expression, because that makes this mechanism "more and more powerful", but I think it's dangerous with respect to the overall readability of the code.

I don't think anyone went so far here, but it's still worth considering a mechanism where the ability to call it off is consistently forced up front:

```dart
var mySet = let ?v = picture in {
  canvas.drawParagraph(
      (ui.ParagraphBuilder(
        ui.ParagraphStyle(textDirection: ui.TextDirection.ltr),
      )..addText('Hello, world.'))
          .build()
            ..layout(ui.ParagraphConstraints(width: logicalSize.width)),
      ui.Offset(...)),
  ui.window.render((ui.SceneBuilder()
        ..pushClipRect(physicalBounds)
        ..addPicture(ui.Offset.zero, v)
        ..pop())
      .build()),
}
```

Of course, it might be far to alien to use `let` in Dart, but the main idea is that we can mark the whole construct as "omission-prone" by using `?v` in the declaration of some (final) variables up front. The reader would then know that the whole thing is just null if any of the `?v` variables end up being null, and it is executed if they are all non-null.

**Comment by tatumizer** [comment]
The original motivation for `?expr` operator was: to find a simpler/less confusing alternative to if-element.
I was thinking also about the possibility of `a = ?b` and found it confusing. So IMO, `?expr` would be good only in a limited number of contexts - in list/map literals; while passing optional value to a method ("I don't pass anything, use the default, whatever it is") and *maybe* (I'm less sure) in `yield ?expr`.

Now that dart has chosen if-element anyway  - which I personally don't like, but the feature is already a (regrettable) *fait accompli* - I realize that the justification for the `?expr` feature is not that strong.  Though the case of passing optional parameter remains. I know dart is planning to use pure null in the same sense, but I find the idea controversial; explicit "ignore if null" would be preferable IMO. 

But the thing is: if we introduce `?expr` only in *that* meaning, then the next question would be: why *only* in that context? Why not use it in the literals, too? I don't know how to answer that question, and where to draw a line.

**Comment by eernstg** [comment]
> Calling function `f(?arg)` only when `arg != null`? No, I never meant that! :)

Sorry about over-interpreting! That was exactly the kind of semantics that we've had proposals for on earlier occasions.

**Comment by lrhn** [comment]
If we consider *only* the collection element case, and only the "element computation is null" case, then it might work. Say we use "suffix `??`" as marker (a `??` with *nothing* after it, which we only make syntactically valid after a collection element):
```dart
 var x = [1, 2, computation() ??, 4];
```
That could work. The problem is that it only works for single elements, not for map entries. We cannot do `{x: y ??}` because it's not clear whether it's `x` or `y` or both being tested. We'd probably have to allow for `{x??: y, z: w??}` where you test each part and omit the entirety if one is null (left join/right join?).

It's not a good ortogonal feature, but it mirrors the nullability of `...` vs `...?`. (Which is probably also why prefix `?` feels more right to me).

**Comment by tatumizer** [comment]
@lrhn: if prefix `?` feels more right to you, ... sorry, then I don't understand how suffix `??` even came up here in the first place. I was under the illusion that were've been talking about prefix `?` all along! :-)
I can't see the problem in `{?x: y}` - clearly, the prefix applies to the expression that follows, and `x: y`, as a whole, is not an expression. `{?x: y}`, `{x: ?y}`, `{?x : ?y}` all mean different things: "exclude the item if the key is null", "exclude the item if the value is null",  "exclude the item if either in null".

**Comment by lrhn** [comment]
Ah, the "suffix `??`" was something I discussed with someone somewhere, so it was in my head while writing this. 
It makes a kind of sense to have an element `??` condition with no `else` branch, like we do for `if`-elements, so it would be consistent ... in some ways. Just not particularly readable, or generalizable.

**Comment by tatumizer** [comment]
Upon sleeping on the issue a bit longer (2 years or so), I got disappointed in the idea of null-elimination and don't like it as much as I used to. We need a general syntax of conditional parameter-passing, not just null-elimination.
Maybe we can consider another approach discussed earlier: introduce an *operator* `default`, which can be used in 2 forms of conditional expressions while evaluating an (optional) parameter.
```
foo(1, test ? 2 : default);
foo(1, nullableVar ?? default);
```
The action of the operator is: break the evaluation of the expression and act as if the parameter was not passed at all. 

(The operator `default` is valid only in a specific context of optional parameter passing. We have precedents of contextual constructs, so it's not something new).

**Comment by nxcco** [comment]
Is there any progress on this?

**Comment by Levi-Lesches** [comment]
I personally vote for `value ?? default`, it reads more naturally: "pass this value, but if it's null use the default value instead".

**Comment by leoshusar** [comment]
This would be useful for late final variables if you sometimes don't need to inizialize them right in the constructor initializer.
Something like this:
```dart
class Something {
  late final String _text;

  class({String? text})
    : _text = ?text; // if text is null, _text won't get assigned anything and can still be assigned later
}
```

**Comment by sudha-anecure** [comment]
I see this has been closed as "completed". Was this implemented? Can someone please send me a reference to how we can achieve this?
