### ISSUE TITLE
Unexpected type inference result involving Closures.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#2192]
This issue is about an unexpected type inference result where calling a Closure in a direct and an indirect way leads to two different types.

Consider the following example:

```dart
Foo<Object> Function() bar = (){
  if (arbitraryBoolean) {
    return FooA();
  } else {
    return FooB();
  }
};

Foo<Object> baz = bar();

// Fails with:
// A value of type 'Object' can't be assigned to a variable of type 'Foo<Object>'.
Foo<Object> qux = (){
  if (arbitraryBoolean) {
    return FooA();
  } else {
    return FooB();
  }
}();

abstract class Foo<R> {}

class FooA implements Foo<String> {}

class FooB implements Foo<num> {}

final arbitraryBoolean = false;
```

It is not clear to me why `bar` and `baz` succeed, but `qux` fails.

My expectation was that `qux` would not fail i.e. that its initializing expression would be assignable to a variable of type `Foo<Object>`.

**Comment by modulovalue** [comment]
Thank you @eernstg for the detailed response.

> It's never invoking itself recursively (which was good because Java and other languages had termination problems with their least upper bound algorithms)

Would it be possible to limit the depth of the recursion by having N separate type inference algorithms for each level and with the last level missing all recursion?

in pseudo Prolog:
```prolog
up0(dartType(X, TL), dartType(Y, TR)) :- other_rules(X, Y), up1(TL, TR).
up1(dartType(X, TL), dartType(Y, TR)) :- other_rules(X, Y), up2(TL, TR).
up2(dartType(X, _), dartType(Y, _)) :- other_rules(X, Y).
```

**Comment by eernstg** [comment]
> Would it be possible to limit the depth of the recursion

Certainly, but the problem was that it was a breaking change. Type inference involving least upper bounds occur in so many places, with no visible syntactic marker, and that makes it hard to manage the migration.

**Comment by eernstg** [comment]
Ah, I forgot to close the issue. @modulovalue, this doesn't prevent further comments here, but it's still better to have discussions about this particular sub-optimal behavior of least upper bound computations in #176.
