### ISSUE TITLE
Patterns: extractor examples use invalid positional destructuring?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#2193]
I think the extractor examples are wrong: either they need to use named destructuring, or the extracted classes need to implement positional destructuring.  For example, I think the corrected `Rect` example should look like:

```dart
class Rect implements Destructure2<double, double> {
  final double width, height;
  double get field0 => width;
  double get field1 => height;
  Rect(this.width, this.height);
}

display(Object obj) {
  switch (obj) {
    case Rect(var width, var height):
      print('Rect $width x $height');
    case _:
      print(obj);
  }
}
```

and similarly for the enum example?

cc @munificent

**Comment by munificent** [comment]
Thanks! Good catch.
