### ISSUE TITLE
I am declaring private variable and function by creating a stateless class, but when I used function in body the function is showing error

### ISSUE THREAD

**Issue by Ballu1811** [dart-lang/language#2195]
[I am declaring private variable and function by creating a stateless class, but when I used function in body the function is showing error]

![image](https://user-images.githubusercontent.com/84559920/162427188-a21e93f8-546b-49f5-9bd2-96bb7f84c869.png)

**Comment by eernstg** [comment]
Looking at [`GestureDetector`](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html#:~:text=GestureDetector%20class%20Null%20safety,child%20for%20its%20sizing%20behavior.), the type of the named parameter `onTap` is `void Function()?`, but the type of `_handler` is `Function?`, which is a proper supertype of `void Function()?`, so you'll have a compile-time error unless you add an explicit downcast (`_handler as void Function()`). You probably just want to declare `_handler` with the type `void Function()?` in the first place.

Note that the type `Function` is a kind of "`dynamic` for functions": It causes arbitrary invocations to be accepted at compile time, and checked at run time; e.g., with a variable `f` of type `Function` you can have `int i = f();` and `String s = f(whatever: 1);` and `f('a', 'b', 'c')` without compile-time errors, but it is not possible to declare a function which would actually perform all of those invocations without error. So you should only use the type `Function` if you want to use `dynamic`, but you also want to ensure that the object _is_ some kind of function. In contrast, a function type like `void Function()` gives rise to static checks on the actual arguments as well as the returned type, and `g(1)` as well as `int i = g();` will give rise to compile-time errors if `g` has that type.

**Comment by eernstg** [comment]
I'll close this issue because it does not report anything that needs to change.
