### ISSUE TITLE
generalized-void.md confusingly mentions evaluation during static analysys

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/language#22]
"It is a compile-time error to evaluate an expression of type void, except for the following situations:"

We don't normally evaluate expressions at compile-time.  It's not even decidable if they will be evaluated.  In fact, it's just a compile time error for there to even be such an expression, right?

**Comment by leafpetersen** [comment]
I think the intention of this wording is more along the lines of "use" or "reference" than "evaluate".  cc @eernstg

**Comment by eernstg** [comment]
Said wording was not used when generalized-void.md was integrated into dartLangSpec.tex, and generalized-void.md is now a background-only document.
