### ISSUE TITLE
Implicitly cast non-nullable "`dynamic`".

### ISSUE THREAD

**Issue by SuporteSysrs01** [dart-lang/language#2201]
In my application, I use a _LOT_ of JSON (`Map<String, dynamic>`) types.

After migrating to null safety, my biggest issue is the analyzer not telling me that accessing that map could return `null`. Sure, changing it to `Map<String, Object?>` works, and it warns me about it potentially being `null`, but now I have to explicitly cast _every. single. time._ I try to access a value from it. Which makes me choose between "Do I want to have 20 casts in the following block or do I not want null safety?".

I can't understand why disabling type checking also has to disable null checking, having `dynamic` and `dynamic?` would solve all the issues I have with null safety, as it would warn me about it potentially being null but also implicitly casting if it isn't.

_Originally posted by @SuporteSysrs01 in https://github.com/dart-lang/language/issues/1022#issuecomment-1099199832_

**Comment by SuporteSysrs01** [comment]
More info in my other comment:

https://github.com/dart-lang/language/issues/1022#issuecomment-1099422249

**Comment by mnordine** [comment]
@SuporteSysrs01 what does your `analysis_options.yaml` file look like?

**Comment by SuporteSysrs01** [comment]
> @SuporteSysrs01 what does your `analysis_options.yaml` file look like?

It's the default Flutter generates, just the lints. There is no analyzer options or anything.
I've tried adding `implicit-casts: false`, but that just makes dynamics behave basically like a `Object?`.

I do want the implicit casts `dynamic` gives me, but I would like a warning when it is implicitly casting to a non-nullable.

**Comment by mateusfccp** [comment]
The right thing to do is not to cast the value, but to check it and promote. For example.

```dart
final data = await http.get<Map<String, Object?>>(...);
final person = data['person'];

if (person is Map<String, Object?>) {
  final name = person['name'];
  if (name is String) {
    doSomethingWithName(name);
  }
}
```

**Comment by SuporteSysrs01** [comment]
> The right thing to do is not to cast the value, but to check it and promote.

I know this is the most safe approach, but it becomes impractical in my use case, see https://github.com/dart-lang/language/issues/1022#issuecomment-1099422249

![image](https://user-images.githubusercontent.com/87761804/163454262-70a1d016-62b3-4905-bf0d-acbe51bfcaa6.png)

Having to check each variable (or even just casting it) adds tons of boilerplate code that I would rather just not have. Having it just warn me about it potentially being null would the best solution for my use case.

**Comment by SuporteSysrs01** [comment]
I'm closing this in favor of the solution proposed by https://github.com/dart-lang/language/issues/1022#issuecomment-1099436839 and the current on-going experimental lint referenced in the dart-lang/linter#2828 issue.

Current solution is disabling implicit-cast and implementing the following `Map` extension:

```dart
extension<Key, Value> on Map<Key, Value> {
  R? getCast<R>(Key key) => this[key] as R?;
}
```
