### ISSUE TITLE
`FunctionTypeAnnotation`s should not require names for parameters, but do today

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2208]
Today the `ParameterDeclaration` class requires a name (it extends from `Declaration`). This type is then used in the `FunctionTypeAnnotation` class to represent the parameters, but in that context they don't require a name.

The name is also an `Identifier`, which probably doesn't make sense in the context of a function type either, it isn't anything you can reference afaik.

## Proposal

Make a new class `Parameter` which does not extend from `Declaration`, and has all the fields that `ParameterDeclaration` has. The `ParameterDeclaration` class would now implement both `Declaration` and `Parameter`. And we would add an additional class `FunctionTypeParameter` which would implement `Parameter`, and also have a `String? get name` field, instead of the `Identifier get name` field on `Declaration`.

cc @scheglov @johnniwinther

**Comment by scheglov** [comment]
Another alternative design could be to have separate `FunctionTypePositionalParameter` with `String? get name` and `FunctionTypeNamedParameter` with `String get name`. And then we would not need `isNamed`. Currently we imply that `isNamed` means also that `get name` return non-nullable `String`. But with types we could prove it.

**Comment by jakemac53** [comment]
True, I worry a bit that it doesn't map very directly to `ParameterDeclaration` which does not have that distinction. But I could also create `NamedParameterDeclaration` and drop `isNamed` from that api?

**Comment by scheglov** [comment]
Yes, in my opinion `NamedParameterDeclaration` also would be nice, and consistency as well.

In the analyzer it might be slightly less convenient though, because we have another layer of options - default parameters, field formal parameters, super formal parameters, all of which can be [required, optional] * [positional, named].

**Comment by scheglov** [comment]
Sounds good.
