### ISSUE TITLE
Better static type checking of potentially constant expressions.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2209]
When we did the 2018 constants update, we made a choice to not make "potentially constant expression" depend on the type of the expression. That was to allow the parser to determine "potentially constant expression" without needing to rely on later phases of the compiler.
That was a mistake.

That now means that there is no static warning for code like:
```dart
class C {
  final List<int> ints;
  const C(this.ints) : assert(ints.length > 0);
}
```
This code is guaranteed to throw if the constructor is ever invoked with `const`, because `ints.length` is invalid as a constant expression (we only allow `.length` on a constant string, not on a constant list).

I've seen code doing this *in production*. Apparently it just never used `const` with the constructor.

We should reintroduce compile-time errors for potentially constant code which can't run as actually constant code.
That includes:
* `e.length` if the type of `e` is not assignable to `String` (so `String`, `dynamic` or `Never`, and probably not `Never` in practice).
* `e1 + e2` if the type of `e1` is not assignable to `num` or `String`. Same for `*`.
* `e1 | e2`, `e1 & e2`, `e1 ^ e2` if the type of `e1` is not assignable to `int` or `bool`.
* `e1 - e2` if the type of `e` is not assignable to `num`. Same for all the remaining number operators, including prefix `~e` and `-e`.
* `"${e}"` if the type of `e` is not assignable to one of `String`, `num`, `bool`, or `Null`.
* `e1 == e2` if the type of `e` is not assignable to one of `String`, `num`, `bool` or `Null` and the type of `e2` is not assignable to `Null`.

At least that would prevent some invalid code that currently has no warning at all.

**Comment by eernstg** [comment]
Sounds good! Cf. the very similar https://github.com/dart-lang/language/issues/1296.

**Comment by lrhn** [comment]
So, duplicate. (Why is GitHub search so hard to use :blush:).
