### ISSUE TITLE
Override the built-in class will broken the syntax-lint.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [dart-lang/language#221]
Redirect from: [When a field type is a class named `Locale`, the intellisense tips would got wrong. ](https://github.com/flutter/flutter/issues/27428#issuecomment-462646773)

**Comment by munificent** [comment]
Hi, sorry to keep bouncing you around, but I think this is probably not the right repo either.

I think there is a bug in the static analysis. It should not be inferring `dynamic` for a variable whose type is explicitly annotated `Locale`, even if there are two classes with that name. It should either know unambiguously which name you're referring to and use that type, or it should report an ambiguous name error.

I filed an issue here for you: https://github.com/dart-lang/sdk/issues/35938
