### ISSUE TITLE
Unexpected `Unnecessary cast` warning for `List<T>` generic inference.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [dart-lang/language#222]
Consider this case:
``` dart
var list = Iterable.generate(10).map((i) => 0 as Comparable).toList()
  ..addAll([1.0]);
```

Here we would got an `Unnecessary cast` warning:
![image](https://user-images.githubusercontent.com/12682063/52704746-4042fd80-2fbc-11e9-8965-2839a0dd553d.png)

However, if we remove the `as Comparable` cast, then the compiling would failed because `Dart` think `Iterable.generate(10).map((i) => 0).toList()` is typed `List<int>` insteadof `List<num>`.
![image](https://user-images.githubusercontent.com/12682063/52704838-72ecf600-2fbc-11e9-98a7-c39c45e03f6b.png)

Maybe we should improved the syntax-lint to recognize this case and not throw the warning? Or maybe the `List<T extends S>` could auto-downgrade to `List<S>` while we try to add an S into it?

**Comment by vanesyan** [comment]
The problem with your code is that `Iterable.map` is a generic method and you call it without explicitly provide type, so type inference take a place and `int` was taken as a prime type because of the fact that 0 is of type `int`

```
void main() {
  print(0.runtimeType); // int
}
```

If you explicitly provide `num` to `Iterable.map` everything should work as expected:
```dart
void main() {
    var list = Iterable.generate(10).map<num>((i) => 0).toList()..addAll([1.0]);

    print(list);
}
```

**Comment by zhengxiaoyao0716** [comment]
@vanesyan Thanks! I'm sorry that I only tried `list.<T>toMap` like what I ever do in Java, so I mistooked that it was not support in Dart. ╮(╯3╰)╭
