### ISSUE TITLE
[Macros] "A macro should be a pure function from input code to resulting code."

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#2238]
Quote from the [macro specification](https://github.com/dart-lang/language/blob/master/working/macros/feature-specification.md)

> A macro should be a pure function from input code to resulting code.

I agree with this statement however the current proposal makes that impossible.

Any given function `m` _(e.g. a macro)_ that is allowed to call a function `f` _(e.g. [declareType](https://github.com/dart-lang/sdk/blob/07aeba22865a40d12ccbb8c286eda9aad1232ffe/pkg/_fe_analyzer_shared/lib/src/macros/api/builders.dart#L32))_ where `f` returns a value of type `Unit` (_e.g. void in Dart_) is only pure if all `f` produce no sideffects. Some of the possible `f` have to have sideeffects for `m` to be useful so macros can provably not be pure. All the properties that come from having purity do not apply to macros.

This is a problem that the functional programming community has struggled with for decades until Monads were discovered as a solution that allowed functional programmers to do effectful computations without loosing purity.

The need for Monads to stay pure can be relaxed here. A simpler solution to this problem in the context of Dart would be to instead of providing functions that users have to call to add declarations, to expose a declarative DSL where the macro output is described declaratively and simply returned from the macro builder. The macro compiler would have to interpret that DSL to produce an effectful computation and purity could be retained _(up to the purity of the standard library which I think is acceptable given that Dart is not pure by default.)_

**Comment by jakemac53** [comment]
> I agree with this statement however the current proposal makes that impossible.

Correct, that is a statement about how well behaved macros _should_ operate. They are not statements about what a macro can or cannot do. We cannot guarantee any of the bullet points there. Hence this statement:

```
The macro system is not designed to provide hard security guarantees of the above properties. Users should consider the macros that they apply to be trusted code.

The restrictions in the following sections encourage the above properties as much as possible.
```

We are providing the full expressiveness of the Dart language, so you can have mutable global state, etc. And in fact some uses of a mutable global state may be perfectly fine (maybe it's just a cache of computations, etc). We can try to mitigate things in certain ways to try and keep people on the rails, but ultimately the macros have to be well behaved.

> to expose a declarative DSL where the macro output is described declaratively and simply returned from the macro builder

If I understand correctly you are suggesting a code DSL instead of the Code classes which are based on Strings and Identifiers?

I don't think that buys us much (if anything, other than possibly a nice syntax). Macro can still use mutable global state in order to break the desired pure nature. We could try to make it difficult/impossible to create a custom subtype of Code. But I am not sure it's worth the effort.

Just from a usability standpoint alone we do want to look at templated strings as a way of helping this, and it would also probably achieve some of the other "pureness" goals. We could even make all the Code types have no public constructors and force you to go through templated strings.

**Comment by modulovalue** [comment]
_(First of all, sorry to be this pedantic here, but that statement appears in a specification and I think it is important to be precise here to not infer anything that's wrong about such an important feature)_

---

> Correct, that is a statement about how well behaved macros should operate.

My point is that macros can't be pure by definition, at all. Pure is a concept that is clearly defined, similar to soundness.

Dart can be pure by restricting Dart to a subset of Dart

Consider the following example:

Example A:
```dart
void foo() {
  1 + 1; /// (Ints can overflow, this isn't really pure, imagine I'm using BigInt.)
}
```

We can easily verify that Example A is pure, as long as we assume that the binary addition over 1 and 1 doesn't throw.


Example B:
```dart
void foo(void Function() bar) {
  1 + 1;
}
```

Example B is pure as well, but it doesn't do anything useful.

Example C:
```dart
void foo(void Function() bar) {
 bar(); 
 1 + 1;
}
```

Now, with Example C, we have 2 cases: 
* foo is pure as long as bar has no sideeffects. (If bar has no sideffects, then foo is useless)
* or foo is not pure, because bar is not pure, in this case foo is useful but not pure.

_(It's silly I know, but important, especially for static analysis)_


---

> We can try to mitigate things in certain ways [..].

I don't think that is necessary. Dart isn't pure by default and that would be too restricting for little added benefit.

(Also, there is no proof so far that pure programs can implement all non pure programs as efficient as the non pure version, I don't think forced purity for the sake of being pure is good)

---

Here is a more concrete example for a pure alternative:

```dart
class MyMacro implements Macro {
  const MyMacro();

  @override
  MacroOperation buildMacro(
    final MacroContext context,
  ) {
    // Purity is retained as long as no declaration within [context] throws.
    return const MacroOperationComposite(
      operations: [
        MacroOperationDeclaration(
          name: "MyDeclaration",
          otherProperty: "example argument",
          // ...
        ),
        MacroOperationDeclaration(
          name: "MyDeclaration",
          otherProperty: "example argument",
          // ...
        ),
      ],
    );
  }
}

// === Macro application ===

@MyMacro()
void foo() {}

// =========================

// === Standard lib ===

abstract class Macro {
  MacroOperation buildMacro(
    final MacroContext context,
  );
}

abstract class MacroContext {
  String get filePath;

  ClassIntrospector get classIntrospector;

// ...
}

// Note: This looks like as AST it basically is an AST.
// Note: If this reminds you of flutter, this resemblance
//       is intentional not because I like Flutter, but
//       because flutter made a good decision to do it that way.
// Note: A builder that would provide an API similar to the
//       current proposal could be provided as a package.
// Note: To make this really clean dart would need sum types 
//       for double dispatch.
// Note: To evaluate this, the macro system would interpret this dsl.
//       (By walking the model how a tree walking interpreter
//       would interpret a program.)
abstract class MacroOperation {}

abstract class MacroOperationComposite implements MacroOperation {
  const factory MacroOperationComposite({
    required final List<MacroOperation> operations,
  }) = _MacroOperationCompositeImpl;

  List<MacroOperation> get operations;
}

abstract class MacroOperationAddDeclaration implements MacroOperation {
  List<MacroOperation> get operations;
}

abstract class MacroOperationDeclaration implements MacroOperation {
  String get name;

  String get otherProperty;

  const factory MacroOperationDeclaration({
    required final String name,
    required final String otherProperty,
  }) = _MacroOperationDeclarationImpl;
}

abstract class ClassIntrospector {
  // ...
}

class _MacroOperationCompositeImpl implements MacroOperationComposite {
  @override
  final List<MacroOperation> operations;

  const _MacroOperationCompositeImpl({
    required final this.operations,
  });
}

class _MacroOperationDeclarationImpl implements MacroOperationDeclaration {
  @override
  final String name;
  @override
  final String otherProperty;

  const _MacroOperationDeclarationImpl({
    required final this.name,
    required final this.otherProperty,
  });
}

// ================================

```

**Comment by modulovalue** [comment]
> Just from a usability standpoint alone we do want to look at templated strings as a way of helping this, 

I have very good evidence (from my personal macro system) to believe that templated strings or something similar is not needed (at least for an initial release of macros).

Also, Flutter shows that declarative models are accepted by users. Only a tiny minority wishes to have special syntax for constructing widget trees. The added complexity is in my opinion not worth it.

**Comment by jakemac53** [comment]
> My point is that macros can't be pure by definition, at all. Pure is a concept that is clearly defined, similar to soundness.

Maybe a better word would be `idempotent`? I accept that the use of `Pure` here is not really accurately describing even a well written macro. What we really want to express is that the same inputs should always result in the same outputs.

> I have very good evidence (from my personal macro system) to believe that templated strings or something similar is not needed (at least for an initial release of macros).

They are definitely not required, just a nice to have. But I do think that they would be a much nicer api, a rough proposal is here https://github.com/dart-lang/language/blob/master/working/tagged-strings/feature-specification.md if you are interested.

**Comment by modulovalue** [comment]
I think `pure` is fine, it's just that pure is not applicable here if the API to add declarations returns void.

A bug in the macro compiler could make a macro crash during a call to e.g. declareType. The proposed example for a declarative macro API above would prove that that can never happen. That would be a direct benefit of preserving real purity here!

> a rough proposal is here

Thank you.
