### ISSUE TITLE
Safe way to convert a nullable non-local variable to a non-nullable local variable

### ISSUE THREAD

**Issue by fptavares** [dart-lang/language#2248]
When an instance method is called, which makes use of a nullable instance variable, it's hard to avoid using the bang (!) operator, as the instance variable can change at any time back to null.

```dart
class APIClient {
  String? apiKey;

  void callAPI() {
    if (apiKey == null) {
      throw Exception('Cannot use API without a key');
    }
    http.get(Uri.https('http://myapi', '/path'), headers: {'key': apiKey!});
  }
}
```

This code can still throw an exception from the not-null assertion: `apiKey!`. The solution would be to create a local variable with the non-null value of the nullable instance variable at the time the method was called. However, there's no simple way for doing this.

One could catch the error thrown by the assertion, and convert it to an application specific exception:

```dart
class APIClient {
  String? apiKey;

  void callAPI() {
    String notNullApiKey;
    try {
      notNullApiKey = apiKey!;
    } catch (error) {
      throw Exception('Cannot use API without a key');
    }
    
    http.get(Uri.https('http://myapi', '/path'), headers: {'key': notNullApiKey});
  }
}
```

A shorter form could be:

```dart
class APIClient {
  String? apiKey;

  void callAPI() {
    String? localApiKey = apiKey;
    String notNullApiKey = localApiKey != null ? localApiKey : throw Exception('Cannot use API without a key');

    http.get(Uri.https('http://myapi', '/path'), headers: {'key': notNullApiKey});
  }
}
```

But as a cleaner and more flexible solution, I would like to propose that Dart allows a throw in the if null expression (??), just like it allows it in the above one-line if-else condition expression:

```dart
String notNullVar = nullableVar ?? throw ...
```

Here is how this example would look like then:

```dart
class APIClient {
  String? apiKey;

  void callAPI() {
    String notNullApiKey = apiKey ?? throw Exception('Cannot use API without a key');

    http.get(Uri.https('http://myapi', '/path'), headers: {'key': notNullApiKey});
  }
}
```

**Comment by fptavares** [comment]
Also, since this is done in a one-line conditional expression, the example above could be further simplified to:
```dart
  void callAPI() {
    http.get(Uri.https('http://myapi', '/path'), headers: {
      'key': apiKey ?? throw Exception('Cannot use API without a key'),
    });
  }
```

**Comment by eernstg** [comment]
Note that the specific approach mentioned [here](https://github.com/dart-lang/language/issues/2248#issue-1239681401) is already available:

```dart
String? nullableVar;

void main() {
  // ... code that might initialize `nullableVar`.
  String notNullVar = nullableVar ?? (throw 'Something');
  // ...
}
```

The `throw` expression needs to be parenthesized because of the operator precedence, but otherwise it's just working as described already.

**Comment by fptavares** [comment]
Thanks @eernstg. I didn't realize that was already possible when parenthesized. Closing request.
