### ISSUE TITLE
Infer generic from callbacks

### ISSUE THREAD

**Issue by terryl1900** [dart-lang/language#2261]
Hello! I noticed that this works fine:
```
class Emitter<T> {
  Emitter(this.create);
  final void Function(void Function(T) emit) create;
}

void main() {
  Emitter<int>((emit) => emit(1));
}
```

While this throws `The argument type 'int' can't be assigned to the parameter type 'Never'.`
```
void main() {
  Emitter((emit) => emit(1));  // Omit type int
}
```

I'm curious what stops Dart infer the type here? I couldn't find an existing issue about this.

**Comment by Levi-Lesches** [comment]
Perhaps this is vaguely related to #731, because it can't infer `T` even though it is in the given argument.

**Comment by terryl1900** [comment]
Thanks for the explanation.

**Comment by munificent** [comment]
> How does Dart determine that `?` is a `Never`?

I believe it's because `T` appears in a contravariant position (as a function parameter).

> `Never` would mean it can be statically shown that no argument would be valid, but it sees `emit` being called with `1` right there.

Using `Never` for the function's parameter type means that any function type accepting any parameter type is a valid callback to be passed to `Emitter()`.
