### ISSUE TITLE
Static classes

### ISSUE THREAD

**Issue by nate-thegrate** [dart-lang/language#2270]
Often times, a class is created as a way to organize a bunch of `static` functions/variables/constants rather than to be instantiated or extended. The `Colors` class is a great example: instead of creating objects of type `Colors`, you use its static members in place of `Color` objects.

```dart
Color mysteryColor  = Color(0xFF00FFFF); // not readable :(
Color favoriteColor = Colors.cyan;       // convenient!

Colors c = Colors(); // doesn't make sense
```

<br>

If you take a look at the [colors.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/colors.dart#L193) file, you'll see that they do something clever:

```dart
class Colors {
  // This class is not meant to be instantiated or extended; this constructor
  // prevents instantiation and extension.
  Colors._();
  ...
}
```

Since the `abstract` keyword doesn't prevent extension, it's necessary to have this empty private constructor. However, this isn't very intuitive, so you have to include that comment [every time you make a static class](https://github.com/flutter/flutter/search?q=%22This+class+is+not+meant+to+be+instantiated+or+extended%22).

<br>

## Proposal

Allow classes to be defined using the `static` keyword.

For example, let's say we wanted to make a collection of `Shape` objects.

```dart
class Shape {
  int sides;
  Shape({required this.sides});
}
```

We could do something like this:

```dart
class Shapes {
  // This class is not meant to be instantiated or extended; this constructor
  // prevents instantiation and extension.
  Shapes._();

  static Shape circle = Shape(sides: 0);
  static Shape triangle = Shape(sides: 3);
  static Shape square = Shape(sides: 4);
  static Shape rect = Shape(sides: 4);

  static List<Shape> polygons = [triangle, square, rect];
  static List<Shape> get rectangles => [
        for (final polygon in polygons)
          if (polygon.sides == 4) polygon
      ];
}
```

But the class would be much more elegant if we could write it another way:

```dart
static class Shapes {
  Shape circle = Shape(sides: 0);
  Shape triangle = Shape(sides: 3);
  Shape square = Shape(sides: 4);
  Shape rect = Shape(sides: 4);

  List<Shape> polygons = [triangle, square, rect];
  List<Shape> get rectangles => [
        for (final polygon in polygons)
          if (polygon.sides == 4) polygon
      ];
}
```

This feature already exists in languages like C#, and I believe it would be a great addition to the Dart language.

**Comment by nate-thegrate** [comment]
Thanks to both @jakemac53 and @lrhn for the great responses. Enhanced enums fit a lot of use cases that you might want a static class for.

`extension Colors on Never` isn't very intuitive to read & understand, but it looks like it accomplishes exactly what I'm looking for. I also saw that the Dart style guide link you gave recommends using libraries instead:

> If what you want is a namespace, a library is a better fit. Libraries support import prefixes and show/hide combinators.

Fortunately it looks like there are plenty of different ways to accomplish what I'm trying to do, so I think we're good to close the issue.

**Comment by Levi-Lesches** [comment]
@lrhn I believe you're thinking about https://github.com/dart-lang/language/issues/2254#issuecomment-1134702760, as well as a lot of namespace-related talk in #336

**Comment by lrhn** [comment]
Thanks @Levi-Lesches, there doesn't seem to be a single issue just about namespaces, but it keeps cropping up in other discussions.

The `extension Colors on Never` is definitely not intuitive.

A namespace would be like a `class`, `mixin` or `extension` declaration that cannot be used for what those declarations are otherwise used for. The `extension ... on Never` satisfies that by not introducing a type or interface to begin with, and being entirely unusable for what extensions or otherwise used for. Using a `class` or `mixin` would at least introduce an interface.
Not pretty, but useless!

**Comment by nate-thegrate** [comment]
For those interested, I've created #2272 based on what's been discussed in this issue.

**Comment by mateusfccp** [comment]
With the upcoming class modifiers will `abstract final class` be an alternative on `extension ... on Never`? I don't think it's any more intuitive, but it will be at least "documented".

**Comment by munificent** [comment]
Yeah, I think `abstract final class` gets you most of the way there. It's a class that you can't construct, extend, mix in, or implement.
