### ISSUE TITLE
Found 1 file excluded from sound null safety

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/language#2274]
Found 1 file excluded from sound null safety:

```
working/macros/example/bin/run.dart:5:// @dart=2.9
```

See https://github.com/dart-lang/sdk/issues/49169 for more context.

**Comment by jakemac53** [comment]
Fwiw, that file is blocked on `package:frontend_server/compute_kernel.dart`.

**Comment by jakemac53** [comment]
https://dart-review.googlesource.com/c/sdk/+/247601 will unblock this

**Comment by jakemac53** [comment]
Fixed in https://github.com/dart-lang/language/commit/a850f3cd7c6177e9b7dc0a0b79b6dbd44b9b2b22
