### ISSUE TITLE
Should parallel assignment be treated as multiple assignment for lints?

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2277]
We have a lint, [avoid_multiple_declarations_per_line](https://dart-lang.github.io/linter/lints/avoid_multiple_declarations_per_line.html)
which warns about 
```dart
var x = something, y = other;
```
declarations which declare more than one variable. (It's a lint, and AFAICS not included in the official core/recommended lints, so it's something people have chosen to opt into.)

Should an assignment like `var (i, length) = (0, list.length);` count towards that lint? 

(And is this really a linter question? The lint documentation has no motivation, so it's unclear what the goal of the lint is, other than to avoid declarations of that form, and therefore it's unclear whether a pattern parallel assignment should be covered too.)

**Comment by cedvdb** [comment]
God no, it's pretty clear and concise with the parenthesis, as opposed to `var x = something, y = other;`.

How else are you going to destructure a tupple ?

**Comment by lrhn** [comment]
You can obviously destructure a tuple, but if you are destructuring a tuple *literal*, then you are effectively just doing parallel initialization, and could just as well use two separate declarations instead.

With two different ways to do the same thing, a lint is a way to enforce one or the other. Since we have a lint for preferring separate declarations over multiple declarations on the same line, would we want one for preferring separate declarations over multiple variable declarations using a tuple literal too?

**Comment by cedvdb** [comment]
I was talking about destructing a tupple literal too. That rule would be detrimental for people that find it perfectly fine but do not find this okay:

var x = something, y = other;

So if you want to add tupple literal because it fits the lint rule title, then an additional more fine grained rule would be useful.

**Comment by munificent** [comment]
Closing this. I think the answer is "no", we shouldn't lint destructuring a tuple literal in a variable initializer.
