### ISSUE TITLE
Is it possible to invoke setters in class in Dart?

### ISSUE THREAD

**Issue by sardorbek-jurakulov** [dart-lang/language#2296]
Is it possible to invoke setters which declaired with set keyword in class in Dart?

In the script written below, Dart does not recognize the setters:
```
    class Cat {
      String _size = '';
      String _color = '';
      int _age = 0;
    
      Cat(String initialSize, String initialColor, int initialAge) {
         size(initialSize);
         color(initialColor);
         age(initialAge);
      }
    
      // getter and setter fields are started
      String get size {
        return _size;
      }
    
      void set size(String animalSize) {
        _size = animalSize;
      }
    
      String get color {
        return _color;
      }
    
      void set color(String animalColor) {
        _color = animalColor;
      }
    
      int get age {
        return _age;
      }
    
      void set age(int animalAge) {
        _age = animalAge;
      }
      // getter and setter fields are ended
    
    }
```
Error: 'size' isn't a function or method and can't be invoked.

Error: 'color' isn't a function or method and can't be invoked.

Error: 'age' isn't a function or method and can't be invoked.

**Comment by mraleph** [comment]
Setters are invoked when you assign to the property, the syntax you are looking for is `size = initialSize;`. I recommend reading through the language tour: https://dart.dev/guides/language/language-tour#getters-and-setters

**Comment by sardorbek-jurakulov** [comment]
Got it, thank you very much!
