### ISSUE TITLE
Can a record type be an expression, and if so, how to distinguish between a record?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2304]
Are record types legal expressions, like type literals? For example, `var x = List<int>;` is legal, but `var x = void Function()` is not.

If the answer is 'no,' I'm not sure anything needs to be added to the spec. (The constructor-tearoffs spec [did not need to be amended](https://github.com/dart-lang/language/issues/1700) for the 'no' answer regarding function types.) If the answer is 'yes', how might we disambiguate between a record _type_ with only positional fields, and a record with only positional fields? For example,

```dart
var x = (int, String);
```

Does this declare a record, referencing, possibly, two local variables, or a record type?

https://github.com/dart-lang/language/blob/df9574472a7a84aa518b88794c5ec9ff6349f170/working/0546-patterns/records-feature-specification.md

**Comment by Levi-Lesches** [comment]
It's questions like these that make me so glad I didn't take compiler classes.

**Comment by eernstg** [comment]
I would recommend that we do not generalize expressions to include record types. This would mean that an expression of the form `(int, String)` evaluates to a record of type `(Type, Type)` (or some other type if `int` and/or `String` refers to some other declaration than the standard one).

**Comment by munificent** [comment]
What @eernstg and @lrhn said. No good can come of us trying to make record type literals work. Honestly, type literals themselves were a bad idea that have gotten in the way of a number of other more useful features. (For example, using a class name as a tear-off of its unnamed constructor, or a metaclass.)
