### ISSUE TITLE
"return/yield if not null " symbol.

### ISSUE THREAD

**Issue by Mehmetyaz** [dart-lang/language#2307]
I have a very small but effective symbol idea.

"Return if not null":

```dart
Map<String , int> map = {};


int function(){
  var y = map['key'];
  if (y != null) {
    // do something / create new key
    return y;
  }
  return 10;
}

int alternative(){
  return? map['key'];
  // do something
  return 10;
}

Stream<int> stream() async* {
  yield? map['key'];
  yield 10;
}
```

A "?" right next to return or yield. By adding it, we are not creating both a new variable and a new statement.

Yes, we can shorten our function with the statement `return map["key"] ?? doSomething()`.
But for this we need to create a second function and assume certain situations in this second function. And having assumptions about something in different code blocks negatively affects team cohesion and code readability. For example, we should fit assumptions about whether a class member is null or not in the same block as possible.  Maybe there is no such policy, but I care about it and I've seen many developers care. 

In real use case:

I really don't need to create variable "f" and first if statement.

```dart
static int _getTypeForData(Object data) {
    var f = _types[data.runtimeType];

    if (f != null) {
      return f;
    } else if (data is Map<dynamic, StyleData>) {
      return 17;
    } else if (data is List<int>) {
      return 15;
    } else if (data is List) {
      return 18;
    } else {
      throw UnsupportedError("Type ${data.runtimeType} is not supported");
    }
  }
```

My suggestion:

```dart
static int _getTypeForData(Object data) {
    return? _types[data.runtimeType];

    if (data is Map<dynamic, StyleData>) {
      return 17;
    } else if (data is List<int>) {
      return 15;
    } else if (data is List) {
      return 18;
    } else {
      throw UnsupportedError("Type ${data.runtimeType} is not supported");
    }
  }
```

**Comment by Levi-Lesches** [comment]
To add to this, a lot of times you find code like the following: 

```dart
int computeValue() {
  int? result;
  result = computation1();  // returns null on failure
  if (result != null) return result;  // end here

  result = computation2();  // otherwise, keep going
  if (result != null) return result;

  // ...
}

This use-case could be simplified by `return?`:
```dart
int computeValue() {
  int? result;
  return? result = computation1();  // assignments are expressions
  return? result = computation2();
  // ...
}

**Comment by cedvdb** [comment]
> To add to this, a lot of times you find code like the following:
> 
> ```dart
> int computeValue() {
>   int? result;
>   result = computation1();  // returns null on failure
>   if (result != null) return result;  // end here
> 
>   result = computation2();  // otherwise, keep going
>   if (result != null) return result;
> 
>   // ...
> }
> 
> This use-case could be simplified by `return?`:
> ```dart
> int computeValue() {
>   return? computation1();
>   return? computation2();
> }
> ```

What is the difference with ?

```
return comp1() ?? comp2()
```

**Comment by Mehmetyaz** [comment]
> > To add to this, a lot of times you find code like the following:
> > ```dart
> > int computeValue() {
> >   int? result;
> >   result = computation1();  // returns null on failure
> >   if (result != null) return result;  // end here
> > 
> >   result = computation2();  // otherwise, keep going
> >   if (result != null) return result;
> > 
> >   // ...
> > }
> > 
> > This use-case could be simplified by `return?`:
> > ```dart
> > int computeValue() {
> >   return? computation1();
> >   return? computation2();
> > }
> > ```
> 
> What is the gain over
> 
> ```
> return comp1() ?? comp2()
> ```

The difference is `//...`.  As you know "??" The symbol is the return of the second value if the first value is null. 

If we have a 3rd value (where 2 is also null), or if we're going to do something extra while returning the second value, we should definitely create an "if statement" or a second function. In the seconds function we have to assume that the first value is null.  I wanted this whole sentence to appear easily in one block: "The 1st and second values are null. A process is now running for the third value."

BUT: 

Based on the comments I got on Reddit, this suggestion is going to create confusion. So I agree that it would create unnecessary confusion for a small benefit to be used in such specific situations.

It will be difficult to explain a return that doesn't kill the code block, especially to a beginner (who is learning software for the first time in the darts ecosystem).
