### ISSUE TITLE
Event Loop Vs Fibers

### ISSUE THREAD

**Issue by jayadevanraja** [dart-lang/language#2309]
This is a question about language design decision, and advantages and disadvantages thereof.

[Javascript (Node.js)](https://www.journaldev.com/7462/node-js-architecture-single-threaded-event-loop) and [Dart](https://medium.com/@purvajg/microtasks-and-event-loops-in-dart-9f5863f031d8) use the "Single Threaded Event Loop Model", while [Java](https://www.infoworld.com/article/3652596/project-loom-understand-the-new-java-concurrency-model.html), Golang, .net etcetera use fibers or something similar. Here, by fibers, I include "Multi-Threaded Request-Response Model". What are the advantages and disadvantages (like ease of coding, easy to reason about, better performance, etcetera) of each approach?

It is advantageous to have fibers instead of having to use heavy threads, so I am interested in the case of "**Fibers + Scheduler**" vs "**Event Loop + Futures**".

**Comment by ykmnkmi** [comment]
Look at [dartion](https://github.com/dart-archive/sdk), it's archived.

**Comment by ykmnkmi** [comment]
@jayadevanraja some information here [index.md](https://github.com/dart-archive/www.dartino.org/blob/4dc69750fc11986caf7a747349ef9105792ae7e9/index.md) and [concurrency.md](https://github.com/dart-archive/www.dartino.org/blob/4dc69750fc11986caf7a747349ef9105792ae7e9/guides/concurrency.md).

**Comment by jayadevanraja** [comment]
@ykmnkmi  Thanks. So there was a previous attempt to bring fibres to Dart. Has there been any discussion about the relative merits and demerits of the two approaches? I mean, the [coloured function problem](http://journal.stuffwithstuff.com/2015/02/01/what-colour-is-your-function/).

Will it be appropriate to propose [Loom](https://wiki.openjdk.org/display/loom/Main) for Dart language? If yes, where to propose it?

**Comment by munificent** [comment]
> Has there been any discussion about the relative merits and demerits of the two approaches?

Yes, many of them over the years. Concurrency is a deep property of a language and every approach has many trade-offs. A recent discussion is: https://github.com/dart-lang/language/issues/333.

I'll close this issue in favor of continuing the discussion there.
