### ISSUE TITLE
[suggestion] Dart type annotation should someday be positioned to the right.

### ISSUE THREAD

**Issue by devanon8** [dart-lang/language#2312]
```typescript
class TypeScript {
    #a: number
    constructor(a: number) {
        this.#a = a
    }
}
```

```dart
class Dart {
  num a;
  Dart(num this.a) { 
  }
}
```

Dart is a good language, but I feel that having the type annotations on the left brings a switching cost for developers writing mainstream languages today.

At the time Dart was created, the main languages had type annotations on the left.

I know that Dart was designed with the intention of being a language with few surprises for developers of other languages.

However, over time, the syntax of those languages is slowly becoming legacy, and it is possible that new developers will gradually come to find it rather surprising to have type annotations on the left.

If a new front-end-friendly language is ever created, it will probably not have type annotations on the left.

Today's JavaScript developers are more familiar with languages like TypeScript, Kotlin, Swift, Rust, and Go than Java, C, or C#. The number of people who are uncomfortable or surprised to see type annotations on the right side is much smaller, and for new Dart developers, the syntax of being able to write code with a syntax similar to those languages is a welcome thing.

In the long run, the dominant type annotation position is still expected to be on the right side.

I don't think this is a task that will be taken up immediately, as it would be a major disruptive change, but in the long run, I think it would be desirable to have type annotations on the right side sooner rather than later, so that Dart and Flutter continue to be accepted by new developers and do not become legacies.

I'm not a language developer, so I don't know the details, but I've often seen the argument that from a parsing perspective, having the type on the right is easier to implement and better in terms of performance.

It was suggested that Dart should make a disruptive change to Dart3 (or Dart4) to make type annotations right side for the next 5 or 10 years.

**Comment by Cat-sushi** [comment]
[Right Hand Types · Issue #42 · dart-archive/dart_enhancement_proposals](https://github.com/dart-archive/dart_enhancement_proposals/issues/42 "Right Hand Types · Issue #42 · dart-archive/dart_enhancement_proposals")

**Comment by devanon8** [comment]
I'm surprised it's been more unpopular than I thought it would be, but even if it's already been discussed, it could change after a long time, and I'd like to propose it again in five years.

**Comment by vxern** [comment]
> having the type annotations on the left brings a switching cost for developers writing mainstream languages today.

That's too bad. I didn't know that a language becoming mainstream meant that all other programming languages were consequently required to become more or exactly like them. What's the innovation in that?

> At the time Dart was created, the main languages had type annotations on the left.

Indeed. What's wrong with that?

> Dart was designed with the intention of being a language with few surprises for developers of other languages.

Type annotations on the left are not a 'surprise'. If a person expects that all languages they come to meet have identical syntax to what they already write, that is on them, not the language designers.

> If a new front-end-friendly language is ever created, it will probably not have type annotations on the left.

But Dart does. And we're at Dart stage.

> Today's JavaScript developers are more familiar with languages like TypeScript, Kotlin, Swift, Rust, and Go than Java, C, or C#.

Why are we suggesting to model Dart after what JavaScript developers are familiar with?

> I don't think this is a task that will be taken up immediately, as it would be a major disruptive change, but in the long run, I think it would be desirable to have type annotations on the right side sooner rather than later, so that Dart and Flutter continue to be accepted by new developers and do not become legacies.

If you're considering the factors that contribute to a language becoming legacy, you're looking at the wrong thing.
