### ISSUE TITLE
Null Safety not encapsulated in Inline Conditional

### ISSUE THREAD

**Issue by Decryptic** [dart-lang/language#2317]
It is my understanding from reading the Dart language walk-through that Dart syntax escapes the nullity of a nullable variable once it has been checked to ensure it's not null. E.g.:

```
String message = ', world';
String? test = 'hello';
if (test != null) {
    message = test + message;
} else {
    message = 'goodbye' + message;
}
print(message);
```

Since `test` has been checked to ensure it has a non-null value, it can be called with `+ message` in a concatenation operation like it were a `String`, rather than it being a `String?`.

I would like to see this null Safety be encapsulated in inline conditional statements. E.g.:

```
String? test = 'hello';
String message = (test == null ? 'goodbye' : test) + ', world';
print(message);
```

Logically, this should work in Dart; however, this line causes an error because the compiler isn't sure whether `test` is null or not in the concatenation operation. To get this to work, one must force the escape of nullity using the `!` operator. I believe Dart should apply the same ease of null safety in inline conditionals as it does in conditional blocks, because the principle is the same and inline conditionals are much more concise than their block counterparts. 

I encountered this error while I was writing my free, open-source app called [Card Counting Companion](https://github.com/Decryptic/card_counting_companion). On line 257 of `lib/main.dart`, I have a line of code that reads:

`_cards_path + (_card == null ? 'back.png' : _card!.png_name),`

Here, I was forced to access the getter `.png_name` with `_card!.png_name`, even though, due do the scope of the inline conditional, the `Card?` will never be null when accessing the property, so `_card.png_name` should work just fine here. It would be nice to see Dart carry the same null safety assertions it does for inline conditionals as it does for conditional blocks.

**Comment by Levi-Lesches** [comment]
> ```
> String? test = 'hello';
> String message = (test == null ? 'goodbye' : test) + ', world';
> print(message);
> ```
> 
> 
>     
>   
> 
> Logically, this should work in Dart; however, this line causes an error because the compiler isn't sure whether `test` is null or not in the concatenation operation. To get this to work, one must force the escape of nullity using the `!` operator.

This does work in the current version of Dart, 2.17.5. 
```dart
String? getStr() => "hello"; 
void main() {
  String? test = getStr();
  String message1 = (test == null ? 'goodbye' : test) + ', world'; // OK
  String message2 = "${test ?? 'goodbye'}, world";  // same but simpler
}
```

Also, as you can see, you can shorten `x == null ? y : x` to just `x ?? y`, as you can see in `message2` above. 

Your second example also works as-is, and Dart will even tell you that you can get rid of the `!`: 

```dart
  Card? _card = // ...
  String temp = _card == null ? 'back.png' : _card!.png_name;  // Warning: The ! will have no effect
```

**Comment by Decryptic** [comment]
> > ```
> > String? test = 'hello';
> > String message = (test == null ? 'goodbye' : test) + ', world';
> > print(message);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Logically, this should work in Dart; however, this line causes an error because the compiler isn't sure whether `test` is null or not in the concatenation operation. To get this to work, one must force the escape of nullity using the `!` operator.
> 
> This does work in the current version of Dart, 2.17.5. Make sure your project is using the latest version.
> 
> ```dart
> String? getStr() => "hello"; 
> void main() {
>   String? test = getStr();
>   String message1 = (test == null ? 'goodbye' : test) + ', world'; // OK
>   String message2 = "${test ?? 'goodbye'}, world";  // same but simpler
> }
> ```
> 
> Also, as you can see, you can shorten `x == null ? y : x` to just `x ?? y`, as you can see in `message2` above.
> 
> Your second example also works as-is, and Dart will even tell you that you can get rid of the `!`:
> 
> ```dart
>   Card? _card = // ...
>   String _card_path = "files/cards/";
>   String temp1 = _card_path + (_card == null ? 'back.png' : _card!.png_name);  // Warning: The ! will have no effect
>   String temp2 = _card_path + (_card?.png_name ?? "back.png");  // OK
> ```

Thank you for reminding me about the `(??) :: Null n => n a -> a -> a` function. I will use that code instead of `?:` in my implementation. Nevertheless, I am still getting the error trying to access the getter after `_card` has been checked to ensure it's not null in the inline conditional.

For reference:

```
lib/main.dart:257:69: Error: Property 'png_name' cannot be accessed on 'Card?' because it is potentially null.
 - 'Card' is from 'package:card_counting_companion/src/card.dart' ('lib/src/card.dart').
Try accessing using ?. instead.
                  _cards_path + (_card == null ? 'back.png' : _card.png_name),
                                                                    ^^^^^^^^
lib/main.dart:44:9: Context: '_card' refers to a property so it couldn't be promoted.
See http://dart.dev/go/non-promo-property
  Card? _card;
```

```
penguin@icicle:~$ flutter --version
Flutter 3.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 676cefaaff (5 days ago) • 2022-06-22 11:34:49 -0700
Engine • revision ffe7b86a1e
Tools • Dart 2.17.5 • DevTools 2.12.2
```

Regardless of the status of this issue, I will stick to using `_cards_path + (_card?.png_name ?? 'back.png'),` in my repo. Thank you.

**Comment by eernstg** [comment]
Here's the crucial bit:

> `Context: '_card' refers to a property so it couldn't be promoted.`

An instance variable can not be promoted, because we might get a different value next time we evaluate the same instance variable. One reason is that the instance variable could have been modified by some other code which has been executed in the meantime. For instance:

```dart
A? anA;

class A {
  int? i = 1;
  A() {
    anA = this;
  }
}

void innocentFunction() => anA?.i = null;

void main() {
  var a = A();
  if (a.i != null) {
    innocentFunction();
    print(a.i!.isEven); // Throws.
  }
}
```

Dart does not try to analyze the body of `innocentFunction` even though it is statically known that we will execute exactly that body when `innocentFunction()` is evaluated. But if we're calling an instance member (of _any_ object) then we certainly can't know at compile time which piece of code we will actually execute, so we can't know that they don't do things like `anA?.i = null`. Another issue is that the object of type `A` could have been an instance of a subtype that overrides the getter of the instance variable `A.i`, and that getter could return a different value each time it's called.

Check out [this topic](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion) to see much more info about this topic.
