### ISSUE TITLE
Mixin's methods incorrect applying in case with the same name   

### ISSUE THREAD

**Issue by mormih** [dart-lang/language#2320]
I faced with weird problem when try to apply 2 mixins with the same methods.

```
mixin M1 {
  void methodA(){
    print("M1");
  }
}

mixin M2 {
  void methodA(){
    print("M2");
  }
}

class A with M1, M2 {

}

void main() {
  A().methodA(); 
}

```
Expected error like: 
`
Error: Applying the mixin 'M2' to 'Object with M1' introduces an erroneous override of 'methodA'.
` 
But it's compiled and silently overrides M1 mixin.

Here is my SDK version output: 
`Dart SDK version: 2.17.3 (stable) (Wed Jun 1 11:06:41 2022 +0200) on "windows_x64"`

**Comment by munificent** [comment]
This is working as intended. Mixins are applied one after the other and it's valid for one mixin to override another's methods.
