### ISSUE TITLE
Add Move Semantics via Unique<T> / Rvalue<T> magic classes

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/language#2355]
## Motivation

I would like a way to guarantee constant time communication between isolates.  In other languages this could be accomplished with move semantics.  We could solve that problem by adding move semantics to Dart but that is a big change to the language.  Here I propose if we add 2 magical classes to the language we could get move semantic's performance with minimal change to the language.

## Example usage

```dart

void _isolateMain(SendPort port) {
  // This would call the empty constructor for HashMap.  It would be nice to assert that that
  // will be successful at compilation-time but I know that is another can of worms.
  var hashMap = Unique<HashMap<Unique<String>, Unique<String>>>.make();
  hashMap.value['foo'] = 'bar';
  // `send` treats `Unique` specially to implement move.
  port.send(hashMap);
  // This would be an runtime error:
  // print(hashMap.value);
}

void main() async {
  ReceivePort receivePort = ReceivePort();
  spawn(_isolateMain, receivePort.sendPort);
  Unique<HashMap<Unique<String>, Unique<String>>> result = await receivePort.first;
  print(hashMap.value);
}
```

## The new classes

```dart
// This class throws an exception if it is copied in any other context than a
// return value from Unique<T>.value.  This is a novel usage of inheritance and generics.
class Rvalue<T> extends T {}

// This class implements move semantics by clearing out `_value` when it assigned to another `Unique<T>`.
class Unique<T> {
  Rvalue<T> _value;
  static Unique<T> make(List args = []);
  Rvalue<T> get value => _value;
}
```

The new classes will have custom assignment operations that will be used when:
  1) using the `=` operator
  1) passing the object to a function
  1) returning the object from a function

I considered just proposing to make the assignment operation modular but that wasn't sufficient to implement move semantics because the class `Unique` has one more required feature that can't be expressed with just that.  `Unique<T>` has to be recursive such that all the fields and type arguments in T must themselves be `Unique<T>`.

As a convenience we should be able to implicitly cast rvalues to a Unique<T>.  That way we can say:
```dart
  var hashMap = Unique<HashMap<Unique<String>, Unique<String>>>.make();
  hashMap.value['foo'] = 'bar';
```
instead of 
```dart
  var hashMap = Unique<HashMap<Unique<String>, Unique<String>>>.make();
  hashMap.value[ Unique<String>.make('foo')] = Unique<String>.make('bar');
```

## Workaround

It should be noted that technically someone could try to implement this on their own with C interop where C owns the data outside of Dart's heap and there is a Dart api to read and write from it.  This wouldn't however have the uniqueness guarantee which is important for thread-safety.

**Comment by gaaclarke** [comment]
I added an sdk proposal too that sacrifices any compile-time checks for uniqueness and relies on runtime checks: https://github.com/dart-lang/sdk/issues/49587

**Comment by leafpetersen** [comment]
cc @mkustermann

**Comment by mraleph** [comment]
This looks like an attempt to bring `std::unique_ptr<T>` into Dart. Note that `unique_ptr` does not actually guarantee a uniqueness of a pointer to the wrap'ed object, consider for example your code: 

```dart
var hashMap = Unique<HashMap<Unique<String>, Unique<String>>>.make();
hashMap.value['foo'] = 'bar';
```

here you are calling `HashMap.operator[]=` which takes a `HashMap` as a receiver, not a `Rvalue<HashMap<...>>`. So this is a valid implementation of such operator:

```dart
Object? lastAccessedMap;

class HashMap<K, V> {
  operator []=(K k, V v) {
    lastAccessedMap = this; // oops. not so unique anymore.
    // ...
  }
}
```

(btw, you can write this type of code in C++ - which is exactly why `std::unique_ptr<T>` does not really _guarantee_ anything, it is just a smart pointer).

That's not to say that `Unique` and `Rvalue` are not reference types and have overriden assignment/copy/move, which means that our generics need to respect this behavior somehow - which is a massive departure from the current semantics. 

To really guarantee uniqueness through types you need something like linear type system or some variation of it --- and that would have to permeate everything (including builtin collections) to really be safe. I think it is a massive change.

**Comment by gaaclarke** [comment]
Yea @mraleph, that's why I stated that we'd have to recursively check at compile-time that all fields are also `Unique`.  I was thinking that fields would be enough but you're right that global variables throw a wrench in that.  The compile-time checker would have to check them as well.  If you did implement it, it would be pretty surprising if you send an object over a SendPort and it nulls out a global variable that is referenced by the object.

FWIW I was actually thinking of Rust when I came up with this.  I just tried out a few things and Rust does recursively check uniqueness of a struct when sending it on a channel at compile-time.  They are also able to get around your stated problem by disallowing mutable global variables (unless you use `unsafe`).

I'm going to close this since I think it's pretty involved and I'm going to lean into finding a solution for the runtime checks for uniqueness instead of compile-time checks.

**Comment by mraleph** [comment]
FWIW, I think static solution is more _realistic_ than dynamic solution - we have pondered on various types of ownership transfer before (including write-barrier based checking), but we could not figure out a way that would not be too expensive in terms of performance (and/or code size). Static solution does not have those drawbacks. 

Being realistic does not mean easy to implement though and it might not work well with existing Dart code. If you look at how Rust borrow-checker forces you to structure your code around the constraints of the ownership you will notice that you have to write code in a completely different way compared to Dart.

**Comment by fzyzcjy** [comment]
It is possible to create another semantics: "move after gc"?

We may mark a object as needed-to-be-transfered. And then, after a GC, we know it is uniquely referenced, and will finally transfer it.
