### ISSUE TITLE
Type promotion for `x?.f != null`

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/language#2356]
Today we do type promotion on tests of the from `x != null`, but we don't on `x?.f != null`. This yields a somewhat surprising behavior on equivalent programs. For example, this program results in a static error:

```dart
class A { int? f; }
A? maybeNull(A a) => a;

main() {
  var x = maybeNull(A());
  if (x?.f != null) {
    print(x.f); // ERROR: `x` is potentially null
  }
}
```

Rewriting the code to expand `x?.f != null` with the equivalent `x != null && x.f != null` gets rid of the static error.

**Comment by srawlins** [comment]
Maybe a duplicate of https://github.com/dart-lang/language/issues/1224?

**Comment by sigmundch** [comment]
yes, indeed!
