### ISSUE TITLE
Automatically inherit return type

### ISSUE THREAD

**Issue by LeTadas** [dart-lang/language#2359]
# Problem
In the example below I would expect `getResult()` method to automatically inherit the return type without manually casting it. It seems that it already does that if I print `result.runtimeType` it returns `Success<String>`, but trying to access `value` variable gives compile time error.

```dart
void main() {
  final result = getResult();

  print(result.runtimeType); // prints Success<String>
  print(result.value); // gives compile-time error
}

Result<String> getResult() {
  return Success<String>("result");
}

abstract class Result<R> {}

class Success<R> implements Result<R> {
  final R value;
  
  Success(this.value);
}

class Failure implements Result {
  final String error;
  
  Failure(this.error);
}
```

# Expected behaviour

```dart
void main() {
  final Success<String> result = getResult(); // No compile-time errors
  print(result.value); // prints "result"
}

Result<String> getResult() {
  return Success<String>("result");
}

abstract class Result<R> {}

class Success<R> implements Result<R> {
  final R value;
  
  Success(this.value);
}

class Failure implements Result {
  final String error;
  
  Failure(this.error);
}
```

**Comment by Levi-Lesches** [comment]
You sort of answered your own question: 

> It seems that it already does that if I print `result.runtimeType` it returns `Success<String>`, but trying to access `value` variable gives compile time error.

When compiling, before any code is even run, there's no way to know whether `getResult` will return a `Success` or `Failure`, just that it will return some type of `Result`. When you actually run it, _then_ it knows it got a `Success`, and it can print the `.value` if you cast it. The reason you get an error is that Dart doesn't know what it should do in case it gets a `Failure`, because then it won't have a `.value` property

**Comment by LeTadas** [comment]
> You sort of answered your own question:
> 
> > It seems that it already does that if I print `result.runtimeType` it returns `Success<String>`, but trying to access `value` variable gives compile time error.
> 
> When compiling, before any code is even run, there's no way to know whether `getResult()` will return a `Success` or `Failure`, just that it will return some type of `Result`. When you actually run it, _then_ it knows it got a `Success`, and it can print the `.value` if you cast it. The reason you get an error is that Dart doesn't know what it should do in case it gets a `Failure`, because then it won't have a `.value` property.
> 
> Also, this isn't about inheritance. The `Result` class doesn't have any properties at all so there's nothing to inherit.

Ok, I see what you mean. Thank you.
