### ISSUE TITLE
Should we allow extension structs with multiple fields?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#2371]
In the extension struct proposal (#2360), I propose extension structs as a way to support wrapper-less views on an underlying representation (see the meta-issue for linked context).  In the proposal, I only allow a single field to be declared on the extension struct.  This is so that the extension struct may be represented at runtime simply as the value of that field.  There are two ways that we could consider allowing multiple fields:
  - We could say that extension structs with multiple fields get wrapped into a container object (essentially auto-boxing).
  - We could say that an extension struct with multiple fields is simply an unboxed aggregate, which is not a subtype of `Object`, but which represents the equivalent of a raw `C` struct, with move semantics.
 
The former is unappealing to me, since the entire goal of this feature is to avoid implicit wrapping.

The second has some appeal, but feels somewhat under-motivated.

This issue is for discussion and feedback on this.

**Comment by leafpetersen** [comment]
cc @mit-mit @lrhn @eernstg  @munificent @stereotype441 @natebosch @jakemac53 @rakudrama @srujzs @sigmundch @rileyporter

**Comment by lrhn** [comment]
An extension struct is not a struct. It's a view.
When we get records, you can make a view on a tuple if that's what you want.

I see no motivating reason to allow it directly in an extension struct.
