### ISSUE TITLE
weird hashCode behavior for List<int>

### ISSUE THREAD

**Issue by iapicca** [dart-lang/language#2375]
I'm sure this isn't a bug, but just a weird behavior I came across and maybe could be highlighted with some lint or else
Cutting the chase:

the `hashCode` for identical `<int>[]` is different, see the code below

```dart
List<int> integersUntil(int limit) => [for (var i = 0; i < limit; i++) i];

class Foo {
  final List<int> bar;
  final List<int> baz;
  const Foo(this.bar, this.baz);
  @override
  bool operator ==(Object other) => other is Foo && other.hashCode == hashCode;

  @override
  int get hashCode => Object.hash(bar, baz);
}

void main() {
  final foo1 = Foo(
    integersUntil(10),
    integersUntil(100),
  );
  final foo2 = Foo(
    integersUntil(10),
    integersUntil(100),
  );

  print(foo1 == foo2);
}
```

### prints `false`

```diff 
  @override
+  int get hashCode => Object.hashAll([bar, baz]);
-  int get hashCode => Object.hash(bar, baz);
```
### also prints `false`

```diff 
  @override
+  int get hashCode => Object.hashAll([...bar, ...baz]);
-  int get hashCode => Object.hash(bar, baz);
```
###  prints `true`

it would be nice to get a warning or something that points the user in the right direction

**Comment by munificent** [comment]
> NB: Note that it is not safe, in general, to rely on `hashCode` in order to determine equality of anything, because there is no guarantee that objects with the same hash code will be equal in any reasonable sense.

For those who want to know more, [the pigeonhole principle](https://en.wikipedia.org/wiki/Pigeonhole_principle) explains why this must be true.
