### ISSUE TITLE
In a struct or data class instance, what is the value of `this` when it is unboxed?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2377]
Perhaps `this` can only be used to access members of the struct/class, and `this.someMember ...` would be compiled to an invocation of a global function (similar to extension methods) in this situation?

**Comment by leafpetersen** [comment]
I'm not sure I understand the question.  Unboxing, from the perspective of structs, is a compiler optimization that (modulo identity) preserves semantics.  So the value of `this` is a pointer to the struct.  That is, if there is a use of `this` (e.g. an escaping use) the compiler must make the same decisions as any other use: either to re-materialize it, or to not unbox in the first place, or to try to push an unboxed version forward.

I don't understand the dispatch question.  Maybe a helpful way to think about it is that implicitly, an unboxed struct consists not just of the fields, but also of the vtable (well, object header in our case, but you get the idea).  So rather than reading the object header from an offset and using that to find `someMember`, it just reads it from a register.  But that's all an implementation detail.

**Comment by eernstg** [comment]
About the unboxed object and `this`: Yes, we can box the object if there is a reference to `this`. However, this looks like a source of time/space consumption that might fly under the radar.

```dart
class C {
  int i;
  String s;
  C(this.i, this.s);
}

struct S(C that) {
  void sOfBiggerI(S other) {
    var source = i > other.i ? this : other;
    return source.that.s;
  }
}

class D {
  S s; // Let's say that the compiler managed to unbox this.
  ...
}

void main() {
  List<D> ds = ...; // A billion instances of `D`.
  S s = ...;
  for (var d in ds) {
    print(d.s.sOfBiggerI(s));
  }
}
```

It looks benign, but it will give rise to a boxed version of a billion `S`s that were otherwise unboxed. Isn't it a bit dangerous to have that notion of `this` in a struct at all? We can of course lint every occurrence of `this` in a struct which isn't of the form `this./*a sequence of selectors*/`, but it still looks (to me) like a hint that we should think about how to handle `this` in the body of a struct.

> I don't understand the dispatch question

I assume that's the following:

> Perhaps `this` can only be used to access members

The point is that I assume we'd want to execute members of a concrete struct type (assuming that they do not have any non-bottom subtypes) using static resolution (similarly to extension methods). In that case we would not have a dispatch step when we are invoking`sOfBiggerI` on an expression of type `S` which is known by the compiler to be unboxed.

... except that this particular method doesn't support unboxed execution at all, because it introduces the need for a pointer to the enclosing `S`.

So if we make it an error to have a plain `this` in a struct (in general, anything that leaks the reference to the enclosing instance of the struct), and this means that we can only use `this` to access members of the struct.

This means that we could compile `this.someMethod(...)` to a statically resolved invocation of the member `someMethod` of the enclosing struct, if it is concrete and `someMethod` doesn't require access to `this`.

**Comment by lrhn** [comment]
I still do not understand the issue.

A struct instance is an object. The only difference between a struct instance and a class instance is that the struct instance is guaranteed to be unmodifiable, and that we do not guarantee that the struct instance identity is preserved over time.
When you do:
```dart
MyStruct v1 = MyStruct(1, 2);
MyStruct v2 = v1; // Alias, copy, reference copy? Nobody knows!
```
you are creating a new reference to "the structure". Whether `identical(v1, v2)` is true or not is unspecified. Heck, whether `identical(v1, v1)` is true is also unspecified.

There is nothing special about `this`, it's just way to get a reference to the enclosing struct instance.
Writing:
```dart
   void myStructMethod() {
     MyStruct v2 = this;
     ...
   }
```
is precisely the same kind of operation that is done above. Nothing special.

> It looks benign, but it will give rise to a boxed version of a billion `S`s that were otherwise unboxed.

I'm not sure how you can be certain of that.
There is nothing in 
```dart
 void sOfBiggerI(S other) {
    var source = i > other.i ? this : other;
    return source.that.s;
  }
```
that seems like it would guarantee boxing to me. 

It's a small method, with a struct `this` and struct `other` parameter. It looks like something that can easily be entirely inlined. If `that` is also an `S` member, that too can be inlined, or maybe there is a way to called it with a reference to an existing unboxed structure. Or as Leaf said: Change D.s to not be unboxed anyway, rebox `this`, or push the unboxed value forward to `S.that`. That's all up to the compiler. 

You cannot predict when a struct is boxed or unboxed. You shouldn't try. (*Narrator voice*: People tried anyway). 
Instead the compiler should work hard to to whatever works the best for a particular program. That's not always unboxing. Sometimes keeping something boxed is more efficient overall.

**Comment by eernstg** [comment]
We'll see. ;-)

I strongly suspect that if and when we have an implementation where unboxing yields substantial performance benefits, we will have lints telling developers to stop using `this` as a reference in the body of a struct (`this.getter` and `this.method(...)` is OK, it's the plain `this` which is a problem). It's simply going to be intolerable that my example above gives rise to gigabytes of memory which is allocated and never used after the execution of a single statement, when the example could just as well have been expressed as follows:

```dart
struct S(C that) {
  String sOfBiggerI(S other) {
    if (i > other.i) return that.s; else return other.that.s;
  }
}
```

One might claim that it's up to the optimizer to turn the first version into the second one, but we can't rely on optimizers to be infinitely smart, they'll have to stop at some point.

I suspect that it _will_ matter whether we're writing struct code in a style that makes it really hard to avoid unnecessary boxing, or we're writing it in a style where unnecessary boxing is much easier to avoid. Using `this` as a reference is just one of those things that may be extremely box-prone, and can sometimes easily be avoided.

In any case, perhaps the right solution will be to lint it, as far as possible. It's just that we don't usually design features in such a way that developers are told to stop using them, because they are harmful to your software quality.

**Comment by leafpetersen** [comment]
> It's simply going to be intolerable that my example above gives rise to gigabytes of memory which is allocated and never used after the execution of a single statement, when the example could just as well have been expressed as follows:

I'm really lost about how you are arriving at the assumption that your example will give rise to gigabytes of memory.  Compilers are always having to make choices about representation. Sometimes they do make speculative decisions which can have actual negative consequences for (e.g.) memory allocation.  It is true that, for your example, if the compiler decides to unbox the struct and not keep around a boxed version to use, then it will be forced to re-materialize the struct inside of the loop.  That is what is known as a "poor optimization choice".  :). In other words, if we assume that compilers are going to make poor choices, then ... well, compilers are going to make poor choices.  This problem, if you view it as such, already exists.  Doubles, for example, have exactly the semantics that we propose here.  And it is true, that if the compiler  makes a poor choice of where to unbox a double, it can be forced to add allocation that was not apparently there in the original program.    So I'm not sure I really see where to go with this issue.

**Comment by eernstg** [comment]
OK, I'll close this and rest assured that excessive boxing will not be a problem, and/or we can't do anything useful about it by putting constraints on the use of `this`. ;-)
