### ISSUE TITLE
Are pattern guards statically required to be boolean expressions?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#2384]
The patterns proposal has the following text:

```
If there is a guard clause, evaluate it. If it does not evaluate to a Boolean, throw a runtime exception. If it evaluates to false, continue to the next case (or default or exit).
```

Is the implication that a guard clause may have type `dynamic`, with an implied implicit downcast?  Otherwise, how do you get a non-boolean?

**Comment by munificent** [comment]
> Is the implication that a guard clause may have type `dynamic`, with an implied implicit downcast? Otherwise, how do you get a non-boolean?

Yes, in the type checking section, it says:

> It is a compile-time error if the type of an expression in a guard clause is not `bool` or `dynamic`.

**Comment by leafpetersen** [comment]
Ah, missed that, thanks.
