### ISSUE TITLE
Is it intended that patterns break complex constant cases?

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2408]
The following program is accepted by both the analyzer and the front end today, and prints `two`:
```dart
main() {
  switch(2) {
    case 1+1:
      print('two');
      break;
  }
}
```
According to my reading of the [patterns proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md), once patterns are enabled, this program will be rejected because the word `case` is required to be followed by a pattern, and although `1+1` is a valid constant, it's not a valid pattern (because constant patterns must be qualified names).

Is this an intentional breaking change?  If so, the patterns proposal should probably discuss it (similar to how it discusses that single identifiers are not allowed as a constant case pattern anymore, because of the ambiguity with variable patterns).  If not, we'll need to update the grammar in the spec to allow it.

**Comment by stereotype441** [comment]
CC @munificent @lrhn @leafpetersen @natebosch @jakemac53 @eernstg @mit-mit

**Comment by stereotype441** [comment]
FWIW, I personally think this breaking change is ok, especially considering that the feature is language-versioned (so we can still accept `case 1+1:` in older code).  I just want to make sure we're aware of the change, and that we document it so that we remember to test it.

**Comment by eernstg** [comment]
(Should I repeat my recommendation that we keep the old and the new syntax separate, rather than breaking the old one? ;-)

**Comment by munificent** [comment]
Wow, somehow I didn't even realize that arbitrary constant expressions were allowed there. I knew collection literals were allowed (though never used in the wild that I was able to find) but I didn't think about arithmetic.

Personally, I think it's OK to make the breaking change. I've never seen it used in the wild. If we do [relational patterns](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#relational-pattern), then it's an easy mechanical fix to put `==` before the expression and then it's fine.

**Comment by munificent** [comment]
> (Should I repeat my recommendation that we keep the old and the new syntax separate, rather than breaking the old one? ;-)

We could, but then the old syntax would be dead weight with the only reason it exists being backwards compatibility.

**Comment by eernstg** [comment]
> the old syntax would be dead weight

I'd think that we could preserve the guarantee that the old-style `switch` statement admits faster execution (anything other than linearly checking every case in the textual order, e.g., binary search or jump tables, dense or hashed). The new syntax yields (1) access to all the fancy new pattern matching features, and (2) commitment to a semantics which uses a textually ordered linear execution of all cases.

At the same time, we avoid the breakage associated with composite constant expressions.

**Comment by natebosch** [comment]
> At the same time, we avoid the breakage associated with composite constant expressions.

Is there a syntax where the old semantics could be expressed? Would it be feasible to write a `dart migrate` tool  that can reliably detect and upgrade impacted code without changing behavior?

**Comment by stereotype441** [comment]
> > At the same time, we avoid the breakage associated with composite constant expressions.
> 
> Is there a syntax where the old semantics could be expressed? Would it be feasible to write a `dart migrate` tool that can reliably detect and upgrade impacted code without changing behavior?

For the most part, yes, and it would be trivial: `case 1+1:` is equivalent to `case 2:`, for example.  Basically we would just have to run the constant evaluator and replace every complex case expression with the expression it evaluates to.  The process could be easily automated via `dart fix`, assuming we want to put the time into writing a lint and an analyzer quick fix.

The only circumstance I can think of where it gets tricky is if one of the subexpressions in the complex constant refers to a value imported via a conditional import.  In that case, the constant's value might depend on the compilation environment, so we can't just replace it with an equivalent simple constant.

Honestly, though, I don't think it's worth the development effort.  I suspect that these cases are going to be exceedingly rare.  If we do nothing, the worst that's going to happen is that a few users will get a compile-time error when they update their language version to turn on pattern support, and when that happens, they'll be able to edit `case <complexExpr>:` to either:
- `case == <complexExpr>:` (which is not 100% semantically equivalent, but probably good enough for most cases), or
- `case x where <complexExpr> == x:` (which is 100% semantically equivalent).

Note that both of these equivalent forms require pattern support to be enabled, so they're not something we can prepare for ahead of time with `dart fix`.

**Comment by lrhn** [comment]
As a (possibly horrible) idea, what if we introduced different *context kinds* that changes how a pattern is interpreted.

The `case` expression is in a `const` context. Any raw identifier is interpreted as a constant value. Any non-pattern expression is evaluated as a compile-time constant. (Meaning that `Foo(x: 1)` is a constant object creation, not an extractor pattern!)
The prefix `const pattern` can be used to put any pattern into a `const` context.

The `var p = e` puts `p` in a *declaration context*. Any raw identifier is a variable introduction, so `var (x, y)` is the same as `(var x, var y)`. The `var` or `final` prefixes can put any pattern into a declaration context (defaulting new variables to mutable or final, respectively).

A plain pattern assignment `p = e` is an *assignment context*. A raw identifier must be an existing variable. Expressions must  assignable expressions that you assign to (you can use `const e` if you want a constant to compare to).

If we do `on`-type patterns, they'd use a "type first" context where a raw identifier must refer to a type, so `on (int, int x)` would match the `int` type first. (I hope we can eventually do something like this, but it's non-trivial. Maybe `on type as declaration-pattern` is better.)


It looks horrible, everything depends on context and what variables actually refer to, the same code can mean different things in different contexts.
But it just might do exactly what people expect in each context, and will match existing syntax where it overlaps.

You can use `var`/`final`/`const` as override prefixes to get the interpretation you want, the only thing you can't ask for is assignment to existing variables, which is the default for `pattern = ...` checks, and not for any `case` checks or "if"-binding.

(Is `this.x` in a constructor parameter list really an assignment-pattern? :wink:)

**Comment by munificent** [comment]
I analyzed 94,249 switch cases in 18,672,247 lines of code in 102,015 files, including the 2,000 latest pub packages, a large corpus of open source Flutter applications, and the Dart and Flutter repos. Here's the results:

```
-- Cases (94249 total) --
  41152 ( 43.663%): prefixed identifier `foo.bar`                =======
  38499 ( 40.848%): string literal `"foo"`                       =======
   6886 (  7.306%): int literal `123`                            ==
   6058 (  6.428%): simple identifier `foo`                      =
   1113 (  1.181%): qualified prefixed identifier `foo.bar.baz`  =
    278 (  0.295%): negative int literal `-123`                  =
    110 (  0.117%): null literal `null`                          =
     70 (  0.074%): symbol literal `#foo`                        =
     55 (  0.058%): bool literal `true`                          =
     28 (  0.030%): ** other **                                  =
```

Most cases are literals or qualified constants whose behavior is unchanged by the proposal. There are a handful of simple identifiers that need to be changed to `== foo`. Most of those appear in a fairly small number of packages.

Here are *all* of the remaining cases, every single one:

-- Other (28 total) --
      4 ( 14.286%): const ConstClass(2)                           ===
      2 (  7.143%): A + A                                         ==
      2 (  7.143%): A + 'b'                                       ==
      2 (  7.143%): const ConstClass(1)                           ==
      2 (  7.143%): const ConstClass(3)                           ==
      2 (  7.143%): -ERR_LDS_ICAO_SIGNED_DATA_SIGNER_INFOS_EMPTY  ==
      1 (  3.571%): -sigkill                                      =
      1 (  3.571%): AsyncModifier.sync()                          =
      1 (  3.571%): AsyncModifier.async()                         =
      1 (  3.571%): AsyncModifier.syncStar()                      =
      1 (  3.571%): AsyncModifier.asyncStar()                     =
      1 (  3.571%): List<RPChoice>                                =
      1 (  3.571%): 720 * 1280                                    =
      1 (  3.571%): 1080 * 1920                                   =
      1 (  3.571%): 1440 * 2560                                   =
      1 (  3.571%): 2160 * 3840                                   =
      1 (  3.571%): _AdjustSliderIntent.right()                   =
      1 (  3.571%): _AdjustSliderIntent.left()                    =
      1 (  3.571%): _AdjustSliderIntent.up()                      =
      1 (  3.571%): _AdjustSliderIntent.down()                    =
```

Just a handful of const constructors, a couple of negated constants, and a few binary operators. So, yes, it is a breaking change in a small number of cases. Assuming we sort out #2378 in some reasonable way, it should be possible to migrate them mechanically to use `==` or some other syntax that we come up with that means "use primitive equality on the constant".

**Comment by munificent** [comment]
As part of 8a9b9a8a74a49e13c625e5208bab201d8a4f0e76, I clarified that, yes, some constant switch cases are broken. But also, it adds support for explicit `const <expr>` patterns to give us a way to migrate those cases to something non-broken.
