### ISSUE TITLE
Equality on enum implemented type

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/language#2414]
I've created a class that only takes `Enum`s as parameters. I figured I could create a third `Enum` where I would manually put every option so they have a better naming.

The only thing is, I can't test if both my third `Enum` constant and my class instance with the same parameters are equal just by using the `==` operator. Tried using [`equatable`](https://pub.dev/packages/equatable) and considering the `Enum` constant as my class instance since it does implement it, but nothing works. Of course, I could create a test where all my given parameters are equal, but I just wondered whether I could do something, that I'm missing, so they return `true` when using the `==` operator, or if this is not possible. If it isn't possible, why?

E.g.:

### Configuration
```dart
enum A {
  a,
  b;
}
enum B {
  c,
  d;
}

class Class with EquatableMixin {
  const EveryDayOfYear({required this.aValue, required this.bValue});

  final A aValue;
  final B bValue;
  
  @override
  List<Object?> get props => [aValue, bValue];
}

enum C {
  ac(Class(aValue: A.a, bValue: B.c)),
  ad(Class(aValue: A.a, bValue: B.d)),
  bc(Class(aValue: A.b, bValue: B.c)),
  bd(Class(aValue: A.b, bValue: B.d));

  const C(this._handler);

  final Class _handler;

  @override
  A get aValue => _handler.aValue;

  @override
  B get bValue => _handler.bValue;

  @override
  List<Object?> get props => [aValue, bValue];
}
```

### Objective

```dart
final instance = Class(aValue: A.a, bValue: B.c);
instance == C.ac; // I would like something so this operation returns true.
```

**Comment by Levi-Lesches** [comment]
Did you try adding an `==` operator to your `Class`? 
```dart
  @override
  bool operator ==(Object other) => other is Class
    && other.aValue == aValue
    && other.bValue == bValue;
```
This makes `instance == C.ac` return true. Note that `C.ac == instance` will never be true since you cannot implement your own `==` on an enum. Enums have their own notion of equality that you cannot override (I believe they check `identical()`).

**Comment by FMorschel** [comment]
This solved my problem and is fair since my class instance is not an `Enum`, but my enum value is actually my class value. I just wonder why this is not implemented by default, at least the `other is Class` in the `equatable` package. I'm going to look more deeply there. Thank you!

**Comment by Levi-Lesches** [comment]
> I just wonder why this is not implemented by default


I can't speak for `equatable`, but on the [Dart side](https://api.dart.dev/stable/2.17.6/dart-core/Object/operator_equals.html): 
> The default behavior for all [Object](https://api.dart.dev/stable/2.17.6/dart-core/Object-class.html)s is to return true if and only if this object and other are the same object.

This means that for a class `A` without an overridden `==` operator, `a == b` returns `identical(a, b)`: 
```dart
class A { }
void main() { 
  final a = A(), b = A();
  print(a == a);  // true
  print(a == b);  // false
  print(identical(a, a));  // true
  print(identical(a, b));  // false
}
```
