### ISSUE TITLE
`Mixin`s with `with` clauses

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/language#2417]
### Explanation
I'm trying to create an API for my future package and stumbled across a Dart feature. I'm trying to create a base class and three subclasses. All will be visible to the package user, but my three subclasses will automatically override two methods from the first. 

The thing is, I would like to create these overrides as a `Mixin`, so if my user only implements my subclass, they have a way of easily implementing this override.

Here it's an example of what I want to do:
```dart
abstract class A {
  void a();
}

abstract class B extends A {
  void b(String str);
  
  @override
  void a() => b('B');
}
```
But even more, I wanted anyone implementing B could automatically use something like `BMixin` to have the `a()` method override already implemented. The mixin would only be:
```dart
mixin BMixin on B {
  @override
  void a() => b('B');
}
```
### Objective
I want a way of creating this override just once and using it everywhere.

I've tried using `with` on a Mixin to try and solve that, tried creating a private subclass with the `b(String)` method and using this on my mixin and mixin it on a public class that implements that class and some other combinations of weird combinations of classes and mixins. And all of the attempts ended with error messages.

Is there any way of doing this in Dart? Should there be a way of doing this or am I trying to do/create something that is wrong in some aspect?

PS: I'm not really sure if I can do what I want, I'm sorry if I'm trobling you with something already solved.

**Comment by munificent** [comment]
What you probably want is:

```dart
abstract class A {
  void a();
}

mixin BMixin implements A {
  void b(String str);
  
  @override
  void a() => b('B');
}

class B extends A with M {}
```
