### ISSUE TITLE
How do switch statements handle variable patterns when multiple cases share a body?

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2419]
The current [pattern spec](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#logical-or-pattern) says:

> A logical-or pattern may match even if one of its branches does not. That means that any variables in the non-matching branch would not be initialized. To avoid problems stemming from that, the following restrictions apply:
>
> *   It is a compile-time error if one branch contains a variable pattern whose name or type does not exactly match a corresponding variable pattern in the other branch. These variable patterns can appear as subpatterns anywhere in each branch, but in total both branches must contain the same variables with the same types. This way, variables used inside the body covered by the pattern will always be initialized to a known type.
>
> *   If the left branch matches, the right branch is not evaluated. This determines *which* value the variable gets if both branches would have matched. In that case, it will always be the value from the left branch.

This is great.  But I'm surprised not to see similar text to cover the situation where multiple cases share a body, e.g.:

```dart
(int, String) rec = ...;
switch (rec) {
  case (0, x):
  case (x, ''):
    // What is the static type of `x`?
}
```

I propose that we apply the same rules to this situation, namely: when multiple cases share a body, it's a compile-time error if one case contains a variable pattern whose name or type does not exactly match a corresponding variable pattern in all other cases.

**Comment by stereotype441** [comment]
CC @munificent @lrhn @leafpetersen @kallentu @mit-mit @jakemac53 @natebosch @eernstg

**Comment by munificent** [comment]
It's [in there](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#variables-and-scope), but maybe not where you expect it. In the second on scoping, it says:

> However, it is a compile-time error if all switch case patterns that share a body do not all define the exact same variables with the exact same types.

If there's a better place for me to specify this, let me know and I'm happy to move it around.

**Comment by stereotype441** [comment]
> It's [in there](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#variables-and-scope), but maybe not where you expect it. In the section on scoping, it says:
> 
> > However, it is a compile-time error if all switch case patterns that share a body do not all define the exact same variables with the exact same types.
> 
> If there's a better place for me to specify this, re-open this and let me know and I'm happy to move it around.

Aha, thank you!  I thought it might be hiding somewhere else and searched around a bit, but I didn't manage to find it.  I don't have any recommendation of a better place to specify it, though; it's in a good place 😄
