### ISSUE TITLE
[Views] Write the spec

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/language#2420]

**Comment by nuritzi** [comment]
Per @eernstg in go/dart-feature-cheatsheet: the spec is still a WIP; the two current proposals are: [views](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification-views.md) and [extension structs](https://github.com/dart-lang/language/blob/master/working/extension_structs/overview.md) (We'll do one, or the other, or a combination)

**Comment by eernstg** [comment]
This feature is now known as 'inline classes'. The spec has been written, accepted by the language team, and can be found here: https://github.com/dart-lang/language/blob/master/accepted/future-releases/inline-classes/feature-specification.md.
