### ISSUE TITLE
Disallow !is

### ISSUE THREAD

**Issue by car-anubis** [dart-lang/language#2425]
Many dart developers also use Kotlin. In Kotlin this is possible:
```
if (obj is String) {
    print(obj.length)
}

if (obj !is String) { // same as !(obj is String)
    print("Not a String")
} else {
    print(obj.length)
}
```

So I went ahead and used this in Dart.
It took some time to figure out that for Dart following code:
`if (obj !is String)`
actually is not a negated type check but has to do with nullability, and is equal to:
`if (obj! is String)`
This should be disallowed as it can create confusion and introduce bugs.
The current warning
`Warning: Operand of null-aware operation '!' has type 'String' which excludes null.`
doesn't really warn the developer that this code doesn't do what he thinks it does.

**Comment by jakemac53** [comment]
Note that if you are using the formatter (`dart format`), it will also make this apparently by moving the `!` off of the `is` and next to the thing it is actually negating.

**Comment by srawlins** [comment]
The lint rule request is here: https://github.com/dart-lang/linter/issues/2995

I think this is a duplicate.
