### ISSUE TITLE
Do we support "named anywhere" for record literals?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2429]
I couldn't spot anything in the records feature spec, but it would make sense, just like parameter lists:

```dart
(int, int, {int a, int b}) record = (b: 1, 2, a: 3, 4); // OK?
```

**Comment by lrhn** [comment]
Sure, why not!

**Comment by munificent** [comment]
Yes, the proposal doesn't call it out explicitly, but I updated the grammar deliberately allow named arguments to be interleaved with positional ones. It says:

---

A record is created using a record expression, like the examples above. The grammar is:

```
literal      ::= record
               | // Existing literal productions...
record       ::= 'const'? '(' recordField ( ',' recordField )* ','? ')'
recordField  ::= (identifier ':' )? expression
```

This is identical to the grammar for a function call argument list (with an optional `const` at the beginning).

---

**Comment by eernstg** [comment]
Sounds like "yes".

@jakemac53, @kallentu, @stereotype441, @leafpetersen, @natebosch, WDYT?

**Comment by munificent** [comment]
Closing this because there is an answer, but I'm definitely happy to re-open and discuss more if language folks disagree. :)
