### ISSUE TITLE
Operator "self ternary" 

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/language#2440]
Mainly in Flutter, I find myself having some ternary operations that are a little verbose. Here is an example:
```dart
final value = 2.clamp(1, 3).isEven ? 2.clamp(1, 3) : 2;
```
As you can see here, the `2.clamp(1, 3)` is my main answer, but if some test fails I want to return the else option. This is all fine, but as soon as I need a result deeply nested inside my objects this gets way too big, and sometimes I have to come up with a name for that variable that is not a great name because and way up my file before my widgets actually start or even creating a `Builder` so the new variable is created near. 

So what I ended up creating was this:
```dart
dynamic selfTernary<P, S>(P self, bool Function(P self) test, S other) {
  if (test(self)) {
    return self;
  }
  return other;
}
```

So now I'm asking if there is any interest in trying to figure out an operator that solves this case

**Comment by lrhn** [comment]
The *general* solution is a local variable binding: `let v = 2.clamp(1, 3) in v.isEven ? v : 2`. That works for many more cases where you need two uses of the same value in the same expression.

(Possible shorthand, omit variable it defaults to `it`: `let 2.clamp(1,3) in it.isEven ? it : 2`. Or my personal preference for syntax: `(var v = 2.clamp(1, 3)).isEven ? v : 2`.)

This particular case is far too specialized for me, personally, to want to sacrifice precious syntax on it.

Here, you have a value, but want it conditionally, and if not, you want something else. I'd probably go with:
```dart
extension When<T extends Object> on T {
  T? when(bool Function(T) test) => test(this) ? this : null;
}
```
Then you can do:
```dart
  2.clamp(1, 3).when((x) => x.isEven) ?? 2  // Read: thing, when thing is even, otherwise 2
```
Doesn't work for nullable values, but 99.9% of the time, the `null` will be the "other case" anyway.

(Shorter function literal syntax would make it event shorter: `2.clamp(1, 3).when(=>it.isEven) ?? 2`. Neat!)

**Comment by FMorschel** [comment]
> ```dart
> extension When<T extends Object> on T {
>   T? when(bool Function(T) test) => test(this) ? this : null;
> }
> ```
> 
> Then you can do:
> 
> ```dart
>   2.clamp(1, 3).when((x) => x.isEven) ?? 2  // Read: thing, when thing is even, otherwise 2
> ```
> 
> Doesn't work for nullable values, but 99.9% of the time, the `null` will be the "other case" anyway.

Just as a side note: 

```dart
extension When<T extends Object?> on T {
  T? when(bool Function(T) test) => test(this) ? this : null;
}
```
This compiles, so if for some reason you want to test if your object is not null for example, you can create something like:
```dart
bool isNotNull(Object? obj)  => obj != null;
```
Then you can use both like:
```dart
int? nullableInt = 2;
nullableInt.clamp(1, 3).when(isNotNull) ?? 2;
```

**Comment by lrhn** [comment]
The problem with extending `when` to nullable types is that the result when calling it on `null` will be `null`, whether or not the test succeeds, so you don't actually get a way to *accept* `null` as a value. You're just as well off using the original declaration and `?.when(...)` to call the test, like `nullableInt?.clamp(1, 3)?.when((x) => x.isEven) ?? 2`.

**Comment by FMorschel** [comment]
After some time using this extension, I just wanted to update this so if anyone finds it they can have a better solution still. 

```dart
extension ObjectExtensions<T extends Object> on T {
  T? when(bool Function(T self) predicate, {T Function(T self)? otherwise}) {
    if (predicate(this)) return this;
    return otherwise?.call(this);
  }
}
```

So this way you could make something like this or even cascade it:

```dart
num? a;
a = a?.when((self) => self > 0, otherwise: (self) => self * 2) ?? 0;
```
