### ISSUE TITLE
Should empty list and map patterns be supported?

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2441]
The [patterns proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md) defines `listPattern` and `mapPattern` as non-empty:

> ```
> listPattern       ::= typeArguments? '[' patterns ']'
> patterns          ::= pattern ( ',' pattern )* ','?
> mapPattern        ::= typeArguments? '{' mapPatternEntries '}'
> mapPatternEntries ::= mapPatternEntry ( ',' mapPatternEntry )* ','?
> ```

Is this intentional?  Since the runtime semantics of both list and map patterns includes a length check, it seems like allowing empty list and map patterns could be useful.

If we do decide that we want to allow empty list and/or map patterns, we'll also need to specify their type schemas.  Currenly we specify that a list pattern without an explicit type gets its type schema from the GLB of the type schemas of all the element subpatterns; that doesn't work if there are no element subpatterns at all.  Empty map patterns have a similar problem.

**Comment by munificent** [comment]
Good catch!

**Comment by stereotype441** [comment]
@munificent what about this part?

> If we do decide that we want to allow empty list and/or map patterns, we'll also need to specify their type schemas. Currenly we specify that a list pattern without an explicit type gets its type schema from the GLB of the type schemas of all the element subpatterns; that doesn't work if there are no element subpatterns at all. Empty map patterns have a similar problem.

To clarify, the spec currently says:

> *   **List**: A context type schema `List<E>` where:
>
>     1.  If `p` has a type argument, then `E` is the type argument.
>
>     2.  Else `E` is the greatest lower bound of the type schemas of all element subpatterns. *We use the greatest lower bound to ensure that the outer collection type has a precise enough type to ensure that any typed field subpatterns do not need to downcast:*
>
>         ```dart
>         var [int a, num b] = [1, 2];
>         ```
>
>         *Here, the GLB of `int` and `num` is `int`, which ensures that neither
>         `int a` nor `num b` need to downcast their respective fields.*
>
> *   **Map**: A type schema `Map<K, V>` where:
>
>     1.  If `p` has type arguments then `K`, and `V` are those type arguments.
>
>     2.  Else `K` is the least upper bound of the types of all key expressions and `V` is the greatest lower bound of the context type schemas of all value subpatterns.

How do we interpret "greatest lower bound" of an empty set of types?  The "unknown type" (`?`) is one possible choice; `Object?` or `dynamic` might also be reasonable.

Similarly, how do we interpret "least upper bound" of an empty set of types?  Again, the unknown type is a possibility, or alternatively, `Never`.
