### ISSUE TITLE
[Patterns] Question about pattern variable declaration grammar

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#2446]
The proposal, under "Pattern variable declaration" says:

> It is a compile-time error if the outermost pattern in a `patternDeclaration` is not one of:
>
> * `groupingPattern`
> * `listPattern`
> * `mapPattern`
> * `recordPattern`
> * `extractorPattern`
> * `nullCheckPattern`

Would it be better to have a separate production for these six kinds of patterns and use it in the production for `patternDeclaration`? Doing so would mean that it was a syntactic error to use any other kind of pattern in that location making it possible for the parser to report the problem.

Later, in the same section, it says

> But excludes other kinds of patterns to prohibit weird code like:
>
> `// Not allowed:`
> ...
> `var (pointless) = 'parentheses';  // Grouping.`

Even though a grouping pattern is explicitly allowed above. Which is correct?

**Comment by bwilkerson** [comment]
@munificent

**Comment by munificent** [comment]
> Would it be better to have a separate production for these six kinds of patterns and use it in the production for `patternDeclaration`?

I thought about that, yes. I was worried it would get weird because I also use the grammar to control the precedence of the various pattern operators, but it looks like it mostly works out. I'll do that.
