### ISSUE TITLE
Support "..." in list and map patterns

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2453]
The patterns proposal has a TODO to allow `...` in list and map patterns. Currently, both patterns only match if the object has exactly the same length as the number of element/entry subpatterns. Adding `...` would loosen that to match if the object has *at least* that many elements/entries.

Also, `...` could have element patterns after it in a list pattern in order to extract trailing elements from the list while ignoring elements in the middle.

**Comment by lrhn** [comment]
Ship it!

We should be clear that the only effect of `...` is to change a `==` on a length check into a `>=`.
And that map patters really only read `length` and `[]`-values, it doesn't *understand* the map.
We won't actually check that, say, the keys of the map pattern are actually distinct. (Must map pattern keys have primitive equality? If not, we can't check them for being distinct, and even then, we don't know the equality used by the actual map.)

```dart
class AllTheSame {
  final int id;
  const AllTheSame(this.id);
  int get hashCode => 0;
  bool operator==(Object other) => other is AllTheSame;
}

void main() {
  switch ({const AllTheSame(1): 42, "anotherKey": 37}) {
     case const {AllTheSame(1): 42, AllTheSame(2): 42}: print("Yep");
  }
}
```
Here, we should print "Yep". And that's fine, as long as we tell people that they get precisely what they ask for.

**Comment by munificent** [comment]
Yeah, I think capturing the "rest" elements would be useful. (And would naturally extend to actual rest parameters if we ever add that feature.)

> We should probably keep our pattern as just accepting `List`s, and could choose to make `middle` an iterable instead, to avoid copying.

Even if we do that, we still have to specify *when* that iterable invokes `[]` on the underlying list object since that could be user-visible on custom implementation of `List`.
