### ISSUE TITLE
Short return or throw on nullable variables.

### ISSUE THREAD

**Issue by xanahopper** [dart-lang/language#2455]
## Description

After null-safety of Dart, we met lots of situations like this

```dart
class Person {
    String? name;
    
    void say() {
        final name = this.name;
        if (name == null) {
            return;
        }
        // do anything with local variable `name` as non-null variable
    }
}
```

But this is really verbose when going with many nullable variables. Here we can borrow some syntax from Kotlin like

```Kotlin
// in Kotlin
class Person {
    var name: String?
    
   fun say(word: String?) {
        val name = this.name ?: return
        val someWord = word ?: throw Exception()
        // do anything with local variable `name` and `someWord` as non-null variable
    }
}
```

for user and analyzer, this might be better and reduce verbose code.

**Comment by Levi-Lesches** [comment]
I believe this is a duplicate of https://github.com/dart-lang/language/issues/2025, which proposes
```dart
final name = this.name ?? return;
```

**Comment by xanahopper** [comment]
> I believe this is a duplicate of #2025, which proposes
> 
> ```dart
> final name = this.name ?? return;
> ```

got it, this is what I am looking for. I'll close this issue.
