### ISSUE TITLE
Do relational patterns/extractor patterns allow extension members

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2457]
A pattern like `Foo(bar: < 4)` reads a `bar` getter and calls a `<` operator on the result.

Can those be extension members.

Say:
```dart
class Foo {
  String _value;
  Foo(String value) : _value = value;
  String toString() => value;
}

extension on Foo {
  String get bar => this.toString();
}
extension on String {
  bool operator< (String other) => this.compareTo(other) < 0;
}

// ...

switch (foo) {
  case Foo(bar: < "abc"): ...
```

Will this code work?

(I'd hope so, if we consider pattern matching as mainly syntactic sugar, and desugaring it at the place of writing would call the extension members. I think we should make sure to say this explicitly in the specification.)

**Comment by munificent** [comment]
Yes, I think we should allow this. The proposal is agnostic/ambiguous on the point, but I'll clarify it.
