### ISSUE TITLE
Pattern type schemas don't work well in pattern-if

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2458]
This morning I was contemplating the following code:
```dart
f(List<String> strings) {
  if (var ['foo', int i] = [for (var string in strings) decode(string)]) {
    doStuff(i);
  }
}
Object? decode(String s) { ... }
```

The idea here is that we decode each string in `strings` to an `Object?`, then we put them in a list, and then we check whether the first element of that list is`'foo'` and the second element is an integer.  It's kind of contrived, but I could imagine things like this arising from deserialization, where the user knows what types they expect their data structure to be, and they're just using pattern-if to screen out the cases where the wrong type of data is present due to data corruption.

The problem is, this code has a compile error.  The first step in type inference of the pattern-if statement is to assign a type schema to `['foo', int i]`.  The type schema for a list is computed using the GLB of the type schemas of the sub-patterns, so we compute `GLB(String, int)`, which is `Never`, and we get a type schema of `List<Never>`.  We then analyze `[for (var v in strings) decode(string)]` with that type schema as its context.  Downwards inference infers a list element type of `Never`.  But `decode` returns an `Object?`, and `Object?` isn't assignable to `Never`, so we fail to compile.

At first I thought maybe the mistake was using GLB for list patterns, but using LUB doesn't help.  Then we would get a type schema of `List<Object>`, and since `Object?` isn't assignable to `Object`, that wouldn't work either.

I think the real problem is that we shouldn't be using the pattern type schema at all in pattern-if statements.  Here's my reasoning: a type schema of *T* is a way for a syntactic construct to communicate to one of its subexpressions "please try to have a static type of *T*, or a subtype of *T*".  But with pattern-if, there's no need for the scrutinee to have any particular static type.  In fact, that's kind of the whole point--we want to know at runtime whether the pattern matched, so we don't want the type system to constrain us, and force us into only using expressions that are guaranteed to match.

If we change the spec so that pattern type schemas aren't used in pattern-if, then a side benefit will be that type inference for pattern-if would work the same way as type inference for switch statements.  Another side benefit would be that pattern type schemas would only get used in irrefutable contexts, which would mean we wouldn't have to define the pattern type schema for logical-or, relational, null-check, literal, or constant patterns.  That would be nice because some of those definitions were hurting my brain*.

(*In particular, for literal and constant patterns we said that the pattern type schema was the static type of the pattern's constant value expression.  But then what should be used as the context for analyzing the constant value expression?  I want to use the matched type as the context, but that's a catch-22 because we don't know the matched type until after we've compute the pattern type schema.)

So my proposal would be:
1. Pattern type schemas are only defined for irrefutable patterns.
2. Remove the definition of type schema for logical-or, relational, null-check, literal, and constant patterns.
3. For pattern-if, the context type `?` is used to analyze the scrutinee (just like for switch statements).

**Comment by stereotype441** [comment]
CC @munificent @lrhn @leafpetersen @kallentu @mit-mit @jakemac53 @natebosch @eernstg

**Comment by mnordine** [comment]
I take it you meant:
```dart
if (var ['foo', int i] = [for (var string in strings) decode(string)]) {
```
?

**Comment by stereotype441** [comment]
> I take it you meant:
> 
> ```dart
> if (var ['foo', int i] = [for (var string in strings) decode(string)]) {
> ```
> 
> ?

Yes, thank you!  I've fixed the description text.

**Comment by munificent** [comment]
I think you're right. Calculating a context type schema for a refutable pattern seems like type system equivalent of begging the question.

It will be a little strange for a pattern-if pattern to not have a context type when a pattern variable declaration does since those two are *so* syntactically similar. Maybe that's a suggestion that the pattern-if syntax isn't ideal.

**Comment by munificent** [comment]
In 8a9b9a8a74a49e13c625e5208bab201d8a4f0e76, I changed the syntax back to a more explicitly refutable `if (<expr> case <pattern>)` syntax and also specified that no downwards context type schema from the pattern is applied to the expression.
