### ISSUE TITLE
Is there any way to control the ordering of destructuring.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2466]
We have patterns with side effects, specifically the `!` and `as SomeType` patterns.
The current specification does not specify the order that fields of a record pattern are checked in.

If I know I have a pair of values, where the value of the first element determines the type of the second, can I write it as:
```dart
switch (pair) {
  case ("s", s as String): ...
  case ("i", i as int): ...
  ...
}
```
That seems like the immediate approach that someone might try, but if we don't actually specify the ordering of the tests, it's possible for the pattern matching algorithm to test `s as String` first.

I believe the `as`-pattern is currently defined only applies to a simple variable pattern and only does the cast when binding, after successfully matching, and the cast pattern is irrefutable, but I believe the cast pattern might need to be more general. Also the null-assert  `!` pattern is not defined the same way, so
```dart
  case ("int", int x!): 
```
would be able to throw on the scrutinee `("string", "value")`, even though the tag wouldn't match anyway.

Do we want to ensure a predictable order of testing? (Probably source order for the pattern.)
Or should we specify that the order is *not* guaranteed?

(For a situation where you would want/need to do a cast *before* binding to a single variable, consider:
```dart
enum Kind { int, string, bool, point };
...
switch (taggedValue) {
  case (Kind.int, x as int): ...
  case (Kind.string, s as String): ...
  case (Kind.bool, b as bool):  ...
  case (Kind.point, (:x, :y) as (int, int)): ...
} // exhaustive!
```
Here we don't want to just do `(:int x, :int y)` for the second element of a `point`, because then it's refutable, and then the switch is not exhaustive. So, to ensure exhaustiveness, we want to *cast* the second field of the `taggedValue` to `(int, int)` *before* doing an irrefutable pattern match on the result.)

**Comment by munificent** [comment]
> The current specification does not specify the order that fields of a record pattern are checked in.

It does for record patterns, actually, but not for maps and extractors. I'll fix the latter.

> Do we want to ensure a predictable order of testing? (Probably source order for the pattern.)

Yes, I think so.
