### ISSUE TITLE
Language Specification (PDF) - Off Margin Text

### ISSUE THREAD

**Issue by OsaXma** [dart-lang/language#247]
Off margin text in the following pages:
[57](https://www.dartlang.org/guides/language/specifications/DartLangSpec-v2.2.pdf#57) (shown below)
[187](https://www.dartlang.org/guides/language/specifications/DartLangSpec-v2.2.pdf#187) (bottom line)
[189](https://www.dartlang.org/guides/language/specifications/DartLangSpec-v2.2.pdf#189) (last line @ first paragraph)

![screen shot 2019-02-26 at 5 42 06 pm](https://user-images.githubusercontent.com/46427323/53455163-2c9d8b00-39ef-11e9-95fd-bfb38a47ee7c.png)

**Comment by OsaXma** [comment]
Noticed this left off margin as well in page 6 & 7:

![screen shot 2019-02-26 at 6 19 43 pm](https://user-images.githubusercontent.com/46427323/53456244-42ad4a80-39f3-11e9-979f-024c53b6a4c9.png)

**Comment by eernstg** [comment]
Thanks! We are aware that there are many `Overfull \hbox` warnings (and it doesn't actually ), but these ones are huge. Handled in https://github.com/dart-lang/language/pull/248.

For the left margin issue on page 6-7: The text has been formatted like that for years, I think I'll decide that `\begin{itemize}\item[Something] Some things about something.\end{itemize}` is supposed to look like that. ;-)

**Comment by eernstg** [comment]
Closing: Said PR landed as 9cc8d534dc295cec8876f7425c0879943a664089.
