### ISSUE TITLE
Replace storage of augmented variable

### ISSUE THREAD

**Issue by blaugold** [dart-lang/language#2470]
I'm wondering if the following will possible with macros and augmentation libraries:

```dart
class A {
  @valueNotifier var b = 0;
}

// Code generated by macro
class A {
  final _b = ValueNotifier<int>(<?? initialzer of b ??>);
  augment int get b => _b.value;
  augment set b(int value) => _b.value = value;
}
```

The example does not make much sense on its own, but it demonstrates the case where the storage of a variable is outside of the object.

**Comment by Levi-Lesches** [comment]
I imagine it would be better to write: 
```dart
class A { 
  @notifier
  final _b = ValueNotifier<int>(0);
}

// which generates: 
augment class A { 
  int get b => _b.value;
  set b(int value) => _b.value = value;
}
```

That way the macro doesn't have to "make up" a) the default value and b) the type of `Listenable` (since there is `ValueNotifier`, `ChangeNotifier`, and more).

**Comment by blaugold** [comment]
@Levi-Lesches Yeah, that would work for that specific example, but not in general. With that approach, the macro cannot make `ValueNotifier` an implementation detail. Also, what if the variable is not stored in a specific object but some backing collection?

**Comment by Levi-Lesches** [comment]
> Yeah, that would work for that specific example, but not in general. With that approach, the macro cannot make `ValueNotifier` an implementation detail.

I'd argue the other way around -- that choosing which type of `Listenable` you want to use is an important detail that _shouldn't_ be automatically chosen. So long as you declare it private, `_b` is an implementation detail to your API. 


> Also, what if the variable is not stored in a specific object but some backing collection?

Again, all the more reason to initialize your variable by hand and write the convenient getters with a macro. Or maybe I'm misunderstanding your point here.

**Comment by blaugold** [comment]
Maybe this is a clearer example of what I'm trying to get at:

```dart
import 'dart:html';

@storeInLocalStorage var a = 'b';

// Generated code
augment String get a => window.localStorage['a'] ??= <?? initialzer of a ??>;
augment set a(String value) => window.localStorage['a'] = value;
```

**Comment by jakemac53** [comment]
https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md#augmenting-variables-getter-and-setters i think answers your questions here (see "augmenting with a getter" and "augmenting with a setter").

**Comment by blaugold** [comment]
>  i think answers your questions here (see "augmenting with a getter" and "augmenting with a setter").

I was reading that section of the spec and to me, it looked like it won't be possible to do what I would like to do, which is why I opened this issue.

Regarding the example in https://github.com/dart-lang/language/issues/2470#issuecomment-1241653151: I could use `augment super` where I used a placeholder (`<?? initialzer of a ??>`). The reason, I'm looking for a way to invoke the initializer expression of the augmented variable from the augmentation library is to avoid incurring a global variable or an instance field that is only ever accessed once. But maybe the compiler would optimize such a field out?

**Comment by jakemac53** [comment]
You can only access the original initializer using `augment super` inside an augmenting initializer as stated in that section, there is no other way to access it.

Originally the macro proposal did allow you to get a code object for that initializer which you could then re-use elsewhere (basically allowed you to copy it), but we removed that due to implementation concerns.

**Comment by blaugold** [comment]
Got it. Thanks for clearing it up @jakemac53!
