### ISSUE TITLE
Loosen the restriction on variables declared in case patterns that share a body

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2473]
When refactoring dart_style to try out some pattern syntax, I ran into this example:

```dart
switch (expression) {
  case NamedExpression(:var expression)
      when _isBlockFunction(expression):
    return true;

  case MethodInvocation(:var target, argumentList: [var arg])
      when _isValidWrappingTarget(target) && _isBlockFunction(arg):
    return true;

  case InstanceCreationExpression(argumentList: [var arg]):
      when _isBlockFunction(arg);
    return true;

  case FunctionExpressionInvocation(:var function, [_, ...])
      when _isBlockFunction(function):
    return true;

  case ParenthesizedExpression(:var expression)
      when _isBlockFunction(expression):
    return true;

  case FunctionExpression(body: BlockFunctionBody(:var block))
      when block.statements.isNotEmpty ||
          block.rightBracket.precedingComments != null:
    return true;

  default:
    return false;
}
```

Note that all of the cases have the same body. It would be nice to rely on fallthrough to let them actually just share one body:

```dart
switch (expression) {
  case NamedExpression(:var expression)
      when _isBlockFunction(expression):
  case MethodInvocation(:var target, argumentList: [var arg])
      when _isValidWrappingTarget(target) && _isBlockFunction(arg):
  case InstanceCreationExpression(argumentList: [var arg]):
      when _isBlockFunction(arg);
  case FunctionExpressionInvocation(:var function, [_, ...])
      when _isBlockFunction(function):
  case ParenthesizedExpression(:var expression)
      when _isBlockFunction(expression):
  case FunctionExpression(body: BlockFunctionBody(:var block))
      when block.statements.isNotEmpty ||
          block.rightBracket.precedingComments != null:
    return true;

  default:
    return false;
}
```

This is much shorter and there's nothing problematic about the code. But it violates the current proposal because some of those cases do bind variables that others don't. It's not a problem because the variables only end up being used in their respective guard clause.

I think we should allow code like this. To enable that, I suggest that we loosen the rule to say that it's it's a compile-time error if a variable *used inside a case body* is not declared by all case patterns with the same type. If the variable isn't used in the case body, it's fine if not all cases define it or it has different types in each.

Thoughts?

**Comment by leafpetersen** [comment]
As an aside, are the cases there overlapping?  Otherwise why not:
```dart
return switch (expression) {
  case NamedExpression(:var expression): _isBlockFunction(expression);
  case MethodInvocation(:var target, argumentList: [var arg]): _isValidWrappingTarget(target) && _isBlockFunction(arg);
  case InstanceCreationExpression(argumentList: [var arg]): _isBlockFunction(arg);
  case FunctionExpressionInvocation(:var function, [_, ...]) : _isBlockFunction(function);
  case ParenthesizedExpression(:var expression): _isBlockFunction(expression):
  case FunctionExpression(body: BlockFunctionBody(:var block)): block.statements.isNotEmpty ||
          block.rightBracket.precedingComments != null;
  default: false;
}
```

But to the general question, I think this seems reasonable.

**Comment by leafpetersen** [comment]
Corner case to consider/test for:

```dart
int x = 3;
void test(...) {
  switch(...) {
     case A():
     case B(:int x):
        print(x);
   }
}
```

**Comment by munificent** [comment]
> As an aside, are the cases there overlapping? Otherwise why not:

I make no claims that my temporary refactoring is optimal or good style. :)

**Comment by lrhn** [comment]
I do want the ability to have variables bound just for the `when` clause, without it getting in the way of writing a good switch.

So, when you have multiple `case casehead`s for the same body `:statement`/`=>expression`, then 
* All variable names declared by any casehead is in the lexical scope. (This blocks the outer lexical scope.)
* It's a compile-time error for the body to refer to a variable name which is declared by some, but not all, of the caseheads.
* It's a compile-time error for the body to refer to a variable name which is declared by all of the caseheads, but where the declared variables do not have the same *declared* type. (Can also use LUB of types for final variables, or LUB for read and GLB for write, but let's just make it a conflict error). 
* If some or all the caseheads promote their declared variables, we join promotions like we normally do at join points.
* It's a compile-time error for the body to assign to a variable name which is declared `final` by any of the caseheads. _(We could require them all to agree on `var` vs. `final`, but we can also just pick the strictest restriction.)_
* At runtime, the variable reference in the body refers to the variable declared by the matching casehead. (The runtime scope depends on control flow. That's very weird, but we already do so for `for(;;)` loops. Still weird.)
* A `default:` or `label:` counts as a casehead declaring no variables.

Basically, the body cannot access pattern-bound variables if there are multiple entry-paths to the body, but we make an exception if *all* the patterns declare variables with the *same* type. We join promotion like we'd normally do at join-points. If all the variables are writable, we even allow writing to it.
The tricky part is that the *actual* variables accessible to the body at runtime depends on the path taken. 

For a single case-head, this reduces to allowing access to all variables.

```dart
late int Function() n1;
late int Function() n2;
switch ((1, 5)) {
  case (int a, int b) when (n1 = () => a++) == 0:   // Capture this a
  case (int a, int b) when (n2 = () => b++) == 0:  // Capture this b
  case (int a, int b):   // Capture new a and b variables. All `a` and `b` variables visible.
    print(a);  // 1
    print(b);  // 5
    print(n1());  // 1
    print(n2());  // 5
    print(n1());  // 2
    print(n2());  // 6
    print(a);  // 1
    print(b);  // 5
}
```
    
Another, complicated, alternative would be to define "private" variables, `var _a`, in casehead patterns to only be visible in the `when` clause, but not in the body, and then require that all the caseheads agree completely on the public variables.
