### ISSUE TITLE
[records] Do we have `(e,)` after all?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2479]
The record proposal used to include support for a record literal with one positional field, like `(1,)`.  It was presumably removed in version 1.4, cf. https://github.com/dart-lang/language/blob/master/working/0546-patterns/records-feature-specification.md#14.

However, the [grammar](https://github.com/dart-lang/language/blob/master/working/0546-patterns/records-feature-specification.md#record-expressions) still allows `(1,)` to be derived (and even mentions it in an example), and as far as I can see it is not stated anywhere that it is a compile-time error to have such record literals.

@munificent, WDYT, did I misread that version history item?

**Comment by leafpetersen** [comment]
I think this was re-added in 1.6?  
```
 Support empty and one-positional-field records (#2386).
```

**Comment by eernstg** [comment]
Right, I missed that! So we do have the '(e,)' syntax and the `Record.empty` constant to cover those two kinds of records.
