### ISSUE TITLE
[Patterns] Should we allow matching on final variables?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#2484]
With the current patterns specification, a bare identifier in a refutable context is interpreted as a reference to a named constant.  Should we generalize this to allow referencing final variables?

```dart
final int x = 4;
switch (...) {
  case (x, x): ...
   default: ...
}
```
cc @munificent @lrhn @eernstg @stereotype441 @natebosch @jakemac53 @kallentu

**Comment by munificent** [comment]
Good question. I think we could generalize constant patterns to become expression patterns (much like we could generalize default values to allow non-const expressions). I think what you're asking here is a special case of that general suggestion which @lrhn filed as #1406. I'll close this as a duplicate and we can talk about it there.

**Comment by leafpetersen** [comment]
Ok.  I'll note though that this one probably just falls out (it's a restriction, that could just be elided) whereas I think the more general thing will be very hard to fit into the grammar unless you delimit it.

**Comment by leafpetersen** [comment]
Also... I'm not actually sure what is being proposed in #1406?
