### ISSUE TITLE
Typo: Wrong form for indefinite article before "Extension"

### ISSUE THREAD

**Issue by jmewes** [dart-lang/language#2495]
## Observed result

Before the noun "Extension", different forms are used for the indefinite article "a" / "an".

![Selection_078](https://user-images.githubusercontent.com/5235584/190556884-cd54763a-ce4f-4790-a85d-b29c865017dc.png)

## Expected result

Before nouns beginning with a vowel, the "an" form should be used as indefinite article, i.e. "an Extension".

## Steps to reproduce

See 

- https://github.com/dart-lang/language/blob/a3b45ab2bc4e2442c909252858119ffd2e8c685a/specification/dartLangSpec.tex#L5801
- https://github.com/dart-lang/language/blob/a3b45ab2bc4e2442c909252858119ffd2e8c685a/specification/dartLangSpec.tex#L6095

## References

- https://owl.purdue.edu/owl/general_writing/grammar/using_articles.html

**Comment by eernstg** [comment]
Thanks, @jmewes!
