### ISSUE TITLE
`bool Function(...)` tear-off could accept the `!` operator in front

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/language#2505]
I've recently run into a project where I had a list of objects and wanted to test and process them using the `Iterable.*where*` / `Iterable.*when*` / `Iterable.*while*` methods. So I've created a function where it received a `bool Function(MyClass element) test` parameter. 

In some places, I would use the positive results of this test, so I could easily do `iterable.*where*(test)` but in other places I would use the negative results, so I would need to write `iterable.*where*((e) => !test(e))`.

This made me wonder whether `iterable.*where*(!test)` should exist.

**Comment by mraleph** [comment]
As an option (if you really find yourself writing this code a lot) you could just use higher order function:

```dart
bool Function(E) not<E>(bool Function(E) predicate) {
  return (e) => !predicate(e);
}

iterable.where(not(test));
```

**Comment by lrhn** [comment]
Or
```dart
extension NegFunc<P> on bool Function(P) {
  bool Function(P) get not => (P value) => !this(value);
}
```
so you can do:
```
iterable.where(test.not)
```

I actually think `whereNot` should be a method on `Iterable`. We failed to add it for Dart 2.0, and we're unlikely to change the interface now, so we instead added it as [an extension method](https://pub.dev/documentation/collection/latest/collection/IterableExtension/whereNot.html) instead, in `package:collection`.

There is no corresponding `takeWhileNot`/`skipWhileNot`. There probably could be.

**Comment by FMorschel** [comment]
> Or
> 
> ```dart
> extension NegFunc<P> on bool Function(P) {
>   bool Function(P) get not => (P value) => !this(value);
> }
> ```
> 
> so you can do:
> 
> ```
> iterable.where(test.not)
> ```
I like the idea but the reading is a bit odd compared to `iterable.where(not(test));` imo.
> I actually think `whereNot` should be a method on `Iterable`. We failed to add it for Dart 2.0, and we're unlikely to change the interface now, so we instead added it as [an extension method](https://pub.dev/documentation/collection/latest/collection/IterableExtension/whereNot.html) instead, in `package:collection`.
> 
> There is no corresponding `takeWhileNot`/`skipWhileNot`. There probably could be.

I really like this option, I think I'm going to be using this.

**Comment by mateusfccp** [comment]
> We failed to add it for Dart 2.0, and we're unlikely to change the interface now, so we instead added it as [an extension method](https://pub.dev/documentation/collection/latest/collection/IterableExtension/whereNot.html) instead, in `package:collection`.

@lrhn Isn't it non-breaking to add a method to an interface?
