### ISSUE TITLE
Record type grammar: Small fixes

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2511]
In the [feature specification of records](https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md), I believe that the alternative `recordType` in the grammar rule for `type` should be removed. It is redundant, because `type` derives `typeNotFunction`, and `typeNotFunction` already derives `recordType`.

**Comment by eernstg** [comment]
I think the `typeNotFunction` rule alternative `recordType` should be able to be nullable:

```
typeNotFunction
    :    typeNotVoidNotFunction
    |    recordType '?'?
    |    VOID
    ;
```

**Comment by munificent** [comment]
Thanks for pointing these out! Grammar is hard.

**Comment by eernstg** [comment]
Thanks! I'm still trying to understand why the spec parser fails on basically every test with these new rules. That'll be tomorrow. ;-)
