### ISSUE TITLE
[records] Grammar issues

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2515]
Follow-up on https://github.com/dart-lang/language/issues/2511: The Dart.g in https://dart-review.googlesource.com/c/sdk/+/260821 is now able to parse all records related tests as expected (parse failures appear to be actual syntax errors), so it should be possible to compare the change to Dart.g and the change specified for the Records feature and see if there are any surprises.

The only non-typo change that I had to perform to make it all work after #2511 was adding `recordType '?'?` to the rule `typeNotVoid`:

```
typeNotVoid
    :    functionType '?'?
    |    recordType '?'?
    |    typeNotVoidNotFunction
    ;
```

We used to have an alternative for `recordType` in `type`, and this is very similar. But the one in `type` introduced an ambiguity, and this one does not, it covers exactly the cases that were missing when we removed the alternative from `type`.

**Comment by munificent** [comment]
Thanks for catching that! I deliberately omitted record types from that rule to syntactically prohibit record types from appearing in `extends`, `implements`, `with`, and `on` clauses. But that also incorrectly prohibits them from appearing in `is` and `as` expressions. And, also, the syntactic restriction isn't sufficient to prevent extending or implementing record types thanks to type aliases, so clarified that too.

**Comment by eernstg** [comment]
The `extends`, `implements`, `with` and `on` clauses (of classes/mixins, not try/catch) actually use `typeNotVoidNotFunction`, so they still can't have a record type. The `on` clause of a try/catch statement uses `typeNotVoid` so it _can_ have a record type, as it should. I think this will work. Thanks!
