### ISSUE TITLE
Why does dart use certain methods if for loops are encouraged?

### ISSUE THREAD

**Issue by dumdumboi111** [dart-lang/language#2521]
I originally posted this question on

https://stackoverflow.com/questions/73842666/converting-a-list-to-a-map-why-does-dart-ask-you-not-to-use-the-map-fromiterabl/73842739?noredirect=1#comment130388825_73842739

And one of the posters asked me to post the same here.

So my question is why does dart prefers for loops, whats the point of having methods like Map.fromIterable if dart don't want you using them.

**Comment by TimWhiting** [comment]
`Map.fromIterable` existed before the collection elements feature existed. Removing it now would be a breaking change. The warning comes from a lint and not from the language. It's a style preference.

**Comment by lrhn** [comment]
Yep, that's the answer. If we had had the `for`-element syntax first, we never would have added `Map.fromIterable`.
