### ISSUE TITLE
Same object reference shorthand syntactic sugar

### ISSUE THREAD

**Issue by noga-dev** [dart-lang/language#2527]
Instead of being forced to write something like this:
```dart
if (x == 'a' || x == 'b' || ...) {
  ...
}
```
Would be great to be able to simply do this:
```dart
if (x == 'a' ||| 'b' ||| ...) {
  ...
}
```
Or:
```dart
if (x === 'a', 'b', ...) {
  ...
}
```
The new operators are just brainstorming.

Additionally, I'd opt to drop the redundant parenthesis altogether to make it more like Golang (or at least make them optional):
```dart
if x == 'a' ||| 'b' ||| ... {
  ...
}
```

**Comment by noga-dev** [comment]
I should note that my current workaround for this is to do something like this:
```dart
if (['a', 'b', ...].contains(x)) {
  ...
}
```
But I'd prefer the syntactic sugar.

**Comment by munificent** [comment]
With the current [patterns proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md), you could use a pattern in an `if-case` statement like so:

```dart
if (x case 'a' | 'b' | ...) {
  ...
}
```

**Comment by noga-dev** [comment]
> With the current [patterns proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md), you could use a pattern in an `if-case` statement like so:
> 
> ```dart
> if (x case 'a' | 'b' | ...) {
>   ...
> }
> ```

Perfect. Then I'll go upvote that proposal and close this issue. Thanks!
