### ISSUE TITLE
Implementing typed tables

### ISSUE THREAD

**Issue by FredslundMagnus** [dart-lang/language#2531]
I want to create a statically typed table as exemplified below:
```dart
InfoTable3<DateTime, double, SomeEnum, Data>(
      columns: InfoColumns3<DateTime, double, SomeEnum>(
        InfoColumn("Date", toWidget: (DateTime date) => Text(date.someFormat())),
        InfoColumn("Amount", toWidget: (double amount) => CoolWidget(amount)),
        InfoColumn("Type", sort: (SomeEnum a, SomeEnum b) => someSort(a, b),
      ),
      rows: listOfData.map(
        (data) => InfoRow3<DateTime, double, SomeEnum, Data>(
          InfoCell(data.date),
          InfoCell(data.amount),
          InfoCell(data.type),
          data: data,
        ),
      ),
    );
  }
```
I want it to be statically typed, and i want the i'th column have the same generic type as the i´th cell in a row, such that i can perform actions on a full column like formating, sorting, etc...

However in order to type this I need to create new InfoTableN, InfoColumsN and InfoRowN, for all needed N, which leads to a lot of repetition. I know that with Records, (when they arrive), I can get rid of InfoColumsN and InfoRowN, but not InfoTableN, something like below, (I am not sure about the Records syntax, but it should be understandable):

```dart
InfoTable3<DateTime, double, SomeEnum, Data>(
      columns: Record<InfoColumn<DateTime>, InfoColumn<double>, InfoColumn<SomeEnum>>(
        InfoColumn("Date", toWidget: (DateTime date) => Text(date.someFormat())),
        InfoColumn("Amount", toWidget: (double amount) => CoolWidget(amount)),
        InfoColumn("Type", sort: (SomeEnum a, SomeEnum b) => someSort(a, b),
      ),
      rows: listOfData.map(
        (data) => Record<InfoCell<DateTime>, InfoCell<double>, InfoCell<SomeEnum>, data: Data>(
          InfoCell(data.time),
          InfoCell(data.amount),
          InfoCell(data.type),
          data: data,
        ),
      ),
    );
  }
```

Just to make it a bit easier to read, without explicitly stating all the types, however they would be inferred correctly :

```dart
InfoTable3(
      columns: (
        InfoColumn("Date", toWidget: (date) => Text(date.someFormat())),
        InfoColumn("Amount", toWidget: (amount) => CoolWidget(amount)),
        InfoColumn("Type", sort: (a, b) => someSort(a, b),
      ),
      rows: listOfData.map(
        (data) => (
          InfoCell(data.time),
          InfoCell(data.amount),
          InfoCell(data.type),
          data: data,
        ),
      ),
    );
  }
```
This is a lot cleaner but I still have the problem with InfoTableN, since there will be more generic types as i add a column. So I need to implement a new table for each N. Just a simple implementation of InfoTable3, however it will get more complicated when adding more attributes to the table, which the have to be added to all InfoTableN.

```dart
class InfoTable3<C1, C2, C3, D> extends StatelessWidget {
    InfoTable3({required this.columns, required this.rows});
    final Record<InfoColumn<C1>, InfoColumn<C2>, InfoColumn<C3>> columns;
    final Iterable<Record<InfoCell<C1>, InfoCell<C2>, InfoCell<C3>, data: D>> rows;
    ...
}
```

**Comment by munificent** [comment]
Yes, as you state records will help for the rows and columns, but not for the table. I think what you're really asking for here is variadic generics, so I'll close this issue in favor of that one.
