### ISSUE TITLE
Patterns spec needs to specify an error for mismatch of "finality" within a pattern that declares variables:

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2533]
There's nothing in the spec preventing this:

```dart
switch (...) {
  case (var x | final x): ...
}
```
We need some kind of compile-time error here, otherwise it's not clear whether the variable should be final or not.

**Comment by munificent** [comment]
I think the PR out for clarifying scoping and finality [covers this case too](https://github.com/dart-lang/language/pull/2543/files#diff-4f7dd83d44f89cec4e2925d0288980ea778d3c607af5a862d9ee38938f0ea4afR1763).
