### ISSUE TITLE
Named constructors and super parameter forwarding

### ISSUE THREAD

**Issue by nullbtb** [dart-lang/language#2544]
Hi there! 

Since we have super parameter forwarding for unnamed constructors (2.17), can we also have it for named constructors?  I'm getting an error when I try to do the following:

```
class A {
  final int x;
  final int y;
  A(this.x, this.y);

  A.fromC(C c)
      : x = c.x,
        y = c.y;
}

class B extends A {
  B(super.x, super.y);

  // This is the requested feature.  It's marked as error, it's assuming I want to invoke the unnamed constructor of A.
  B.fromC(super.c); 
}

class C {
  final int x;
  final int y;
  C(this.x, this.y);
}
```

**Comment by mmcdon20** [comment]
This is already possible, but you have to specify the desired super constructor in the initializer list.

```dart
class B extends A {
  B(super.x, super.y);

  // specify the desired super constructor in the initializer list
  B.fromC(super.c): super.fromC(); 
}
```

**Comment by nullbtb** [comment]
> This is already possible, but you have to specify the desired super constructor in the initializer list.
> 
> 
> 
> ```dart
> 
> class B extends A {
> 
>   B(super.x, super.y);
> 
> 
> 
>   // specify the desired super constructor in the initializer list
> 
>   B.fromC(super.c): super.fromC(); 
> 
> }
> 
> ```

Thanks this makes sense and addresses my primary concern.  However for consistency I thought it may be cleaner to not have to add the ': super.fromC()' part since it's not required to add ': super()' with unnamed constructors using super parameters.

**Comment by lrhn** [comment]
Dart currently forwards to the unnamed constructor by default if you don't write a super-invocation explicitly. It does so for named constructors too, so `C.foo();` is equivalent to `C.foo(): super();`.

Changing that behavior when you add a `super` parameter would probably have been too confusing, so the default super-constructor is still always the unnamed one, and you have to write the name if you want a different one.
