### ISSUE TITLE
View constructors, discussion.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2558]
As currently specified, a `view class` can declare constructors initializing the single final field.

Constructors come in a number of different shapes:
* non-redirecting (initializing) generative constructor (the actual constructor which initializes a new object).
* redirecting generative constructor (must redirect to another generative constructor of the same class, with a new argument list).
* redirecting factory constructor (must redirect to a constructor of the same class or a subtype class with the same argument list).
* non-redirecting factory constructor (a static function, basically).
* `const` non-redirecting generative constructor (must have potentially constant initializer list and no body).
* `const` redirecting generative constructor (must redirect to const generative constructor, and new arguments list must be potentially constant expressions).
* `const` redirecting factory constructor (must redirect to const constructor).

Each constructor can also be named or "unnamed".

_There is no constant non-redirecting factory constructor, the eight corner of the {generative,factory}&times{redirecting,}&times;{`const`,}` cube, since such a constructor must have a body, and we haven't found a good way to restrict that body to something that is both evaluatable at compile-time, and which is still useful. (`=> potentiallyConstantExpression` could be computable, but it's very hard to make that create a new value of a user type, and equally hard to look up an existing value, so it's too limited to make sense.)_

The current `view` specification does not preclude any of the constructors. (It doesn't mention `const` about constructors with a word, so it doesn't preclude them.)

_The first question is whether all of these constructors make sense for a view?_
(The likely answer is "yes, yes they do!", but let's just make sure.)

_The second question is how these interact with the primary constructor notation? (Mainly, can it be `const`?)_

_Third question is whether a view can have *zero* constructors?_

_Fourth question is how we call super-view constructors (if at all)._

But first, the zeroth question: Why have constructors at all?

You can always cast a representation value directly to the view type, `repValue as ViewType`, without going through any constructor, so what is the purpose of having constructors. (A cast can even be a constant expression if the view type is constant0

The answers are:
* Readability
* Convenience
* Safety

Safety first: A cast `someExpression as ViewType` doesn't statically check whether the type of `someExpression` is likely to be admissible as the representation type of the view type. It's entirely a runtime check. Hopefully compilers will omit the ruintime check if the static type of the expression is guaranteed to satisfy the view type, but that presumes that you haven't made any mistakes in the typing, and you won't get any static warning if you did. Using `ViewType(expression)` does static type checking, and potentially inference of type arguments. You get none of that with `as`.

Readability: An `as` is used for many other things, so it's not easy to see whether `e as ViewType` is meant as a check or a value creation. Using `ViewType(e)` makes it clear that something of the view type is being created.

Convenience: You can have constructors which take arguments other than just the representation type.
Take this point view:
```dart
view class Point {
  final (int, int) coordinates;
  const Point.from(this.coordinates);
  const Point(int x, int y) : coordinates = (x, y);
  int get x => coordinates.$0;
  int get y => coordinates.$0; 
}
```
This is, I believe, a typical example of a view class: It wraps an existing type (a plain tuple) and provides named access to properties of that type. The unnamed constructor is for convenience, to allow you to write things like:
```dart
var points = [Point(1, 2), Point(0, 0)];
```
instead of the much less readable and writable
```dart
var points = [Point((1, 2)), Point((0, 0))];
```
that would be what we had with only a single primary constructor of `view class Point((int, int) coordinates) {...}`.

Multiple constructors gives you different ways to enter the view type.

So, constructors do make sense.

## Do all the constructors work for views?

I'd say yes. There is nothing in the behavior of a constructor for a class with a single field, which cannot be applied to views.

A *non-redirecting generative constructor* must initialize the field. As long as it does that, all is well. There is no problem with being `const`, it means you can use view-typed objects as, say, default values for view-typed parameters, or as values in constant collections. (You don't have to for the latter, you can use the representation type instead, and cast the collection afterwards, but it looks better to create the values in-line.)

A redirecting generative constructor should just work, it redirects to a constructor which work.

The slightly weird one is the redirecting factory constructor (`const` or not), because it's usually used to create an instance of a *subclass*, but since the result has the supertype as static type, that won't make sense for views. It can also be used to redirect to the same class/view, and avoid writing an argument list, but that only makes sense if the view has another constructor which accepts the same argument list, so why have two? (But it could be forwarding to a private constructor with a more general parameter list, which can be shared by multiple public constructors. A little speculative, but not impossible.)
There is no *problem* with allowing redirecting factory constructors, but most likely no practical use-case for them either. (And the analyzer may want to give a warning if you redirect to a sub-view, unless the sub-view constructor is non-trivial, because then it's completely unnecessary.)

The non-`const` factory constructor is just a static method which has to return something with the static type of the `view`.

All in all, I see no problems at all.

## How does this interact with primary constructor syntax?

The primary constructor syntax, `view class Name(type id)` implicitly declares an unnamed non-redirecting generative constructor and a final field, as if you had written:
```dart
  final type id;
  Name(this.id);
```

That works very well for views, which often need nothing but a single final field and a simple initializing constructor.

Does the primary constructor syntax extend to declaring:
* a named constructor?
* a `const` constructor?

(Not going to ask about redirecting or factory, those are not really options for a primary constructor.)

Currently the answer is "no" to both.
We can consider extending the syntax to:
```dart
 view class Foo.name(int x) { ... }
```
for declaring a named constructor as the primary constructor, and
```dart
 view const class Foo(int x) { ... } // or
 const view class Foo(int x) { ... }
```
for declaring a `const` primary constructor. (I prefer the former.)

We _could_ make the primary constructor constant by default, since all it does is initialize a field directly with a parameter, but I prefer to never make user code support constant evaluation without the user's explicit opt-in, because then it becomes a breaking change to stop supporting it.

For now, neither is supported by the proposed syntax. Both are possible, and can also be added later.
You can always write an explicit field and constructor if you want a `const` or named constructor.

My main worry is that *many* users will want `const` constructors, and making it hard to get them ruins the advantage of having the primary constructor syntax.

**I propose** adding `const` support for primary constructors in the first release, if possible.

## Can you have no constructor?

If a view class declares a single final field and *no* constructor, is that an error, or does it just not have a constructor?

Normally declaring no constructor means getting a default constructor of `ClassName()`. That constructor would fail to initialize the single field that a view class must have, so it would be an error to introduce it.

The alternative is to just not introduce a default constructor. (We know it won't work, so why do it?)
That leaves the class with no constructor at all. For a normal non-abstract class, that would make it useless, since there will never be any instance of the class. 
A view is not restricted in that way, you can just do `representationObject as ViewType` to get a value.
Not having a constructor is not a problem.

If the view declares nothing but a private factory constructor, it will still not have any generative constructor, and that's no more or less a problem than having none at all.

**I propose** we do _not introduce a default constructor_ if a view does not declare any constructors, and _not make it an error_ to have no constructors (it is for classes, to have a final field and no generative constructor).

## Can you call super-constructors.

All this discussion about constructors, when you don't actually need them for anything.

If the goal of constructors is only safety, readability and convenience, then it's not a problem that a view doesn't call its superview's constructors. All of these apply the constructor invocation point only.

However, if you try to have the constructor *validate* inputs, in order to only accept some values, then it's definitely not sound, but it might still be OK if you stay within the abstraction.
Take:
```dart
view class EvenInt {
  final int value;
  EvenInt(int value) : value = value.isEven ? value : (throw ArgumentError("Odd!"));
  EvenInt operator+(EvenInt other) => EvenInt(value + other.value);
  EvenInt operator*(int other) => EvenInt(value * other);
}
```
We know that you can always do `3 as EvenInt`, and we accept that keeping the abstraction requires cooperating from the user.
That's OK.

If I then try to make a sub-view:
```dart
view Class EvenIntWithMinus implements EvenInt {
  /// What to do here?
  EvenInt operator-(EvenInt other) => EvenInt(value - other.value);
}
```
What you *need* to do is something like:
```dart
  final int value;
  EvenIntWithMinus(int value) : value = value.isEven ? value : (throw ArgumentError("Odd!"));
```
If you want to call the super-constructor, you can hack it as :
```
  final int value;
  EvenIntWithMinus(int value) : value = EvenInt(value).value;
```

Should we allow you to call the super-class constructor instead? And maybe not even declare a field of your own, if you do so?
```dart
  EvenIntWithMinus(int value) : super(value);
  // or even
  EvenIntWithMinus(super.value);
  // or, heck:
  view class EvenIntWithMinus(super.value) extends EvenInt { ... }
```

So, a sub-view does not need to declare a field, but it must call a super-constructor with a value then.
_Should we allow that? Or just keep it as option for later?_

Since a view doesn't have to have a generative constructor at all, and you can still implement it, there may not be a super-constructor to invoke, so we can't automatically call a super-constructor for you.

It will get complicated if you can have more than one super-view, which you can. In that case, you may want to call *more* than one super-constructor. We don't have that issue in classes, so we have no prior examples.

**Comment by eernstg** [comment]
Allowing **constant constructors**: Sounds good, I couldn't see anything that breaks because of this feature. Maybe even:

```dart
view class const Foo(int x) { ... }
```

which would serve as a reminder that it's very much about the particular constructor which is created by the special syntax `(int x)`, and there could be other constructors which are not constant.

**No constructors**: Why not? The default constructor would work in some cases:

```dart
view JustAMinute {
  final _deadline = (DateTime.now()).add(Duration(minutes: 1));
  void done() {
    var now = DateTime.now();
    if (!now.isBefore(_deadline)) throw 'Too late!!';
  }
}
```

**Calling superconstructors**: I think we need to keep at least some distance to the rules around classes is the situations where following those rules seem to imply that the view has several instance variables. We actually want a view to have a single representation object, but if we have a superclass declaring an instance variable `one` and a subclass thereof declaring another instance variable `two` then the resulting subclass instances will have storage for both variables (final or not).

I don't think we want to go down a path that implies several storage locations. That's the main reason why I specified that there is no support for superinitializers (that is, the `super(...)`/`super.name(...)` construct at the end of the initializer list).

It is still possible to invoke the constructors, of course, so perhaps we could just say that this is the way to do it:

```dart
view class EvenInt {
  final int value;
  EvenInt(this.value) {
    if (!value.isEven) throw ArgumentError("Odd!");
  }
  EvenInt operator+(EvenInt other) => EvenInt(value + other.value);
  EvenInt operator*(int other) => EvenInt(value * other);
}

view class EvenIntWithMinus implements EvenInt {
  final int otherName; // No problem using a different name.
  EvenIntWithMinus(this.otherName) {
    // Check that `otherName` satisfies the constraints to be an `EvenInt`.
    EvenInt(otherName);
  }
  EvenIntWithMinus operator-(EvenInt other) =>
      EvenIntWithMinus(otherName - other.value);
}

view class NegativeEvenInt implements EvenInt {
  final int value; // No problem using the same name.
  NegativeEvenInt(this.value) {
    // Check that `value` satisfies the constraints.
    EvenInt(value);
    if (value >= 0) throw ArgumentError("Not negative!");
  }
}
```

This approach would work as long as a constructor is essentially just passing the representation object through and running some validation steps.

There may be other idioms that work well for the case where a constructor is used to create the representation object from various parts, but perhaps it does make sense to always provide a constructor that just passes the representation object through and validates.

**Comment by lrhn** [comment]
If the constructor only passes the representation object through, then you don't need to call it.

Consider instead:
```dart
view class Complex(({num r, num i}) c) {
  Comple.fromAngular(num theta, num magnitude) : this((sin(theta) * magnitude, cos(theta) * magnitude);
  num get r => c.r;
  num get i => c.i;
}

view class MoreComplex(({double r, double i}) c) extends Complex {
  MoreComplex.fromAngular(super.theta, super.magnitude): super.fromAngular();
  // more methods
}
```
This one looks useful, but is actually unsound because we are not checking against the `c` type of the sub-view, just of the super-view. That's not sound.

Too bad. My idea of calling a super constructor instead of initializing the local variable doesn't seem to work. ☹️

**Comment by eernstg** [comment]
@lrhn, do we intend to extract further elements from this discussion, or have we already done what we want to do? If so then it might be useful to close it.

**Comment by lrhn** [comment]
I think everything has been turned around a few times now. Nothing new to be gathered.

**Comment by eernstg** [comment]
Very good! Then I'll close it.
