### ISSUE TITLE
Rename "extractor" patterns to "object" patterns

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2562]
The patterns proposal calls patterns like `Point(x: var x, y: 2)` "extractor patterns", roughly based on Scala's terminology. I think that made sense when we were planning to also support user-defined extractor operations. But the current proposal doesn't support those. Really these patterns just call getters on arbitrary objects.

The other types of destructuring patterns—record, list, and map—describe what they apply to. Given that, I think it makes sense to call these simply "object patterns" instead. I'm working on a talk now, and as I wrote the slides, it felt like "object pattern" was the more natural name. We'll be stuck with this name forever in the spec, docs, AST class names, etc., so it's worth making it good.

Thoughts?

**Comment by bwilkerson** [comment]
I think that users will find "object pattern" to be easier to understand than "extractor pattern", in part because of the similarity to "list pattern" etc.

**Comment by lrhn** [comment]
I can see the point, but as a pedant, all values are objects! It's really just saying "pattern" then.

I'd say "property pattern", since properties are what you extract.

Maybe "interface pattern", to use another heavily overloaded word. Not as good, though.

In practice, I thing "object pattern" can work, and people will learn what it means.

**Comment by munificent** [comment]
> I can see the point, but as a pedant, all values are objects! It's really just saying "pattern" then.
> 
> It's also not like `Foo(...)` applies to _all_ objects.

I mean... it does. At least to all objects that have a named type, which even includes typedefs of record and function types. There's nothing saying you can't do `int(isOdd: false)`, `List(first: 'e')`, or even `Null(hashCode: var x)`.

> (But `<int>[...]` doesn't apply to all lists either.)
> 
> I'd consider "property pattern", since properties are what you extract.

But it's not like we call list patterns "element patterns" or map patterns "entry patterns".

> In practice, I think "object pattern" _can_ work, and people will learn what it means easily enough. It's the primitive pattern that the others can desugar to (`e case [var x, var y];` can desugar to `e case List(length: 2, first: var x, last: var y)` - would be even clearer if we allowed `[0]` as a property to match against too.)
