### ISSUE TITLE
Is destructuring going to be included in patterns release?

### ISSUE THREAD

**Issue by AlexanderFarkas** [dart-lang/language#2565]
I've read the accepted specification of patterns, and there is no sign of destructuring, though there was IIRC.
Is it planned? Would it be possible to destructure Records? Would it be possible to define destructuring for non-Record class? If yes, could it be done with extension methods?

**Comment by leafpetersen** [comment]
[This section](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#destructuring) of the patterns proposal shows examples of destructuring.  :). 

Yes, this is definitely part of the specified proposal.  Note that the records proposal (which has been moved to accepted) only covers records.  Patterns and destructuring are specified separately and have not yet been moved to accepted.

**Comment by AlexanderFarkas** [comment]
Oh, I confused records accepted proposal with patterns wip

**Comment by munificent** [comment]
> I confused records accepted proposal with patterns wip

The patterns proposal is still going through a little more churn (it has a *lot* more surface area than the records proposal), but we expect to ship both as a single unit. It's just that the implementers are working on the records portion first while the language team hammers out some remaining corners of the patterns proposal.
