### ISSUE TITLE
Typecasting is causing change in type

### ISSUE THREAD

**Issue by niteshb** [dart-lang/language#2566]
// ac.onlyInC(); // Compile ERROR
(ac as C).onlyInC();
ac.onlyInC(); // NO MORE AN ERROR! WHY?

https://github.com/niteshb/dart-bug-interface-2022-10-08/blob/master/dart-lang-bug-interface.dart

**Comment by niteshb** [comment]
Seems like this is due to "type promotion" optimizations.
Please close if this is indeed the case.

**Comment by mraleph** [comment]
Yes, this is result of type promotion. It's not an optimisation, but rather an integral part of how language is defined.

**Comment by niteshb** [comment]
Thanks Vyacheslav. Sorry for the bother.
