### ISSUE TITLE
Different treatment of private names and 'Object' member names in record types

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/language#2575]
The Records spec [forbids](https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#record-type-annotations) the names `hashCode`, `runtimeType`, `noSuchMethod`, and `toString` as the names of the named fields in record types, but makes it possible to use them as the names of the positional fields in record types. The same logic isn't applied to the names starting with an underscore: they are forbidden for both the named and the positional fields in record types.

It's unclear why the names with the underscores can't be given to the positional fields of record types. They are purely decorative and don't induce any members.

/cc @lrhn @munificent

**Comment by lrhn** [comment]
I'm fine with allowing or not allowing private names and `Object`-member names for positional fields in record types, but I think we should do the same thing for both, whichever it is.

**Comment by eernstg** [comment]
I'd recommend consistency as well: Private names cannot be the name of a variable in a record type, named or positional, and names of `Object` members get exactly the same treatment. So `final (int toString,) x;` is an error.

**Comment by munificent** [comment]
Yeah, this looks like it was an actual mistake in the proposal, since it allowed object member names in record types, but not in record expressions. They should all be consistent now.
