### ISSUE TITLE
Cascade operator on (any)Builder can end with ..build() but still returns Builder

### ISSUE THREAD

**Issue by MichalTorma** [dart-lang/language#258]
Hi, I find this a little confusing. When you run cascade operators on for example ParagraphBuilder and end it with ..build() it still returns ParagraphBuilder, not a Paragraph. It should throw an error perhaps?

Example code:

```
import 'dart:ui';
import 'package:test_core/test_core.dart';

void main() {

  test('Cascade test', () {
    var paragraph = ParagraphBuilder(ParagraphStyle())
          ..addText('There is no dark side of the moon')
          ..build();
    print('Is Paragraph type: ${paragraph is Paragraph}');
    print('Is ParagraphBuilder type: ${paragraph is ParagraphBuilder}');
  });
}
```
Test passes:
```
Is Paragraph type: false
Is ParagraphBuilder type: true
✓ Cascade test
```

**Comment by MichalTorma** [comment]
After a bit more study I realized this is probably intentional and my requested behaviour can be achieved this way instead:
```dart
var paragraph = (ParagraphBuilder(ParagraphStyle())
          ..addText('There is no dark side of the moon'))
          .build();
```

**Comment by davidmorgan** [comment]
Yes, that's the correct way to do it.

It requires an API change, but a nicer pattern is to accept a lambda for the updates. This is what [built_value](http://github.com/google/built_value.dart) does. For your example it would look something like this:

```dart
var paragraph = Paragraph(
    ParagraphStyle,
    (b) => b..addText('There is no dark side of the moon'));
```

This leads to nicer bracketing/nesting.
