### ISSUE TITLE
Pattern matching double constants

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2587]
Doubles have weird and invalid equality. We distinguish `0.0` and `-0.0` in many ways, but they are still equal. And NaN is just not equal to itself. Also `1` is equal to `1.0`, just for good measure.

So far that has not been an issue for switch cases because we require the switch expression and case expressions to have the same type, and doubles cannot be used as switch expressions since they don't have primitive equality.

With patterns, we remove those restrictions and use `==` for checking case expressions against the match value.
That means that:
```dart
switch (someDouble) {
  case 0.0 => "zero"
  case -0.0 => "negative zero"
  case double.nan => "NaN"
  case ...
}
```
will fail to work as expected. A `-0.0` value for `someDouble` sill match `0.0`.
A NaN value for `someDouble` will *not* match `double.nan`.

For `-0.0`, I'd probably want to actually match precisely `-0.0`. If you really want equality, you can use `== -0.0`, aka `== 0`.

It's not trivial because I can't completely decide whether I want `const int zero = 0; switch (-0.0) { case zero: ... }` to match or not.
Or `switch (0.0) { case zero => ...}` and `switch (0) { case 0.0 => ...}`. 
If any of those should match, we can't just use `identical` for all number constants.

If we are OK with them *not* matching, then we are not using `==` for any number. I think that might be reasonable.

So, PROPOSAL: For a constant pattern which is a number, use `identical` for comparison, not `==`.

(It sucks to special-case some types, but there is a reason we've done it repeatedly before. Our numbers really just don't fit very well into the general Dart language, be it the type system, or having a reasonable equality.)

The NaN issue is tricky too, and we might still have to rely on `case var x when x.isNaN =>` instead, because we have 2^53-2 different potential NaN values which are not identical to each other. They aren't equal either, not even to themselves.
If we use `identical` for all double-vs-double constant checks, then `double.nan` won't match all `nan` values (on native, probably will on the web), but it will match the most common NaN value.
That might actually be a curse, because then it becomes much easier to forget that there can be others, and that you really should be using `case var x when x.isNaN` instead.

We could make any NaN constant pattern, or just the default `double.nan` value, match any NaN value. Then we lose the ability to distinguish different NaN values in a switch. That should *probably* never happen anyway (so it definitely will).

**Comment by munificent** [comment]
> Doubles have weird and invalid equality. We distinguish `0.0` and `-0.0` in many ways, but they are still equal. And NaN is just not equal to itself. Also `1` is equal to `1.0`, just for good measure.

Doubles just *are* weird and users working with them have to understand that.

> So far that has not been an issue for switch cases because we require the switch expression and case expressions to have the same type, and doubles cannot be used as switch expressions since they don't have primitive equality.

Sure, but it has been an issue for users using `==` on doubles, and in practice I haven't heard many complaints about those semantics. (I didn't even realize until now that `1.0 == 1` is `true` in Dart even when not on the web.) If you're writing code that cares about negative versus positive zero or NaN, you already have to know that you can't use `==`.

I think the least confusing behavior for switches is to have them behave consistently with `==`. That's consistent with how other types work, and is the other way users typical check for equivalent values.

If you want to explicitly test for negative versus positive zero or NaN in a case then, like you suggest, you can always use a guard.
