### ISSUE TITLE
imutable list

### ISSUE THREAD

**Issue by MansonLuo** [dart-lang/language#2597]
it's can't image that google cant make imutable list into dart type system, leaving ide ignore modifing imutable list without any prompt, I wonder is it imppossible to do that or it's worth nothing to do that?

**Comment by lrhn** [comment]
It was a deliberate choice to not have separate APIs for read-only lists.
It's not impossible to add, but it is not something we are planning to do.
(Discussed before in, e.g., https://github.com/dart-lang/sdk/issues/13926)
