### ISSUE TITLE
[records] Parsing ambiguity resolution with `on` relies on ambiguity

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2599]
See also https://github.com/dart-lang/co19/issues/1528 where this question came up.

The records feature specification specifies [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#ambiguity-with-on-clauses) that the ambiguity arising from syntax that may be seen as (1) an `on` clause with a record type, and may also be seen as (2) a local function declaration named `on`, should be parsed as an `on` clause. Here is the example given at that point:

```dart
void foo() {
  try {
    ;
  } on Bar {
    ;
  }
  on(a, b) {;} // <--
}
```

The ambiguity arises because `on(a, b) {;}` can be a local function with no declared return type. At the same time, it could also be seen as an `on` clause specifying a record type `(a, b)`.

The reason why I created this issue is that I'm slightly worried about a rule that says "if there is an ambiguity, prefer the `on` clause". It reminds me of the rule "If it is not an error, `const` is implicitly added", which is a rule that we do _not_ have, because it gave rise to substantial difficulties when we tried to introduce such a rule.

Note that the rule where we rely on ambiguity gives rise to unlimited lookahead (in practice it's probably rather small, but this means that parsers as well as human beings need to scan some code before they know whether a given `on` is the name of a local function or it's yet another `<onPart>`):

```dart
void main() {
  try {
    // ... whatever.
  } on String {
    // ... whatever.
  } on (int i, int j, {String named = ""}) {
    // ... whatever.
  }
}
```

A named field in a record type can't have a default value, so there is no ambiguity, so the last `on` is a local function.

So perhaps we should simply say that when the token `on` occurs in a situation where an `<onPart>` can occur, the parser can commit to parsing an `<onPart>`.

Clear and simple, and if there is any existing code where a try/catch statement is immediately followed by a local function declaration with the name `on` and without a declared return type, that's a syntax error. It can be fixed by declaring the return type (or using a less silly name for the local function ;-).

Yes, that's a breaking change, but the code is seriously confusing anyway, and probably only occurs very, very rarely.

@munificent, @jakemac53, @kallentu, @lrhn, @leafpetersen, @natebosch, @stereotype441, WDYT?

**Comment by lrhn** [comment]
I thought that was what we did: Commit to an `on`-clause if seeing `on` after a `try` body or `on`/`catch` clause body.

So, yes.

**Comment by munificent** [comment]
I didn't make it unconditional in the proposal originally, but I'm fine with doing it that way: https://github.com/dart-lang/language/pull/2604
