### ISSUE TITLE
Can a sealed type appear in the "on" clause of a mixin declaration in another library?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2600]
When a type is sealed (or whatever keyword we pick for it), you can't extend, implement, or mix it in in a type declaration outside of the library where the type is declared.

Can you use it in an `on` clause?

This is outside of my area of expertise, but I think we can allow that, even though it's not likely to be _super_ useful. For example:

```dart
// lib.dart
sealed class A {}

class B extends A {}
class C extends A {}
```

Depending on syntax choices, you may have to write some modifier on `B` and `C` to indicate that _they_ aren't closed to extends/implements/mixin even though `A` is. Whatever syntax we pick, it should be possible to have a non-closed subtype of a sealed type. Given that, it's feasible to define:

```dart
// other.dart

mixin M on A {}
```

What that means in practice is that `M` can only be applied to `B` or `C` (and not `A` directly because `A` is sealed). But that could be a thing a user might want to express and I don't see any reason to disallow it. Am I missing anything?

**Comment by lrhn** [comment]
I don't see any problem. 

The mixin `M` must be applied to a class implementing `A`, and that class must be extendable. Mixin applications extend their superclass, they cannot if the superclass cannot b extended.

**Comment by munificent** [comment]
OK, sounds like it's fine then. I'll close this since there's no change needed to proposal.
