### ISSUE TITLE
The string '--' isn't a user-definable operator

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/language#2609]
I was trying to create a shortcut for my package users where they could use `eumConstant--` and get the previous one by index, and I got this error. I do believe this operator should be possible to override. So that they could do just like `someInteger--` and get the previous one.

**Comment by eernstg** [comment]
```dart
enum E { one, two }

extension EIncrement on E {
  E operator +(int i) => E.values[this.index + i];
}

void main() {
  E e = E.one;
  e++;
  print(e); // 'E.two'.
}
```

**Comment by FMorschel** [comment]
Ohh! I get it, is not exactly what I wanted because they will be able to add actual integers, but I guess it works! Thanks!

**Comment by eernstg** [comment]
`e++` means `e += 1`, no matter what, so you can't avoid supporting `myEnum + anInt` if you want the syntax `e++`.

**Comment by Levi-Lesches** [comment]
See also #2580
