### ISSUE TITLE
Error for assigning to a variable in a guard is too specific

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2612]
Following up on this conversational snippet (from https://github.com/dart-lang/language/pull/2606#issuecomment-1302640815):

> > 1. In our meeting yesterday we talked about the idea of prohibiting a guard from modifying a variable that's bound by the corresponding pattern.  I don't see anything in this PR about this; do we still want to do it?
> 
> Yes, I just, uh, forgot to add it. Done. 🙃
> 
> > 1. If so, do we want to do it everywhere (switch statements, switch expressions, if-case statements, if-case in collections)?
> 
> I think it's best to just do it unconditionally. I think it's essentially an anti-pattern anyway, so may as well forbid it everywhere.
> 
> > I would favor instead having a separate rule in the spec saying that within a guard, it is a compile-time error to write to a variable that's bound anywhere in the corresponding pattern.
> 
> Me too, that's what I added.

It sounds to me from the conversational snippet above like our intention is to apply this restriction to switch statements, switch expressions, if-case statements, and if-case in collections.

However, the patterns proposal currently says this, in the "Shared case scope" section:

> It is a compile-time error to assign to a variable declared by a case in that case's guard expression. *This helps avoid users running into the confusing behavior where the body sees a different variable than the guard when cases share a body. We make this an error even when the body only has a single case to keep the rule simpler for users to understand. This is similar to the restriction that you can't assign to the variable introduced by an initializing formal inside the initializer list.*

Since the "Shared case scope" section is concerned solely with switch statements, it sounds to me like we're saying this should only be an error in a switch statement.

I'd recommend either (a) moving this paragraph to the "Guard clause" section, so that it's clear that it applies to all guard clauses, not just guard clauses in switch statements, or (b) adding a normative text clarifying that this error is intended to apply to switch expressions, if-case statements, and if-case in collections as well.

**Comment by stereotype441** [comment]
CC @munificent

**Comment by munificent** [comment]
Yes, putting the prose where I did was confusing. My intent (as the non-normative text suggests) was that the prohibition always applies regardless of where the guard appears. Moved it like you suggested. Thanks!
