### ISSUE TITLE
Will Object.toString() return a non-null String?

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/language#263]
Once we have NNBD, will the type signature of `Object.toString()` to be changed to enforce that all implementations must return a non-null String?

Or is it considered a desired feature that this method can indeed return null?

**Comment by jonahwilliams** [comment]
I would think it should be non-null, if only because of the behavior of string interpolation:

```
class Foo {
  toString() => null;
}

void main() {  print('${Foo(}'); }
```

> Uncaught exception:
> Invalid argument: Instance of 'Foo'

**Comment by jonahwilliams** [comment]
Ahh, I see you've referenced that in a similar issue

**Comment by lrhn** [comment]
Yes. The return type of `Object.toString` will almost certainly be `String` (non-nullable).
(I can't imagine any issue that would change that, but then, you never know).

**Comment by leonsenft** [comment]
Great, thanks for clarifying!
