### ISSUE TITLE
Map pattern inefficient (or not)?

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2634]
The spec for map pattern matching states:
> iv. Otherwise, for each (non-rest) entry in `p`, in source order:
>     a. Evaluate the key expression to `k` and call `containsKey()` on the value. If this returns `false`, the map does not match.
>     b. Otherwise, evaluate `v[k]` and match the resulting value against this entry's value subpattern. If it does not match, the map does not match.

This is potentially less efficient than possible.

Since the `Map.operator[]` returns `null` for non-present keys, it's more efficient to do `v[k]` first, and then only check `containsKey(k)` if the first value is `null` (and not even that if we statically know that the following pattern won't match `null`, which we might.)

So, the specification is being precise about which operations are done in which order, and by doing so preventing optimizations.
Should we loosen up the phrasing to say that the pattern may call only `constainsKey` and `operator[]` with the `k` value, and say what it should do in prose instea. Something like:

>    a. Evaluate the key expression to `k`.
>    b. Using only calls to the methods `containsKey` and `operator[]` of the value, and only with `k` as argument, determine:
>    c. Whether `k` is a key of the `Map` value. If not, the map does not match.
>    d. The value assigned to the key `k` in the map, call it `w`.
>    e. Then match `w` against the entry's subpattern. If that does not match, the map does not match.

(It's probably only `Map`s where we have to do something like that for matching, because calling getters and `operator[]` on lists is done only when necessary anyway. Rest patterns on lists may also be worth considering.)

The one worry I have is that an optimization like reading `v[k]` does assume a specific behavior for the non-key case. If someone introduces a `Map` with a default value it returns instead of `null` for missing values (say `0` for a numerical map), then that optimization will fail. (But since we use it elsewhere, other things will fail too, so hopefully they don't do that.)

**Comment by eernstg** [comment]
I like the specification that allows optimizations! This is in line with several other choices we've made in the language design. It's probably never a good idea to have a `Map` implementation that has side effects in `containsKey`, and a program that depends on those side effects.

> The one worry ... is that ... reading `v[k]` does assume a specific behavior for the non-key case

I think we can consider that to be a non-problem, as long as this behavior in pattern matching is documented:

The `Map` documentation uses the concept "the given `key` is _in the map"_, and the semantics of `containsKey` and `operator []` should be consistent with the answer to this question ("is `k` in this map?").

If the `map` models a function whose domain is "any object whatsoever" then it can return true from `map.containsKey(k)` for all unassigned `k` (of type `K` or not) and it could return the default value from `map[k]`. It could also map all unassigned `k` of type `K` to the default value, and all `k` that are not of type `K` to null. I suspect that most other combinations are inconsistent (so the map is to blame).

**Comment by lrhn** [comment]
Good point. We should make sure to document that `map.containsKey(k) == false` implies `map[key] == null`.
Then anyone providing a default value for all key values should also return `true` from `containsKey` for all those values.
(It won't match the behavior that `map.containsKey(k) == map.keys.contains(k) && map.length == map.keys.length`, though. So they probably shouldn't do ti at all.)

**Comment by munificent** [comment]
I like the idea of being able to avoid the double look up. Instead of leaving it loosely specified, would it work to just say that an implementation *must*:

1. Call `v[k]` to get a value `e`.
2. If `e` is `null`, then call `containsKey()`. If that returns `false` then the map pattern doesn't match.
3. Else (`e` is not `null` or `containsKey()` returns `true`), match `e` against the subpattern.

**Comment by lrhn** [comment]
Specifying the optimization is probably better, but still potentially over-specific. 

For example, there is no need to call `containsKey` if we can see statically that the pattern cannot match `null` (say it starts with `p?`). Then we can simply reject immediately on `null`, without calling `containsKey`. (Because we just did a `!= null` check as part of the "lookup" sequence.) Or if the pattern is `int x`, or another immediately non-nullable pattern (something which rejects `null` without doing any further property accesses), then we can again skip directly to the pattern and not need to do the `containstKey`.

In general, there may be many ways to reject early, so forcing a call to `containsKey` can get in the way.

**Comment by munificent** [comment]
There's also no need to call `containsKey()` if we see that `V` on the map pattern's `Map<K, V>` static type is known to be non-nullable, which is likely the common case.

I don't like:

> Using only calls to the methods containsKey and operator[] of the value, and only with k as argument, determine:

Because it's too vague about *how* to determine that since the policy between `containsKey()` and `[]` isn't explicit. What about:

1. Call `v[k]` to get a value `e`.
2. If `e` is not `null` then match the subpattern against `e`.
3. Else if `v.containsKey(e)` returns `true` then match the subpattern against `e`. A compiler may omit the call to `containsKey(e)` if it knows that it's not possible for `null` to be a valid matching map value. *If the map pattern's required type V is non-nullable, then `null` can't be valid. If the subpattern will not match `null`, then there's no point calling `containsKey()` because even if that returns `true`, the subpattern will fail to match.*
4. Else the pattern doesn't match.

**Comment by lrhn** [comment]
Seems reasonable. I can't come up with an example where a call to `v[k]` is not necessary, except perhaps:
```dart
case {"key": _}: print("Map has 'key' key");
```
which can be implemented using only `containsKey`. But why would you *do* that check, and not care what the value is.

It is a question how defensive we need to be around `Map` objects which don't follow the normal rules, like a map which returns a default value instead of `null` for a missing key, but does allow `constainsKey` to see whether it exists. I'd say we *shouldn't* try to accommodate that, and just document up-front which assumptions we make, and that any map not satisfying those assumptions migh just not work consistently with pattern matching.
(I still worry about differences between platforms, or versions, but if the front end does all the desugaring, we should be fairly consistent.)

**Comment by leafpetersen** [comment]
> 3\. A compiler may omit the call to

I get where this is coming from, but I also feel a bit hinky about explicitly saying that this is one spot where the compiler is free to skip potentially side effecting operations.  We've gone to a fair bit of length to specify exactly where side effects happen elsewhere in pattern matching, it feels odd to just throw up our hands here.

**Comment by lrhn** [comment]
This case is special in that it doesn't correspond to a single member invocation.

Maps are tricky in several ways. We pretend that `case {"a": p1, "b": p2, "c": p3}` will match a map with the three keys `"a"`, `"b"` and `"c"`. We don't *know* that, because maps can have weird equalities, or have a key which considers itself equal to multiple other things. 

That's not an issue for lists. A list has a `length`, and that many elements accessible using the `operator[]` getter. Only integers involved, nothing fishy is possible without breaking the `List` protocol.

Maps have a very loose semantics for equality, which depends on user provided key objects. (So do sets, and thankfully we don't have set patterns. Even defining what `Set<T>.retainAll(Iterable)` should do, or `Set.intersection(Set)`, was non-trivial.)

So, to not get completely lost in likely-unimportant details, it might be best to just *assume* a reasonable semantics, and not check for it.

That brings us back to not having a single method which 
* Tells us whether key is in the map.
* Tells us the value, if it is.

The `containsKey` only answers the first question.
The `operator[]` answers the second question, but not (necessarily) the first.

There are patterns which can adequately be answered by just one or the other, and patterns which require both:
* `case {"x": _}`  - Decidable by `containsKey` alone, but not by `operator[]`.
* `case {"x": var x?}` - Decideable by `operator[]` alone.
* `case {"x": var x}` - Needs both of value type is nullable.

Of these, the first seems the least useful, but I can't rule out wanting to check if a map has a specific key, without caring (yet) what its value is.

So, if we define late variables for both checks as usual, the question is how we best combine them in a way which is predictable, but not wasteful.

Maybe define a helper function over patterns:
   *eagerlyRejectsNull*(pattern), which is true if the pattern definitely will reject `null`, and will not do any member invocations before doing so. Includes `int x`, `p?`, `== 4`, but not `Object?(runtimeType: bool) & _?`.
Then matching the map entry pattern `"x": p` against the map value proceeds as follows:
    * let *v* be `map[key]`
    * if *v* is `null` and not *eagerlyRejectsNull*(`p`):
        * if `map.containsKey(key)` is false, reject.
    * Match *v* against `p`.

I was considering also having a check for whether the pattern doesn't use the value, like `"x": var _`, and not call `operator[]` in that case. It felt too weird and special-casey. We don't omit calling the getters of other objects for `Foo(x: var _)`. The `operator[]` is the getter. The `containsKey` is a disambiguator for `null` values.

So, back to basically what @munificent said, but with an option to check the pattern first, to see if we _need_ to call `containsKey`, which we don't if the pattern will reject `null` anyway, before doing anything visible.


**Thought**: Are we optimizing for the right thing?

There are two things to possibly optimized for: Branching in the matching algorithm, and lookups. Lookups are far the more expensive.

The three possible combinations of `[]` and `containsKey` results are:

|[]\\containsKey|          false | true |
|:----:|:----:|:-----:|
|null|      |   reject       |  check pattern   |
|non-null|     🚫      |  check pattern  |


Doing `containsKey` first would either immediately reject or put us in a position where we need to check the value. 
That's the least *branching* we can do, because we just treat the value the same in all cases,
but it always costs two *lookups* for a potential match.

Doing `[]` first means we still don't know which column we're in, if we see `null`.
So we check for `null` (one branch).
If the value is non-`null`, we can immediately go to matching.
If `null`, we're in the first row, so we need to also check `containsKey` before rejecting or checking the pattern (second branch, second lookup).
That's potentially two conditional branches before checking the pattern, and always when we reject.

What do we *expect* to be the common case?

For declaration/assignment patterns, we *expect to match*. That means we expect `containsKey` to always be true.
We'd always end up doing two lookups if we do `containsKey` first.
We'll sometimes save one lookup if we do `[]` first, and check for `null`.

For refutable patterns, we have two cases: `if` and `switch`. Not sure how much they differ.
For `if`, I'd optimistically assume that it matches, because it's definitely something the user expects to be able to happen. If not, it may fail early anyway. But impossible to say.

For `switches`, I expect it to be more common to do *similar* checks on a map, like checking
```dart
case {"type": 4, "name": String s} : ....
case {"type": 5, "valid": bool b} : ....
```
There are more cases, so statistically some of them are going to reject. Possibly most (but well-coded switches would put the patterns that match the most at the start, for speed, so we might not reach all the patterns that would reject).

_Would it make sense to optimize for rejecting the map shape, by checking `containsKey` first in switch cases?_

Or should we optimize even more, and depend on which values we have available.
Maybe making `_containsX` not be late, but maybe `bool? _containsX;` instead, and doing:

   * **if** `_containsX` is false, reject.
   * otherwise let *v* be `_valueX` (late variable, initializing to `theMap["x"]`)
   * **if** `_containsX` is null:
       * **if** *v* is `null`:
          * _If the pattern rejects `null` eagerly, reject. (Static property of pattern)._
          * _If the value type of the map is statically known to be non-nullable, reject._
          * otherwise call `theMap.contains("x");` and set `_containsX` to the result.
          * **if** that result is false, reject.
       * otherwise set `_containsX` to true.
   * assert(`_containsX` is true)
   * match *v* against *p*.

It's close to:
```dart
  late bool containsX = _valueX != null || _theMap.containsKey("x");
  late V? _valueX = _theMap["x"];
```
but with the option of never calling `containsKey` if the pattern rejects `null` eagerly, or the map is known to not have `null` as a value.

It risks four branches on the way to a rejection (but any future checks of the same `containsX` will have the answer immeidately).


This optimizes for *available information*, which is probably a good idea for repeated tests in a `switch`, where you can have information from an earlier case available.

I'm not worried about side-effects from `containsKey` or `[]`. Honestly, if you have those, I want you to fail.
I am only considering performance, which has historically been quite bad for some map implementations.

**Comment by munificent** [comment]
Haha, oh, God, you wrote an essay. 😁 

I kind of feel like we should either just keep the current spec and acknowledge that it's maybe not optimal in some scenarios but it is precisely defined. Or we should just loosen it to your original suggestion and state that a compiler is free to call either or both of `v[k]` and `v.containsKey(k)`, in either order. And then define the policy between the two that the compiler assumes those two methods will implement, which is your last two bullet points.

**Comment by lrhn** [comment]
Oops, I did it again 😢

**Comment by munificent** [comment]
Re-opening based on discussion in #2671.

**Comment by lrhn** [comment]
Another thought: Would it make sense for
```dart
case {k1: p1, k2: p2, k3: p3}: ...
```
to do
```dart
  if (value.length == 3 && value.containsKey(k1) && value.containsKey(k2) && value.containsKey(k3) ...
```
before trying to match any of the patterns?

Some patterns are trivial, like just binding to a variable, but we should assume that some patterns can be complicated and expensive. Rejecting a pattern early because the *structure* doesn't match would avoid checking partial contents of something that will eventually be rejected anyway.

(And if the pattern is just a binding, we can do it eagerly if we have already read the value anyway, which we may want to do.)

Consider this desugaring:
```dart
late final bool isMap1 = value is Map<K, V> && (map1 = value; true);
late final var map1 = ...;
late final bool containsKey1 = mapValue1 != null || map1.containsKey(k1);
late final V mapValue1 = map1[k1];
late final bool containsKey2 = mapValue2 != null || map1.containsKey(k2);
late final V mapValue2 = map1[k2];
late final bool containsKey3 = mapValue3 != null || map1.containsKey(k3);
late final V mapValue3 = map1[k3];
...
 // checking pattern above:
 if (isMap1 && map1.length == 3 && containsKey1 && containsKey2 && containsKey3 &&
     // Structure is right, and values have been read, but not matched against yet.
     .. p1 matches mapValue1 ... && p2 matches mapValue2 .. && ...p3 matches mapValue3...) {
   // bindings and body
 }
```

**Comment by munificent** [comment]
We could play this game of speculatively defining a desugaring based on guesswork about performance forever. Since we don't have reliable ground truth data, it becomes impossible to choose which desugaring is most optimal.

I think the right thing to do is to pick a desugaring that is simple, obvious, and not clearly inefficient and stick with it. If users really need to care extremely precisely about the order that `containsKey()` is called relative to recursing into subpatterns, etc... then maybe that's a hot spot in their code base where they should hand-write the method calls they want in the order they want.

**Comment by leafpetersen** [comment]
> I think the right thing to do is to pick a desugaring that is simple, obvious, and not clearly inefficient and stick with it.

+1

I'm quite in favor of picking a specific semantics to specify.  In general, I'm highly sympathetic to the desire to make code optimizable, but I think if we're going to define this relative to a user defined interface, we should just accept that the interface guarantees nothing more than certain typing properties.  

If the implementation teams would prefer a different order of operations to make this more efficient I'm certainly open to taking that into account, but I don't think we should leave this as undefined behavior.

**Comment by munificent** [comment]
After a bunch of revisions, I think we have the map semantics pinned down now.
