### ISSUE TITLE
Should eliminating implicit casts include casts during iteration.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#264]
Currently in Dart (or soon in the case of the spread), the following is a legal program:

```dart
main() {
  var a = <Object>[1, 2, 3];
  for(int x in a) {
    print(x);
  }
  <int>[...a];
}
```

There are implied casts on each element of the iteration, and on each element addition from the spread.

If we eliminate implicit casts, should we include these as well?

**Comment by leafpetersen** [comment]
cc @rakudrama

**Comment by lrhn** [comment]
If we rewrite the code as:
```dart
for (int i = 0; i < a.length; i++) { 
 int x = a[i];
 ...
}
````
or 
```dart
for (var it = a.iterator; it.moveNext(); ) {
  int x = it.current;
  ...
}
```
we would not allow the downcasts from `it.current` and `a[i]` to `int`.

I see no reason language-controlled iteation should be different. It's just member access.

**Comment by eernstg** [comment]
We could apply an idea here that we've discussed a few times in the past: Optimistic checking of the components of a higher-order type (that is, a generic type or a function type). OK, we probably never made it explicit how to do this, but let's give it a syntactic form for concreteness:

```dart
main() {
  Iterable<lazy int> xs = <Object>[1, 2, "3"]; // OK, statically and dynamically.
  double d = xs[0]; // Compile-time error, elements considered `int`.
  int i = xs[0]; // OK statically. Dynamic check, succeeds.
  int j = xs[2]; // OK, statically, throws at run time.

  void Function(lazy num) f = (int) => print(x); // OK statically and dynamically.
  f(3.14); // OK statically, dynamic error.
}
```

This concept would then fit the treatment of the collection that you alluded to, that is, checks on each element during the iteration. Given that we can now write down the casts to get that semantics, we could eliminate the implicit casts and get the same typing situation explicitly as follows:

```dart
main() {
  var a = <Object>[1, 2, 3];
  for(int x in a as Iterable<lazy int>) {
    print(x);
  }
  <int>[...a as Iterable<lazy int>];
}
```

If we can find a syntax for "cast as needed" that not everybody hates then we could also allow developers to use a shorter form (I'll use `!!` as a stand-in for that syntax):

```dart
main() {
  var a = <Object>[1, 2, 3];
  for(int x in a!!) {
    print(x);
  }
  <int>[...a!!];
}
```

**Comment by munificent** [comment]
I agree with the first two paragraphs of @lrhn's comment. Your suggestion is interesting, Erik, but feels like a lot of mechanism to me. I did spend some time a while back noodling on some ideas for pattern matching syntax and one thing I considered as a notation there for doing an explicit downcast. So maybe there is something to that.

I agree with Lasse that losing the implicit downcast here is particularly annoying because there isn't an easy notation to do it explicitly. If you don't want to use `.cast<T>()`, another option is:

```dart
main() {
  var a = <Object>[1, 2, 3];
  [for (var x in a) x as int];
}
```

**Comment by eernstg** [comment]
@munificent wrote:
> a lot of mechanism

Right, it does not fit well as a solution to this problem only, but this whole notion of "promise that this is a `List<int>` even though it's actual type argument is `num`, and then we will check that we get an `int` every single time we fetch an element from it" has been on the table several times, for different purposes, and I think this fits well into that discussion.

So if we want some kind of "lazy higher-order promotion" anyway then this is just an obvious use case.

**Comment by leafpetersen** [comment]
This is disallowed.
