### ISSUE TITLE
Can the new Exhaustiveness Checking proposal handle non-abstract cases?

### ISSUE THREAD

**Issue by rubenferreira97** [dart-lang/language#2640]
After reading the new [Exhaustiveness Checking](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/exhaustiveness.md#exhaustiveness-checking) proposal I came with the following example that seems sound:

```dart
// amigos.dart
class Amigo {}
class Lucky extends Amigo {}
class Dusty extends Amigo {}
class Ned extends Amigo {}

// The body might complete normally, causing 'null' to be returned, but the return type, 'String', is a potentially non-nullable type.
String lastName(Amigo amigo) {
    if(amigo is Lucky) {
      return "Day";
    } else if(amigo is Dusty) {
      return "Bottoms";
    } else if (amigo is Ned) {
      return "Nederlander";
    } else if(amigo is Amigo) { // Unnecessary type check; the result is always 'true'.
      return "Unknown Amigo";
    }
}
```
Dart already seems to know that the result is always true.
The same applies to the proposal:
```dart
// amigos.dart
class Amigo {}
class Lucky extends Amigo {}
class Dusty extends Amigo {}
class Ned extends Amigo {}

String lastName(Amigo amigo) =>
    switch (amigo) {
      case Lucky _ => 'Day';
      case Dusty _ => 'Bottoms';
      case Ned _   => 'Nederlander';
      case Amigo _ => 'Unknown Amigo';
    }
```

We could even omit one or more cases like:  

```dart
// amigos.dart
class Amigo {}
class Lucky extends Amigo {}
class Dusty extends Amigo {}
class Ned extends Amigo {}

String lastName(Amigo amigo) =>
    switch (amigo) {
      case Lucky _ => 'Day';
      case Amigo _ => 'Unknown Amigo';
    }
```

Is there any unsound reason that this example can't be accomplished? I think `Amigo` doesn't need to be abstract either, since the upper bound is `Amigo` given by the param type, and the lower bound is also `Amigo` given by the condition `amigo is Amigo`.

**Comment by lrhn** [comment]
The `case Amigo _ => ` on a value with static type `Amigo` should be recognizable as a guaranteed match. It should be as good as `case _ =>` or `default =>`.

I think that's within range of what we are already expecting to achieve. (Don't know if it's written down, though.)

**Comment by munificent** [comment]
Yes, the exhaustiveness checking algorithm I proposed (or any other one we come up with) will understand that a pattern that matches all values of type `T` is exhaustive when the matched value type is `T` or a subtype of `T`.
