### ISSUE TITLE
Override method with a callable getter

### ISSUE THREAD

**Issue by AlexanderFarkas** [dart-lang/language#2642]
Why is this not possible:
```dart
abstract class A {
  void copyWith({String? a});
}

abstract class B extends A{
  CopyWith get copyWith;
}

class CopyWith {
  void call({String? b, String? a, }) {
  
  }
}
```

Error: 
```dart
Class 'B' can't define field 'copyWith' and have method 'A.copyWith' with the same name.
Try converting the getter to a method, or renaming the field to a name that doesn't conflict.dart(conflicting_field_and_method)
```

**Comment by mateusfccp** [comment]
You are defining both a getter and a method with the same name.

When you call `yourBInstance.copyWith`, what is supposed to happen? Return the value of the getter or call the method?

They are conflicting interfaces.

**Comment by eernstg** [comment]
This is a very old restriction in Dart (that a getter can't override a method or vice versa). It would probably be very costly to change the semantics in such a way that every method invocation could potentially be a getter invocation followed by a function object invocation.

This means that you can make the choice to have a getter that returns a function (and it would be known for all statically checked invocations that they must call the getter and then the function), but you can't change your mind about this choice in an overriding declaration.

So it could be implemented, but it won't. ;-)
