### ISSUE TITLE
Patterns spec needs to clarify how and when map keys are inferred

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2645]
The patterns spec says that the type schema for a map pattern is computed like this:

> *   **Map**: A type schema `Map<K, V>` where:
>
>     1.  If `p` has type arguments then `K`, and `V` are those type arguments.
>
>     2.  Else if `p` has no entries, then `K` and `V` are `?`.
>
>     3.  Else `K` is the least upper bound of the types of all key expressions and `V` is the greatest lower bound of the context type schemas of all value subpatterns. *The rest pattern, if present, doesn't contribute to the context type schema.*

There's no mention of what the context type should be when analyzing the types of the key expressions, however since the type schema has to be computed prior to computing the matched type, this means that it's impossible for the matched type to influence the type inference for keys. This means, for example, that in the following code, the type of `values` can't trigger int-to-double conversion on the constants `0` and `1`, so the match is guaranteed to fail at runtime:

```dart
f(Map<double, String> values) {
  var {0: x, 1: y} = values;
}
```

This seems unfortunate.

Personally I think it would be better to change the type schema for map patterns to work this way:

> *   **Map**: A type schema `Map<K, V>` where:
>
>     1.  If `p` has type arguments then `K`, and `V` are those type arguments.
>
>     2.  Else if `p` has no entries, then `K` and `V` are `?`.
>
>     3.  Else `K` is `?` and `V` is the greatest lower bound of the context type schemas of all value subpatterns. *The rest pattern, if present, doesn't contribute to the context type schema.*

And then update the type checking rules for map patterns to something like this (my proposed changes are in bold):

> *   **Map**:
>
>     1.  Calculate the value's entry key type `K`, value type `V`, **and key context `C`**:
>
>         1.  If `p` has type arguments `<K, V>` for some `K` and `V` then use those, **and let `C = K`**.
>
>         2.  Else if `M` implements `Map<K, V>` for some `K` and `V` then use those., **and let `C = K`**
>
>         3.  Else if `M` is `dynamic` then `K` and `V` are `dynamic`, **and `C` is `?`**.
>
>         4.  Else `K` and `V` are `Object?`, **and `C` is `?`**.
>        
>     2.  **Type-check each key expression using `C` as the context type.**
>
>     3.  Type-check each value subpattern using `V` as the matched value type.  *Like lists, we calculate a single value type and use it for all value subpatterns:*
>
>         ```dart
>         var {1: a, 2: b} = {1: "str", 2: bool};
>         ```
>
>         *Here, both `a` and `b` use `Object` as the matched value type.*
>
>     3.  The required type of `p` is `Map<K, V>`.

**Comment by stereotype441** [comment]
CC @munificent @leafpetersen @jakemac53 @lrhn @mit-mit @natebosch @eernstg @kallentu

**Comment by munificent** [comment]
SGTM, thanks for thinking this through!
