### ISSUE TITLE
Should we allow "sealed", "final", "interface", and/or "base", on mixin classes?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2652]
The proposals for those modifiers currently allow them on class and mixin declarations where appropriate, but I overlooked mixin classes:

```dart
class C = B with M;
```

Should we allow any of those modifiers on them? It looks like mixin classes can have `abstract`, so probably yes. Filing this as a reminder to figure out which ones make sense.

**Comment by eernstg** [comment]
Sure! I don't see any reason why not.

**Comment by lrhn** [comment]
It's a class declaration like any other, so I think it should be like any other.

**Comment by munificent** [comment]
Apparently I am ahead... of myself. I did *not* overlook mixin applications and both the sealed and base/final/interface proposals do explicitly support the new modifiers on them, so I think we're good.
