### ISSUE TITLE
Constant patterns do not include negative numbers

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2663]
Thanks to @sgrekhov for noticing this issue. The syntax rule about constant patterns is as follows:

```
constantPattern ::= booleanLiteral
                  | nullLiteral
                  | numericLiteral
                  | stringLiteral
                  | identifier
                  | qualifiedName
                  | constObjectExpression
                  | 'const' typeArguments? '[' elements? ']'
                  | 'const' typeArguments? '{' elements? '}'
                  | 'const' '(' expression ')'
```

which includes `numericLiteral`. However, `numericLiteral` does not include negative numeric literals (they are handled as a special case with the unary minus operator). Do we want to add that special case for constant patterns as well? It does look like an oversight that it's currently a syntax error. In the grammar, this could be achieved by adding an optional `-` in front of `numericLiteral`, and we might then need to add a couple of words in the main text of the specification about it.

**Comment by munificent** [comment]
Good catch! I fixed it by allowing negative numeric literals, but not negative named constants. In the corpus I looked at, there were only two uses of `-namedConstant` in existing cases, so it doesn't seem very useful to support. I worry that if we allow that, then users will also expect `a - b` or `a + b` or other more complex const expressions to work and very quickly that gets you into syntactic territory that collides with pattern syntax.

Limiting it to negative number literals (which are also rare, for what it's worth), seems safer.
