### ISSUE TITLE
Type of `Record` fields

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2665]
What's the inferred type of `x`?

```dart
void f(Record r) {
  var x = r.whatever;
}
```

Following `Function`, it could be `dynamic`. Following more recent trends, it could be `Object?`.

**Comment by alexmarkov** [comment]
Maybe this time we can avoid adding dynamic trait to `Record` and just issue a compile-time error as `Record` class doesn't have a getter `whatever`. If needed, this can be written as `(r as dynamic).whatever` to access field dynamically.

**Comment by munificent** [comment]
> Maybe this time we can avoid adding dynamic trait to `Record` and just issue a compile-time error as `Record` class doesn't have a getter `whatever`.

That's the right answer. The proposal deliberately doesn't specify that there is any dynamic property look up on `Record`. It's mostly just a tag interface with no real useful operations on it.

**Comment by eernstg** [comment]
Very good!
