### ISSUE TITLE
Better terminology for the two kinds of rest patterns

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2678]
@johnniwinther pointed out in a meeting this morning that in the front end code, "rest pattern without a subpattern" (`...`) and "rest pattern with a subpattern" (`...pattern`) actually have fairly different semantics from one another.  The former just means "loosen the list length check", and affects the way the index is computed for any patterns that follow, whereas the latter causes additional matching to be performed.  Because they're so different, the front end team is finding themselves saying things like "rest pattern without a subpattern" and "rest pattern with a subpattern" a lot in their code comments, function names, etc., and it's pretty unwieldy.

Is it possible to come up with different spec terminology that distinguishes the two types of rest patterns?  E.g. maybe we could call `...pattern` a "rest pattern", and call a bare `...` an "ellipsis"?

**Comment by stereotype441** [comment]
CC @munificent @leafpetersen @jakemac53 @lrhn @mit-mit @natebosch @eernstg @kallentu

**Comment by eernstg** [comment]
A bit like `_` and `int _` not really being variable patterns? How about 'rest pattern' (meaning `...p` for some `p`) and 'non-binding rest pattern' (meaning `...`)?

**Comment by munificent** [comment]
Good call. It was even awkward for me what I was writing the proposal. I like Erik's "non-binding rest pattern" but a rest pattern with a subpattern might not actually *bind* anything. Instead, I went with "matching rest element" and "non-matching rest element".

(The proposal already used a random mixture of "rest element" and "rest pattern". I went with "element" since a non-matching one doesn't really have any patterns in it.)

**Comment by munificent** [comment]
> And, like similar cases, should `... _` behave differently from `...`? Can we make it _not_ do so?

As specified, it does. `... _` will call `sublist()` and then throw the result away. `...` won't call `sublist()`. I'm fine with these behaving differently. If you write something weird, you might get something weird. The best solution is to not write something weird. :)
