### ISSUE TITLE
Update code example for Instantiation to Bound Algorithm

### ISSUE THREAD

**Issue by jmewes** [dart-lang/language#2679]
## Observed

In the Dart language specification there the following code example for the section "Generics > Instantiation to Bound > The Instantiation to Bound Algorithm":

```dart
typedef Inv<X> = X Function(X);
class B<Y extends num, Z extends Inv<Y>> {}

B b; // The raw B means B<num, Inv<num>>.
```

(see [14efbe8/specification/dartLangSpec.tex#L8044-L8049](https://github.com/dart-lang/language/blob/14efbe8/specification/dartLangSpec.tex#L8044-L8049))

This yields a [not_initialized_non_nullable_variable](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=not_initialized_non_nullable_variable#not_initialized_non_nullable_variable) error.

![error](https://user-images.githubusercontent.com/5235584/205225878-c21f4b56-b1e7-4166-ab6a-718fc81043df.png)

## Expected

The variable `b` should have a nullable type, contain an instance of type `B`, or be declared within a function.

```dart
typedef Inv<X> = X Function(X);

class B<Y extends num, Z extends Inv<Y>> {
  Y? y;
  Z? z;
}

void main() {
  B b = B();
  assert(b.y is num?);
  assert(b.z is Inv<num>?);
}
```

## Comment

In the example below there is a similar code snippet that shows an example for a compilation error. It might be useful to adapt this as well, so that it show the expected compilation error.

**Comment by eernstg** [comment]
Good catch, thanks! Handled in https://github.com/dart-lang/language/pull/2605/commits/8f1fd5718b1cf39dc77ea4fc3a0838e71f7cbefb.
