### ISSUE TITLE
Should patches be a use case for augments?

### ISSUE THREAD

**Issue by makoConstruct** [dart-lang/language#2684]
I'm sensing that [augments](https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md) may have a whole other use beyond the one proposed, but I'm not sure, so I'll ask, do augments support everything we'd want if we were using augments to describe patches/diffs? It looks really close, so if not, here's why it probably should:

I've been doing some language design exploration around extension and interoperability. One common obstacle to collaboration even with open source software is that source patches must wait for the approval of a single party of maintainers, the approval process isn't maximally decentralized. Sometimes, if the patch is only for the benefit of a small group, the maintainer has no real incentive to evaluate it and approve it, it's extremely common that they might not even be able to understand the minority groups' needs well enough to tell whether it's necessary.

The current practice for these cases is to fork, but this has a somewhat suboptimal process for merging changes from upstream, and it doesn't really work if minority groups overlap a lot, and users tend to end up wanting _unique combinations_ of extensions, they either have to make a fork of their own that combines other forks, or they have to look for a super permissive kitchen sink fork that tries to incorporate everything, which probably either wont exist, or will be bigger and less secure than they want.

So I looked for a better process, one that would continue to work as code shifts around, to give clean, comprehensible errors when upstream changes break the patch. I ended up with: Have a type of file/block that can describe alterations to modules, types or functions by name (rather than line number), the addition, removal, or replacement of methods. I called this "augments". I went looking for precedent. I tried describing it to GPT4 and all it had for me were lies (it turned out that in fact the rust package "patchwork" was about sprite atlasses, and the haskell-based package manager's "DSL" was just a regular diff format).

So I tried searching "programming language augments" and, wow, this is maybe the exact same featureset, with the same name, but it seems like you proposed it for a different purpose??

**Comment by jakemac53** [comment]
The library augmentation feature is local and does not allow you to modify other libraries arbitrarily. That is an explicit non-goal for the feature.

If you enable these types of patches, then since they are lower effort than upstream fixes they would likely become the norm, and pretty soon you have an extremely brittle ecosystem of patches. I don't think its something we would want to endorse/support as a core part of the ecosystem.

**Comment by makoConstruct** [comment]
I guess there's a pretty serious UX issue that needs to be solved before it would work for this, the extension discovery system needs to be integrated with the version control system and its frontends, so that merging extensions is as easy as merging pull requests, and the extension can usually be uninstalled automatically for users when this happens.

If that were done, would you be more interested? (It is on the roadmap, as is Dart support)
