### ISSUE TITLE
Result type

### ISSUE THREAD

**Issue by satvikpendem** [dart-lang/language#2697]
Does Dart have a general [Result type](https://en.wikipedia.org/wiki/Result_type)? ie, where instead of try-catching on exceptions, anything that can throw an exception is wrapped with either a success or failure case, (often languages call this the Ok and Error types respectively). The difference with try-catch is that it's usually coupled with exhaustive pattern matching, [which it seems Dart is getting soon](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/exhaustiveness.md) so that exceptions *must* be dealt with, while traditionally the programmer could forget in a try-catch based language.

It looks like [Dart already has a Result type, but it's only in the async library ](https://api.flutter.dev/flutter/async/Result-class.html)if I'm not mistaken, so I'm wondering whether that paradigm can be brought to the rest of the language as well. There are [some](https://pub.dev/packages/result_type) [packages](https://pub.dev/packages/freezed_result) [implementing](https://pub.dev/packages/okay) the concept already, often with a `when(success: ... , error: ... )` style syntax to simulate exhaustive pattern matching.

**Comment by munificent** [comment]
With pattern matching and sealed classes, yes, you will definitely be able to define a result type that works well with exhaustiveness. It would look like:

```dart
sealed class Result<V, E> {}

class Error<V, E> extends Result<V, E> {
  final E error;

  Error(this.error);
}

class OK<V, E> extends Result(V, E) {
  final V value;

  OK(this.value);
}

// Some example function returning a result:
Result<int, String> tryParseInt(String string) {
  var value = int.tryParse(string);
  if (value == null) return Error("Couldn't parse '$string'.");
  return OK(value);
}

// Use it:
main() {
  switch (tryParseInt("1234")) {
    case OK(:var value):
      print("Successfully parsed $value.");
    case Error(:var error):
      print("Failed to parse: $error");
  }
}
```

However, idiomatic Dart code uses exceptions or null return values for error handling, so you'll probably find that using Result types goes against the grain of the language and the ecosystem.

Rust and Haskell are very nice languages, but Dart is a different one with somewhat different priorities and ways of solving similar problems.

We don't have any plans to include a Result type in the core library.
