### ISSUE TITLE
Destructuring without `var`

### ISSUE THREAD

**Issue by water-mizuu** [dart-lang/language#2712]
Currently, my preferred code style is using explicit left-hand types in declaring variables. For example:

```dart
int foo = computeFoo();
List<int> bar = computeBar();
// and so on...
```

I disliked the `var` keyword because of it causes inconsistency on the right-hand side of the code.
```dart
var list = [1, 2, 3];
var list2 = <int>[]; // Now it's required to have a type annotation?
```
The thing for this though is that I think always keeping explicit container types with inline values is ugly. Or too verbose.

So declaring the variables with explicit types has been working for me, but when I saw the pattern specification, I got concerned because we are basically forced into using a keyword that we have been avoiding, and it causes even more inconsistency because it is only needed in pattern deconstruction contexts. 
```dart
int foo = 123;
var (int x, int y) = calculateCoordinates(); // Huh.
``` 

If anything, I just want to learn, what is stopping the syntax from just being as follows?:
```dart
(int x, int y) = calculateCoordinates(); // For explicit LHS type
var (x, y) = calculateCoordinates(); // For implicit LHS type
```

I think that the first line in the last block looks fine, and that the `var` is just unnecessary visual clutter. 

Especially in the revised `if-case` syntax, why is it warranted to add an extra keyword for declaration? I liked the infamous `if-case` syntax because it actually makes sense if one sees that it is from the `switch-case` statement, but it does look ugly from an outsider standpoint.
```dart
if (parseItems(line) case Items items) {
  // ...
}

if (Items items = parseItems(line)) {
  // This looks better from a pattern-matching standpoint, but I don't see why we need a `var` keyword there.
}
```

In fact, basing from the changelog, I think requiring `var` makes the statement worse.
```dart
if (var Items items = parseItems(line)) {
  // I thought we were supposed to avoid weird syntax like this?
}
if (parseItems(line) case Items items) {
  // Makes.. sense?
}
```

But honestly, that's just my opinion. I would love to hear from you guys who actually work on this language. Overall, thank you for everything you've done for Dart, and I look forward to seeing your guys' work from here on out.

**Comment by munificent** [comment]
> If anything, I just want to learn, what is stopping the syntax from just being as follows?:
> 
> ```dart
> (int x, int y) = calculateCoordinates(); // For explicit LHS type
> var (x, y) = calculateCoordinates(); // For implicit LHS type
> ```
> 
> I think that the first line in the last block looks fine, and that the `var` is just unnecessary visual clutter.

The former is the syntax C# uses for their pattern support. We discussed it heavily. I can't find the right issues now, but if you poke around in the issue tracker for closed issues labeled "patterns", you may be able to find the discussions. There are a few different problems we ran into, some of which I've forgotten.

But the main one is that almost all of our users *do* prefer using `var` or `final` to declare variables and C#'s syntax is more verbose for them:

```dart
(var x, var y, var z) = (1, 2, 3);
// Versus:
var (x, y, z) = (1, 2, 3);
```

The latter syntax is what destructuring looks like in most other languages: JavaScript, Rust, Swift, Kotlin, etc. We had a pretty strong sense that that's the syntax most users wanted. Of course, no syntax pleases everyone, but we tried to come up with something that looked right to as many people as we could.

**Comment by water-mizuu** [comment]
I can see that using `var` inside the destructuring does look terrible, but I am only looking at using types for them:
```dart
(var x, var y, var z) = (1, 2, 3); // That's unnecessary. Extract the `var` outside.
(int x, int y, int z) = (1, 2, 3); // This is better.
var (x, y, z) = (1, 2, 3); // This is also good in my opinion.
```

The question remains, will we be able to use the second line in declaring variables? I've read that we can basically declare assignment patterns, and considering that we can add type checks, then perhaps?

**Comment by leafpetersen** [comment]
> The question remains, will we be able to use the second line in declaring variables?

No, but you will be able to use:
```
var (int x, int y, int z) = (1, 2, 3); // This is better.
```
It is slightly more verbose, but I have to say, to my eye it looks better.
