### ISSUE TITLE
Issue with record equality logic

### ISSUE THREAD

**Issue by albertodev01** [dart-lang/language#2739]
I am reading [this](https://github.com/dart-lang/language/blob/8c8d93b8b6e776f3f2360cde5039c433f7efaeab/accepted/future-releases/records/records-feature-specification.md) part of the Record feature specification:

> Records have value equality, which means two records are equal if they have the same shape and the corresponding fields are equal. Since named field order is not part of a record's shape, that implies that the order of named fields does not affect equality:
> 
>```dart
>  var a = (x: 1, 2);
>  var b = (2, x: 1);
>  print(a == b); // true.
> ```

However, when I try to run this Dart code I get `false`:

```dart
void main() {
  const a = (1, 2);
  const b = (2, 1);

  print(a == b); // false.
}
```

This piece of code instead works as expected:

```dart
void main() {
  const a = (x: 1, 2);
  const b = (2, x: 1);

  print(a == b); // true.
}
```

The same also applies if I declare them with `var` or `final`. Why shouldn't named parameter "matter" in the comparison logic?

---

```dart
$ dart --version
Dart SDK version: 3.0.0-53.0.dev (dev) (Tue Dec 20 20:57:43 2022 -0800) on "windows_x64"
```

**Comment by Wdestroier** [comment]
It's working correctly as described by the specification. A possible explanation is because this matches the same behavior of method arguments. Some devs may prefer to put named values at the start and others at the end of the list.

**Comment by lrhn** [comment]
> if they have the same shape and the corresponding fields are equal.

Here "corresponding" means having the same name (for named fields) or position (for positional fields).
The `(1, 2)` and `(2, 1)` records are not equal because the corresponding (first and second) positional fields are not equal, `1 != 2` and `2 != 1`.
