### ISSUE TITLE
[Patterns] Ambiguity with the wildcards in object patterns

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#2745]
Patterns spec says nothing about the case when class contains a getter named `_` (or, at least, I didn't find it in the spec). What should we expect in the following case?
```dart
class C {
  int get _ => 42;
}

main() {
  C c = C();
  switch (c) {
    case C(:var _): print(_);
  }
}
```
Did we declare here a variable named `_` and the programm will print `42`? Or `_` is always a wildcard and `print(_)` is a compile time error?

**Comment by lrhn** [comment]
The `_` is always a wild card in a pattern. You'll have to write `case C(_: var underscore): ...` to read that particular getter. The `_` in the name part is a plain identifier, not a pattern.

**Comment by leafpetersen** [comment]
> We should probably say that `C(:var _)` is invalid, because it does not introduce an implicit name for a getter to read.

I at least attempted to specify this [here](https://github.com/dart-lang/language/pull/2682) (see the added section on name inference and the two references to it).

**Comment by lrhn** [comment]
My bad, I should have checked that we didn't already do it, before saying that we "probably should". We should, and we do, and that's good!

**Comment by sgrekhov** [comment]
Ah, it is specified that it is a compile-time error. Sorry, didn't notice that. I'll add appropriate tests. Closing this issue

**Comment by leafpetersen** [comment]
> Ah, it is specified that it is a compile-time error. Sorry, didn't notice that. I'll add appropriate tests. Closing this issue

I'm trying to remind myself to cc you when we make spec changes, but I usually forget.  Sorry.  :(
