### ISSUE TITLE
[Patterns Question]: Short-Circuiting of Object Destructuring

### ISSUE THREAD

**Issue by water-mizuu** [dart-lang/language#2754]
I want to ask, will object destructuring eventually be short circuited, i.e.:

```dart
Set<int> values = computeValues();
if (values case Set(length: 1, :var single) { // Does not throw a StateError
  print(single); 
} else if (...) {...}
```

In the specification, I'd assume that it is, or is it still unimplemented as of now? Thank you.

**Comment by munificent** [comment]
Yes, the runtime semantics for object patterns specify that fields are matched in order and that the object pattern fails to match as soon as a single field subpattern fails to match. Good question!
