### ISSUE TITLE
Downwards inference step for object patterns is underspecified.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2770]
(Thanks to @johnniwinther for noticing this problem)

In the section [Type checking and pattern required type](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#type-checking-and-pattern-required-type), we say this:

> To type check a pattern `p` being matched against a value of type `M`:
>
> ...
>
> *   **Object**:
>
>     1.  Resolve the object name to a type `X`. It is a compile-time error if the name does not refer to a type. Apply downwards inference from `M` to infer type arguments for `X` if needed.

But downwards inference isn't guaranteed to produce types, it produces *type schemas*.  For example, in this code:
```dart
class Class<T extends Object> {
  T field;
  Class(this.field);
}
method1(Object object) {
  if (object case Class(:var field)) { ... } // (1)
}
```
At (1), downwards inference will infer a type of `Class<?>`, because the matched value type of `Object` doesn't provide enough information to fully constraint the type parameter.

We really need a type here, because the next step is to look up the type of the getter and use it as the matched value type when recursively type checking the subpattern `:var field`.

**Comment by stereotype441** [comment]
Currently, the analyzer implementation copes with this problem by performing an extra step after downwards inference: it replaces any instances of the unknown type (`?`) with `dynamic`.  But I can think of a few alternatives that might be better:

(1) Maybe we should replace `?` with `Object?` instead of `dynamic`, to reduce the amount of unexpected dynamism in the user's code.

(2) Maybe we should replace `?` with `Never` in contravariant positions, to reduce user surprise in the case where the type in question is a type alias, e.g.:
```dart
typedef UnaryFunction<T> = void Function(T);
void f(int i) { ... }
main() {
  Object object = f;
  if (object case UnaryFunction()) {
    // The user probably expects this pattern to match, because `f` is a unary function.
    // But if our rule is to replace `?` with `Object?` or `dynamic`, then it won't match, because
    // `f` isn't a `UnaryFunction<dynamic>`.
  }
}
```
Note that if we go with this approach, we'll want to carefully consider what happens if a type argument to the type alias appears in both covariant and contravariant positions, e.g.:
```dart
typedef A<T> = T Function(T);
f(Object object) {
  if (object case A()) {
    // What function types match here?
  }
}
```

(3) Maybe we should just use the "instantiate to bounds" algorithm on any types that remain unknown after downwards inference.  This would be consistent with what we do for ordinary invocation inference, except that for ordinary invocation inference, there are extra steps between downwards inference and instantiate to bounds where we account for the types of the arguments; we would skip those steps because the sub-patterns of the object pattern aren't really "arguments".

**Comment by stereotype441** [comment]
CC @munificent @leafpetersen @jakemac53 @lrhn @mit-mit @natebosch @eernstg @kallentu

**Comment by eernstg** [comment]
Instantiation to bound (approach 3) will use the bounds whenever possible, but it can produce types containing `dynamic` in the case where an F-bound is resolved. (For instance, with `class A<X extends A<X>> {}`, the raw type `A` means `A<A<dynamic>>`).

We could introduce a variant of instantiation to bound that uses `Object?` rather than `dynamic` when it needs to invent a top type, and then we could gradually switch to use that algorithm in more and more situations, starting with the downwards inference on object patterns.

**Comment by eernstg** [comment]
@stereotype441 wrote in the initial comment:
> We really need a type here, because the next step is to look up the type of the getter and use it as the matched value type when recursively type checking the subpattern `:var field`.

I would assume that a pattern in a declaration context could yield a non-trivial type schema (like `Class<_>`), and that type schema would be used as the context type during type inference of the initializing expression, and the resulting initializing expression type would then be used as a kind of context type during type checking of the pattern.

In a matching context we would only have the last two steps, but this still means that the pattern could give rise to a type schema like `Class<_>` and this could be used to give the pattern the static type `Class<Something>` based on the static type of the matched object.

In the original example `if (object case Class(:var field)) { ... }` there is no information because the type of `object` is `Object`, but it could have been `Class<T>` for some specific type `T`, and we could then infer `Class` to have type argument `T`, and `field` to have the type which is taken from the `Class<X>.field` getter, substituting `T` for `X`.

**Comment by stereotype441** [comment]
In further discussion with @johnniwinther, we realised that:
1. the current analyzer behaviour is actually more subtle than what I said above; it replaces `?` with `dynamic` only when the corresponding type parameter has no bound.  When there *is* a bound, it replaces `?` with the bound.
2. this is actually a problem for f-bounded types, because the bound may contain other type variables.

I'm going to try fixing this by changing both the analyzer and the CFE to use "instantiate to bounds" (permitting super-bounded types).

**Comment by eernstg** [comment]
Sounds good! Instantiation to bounds uses `dynamic` in a number of situations where we could have used `Object?` (but it was so far considered too breaking). But we might as well try to nudge that behavior in the direction of improved static type safety by evolving instantiation to bounds, which will then propagate to all usages consistently.

**Comment by leafpetersen** [comment]
I meant to follow up on this.  I think my thinking is generally aligned.  With normal inference, when matching a schema `K` against a generic constructor for a class `C<T0, ..., Tn>`, the steps you do are: 
  - First do downwards inference (subtype match `K <# C<T0, ..., Tn>`) to solve for `T0...Tn`
  - For any of the `Ti` which are constrained by the matching, fix them with a solution
  - Do upwards inference to (possibly) constrain more of the `Ti`
  - Do instantiate to bounds (using the partial solution from downwards and upwards inference) to fill in anything left unconstrained.

With patterns, there is no upwards step. I think this means we should just do exactly the above, except we leave out the "Do upwards inference..." step.  Does this correspond to your thinking @stereotype441 ?

**Comment by stereotype441** [comment]
> I meant to follow up on this. I think my thinking is generally aligned. With normal inference, when matching a schema `K` against a generic constructor for a class `C<T0, ..., Tn>`, the steps you do are:
> 
> * First do downwards inference (subtype match `K <# C<T0, ..., Tn>`) to solve for `T0...Tn`
> * For any of the `Ti` which are constrained by the matching, fix them with a solution
> * Do upwards inference to (possibly) constrain more of the `Ti`
> * Do instantiate to bounds (using the partial solution from downwards and upwards inference) to fill in anything left unconstrained.
> 
> With patterns, there is no upwards step. I think this means we should just do exactly the above, except we leave out the "Do upwards inference..." step. Does this correspond to your thinking @stereotype441 ?

Yes, precisely.  And fortunately we can re-use all of the existing logic for normal inference so this is actually simpler than what we were doing before (https://dart-review.googlesource.com/c/sdk/+/290613).
