### ISSUE TITLE
Invocations of `super`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2772]
I just noticed that we have constructs of the form `super(...)`/`super<...>(...)` in a test, with the intention that it works like `super.call(...)`/`super.call<...>(...)`.

Concretely, [all_kinds_test.dart](https://github.com/dart-lang/sdk/blob/main/tests/language/named_arguments_anywhere/all_kinds_test.dart) contains the following:

```dart
    414     // Using super.call() implicitly.
    415     runAndCheckEvaluationOrder([1, "2", false, 3.14], () {
    416       super(evaluate(1), evaluate("2"), z: evaluate(false), w: evaluate(3.14));
    417     });
    418     runAndCheckEvaluationOrder([1, false, "2", 3.14], () {
    419       super(evaluate(1), z: evaluate(false), evaluate("2"), w: evaluate(3.14));
    420     });
    421     runAndCheckEvaluationOrder([false, 1, "2", 3.14], () {
    422       super(z: evaluate(false), evaluate(1), evaluate("2"), w: evaluate(3.14));
    423     });
    424     runAndCheckEvaluationOrder([3.14, 1, "2", false], () {
    425       super(w: evaluate(3.14), evaluate(1), evaluate("2"), z: evaluate(false));
    426     });
    427     runAndCheckEvaluationOrder([1, 3.14, "2", false], () {
    428       super(evaluate(1), w: evaluate(3.14), evaluate("2"), z: evaluate(false));
    429     });
    430     runAndCheckEvaluationOrder([1, 3.14, "2"], () {
    431       super(evaluate(1), w: evaluate(3.14), evaluate("2"));
    432     });
```

However, these constructs are actually not derivable in the grammar as specified (in the language specification, or in any current feature specification that I can find).

Do we wish to change the grammar such that it admits invocations where the function is denoted by `super`? Or do we want to keep it specified as an error, and request changes in the parser such that it is reported as a compile-time error?

I suppose this will be a revert of a change where it was made possible, it has always been a syntax error&mdash;but hopefully the change is rather small. It is technically a breaking change, but I doubt it is widely used.

**Comment by eernstg** [comment]
@munificent @mit-mit @leafpetersen @jakemac53 @lrhn @natebosch @kallentu @stereotype441, do you think it's better to maintain that this is a syntax error (and accept the breakage, if any)? .. or would it be better to generalize `super` to be an expression in the grammar? .. or would we just enable invocations like `super(...)` and `super<...>(...)` and not otherwise turn `super` into an expression? .. or do something completely different?

**Comment by lrhn** [comment]
I see this in the spec:
```ebnf
<primary> ::= <thisExpression>
  \alt \SUPER{} <unconditionalAssignableSelector>
  \alt \SUPER{} <argumentPart>
  ...
```
That should allow `super(args)` and `super<typeArgs>(args)` as I read it.

In general, the `super` term should be a valid *receiver* (target of selectors) for any valid object instance member invocation, but unlike other such things, it can't also have no selectors or treated as a value itself in other ways (so no `!` , `?.id` or `?[..]` selectors, and not a cascade target).

The `<primary>` production above, and the `<assignableExpression>` production
```ebnf
<assignableExpression> ::= <primary> <assignableSelectorPart>
  \alt \SUPER{} <unconditionalAssignableSelector>
  \alt <identifier>
```
should cover those uses.

**Comment by eernstg** [comment]
> That should allow `super(args)` and `super<typeArgs>(args)` as I read it.

You're right, good catch! That alternative was added to the `<primary>` grammar rule in b26e7287c318c0112610fe8b7e175289792dfde2, but the corresponding spec parser update has not been performed. The spec parser is updated in https://dart-review.googlesource.com/c/sdk/+/279092.

So we _did_ decide that we would support this case, and I can close this issue.
