### ISSUE TITLE
Use context type schema from the pattern in a pattern-for-in statement?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2775]
Consider a pattern-for-in statement where the iterable is subject to non-trivial inference:

```dart
List<(X?, bool)> f<X>() => [(null, true)];

void main() {
  for (var (int? i, b) in f()); // Report an error, or infer `f<int>()`?
}
```

I can't spot any location in the patterns feature spec where the approach taken during type inference is spelled out for this case.

I'd expect that type inference uses the context type schema of the pattern during inference of the iterable, here: `f()`, and in the given example it would infer the type argument `int` (and there's no error). This would also match the inference behavior in the following example:

```dart
List<X?> f<X>() => [null];

void main() {
  for (int? i in f()); // Infers `f<int>()`.
}
```

@munificent, do you think this is already covered? A couple of places where I expected to find it is [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#pattern-for-in-statement) or [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#:~:text=Calculate%20the%20static%20type%20of%20the%20matched%20value).

Otherwise, and asking @stereotype441 @leafpetersen @jakemac53 @kallentu @lrhn @mit-mit @natebosch as well, WDYT?

**Comment by munificent** [comment]
> @munificent, do you think this is already covered?

No, I missed it. I'll add it.
