### ISSUE TITLE
Broken link?

### ISSUE THREAD

**Issue by zeritonius** [dart-lang/language#2791]
On this page:
[https://github.com/dart-lang/language/blob/master/LICENSE](https://github.com/dart-lang/language/blob/master/LICENSE)
it says:

The following license applies to all parts of this repository.
See [http://github.com/dart-lang/sdk/blob/LICENSE](http://github.com/dart-lang/sdk/blob/LICENSE) for the license
of the Dart language implementation.
I received a "page not found" when I tried to access it. I tried with http like it was specified and also with https - both gave the same result.

What is the correct link, please?
Thank you.

**Comment by parlough** [comment]
The intended link here seems to be: https://github.com/dart-lang/sdk/blob/main/LICENSE

**Comment by zeritonius** [comment]
Thank you. Appreciate it.
