### ISSUE TITLE
Is there an error/warning on impossible patterns?

### ISSUE THREAD

**Issue by mnordine** [dart-lang/language#2800]
```dart
final result = switch ([1,2,3]) {
  [a, ...] => a,
  [a, b, c] => c, // not possible, error, lint, warning, or silent?
};
```
I'm almost certain this was discussed, but I can't find it.

**Comment by mnordine** [comment]
So it's a static error?

**Comment by munificent** [comment]
I'm not sure if unreachable cases will be a warning or an error. (They are harmless dead code, so typically that would mean making them a warning.) But either way, yes, the compiler should tell you *something* about unreachable cases.
