### ISSUE TITLE
incorrect multiplication result of 555.55 * 100 

### ISSUE THREAD

**Issue by samuelhowell** [dart-lang/language#2802]
https://dartpad.dev/?id=0302b4ceae7426ed7e68f9878d80556e

**Comment by mraleph** [comment]
That's just how floating point works. That's why, for example, it is unadvisable to use floating point numbers for financial calculations.

See https://floating-point-gui.de/ for explanation.

**Comment by samuelhowell** [comment]
Of course🤦 this is something I was aware of before but have never had to worry much about precision until recently. 
My bad for the erroneous bug ticket. Thanks for the link @mraleph
