### ISSUE TITLE
Exhaustiveness on map patterns

### ISSUE THREAD

**Issue by gnprice** [dart-lang/language#2818]
In the patterns spec, at the runtime semantics for a map pattern ([permalink](https://github.com/dart-lang/language/blob/92fa381e5e9913b644561912ffa90d39804d02c8/accepted/future-releases/0546-patterns/feature-specification.md#matching-refuting-and-destructuring)), there's this explanatory remark:

> *An empty map pattern can match only empty maps. Note that this treats a misbehaving map whose `length` is negative as an empty map. This is important so that a set of map patterns that is clearly exhaustive over well-behaving maps will also cover a misbehaving one.*

The wording is very similar to a remark in the list section above it, where it's a reference to #2701. But I think the current spec doesn't actually accomplish this for maps (unlike lists). On the other hand, I'm not sure this property matters much for maps, because (unlike lists) I think there's no common pattern that would lead to a set of map patterns that has any hope of being exhaustive, except using `{...}`.

Here's a set of map patterns that is clearly exhaustive over well-behaving maps:
```dart
String test(Map<bool, int> map) => switch (map) {
    {} => 'unknown',
    {false: _} => 'false',
    {true: _} => 'true',
    {false: _, true: _} => 'contradiction',    
};
```

But if we pass this a map whose `length` reports 1 but whose `[]` and `containsKey` deny containing any keys ([dartpad](https://dartpad.dev/?channel=master&id=55a5691a6d2ae00eaf87a76b8f6a3fd1)), it will not match. The patterns `{false: _}` and `{true: _}` will get past the length check, but then find that the respective keys are absent.

For that matter, if we pass a map whose `length` reports 3, or any number ≥3, this will not match.

It also won't match if the map's `length` reports 2, but its `[]` and `containsKey` only accept one key: e.g. `map[false] != null` but `map[true] == null`. The only patterns that could match such a map would be patterns with duplicate keys:
```dart
    {false: _, false: _} => 'double',
```
but the spec already rightly forbids those.

---

The basic options here are:
1. Accept that no sets of map patterns without `{...}` are exhaustive; users will have to write unnecessary default or `{...}` cases.
2. Come up with a semantics that accepts at least some legitimate cases as exhaustive, while being sound in the face of misbehaving maps.

I think (2) will be hard, and there aren't a lot of legitimate cases it would benefit, so that the right answer will be (1). But perhaps someone will see a clever solution.

The basic reason it's hard while lists are doable is that when a list tells us its length `n`, that also tells us exactly which keys should be valid: 0, 1, 2, …, n-1. We'll go probing some of those keys according to the pattern, and if the list changes its mind and says they're absent then it can only do so by throwing an exception. But when a map tells us its length, then except in unusual cases we still don't know of any key that must be present. So the list could keep denying every key we ask it about, and unless we keep careful track we'll never catch it in a contradiction.

**Comment by lrhn** [comment]
Exhaustiveness is non-trivial. 

The issue here is that you know, for certain, that a `Map<bool, X>` can only have up to two entries.

That's probably always true, but counting map keys for enum-like types is not something we're currently doing, and not something we can *safely* do, because the `Map` interface can be subverted by non-conforming implementations.

Imagine a `NastyMap implements Map<bool, int>` which claims to have three keys, and if you iterate them, you get `true`, `false`, and `true` again. That's *possible* to implement, which means that we cannot let exhaustiveness rely on maps always being reasonable, because exhaustiveness affects type inference, and type inference affects soundness.
Being unsound is not an option.

So, I don't think this particular variant of exhaustiveness is going to be recognized.

**Comment by munificent** [comment]
> I think there's no common pattern that would lead to a set of map patterns that has any hope of being exhaustive, except using `{...}`.

That's correct. If you want to exhaustively match maps, you'll have to use `...`. The remark in the spec is that the language *should* consider this exhaustive:

```dart
switch (map) {
  case {...}: ...
}
```

But if we aren't careful how we handle maps that claim to have a negative length, then it's possible that that case wouldn't match such a badly-behaving map.

In general, yes, exhaustiveness checking won't help you that much with maps. But when you do cover all (reasonable) maps, the compiler should agree with you.

**Comment by gnprice** [comment]
> That's correct. If you want to exhaustively match maps, you'll have to use `...`. The remark in the spec is that the language _should_ consider this exhaustive:
> 
> ```dart
> switch (map) {
>   case {...}: ...
> }
> ```

Cool, that makes perfect sense, thanks.

I think the existing remark sounds more like it's about `{}`, though, given the context where it appears. Just sent #2825 to perhaps make that clearer, and also be more explicit about what sets of map patterns can be exhaustive (namely, just those with `{...}`).
