### ISSUE TITLE
Easy way to define a `inline class` which inherits all members of the base class.

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/language#2854]
`typedef` is a easy way to define a alias of a type, but it doesn't have separate static type to be completed, inferred or checked.
On the other hand, `inline class` doesn't inherit members of base class.
I want to have easy way to define a `inline class` which inherits all members of the base class.

For example,

```dart
inline class Db = Map<int, String>;
```

**Comment by rubenferreira97** [comment]
I really wish something like this was possible. Sometimes I only want to define a superset of operations to a custom type. Forwarding the whole constructor is verbose (and in this cases I don't really want to create a new class, just inline it). 

Example with an extension:

```dart

inline class MyCustomMap<K,V> = Map<K,V>;

extension on MyCustomMap<K,V> {
   void fancyMethod() => print('Fancy');
}

final Map<int,int> map = {1:1};
map.fancyMethod(); //compile error
final MyCustomMap<int,int> fancyMap = {1,1};
fancyMap.fancyMethod(); //fine
```

**Comment by Cat-sushi** [comment]
A modifier might be better to override(?) some members of the base class.

```dart
inline class LruCache<K, V> {
  inherit Map<K, V> map;
  static int size = 100;

  @override // ?
  V? operator [](K key) {
    var value = map.remove(key);
    if(value == null) {
      return null;
    }
    map[key] = value;
  }

  @override // ?
  void operator []=(K key, V value) {
    map.remove(key);
    map[key] = value;
    if(map.length > size) {
      map.remove(map.keys.first);
    }
  }
}
```

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/issues/2506.

**Comment by Cat-sushi** [comment]
@eernstg Thank you for your information.
#2506 satisfies my wants.
Closing this issue as duplicated.
