### ISSUE TITLE
Enhance `switch-case` syntax

### ISSUE THREAD

**Issue by techwnn** [dart-lang/language#2859]
Currently, there is 2 pain spot for syntax of `switch-case`:
1. Every case must ended with break;
2. We can not place multiple variables following case.

The current syntax is like this:
```
final command = "hello";
switch(command) {
    case "hello":
    case "world": {
      print(command);
      break;
    }
    default: {
      print('default');
    }
}
```

I think the syntax in Kotlin is more concise, which solve the 2 pain spot above like below:
```
val command = "hello"
when (command) {
    "hello", "world" -> {
        println(command)
    }
    else -> {
        println("else")
    }
}
```

So maybe we can introduce `when` syntax and encourages user migrate to use `when`, and delete `switch-case` in the future. 

Or we still use `switch` keyword, but introduce new syntax like `when`, and the compiler still compatible for old syntax in library for some time.

**Comment by lntls** [comment]
See [Switch expression](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#switch-expression).

**Comment by mraleph** [comment]
This is part of Dart 3 patterns feature.
