### ISSUE TITLE
Short-circuiting null check operator

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/language#2862]
Currently, instead of doing
```dart
a == null ? null : b
```
We can do
```dart
a ?? b
```

And instead of doing
```dart
a == null ? null : a.method()
```
We can do
```dart
a?.method()
```

However, we can't do this for other expressions, like function calls.
```dart
a == null ? null : f(a)
```
I propose a short-circuiting null check operator, so we can change the previous to this
```dart
f(??a)
```

Or convert this
```dart
a == null ? null : b == null ? null : a + b
```
into
```dart
??a + ??b
```

It can also be short-circuiting so in this example if `f()` is null then `g` won't be called:
```dart
??f() + ??g()
```

The operator itself doesn't have to be double question marks.

**Comment by lrhn** [comment]
Specifically issue #1592, which even tries to summarize all the other ideas.

**Comment by munificent** [comment]
I'm going to go ahead and close this in favor of the other related issue and label.
