### ISSUE TITLE
Boolean compound assignment operators should short-circuit if possible

### ISSUE THREAD

**Issue by anqit** [dart-lang/language#2864]
Currently, there is an inconsistency between the behavior of boolean compound assignment operators (`|=` and `&=`) and their plain syntax supposed-to-be-equivalents, in that the former does not use short-circuiting when the left operator determines the result of the boolean expression so the right operator does not need to be evaluated. This dartpad demonstrates the difference:
https://dartpad.dev/?id=cab11271c6d481729b457e5a1585aa88

I believe that the assignment operators should be updated to use short-circuiting when possible.

**Comment by lrhn** [comment]
That should be `&&=` and `||=` instead.  See https://github.com/dart-lang/language/issues/23

**Comment by anqit** [comment]
@lrhn is there a specific language version that `&&=`/`||=` is found in? I've tried modifying my code to use those operators instead and it is not compiling

**Comment by natebosch** [comment]
`&&=` and `||=` are not existing language features. This issue is closed as a duplicate of #23 which is an existing issue requesting them as new features.
