### ISSUE TITLE
Exhaustiveness for bool values used in switch case

### ISSUE THREAD

**Issue by luiges90** [dart-lang/language#2888]
Currently, the following code does not compile. The error is `Error: A non-null value must be returned since the return type 'TriState' doesn't allow null.`

```
enum TriState { none, forceFalse, forceTrue }

extension TriStateFrom on bool? {
  TriState toTriState() {
    switch (this) {
      case null: return TriState.none;
      case false: return TriState.forceFalse;
      case true: return TriState.forceTrue;
    }
    // unreachable code.
  }
}
```

However, as the input value is `bool?`, there are only three possible values which I have exhausted. There are no case where no values are returned. Hence this code should compile. Same goes to non-nullable `bool`.

While currently we can add a default return or `throw AssertionError();` to workaround this issue, it would be nice if the language could recognize this use case.

**Comment by Wdestroier** [comment]
Would a switch expression work?
```dart
  TriState toTriState() {
    return switch (this) {
      null => TriState.none,
      false => TriState.forceFalse,
      true => TriState.forceTrue,
    }
  }
```

**Comment by munificent** [comment]
When exhaustiveness checking is fully implemented, it should do what you want here. The implementations just aren't done yet.
