### ISSUE TITLE
Update augmentation libraries spec for class modifiers

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2892]
I think probably we should just add a requirement that augmented class declarations must re-declare all the same modifiers as the original class.

Note that the macro implementation for generating augmented classes will also have to be updated.

We could also allow augmentation libraries to add class modifiers to existing classes, but IMO that would be a mistake. You should be able to see all the modifiers on a class when looking at the original definition.

**Comment by munificent** [comment]
> I think probably we should just add a requirement that augmented class declarations must re-declare all the same modifiers as the original class.

Me too.

> We could also allow augmentation libraries to add class modifiers to existing classes, but IMO that would be a mistake.

Yeah, that sounds like a bad idea to me too.
