### ISSUE TITLE
Warning/lint for switch case constants that will never be == to the matched value type

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2894]
## Background

In Dart 3.0, switch cases are now patterns. In addition to all the fun new pattern stuff, we have also tweaked switch cases that are still simply constant expressions. Previously, the language required switch case constants to have the same type as the matched value, and the constant's type had to have primitive equality. Both of those restrictions are now removed.

This is a useful change, because it means you can use switch statements for user-defined "value-like" types that have their own notion of equality, like:

```dart
class Point {
  final int x, y;
  const Point(this.x, this.y);

  bool operator ==(Object other) =>
      other is Point && x == other.x && y == other.y;

  int get hashCode => Object.hash(x, y);
}

String describe(Point p) {
  const origin = Point(0, 0);
  const unitX = Point(1, 0);
  const unitY = Point(0, 1);

  switch (p) {
    case origin: print('origin');
    case unitX: print('unit x');
    case unitY: print('unit y');
    default: print('other');
  }
}
```

You can even use switch statements for types whose implementation of `==` can return true when passed instances of *other* types. That's not likely to be useful often, but could potentially be handy for things like units of measure.

However, we've lost useful static checking in the process. This no longer produces any error or warning:

```dart
switch ('not a number or a bool') {
  case 123: print('wat');
  case true: print('no way');
  default: print('ok');
}
```

## Unrelated types and primitive equals

Because the case constant is a constant, we know not just its static type, but the actual concrete type of the constant instance at compile time. This means we can tell whether or not the type has primitive equality, or some other `==` known to the platform.

We could report a warning (or have a lint that reports a warning) if we know that the matched value's static type will never match, as in:

```dart
class NoCustomEquals {}

class Unrelated {}

test(Unrelated other) {
  switch (other) {
    case const NoCustomEquals(): print("can't match");
  }
}
```

Here, since `NoCustomEquals` has primitive equality, which for object types is based on identity, and the compiler knows that a constant instance of concrete type `NoCustomEquals` will never have the same identity as any instance of `Unrelated` (since `Unrelated` isn't a supertype of `NoCustomEquals`), I think the compiler can tell this switch case is pointless.

Note that we don't need `NoCustomEquals` and/or `Unrelated` to be sealed for this to work. Since we know the actual constant *object* that we're calling `==` on, we know its concrete instance type.

## User-defined equals

It would be nice to report warnings for clearly pointless cases even on types with user-defined equals, like `Point` above:

```dart
const origin = Point(0, 0);

switch ('not a point') {
  case origin: print('origin');
  default: print('other');
}
```

This is harder because `Point.==()` accepts `Object` on the right hand side, so for all the compiler knows (without trying to actually analyze the code in the function body), it *could* match a string.

I think we can live with this. If we want to do something here, we could possibly suggest that when defining `==` that expects an object of a certain type, instead of simply returning `false` if the argument isn't that type, make it a *runtime error* to call `==` with an unsupported type. If that policy works OK for the class (it might not if users need to use their type in heterogeneous sets, etc.), then they can implement that policy like:

```dart
class Point {
  final int x, y;
  const Point(this.x, this.y);

  bool operator ==(covariant Point other) => x == other.x && y == other.y;

  int get hashCode => Object.hash(x, y);
}
```

And now, thanks to the `covariant Point`, the compiler can see exactly which type the `==` expects and we could warn if the argument isn't that type.

But now consider:

```dart
class Point {
  final int x, y;
  const Point(this.x, this.y);

  bool operator ==(covariant Point other) => x == other.x && y == other.y;

  int get hashCode => Object.hash(x, y);
}

class Unrelated {}

main() {
  switch (Unrelated()) {
    case const Point(1, 2): print('(1, 2)');
    default: print('other');
  }
}
```

Can that case ever match? It seems like no, but for all the compiler knows, there could be:

```dart
class UnrelatedPoint implements Point, Unrelated {}
```

So there *could* be instances of `Unrelated` that are `Point`s. For this checking to work, we'd probably have to restrict it to types that are sealed or final so that the compiler knows that if the RHS of `==()` and the matched value have unrelated types, that there can't be any other subtype that combines them.

All of this may be overkill. I think we'll get most of the value by simply warning in cases where the case constant has primitive equality and the matched value is a type that we know can't match.

Thoughts @dart-lang/language-team?

**Comment by munificent** [comment]
Note that #2632 is a special case of this.

**Comment by scheglov** [comment]
BTW, the warning for primitive equals is already implemented in the analyzer.
<img width="556" alt="image" src="https://user-images.githubusercontent.com/384794/223919653-68a09f11-0a03-474b-b700-ebefaee4786a.png">

**Comment by mit-mit** [comment]
Given we already have the warning for primitive equals, do we perhaps have enough for 3.0, and can wait and see what user feedback we get on this topic?
