### ISSUE TITLE
Inconvenient to build a generic List<T> method

### ISSUE THREAD

**Issue by timsneath** [dart-lang/language#2903]
## Describe the problem you are trying to solve, why is it hard to solve today?

Consider the [following example](https://dartpad.dev/?id=f31879fc22ef2bb67ccac65ea106f063):
```dart
class Range<T extends num> {
  final T from;
  final T to;

  num get magnitude => to - from;

  Range(this.from, this.to);

  factory Range.fromList(List<T> list) {
    assert(list.length == 2);
    return Range(list.first, list.last);
  }
}

// Extension on Iterable<Range<T>> is not allowed. Error given:
// The name 'T' isn't a type, so it can't be used as a type argument.
extension RangeOfRanges on Iterable<Range<num>> {
  Range<num> range() {
    final min = (map((range) => range.from).toList()..sort()).first;
    final max = (map((range) => range.to).toList()..sort()).last;

    return Range<num>(min, max);
  }
}

void main() {
  final intRange = Range(-3, 6);
  print(intRange.magnitude);
  print(intRange.magnitude.runtimeType); // int, all good so far

  final rangeList = <Range<double>>[
    Range(3.5, 5.3),
    Range(6.3, 9.2),
    Range(-3.0, 13.1),
  ];
  final rangeOfRanges = rangeList.range();
  // I want to call a function that accepts Range<double>.
  print(rangeOfRanges.runtimeType); // Range<num> :(

  final nastyWorkaround =
      Range(rangeOfRanges.from.toDouble(), rangeOfRanges.to.toDouble());
  print(nastyWorkaround.runtimeType); // Finally: Range<double>
}
```

In this scenario, I have created a class `Range` that can accept any numeric type. I want to create a series of extension methods that work on instances of `Iterable <Range>`. I can't create them as extension methods of `Iterable<Range<T extends num>`, because generics are not allowed. I can create them as extensions of `Iterable <Range<num>>`, but then the return type must be `num`. But I don't want a `Range<num>`, I want a `Range<double>`. 

The best way I can find so far to make this work is either the nasty workaround shown above, of copying the output. Another alternative is to create the extension methods for every subtype in `T extends num`, but that's laborious and duplicative. And it's only viable in a scenario like this where there are are a small and known number of subtypes.

Am I missing an alternative? If not, is there a feature we should put on the roadmap for this kind of thing?

**Comment by mateusfccp** [comment]
You can define your extension as:

```dart
extension RangeOfRanges<T extends num> on Iterable<Range<T>> {
  Range<T> range() {
    final min = (map((range) => range.from).toList()..sort()).first;
    final max = (map((range) => range.to).toList()..sort()).last;

    return Range<T>(min, max);
  }
}
```

**Comment by lrhn** [comment]
A bigger issue is that you'd probably want `T get magnitude => (to - from) as T;`.

There's no good way around that cast because of how `num.-` is typed.

**Comment by timsneath** [comment]
Ah, you can apply a generic to the _name_ of the extension? That's something new I learned today! Thank you, @mateusfccp. 

@lrhn I'll let you know if I regret it :)
