### ISSUE TITLE
Could macros expose the source's identity of a function/class/method for hot-reload's sake?

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#2905]
Hello!
This is about a problem I believe macros currently do not allow implementing when build_runner does.

This is about empowering stateful-hot-reload for packages by using code generation.
Build_runner allows implementing this today, but the current macro proposal would afaik not allow it.

### Context

Currently, Hot-reload currently is an "all or nothing" kind of thing.  A package cannot know if a specific function has changed after a hot reload.  
This is problematic as it prevents being more granular with hot-reload logic.

An example would be a network-request caching package:
After a hot reload, we would want to retrigger the network requests that had their source changed.
We don't want to trigger **all** the requests again, as this would effectively be a hot restart instead of a hot reload. Yet we don't want to keep all the cache either, as otherwise, the hot reload will do nothing.  

One package of mine (riverpod) solved this problem using code generation.  
The idea is, when a user writes a network request using the said package, the code-generator generates an MD5 of the source of the said network request.   

For example, given:

```dart
@cached
Future<int> function() => fetchSomething();
```

The code-generator may generate (simplified for the sake of example. I removed my package logic):

```dart
const _functionHash = "md5-hash of function";
String? _cacheKey;
late Future<int> _functionCache;

// Function augmentation to cache the execution.
Future<int> function() {
  // TODO strip the hash in release mode. It's just an example
  if (_cacheKey == _functionHash) return _functionCache;
  _cacheKey = _functionHash;
  return _functionCache = super.function();
}
```

Then on source change, the `_functionHash` will be updated. And when `function` will be executed, `_cacheKey` will be different from `_functionHash`, making the function re-execute.

This is a simplified explanation of how [riverpod_generator](https://pub.dev/packages/riverpod_generator) was able to implement its hot-reload support, and it works quite well!

### Problem

Although the previous example works well, afaik the current metaprogramming proposal will severely limit this feature.
The reason is: Macros currently apparently will be unable to inspect the AST of a function/class. But this feature relies on it.

The reason this feature relies on AST visiting is that it's not a simple "toSource". The idea is that we want to detect any change that impacts the execution of a function.  
An example would be a hot reload which introduces the following changes

```diff
int doSomething() {
+ return 42;
- return 21;
}

@cached
int functionWithMacro() {
  return doSomething();
}
```

In that scenario, the source of `functionWithMacro` hasn't changed. Yet after a hot reload, that function has a different behavior, so we would want to consider that this function has changed and re-execute it.

Using build_runner this could be fixed by inspecting the AST of `functionWithMacro`. Then, we would be able to visit the source of `doSomething` and have a change in `doSomething` impact the hash of `functionWithMacro` too. 

But unless I missed something, the current macros proposal does not enable AST visiting. As such the scenario that I described wouldn't be supported anymore.  
This is a pretty common scenario for the feature I've described, so it would seriously hinder the user experience after migration.

**Comment by jakemac53** [comment]
The reason we have so far avoided exposing a full AST is it would _significantly_ expand the surface area of the API - and in such a way that is _much_ more likely to have breaking changes in the future as well.

We could probably expose a `Code` object for function bodies though - this would not really be a full AST, although you could use something like the analyzers parser and _get_ a full AST from it (you can generate a raw string from a Code object fairly easily). This would keep the AST class in a separate package which helps with versioning concerns. Also if you only care about the string contents of the function, as it seems here, you could avoid parsing it at all.

How does that sound? Would that cover some of the other use cases also?

**Comment by rrousselGit** [comment]
Wouldn't using analyzer to parse the AST be really inefficient?

**Comment by jakemac53** [comment]
> Wouldn't using analyzer to parse the AST be really inefficient?

It's the same parser the compiler would use. There would be some duplication of work for sure, but the parser is fast.

I would also presume that this won't be applied to every function in the program etc. We would most likely only provide these Code objects on demand where requested. TBH I wouldn't be surprised if the parsing overhead is similar to the corresponding serialization overhead of AST node objects.

**Comment by jakemac53** [comment]
We could also explore exposing more directly some identity hash as the title originally requests, that would be less chatty in terms of the protocol. We would still want you to have to request it on demand, so that we can optimize invalidation (generally method body modifications don't necessitate a macro re-invocation, but if you ask for identity it would).

**Comment by rrousselGit** [comment]
Indeed. I was originally about to ask for this; but figured it made more sense to keep the issue generic.
If there's a decent performance gain, I'd love it to be more integrated like this. 

> The larger issue would probably be having analyzer as a dependency of a macro - one of the largest costs of macros will actually be compiling the macros themselves. Having heavy dependencies like analyzer will make them quite slow.

I assume this cost would only happen once on start right?

> I would also presume that this won't be applied to every function in the program etc. 

A lot of functions are probably going to be parsed this way though. In my case, most of the user logic is contained within such functions.
Although I don't need to parse hosted dependencies as they don't change (but need to traverse path dependencies as they _do_ change :P).

**Comment by jakemac53** [comment]
> I assume this cost would only happen once on start right?

Or if a macro or any of its deps are modified, but generally yes. It still can add significant time though, the analyzer is very large and it takes several seconds to compile even the most basic app that imports it.

> A lot of functions are probably going to be parsed this way though. In my case, most of the user logic is contained within such functions.

Can you define a lot at all? Is this like multiple functions per widget?

> Although I don't need to parse hosted dependencies as they don't change (but need to traverse path dependencies as they _do_ change :P).

This is probably not something  you will be able to optimize around in the macro world. But either way if those deps don't change your macro won't re-run on them. With incremental compilation etc users should rarely pay this extra cost.

**Comment by rrousselGit** [comment]
> Can you define a lot at all? Is this like multiple functions per widget?

Yes, definitely. 

I'd expect almost anything that is used by the "business logic" of a flutter app to be parsed this way.
This can involve a lot of stuff

> But either way if those deps don't change your macro won't re-run on them.

That's not the case here. Those dependencies don't necessarily use the macro. They may only define functions used by the macro. 
The issue is that the macro needs to visit even a function that is not annotated by the macro, and do so recursively too (functions used by that function need to be visited too).

**Comment by rrousselGit** [comment]
>  Do you currently use debug/release configuration from build_runner to enable/disable this behavior?

The generated code checks the environment variables used by Flutter to define release mode.

Here's the generated code of some tests using it: https://github.com/rrousselGit/riverpod/blob/c18e93e53d62be5f1ae1db255ad365e1ef0a2a71/packages/riverpod_generator/test/integration/async.g.dart#L16

I've pointed you do the env usage.

**Comment by jakemac53** [comment]
> The issue is that the macro needs to visit even a function that is not annotated by the macro, and do so recursively too (functions used by that function need to be visited too).

Ah ok, that makes sense but also definitely further complicates things, in fact I don't think it is possible to do at all (during modular compilation in particular).  We need to be able to run with only the outline of dependencies. Those outlines cannot contain any identifying information about method bodies, otherwise they would cause unnecessary invalidation downstream. This feature I don't think would justify regressing the invalidation logic of summaries like that.

The compiler could not even provide for you an identity that includes such transitive invalidation logic, because it doesn't even have the bodies itself.

> The generated code checks the environment variables used by Flutter to define release mode.

Ok that pattern should continue to work.

**Comment by jakemac53** [comment]
Just to elaborate on the above this basically comes down to my earlier note (which I added with an edit so you might have to refresh to see it):

```
Note: This would likely only be exposed for the declaration that is immediately annotated with the macro. If that declaration is augmented by a different macro, you would likely see the original and not the augmented one. We could possibly expose access to any declaration in the current library as well, but again likely only the original versions.
```

**Comment by rrousselGit** [comment]
Hum, that's a bit sad.

Because then it'd mean users would effectively be punished for refactoring their code. A large monolithic function would have better hot-reload behavior than a bunch of composed smaller functions.

I wonder what could be done then. Maybe SDK support for detecting changes on hot-reload? But that sounds like quite a lot of work

**Comment by jakemac53** [comment]
Fwiw this could probably be implemented a lot more efficiently as a direct part of hot reload anyways

**Comment by jakemac53** [comment]
I am going to go ahead and close this as not planned because I don't think it would be feasible based on the constraints we have for macros.
