### ISSUE TITLE
[patterns] Probably obsolete use of non-matching rest element

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2915]
Thanks to @sgrekhov for noticing this!

The [exhaustiveness algorithm](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#side-effects-and-exhaustiveness) has the following commentary:

> Note that the actual end argument passed to `sublist()` is `length - t`, but we just use `t` for the invocation key here since the length of the list isn't a syntactically known property. Since the list and its length are cached too, using `t` is sufficient to distinguish calls to `sublist()` that are different, like `[...] && [..., a]` while caching calls that are the same as in `[..., a] && [..., b]`.

The non-matching rest elements should probably be replaced by matching ones, because the non-matching ones do not give rise to invocations of `sublist()`.

**Comment by munificent** [comment]
Nice catch!
