### ISSUE TITLE
Should macro introspection of classes have default modifiers for <3.0 classes?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2930]
I recently added several boolean flags to `ClassDeclaration` to handle the various new modifiers. All of these in the docs today specify that they are defined by whether a given modifier is present. So for instance:

```dart
  /// Whether this declaration has a `mixin` modifier.
  bool get isMixin;
```  

Now there is a question of what to do for packages that are pre-3.0. Should `isMixin` be true for those classes? Should any of the [other getters](https://github.com/dart-lang/sdk/blob/baff2375c3a6bb761a78dff116adba1f8b3ae737/pkg/_fe_analyzer_shared/lib/src/macros/api/introspection.dart#L128) be true by default for <3.0 classes?

cc @munificent @johnniwinther @scheglov

**Comment by rrousselGit** [comment]
I personally think those booleans should represent the keywords more than the behavior. +1 for the `has*` then

But to begin with, I wouldn't expect `mixin T {}` to come up as a ClassDeclaration but as a MixinDeclaration.
It doesn't use the `class` keyword in the end.

**Comment by scheglov** [comment]
Note also that in the analyzer we [about to make](https://dart-review.googlesource.com/c/sdk/+/289406) these modifiers on `ClassElement` not purely syntax base, but some of them can be induced by other modifiers on superclasses. So, in the analyzer I can justify using `isX` instead of `hasX`. Maybe.

**Comment by jakemac53** [comment]
> But to begin with, I wouldn't expect `mixin T {}` to come up as a ClassDeclaration but as a MixinDeclaration.
> It doesn't use the `class` keyword in the end.

I am actively working on restructuring to exactly this (EnumDeclaration/ClassDeclaration/MixinDeclaration and likely some base class they all inherit from). That is what spurred this question for me actually haha.

**Comment by jakemac53** [comment]
@scheglov would it provide any issues in translating between ClassElement -> ClassDeclaration if we were syntax based but ClassElement was not, especially if the AST was not available?

**Comment by scheglov** [comment]
In the analyzer AST we have: `ClassDeclaration`, `MixinDeclaration`, `EnumDeclaration`.
In the analyzer elements we have: `ClassElement`, `MixinElement`, `EnumElement`.
So, there should be no issues with building specific macro wrappers either around AST or elements.

**Comment by jakemac53** [comment]
I am going to go ahead and close this, leaving the docs as is but change the names to `has*`. That seems the most straightforward, and additional functionality (to ask, "is this class extendable" etc) can be built on top if needed.
