### ISSUE TITLE
Dart's Library is File Or Package ??

### ISSUE THREAD

**Issue by jpoh281** [dart-lang/language#2935]
I test `final class` in Dart Package.

in package 

```dart
// a.dart
final class A {}

// b.dart
class B extends A {}
```

`The class 'A' can't be extended outside of its library because it's a final class.`

so Library is File?

**Comment by rrousselGit** [comment]
A library is a dart file with all its "part of"

So the following works:

```dart
// a.dart
part 'a.g.dart';

final class A {}

// a.g.dart
part of 'a.dart';

class B extends A {} // OK
```

Augmentation libraries likely would have the same effect as parts too here.

**Comment by jakemac53** [comment]
Yes, a "library" is a file + its parts (and later, augmentations).

**Comment by jpoh281** [comment]
Thank you !!
