### ISSUE TITLE
How to use “>>>” in Dart ?

### ISSUE THREAD

**Issue by arcticfox1919** [dart-lang/language#294]
[dart operators](https://www.dartlang.org/guides/language/language-tour#operators)

Dart documentation indicates support for the '>>>' operator

but the code can't run, how can I use it?

```
void main() {
  print(3 >>> 1);
}
```

**Comment by arcticfox1919** [comment]
Is it because the guy who wrote the document copied it directly from Java or JavaScript?

**Comment by eernstg** [comment]
`>>>` has been specified (it's needed because there is no logical shift right in Dart otherwise), but has not yet been implemented.

**Comment by mit-mit** [comment]
https://github.com/dart-lang/language/issues/120 is the feature bug to track for this
