### ISSUE TITLE
Make non-top level declarations of `typedef` valid

### ISSUE THREAD

**Issue by purplenoodlesoop** [dart-lang/language#2951]
Currently, it is not possible to create a `typedef` not as a top-level entity. However, they could be useful as a class member (static or not), or in a function body.

It is open to discussing how they should behave in classes, but it looks like it should be entirely possible to do the following:

```dart
void foo<T extends Object?>() {
  typedef Double = T Function(T value);
  ...
}
```

**Comment by lrhn** [comment]
Existing issue in the SDK repo, which has not been moved to the language repo yet: https://github.com/dart-lang/sdk/issues/17413

**Comment by purplenoodlesoop** [comment]
Thanks! Closing the issue then – searched in the language repo initially :)

**Comment by lrhn** [comment]
Seems that another issue, #67, is also in the language repo, with a name that made it unsearchable. My bad :grin:.
