### ISSUE TITLE
[patterns] An empty map pattern is an error?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2962]
I believe it has just been decided in the language team that an empty map pattern, `{}`, is an error.

The 2.29 changelog entry says 'Make it an error to have an empty map pattern.'

However, I can't see that the spec was actually changed such that this is specified. Perhaps it could be done simply by removing `?` from `mapPatternEntries?` in line 605.

**Comment by munificent** [comment]
Oops, thanks!
