### ISSUE TITLE
Consider definition of "same" for records in patterns.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2979]
The pattern specification tries to avoid the "same" key occurring twice in a map pattern.

The phrasing is that it's a compile-time error if:
> * Any two keys in the map are identical. *Duplicate keys are likely to be a copy/paste error. If you want to match the value associated with some key against multiple patterns, you can always use an || pattern.*s
> * Any two record keys which both have primitive equality are equal. Since records don't have defined identity, we can't use the previous rule to detect identical records. But records do support an equality test known at compile time if all of their fields do, so we use that.

That might leave some holes where two keys are *probably* the same, but neither identical, nor have primitive equality, because it mixes the two.

Take:
```dart
const a = A(); // `A` class does *not* have primitive equality.
switch (map) {
  case {(a, 1): ..., (a, 1): ....}: ...
}
```
Here the `(a, 1)`'s are records, so we cannot assume being identical, but they also do not have primitive equality because `A` doesn't, so we don't recognize that these are the same key &mdash; unless they *do* happen to be identical, which they *probably* will. But we don't promise it, which means this program can compile one day and fail to compile the next, because it's only invalid if the records are identical, which is unspecified.

Consider rephrasing as:
> We define an equivalence on constant values which includes both identity and primitive equality, and which extends 
> naturally to records.
> Two constant values are *equivalent as constants* if:
> * The two values are identical.
> * The two values have primitive equality and are equal. (All types with primitive equality have symmetric `==` operators, 
>    so it doesn't matter which order the operands of `==` are in.)
> * The two values are record values with the same shape, and the corresponding values of each field are equivalent as constants.
>
> It's a compile-time error if a map pattern contains two key values which are equivalent as constants.

**Comment by munificent** [comment]
That rephrasing doesn't actually fix it, though, does it? It still says "the two values are identical", and it's not clear whether that rule is allowed to come into play when the values are records. Should that be "the two values are not records and are identical"?

**Comment by lrhn** [comment]
The rephrasing is probably *safe* because if two records are identical, then their field values are *also* equivalent as constants, so it doesn't matter which item gives the true result, the result will always be consistent. 

But it would be equally safe, and probably more readable, to say:
> * Not records and identical.
> * Not records and have primitive equality and are equal.
> * Are records with same shape, and fields values are equivalent as constants.
