### ISSUE TITLE
Places where a non-nullable type is required in the language syntax.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#298]
This is an attempt to list places in the Dart language where specific types are needed or specified by the language specification, and where the required type will be non-nullable with the NNBD feature. That is, where the *language* introduces a context type for an expression which is not fully under the control of the programmer, which is typically around non-implementable operators or syntactic constructs.
In those places, unless the operator is explicitly `null` aware, the operands must usually be non-nullable.

This issue does not consider *library* changes.
It does not include the standard "can't call methods on a nullable type" rule..
It does not include any other position where the context type is fully user-controller, and the chosen type happens to be non-nullable. 

It will be a static error to use a nullable type in any of the positions where a non-nullable value is required.
It will be a static error (or at least a warning) to use a non-nullable type where a potentially nullable value is required, but only because it's known to be unnecessary.

## Places that must be non-nullable (or `dynamic`, which allows an implicit downcast):
* Boolean contexts where the context type is non-nullable `bool`.
    * Operands of `&&`, `||`, prefix `!`, 
    * Condition of `if`, `for(;;)`, (`do`-)`while`, and conditional expression `?`-`:`. 
    * Condition of `assert(...)`.
* The operand of `throw`. (You still can't throw `null`, so the `on` catch types should probably be non-nullable too).
* The iterable of a `for`-`in` or the stream of an `await for`.
* Operand of `...` spread operator in collection literals
* Operand of `yield*`.
* The implicit return type of a factory constructor is non-nullable.

Apart from the last item, these are all places where the current implementation throws (or should throw) if the value is `null`. In NNBD, there will be an implicit context type that is non-nullable (`bool` for boolean contexts, `Object` for `throw`, `Iterable<T>`/`Stream<T>` for `for-in` and `yield` (where `T` may be inferred from the surrounding context), `Iterable<T>` for non-nullable spreads, and the type itself for constructors. Not being assignable to that context type is a compile-time error.

## Places that must be potentially nullable
* First operand of `??`, left-hand-side of `??=`, receiver of `?.` or `?..`
* The operand of suffix `!`.
* Operand of `...?` spread operator in collection literals.

We don't have to make these errors, but they show that the programmer is not fully aware of the types involved. All these operations are statically guaranteed to be unnecessary, so the compiler could also just ignore them, but that could hide a more important misunderstanding.

## Places where the resulting type is always non-nullable.
* Boolean operators `&&`, `||`, prefix `!`.
* `is` type tests.
* `==` expressions (needs to be said because it's not just a plain method call, operands can be nullable or not).

A noticeable omission is `await`. It still accepts nullable operands since it must work with `FutureOr<T>` for any `T`, even nullable ones. Both `return` and `yield` are only limited by a user-supplied type. String interpolation accepts anything, and `Object.toString()` will return non-nullable `String`).
Switch `case`-expressions currently cannot be `null` unless it's the only `case`-expression, but only because all cases must be instances of the same class. This constraint could just be dropped.

**Comment by eernstg** [comment]
> The implicit return type of a factory constructor is non-nullable

We should probably check out whether this is breaking in practice. It could make sense (especially now where static method invocations and constructor invocations may look the same at the call site) to use a factory constructor to obtain a "worker" object from a pool and return `null` when the pool of idle workers is empty. Maybe we could have a default return type of the enclosing class `T`, and allow developers to explicitly specify `T?` if they want to do that?

> - == expressions

Right, it follows from the description of [equality expressions](https://github.com/dart-lang/language/blob/434d0a90fff5b04e9150e0c6b1a071fc6edb3460/specification/dartLangSpec.tex#L10955) that they evaluate to a value of type `bool` (not `bool?`) when the return type of `operator ==` is `bool`. So that would be a consequence of the spec-as-of-today plus a core library update.

**Comment by lrhn** [comment]
I'm *certain* that making the return type of factory constructors non-nullable is breaking. There do exist factory constructors which return `null`. Those will have to be changed to static methods.

I'm equally certain that making the return type non-nullable is the right thing to do. 

The type of factory constructors and the type of generative constructors should be the same so that you can change one to the other.

Even if we made generative constructors non-nullable and factory constructors nullable, which could be argued as reasonable because changing a generative constructor to a factory constructor is already breaking in case of subclassing, it would be quite annoying to have `Foo x = Foo(42);` not compiling because the RHS is nullable. 
Having to write `Foo x = Foo(42)!;` is ... not ergonomic, to put it politely.

So, the only reasonable and consistent behavior *in the absence of an explicit return type* is to make the return type non-nullable.
(I'm all for discussing return types on constructors, especially when we get generic constructors.)

As for `==`, the spec currently just says that the type is `bool`. That can mean either `bool` or `bool?` after NNBD. It is clear that the values will be either `bool` instances (when comparing `null`) or the result of calling `operator==`, so the values will definitely be non-null booleans, but we have to say what the static type will be, how the current `bool` is migrated, because the operation is not *just* the method invocation. It might be an obvious choice, but it still needs to be stated. 

Any place in the specification which currently mentions a type can be migrated to either a nullable or a non-nullable type. In most cases it's probably obvious which one it is, and that may cause no textual change if the type is non-nullable. It is still a migration, and we need to make sure it's done correctly.

**Comment by eernstg** [comment]
> The type of factory constructors and the type of generative constructors
> should be the same so that you can change one to the other

I'll buy that!

**Comment by munificent** [comment]
> Places that must be non-nullable (or dynamic, which allows an implicit downcast):

One more case, the second clause of a C-style for loop:

```dart
for (; foo; ) { ... } // foo must be non-nullable bool.
```

> I'm equally certain that making the return type non-nullable is the right thing to do.

+1.

**Comment by lrhn** [comment]
@munificent  
Thanks. I was convinced `for` was already there, but I must have misread `if` when I checked.

**Comment by stereotype441** [comment]
> It will be a static error to use a nullable type in any of the positions where a non-nullable value is required.

Will it also be a static error to use a *potentially nullable* type in such positions?

It seems like it should.  Consider:
```dart
class C<T extends bool?> {
  f(T x, T y) => x && y;
}
```
The spec currently says that for `e1&&e2`, "it is a compile time error if the static type of `e1` may not be assigned to `bool` or if the static type of `e2` may not be assigned to `bool`".  Since the type of `x` and `y` in the example above is `T`, which is not a subtype of `bool`, I think that should be an error.

**Comment by stereotype441** [comment]
One more case for "Places that must be non-nullable": the condition of an assert statement:
```dart
assert(foo); // foo must be non-nullable bool.
```

**Comment by lrhn** [comment]
@stereotype441 
Yes. A potentially nullable non-dynamic type is not assignable to `bool`. The only types which are assignable to `bool` are `bool` and `dynamic` (the latter via implicit downcast).

Good catch on `assert`.

**Comment by bwilkerson** [comment]
> ... and `dynamic` (the latter via implicit downcast).

My understanding is that nnbd disallows implicit downcast, so I think this means that the only type assignable to `bool` is `bool`. Is that correct?

**Comment by leafpetersen** [comment]
> My understanding is that nnbd disallows implicit downcast, so I think this means that the only type assignable to `bool` is `bool`. Is that correct?

We will allow implicit downcasts from dynamic.  I would propose that the --strict option that @srawlins has been working on will then disallow this for users that would prefer no downcasts at all.

**Comment by MichaelRFairhurst** [comment]
What about comparing to null?

```
int? x;
return x != null;
```

Should this be a dead code hint or a warning?

**Comment by bwilkerson** [comment]
Did you mean
```
int x;
return x != null;
```

**Comment by MichaelRFairhurst** [comment]
@bwilkerson yes! Thanks :)

**Comment by leafpetersen** [comment]
> int x;
> return x != null;

This probably should be a hint, but I don't think it should be a warning.  There are lots of similar things that we don't warn on, e,g, `int x = ....; return x is String;'.

Note also that during the transition period, this test may be very well justified, since `x` may actually end up being `null`.

**Comment by MichaelRFairhurst** [comment]
> Note also that during the transition period, this test may be very well justified, since x may actually end up being null.

Wait, wouldn't that justify `??`, `??=`, `!`, etc, too?

**Comment by leafpetersen** [comment]
> Wait, wouldn't that justify `??`, `??=`, `!`, etc, too?

Yes.  And we currently specify warnings around using those on non-nullable types, which might be a little awkward.

```
It is a warning to use a null aware operator (`?.`, `?..`, `??`, `??=`, or
`...?`) on a non-nullable receiver.
```

In general, I'm on the fence about this warning.

**Comment by bwilkerson** [comment]
Is there an issue open that we can watch in order to know when a decision has been made?

**Comment by leafpetersen** [comment]
> Is there an issue open that we can watch in order to know when a decision has been made?

As of now, the warning as specified is POR.  If we decide to change this, I will communicate that to everyone.

**Comment by MichaelRFairhurst** [comment]
This issue references `!` but the informal spec does not. Which is correct? Should `nonNullable!` be a warning or not?

**Comment by MichaelRFairhurst** [comment]
ping @leafpetersen

**Comment by leafpetersen** [comment]
@MichaelRFairhurst: yes, thanks.  https://github.com/dart-lang/language/pull/467

**Comment by eernstg** [comment]
I believe the issues raised here have already been resolved:

> Should `nonNullable!` be a warning or not.
Yes, and this is in the spec.

About `x != null` even though `x` has a non-nullable type, and by analogy `??=` and other null-aware constructs:

> Note also that during the transition period, this test may be very well justified

We do not make any exceptions for the transition period, but the associated diagnostics are warnings so they do not prevent compilation. Tools may allow for more control (like turning off these warnings), in case a build process will fail when there are warnings.
