### ISSUE TITLE
Does a `null` initializer yield the inferred type `dynamic`?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#300]
This may be a pragmatically justified choice, but it still does not seem to be consistent with the upcoming [type inference feature spec](https://github.com/dart-lang/language/pull/218): Variable `x` in the following example will currently get the inferred type `dynamic`, with the common front end as well as the analyzer:

```dart
main() {
  var d = null;
  d.whatever(); // No error at compile-time.
}
```

**Comment by nguyenxndaidev** [comment]
Another example related to type inference for nullable variable:

```
class Movement {
  Movement(this.fromX, this.toX);
  
  int fromX;
  int toX;
  
  // type of direction should be String?
  get direction {
    if (fromX == toX) {
      return null;
    } else if (fromX < toX) {
      return 'right';
    } else {
      return 'left';
    }
  }
}

void main() {
  final direction = Movement(1, 2).direction;
}
```

![image](https://user-images.githubusercontent.com/24372782/103168548-5a92c700-4834-11eb-9be8-49d4d1d305b6.png)

**Comment by nguyenxndaidev** [comment]
I created https://github.com/dart-lang/language/issues/1385 for more general type inference problem.

**Comment by lrhn** [comment]
The issue in #1385 is about member declarations, not local variables, so it's a different issue.

**Comment by leafpetersen** [comment]
This has been specified now in inference.md (for top level variables) and in the null safety feature specification for local variables.
