### ISSUE TITLE
Exhaustive pattern matching with `abstract` classes

### ISSUE THREAD

**Issue by SandroMaglione** [dart-lang/language#3030]
I noticed a possible issue with exhaustive pattern matching (`switch` expression) and `abstract` classes.

Specifically, this happens when you create an `abstract class` with some subclasses (`extends`):

```dart
abstract class Source {}

class Sub1 extends Source {}

class Sub2 extends Source {}
```

When you use `switch` on an variable of type `Source` you get an error if you don't match on `Source` as well:

```dart
Source src = Sub1();

/// Error here 👇
///
/// The type 'Source' is not exhaustively matched by the switch cases since it doesn't match 'Source()'.
/// Try adding a wildcard pattern or cases that match 'Source()'.
final match = switch (src) {
  Sub1() => 1,
  Sub2() => 2,
};

/// This works instead 👇
final match = switch (src) {
  Sub1() => 1,
  Sub2() => 2,
  Source() => 0,
};
```

However, since `Source` is `abstract`, creating a instance of `Source` (`Source()`) is not possible, therefore matching on `Source()` shouldn’t be included in the exhaustive check.

May this be an issue with how exhaustive checking is performed with `abstract class`?

**Comment by rrousselGit** [comment]
The problem is that the list of `Source` implementations is not known.

A random file could very well do `extends/implements Source` without extending/implementing Sub1/2

Hence why we have all these new class keywords. You can make Source `sealed`, which would make it an error to extend/implement the class outside of its library.

**Comment by SandroMaglione** [comment]
Yes, but the issue I think is related to having to match `Source()`, more than having exhaustiveness on a class that is not `sealed`.

I would expect the `switch` to require a wildcard (`_`), since dart cannot know where `Source` may be extended or implemented. Instead, the issue mentions `Source()`, but an instance of `Source` cannot exists. Am I missing something?

**Comment by rubenferreira97** [comment]
An instance of `Source` cannot exist since is abstract but any other class that implements or extends `Source` will be exhausted into the `Source()` pattern.

```dart
Source src2 = Sub3(); // Sub3 was declared on a different library, extending/implementing `Source`

final match = switch (src) {
  Sub1() => 1,
  Sub2() => 2,
  Source() => 0,
};

print(match); // prints 0
````
