### ISSUE TITLE
[patterns] Do we support patterns in asynchronous for constructs?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3035]
The [patterns feature specification](https://github.com/dart-lang/language/blob/main/accepted/future-releases/0546-patterns/feature-specification.md) specifies that the non-terminal `forLoopParts` is extended to allow a pattern declaration in a for-in construct. It does not mention whether or not this enhancement is applicable in an await-for-in statement/element. The document mentions the word 'await' just once, with no connection to for-in constructs.

We do have sections about for-in [statements](https://github.com/dart-lang/language/blob/main/accepted/future-releases/0546-patterns/feature-specification.md#pattern-for-in-statement) and [elements](https://github.com/dart-lang/language/blob/main/accepted/future-releases/0546-patterns/feature-specification.md#pattern-for-in-element), but there are no corresponding sections about the asynchronous for constructs.

For the purpose of reviewing tests I'm assuming that pattern declarations in await-for-in constructs are supported, but in that case we'd probably want to add some text about it in the feature specification as well.

**Comment by munificent** [comment]
I'll be honest, I didn't spend much time thinking about pattern support in await-for at all.

I think I would say that if it falls out naturally from the implementations and is already supported, then, sure, we should support it and I can add some verbiage to the spec to call that out. If it isn't already working, then the spec for the proposal should say that it isn't supported and we can consider adding support for it in 3.1 or some other future version of the language.

**Comment by eernstg** [comment]
Closing: all tests are passing, https://dart-current-results.web.app/#/filter=co19/LanguageFeatures/Patterns/execution_pattern_await_for_in_statement&showAll.
