### ISSUE TITLE
[ANTLR/spec] multiple parse trees for `#id.id`

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#3038]
I think the current grammar describes two parse trees for the symbol literal expression `#id.id` 

Consider the following production:

https://github.com/dart-lang/sdk/blob/e82a5a2ff34d9fec3cfdaf5ac46654e40f31379b/tools/spec_parser/Dart.g#L965 (Section 17.35 in the [language spec](https://spec.dart.dev/DartLangSpecDraft.pdf).)

and the following derivations:

```
- primary                                                selector*
- literal                                                selector*
- symbolLiteral                                          selector*
- '#' (operator | (identifier ('.' identifier)*) | VOID) selector*
- '#'              identifier ('.' identifier)*          selector* 
- '#'              identifier ('.' identifier)*          assignableSelector*
- '#'              identifier ('.' identifier)*          unconditionalAssignableSelector*
- '#'              identifier ('.' identifier)*          ('.' identifier)*

1.'#'              identifier ('.' identifier)*          
2.'#'              identifier                            ('.' identifier)*
```

So `#id.id` is either a single symbol literal (1), or a symbol literal `#id` followed by a selector `.id` (2).

I wanted to ask if both specs are meant to disambiguate this via some implicit disambiguation strategy or whether this is unwanted/unexpected and considered to be a bug in either of the specs?

**Comment by eernstg** [comment]
It is not a safe assumption that the Dart grammar is unambiguous, it is in general relying on the [rule](https://github.com/dart-lang/language/blob/961ed40ede0c75d1cd5b345e03e2aed33391f0f7/specification/dartLangSpec.tex#L491) whereby a textually earlier alternative is chosen in favor of a later one in the case where the first one succeeds:

> As in PEGs, alternation gives priority to the left.

This rule is somewhat magical in the situation where the grammar rule uses meta symbols like `*` to specify that a certain construct can occur zero or more times, but the effect is that a successful parse of a longer sequence is preferred over a shorter one.

So, I do recognize that it would have been nice if the grammar had been designed as a plain context free grammar, with no ambiguities and no notions of priorities etc, but the fact is that the grammar does rely on disambiguation like this in a number of rules.

Of course, this approach fits very nicely with a greedy extended-recursive-descent parser, but it does create problems for, e.g., parser generators based on LR parsing.

If possible, you could adopt the rule that the left parse (the longer symbolLiteral) has a higher priority.

**Comment by eernstg** [comment]
The underlying reason for this ambiguity isn't going to go away any time soon, so I think I'll have to consider this behavior as 'working as intended'.
