### ISSUE TITLE
Recursive explicit casting

### ISSUE THREAD

**Issue by Daniel-Genkin** [dart-lang/language#3056]
I am currently building up a parser using Dart. All the values that are parsed from the input string end up being stored in a `Map<String, Object>` while they are being processed. The values of this map can be collections with arbitrary inner value types. So some entries might contain something like a `List<Map<String, List<CustomObject<int>>>>` while others just contain an `int` or a `String`. My issue is that I would like to be able to cast these types elegantly.

## Current solution
I have found that I can use the `Map.cast` and `List.cast` methods to cast 1 layer deeper (i.e. `Map<String, Object>` to `Map<String, List<Object>>` or `List<Object>` to `List<List<Object`). However, if I need to go deeper, I need to start rebuilding the collections one layer at a time (such as via `map((item) => item as T).toList()`). This is obviously slow and memory intensive since I need to reallocate the entire collection. This also has the problem that since there is no built-in way to get the inner type of a type, casting one layer at a time is not always easy. I needed to create a lot of methods with different type signatures (and names since there is no parameter overriding in Dart) that each correspond to one combination of types that are supported by the parser.

## Potential Solution Proposal
Make the `.cast` methods create a recursive view of the objects instead of just stopping at a single level. Then there would not be any need to rebuild the object one layer at a time and no need to create so many methods for casting everything.

## Another Potential Solution Proposal
Add method parameter overloading. This would also fix the issue as a single method with multiple overloads would allow Dart to select the appropriate method (given that they all were defined and there is a fallback that throws an exception if none of the other ones match)  and thus we could do something in the form of the first comment.

## Question
Also, is there a difference between `(parsedObject as List).cast<T>()` and `List.castFrom<T>(parsedObject as List)`?

**Comment by Daniel-Genkin** [comment]
I also tried to do something like this:
```dart
dynamic cast<T>(Object object) {
  if (object.runtimeType is T) {
    return object;

  } else if (object is Map && isSubType<T, Map>()) {
    Type K = object.keyType;
    Type V = object.valueType;
    return object.map((key, value) => MapEntry(cast(key), cast(value)));

  } else if (object is List && isSubType<T, List>()) {
    Type V = object.childType;
    return object.map((value) => cast(value));

  } else if (object is Iterable && isSubType<T, Iterable>()) {
    Type V = object.childType;
    return object.map((value) => cast(value));

  } else {
    throw ArgumentError("Object cannot be cast to the desired type");
  }
}
```
This does work but it also needs to handle all the cases itself.

Also, it is possible to just use a dynamic that is returned from a function to throw away all type information (i.e. `dynamic cast(Object o) => o;` and then pretend that it was casted but this doesn't provide any type safety.

**Comment by lrhn** [comment]
I'm not entirely sure I understand the problem description.

It's you have a value that you know is a `List<Map<String, List<CustomObject<int>>>>`, you should be able to just write `value as List<Map<String, List<CustomObject<int>>>>`.

If that doesn't work, could you explain what the constraints and use cases are?

**Comment by Daniel-Genkin** [comment]
An example use case would be something like this:
```dart
class Parser {
   Map<String, Object> _values;

    T getProperty<T>(String name) => _values[name] as T;
}

class SomeThingElse {
    void someMethod() {
      var parser = Parser();
       // do some stuff to parse
      var property = parser.getProperty("result"); // I want to have the type of property here to be explicitly defined and checked
   }
}
```
The issue is that I cannot type cast (for the reasons stated above) when the types are very complex (such as a collection of collections).

**Comment by lrhn** [comment]
The problem here does not seem to be *casting*, but that the underlying object is not actually typed as what you want it to be. Your original "something like a `List<Map<String, List<CustomObject<int>>>>`" is misleading, because that is not the type of the object. More likely the object is a `List<Object>`, which contains only `Map<String, Object>`s, whose values are only `List<Object>`s, whose values are again only `CustomObject<int>`s.

If you have an `UmodifiableMapView<String, Object>`, it's not important that it's an `UmodifiableMapView`, but it is important a `Map<String, Object>`, not a `Map<String, List<String>>`.

If you had created it as a `Map<String, List<String>>` originally, doing `as `Map<String, List<String>>` would work, but it isn't one. It is, presumably, a `Map<String, Object>` where all the value are lists, whose values are all strings.

So you want to *convert* (or wrap) the object to *make* it into an object with the type that you want.

You can't easily do that using just a type variable containing `Map<String, List<String>>`, because Dart doesn't allow you to destructure types. There is no way to get to the `List<String>` from a `T` bound to `Map<String, List<String>>`.
So you need to build something matching the type structure as a value.

Take:
```dart
import "dart:collection";

class Coercer<T> {
  T coerce(Object? value) => value as T;

  T convert(Object? value) => value as T;

  Coercer<Map<K, T>> mapOf<K>() => MapValueCoercer<K, T>(this);
  Coercer<List<T>> listOf() => ListValueCoercer<T>(this);
}

class MapValueCoercer<K, V> extends Coercer<Map<K, V>> {
  final Coercer<V> _valueCoercer;
  MapValueCoercer(Coercer<V> valueCoercer) : _valueCoercer = valueCoercer;
  @override
  Map<K, V> coerce(covariant Map<K, Object?> value) =>
      _WrapMap<K, V>(value, _valueCoercer);

  @override
  Map<K, V> convert(covariant Map<K, Object?> value) =>
      {for (var e in value.entries) e.key: _valueCoercer.convert(e.value)};
}

class ListValueCoercer<E> extends Coercer<List<E>> {
  final Coercer<E> _valueCoercer;
  ListValueCoercer(Coercer<E> valueCoercer) : _valueCoercer = valueCoercer;
  @override
  List<E> coerce(covariant List<Object?> value) =>
      List<E>.unmodifiable(_WrapList<E>(value, _valueCoercer));

  @override
  List<E> convert(covariant List<Object?> value) =>
      [for (var element in value) _valueCoercer.convert(element)];
}

class _WrapMap<K, V> extends UnmodifiableMapBase<K, V> {
  final Map<K, Object?> _map;
  final Coercer<V> _coercer;
  _WrapMap(this._map, this._coercer);

  @override
  V? operator [](Object? key) {
    var value = _map[key];
    if (value == null && !_map.containsKey(key)) return null;
    return _coercer.coerce(value);
  }

  @override
  Iterable<K> get keys => _map.keys;
  @override
  int get length => _map.length;
  @override
  bool containsKey(Object? key) => _map.containsKey(key);
}

class _WrapList<E> extends ListBase<E> {
  final List<Object?> _list;
  final Coercer<E> _coercer;
  _WrapList(this._list, this._coercer);
  @override
  int get length => _list.length;
  @override
  set length(int _) => throw UnsupportedError("unmodifiable");
  @override
  E operator [](int index) => _coercer.coerce(_list[index]);
  @override
  operator []=(int index, E value) => throw UnsupportedError("unmodifiable");
}
```

Then you can use this as:
```dart
void main() {
  var coercer = Coercer<String>()
      .listOf()
      .mapOf<String>(); // coercer for Map<String, List<String>>
  var untyped = <String, Object>{
    "a": <Object>["a"],
    "b": <Object>["b"],
  };
  Map<String, List<String>> property = coercer.coerce(untyped);
  print(property);
}
```

**Comment by Daniel-Genkin** [comment]
Closing as it looks like the proposal is unnecessary. Thanks for your help @lrhn. I ended up using a similar idea but customized to my use case to avoid all the extra classes.
