### ISSUE TITLE
Make the semicolon optional 

### ISSUE THREAD

**Issue by MrLuckyCat** [dart-lang/language#3063]
I really love the dart language and its nice syntax. My only issue with it is the semicolon. Why can't I just write:
```dart
print("hello world")
```
Instead of:
```dart
print("hello world");
```
This really decreases the productivity. I wish the language could implement automatic semicolon insertion like JavaScript or something like that because it is just annoying when adding it manually and wastes a lot of time when writing the code.

**Comment by julemand101** [comment]
Looks like a duplicate of: https://github.com/dart-lang/language/issues/69

**Comment by lrhn** [comment]
Closing as duplicate.
