### ISSUE TITLE
`Map<TKey, TValue>` should inherit from `Iterable<MapEntry<TKey, TValue>>`

### ISSUE THREAD

**Issue by ahmednfwela** [dart-lang/language#3081]
currently to iterate over a `Map`, you need to access the `entries` property, but you can't iterate over the map itself

this makes representing a union of `Map | List`  a chore, since they have no common denominator, thus requiring changing the type to `dynamic`

**Comment by Wdestroier** [comment]
Would a trait suit you better? A trait would allow you to _implement_ Iterable _for_ Map. You might want to move this issue to the dart-lang/sdk repository.

**Comment by ahmednfwela** [comment]
How would that work ? @Wdestroier

**Comment by ahmednfwela** [comment]
Moved to https://github.com/dart-lang/sdk/issues/52435

**Comment by Wdestroier** [comment]
@ahmednfwela You can find examples in the Rust programming language documentation. They're like no overhead inheritance. However, traits are resolved at compile. That's a problem for optionally typed languages like Dart. You can read more at https://doc.rust-lang.org/rust-by-example/trait.html.
