### ISSUE TITLE
Why do we  have to put mixins before `implements`?

### ISSUE THREAD

**Issue by joshpetit** [dart-lang/language#3104]
I'm looking at creating a structure like this:
```dart
class ConnectivityRepository {
  void add() {}
}

abstract class RetryEnabled {
  ConnectivityRepository get connectivityRepository;
}

mixin EventConnectivityGateway on RetryEnabled {
  void addToRepository(String id) {
    connectivityRepository.add();
  }
}

class OurBloc implements RetryEnabled with EventConnectivityGateway {
  @override
  ConnectivityRepository get connectivityRepository =>
      throw UnimplementedError();
}
```

but was stopped short when I received the error that we have to put mixins before we say what a class implements. Why exactly is that the case? I thought it would be good to specify what a class is capable of doing before adding mixins to extend its capabilities. But maybe I don't understand the fundamentals of how these work together.

**Comment by joshpetit** [comment]
After going through the [docs](https://dart.dev/language/mixins) I see that it's possible to add abstract methods to mixins, which will suffice for my purposes in this example:
```dart
class ConnectivityRepository {
  void add() {}
}

mixin EventConnectivityGateway {
  void addToRepository(String id) {
    connectivityRepository.add();
  }

  ConnectivityRepository get connectivityRepository;
}

class OurBloc with EventConnectivityGateway {
  @override
  ConnectivityRepository get connectivityRepository =>
      throw UnimplementedError();
}
```
On top of that, mixins can implement interfaces themselves, if you want that class to have the contract as well:

```dart
class ConnectivityRepository {
  void add() {}
}

abstract class RetryEnabled {
  ConnectivityRepository get connectivityRepository;
}

mixin EventConnectivityGateway implements RetryEnabled {
  void addToRepository(String id) {
    connectivityRepository.add();
  }

  @override
  ConnectivityRepository get connectivityRepository;
}

class OurBloc with EventConnectivityGateway {
  @override
  ConnectivityRepository get connectivityRepository =>
      throw UnimplementedError();
}

void doThing(RetryEnabled obj) {}

void main() {
  doThing(OurBloc());
}

```
The only downside to this I see is that classes won't explicitly declare what they implement.

**Comment by eernstg** [comment]
It shouldn't be difficult for the _parser_ to allow the clauses in the header of a class (or mixin, etc., for things which can have said clause) in any order whatsoever. The compiler/analyzer can always reorganize the pieces when the abstract syntax tree has been created, or visit them in any order one might need.

However, if you have `class C extends B with M implements I1, I2 {...}` then the superclass of `C` is `B with M`. This implies that it is at least confusing if we allow `with M` to occur as in `class C extends B implements I1, I2 with M {}`, or in any other order that doesn't contain `B with M`.

An ordering like `class C implements I1, I2 extends B with M {...}` would be more meaningful, but I suspect that the ordering where the superclass comes before the implemented interfaces is considered so "natural" in Dart code that there is very little appetite for changing the order, or even allowing several different orderings.

**Comment by eernstg** [comment]
> classes won't explicitly declare what they implement.

With `class C implements B {}` and `class B implements A1, A2 {}`, it is also not explicit that `C` implements `A1` and `A2`. The fact that an interface type implements a given superinterface is true for all kinds of subtype relationships, including `implements` and `extends _ with _`, and the indirect relationships are never explicit.
