### ISSUE TITLE
Deconstructing lambda parameters

### ISSUE THREAD

**Issue by spkersten** [dart-lang/language#3107]
I would like to be able to do deconstruct parameters to lambdas like:
```dart
someMap.entries.where((MapEntry(key: id, value: name)) => ...)
```
similarly to how it's already possible to do so for for-loops:
```dart
for (final MapEntry(key: id, value: name) in someMap.entries) {
  ...
}
```

**Comment by mraleph** [comment]
Duplicate of https://github.com/dart-lang/language/issues/3001
