### ISSUE TITLE
Can we find the ultimate representation type with an inline F-bound?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3109]
Thanks to @sgrekhov for bringing up this situation! Consider the following program:

```dart
inline class V<X extends V<X>> {
  final X x;
  V(this.x);
}
```

In order to be able to compile `anExpression is AnInlineType` correctly, we need to find the non-inline type which will be the run-time value of the inline type, say `ARegularClass`, and then compile it to `anExpression is ARegularClass`. Similar actions need to be taken around dynamic type checks, etc.

We have [an anti-cycle rule](https://github.com/dart-lang/language/blob/main/accepted/future-releases/inline-classes/feature-specification.md#:~:text=type%20V.-,Let%20DV%20be%20an%20inline%20class%20declaration,-named%20V%20with) which is intended to ensure that it is possible to compute this non-inline type for every inline type based on each given `inline class` declaration, and in particular that the computation is guaranteed to terminate.

That rule does not make the declaration of `V` above an error, but the dependency of `V` on `V` in its own type parameter bound seems to be a cyclic dependency that we would probably want to report as an error, even if smart people could prove that there is a way to make it work. This would be in line with the treatment of type aliases (`typedef F<X extends F<X>> = int;` is an error, even though it would probably be possible to handle it).

I'd recommend that we simply specify that each type parameter bound must satisfy the same anti-cycle constraint that we currently specify for the representation type. With that, the declaration of `V` is an error. We could have a rule like this:

> Let _DV_ be an inline class declaration named `V` with representation type `R` and type parameter bounds `B1 .. Bs`. Assuming that all types have been fully alias expanded, we say that _DV_ has a representation dependency on an inline class declaration _DV2_ if any of `R, B1, .. Bs`  contains an identifier `id` (possibly qualified) that resolves to _DV2_, or `id` resolves to an inline class declaration _DV3_ and _DV3_ has a representation dependency on _DV2_.
>
> It is a compile-time error if an inline class declaration has a representation dependency on itself.

It is not obvious to me that we would miss out on any useful programs by doing this.

@dart-lang/language-team, WDYT? Do you have a simpler and/or more powerful check which would give us the same certainty that the non-inline representation type can always be computed? Do you think any useful programs are turned into an error?

**Comment by leafpetersen** [comment]
> We have [an anti-cycle rule](https://github.com/dart-lang/language/blob/main/accepted/future-releases/inline-classes/feature-specification.md#:~:text=type%20V.-,Let%20DV%20be%20an%20inline%20class%20declaration,-named%20V%20with) which is intended to ensure that it is possible to compute this non-inline type for every inline type based on each given `inline class` declaration, and in particular that the computation is guaranteed to terminate.

This isn't really correct - this rule is intended to ensure that it is possible to compute this non-inline type for every inline type based on each **instantiated typed produced from** a given `inline class` declaration.  That is, we do not need to produce a representation type from `V` above, but from `V<Something>`.  And the answer here, is, of course, `Something`.  So... what's the problem?  

(I'm not saying there's not a problem here, just that I don't see it from the above). 

I'm not sure if the example above is inhabitable or not, but you could (for example) perfectly well have uses of it as a type:

```
List<V<Never>> foo = [];
```

Which has the perfectly well-defined erasure:

```
List<Never> foo = [];
```

**Comment by eernstg** [comment]
> ensure that it is possible to compute this non-inline type for every inline type based on each instantiated typed produced from a given inline class declaration

Sure, that is exactly what I intended to say with the following phrase, admittedly relying on 'based on' to mean 'which is a parameterized type of the form `V<T1 .. Tk>` where `V` is':

> compute this non-inline type for every inline type based on each given inline class declaration

The point is that we may be able to process each such parameterized type as it is encountered, and we may then determine that, say, `V<Never>` has the ultimate representation type `Never`, and there are no errors.

However, I think it would be useful to know that the inline class declaration `V` as such has the property that every parameterized type of the form `V<T1 .. Tk>` which isn't an error has a well-defined ultimate representation type.

> So... what's the problem?

It is just not obvious to me that it is impossible to come up with a type `T` such that `V<T>` is OK (it is not an error), and yet `V<T>` does not have an ultimate representation type.

My intention was to take a look at a bit of expressive power (the ability to have cyclic dependencies in type variable bounds in inline classes), conclude that it isn't actually useful, but it does question the tractability of a computation which is needed with every parameterized type based on that inline class, and then simply make it an error.

It is also possible that there is no problem at all, and those representation type computations are trivial, even when we allow these cyclic dependencies.

@johnniwinther, @stereotype441, what's your take on this question? Would it be helpful to know that such cyclic dependencies just don't exist?

**Comment by leafpetersen** [comment]
> It is just not obvious to me that it is impossible to come up with a type `T` such that `V<T>` is OK (it is not an error), and yet `V<T>` does not have an ultimate representation type.

This is, indeed, not obvious to me, but I'm not sure why the F-bound part has anything to do with it.  That is, there is no part of the algorithm that looks at the bound right?  So how can the bound affect the termination (or non-termination) of the algorithm? 

What's still not obvious to me is the termination of the algorithm regardless of f-bounded ness in general.  I *think* it does?  But I can't quite convince myself informally that there's no way, via passing type parameters, to induce a loop.  It feels like there should be at least an informal proof here.

**Comment by eernstg** [comment]
@leafpetersen wrote:
> It feels like there should be at least an informal proof here.

Yes, exactly. The algorithm hasn't been described in the feature specification, but we might want to do that. 

@johnniwinter, how would you describe that algorithm? Does the implementation already have a solution that you feel good about?

Looking at the bounds to conclude that there will be a representation type:

```dart
inline class A<X extends num>(X value) {}
inline class B<X extends B<X>>(X value) {}
```

I'd expect `A` to be safe in the sense that any `A<T>` that we could encounter must satisfy that `T <: num`. This means that `T` could be a non-inline type (and we're done), or `T` could be an inline type `C` which is a subtype of `num`. An inline type can be a subtype of `num` if it `implements int` or something like that, but this is only allowed when `C` has an ultimate representation type `R` such that `R <: int`. The ultimate representation type of `A` is then `R` (and we're done).

I would prefer to say that `B` isn't safe. Go away. ;-)

However, we could try to argue coinductively: Let's say that `R` is the ultimate representation type of `B<T>` for a given type `T`. Let's use the notation `URT(B<T>) == R` for that. We know that `T <: B<T>`, based on the fact that inline types are regular bounded. We also know that if `I2 <: I1` where `I2` and `I1` are inline types then `URT(I2) <: URT(I1)`. But we already assumed that `URT(B<T>)` is `R`, which means that if `T` is an inline type then we must have `URT(T) <: R` (and if `T` is a non-inline type then `URT(T) == T`). At the same time, we certainly want an algorithm to be able to conclude that if `R` is the ultimate representation type of `B<T>` then it is also the ultimate representation type of `T`, that is, `R == URT(B<T>) == URT(T)`.

So far we haven't encountered any inconsistencies.

Currently, we have the property that `T <: I` where `I` is an inline type is only true when `T` is a bottom type (`Never`, `X extends Never` and a few more like that). An inline type `I` where `URT(I) == Never` might be useful, but it is most likely not, and it is in any case marginal.

This implies that an inline type of the form `V<T>` which is not a compile-time error must have a `T` which is itself an inline type. Any attempt to compute `URT(V<T>)` would use `URT(V<T>) == URT(T)`, and it would presumably be impossible to determine whether or not `URT(T)` exists based on the declaration of `V` alone (we want to prove that the algorithm will terminate for all `T` where `V<T>` is not an error), unless we take the bound into consideration.

However, if we wish to use the bound to make progress, we have returned to the task of finding `URT(V<T>)`.

I'm still tempted to just say "Go away!" to `B`. ;-)

**Comment by eernstg** [comment]
Closing: I'm convinced that there is no danger here: It is sufficient to require that there are no cyclic dependencies in the representation type itself, there is no need to consider the bounds of the type variables declared by the extension type.
