### ISSUE TITLE
Feature request: async blocks

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/language#3115]
I would like to be able to launch async operations such as

```dart
() async {
    // Do something
}();
```

But with syntactic sugar to eliminate the ugly parentheses:

```dart
async {
    // Do something
}
```

This could also be used as an expression, returning `Future<void>`:

```dart
Future<void> opFuture = async {
    // Do something
}
```

An async block would be treated as a zero-arg lambda that is asynchronously run at the definition point.

**Comment by mateusfccp** [comment]
Seems like a duplicate of #1858.

**Comment by lukehutch** [comment]
It is, thanks.
