### ISSUE TITLE
Abstract interface class shows a confusing error when extending it from a different file

### ISSUE THREAD

**Issue by bkkoluch** [dart-lang/language#3123]
### Steps to reproduce

1. Create an `abstract interface class X`
2. Extend it from a different file

### Expected results

I believe the more appropriate message would be `The class 'X' can't be extended outside of its file because it's an interface class.`, in my opinion `library` in this case is very confusing, unless that's a deliberate wording. The same case occurs for `sealed class` (and probably other ones). I know `interface class` are meant to be implemented, but they can still be extended in the same file.

### Actual results

Geting an error saying `The class 'X' can't be extended outside of its library because it's an interface class.`

### Code sample

```dart
use_case.dart

abstract interface class UseCase<Type, Params> {
  Type call(Params params);
}

class TestUseCase extends UseCase<String, String> {
  @override
  String call(String params) => 'Test';
}

test.dart

class TestUseCase2 implements UseCase<String, String> {
  @override
  String call(String params) => 'Test';
}

class TestUseCase3 extends UseCase<String, String> {
  @override
  String call(String params) => 'Test';
}
```

**Comment by jakemac53** [comment]
A library is a single file _and_ its parts, so it can be extended from more than just the immediately enclosing library. In the future it may also include its augmentations. So it is a more correct term than "file".

**Comment by jakemac53** [comment]
Yeah, I also went searching for any docs and only found docs that I would characterize as misleading at best, such as the one you linked 🤦‍♂️.

**Comment by jakemac53** [comment]
I filed https://github.com/dart-lang/site-www/issues/4944 to start a conversation about the docs

**Comment by bkkoluch** [comment]
> I filed [dart-lang/site-www#4944](https://github.com/dart-lang/site-www/issues/4944) to start a conversation about the docs

Thank you, I'll be monitoring the issue 👍.

I wholeheartedly agree with sentence below:
> I think it would also be good to have a dedicated doc explaining more concretely exactly the "library" term and the "package" term.
