### ISSUE TITLE
Add using keyword for resource management

### ISSUE THREAD

**Issue by mnordine** [dart-lang/language#3128]
It'd be really nice to have something like the `using` keyword from C#. Looks like it's being considered for JavaScript, and there's a decent review [here](https://github.com/tc39/proposal-explicit-resource-management).

Looks like TypeScript is [adding it as well](https://github.com/microsoft/TypeScript/issues/52955).

I guess this would mean introducing a `Disposable` interface in the standard lib, and implementing it for relevant classes.

**Comment by julemand101** [comment]
Sounds like a duplicate of: https://github.com/dart-lang/language/issues/2051

**Comment by mnordine** [comment]
I thought it may have already existed, but search didn't reveal anything, closing.
