### ISSUE TITLE
Extension methods need to be able to call method of same name in base class

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/language#3142]
When extending a class, in an override method, it is possible to call the method in the original class (the superclass), by calling `super.method()`. However, the same sort of mechanism (for calling the method of the same name and signature in the base class) does not appear to be available for extension methods.

Usecase: I want to expose a protected method of a base class by defining a method of the same name in an extension, and then use the extension method to call the protected method in the base class. (Specifically, I want to define an extension to `ValueNotifier` that publicly exposes `ChangeNotifier.notifyListeners()`.)

If this is currently possible, it is not [documented](https://dart.dev/language/extension-methods).

**Comment by lrhn** [comment]
If the base object type has a member of the same name as the extension, then it takes precedence over the extension member. Using the *same* name won't work at all, you'll never call the extension anyway.

That is, calling the original method is not the problem.

That also means that you can directly call the original instead 
In this case, the original is annotated with `@protected`, but that's just an annotation, it doesn't prevent you from calling the method, it just makes the analyser give a warning if you do.
You should be able to ignore that warning using `// ignore: name-of-warning`.

**Comment by lukehutch** [comment]
Got it, thanks for explaining!
