### ISSUE TITLE
Strange behaviour with catching exceptions

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/language#3155]
Hi,

I'm currently experimenting with the catching of exceptions and I found one behavior that is not what I expected:

```dart
Future<void> asyncFunctionError() async {
  throw Error();
}

Future<void> asyncFunctionAssignFuture() async {
  try {
    final future = asyncFunctionError();

    //await Future.delayed(const Duration(seconds: 1));
    await future;
  } catch (e) {
    print('caught in function: $e');
  }
}

void main() async{
  try{
    await asyncFunctionAssignFuture();
  }
  catch(error)
  {
    print('caught: $error');
  }
  await Future.delayed(const Duration(seconds:1));
  print('done');
}
```
prints out 

```
caught in function: Instance of 'Error'
done
```

which I expected. if I add the Future delayed in `asyncFunctionAssignFuture` like

```dart
Future<void> asyncFunctionAssignFuture() async {
  try {
    final future = asyncFunctionError();

    await Future.delayed(const Duration(seconds: 1));
    await future;
  } catch (e) {
    print('caught in function: $e');
  }
```

I suddenly get this output 
```
: Instance of 'Error'Error: Instance of 'Error'
caught in function: Instance of 'Error'
done
```
despite that fact that the exception was caught I get the error message and if this is inside a test, the test fails which I don't expect when catching an exception.

**Comment by Mike278** [comment]
I've been bit by this before too :) Have a look at [this part](https://api.dartlang.org/stable/dart-async/Future-class.html#:~:text=however%2C%20it%20also%20means%20that%20error%20handlers%20should%20be%20installed%20early) of the Future docs.

**Comment by Mike278** [comment]
I've been bit by this before too :) Have a look at [this part](https://api.dartlang.org/stable/dart-async/Future-class.html#:~:text=however%2C%20it%20also%20means%20that%20error%20handlers%20should%20be%20installed%20early) of the Future docs.

**Comment by escamoteur** [comment]
Thanks, yeah, seems like this is a behavior as designed, but it's not at all intuitive

**Comment by lrhn** [comment]
The behavior is deliberate.
The underlying idea is that no error must go unnoticed by mistake. 
The only way to ensure that is to report the errors when they happen. Allowing any delay is arbitrary and unpredictable.

The alternative would be to allow sync errors to be ignored if nobody listened to the future. You can do that yourself by rubbing the code in a zone which ignores uncaught errors, but that's discouraged, just like a catch-all which ignores synchronous errors.

**Comment by lrhn** [comment]
The behavior is deliberate.
The underlying idea is that no error must go unnoticed by mistake. 
The only way to ensure that is to report the errors when they happen. Allowing any delay is arbitrary and unpredictable.

The alternative would be to allow sync errors to be ignored if nobody listened to the future. You can do that yourself by rubbing the code in a zone which ignores uncaught errors, but that's discouraged, just like a catch-all which ignores synchronous errors.
