### ISSUE TITLE
Replacing exception by typed null?

### ISSUE THREAD

**Issue by sirius0xff** [dart-lang/language#3161]
Null can thought of as a kind of anormali / error, what's missing (compare to exception) is the detailed information of the error. That can be added by some kind of typed null and allow the great sound null safety engine to do the rest.
It then would allow all the nice null chaining / checking syntax ( `??` `?.` `!` )to be used for error/exception.

It basically mimicks the rust approach.
The traditional try catch way of handling exception is very verbose. 
The idea is to try to utilize existing null related features to simplify code.

**Comment by elliotPopina** [comment]
Like `try?` in swift ?

in personnel project to do the same of swift i have created this little helper
```
T? tryOrNull<T>(T Function() call) {
     try {
         final value = call()
     } catch(err) {
         debugPrint(err.toString())
         return null   
     }  
}
```

**Comment by munificent** [comment]
The flow analysis we do for null safety is built on Dart's existing type promotion flow analysis, which works for any type. If you want error values and flow analysis to handle them, you can already do that using subtyping:

```dart
sealed class Result<T, E> {}

class Success<T, Never> extends Result {
  final T value;
  Success(this.value);
}

class Failure<Never, E> extends Result {
  final E error;
  Failure(this.error);
}

/// Tries to get the resource at [uri]. Returns `Success<String>` with the
/// contents if successful or `Failure<NetworkError>` if not.
Result<String, NetworkError> httpGet(String uri) { ... }

main() {
  var result = httpGet('http:example.com');

  // Using type promotion:
  if (result is Success) {
    print('Downloaded ${result.value}');
  } else if (result is Failure) {
    print('Error ${result.error}');  
  }

  // Using a type switch:
  switch (result) {
    case Success(:var value):
      print('Downloaded $value');
    case Failure(:var error):
      print('Error $error');  
  }
}
```

I'm going to close this because I think the language gives you enough tools already.

**Comment by jakemac53** [comment]
@munificent I edited your example to forward the type parameters through to the Result (previously they were both dynamic) but it looks like that breaks type promotion later on.

Is there a reasonable way to fix that?

**Comment by munificent** [comment]
Yeah, this touches on a weird corner of type inference and exhaustiveness checking. Ideally, I think the types sould be defined like:

```dart
sealed class Result<T, E> {}

class Success<T> extends Result<T, Never> {
  final T value;
  Success(this.value);
}

class Failure<E> extends Result<Never, E> {
  final E error;
  Failure(this.error);
}
```

Logically a `Success<int>`, for example, should be considered a valid subtype of `Result` as long as the `Result`'s value type is `int` and for any possible error type. Likewise, `Failure<IOError>` should a subtype of any `Result` type whose error type is `IOError` regardless of the success type.

I believe `Success<T> extends Result<T, Never>` and `Failure<E> extends Result<Never, E>` correctly models that.

But type inference doesn't seem to understand that, so when you do:

```dart
  if (result is Success) {
    print('Downloaded ${result.value}');
  } else if (result is Failure) {
    print('Error ${result.error}');
  }
```

It doesn't know how to fill in the type arguments for `Success` and `Failure` from the type of `Result`. You end up with `Success<dynamic>` and `Failure<dynamic>`, which isn't very useful. And, then those not useful types prevent type promotion from kicking in, so `result` doesn't get promoted at all.

You can fix that by specifying the type arguments explicitly:

```dart
  if (result is Success<String>) {
    print('Downloaded ${result.value}');
  } else if (result is Failure<NetworkError>) {
    print('Error ${result.error}');
  }
```

But that's pretty verbose.

Likewise, exhaustiveness checking doesn't seem to handle this type hierarchy well, even if you fill in the type arguments:

```dart
  switch (result) {
    case Success<String>(:var value):
      print('Downloaded $value');
    case Failure<NetworkError>(:var error):
      print('Error $error');
  }
```

This is exhaustive (as far as I can tell), but the exhaustiveness checker can't see it.
