### ISSUE TITLE
Pattern Matching not working on ternary operators

### ISSUE THREAD

**Issue by shinayser** [dart-lang/language#3174]
This code compiles and works properly:

```dart
void main() async {
  
  var aIntegerList = [1, 2];  
  
  //It works as expeceted!
  if ( aIntegerList case [1, 2] || [2, 3]) {
    print('Matched!');
  } else {
    print("Didn't matched!");
  }
  
}
```

But this one doesn't compile:

```dart
void main() async {
  
  var aIntegerList = [1, 2];
  
  //It doesn't compile, but why?
  print ( (aIntegerList case [1, 2] || [2, 3])? 'Matched!' : "Didn't matched!" );
  
}
```

It gives the following error:
`Conditions must have a static type of 'bool'.`

Dart version: 3.0.5

**Comment by shinayser** [comment]
Interesting I didn't know.
That sounds pretty non-intuitive for me: if the case returns false for the if why not else on other locations like ternary operators?

**Comment by munificent** [comment]
> if the case returns false for the if why not else on other locations like ternary operators?

When we added patterns, we didn't add a `case` expression that you happen to be able to use inside an if condition. We added an explicit `if (expr case pattern)` *statement* form. That's the only place where you can use `case` after an expression.

We discussed generalizing that in the initial design, but we didn't have time to work through all of the consequences around precedence and variable scoping.

There is a feature request to support using `case` in more places: #3059.

**Comment by shinayser** [comment]
Thanks for the clarification @munificent . Congratulations for your work on that feature. Patter Matching is the thing I am loving most on dart nowadays :)
