### ISSUE TITLE
How will primary constructors affect the macro apis?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3178]
- Will you be able to annotate the fields with macros in some way? What should that look like?
- How should they show up when introspecting on a class? Does it look like the desugared form only (a constructor + some normal fields)?
- Should it show up somehow on the `ClassDeclaration` class? Today this just gives you access to all the parts of the class declaration but not its members. A primary constructor looks like part of the declaration, but it might be weird to actually have it show up in the API there as its really just syntactic sugar for some members.

**Comment by lrhn** [comment]
My, uninformed, opinion:

* You can normally annotate parameter syntax, so you should be able to annotate primary constructor parameters individually. If your annotation has a `@Target` annotation itself, then it may be able to imply that it applies only to the induced constructor parameter, or only to the induced field - but it may be tricky to distinguish between applying to the constructor parameter, and the field's implicit setter's parameter, if you need both. So maybe we should introduce an annotation which allows nesting another annotation, and decides what it applies to, like;
    ```dart
    class C(
       @Targeted(at: Target.setterParameter, MyOwnFieldAnnotation(...)) 
       @Targeted(at: Target.constructorParameter, MyConstructorParameterAnnotation(....)) 
       int fieldName,
    ) {
      // ...
    }
    ```
    We may need to extend `Target` with more specific targets for that. Since it's an enum, that could be breaking.
    (It should perhaps be a sealed family of singleton classes instead, so `constructorParameter` and `setterParameters`
    could be subclasses of `parameter`, and we can keep adding sub-targets in the future.)

* I'd recommend showing only a semantic model, not the syntax, to macros, if possible. And then it should show the desugared result of a primary constructor (with `Targeted` annotations already distributed onto their respective targets).
I don't know how it currently works, but removing syntax specific from the equation is almost always a good idea, when you're not writing a formatter. (If we allow generating source code, maybe even pre-generating it, then it's another issue.)

* So I'd say treat it as an implicit constructor + fields declaration, and only expose the desugared results.

**Comment by jakemac53** [comment]
> * If your annotation has a `@Target` annotation itself, then it may be able to imply that it applies only to the induced constructor parameter, or only to the induced field - but it may be tricky to distinguish between applying to the constructor parameter, and the field's implicit setter's parameter, if you need both.

The macro apis do express whether they target functions, variables, classes, enums, etc. But one macro might target several of those things so I think it gets complicated to just infer this.

Ultimately I think it's probably ok to just say you can't use primary constructors if you want to apply a macro the any of the fields or the constructor, but that may be limiting. We could always add it later though.

> * I'd recommend showing only a semantic model, not the syntax, to macros, if possible.

Yeah this is generally how it works, you don't get tokens, but there are getters for the super class, interfaces, mixins, etc. It isn't clear if or how the primary constructor should fit into that.

> So I'd say treat it as an implicit constructor + fields declaration, and only expose the desugared results.

This is also the way I am currently leaning.

**Comment by eernstg** [comment]
I don't think this contradicts anything @lrhn said, but I'd start by saying that the desugaring that creates a normal (non-primary) constructor from a primary constructor would include rules about how to desugar metadata.

To get started, I'd propose that the metadata on a parameter of a primary constructor is associated with that parameter, and it is also associated with the instance variable declaration which is generated as a consequence of having this parameter (if any --- `super.x` doesn't have any, and `this.x` is associated with an explicitly declared instance variable).

This would cause the annotation to be associated with the parameter as well as the instance variable declaration in some cases. I'd assume that some kind of targeting can be used to ensure that it is ignored on the parameter or on the instance variable declaration in the cases where it is intended to apply to one and not the other.

> Should it show up somehow on the `ClassDeclaration` class? 

It seems natural to me that a primary constructor is treated the same as the desugared constructor that it gives rise to. It is a concise notation, but there's nothing to say about the _meaning_ of a primary constructor which differs from anything you would say about the corresponding desugared non-primary constructor.

**Comment by munificent** [comment]
> * Does it look like the desugared form only (a constructor + some normal fields)?

I think this is the real question. For syntactic sugar features, is there a "core Dart" that they desugar too before the macro API sees them, or do macros see the language in all its glory.

There are pros and cons in both directions. Desugaring before running macros can make it easier to author macros that work with a wider variety of inputs as long as those inputs desugar to the same core forms.

But this essentially requires us to define and specify a second "core Dart" language. I think that will be almost as difficult as designing a full language. Deciding what's sugar and what isn't is *really* hard. Is a `switch` expression sugar for a switch statement? What if it appears in a context where a statement isn't allowed (like a field initializer)? Is it sugar for a series of `?:`? or maybe switch *statements* should be desugared to switch expressions? Should the core language just do away with the statement/expression distinction entirely to avoid problems like that?

Do we just throw kernel at macros? What if the best core representation for macros isn't a good IR for compilers?

I suspect if we go in this direction, it would just become a rathole. I'd rather just say that macros see the code as it was written by the user (but statically analyzed). That can make macros more tedious to write and brittle when it comes to language changes. But I think the total cost to keeping those macros up to date when we add new syntactic sugar is less than the work to define and maintain a "core Dart" language.

**Comment by lrhn** [comment]
I tend to have the opposite perspective. We already have an abstraction over the physical syntax. Which is good, physical syntax is awfull, full of small weird idiosyncrazies. (Like `Function(int x, [])` not being allowed, so you need to handle `Function(int x)` and `Function(int x, [int y])` as completely separate cases.)

The question then becomes a matter of degree, how much of the syntax do we hide.

Macros write augmentations that are applied to the library. Augmentations should work at the member-level, and never care whether a library declares a constructor using primary constructor syntax or not. That should be an implementation detail. If it isn't, we're leaking implementation in the library/augmentation abstraction level.
Same way an augmentation probably shouldn't distinguish whether a class has a field or a getter/setter pair. It should work the same on top of both.

That doesn't mean the macro system cannot know, just that it doesn't necessarily have to. If it can't treat augment a primary constructor in any way different from how it'd augment a non-primary constructor, it might not *need* to know in most cases.

That suggests, to me, to have an API which exposes the class members induced by declarations, without needing to see the underlying details. And then maybe also a layer below, which you have to ask for (`if (declaration.syntheticSource case var source?) checkOrigin(source);`. If you *want* to know whether a constructor member was introduced by a primary constructor, you can ask. If you don't need to know, you should be able to use the primary macro API without it ever getting in your way.

**Comment by jakemac53** [comment]
I am curious @scheglov how you would surface primary constructors (and the implicit fields) through the analyzer apis? We probably have a lot of the same design decisions.

**Comment by scheglov** [comment]
For AST we have no choice, we will represent all tokens, and build nodes like `PrimaryConstructorDeclaration`.

For element model, it does not matter how the constructor was declared, we will build `ConstructorElement`, and the consumer (e.g. the resolver inside the analyzer) will not need to know how it was declared. Just as we automatically add the default constructor when the class does not declare any.

**Comment by munificent** [comment]
> So that sounds like a vote for not exposing primary constructors specifically, and instead just the fields/constructor that they introduce.

That sounds reasonable to me. I do think we should at least expose a property on the constructor that lets a macro ask if it was declared as a primary constructor or not. I can imagine someone might want to author a macro that does something special only for primary constructors. If they are completely desugared, then the macro wouldn't know which constructor to work on.

**Comment by davidmorgan** [comment]
SGTM
