### ISSUE TITLE
Language Versioning should require `@dart` comment in parts

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#318]
The analysis server analyzes all of the files in one or more directories without having any foreknowledge about which files define a library and which are parts of a library. That means that it needs to be able to parse a part file without first knowing which (if any) libraries contain that part.

For some potential language changes, the way in which the file should be parsed might depend on the version of language being supported. If the supported language version is only specified in the library, then analyzer won't be able to know the version and hence won't know how to parse the file.

It's also the case that a given part file can be included by more than one library (as long as those libraries will not both be loaded by any given `main`). In those cases the parsing of the file becomes ambiguous, which will lead to a poor user experience.

Our proposed solution to these problems is to modify the Language Versioning proposal to say that
- every _file_ (rather than library) is assigned a language version,
- every file can include a version override, and
- the assigned version of a part must match the assigned version of the library that includes it.

That will allow server to correctly parse a part file before knowing which language version was assigned to the library. That will also make it impossible for valid code to contain a part that needs to be parsed in two different ways.

**Comment by bwilkerson** [comment]
@danrubel @leafpetersen @lrhn @stereotype441

**Comment by munificent** [comment]
+1. This affects dartfmt too, which works on a per-file basis, not per-library.

**Comment by lrhn** [comment]
I never want a part file to have a language version different from its library.

That means that even if you can put a language version marker in the part file, it must always be exactly the same as in the library. 
You should just use `part of "library.dart"` as the part declaration, then it is possible to read the version off the library file.

Or, in other words, I'm not particularly sorry for making life hard for people who import the same part from two different libraries, and if you don't, you should use `part of "library.dart"` so the tool can find the library.

I'd be fine with disallowing `part of library.name;` entirely.

**Comment by bwilkerson** [comment]
> I never want a part file to have a language version different from its library.

Agreed, and part of what I proposed.

> You should just use `part of "library.dart"` as the part declaration, then it is possible to read the version off the library file.

Even if that would work (which I'll address below) that has the disadvantage of requiring tools to read two files in order to process a single part file.

> ... I'm not particularly sorry for making life hard for people who import the same part from two different libraries ...

It also makes it hard for tool providers.

> I'd be fine with disallowing `part of library.name;` entirely.

I'd love to see that happen, and given that nnbd is already a breaking change you could consider rolling that change into it.

But that doesn't change the fact that we need to know the language version at the time that we're parsing the file, not after we've parsed it, discovered a part-of directive, and parsed at least the initial comments in the library file that it references.

**Comment by bwilkerson** [comment]
Has there been any progress or decision on this issue?

**Comment by lrhn** [comment]
The latest version of the document says that part files may contain version numbers. They do not have to. 

Tools should do a best-effort attempt to recognize part files that are parts of known libraries, but if the can't, they can default to the newest version.

Any use of the part file as part of the library should still work, they will see the library file first. Only tools looking at part files independently, meaning editors and the formatter, needs the distinction, and then the person in charge is in the perfect position to add the marker if they want to.

That means that you should be able to pars the `part of` declaration without knowing the language version. If we ever change that syntax, we'll take it from there.

(The formatter is the biggest issue, and may be reason enough to require part files to have the mark. I'm being swayed in that direction.)

**Comment by leafpetersen** [comment]
I think per latest discussion we have agreement that all files must be marked.

**Comment by lrhn** [comment]
Yes. I have updated the document since I wrote this comment.

So now all files either run at the default language level, or they must be marked. If a library is marked, so must every part file it includes be, and they must be marked with the exact same version.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/153702 will check for consistency in analyzer.
