### ISSUE TITLE
Unable to use type inference in switch when using non-local fields.

### ISSUE THREAD

**Issue by SEGVeenstra** [dart-lang/language#3191]
I'm using `freezed` for my project and really loved the [`.map`/`.when`](https://pub.dev/packages/freezed#when) methods it generates.

Now that Dart has sealed classes and pattern-matching, these methods have become redundant.

When migrating from these methods to the new pattern-matching I ran into a situation that forces me to do things I don't really like.

One of the places where I use freezed objects is as state-objects for my blocs/cubits. For example:

```dart
Future<void> updateValue(String newValue) async => state.mapOrNull(
  editing: (editingState) {
    emit(
        // I can use copyWith because editState has been inferred as its subtype
        editingState.copyWith(
           value: newValue,
         ),
      );
  }
);
```

To achieve this with the new switch I have to do this:

```dart
Future<void> updateValue(String newValue) async {
  // I need to store the state in a local variable for type inference to be possible.
  final currentState = state;
  switch (currentState) {
    case EditingState() :
      emit(
        currentState.copyWith(
           value: newValue,
         ),
      );
    default: 
  }
}
```

I feel like the code becomes less readable after the migration.

**Comment by rrousselGit** [comment]
You can alternatively do:

```dart
Future<void> updateValue(String newValue) async {
  // I need to store the state in a local variable for type inference to be possible.
  switch (state) {
    case final EditingState state:
      emit(
        state.copyWith(
           value: newValue,
         ),
      );
    default: 
  }
}
```

**Comment by SEGVeenstra** [comment]
@rrousselGit thanks for your reply! (and sorry for my late one)
I'm going to give it a try!

**Comment by munificent** [comment]
Yes, what @rrousselGit is the canonical answer. You don't need to copy to a local variable and promote because patterns themselves let you bind new local variables to the matched type.
