### ISSUE TITLE
Is an extension type's representation type part of its public contract or not?

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#3193]
If an extension type is declared as, say
```dart
extension type MyId._(int _it) { 
  MyId(int id) : assert(id >= 0), _it = id;
  int id => _it; 
  String name => "$_it"; }
}
```
should other code, even in other librares, be able to assume that the representation type of `MyId` is `int`, or should they not be able to assume that.

It matters if someone writes:
```dart
extension type MyInt(int id) implements MyId {
  // More methods.
}
```
If they can do that, then it becomes a breaking change for the `MyId` author to change the declaration to
```dart
extension type MyId._(({int id, String cachedName}) _it) { 
  MyId(int id) : assert(id >= 0), _it = (id: id, cachedName: "$id");
  int id => _it.id; 
  String name => _it.cachedName; }
}
```

We have three possible answers to whether the representation type is part of the public contract of an extension type, which others can *rely* on.
* Always yes.
* Always no.
* Author can decide.

The "always no" makes it very, very hard to actually include other extension types, which is one of the use-cases we want ot support, so that's not really an option.

The "always yes" makes it impossible for an extension type to hide its representation type, and prevent others from becoming dependent on it. That's something we usually do want to *allow*, it's why we added `final` to `class` declarations.

So "Author can decide" seems like the (duh) more flexible approach. But since it allows two separate modes for extension types, it's one more bit of complexity.

I propose we use `final` on an extension type to say both that it _cannot_ be implmented_by other extension methods, and that you _shouldn't_ make assumptions about the representation type in general.

However, there are more complications, and an exception to the "cannot implement" that we (read: I) will want.

There are really two modes of using `extension type`:
* The "restricted view" /"new type" mode where we create a new type, on some unrelated representation type, and add only new methods to the new type.
* The "extended view"/"extension type" mode where we implement the representation type (or at least a supertype of it), exposing all those members, and extend that with more members.

Those two are significantly different, and the `implements RepresentationTypeSupertype` of the latter is significantly different from the `implements ExtensionTypeOnSameRepresentationType` that both can also use.

Examples:
```dart
// "open" extension type. Restricted view of `num`.
extension type FancyNum(num n) {
  bool get isInt => n is int;
  bool get isDouble => n is double;
  String toFancyString() => ....;
}

// "final" extension type. Restricted view of a "hidden" type.
final extension type FancyNumCache._((num, String) _it) {
    FancyNumCache(num n) : this._((n, _toFancyString(n)));
    bool get isInt => _it.$1 is int;
    bool get isDouble => _it.$1 is double;
    String toFancyString() => _it.$2;
    static String _toFancyString(num n) => ...;
}

// Extended view of `int`, as `FancyNum` and `int`.
extension type FancyInt(int n) implements FancyNum, int {
  int toEven() => switch (n & 3) { 1 => n - 1, 3 => n + 1, _ => n};
} 

// Extended view of `FancyNumCache`.
extension type FancyNumMore(FancyNumCache c) implements FancyNumCache {
  Type get type => isInt ? int : isDouble ? double : num;
}

// Not allowed:
// extension type LookBehindTheFinal((int, String) _pair) implements FancyNumCache {
//   // ...
// }
```

The `FancyNum` extension type is just the plain, open restrictive declaration on a `num`.
It doesn't subtype `num`, but it's public knowledge that it's an extension type on `num`,
which is why `FancyInt` is allowed to `implement FancyNum`. All valid representation objects of `FancyInt` are also valid for `FancyNum`, so it's OK to include the `FancyNum` methods in `FancyInt`, and have a subtype relation.

The `FancyNumCache` declaration is `final`. That means that it's not supposed to be implemented by other extension types which have compatible representation types, because it's not part of the contract which representation type `FancyNumCache` has. If it decides to not cache the string tomorrow, it can do that.

The `FancyInt` extension also `implements int`. Even if `int` is a `final` class declaration. It's OK to do that because `int` is a supertype of the representation type itself. This is an *extended view* on `int`. 
We don't have a problem with allowing a new subtype of the final type `int`, because it requires an existing instance of `int` to create a `FancyInt`. We can't introduce _new_ values which implement `int`, without it already being an `int`.

Then there is `FancyNumMore` (all the good names were taken!), which *implements the `final` `FancyNumCache`*.
It ignores the `final` (and not just because it's in the same library). And that's OK with the exact same argument as for `implements int`: We need an instance of `FancyNumCache` to even create a `FancyNumMore`, we don't need to know what the representation type of `FancyNumCache` is, and we don't, so all we can really do is call methods on it, and extend it with more. We can't introduce a _new_ value which implements `FancyNumCache`, without it already being a `FancyNumCache`.

And the `LookBehindTheFinal` declaration is a compile-time error because it tries to implement a 
`final` extension type which is not a supertype of its own representation type. It's not creating an extended view on its representation type, it's just trying to include another extenstion type, which should have a compatible representation type, but `FancyNumCache` doesn't have a publicly visible representation type, so it's not allowed.
(Actually, it should probably be allowed *inside the same library*, to ignore the `final`, so let's assume every declaration here is in its own library.)

**That is**, the `implements int` of `FancyInt` and `implements FancyNumCache` of `FancyNumMore` are a different *kind* of `implements` to the `implements FancyNum` of `FancyInt`.

The former is *exposing the representation type* (or a supertype of it).
The latter is *including another extension type* on the same representation type.

And we should allow a `final` extension type (or a non-extension type) to occur as the former, but not as the latter.

(Does that mean we should use a different keyword, so it would be, say:
```dart
extension type FancyInt(int n) implements FancyNum extends int { ... }
```
and you can `extends` all types, even `final` ones, of any kind. Or just have very good error messages.)

## Proposal, more formally

*  Allow `final` as a modifier on `extension type` declarations.
*  If so marked, we say the declaration is "final", otherwise we say that it's "open".
*  For each type *S* in the `implements` clause of an extension type declaration *D* in library *L* 
    with representation type *R*,
    * We say the clause is _exposing a representation type_ iff the _ultimate accessible representation type_ of *S* wrt. *L* is a supertype of the ultimate accessible representation type of *R* wrt. *L*.
    * Otherwise we say the clause is _including an extension type_.
* The ultimate accessible representation types of a type *R* wrt. library *L*, UART(*R*, *L*), is computed as follows:
    * If *R* is a non-extension type, then the result is *R*.
    * If *R* is a final extension type, declared in a library other than *L*, then the result is *R*.
    * Otherwise, *R* is an open extension type, or an extension type declared in library *L*.
       Let *R2* be the representation type of *R*, then the result is UART(*R2*, *L*).
*  It's a **compile-time error** if an extension type declaration *D* in library *L* with representation type *R*
    has an implements type clause *S* and:
    * The ultimate accessible representation type of *S* wrt. *L* is not a supertype of the ultimate accessible representation type of *R* wrt. *L*.
    * *S* denotes a final extension type declared in library *L* and *D* is not final. _You can ignore `final` inside the same library, but then the subtype must also be `final`._
    * *S* denotes an open extension type and *D* is declared `final`. _Cannot leak representation type through open supertypes._.
    

The _accessible representation types_ of a type is always a chain of pairs of open extension types and their representation type, until reaching a final extension type or non-extension type. _We chould make it a list if it matters, but it hasn't so far._

## Consequences
You can prevent others from relying on the representation type, effectively making it an *implementation detail*.
That's useful.

If you have a value with a static type which is an open extension type, you always know that casting to the extension type's representation type is valid and allowed, and should keep working in the future.

If you have a value with a static type which is a final extension type, even if you can read the code and see what the current representation type is, you should not rely on it, since it's not guaranteed to keep working.

A `final class` and a `final extension type` are both opaque types that others (outside of the same library) cannot subtype, and others therefore cannot be relying on implementation details, only the public API.

It like classes, where a client of the class cannot distinguish a factory constructor from a generative constructor, but a subclass can. There are stronger links between subclasses than simply though the interface.
For a `final` class, nobody else can distinguish a factory constructor from a generative constructor, and you can change them as needed.
For a `final` extension type, nobody can create a dependence on the representation type. 
(They can still do `o as ExpectedRepresentationType`, but then they should also know that they are relying on internal implementation details, just as badly as if they start importing `package:your_package/src/secret_sauce.dart`.)

The rule against implementing open extension types in final ones is to prevent against leaking the representation type. It's Maybe a warning would be in enough, but it does leak the representation type of the (presumed) opaque final type. Example:
```dart
extension type E1(num _) {}
final extension type E2(int _) implements E1 {}
// someone else:
E2 v = ...;
num rep = (v as E1 /* upcast */) as num; /* assumes representation type of open extension type */
```
There is nothing wrong about that code, it assumes nothing that is not in evidence in the public contracts of the classes involved, and yet it exposes the  so the error is to allow `final ... implements E1` to begin with.

The biggest annoyance is that you can't have a *private* helper extension and apply it to both open and final extensions, because it has to be `final` to be applicable to final extensions, and if so, the open extensions it's included in must become `final` too.

The rule means that final and non-final representation types become almost entirely separate, only able to interact through being representation types for each other, not being supertypes or subtypes.
(And maybe that's just how it must be, because either the entire type hierarchy exposes the representation type, or the entire type hierarchy hides it. There is no "partly hidden".)

The rule is also important in allowing us to use UART for checking whether an `implements` is valid.
If an final extension type can implement an open extension type, and an open extension type can then has the final extension type as representation type, one might start wanting to allow implementing extension types on the open supertype - becasue of the leaked representation type making it look obviously correct. Actually figuring out whether an `implements` is correct in that case requires looking at many more combinations of supertypes and representation types, not just the "ultimate" one.

As a negative consquence, people might start adding `final` to extension types as a defensive measure, because it's non-breaking to remove it, but breaking to add it later.
And others migth then start doing 
```dart
extension type MyFoo._(YourFoo foo) implements YourFoo {
   MyFoo(Arg arg) : this._(YourFoo(arg));
   // More methods
}
```
in places where they would have preferred to just do `extension type MyFoo(Arg arg) implements YourFoo {...}`.

Adding more restrictions, more rules, is more complexity for users to learn. 
I hope we can keep the story to one sentence:
> The implemented types must be non-final extension types or supertypes of this extension type's representation type.

And with an error message like:
```
The implemented type 'Bar' is a non-final extension type, which is not a supertype of the representation type 'Foo<int>'.
```
(The last part isn't entirely correct if `Foo<int>` is an open extension type, then the implemented type can also
be a supertype of `Foo<int>`s transitive accessible representation types. Will need a longer
```
The implemented type 'Bar' is a non-final extension type, which is not a supertype of any of the transitive representation types: 'Foo<int>', `Qux`, `int`.
```

**Comment by lrhn** [comment]
And after talking about this, the current idea is that every extension type will be open initially, and if a real need for restrictions comes up, we can add them later.

If you need an abstraction which enforces encapsulation, use a class.

**Comment by eernstg** [comment]
@lrhn, is there any further knowledge we can extract from this discussion, or has it already been incorporated into the upcoming extension types feature to the extent that we'd want? If so then I suppose it could be closed.

**Comment by lrhn** [comment]
The answer was "it is", so this is settled.

**Comment by eernstg** [comment]
Very good! Then I'll close it.
