### ISSUE TITLE
Intermediate variable assignments in pattern matches

### ISSUE THREAD

**Issue by nex3** [dart-lang/language#3196]
Something I've run up against occasionally when writing patterns is the annoyance of assigning a value to a variable _and_ checking that value against the pattern. Here's a simplified version of a real-world example:

```dart
switch ((arg1, arg2)) {
  case (SassString(text: 'nearest' || 'up' || 'down' || 'to-zero'), null):
    throw "Second argument may not be null!";

  case (SassString strategy, SassNumber number)
      when {'nearest', 'up', 'down', 'to-zero'}.contains(strategy.text):
    return _round(strategy, number);

  case (SassString strategy, _):
    throw "Unknown strategy $strategy.";
}
```

It's awkward to have to use a different, more verbose, and possibly slower method of checking `strategy.text` in the second case. One could imagine a syntax that allowed variable assignments to any sub-pattern:

```dart
switch ((arg1, arg2)) {
  case (SassString(text: 'nearest' || 'up' || 'down' || 'to-zero'), null):
    throw "Second argument may not be null!";

  case (
      var strategy = SassString(text: 'nearest' || 'up' || 'down' || 'to-zero'),
      SassNumber number
    ):
    return _round(strategy, number);

  case (SassString strategy, _):
    throw "Unknown strategy $strategy.";
}
```

**Comment by incendial** [comment]
How about `SassString(text: 'nearest' || 'up' || 'down' || 'to-zero') && final strategy,`?
Looks like it does exactly what you are asking.

**Comment by lrhn** [comment]
Yep, that's the recommended approach.

Dart patterns distinguish between binding and destructuring, you can't do both in one plain pattern, like in, say, C#.

What you do instead is combining two patterns with `&&`:
```dart
  DestructuringPattern && BindingPattern
```
That usually bills down to inserting just `&& var` relative to C#-like syntax like
```
 Foo(theValue: var value) foo
```

**Comment by nex3** [comment]
Oh interesting, that never occurred to me. That definitely satisfies my use-case, but it might be nice to call it out as a specific use-case for the logical-and subpattern in the documentation!
