### ISSUE TITLE
Type inference failing when destructuring in a callback function

### ISSUE THREAD

**Issue by ApoorvaAditya** [dart-lang/language#3202]
Currently, destructuring a callback's arguments in the parameter list doesn't compile. You have to accept the record as a variable and then destructure the new variable. I am not sure if this is a bug or there is another syntax to achieve this (couldn't find anything in the dart docs and online), this seemed like the most Dart-like syntax and I assumed that it would work but it doesn't compile. From what I can gather from the compiler error is that Dart is failing to infer types of the destructured arguments.  

```dart
void function1(void Function((String, int)) callback) {
  callback(("John", 23));
}

function1(
  ((name, age)) {} // Does not compile
);

function1(
  (record) {
    final (name, age) = record; // Compiles
  } 
);
```

The same thing happens for callbacks with record arguments with named fields:

```dart
void function2(void Function(({String name, int age})) namedCallback) {
  namedCallback((name: "Jim", age: 30));
}

function2(
  ((:name. :age)) {} // Does not compile
);

function2(
  (record) {
    final (:name, :age) = record; // Compiles
  }
);
```
[Here's the dartpad with the same code as above.](https://dartpad.dev/?id=d5b159f980aee697c2301ce5f9147d71)

**Comment by lrhn** [comment]
There is currently no way to destructure directly in the parameter list. Hopefully it will come in the future

**Comment by munificent** [comment]
Yes, we're definitely interested in this. But it's hard because there is already so much syntax stuffed into parameter lists that collide with patterns (like using `[...]` for optional parameters and `{...}` for named ones).

Here's the main issue: #3001.
