### ISSUE TITLE
Are macros applied on packages too? 

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#3204]
Say a package author works on a project using macros.

Are the virtual files generated at the step of `pub publish`? Or are they generated when the app depending on the package is built?

If the latter, wouldn't that mean a user could use dependency_overrides to modify the source code of packages?
It could also slow build times.

**Comment by jakemac53** [comment]
Macro files are not published with packages because they can't be - their result is potentially dependent on the exact version solve for all the transitive deps of the package.

In theory a package with no deps could ship its pre-generated macro files, but that likely isn't a corner case worth handling.

> If the latter, wouldn't that mean a user could use dependency_overrides to modify the source code of packages?

Depending on your definition of "modify the source code", yes. The hand authored code isn't modified but the macro generated code could be different based on version solves (regardless of dependency_overrides).

> It could also slow build times.

Initial build times yes, incremental build times should be unaffected. Not all commands use incremental builds today, but more and more are. `dart run` is the main offender, but `dart pub run` is incremental and `dart run` has an experimental mode now that is also incremental (`dart run --resident`).

**Comment by jakemac53** [comment]
I will close this as I think that answers the question, but feel free to re-open or just ask follow up questions

**Comment by rrousselGit** [comment]
What I'm personally worried about is that packages may want to not use macros, for the sake of build time.

For example, I could see a world where a package internally heavily relies on code-generation, and therfore wants to voluntarily keep using build_runner.
Because then, generated files would be published on pub instead of generated on clients, which could speed up their build time.

**Comment by jakemac53** [comment]
> With augmentation libraries, that could enable apps authors to override lots of things from the package. Especially if some macros become widely used, such as data classes.

I am not quite understanding what the specific concern is here?

> You mean that when packages are published on pub, they are pre-built?

No - this is about builds after the first build on a given machine. If you create an app that imports something large (like the analyzer), and then run it with `dart run -r <script>`, the first run will take a while just to compile. But if you run the same command again, it will start right away. It initializes the compiler from the previous state, and then only invalidates the changed libraries. Pub dependencies (that aren't path dependencies) will never change (unless you upgrade them). So you won't be re-running those macros all the time, only when the package is upgraded, or your SDK is upgraded.

> What I'm personally worried about is that packages may want to not use macros, for the sake of build time.

Macros are going to be quite fast to run, you can't even really compare it with build_runner. If the experience was anything like build_runner, then I agree people might want to do this. Some may feel compelled to do it anyways, but the goal is to make it fast enough that it just doesn't make sense.

**Comment by xvrh** [comment]
@jakemac53 thanks for pointing to the `dart run --resident` trick!
I just tested it and this is a real jewel.

Any chance this become the default? At least I would like to make it the default in my IntelliJ run config.

**Comment by rrousselGit** [comment]
> Macros are going to be quite fast to run, you can't even really compare it with build_runner

Some macros are bound to be slow. I have various build_runner scripts which take a few seconds to complete because they are brute-forcing the generation of many combinations of objects.

It's fine because the generator is private to the package, so it doesn't matter for end users.
But if I were to use macros instead, the cost would unlikely to be reasonable

**Comment by jakemac53** [comment]
> Any chance this become the default? At least I would like to make it the default in my IntelliJ run config.

I am only aware of its existence but not any long term plans around it. I would file an issue on the SDK asking for it to be the default and see what they say. I do think it should be the default as well, assuming it's stable enough.

> Some macros are bound to be slow. I have various build_runner scripts which take a few seconds to complete because they are brute-forcing the generation of many combinations of objects.

This is really comparing very unrelated things. I know it doesn't seem like that, but the way they run is so dramatically different that I wouldn't infer anything from build_runner behavior.

Do you know  how much time of your builder is actually spent in your code? This is also partly why we don't allow access to the full AST in macros, its bound to lead to much more complicated macros than we actually want people to write...
