### ISSUE TITLE
Macro phases example

### ISSUE THREAD

**Issue by cmkweber** [dart-lang/language#3225]
Should the type here be: `final Human? owner; // Optional, might be feral.`?

[feature-specification.md](https://github.com/dart-lang/language/blob/35c9062d2106e5673f521b4e10766f9eb649eaf7/working/macros/feature-specification.md?plain=1#L430)

Not a huge deal since it's in a readme, but could be confusing for others who may assume `Human` extends from `Owner` somewhere.

**Comment by jakemac53** [comment]
It sure does seem that way! Did you want to send a PR?

**Comment by cmkweber** [comment]
Sure, managed to submit the [PR](https://github.com/dart-lang/language/pull/3226) all through the web interface!
