### ISSUE TITLE
Allow "let" instead of "final"

### ISSUE THREAD

**Issue by cliftonlabrum** [dart-lang/language#3231]
Currently we used `final` to declare an immutable variable. 

I think it would be great to use `let` for the same thing (similar to the Swift language). It would help reduce the number of keystrokes needed and help the code be slightly less verbose. 😊

Thanks for a great language!

**Comment by lrhn** [comment]
Not a bad idea. Also not a new one 😁 
Duplicate of #136 (and #2868).
