### ISSUE TITLE
Design the diagnostic reporting API for macros

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3234]
Today you can just throw, which is treated as a compilation failure. But there should likely be another level of diagnostic that does not cause failure.

In addition to that, it would be nice if all kinds of diagnostics could attach more context - such as a specific declaration or identifier instance, and this could then be used to give more helpful errors.

**Comment by jakemac53** [comment]
cc @bwilkerson I think you might be a good person to chime in on the design here. In particular, it would be cool if macros could support quick fixes, and I am wondering what it might take to be able to support that?

**Comment by rrousselGit** [comment]
> I see there is a `correctionMessage` in the current Diagnostic API, but I don't know if that is what is used for quick fixes at all or if its just there so it can be presented to the user in a consistent way, but only as generic text.

It is unrelated to quick-fixes. It is mainly an IDE layout thingy / a different way of rendering a message to users.

**Comment by jakemac53** [comment]
I don't really have any intuition about what kind of quick fixes a macro might want to produce - in fact it only just now occurred to me that they might be non-local changes.

I actually like the idea of requiring a plugin quite a lot - if we combine that with the ability to produce "data" severity messages then a macro should be able to provide enough information to a plugin about the error that it can figure out the right quick fix to suggest?

Macros also (intentionally) don't have access to source locations (although swift has an interesting approach to this that we might consider also doing, where you can get an abstract representation of a source location). But this severely limits their ability to emit quick fixes directly.

**Comment by rrousselGit** [comment]
Yeah I doubt macros could emit decent quick fixes without giving them more information about the source code.

To begin with, I doubt many of the lints I implemented for some of my packages would be doable using the current macro proposal.  
They often rely on inspecting the content of functions.

**Comment by jakemac53** [comment]
Yeah the quick fixes in this context would be specific to reasons that a macro failed to run (as in, failed to generate the desired code). Not really targeting replacing a custom linter. But I still think it would be hard for them to produce a quick fix given the information available to them.

**Comment by jakemac53** [comment]
> I'm guessing that the intent of the target is to identify where to report the diagnostic. I'll just point out that having a file and range of characters within the file isn't optional, so if the target is optional there will need to be a different way to provide the highlight range when the target isn't supplied. But I do support the idea of allowing the target to be passed in directly; it makes it much easier to consistently report diagnostics.

There would be a default target which is the macro application annotation itself.

**Comment by jakemac53** [comment]
API is out for review here https://dart-review.googlesource.com/c/sdk/+/317221

**Comment by matanlurey** [comment]
Not strongly related but how cool it would be if I could write lints with the same syntax and semantics as code generating macros, i.e. a macro that only issues diagnostics.

It would mean not needing a linter plugin system 😎, you just author macros in any package*

*unfortunately not as dev dependencies

**Comment by jakemac53** [comment]
> Not strongly related but how cool it would be if I could write lints with the same syntax and semantics as code generating macros, i.e. a macro that only issues diagnostics.

Yeah we have discussed this a lot, but the lack of access to method bodies today means you can't write most lints. Plus we don't have any way of a macro implicitly applying itself to declarations, so that makes it less useful as well.

> It would mean not needing a linter plugin system 😎, you just author macros in any package*

They would also show up not only in the IDE but during compilation in the CFE. So that could be nice, or not, depending on your perspective haha.

**Comment by rrousselGit** [comment]
Thinking about it, I wonder if macros should even be allowed to emit an info/warning.
Errors are fine, but optional metadata, I'm less sure about it.


It could push folks into using macros even when not needed, for the sake of custom warnings. I'm not sure that's a desirable outcome.

Ultimately we need an official and efficient analyzer plugin mechanism.

**Comment by jakemac53** [comment]
> Thinking about it, I wonder if macros should even be allowed to emit an info/warning.

I definitely think they should be able to. I also think the compilers should support suppressing info/warning messages for those who do not want them during compilation.

> It could push folks into using macros even when not needed, for the sake of custom warnings. I'm not sure that's a desirable outcome.

I really doubt that this will actually happen, because they just aren't going to be very useful for this purpose.

**Comment by rrousselGit** [comment]
Someone might be tempted to depend on analyzer, analyze a Code object, and send lints this way.
I could see folks making annotations designed to be placed on a `library` statement to enable specific lints in the file.

**Comment by jakemac53** [comment]
Finally circled back here after vacation etc - I did remove the `data` severity after discussion in the PR. The API is also not exactly what I would want, but it is fully compatible with the analyzer/cfe model for diagnostics, and it supports the important pieces here.

I did not end up including the `data` level of diagnostic, there was some concern over whether that is an abuse of the api, and it also wouldn't be able to translate to the analyzer/cfe representations of diagnostics since they don't have that severity level. So at a minimum this would need to happen holistically across the APIs such that the messages can be converted back and forth, but its likely a hard sell.

**Comment by rrousselGit** [comment]
:(
A way for macros to send messages to analyzer is quite important IMO. Otherwise folks will end-up having to rewrite their parsing logic in what's effectively two different languages (analyzer's Element vs macros' Code)

That would seriously hinder my ability to produce lints for my packages.

**Comment by jakemac53** [comment]
The idea isn't necessarily dead in the water, it's just not happening right now. We could also possibly add some other mechanism which is similar in concept, but doesn't go through the diagnostics API.

**Comment by jakemac53** [comment]
This has landed now
