### ISSUE TITLE
Consider requiring a keyword to open a declaration up to augmentation

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3238]
Today an augmentation can freely augment anything from the original library. This might be a bit confusing to users, because the only indication that something might be augmented is the `import augment` directive, but that is very separated from the actual declarations that are augmented.

We could solve this issue by requiring an extra keyword on any declaration that can be augmented, for instance we could just re-use the `augment` keyword. This would add additional boilerplate

If we decide that it is a good idea to add such a keyword requirement, we would have to also decide if that is necessary for all, or just some declarations. In particular, we might only want to require this keyword for declarations which have members, but not other declarations. The reason is that we can't change the fundamental shape of variable or method declarations through augmentation - while the implementation might change, how you interact with it does not. But for declarations that have members, we can add entirely new members, and for some of them we can also alter their super types in possibly surprising ways (add with, implements, extends, or on clauses).

This all needs to be balanced against the extra boilerplate caused by these keywords (also why we might not want to require it for _all_ declarations).

It is also worth noting that in C# all parts of a partial class are marked as `partial`.

**Comment by jakemac53** [comment]
cc @munificent not sure if there is already a discussion that was had, I am sure you probably already considered this as an option originally. But it might be good to write down some of the specific reasons as to why we don't want to require this, if that is the case.

**Comment by jakemac53** [comment]
Another note here is this came up specifically when we were talking about whether we should have a different syntax for macro applications than regular annotations. Is there enough of a signal that something extra is being added? In particular for macros there also is not any sort of `import augment` directive explicitly.

Requiring a keyword solves this problem both for macros and for regular augmentation libraries. If a class is incomplete and filled in via an augmentation, you will always know from its declaration.

**Comment by rrousselGit** [comment]
I'm personally against needing an extra keyword. It would enhance the keyword creep we've had as of late

Imagine:
`@data augment sealed class`


It's also counter productive IMO. We're trying to get rid of `extends _$MyClass`. Replacing it with an `augment` reintroduces the issue of having arbitrary noise, while being technically less clear.

**Comment by rrousselGit** [comment]
I don't mind changing the @ for a different symbols for macros. Although I'm not sure that's worth the trouble.


What about syntax highlighting?
We could have macro annotations be colored differently form regular annotations?

This would only work in places where analyzer is used, but that's probably enough.
In the end, annotations are already a good indicator.
It's up to package authors to respect good practices, and up to users to pick what they think is a good practice or not.

**Comment by jakemac53** [comment]
> I'm personally against needing an extra keyword. It would enhance the keyword creep we've had as of late

Yeah this also came up in some informal discussions, we already have a very large number of keywords you can put on classes.

> It's also counter productive IMO. We're trying to get rid of `extends _$MyClass`. Replacing it with an `augment` reintroduces the issue of having arbitrary noise, while being technically less clear.

I would argue it is more clear that  something "special" is going on - in particular for the case of library level macros and regular augmentations, which won't have any annotation on the class at all.

I don't know that it outweighs the other concerns, but I do think it helps indicate that a class is incomplete.

> I don't mind changing the @ for a different symbols for macros. Although I'm not sure that's worth the trouble.

Yeah I don't think its worth the trouble personally, but I don't feel super strongly about it. I would be happy either way. We do also have some special implicit coercion happening so it might be good to make it look different just because of that (from regular code to Code objects, and from Type to TypeAnnotation). They are special constructor calls that work differently from regular constructor calls (this coercion does _not_ happen for all calls of the constructor, only macro annotations).

> What about syntax highlighting? We could have macro annotations be colored differently form regular annotations?
> 
> This would only work in places where analyzer is used, but that's probably enough. Places where the analyzer isn't available wouldn't have access to the generated code anyway.

Yeah I am generally not concerned about the IDE experience, I think we have lots of good ways to make that be pretty obvious. I am more concerned about the github/text editor experience.

**Comment by rrousselGit** [comment]
> github/text editor experience.

With regards to Github, it's getting better by the day.
If analyzer officially worked on web (at Invertave we have a work of analyzer running in the browser), then Github could behave like an IDE.  

With their latest Github Block, we can customize the rendering of specific files. You can now have static analysis in TS/JS files within GitHub itself if you want to. Dart could do the same

**Comment by munificent** [comment]
I think we discussed this way back in the day. I agree with @rrousselGit that classes don't need more keywords decorating them.

**Comment by munificent** [comment]
Closing this because I think the proposal is where we (or at least I) want it to be. Happy to re-open if others disagree.
