### ISSUE TITLE
Calling clear() immediately after passing List through callback results in empty List being received

### ISSUE THREAD

**Issue by KyAaBo** [dart-lang/language#3244]
When triggering a callback with an `Object` parameter which includes a populated `List<Object?>` field, then immediately calling `.clear()` on the `List`, the callback receives an empty `List`. This issue does not occur when assigning an empty `List` instead (e.g., `myList = []`).

As I've found a workaround, I don't need a solution for this - just pointing this out as I assume this is not expected behavior.

**Comment by srawlins** [comment]
This sounds like expected behavior to me, but I'm not sure I understand the instructions. Can you provide a stand-alone reproduction?

**Comment by KyAaBo** [comment]
I did a bit of testing, and it looks like the behavior actually only occurs if my callback is publishing the data to a stream.

**Code to reproduce:**
```
import 'dart:async';

void main() {
  var someList = [1, 2, 3, 4, 5];
  var someOtherList = [1, 2, 3, 4, 5];
  var someClass = SomeClass();
  
  someClass.listenToStream((someList) {
    print("In main: $someList");
  });
  
  someClass.someOtherClass?.triggerCallback(someList);
  someList = [];
  
  someClass.someOtherClass?.triggerCallback(someOtherList);
  someOtherList.clear();
}

class SomeClass {
  SomeOtherClass? someOtherClass;
  final _someController = StreamController<List<int>>();
  
  SomeClass() {
    someOtherClass = SomeOtherClass(_printList);
  }
  
  void listenToStream(Function(List<int>) callback) {
    _someController.stream.listen(callback);
  }
  
  void _printList(List<int> someList) {
    print("In SomeClass: $someList");
    _someController.add(someList);
  }
}

class SomeOtherClass {
  void Function(List<int>) someCallback;
  
  SomeOtherClass(this.someCallback);
  
  void triggerCallback(List<int> someList) {
    someCallback(someList);
  }
}
```

**Output:**
```
In SomeClass: [1, 2, 3, 4, 5]
In SomeClass: [1, 2, 3, 4, 5]
In main: [1, 2, 3, 4, 5]
In main: []
```

**Comment by srawlins** [comment]
This is expected. The control flow is as follows:

* 1\. main:  ...
* 2\. main: `someClass.someOtherClass?.triggerCallback(someOtherList);`
  * 3\. triggerCallback: `someCallback(someList);`
    * 4\. _printList: `print("Callback from SomeClass: $someList");` // prints [1, 2, 3, 4, 5].
    * 5\. _printList: `_someController.add(someList);`
 * 6\. main: `someOtherList.clear();`
 * 7\. <<< event loop cycle >>>
 * 8\. callback declared in main: `print("Callback from main: $someList");` // prints [].

Hopefully the [article on Stream](https://dart.dev/tutorials/language/streams) addresses this. If not, maybe this [article on event loops](https://medium.com/dartlang/dart-asynchronous-programming-isolates-and-event-loops-bffc3e296a6a).

**Comment by jakemac53** [comment]
Right, setting `sync: true` in the stream controller would also make it not go to the event loop, which you should very rarely use in practice but might help to understand the problem?
