### ISSUE TITLE
Instead of importing, you can call methods directly in a way like package:aaa/bbb.dart:funcName(), just like Java aaa.bbb.StaticClazz.staticMethod(), which is useful for automatically generating code

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#3248]
Instead of importing, you can call methods directly in a way like package:aaa/bbb.dart:funcName(), just like Java aaa.bbb.StaticClazz.staticMethod(), which is useful for automatically generating code

**Comment by Wdestroier** [comment]
Did you mean
```dart
import 'package:aaa/bbb.dart' show funcName;
```
?

**Comment by mateusfccp** [comment]
No, he meant to be able to access a name from a library without having to import it, by using an "extended" notation.

Example:

```dart
void main() {
  print(dart:math.pi);
}
```

Instead of:

```dart
import 'dart:math';

void main() {
  print(pi);
}
```

**Comment by Silentdoer** [comment]
> No, he meant to be able to access a name from a library without having to import it, by using an "extended" notation.
> 
> Example:
> 
> ```dart
> void main() {
>   print(dart:math.pi);
> }
> ```
> 
> Instead of:
> 
> ```dart
> import 'dart:math';
> 
> void main() {
>   print(pi);
> }
> ```

Yes, that's what I mean

**Comment by jakemac53** [comment]
Today you can determine all the dependencies of a library by just parsing the directives - this would no longer be the case (you would have to parse the entire file). So this would potentially be harmful to compile times and general import graph discovery which is done in several other tools outside the compiler. We would also have to update all those other tools to look for these kinds of dependencies.

I don't think this proposal buys enough to be worth those costs.

**Comment by jakemac53** [comment]
(plus, as mentioned we already have prefixed imports which are the "dart way" to get the same level of specificity here)

**Comment by jakemac53** [comment]
I don't have any idea for certain but I don't see how they could avoid it. The cost isn't likely huge, the whole file has to be parsed anyways at some point. But I don't see much value?

**Comment by munificent** [comment]
I agree with @jakemac53. I'm going to close this because I can't see us going in this direction.
