### ISSUE TITLE
Extension type as return type of `async`/`async*`/`sync*` function.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#3257]
The current (or soon-to-be-fixed-up) specification of async and/or generator functions (`async`, `async*`, `sync*`) requires the return type to be a supertype of a possible return value, of `Future<Never>`, `Stream<Never>` or `Iterable<Never>`, because we *know* we'll return one of those, and the only question is which element type to use.

With extension types, it's possible to have a type which *allows* a `Stream<int>` value, but which is not a supertypes of `Stream<int>`. In fact, *no* extension type can be a supertype of `Stream<Never>`.

I propose we allow a return type on an `async*` function if its *ultimate representation type* is a supertype of `Stream<Never>`. And that's also the type we use to figure out the stream element type for the function.
Similarly for `async` and `sync*`, use the ultimate representation type as the target for the return value.

So, if I have my fancy stream
```dart
extension type FancyStream<E>(Stream<E> _it) implements Stream<E> {
   fancyMethod() { ... }
}
```
and I want to return one of those from a method:
```dart
abstract interface class FancyStreamFactory<E> {
  FancyStream<E> create();
}
```
then I couldn't, with the current specification, just write:
```dart
  FancyStream<E> create() async* { .... }
```
With this change I can.
And I'll probably *want* to do that.

The workaround would be:
```dart
  Stream<E> _create() async* { ... }
  FancyStream<E> create() => FancyStream<E>(_create());
```
Nobody will thank us for making them write that.

The thing that could worry some is that we are creating a value with static type `FancyStream` without going through any constructor, or even an explicit cast. If you want to pretend that your extension type does not contain a stream internally, and want everybody to go through constructors which create finely crafted streams that are known to work, then this is a way to bypass that.
But so is `stream as YourExtensionType`. If someone really *wants* to do that, you cannot stop them.
I think the feature is important enough that this worry should be ignored.

(If someone has a lint against doing `as ExtensionType`, they might also lint against having one of these functions, or at least if the extension type doesn't have a public primary constructor. The language doesn't have to care.)

**Comment by eernstg** [comment]
It would be sound, and it seems reasonable, to use an extension type whose ultimate representation type is a supertype of `Future<Never>` as the return type of an `async` function.

This would introduce yet another way to introduce a typing of an object with an extension type without running a constructor. However, following the choices made in several other cases, we'd make no attempt to protect the encapsulation of the extension type in the language itself, we would leave this to other kinds of diagnostics (warnings and lints).

**Comment by eernstg** [comment]
In https://github.com/dart-lang/language/pull/3276, I've proposed a slightly more restrictive approach: It requires that the extension type implements `Future<T>` for some `T`, and also that the same type is the representation type of the extension type.

```dart
class MyFuture implements Future<int> {...}
extension type E(int it) {}

extension type EFuture<X>(Future<X> it) implements Future<X> {...}
extension type EImplementsSuperFuture(Future<int> it) implements Future<num> {...}
extension type EDoesNotImplementFuture(Future<Whatever> it) {...}
extension type ESubtype(MyFuture it) implements Future<int> {...}
extension type EExtension(Future<E> it) implements Future<E> {...}

EFuture<int> f1() async => 1; // OK.
EImplementsSuperFuture f2() async => /*anything*/; // Error.
EDoesNotImplementFuture f3() async => /*anything*/; // Error.
ESubtype f4() async => /*anything*/; // Error.
EExtension f5() async => E(1); // OK.
```

The point is that we're starting cautiously by requiring that we have both a representation type which is a `Future<...>`, and it `implements` exactly the same future type.

For other cases (proposed to be errors), `f4` is "bad" because `f4` will not actually return a `MyFuture`. `f3` is "bad" because its return type isn't a subtype of `Future`, and hence it will not be recognized by `unawaited_futures` and similar lints/warnings. `f2` is "slightly bad" because it reveals "part of" the future type that it actually contains (we might well allow that one in the future, perhaps it is useful?). Finally, `f5` is fine, there are no special restrictions on the use of extension types as type arguments of a `Future` type.

**Comment by lrhn** [comment]
Talked some more with Erik today, and I think the options I'd suggest we go with are, in order of preference:

* No. You can't return an extension type from an `async` function, because `Future<T>` is not assignable to any extenstion type for _any_ `T`.
* No, except for the very special case of an extension type where the representation type is, precisely, `Future<S>` for some `S` *and* the extension type implements `Future<S>`. _(Where you are really just adding methods to a `Future<S>`, nothing tricky going on whatsoever.)_

I'd go with the former, and if people _really_ can't live with that, give them the latter. That also requires *no changes* to the current specification, extension types just naturally falls into the "not allowed" group, like any other type which is not a supertype of a `Future` type.

You'll have to introduce an explicit cast or constructor call in order to convert a `Future<T>` to the extension type `MyFuture<T>`.
Example:
```dart
class MyFuture<T>(Future<T> _) implements Future<T> {
  MyFuture<T> catchError<E extends Object>(FutureOr<T> Function(E error, StackTrace stack) handleError) =>
     MyFuture<T>(_catchError<E>(handleError));
  Future<T> _catchError<E extends Object>(FutureOr<T> Function(E error, StackTrace stack) handleError) async {
        ... something something ... await ... something ...
  }
}
```
Here I can't just write the `catchError` as an `async` function, because that would return a `Future`, and not a `MyFuture`. I need to insert the cast, and either a helper method, or just an IIFE `MyFuture<T>(() async { ... }())`.

We just don't have implicit coercions in Dart, and this is consistent with that. 
(If we get implicit coercions, like a `default MyFuture(Future<T>...)` constructor that gets invoked when assigning `Future` to `MyFuture`, then it's a very different situation, because that changes *assignability* in general.)

Not doing implicit coercions for extension types also enforces the story that extension types are like (very shallow) wrapper classes, and that they are their own types, with their own subtype relations, not just aliases for their representation type. You *can* ignore that, and cast to and from the representation type, but you should do so explicitly.
The reason to disallow extension types as return types for `async` functions follows directly from their subtype relation, and assignability rules, just as for any other type. Nothing special needed, nothing special added.


Allowing the exception of the second item without an explicit cast, even if it's just an extension type which obviously directly extends a `Future` type, is introducing an implicit coercion, in one particular special place. It might be better to just hold off on that, and work on implicit cercions in full generality, so that this case won't end up as a special case that we have to work around.

And it's easier to allow more in the future, than to take away.

Same goes for `Iterable` for `sync*` functions, and `Stream` for `async*` functions. `Iterable<Never>` and `Stream<Never>` are not asignable to any extension type, so you can't use an extension type as return type.


<sub>'Perfection is achieved, not when there is nothing more to add, but when there is nothing more to take away.'</sub>

**Comment by eernstg** [comment]
The most recent update to https://github.com/dart-lang/language/pull/3276 uses option one, that is: An `async`/`async*`/`sync*` bodied function cannot have a return type which is an extension type. This is a safe bet: We can always relax restrictions in a future enhancement of a feature.
