### ISSUE TITLE
[extension-types] Ambiguity in grammar

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3258]
The implementation of extension types currently allows trailing commas in the `<representationSpecification>`. The `<representationSpecification>` is the grammatical construct which is very likely to be a temporary placeholder for a primary constructor. It seems reasonable to be well prepared for this generalization, that is, to build on parts of the primary constructor syntax as far as possible, and then restrict it using (non-syntax) compile-time errors. One of the likely consequences of this generalization is that trailing commas will be allowed (e.g., `extension type E(int i,) {}`).

However, @lrhn noticed an ambiguity that arises if we allow this trailing comma:

```dart
extension type on (int i,) {}
```

This could be an `extension` named `type` whose on-type is the record type `(int i,)`, but it could also be an `extension type` named `on` with a primary constructor with a trailing comma.

I'd recommend that we consider accepting a (presumably) small amount of breakage and make `type` a built-in identifier.

Con: If we do this then every `extension` declaration named `type` will break. I have not found any.

Pro: This eliminates the ambiguity, and it does not use any special non-CFG mechanisms (it does not introduce a new disambiguation rule, or depend on whitespace, etc).

@dart-lang/language-team, WDYT?

**Comment by eernstg** [comment]
I think this is a small issue, but I do have some reasons to lean toward making `type` a built-in identifier.

> not making `type` a built-in identifier ...
> That may not work directly for your parser generator,

ANTLRv4 doesn't have syntactic predicates, but that's just a tool thing which should not matter at all for the decision about the language. (I do have a work-around, too.)

I'm worried about the overall properties of the Dart syntax: Every single time we introduce a non-CFG mechanism for syntactic disambiguation (or indeed for any purpose), we introduce issues in relation to language processing by anyone other than the parsers that are part of the analyzer and common front end. A mechanism that happens to be easy to implement in those parsers may be a substantial hurdle for, say, the Tree-Sitter parser generator, for any LR (including LALR) parser generator, etc.

So I tend to think about this as a kind of budget that we shouldn't waste (as in "don't gratuitously make Dart even less CFG-parsable than it is already").

Another consideration could be that it would make sense to make `type` a built-in identifier if we wish to use it for other constructs (say, any kind of declaration where `type` occurs as a keyword).

> I don't know if we restrict extensions to not be named using a built-in identifier

We do. But I do think you're right that it isn't strictly necessary (I couldn't easily come up with situations where it causes parsing difficulties).

**Comment by munificent** [comment]
My understanding is a that a built-in identifier acts like a reserved word in places where a type is expected but like a regular identifier otherwise. Of all of the possible identifiers that you could use as anything *but* a type, surely `type` has to be the weirdest. I don't think there are compelling use cases for a type named `type` but, I mean, it's *literally the word "type".*

How about we instead make `on` a built-in identifier? It's already an `OTHER_IDENTIFIER`, so it already has some special magic in the spec because of `try` statements. This would just be removing it from one weird category to another one.

Also, it would be *very* annoying if syntax highlighters highlighted `type` like a reserved word, since it's so commonly used as a normal user identifier. But I'd be pretty surprised if `on` was often used as an identifier. (I can see it happening in APIs as the opposite of `off`, but I suspect it's not common.)

**Comment by lrhn** [comment]
> could use as anything _but_ a type,

Type, type variable or import prefix.

> It is a compile-time error if a built-in identifier
> is used as the declared name of
> a prefix, class, mixin, enum, type parameter, or type alias.

Notice the conspicuous absence of "declared name of an extension". We'll have to add that too, or we'd still allow `extension type` to declare an extension.

**Comment by eernstg** [comment]
At the meeting today the language team decided to disambiguate by committing to parsing an `extension type` declaration when an extension type declaration can occur, and the tokens `extension` followed by `type` have been received on the input.

**Comment by eernstg** [comment]
Specification update in https://github.com/dart-lang/language/pull/3431.

**Comment by eernstg** [comment]
Landed #3431.
