### ISSUE TITLE
[extension-types] Adjust the rule for allowed non-extension type superinterfaces

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3261]
Thanks to @johnniwinther for raising this issue!

The extension type feature specification has the following [rule](https://github.com/dart-lang/language/blob/main/accepted/future-releases/extension-types/feature-specification.md#:~:text=was%20specified%20earlier.-,A%20compile%2Dtime%20error%20occurs,-if%20V1%20is):

> A compile-time error occurs if `V1` is a type name or a parameterized type which occurs as a superinterface in an extension type declaration _DV_, but `V1` does not denote an extension type, and `V1` does not denote a supertype of the extension type erasure of the representation type of _DV_.

The motivation for including the erasure is that it provides some added flexibility. However, this issue recommends that the rule is adjusted as follows:

> A compile-time error occurs if `V1` is a type name or a parameterized type which occurs as a superinterface in an extension type declaration _DV_, but `V1` does not denote an extension type, and `V1` does not denote a supertype of the representation type of _DV_.

Here is some background, and an example illustrating the considerations about this topic that were raised in this discussion:

```dart
extension type FancyList(List<int> it) implements List<int> {
  ... // Members making the `List<int>` more convenient for some purpose.
}
```

In this example, `FancyList` is positioned as an extended version of `List<int>`: It is assignable to `List<int>` and may occur due to promotion from some supertype of `List<int>`, it's just providing those extra members.

The current specification rule allows for the representation type to use a similar type:

```dart
extension type FancyInt(int it) implements int {
  ... // Convenience members on int.
}

extension type FancyList2(List<FancyInt> it) implements List<int> {
  ... // Like before, but more convenient for working on the elements.
}
```

This allows the body of `FancyList` to use the convenience members of `FancyInt` on the elements of the list. It is allowed because the extension type erasure of `List<FancyInt>` is `List<int>`, which is a subtype of `List<int>`.

However, we couldn't use the following variant with the rule as stated today:

```dart
// `FancyInt` unchanged.

extension type FancyList3(List<FancyInt> it) implements List<FancyInt> { // Error, using the current rule!
  ... // Like before.
}
```

The error occurs because the extension type erasure of `List<FancyInt>` (that is, `List<int>`) isn't a subtype of `List<FancyInt>`, so we can't have the latter in the `implements` clause.

In general, the inclusion of an erasure at this point ensures that `implements T` where `T` is a non-extension type can reveal an arbitrarily deeply nested underlying non-extension representation type. So if we want to announce to the world that `FancyList` is really just a `List<int>` then we can do it, no matter how many layers of extension types we have used to wrap the representation object.

Conversely, we can't _preserve_ any extension types in a non-extension type in the `implements` clause (in the example, we can't have `implements List<FancyInt>`), because the required subtype relationship doesn't exist.

The updated rule which is proposed above would allow `FancyList3` as well as `FancyList2`. The updated rule just requires that the representation type is a subtype of the implemented non-extension type, it doesn't erase any extension types first.

However, this implies that the following would be an error with the proposed new rule (but it is not an error with the current rule):

```dart
extension type FancyInt(int it) {
  ... // Like before.
}

extension type FancyList4(List<FancyInt> it) implements List<int> { // Error, using the proposed rule!
  ... // Doesn't matter.
}
```

The error arises because `FancyInt` is _not_ a subtype of `int`, and hence `List<FancyInt>` isn't a subtype of `List<int>`.

All in all, this change will introduce some errors where we did not have them previously, but it also removes some errors that we had previously. In that sense it's not obvious which is better.

The motivation for doing this is primarily that the direct use of a subtype relationship is conceptually more natural than anything that involves an implicit erasure followed by a subtype check (even though the latter is sound). For example, it seems intuitively reasonable that `FancyList4` is an error, but `FancyList3` is not.

@dart-lang/language-team, WDYT?

**Comment by lrhn** [comment]
So, effectively, an extension type can implement a type if the implemented type, or its representation type, is a supertype of the extension type's representation type?

No ultimate or transitive anything.

I think it's fair.  

It seems that you can then create extension types that cannot be implemented/subtyped, by making their representation types inaccessible.
That makes the inaccessible type impossible to implement, because it cannot be named, and the extension type which has the inaccessible type as representation type because you cannot have a (non -`Never`) representation type that it or its representation type is a supertype of.

If that's possible anyway, should we just allow you to mark an extension type `final`?

**Comment by eernstg** [comment]
> So, effectively, ...

Yes, that's a nice lemma! ;-)

> you can use the other type itself as representation type

I think that wouldn't work:

```dart
// Library 'n016lib.dart'.
class _C {}
extension type E1(_C it) {}

// Library 'n016.dart'.
import 'n016lib.dart';
extension type E2(E1 e1) implements E1 {} // Compile-time error: "`E1` is not a subtype of `_C`".
```

> should we just allow you to mark an extension type `final`?

We can always do that later.

**Comment by eernstg** [comment]
#3262 has landed now.
