### ISSUE TITLE
Getting information that an object has lost last pointer to it.

### ISSUE THREAD

**Issue by brilliapps** [dart-lang/language#3272]
Hello, Is there any way, even simple, in dart to get whatever information from an object property when a pointer to the object is set to null? Below very simple and shortened code what i tried to do.
I tried to create a simple class and object 'a' of the class, the class with a 'stream' property (another was completer) hoping that when i set a = null the stream will send f.e. an onDone or onError event or anything else (tried with a controller, stream, sink), but it didn't work.

`
class PointersTest2 {
  final stream = Stream<int>.periodic(
      const Duration(milliseconds: 500), (count) => count * count);
  PointersTest2() {}
}
  dynamic a = PointersTest2();
  a = null;
`

**Comment by mraleph** [comment]
Short answer is no. None of the Dart implementations are reference counted or have value types with destructors so as such you don't know when the last reference disappears.

You can get a callback by attaching a [`Finalizer`](https://api.dart.dev/dev/3.2.0-66.0.dev/dart-core/Finalizer-class.html) but be wary of all the warnings listed in the documentation 

> No promises are made that the callback will ever be called. The only thing that is guaranteed is that if a finalizer's callback is called with a specific finalization token as argument, then at least one value with an attachment to the finalizer that has that finalization token, is no longer accessible to the program.

Also consider asking questions using community channels like Discord and StackOverflow - this issue tracker exists for tracking the evolution of the language and associated feature requests.

**Comment by brilliapps** [comment]
Thank you mraleph for your answer. Oooohhh! So there is at least one thing to try out. A little apology from me and thank you for your kindness and patience.
