### ISSUE TITLE
Type safe zero-runtime-cost sum types.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#3273]
Consider, for example, the following model:

```dart
// Model A
class Root {}

class A implements Root {
  B b;
}

class B implements Root {
  C c;
}

class C implements Root {}
```

There is an obvious optimization for representing `Model A` as an explicit graph that avoids the overhead of an object hierarchy:

```dart
// Model B
class Domain {
  // Each node is assigned a unique id from "0" to "amountOfNodes - 1"
  int amountOfNodes; // total amount of 'A's, 'B's and 'C's

  // Each node is assigned a list of nodes that they point to.
  List<List<int>> children;
}
```

Unfortunately, given such an efficient representation of `Model A` as `Model B`, there is no way to restore type safety without wrapper objects.

That is, to strongly type each node in `Model B` (to, for example, expose an efficient, safe and minimal API), we'd need a class hierarchy to model the sum type inherent to our domain. Users would be forced to pay the price of the overhead that comes with having objects.

For cases where each node can be modeled by a sum type with only one variant, [extension types](https://github.com/dart-lang/language/issues/2727) appear to be able to help. However, extension types do not appear to address the case where a sum type of one variant is not enough.

I think that supporting "inline classes/extension types" over domains that can only be modeled by sum types with more than one variant is important and I hope the language team will consider that for the design of extension types, or at least consider possible extensions to extension types in the future, that will allow that language feature to be extended to support modeling sum types with more than one variant.

**Comment by eernstg** [comment]
It seems plausible to claim that the hierarchy `Root`, `A`,  `B`, `C` can be modeled equivalently by the following enum:

```dart
enum ModelA { a, b, c }
```

The values `ModelA.a` corresponds to `A(B(C()))` (assuming suitable constructors), `ModelA.b` corresponds to `B(C())`, and `ModelA.c` corresponds to `C()`. There is no information (as far as I can see) which is not fully represented by the `enum`, and vice versa. That is, if you have one then you can reconstruct the corresponding one, with no loss of information. That's basically everything you can ever do with `Root` (assuming that it isn't intended to have a bunch of subtypes, perhaps declared by others).

So maybe you need to have a more powerful `Root` hierarchy in order to illustrate what it is that you are modeling which isn't handled just as well by a simple enum?

**Comment by modulovalue** [comment]
I apologize, it seems that my description wasn't clear enough. Here is a concrete example that should hopefully clarify things a bit:

The following example constructs a graph that contains 4 instances of Root. (_The first node is an instance of A pointing to the second node which is an instance of B which points to a node that is a C and there's a fourth node that is a C that points to nothing._)


```dart
void main() {
  final nodes = const Store(
    [Store.aTag, Store.bTag, Store.cTag, Store.cTag],
    [
      // A at 0 points to 1.
      [1],
      // B at 1 points to 2.
      [2],
      // C at 2 points to nothing.
      [],
      // C at 3 points to nothing.
      [],
    ],
  ).all();
  print(nodes);
}

class Store {
  static const int aTag = 0;
  static const int bTag = 1;
  static const int cTag = 2;
  final List<int> type;
  final List<List<int>> children;

  const Store(
    this.type,
    this.children,
  );

  Root _read(
    final int nodeId,
  ) {
    switch (type[nodeId]) {
      case aTag:
        return A(nodeId, this);
      case bTag:
        return B(nodeId, this);
      case cTag:
        return const C();
      default:
        throw Exception("Unknown Tag");
    }
  }

  Iterable<Root> all() sync* {
    for (int i = 0; i < type.length; i++) {
      yield _read(i);
    }
  }
}

abstract class Root {}

class A implements Root {
  final int _nodeId;
  final Store _store;

  const A(
    this._nodeId,
    this._store,
  );

  B get b => _store._read(_nodeId) as B;
}

class B implements Root {
  final int _nodeId;
  final Store _store;

  const B(
    this._nodeId,
    this._store,
  );

  C get c => _store._read(_nodeId) as C;
}

class C implements Root {
  const C();
}
```

To me, it doesn't look like the Root hierarchy from the example above could be replaced by an enum, because all variants of enums share the same members. That is, a `ModelA.a` could not have a `b` member without `ModelA.b` also having a `b` member.

But even if enums could be used here, the enum wrapper around `_nodeId` and `_store` would still cause a new allocation to be performed during runtime and introduce Object-related overhead? Whereas if we only had a single Root (_without A B and C_) we could make it an "extension type" over a record containing a nodeId and a store, which would remove the `Root` wrapper overhead and be zero-cost (_assuming the runtime can optimize records in ways that matter here_).

---
In pseudo-code, what I hope to be able to do with extension types would be something like the following:

```dart
extension type Root(int _nodeId, Store _store) = A {
  B get b => _store._read(_nodeId) as B;
} | B {
  C get c => _store._read(_nodeId) as C;
} | C {
  // There are no members.
}
```

That is, to have an `extension type` over a product type, that contains a nodeId and a store, where the extension type models a sum type of three variants, all with their own members.

_For future reference: The fact that a store would need to be carried around is inconvenient, the following issue was meant to focus on making that more convenient: https://github.com/dart-lang/language/issues/3169_

**Comment by modulovalue** [comment]
Thank you for the detailed analysis, Lasse. I agree with most of what you said.

**Comment by eernstg** [comment]
@lrhn wrote:
> The enum doesn't represent the different identities of the instances of `A`, `B` and `C`.

That's true. I noted that `Domain` doesn't seem to represent identities either, and jumped to the conclusion that they weren't intended to matter.

@modulovalue wrote:
> a completely different approach would be needed here.

Are you sure? ;-)

Here is a variant of the example that maintains a (presumably cheap?) representation of a set of trees with type tags and `children` lists, and allows for passing around identifications of those trees in two shapes: An unreified form which is just the index and a reference to the store, and a reified form which is the actual tree:

```dart
class Store {
  static const int aTag = 0;
  static const int bTag = 1;
  static const int cTag = 2;
  final List<int> type;
  final List<List<int>> children;

  const Store(
    this.type,
    this.children,
  );

  Root reify(
    final int nodeId,
  ) {
    switch (type[nodeId]) {
      case aTag:
        return A(reify(children[nodeId][0]) as B);
      case bTag:
        return B(reify(children[nodeId][0]) as C);
      case cTag:
        return const C();
      default:
        throw Exception("Unknown Tag");
    }
  }

  Iterable<Root> all() sync* {
    for (int i = 0; i < type.length; i++) yield reify(i);
  }
}

// Reified hierarchy.

abstract class Root {}

class A implements Root {
  final B b;
  const A(this.b);
}

class B implements Root {
  final C c;
  const B(this.c);
}

class C implements Root {
  const C();
}

// Non-reified representation using extension type.

typedef RootRecord = (int nodeId, Store store);

extension type const NrRoot<X extends Root>._(RootRecord it) {
  NrRoot(int nodeId, Store store): it = (nodeId, store);
  int get _nodeId => it.$1;
  Store get _store => it.$2;
  X get reify => _store.reify(_nodeId) as X;
}

// Usage example.

const store = Store(
  [Store.aTag, Store.bTag, Store.cTag, Store.cTag],
  [
    // A at 0 points to 1.
    [1],
    // B at 1 points to 2.
    [2],
    // C at 2 points to nothing.
    [],
    // C at 3 points to nothing.
    [],
  ],
);

void main() {
  // We can play safe.
  var nrRoot = NrRoot(1, store); // Type is `NrRoot<Root>`.
  print(nrRoot); // '(1, Instance of 'Store')'.

  var root = nrRoot.reify; // Static type `Root`
  if (root is B) print(root.c); // "Instance of 'C'".

  // When an `NrRoot` is created, the type argument `B` is just a manual
  // promise that it will be a `B`. The type system can't check that.
  var nrRoot2 = NrRoot<B>(1, store);
  print(nrRoot2); // '(1, Instance of 'Store')'.

  var b = nrRoot2.reify; // Static type `B`. Checked dynamically.
  print(b.c); // "Instance of 'C'".

  // We still have the `all` method.
  print(store.all());
}
```

**Comment by modulovalue** [comment]
Thank you for the hint @eernstg. I have replaced your reification approach with phantom types + extension-based members and now this is pretty much what I was looking for.

```dart
// This uses the retired inline classes experiment instead of extension types because inline classes are available on DartPad.
void main() {
  const Store(
    [Store.aTag, Store.bTag, Store.cTag, Store.cTag],
    [
      // A at 0 points to 1.
      [1],
      // B at 1 points to 2.
      [2],
      // C at 2 points to nothing.
      [],
      // C at 3 points to nothing.
      [],
    ],
  ).use(
    (final store) {
      String rootToString(
        final Node<RootBrand> n,
      ) {
        return n.match(
          a: (final n) => "A",
          b: (final n) => "B",
          c: (final n) => "C",
        );
      }

      for (final node in store.all()) {
        print(node.match(
          a: (final n) => [rootToString(n), "->", rootToString(n.b)],
          b: (final n) => [rootToString(n), "->", rootToString(n.c)],
          c: (final n) => [rootToString(n), "with no children"],
        ).join(" "));
      }
    },
  );
}

class Store {
  static Store? __storeInstance;
  static Store get _storeInstance => __storeInstance!;
  static const int aTag = 0;
  static const int bTag = 1;
  static const int cTag = 2;
  final List<int> type;
  final List<List<int>> children;

  const Store(
    this.type,
    this.children,
  );

  void use(
    final void Function(Store store) fn,
  ) {
    __storeInstance = this;
    fn(this);
    __storeInstance = null;
  }
  
  Node<RootBrand> _child(
    final int nodeId,
  ) {
    return _read(children[nodeId].single);
  }

  Node<RootBrand> _read(
    final int nodeId,
  ) {
    switch (type[nodeId]) {
      case aTag:
        return Node<ABrand>._(nodeId);
      case bTag:
        return Node<BBrand>._(nodeId);
      case cTag:
        return Node<CBrand>._(nodeId);
      default:
        throw Exception("Unknown Tag");
    }
  }

  Iterable<Node<RootBrand>> all() sync* {
    for (int i = 0; i < type.length; i++) {
      yield _read(i);
    }
  }
}

inline class Node<X extends RootBrand> {
  final int id;

  const Node._(this.id);
}

abstract class RootBrand {}

extension RootBrandExtension<X extends RootBrand> on Node<X> {
  R match<R>({
    required R Function(Node<ABrand>) a,
    required R Function(Node<BBrand>) b,
    required R Function(Node<CBrand>) c,
  }) {
    switch (Store._storeInstance.type[id]) {
      case Store.aTag:
        return a(this as Node<ABrand>);
      case Store.bTag:
        return b(this as Node<BBrand>);
      case Store.cTag:
        return c(this as Node<CBrand>);
      default:
        throw Exception("Unknown Tag.");
    }
  }
}

abstract class ABrand implements RootBrand {}

extension ABrandExtension<X extends ABrand> on Node<X> {
  Node<BBrand> get b => Store._storeInstance._child(id) as Node<BBrand>;
}

abstract class BBrand implements RootBrand {}

extension BBrandExtension<X extends BBrand> on Node<X> {
  Node<CBrand> get c => Store._storeInstance._child(id) as Node<CBrand>;
}

abstract class CBrand implements RootBrand {}

extension CBrandExtension<X extends CBrand> on Node<X> {
  // Empty.
}
```

**Comment by eernstg** [comment]
That's a very interesting technique, @modulovalue! I've simplified a few things (during the time where I was looking at the code in order to understand what was going on ;-).

```dart
void main() {
  const Store(
    [Store.aTag, Store.bTag, Store.cTag, Store.cTag],
    [
      // A at 0 points to 1.
      [1],
      // B at 1 points to 2.
      [2],
      // C at 2 points to nothing.
      [],
      // C at 3 points to nothing.
      [],
    ],
  ).use(
    (final store) {
      String rootToString(final Node<RootBrand> n) => n.match(
            a: (final n) => "A",
            b: (final n) => "B",
            c: (final n) => "C",
          );

      for (final node in store.all) {
        print(node
            .match(
              a: (final n) => [rootToString(n), "->", rootToString(n.b)],
              b: (final n) => [rootToString(n), "->", rootToString(n.c)],
              c: (final n) => [rootToString(n), "with no children"],
            )
            .join(" "));
      }
    },
  );
}

class Store {
  static Store? __storeInstance;
  static Store get _storeInstance => __storeInstance!;
  static const int aTag = 0;
  static const int bTag = 1;
  static const int cTag = 2;
  final List<int> type;
  final List<List<int>> children;

  const Store(this.type, this.children);

  int _check(nodeId) {
    var tag = type[nodeId];
    if (tag != aTag && tag != bTag && tag != cTag) {
      throw Exception("Unknown Tag");
    }
    return nodeId;
  }

  Node<RootBrand> _child(final int nodeId) => _read(children[nodeId].single);
  Node<RootBrand> _read(final int nodeId) => Node<RootBrand>._(_check(nodeId));

  void use(final void Function(Store store) fn) {
    __storeInstance = this;
    fn(this);
    __storeInstance = null;
  }

  Iterable<Node<RootBrand>> get all =>
      [for (int i = 0; i < type.length; ++i) _read(i)];
}

extension type const Node<X extends RootBrand>._(int id) {
  R match<R>({
    required R Function(Node<ABrand>) a,
    required R Function(Node<BBrand>) b,
    required R Function(Node<CBrand>) c,
  }) => switch (Store._storeInstance.type[id]) {
    Store.aTag => a(asA),
    Store.bTag => b(asB),
    Store.cTag => c(asC),
    _ => throw Exception("Unknown Tag."),
  };

  Node<ABrand> get asA => Node<ABrand>._(id);
  Node<BBrand> get asB => Node<BBrand>._(id);
  Node<CBrand> get asC => Node<CBrand>._(id);
}

abstract class RootBrand {}

abstract class ABrand implements RootBrand {}

extension ABrandExtension<X extends ABrand> on Node<X> {
  Node<BBrand> get b => Store._storeInstance._child(id).asB;
}

abstract class BBrand implements RootBrand {}

extension BBrandExtension<X extends BBrand> on Node<X> {
  Node<CBrand> get c => Store._storeInstance._child(id).asC;
}

abstract class CBrand implements RootBrand {}

extension CBrandExtension<X extends CBrand> on Node<X> {
  // Empty
}
```

Here is a summary of my interpretation of this technique:

- The technique makes it possible to work on a representation type (here: an `int id`).
- We look up the intended "type" of that `id` in a database (`Store.type[id]`), which is a tag (`aTag`, `bTag`, `cTag`), and then work on `id` using the extension type `Node<T>` where `T` is `ABrand` when the tag is `aTag`, etc.
- Extension methods on `Node<ABrand>`, ..., `Node<CBrand>` provide the actual behavior.

So the crucial step is that the underlying `int` is equipped with methods by being typed statically as a `Node<T>` where the `T` is chosen by looking up the type tag of that `id` in the store.

This is a from-scratch emulation of OO dispatch. Cool! ;-) It allows for polymorphism (we may see in the store that the child of an `A` is at a specific index `id2`, but the type tag of `id2` could be `BSub` which is a subtype of `B`). It also allows for surprising things like assigning a new type to an existing object (so it could be used to model objects that change type over time, e.g., as they adopt or drop roles, or as they change state.

Of course, the type soundness of the heap is not ensured by any static analysis. For example, `id2` could have a type tag of `A` even though it's supposed to be the child of an `A`, and that should be a `B` (or a subtype of `B`, which does not include `A` as declared).

So we can work on a (potentially large) store of objects, and each of them is just represented by an index into the `Store`, and references from one to the other "object" in that store, and then we glue the proper type and the proper method implementations to the "object" based on the type tag whenever needed.

I think it's useful to be aware of the fact that such a thing is possible, and it's definitely cool that OO dispatch can be emulated statically in a way that makes emulated method invocations look just like real ones. ;-)

**Comment by modulovalue** [comment]
@eernstg Thank you for the summary. I agree with what you said.
