### ISSUE TITLE
switch statements on sealed classes should be exhaustive without matching abstract subclasses. right?

### ISSUE THREAD

**Issue by craigdfoster** [dart-lang/language#3308]
Say, you have sealed class A, with abstract subclass B, which in turn has two subclasses C and D. A switch on this class would/should be exhaustively matched with only matches for C and D right? Given that B cannot be created in its own right.

See code below, which will error in Darted and VSCode:
The type 'T' is not exhaustively matched by the switch cases since it doesn't match 'B()'.

sealed class A {
  String sayHi();
}

abstract class B extends A {
  @override
  String sayHi() => "Hi!";
  
  String sayBye();
  String sayThanks();
}

class C extends B {
  @override
  String sayBye() => "Bye!";
  
  @override
  String sayThanks() => "Thanks!";
}

class D extends B {
  @override
  String sayBye() => "Ciao!";
  
  @override
  String sayThanks() => "Grazie!";
}

void testSwitch<T extends A>(T type) => switch(type) {
    C() => "C",
    D() => "D" 
};

void main() {
  var t = D();
  
  testSwitch(t);
}

**Comment by eernstg** [comment]
I'll close the issue because there is only one possible answer: "No, those switch expressions should not be exhaustive".

**Comment by craigdfoster** [comment]
OK, I see the problem (that I am trying to solve)

The Dart documentation says that

"The sealed modifier prevents a class from being extended or implemented outside its own library."

But that doesn't cascade. So class B should also be sealed.
