### ISSUE TITLE
Switch assignation is not working

### ISSUE THREAD

**Issue by busslina** [dart-lang/language#3318]
![imagen](https://github.com/dart-lang/language/assets/73592852/ea6646ae-ea15-4822-8741-2220bd3ed5f4)

I wanted to try switch assignation and `return switch` feature like multiple examples that I found on internet but no way. I'm using VSCode (I changed the Dart extension to pre-release version), I'm using last Dart version.

![imagen](https://github.com/dart-lang/language/assets/73592852/88704d75-332a-4f2b-ae43-548d1681f8c3)

**Comment by eernstg** [comment]
The features of a particular language version (such as Dart 3.0) are available when the language version of the given library is that language version or higher. If you're in a package then the _lower bound_ of the `sdk:` range is the default language version for libraries in that package. So you might just need to change that lower bound to 3.0 or higher. Alternatively, you could put a `// @dart=3.0` comment at the top of the library.

**Comment by munificent** [comment]
Yaah, as @eernstg says, it looks like your file is still using an older version of the language. The [Dart SDK supports running code at different language versions](https://dart.dev/guides/language/evolution), so even if you're on the new SDK, you might not have access to the new features until you update your program.

Also, in a switch expression, there's no `default`. Use `_` instead. (It means the same thing.)

**Comment by busslina** [comment]
@eernstg That was the thing happening... Thank you very much

**Comment by busslina** [comment]
> Yeah, as @eernstg says, it looks like your file is still using an older version of the language. The [Dart SDK supports running code at different language versions](https://dart.dev/guides/language/evolution), so even if you're on the new SDK, you might not have access to the new features until you update your program.
> 
> Also, in a switch expression, there's no `default`. Use `_` instead. (It means the same thing.)

Yeah, I copied that from an example on the web, and that example used `_` instead of `default`. I just change it to make it more illustrative.

Thank you @munificent
