### ISSUE TITLE
Consider allowing a reference to an abstract getter to be considered stable when there are no conflicting getters/fields

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#3328]
Currently, field promotion (#2020) only considers a getter invocation (`target._getterName`) to be stable if `target` is stable and, `_getterName` refers to a private final field, unless:
- There is a non-final field with the same name elsewhere in the same library, _or_
- There is a concrete getter with the same name elsewhere in the same library, _or_
- There is a concrete class elsewhere in the same library that contains a getter with the same name in its interface, but neither declares nor inherits a concrete implementation of that getter. (Such a class implicitly implements a `noSuchMethod` forwarding getter with the same name, rendering field promotion unsound).

An unfortunate consequence of these rules is that if a getter invocation refers to an abstract getter, it is considered unstable (and thus not promotable), even if all the implementations of that abstract getter are final fields. So, for example, this doesn't work, even though in principle there is no soundness reason why it shouldn't:
```dart
abstract class Base {
  int? get _i;
}

class Derived extends Base {
  @override
  final int? _i;
  Derived(this._i);
}

f(Base b) {
  if (b._i != null) {
    int i = b._i; // ERROR
  }
}

main() {}
```

A user can avoid the error (and make the getter promotable) by expressing the getter as an abstract field, like so:
```dart
abstract class Base {
  abstract final int? _i;
}

class Derived extends Base {
  @override
  final int? _i;
  Derived(this._i);
}

f(Base b) {
  if (b._i != null) {
    int i = b._i; // OK
  }
}
```

But that doesn't seem great, because abstract fields are a recent and little-known feature of Dart that many people don't even know about.

There's no good reason why the language has to work this way; the only reason it does is because when I implemented field promotion, I just didn't think about this use case. But now that I _am_ thinking about it (thanks to a comment from @munificent), it seems like a real shame to prohibit promotion in the case where the idiomatically common case of an abstract getter whose only implementations are final fields, and force users to use a non-idiomatic abstract field instead.

Long term, I definitely think it would be better to change the behaviour of field promotion so that both of the examples above will be allowed. My only question is, should we do it for Dart 3.2 Beta 3, or postpone it until Dart 3.3? Our usual practice is not to land any new language features after the cutoff date for Beta 2 (which happened on August 30), but I think I lean toward considering this a bug fix to an existing language feature rather than a brand new language feature, so I'm inclined to try to do it for Beta 3.

@dart-lang/language-team, thoughts?

**Comment by eernstg** [comment]
I'd prefer that an explicitly declared getter, abstract or not, is only considered stable if it is syntactically recognizable as stable. We don't have syntax for that, so we can't do that for now.

(For instance, we could allow the modifier `final` on a getter declaration, and that would make it stable.)

We could have a quick fix that changes an abstract instance getter to an abstract final instance variable.

**Comment by leafpetersen** [comment]
I'm not strongly opposed, but in general I think it may be time to stop trying to stake out additional little bits and corners here.  There's lots of little things we could do, but at some point I'm not sure the ROI is there.

> We could have a quick fix that changes an abstract instance getter to an abstract final instance variable.

This is a good suggestion.

**Comment by stereotype441** [comment]
Unforunately, I didn't get a chance to get to this before the branch cut for the 3.2 release. I personally don't think there's a big enough return on investment to make it worth our while to implement this in a later release, so I'm closing this issue.

If folks have strong feelings that we _should_ do it for a future release, feel free to reopen and I'm happy to discuss.

**Comment by stereotype441** [comment]
After some further discussion in https://dart-review.googlesource.com/c/sdk/+/332746, I now think it's important to fix this.

The problem is that currently, a property access is considered eligible for promotion if it "resolves to a private final field", and there isn't any other declaration in the same library that blocks promotion of fields with that name. But "resolves to a private final field" isn't a notion that's defined by the spec; the spec just talks about property accesses resolving to interface members, and interfaces never contain fields, they contain getters instead. You could try to talk about the notion of an interface getters "arising from" a particular field declaration, but that's ill-defined when multiple inheritance is involved. Pop quiz: what does this code do?

```dart
abstract class A {
  abstract final int? _field;
}
abstract class B {
  int? get _field;
}
abstract class C implements A, B {}
test(C c) {
  if (c._field != null) {
    int i = c._field; // OK? ERROR?
  }
}
```

Follow-up quiz questions: what happens if you replace `implements A, B` with just `implements A`, or just `implements B`? What happens if you change it to `implements B, A`?

Spoiler alert: `implements A, B` and `implements A` are accepted by both the analyzer and CFE. `implements B, A` and `implements B` are both rejected. This seems particularly bad, because `implements A, B` and `implements B, A` shouldn't behave differently from each other.

Here's my understanding of what's happening: in order to save time and memory, and in order to make error messages and code navigation more intuitive, the analyzer and CFE blur the distinction between an interface getter and the field that it arose from. (The CFE doesn't distinguish them at all; the analyzer *does* distinguish them, but it has a handy getter to map the former to the latter: `PropertyAccessorElement.variable`). Before we had field promotion, it didn't matter that the implementations blurred this distinction, because the language spec *didn't* blur it, and the implementations faithfully reflected the language spec. But now I've gone and implemented field promotion in a way that exposes the blurriness to users. The reason `implements A, B` allows promotion and `implements B, A` doesn't is that when combining equivalently typed getters between two interfaces, the analyzer and CFE just re-use the getter from the first interface it was found in. But the getter for `A._field` is promotable and the getter for `B._field` isn't, which means that field promotion behavior now depends on the order in which the interfaces are listed.

I now think we should completely drop the ill-defined notion of checking what declaration a property get "resolves to", and adopt this rule (based on a comment from @lrhn in https://dart-review.googlesource.com/c/sdk/+/332746): "You can promote a private instance getter access, if all concrete implementations of that getter are final fields. It stops working if there is any concrete getter-declaration, concrete non-final field, or nSM-forwarding getter implementing the same name."

Which means that this would become OK:
```dart
abstract class Base {
  int? get _i;
}

class Derived extends Base {
  @override
  final int? _i;
  Derived(this._i);
}

f(Base b) {
  if (b._i != null) {
    int i = b._i; // OK
  }
}

main() {}
```

This would be allowed too, due to the fact that there's no concrete implementation of `_i` (even though it's useless because there's no way to concretely implement `_i` without disabling field promotion):
```dart
abstract class Base {
  abstract int? _i;
}

f(Base b) {
  if (b._i != null) {
    int i = b._i; // OK
  }
}

main() {}
```

I'll add an agenda item to discuss this at the next language meeting.

**Comment by eernstg** [comment]
Sounds good, let's use that rule:

> "You can promote a private instance getter access, if all concrete implementations of that getter are final fields. It stops working if there is any concrete getter-declaration, concrete non-final field, or nSM-forwarding getter implementing the same name."

**Comment by lrhn** [comment]
> (even though it's useless because there's no way to concretely implement `_i` without disabling field promotion):

Challenge accepted:
```dart
abstract class Base {
  abstract int? _i;
}

class Based extends Base {
  final int? _i;
  Based(this._i);
  set _i(int? _) { print("Nope"); }
}

void f(Base b) {
  if (b._i != null) {
    int i = b._i; // OK
    print(i);
  }
}

main() {
  f(Based(42));
}
```
Currently gets:
```
Info: '_i' refers to a property so it couldn't be promoted.
  abstract int? _i;
                ^
```
(What's a "property"? Something with a setter? Shouldn't matter as long as there is no concrete *getter* preventing promotion.)

**Comment by stereotype441** [comment]
We agreed in today's language meeting to make a breaking change in Dart 3.3 that addresses this, along the lines of my suggestion from https://github.com/dart-lang/language/issues/3328#issuecomment-1792511446. I'll take this through the breaking change process.

**Comment by stereotype441** [comment]
This was implemented in https://github.com/dart-lang/sdk/commit/004f564f40cee1deba2593ef3fd6d197482b27c1.
