### ISSUE TITLE
Linter should catch function references that are missing parentheses

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/language#3334]
I have run into this issue numerous times, so I thought I would suggest a linter check to catch this...

(1) Wrong:

```dart
            onValueChanged: (_) => ProfileData.profileChanged,
            onCommit: ProfileData.commitProfile,
```

(2) Correct:

```dart
            onValueChanged: (_) => ProfileData.profileChanged(),  // Parens were missing
            onCommit: ProfileData.commitProfile,
```

The pattern shown for `onCommit` (passing a function reference) is so common that when I need to create a "function call adapter" (as in the case of `onValueChanged`) to drop a parameter or something (in cases where the function reference can't be used directly), I commonly forget to add the parentheses. The effect of this is that the function is never called, and I can't figure out why my code doesn't have the expected effect. I have stared at the wrong code many times and not seen that the `()` parens were missing at the end of the function reference.

It should be obvious to the linter that the value produced by the `onValueChanged` lambda in (1) has no effect and is not used anywhere, especially since the return type of `onValueChanged` is `null`.

**Comment by lrhn** [comment]
(Now, if we didn't allow `() => expr` where a `void Function()` was expected, at least not with a non-`void` type, so you had to write `() { ProfileData.profileChanged(); }`, that problem would solve itself.)

**Comment by rrousselGit** [comment]
I assume this should be moved to https://github.com/dart-lang/linter


More on the topic: Maybe the linter could warn when returning a `Function` on a `() => void`.

**Comment by lukehutch** [comment]
Sorry, I said the return type is null, of course I meant void.

@rrousselGit is suggesting to move this to the linter project (sorry, I didn't realize there was a separate project for that), but @lrhn seems to be suggesting an actual language change. Should I move it or not? Is there a way to move an issue without re-filing it?

**Comment by rrousselGit** [comment]
You're talking about making a linter change (cf the title). So I assume moving it is logical.
If we want to discuss about a language feature for this, that could be a separate issue on its own (this time in this repo).

**Comment by lukehutch** [comment]
Well of course I can just change the title :)

I'll create a linter issue -- but @lhrn please weigh in on whether a language restriction (to disallow zero-effect code like this) is also reasonable.

**Comment by lrhn** [comment]
It should be possible to lint this, or warn from the analyzer.

It's an expression with no side-effect used in a void context.
We usually warn if you do
```dart
object.method;
```
and forget to call the method.
That's what this is too.
The `=>` may make it look like the value is used, but with a `void` returning function, it won't be.

**Comment by lukehutch** [comment]
Closing after creating https://github.com/dart-lang/sdk/issues/53537 .
