### ISSUE TITLE
Promote the representation variable of an extension type?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3342]
For quite a while, the [extension type feature specification](https://github.com/dart-lang/language/blob/main/accepted/future-releases/extension-types/feature-specification.md) has claimed, in commentary, that the representation variable can be promoted: It is final, and there is no way it can be overridden.

However, the feature specification did not spell out this rule in normative text, so we'd need to decide clearly on the matter in order to proceed with an implementation.

Moreover, the decision to promote the representation variable of an extension type for code outside the library that declares the extension type is controversial.

I'd recommend that we allow promotions of the representation variable in the same library as the extension type declaration. We may then relax this rule in the future if the language team makes that decision.

In particular, this means that promotion of a name that denotes the representation object is _not_ supported in the case where it is an "inherited" declaration from a different library:

```dart
// Library 'a.dart'.

extension type A(num a) {}

// Library 'b.dart'.
import 'a.dart';

extension type B(num b) implements A {
  void foo() {
    if (b is int) b.isEven; // OK.
    if (a is int) a.isEven; // Error, `num` doesn't have a member named `isEven`.
  }
}
```

**Comment by eernstg** [comment]
The language team decided that extension type representation variables are promoted according to similar (but not the same) rules as instance variables: Only privately named representation variables are promoted (hence also: only in the same library). However, there are no exceptions for private names that occur in other declarations (such declarations can prevent a private class/mixin instance variable from being promotable, but they make no difference for an extension type representation variable). Also, extension type member declarations (representation variables and getters) do not prevent class/mixin instance variables from being promotable.

**Comment by eernstg** [comment]
@sgrekhov, is there anything in co19 tests that needs to be reconsidered because of this, or has it already been handled?

**Comment by sgrekhov** [comment]
We have 
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Private-fields-promotion/not_promotable_A01_t06.dart - tests that extension type getter is not promotable

https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Private-fields-promotion/promotion_A01_t09.dart - tests that extension type representation variable is promotable if all conditions are met

https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Private-fields-promotion/promotion_A04_t07.dart - tests that member, declared in an extension type doesn't prevent promotion of class instance member

Missed tests that check that if representation variable is not private then it's not promotable. Also no tests that check that class/mixin member doesn't prohibit representation variable promotion. Adding these tests now

**Comment by scheglov** [comment]
Was a specification updated to reflect this? I searched inside https://github.com/dart-lang/language/blob/main/accepted/future-releases/extension-types/feature-specification.md, but don't see anything new about promotion.

**Comment by eernstg** [comment]
Thanks, @scheglov, good catch: That still needs to be done!

See https://github.com/dart-lang/language/pull/3411.
