### ISSUE TITLE
Inconsistent behavior with static functions inside extensions while importing with alias

### ISSUE THREAD

**Issue by busslina** [dart-lang/language#3347]
![imagen](https://github.com/dart-lang/sdk/assets/73592852/ba746d39-e9d6-4ff0-9ba4-74e73eb84865)

![imagen](https://github.com/dart-lang/sdk/assets/73592852/b86636a5-aee0-4afe-acac-a4de4ede926d)

```
import 'dart:io';

extension DirectoryExtension on Directory {
  static String toJson(Directory directory) => directory.path;

  static Directory fromJson(String path) => Directory(path);
}

class TestClass {
  static String toJson(Directory directory) => directory.path;

  static Directory fromJson(String path) => Directory(path);
}

----------------------------------------------------

import 'package:xxxx/xxxx' as llib;
import 'package:xxxx/file.extension.dart';
import 'package:xxxx/directory.extension.dart';

[....]

aa() {
  const a = llib.DirectoryExtension.fromJson;
  const b = llib.TestClass.fromJson;
}

bb() {
  const a = DirectoryExtension.fromJson;
  const b = TestClass.fromJson;
}
```

Discussed on Discord:

![267843117-4b86c2c9-481b-4617-9bfa-3c3188e08199](https://github.com/dart-lang/sdk/assets/73592852/c7f011ea-eb80-4284-9faa-e5b08321f996)

![imagen](https://github.com/dart-lang/language/assets/73592852/5cc2c13e-65db-4436-b9cb-420c87bd0265)

https://spec.dart.dev/DartLangSpecDraft.pdf

**Comment by busslina** [comment]
https://github.com/dart-lang/sdk/issues/53522

**Comment by lrhn** [comment]
The SDK issue was correct, this is an implementation bug in the analuzer. Closing this one as the duplicate.

**Comment by eernstg** [comment]
Just checking: There is no need to update the specification: We have a specification of the expression itself [here](https://github.com/dart-lang/language/blob/4d1e9964352f1777a070315230c9f0ca247f0d08/specification/dartLangSpec.tex#L14636), and it does mention that we can denote a static method declared by an extension using an expression of the given form (`llib.DirectoryExtension.fromJson`).
