### ISSUE TITLE
Consider changing shadowing rules for macro generated code

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3348]
Relevant specification section https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md#shadowing-declarations.

tldr; it is currently an error for a macro to generate code which changes how some identifier in the same library would have been resolved.

In talking with @scheglov I think I have been convinced that we should not make that an error, but instead just allow it. Effectively, this is option 2 in the linked section "Re-resolve all identifiers after macros are applied, which may change what they resolve to.", except that is a bit misleading since we shouldn't ever have to re-resolve. And in fact, making it an error forces at least 2 resolves to detect the error.

**Comment by jakemac53** [comment]
cc @munificent @leafpetersen thoughts?

**Comment by jakemac53** [comment]
This also makes macro augmentations libraries behave identically to, and have the same capabilities as, user written augmentations libraries.

**Comment by jakemac53** [comment]
There is an issue here related to annotation evaluation. We currently say this:

```
Because macros are not allowed to generate code that shadows an identifier
in the same library, we know that if an annotation class or any arguments to it
could be resolved, then we can assume that resolution is correct.

This allows us to provide an API for macro authors to attempt to evaluate an
annotation in _any phase_. The API may fail (if it requires more macro
expansion to be done), but that is not expected to be a common situation. In
the case where it does fail, users should typically be able to move some of
their code to a separate library (which they import). Then things from that
library can safely be used in annotations in the current library, and evaluated
by macros.
```

Which would no longer be valid.

**Comment by scheglov** [comment]
Other possible approach is to prevent already observed identifiers to change their meaning. The meaning of "observed" can be either explicit, e.g. whether a macro generator actually asked for resolution of an annotation, or implicit, e.g. whether an identifier was used as a type annotation, that we resolved after the types phase, but then shadowed by declaring a top-level function (the naming convention does not like it, but technically possible). So, these observed identifiers should be re-checked, but not `=> x` body that we initially talked about - nobody saw it, or even could see it, so we accept that the users intention was to use whatever it happens at the end. The key is consistency throughout phases.

**Comment by jakemac53** [comment]
> Other possible approach is to prevent already observed identifiers to change their meaning. The meaning of "observed" can be either explicit, e.g. whether a macro generator actually asked for resolution of an annotation, or implicit, e.g. whether an identifier was used as a type annotation, that we resolved after the types phase, but then shadowed by declaring a top-level function (the naming convention does not like it, but technically possible). So, these observed identifiers should be re-checked, but not `=> x` body that we initially talked about - nobody saw it, or even could see it, so we accept that the users intention was to use whatever it happens at the end. The key is consistency throughout phases.

Anything declared in the declarations phase would not be a valid type annotation, so while we could have resolved something incorrectly earlier, it would never result in valid code (unless we had special rules for the resolution just for macro generated code, which we don't want). It does imply some sort of check in the declarations phase that you didn't shadow a type that was used as a type annotation though.

I do definitely see the appeal of just not allowing "observed" identifiers to change their meaning, I just worry about the cost/complexity of actually enforcing that.

**Comment by rrousselGit** [comment]
I personally really dislike the way shadowing works at the moment.   
Macros or not, I don't like that top-level symbols can take over inherited members. I've inadvertently broke apps before by exporting consts in my packages named `widget`, which clashes with State.widget.


I'd be in favour of changing it _everywhere_, not just for macros. But I assume that's not gonna happen due to being breaking.


So I'm a bit on the fence about having macros behave differently. While I would prefer a different behavior, I don't like the idea of having a  difference just for macros. That increases the learning curve.
