### ISSUE TITLE
Extension type should be able to have assert for the parameter of the constructor

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/language#3354]
AFAIK, currently extension types doesn't have a way to define assertion for their parameter of their constructors.
As a *smart* alternative of `typedef`, assertion seems important.

**Comment by Cat-sushi** [comment]
Ex.
```dart
extension type NaturalNumber(int value): assert(value > 0){}
```

**Comment by lrhn** [comment]
Not planned.

You can write a public constructor with an assert:
```
extension type NaturalNumber._(int value) {
  NaturalNumber(this.value) : assert(value > 0);
}
```
The declaration header is then only used to declare the representation type and representation object name. You can choose to ignore the private constructor it introduces, and nobody else can see it.

If you really don't want the private constructor to exist (which doesn't change anything, other people can still write `-1 as NaturalNumber`), that's issue #3343.
