### ISSUE TITLE
May I know why I can't get a normal conversation?

### ISSUE THREAD

**Issue by hamsbrar** [dart-lang/language#3361]
A label from below is required when opening an issue.

- bug: "I found a bug in the spec or documentation."
- feature: "I have an idea for a new language feature."
- request: "I have a problem which is impossible or inconvenient to solve in Dart."

Using any of them for a normal conversation is misleading to others.

Maybe there's a way to open an issue without label that I can't find or maybe you don't want such discussions here.

**Comment by lrhn** [comment]
This is an issue tracker for the Dart language team, for tracking potential and planned language changes.

Not sure what kind of general discussion you want, but the labels are there to guide people towards identifying what they're asking for in relation to language changes.
General questions and discussions are mostly likely better done in the dart-lang/sdk repository.

If you do think that something doesn't fit into the "problem not solved by current language", "solution to such a problem" or "bug in specification" categories, but should still appear in this repository, you can choose one of the categories and remove the pre-filled label.

**Comment by lrhn** [comment]
> I was hoping to learn more by discussing potential solutions to problems that exists in Dart

If it's about finding solutions to programming problems using the existing language, then stack-overflow with the \#dart tag, the dart-misc mailing list/group, or the dart-lang/sdk repo issue tracker would be the best places, in order of preference.

If it's discovered that the current language doesn't and cannot solve a problem, and it cannot be solved by a library or package, then it makes sense to file a "request" issue in the language repo to ask for language support.
A "problem" can be that something is too cumbersome or verbose, not just that it's impossible.

If it's about problems or short-comings of the language itself, the a "request" issue in this repo is probably the correct approach.

(I did think you could remove labels, but that's probably just for people who have edit rights to the repo in general.)
