### ISSUE TITLE
Clarify that multiple augmentations of the same declaration are allowed within one library

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3367]
We do want to allow both:

```dart
augment class A {}
augment class A {}
```

And:

```dart
augment class A {
  augment void foo() {
    augment super();
    print(1);
  }

  augment void foo() {
    augment super();
    print(2);
  }
}
```

This mostly allows macro results to easily compose together in one augmentation library.

The spec is mostly ambiguous today around this topic so we should clarify it, and specify ordering where needed as well.

**Comment by lrhn** [comment]
I'd consider (read: I am considering) not linking augmentation to specific augmentation libraries/files, and just allow any file in a library to declare an augmentation:
```dart
class A {
  int get foo => 42;
}
augment class A {
  augment in get foo {
    log("reading foo");
    return augment super.foo;
  }
  int get bar => 37;
}
```
in the same file, or in different `part` files.

(And allow `part` files to have imports, exports, and heck, parts too.)

Then an augment library is just a part file containing augmentations, just as if the same augmentations had been in the parent file (in some consistent order).


I'm a little uncomfortable allowing two `augment void foo()`s in the same scope, but if we can allow two `augment void topLevelFunction() ...` in the top-level scope, it shouldn't be a problem to do the same in a class scope. They're applied in source order, and everything is well-defined.

**Comment by jakemac53** [comment]
I personally prefer a bit more of a clean break between augmentations libraries and part files. Having their own separate scope for imports is imo a primary benefit (and it would be very weird imo to have access to imports of the thing you are importing plus your own imports?).

Would we have a lint that if an import is only used in a part that it should appear only in that part and not the root library?

I do also believe its a bit weird to have both part files and augmentation libraries, but I would also like to see part files just be removed entirely, and we should be able to `dart fix` them away eventually? But maybe that is just a dream :).

**Comment by lrhn** [comment]
> (and it would be very weird imo to have access to imports of the thing you are importing plus your own imports?)

Not at all. We'd have to define the scoping, but I'm fairly sure I have a consistent and meaningful specification of that.

We can lint about an import having a bigger scope than necessary, but I wouldn't bother. It's not wrong. It's not even dangerous. It just means that the higher level file knows about the dependency.

If augmentation files can do imports (exports? parts?), I'd be happy to use them instead of `part` files, even if they contain no augments. If they cannot do all the work of part files, then I wouldn't remove part files.
But I'd much rather have *one thing* which subsumes both.

**Comment by jakemac53** [comment]
> Not at all. We'd have to define the scoping, but I'm fairly sure I have a consistent and meaningful specification of that.

The problem is it leads to another style choice which will just cause unnecessary churn in reviews etc. Almost certainly a lint will be written to prefer one over the other. It has a serious code smell in general to me, even though it can be well specified, that doesn't make it _good_.

It would also potentially be problematic for macros. Generating valid code is hard when you can't enforce that all your imports are prefixed.

> If augmentation files can do imports (exports? parts?), I'd be happy to use them instead of `part` files, even if they contain no augments. If they cannot do all the work of part files, then I wouldn't remove part files.

They can do everything parts can do (define new declarations and access private declarations).

> But I'd much rather have _one thing_ which subsumes both.

+1, I could imagine a `dart fix` to convert a part to an augmentation even. It should be straightforward.

**Comment by jakemac53** [comment]
> I'm a little uncomfortable allowing two `augment void foo()`s in the same scope, but if we can allow two `augment void topLevelFunction() ...` in the top-level scope, it shouldn't be a problem to do the same in a class scope. They're applied in source order, and everything is well-defined.

It is a bit of a weird thing to do, but it makes a lot of sense for macros, or regular code generators, as their outputs can easily be composed together into a single file.

**Comment by jakemac53** [comment]
Fwiw I double checked and augmentations are allowed to have exports:

```... an augmentation library may contain anything a regular Dart library
can contain: imports, exports, classes, functions, constants, etc.
```

But not parts:

```
It is a compile-time error if:

*   An augmentation library contains any `part` directives.
```

**Comment by jakemac53** [comment]
> If it can contain augment imports, then it can replace parts. At which point, we should just name _that_ `part`.
> Drop the "augmentation", it's cleaner.

I just don't see how we get to that point in any sort of reasonable timeframe (ie: before Dart 4.0?)? Do you think we can break existing parts?

**Comment by jakemac53** [comment]
Or, do we language version it so that parts have different behavior at some point?

**Comment by lrhn** [comment]
What would need to break? If we change `part` to allow it to have `import`, `export` and `part` declarations, then existing `part` files shouldstill work, they just don't use the new features.

We'll have to make sure the semantics are compatible with what we have today, but that shouldn't be hard. It'd be more surprising if they don't.

The extra features would be language version guarded, but it's a non-breaking change, so that's just gating access to it. And all part files must have the same language version as the main library file, so there can't be version skew.

**Comment by jakemac53** [comment]
The breaking part is implicitly having the same import scope. Every augmentations library has its own separate import scope.

**Comment by jakemac53** [comment]
I filed https://github.com/dart-lang/language/issues/3371 to talk more specifically about the `part` vs `import augment` syntax.
