### ISSUE TITLE
[extension types] Should we allow a non-covariant occurrence of a type parameter in a superinterface?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3377]
Consider the following program:

```dart
class A<X> {
  final X x;
  A(this.x);
}

class B<Y> extends A<void Function(Y)> {
  B(super.x);
}

void main() {
  B<num> b = B<int>((x) {}); // Covariant upcast.
  A<void Function(num)> a = b; // Nominal upcast. Soundness violation!
}
```

This program has a compile-time error at the specification of the superinterface `A<void Function(Y)>`, because it is an error to use a type parameter like `Y` in a position of a superinterface type which isn't covariant (and `Y` occurs in a contravariant position in this case).

The code in `main` illustrates why we have this compile-time error: If we hadn't had it then we could write and run the above example, and the code in `main` would perform two assignments which are both upcasts (so no type checks are performed at run time), and we would end up in a situation where a variable of type `A<void Function(num)>` refers to an object whose run-time type is `B<int>`, which is not a subtype of `A<void Function(num)>`. This means that we have violated the soundness of the heap.

With respect to extension types, I had originally assumed that we would apply the same rule, for the same reasons.

However, it is my understanding that the constraints on extension types (in particular, the fact that it is a compile-time error for a type variable of the extension type to occur in a non-covariant position in the representation type; and it is a compile-time error unless the representation type is a subtype of the representation type of an extension type superinterface) seem to ensure that it will not cause any soundness issues if we allow this.

Here is an example where an extension type has a non-extension type as a superinterface:

```dart
class A<X> {
  final X x;
  A(this.x);
}

extension type B<Y extends num>(A<void Function(num)> it)
    implements A<void Function(Y)> {}
```

In this example, we can't directly do exactly the same things as in the class based example. In particular, we cannot use `A<void Function(Y)>` as the representation type, because it is an error for `Y` to occur in a non-covariant position in the representation type. However, if we change the representation type such that it doesn't depend on `Y` then it must use the bound of `Y`, yielding `A<void Function(num)>` (or it must use an even more general representation type), in order to avoid another compile-time error: The representation type of `B` must be a subtype of the implemented type `A<void Function(Y)>`.

A similar example where `B` has a superinterface which is another extension type (so we have `extension type A<X> ...` rather than `class A<X> ...`) has a similar constraint involving the representation type of the superinterface.

As far as I can see, we _do_ avoid the soundness issue in these cases, and probably in general. The reason for this is that we have very little freedom to choose a representation type for `B` and an implemented type for `A` (if `A` is a class) or a representation type for `A` (if `A` is another extension type).

In spite of this, I'd recommend that we _do_ make it an error for a type parameter of an extension type to occur in a non-covariant position of a superinterface. This means that we simply broaden the applicability of the rule that we already have for classes and mixins etc. such that it is also applicable to extension types.

We can always relax this restriction if we are convinced that it is indeed sound to eliminate the error for extension types, and if we encounter some use cases which are really compelling.

@dart-lang/language-team, WDYT?

**Comment by lrhn** [comment]
It probably is sound, because every extension type is sound for a value which satisfies the representation type. If the type variable we're up- or down-casting does not occur in the representation type, it can't be wrong.

So up-casting the extension type means down-casting the contravariant interface it implements, but that can only work for a representation value which is a supertype of both, and of all possible interfaces implemented by that extension type.

I'm more worried about done algorithm getting confused by the extension type itself, and assume that if is a assignable to S, surely a subtype of T also is.

**Comment by eernstg** [comment]
Done in https://github.com/dart-lang/language/pull/3412.
