### ISSUE TITLE
Disallow extension typed declarations with bottom as representation type - from implementing interface types.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#3383]
## Proposal

It's a compile time error of an extension type declaration has a declared representation type which is a bottom type, and the extension type declaration directly or transitively declares a non-extension type supertype.

An extension type decoration directly declares a non-extension type supertype if its declaration has an `implements` clause with an entry which denotes a non-extension type.

It transitively declares a non-extension type supertype if it has an `implements` clause with an entry which denotes an extension type whose declaration directly or transitively declares a non-extension type supertype.

## Background
As currently specified, you can declare:
```dart
extension type Madness(Never _) implements int, double {
  Madness operator -() => this;  // Only a few self-typed nullary members conflict.
  Madness abs() => this;
  Madness get sign => this;
}
```
That's a type which implements `int` *and* `double`. It's not particularly useful, but it's a complication that the specification has to account for. Simply because it *can* exist.
This one, in particular, complicates the special-case type inference for number operators.

Another complicating factor for those rules would be:
```dart
extension type Silly(Never _) implements int, Other {
}
abstract interface class Other {
  Never operator+(Object? a);
}
```
which implements `int` and has a combined interface for `operator+` of `Never Function(Object?)`. (An interface which is trivially satisfied by `Never`.)

There might be more places where such types can confuse the current specification, perhaps a type implementing two different `enum`s.

I propose we either:
* Disallow a representation type _declaration_ which is a bottom type, or
* Disallow a an extension type with a representation type _declaration_ which is a bottom type, from implementing interface types.

It won't prevent the representation type from actually being `Never`. The representation type declaration can be a type variable with a non-bottom bound, which is bound to `Never`, but that won't allow declaring `implements` clauses below the bound.

It just means that an *actual*, compile-time botton representation type either is not allowed (the type is uninstantiable anyway), or it's allowed, but like a representation type of `Null` or `int?`, there are no interfaces that it can implement.

Maybe the rule should be that if the representation type is not an "interface type", you cannot implement interface types, using the same categorization as for which types you can implement. You'll still get `Object` for free if the representation type is non-nullable.

So, mostly out of an abundance of caution, I think we should disallow this, most likely useless, complication, like we disallowed actually implementing `Null`, `Never`, `Function` and `Record` (because the spec may make assumptions about any non-bottom subtype of `Record` actually being a record type.)

**Comment by eernstg** [comment]
> So, mostly out of an abundance of caution, I think we should disallow this, most likely useless, complication

I tend to agree, but it would be nice if we could find a good example demonstrating that there is a problem. We might also just take a minute to consider one use case:

```dart
extension type DoubleAndInt(Never _) implements double, int {
  static String msg(String operation) =>
      "Don't call $operation on an expression of type `DoubleAndInt`.";
  void operator -() => throw msg('unary minus');
  void get abs => throw msg('abs');
  void get sign => throw msg('sign');
}

var b = true;

void main() {
  void Function([DoubleAndInt]) unionTypedFunction;

  unionTypedFunction = ([double d = 3.14]) {}; // OK.
  unionTypedFunction = ([int i = 42]) {}; // OK.
  unionTypedFunction = ([String s = ''] {}); // Compile-time error.
}
```

**Comment by lrhn** [comment]
It might be that the only place such a subtype actually matters is the specification of the special-case type inference for number operations.
There, it does matter, and the spec must be written to account for it, where today it just needs to say "non-bottom subtype of `int`", and then it knows that any instance member has the type it has in `int`.

But we can't know that there aren't any other issues without checking everywhere.

At least it'll only be static types of code that won't ever run, no object can be created with that type.
That's also why I think it's not a big loss to disallow it.

Having taken a minute, the example allows a variable to store one of two incompatible function types, but not any other function type. Or also provides no easy to call those functions without casting them to something else.
And good luck if an argument function has is parameter type inferred, so it's not something that should be in a public API.
I see no real benefit.

It's clever, but not particularly useful.
It's something you can do with interfaces too, it's only `int` and `double` being `final` which ruins that. I'd be fine with ruining it for extension types too.

**Comment by lrhn** [comment]
If we don't have union types in general, then I don't consider it a _goal_ to provide a way to introduce limited union types that only work for function parameter types (because they're relying on a common subtype in contravariant position, and the ability to create common subtypes).

Either provide union types, or do not provide union types. Or deliberately provide limited union types.
Having a feature which *can* be used, hackishly, to provide some limited union types, even if it was not intended for that, and which has some sharp edges that requires using it with care, is ... well, it's what hacks are. Sometimes they work for what you want, sometimes they don't, but it's still a hack, not a feature.

We allow this feature today, for all non-final types (if at most one is `base` and not `mixin`). You can do:
```dart
abstract interface class ListOrSet<T> implements List<T>, Set<T> {
  /// maybe fix some conflicts.
}
typedef ListOrSetFunctions<R, T> = R Function(ListOrSet<T>);

R doStuff<R, T>(Iterable<T> it, ListOrSetFunction<R, T> act) {
  if (act is R Function(Set<T>)) {
    return act(it is Set<T> ? it : it.toSet());
  } else if (act is R Function(List<T>)) {
    return act(it is List<T> ? it : it.toList());
  } else {
    throw ArgumentError("Can't help you, mate");
  }
}
```
That should work.

And it breaks if you do `doSomething([1, 2], (list) => list.length)`, because the `list` parameter is inferred as `ListOrSet<int>` (at best).

I don't see anyone using it, and I don't expect to see anyone using extension type subtypes of final interfaces either.

And not providing that functionality isn't something I'd worry about either. It's not a goal to provide it.

**Comment by eernstg** [comment]
OK, so let's specify that it is an error for an extension type to have a representation type which is a bottom type.

**Comment by eernstg** [comment]
How about this?:

```dart
extension type E<X extends Never>(X x) implements int, double {}
```

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/pull/3393.

@dart-lang/language-team, WDYT?

**Comment by eernstg** [comment]
Closing: The language team accepted this proposal at the meeting yesterday; done in https://github.com/dart-lang/language/pull/3393.
