### ISSUE TITLE
static abstract members in interfaces

### ISSUE THREAD

**Issue by insinfo** [dart-lang/language#3388]
Consider adding static abstract members to interfaces, this will help in various use cases like serialization, it would be similar to what is available in C#

An interface is allowed to specify abstract static members that implementing classes are then required to provide an explicit or implicit implementation of. 

which would allow the jsonEncode and jsonDecode functions to work for any custom object that implements the MapSerializable interface

```dart
abstract interface class MapSerializable<T> {
  Map<String, dynamic> toMap();
  static T fromMap(Map<String, dynamic> map);
}

class Person implements MapSerializable<Person>{
  String name;
  Person(this.name);
  
  @override
  Map<String, dynamic> toMap() {
    return {'name':name};
  }

  @override
  static Person fromMap(Map<String, dynamic> map){
    return Person(map['name']);
  }
}

void main(List<String> args) {
  var p = Person('John Doe');
  print(jsonEncode(p));
  //{"name":"John Doe"}
  Person person = jsonDecode<Person>('{"name":"John Doe"}');
  print(person.name);
  //'John Doe'
}

```

https://www.php.net/manual/en/class.jsonserializable.php
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/static-abstracts-in-interfaces
https://jeremybytes.blogspot.com/2019/12/c-8-interfaces-static-members.html

**Comment by eernstg** [comment]
@insinfo, this may very well be the same request as the one in https://github.com/dart-lang/language/issues/356. I'll close this issue as a duplicate. If you think this is a substantially different proposal then please clarify how, and we can reopen the issue. Also, you may wish to add your comment to #356 and/or vote for that issue in any case.

**Comment by insinfo** [comment]
@eernstg 

Thank you, I hadn't found that there was already a proposal like this
