### ISSUE TITLE
Map Patterns Deconstructing a Non-Existent Key Throws an Exception

### ISSUE THREAD

**Issue by aboutlan** [dart-lang/language#3389]
Dart's Map Patterns Deconstructing a Non-Existent Key throws a "Pattern matching error", but I want the variable to be null, Does Dart's syntax support this? How can I do that?

Practical scenario: When I'm Deconstructing Json, I'm not sure if a key exists in the Json or not, and if it doesn't, it will cause the problem.
```dart
void main() {
  final userInfo = {
    "name": "Jack",
    "age": 18
  };
  // Here throws a Pattern matching error, but my expectation is that the gender variable is null, so how do I do this?
  final {"gender": gender as String?} = userInfo; 
  print(gender); 
}

**Comment by julemand101** [comment]
Maybe related to: https://github.com/dart-lang/language/issues/2496

**Comment by lrhn** [comment]
Does seem like the same issue as #2496.
The pattern syntax currently doesn't support that.
