### ISSUE TITLE
Github action gets "This requires the 'macros' feature..."

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3390]
There may be something like a version conflict in the current contents of working/macros/example: Github actions fail with errors like this one:

```
  error - working/macros/example/lib/auto_dispose.dart:13:1 - This requires the 'macros' language feature to be enabled. Try updating your pubspec.yaml to set the minimum SDK constraint to 3.3.0 or higher, and running 'pub get'. - experiment_not_enabled
```

Here is an example run: https://github.com/dart-lang/language/actions/runs/6454306265/job/17519554972. I've seen the issue with a PR where the language specification is updated, so presumably it could occur for all language repo PRs.

@jakemac53, WDYT?

**Comment by jakemac53** [comment]
I think this is because the SDK version fetched is now a `3.3` language version. The examples just need to be updated to that.

**Comment by eernstg** [comment]
Thx!
