### ISSUE TITLE
Change `augment super` to `augmented` (or similar)

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3403]
Currently, `augment super` looks very weird, and none of  us are happy with it. It feels like you need to wrap it in parenthesis whenever you use it, even though you don't.

The current preferred option is `augmented`, and I will send an update to that soon, but we can consider other proposals as well if you have them.

cc @johnniwinther @scheglov @munificent

**Comment by lrhn** [comment]
I commented on the PR, but to summarize, I recommend `augment.super`.
It fits what I want to do with mixin constructors and targeted mixin application super calls.
And it doesn't need to introduce any further keywords than `augment`, which is probably already a built-in identifier.

**Comment by jakemac53** [comment]
To me, `augment.super` looks like there is some identifier `augment`, with a getter `super`, which is not the case, and especially weird that `augment` on its own would not refer to anything on its own. A single identifier which refers to the augmented member more intuitive imo.

**Comment by jakemac53** [comment]
We discussed this in the language meeting today and agreed upon `augmented`. This is different enough from `super` in the semantics (you are actually replacing that function, it no longer exists in the super chain once it is augmented). The only way to access it is through a reference to `augmented` in the augmenting member.

**Comment by jakemac53** [comment]
Note that the analyzer does have some members called `augmented` currently. Technically this would not have to change, but it might be desirable to change them. I don't see other members with that name internally at least though.
