### ISSUE TITLE
A discrepant problem about 'Restricting the parameterized type'

### ISSUE THREAD

**Issue by Buerkut** [dart-lang/language#3424]
In the language introduction about Generics:
[https://dart.dev/language/generics#restricting-the-parameterized-type](url)

> Restricting the parameterized type
> When implementing a generic type, you might want to limit the types that can be provided as arguments, so that the argument must be a subtype of a particular type. You can do this using extends.
> 
> A common use case is ensuring that a type is non-nullable by making it a subtype of Object (instead of the default, [Object?](https://dart.dev/null-safety/understanding-null-safety#top-and-bottom)).
> You can use extends with other types besides Object. Here’s an example of extending SomeBaseClass, so that members of SomeBaseClass can be called on objects of type T:

```
class Foo<T extends SomeBaseClass> {
  // Implementation goes here...
  String toString() => "Instance of 'Foo<$T>'";
}

class Extender extends SomeBaseClass {...}
```
It tell us to use the 'extends' keyword. But when I wrote the following code:
`class Bucket extends Comparable<Bucket>{...}`
there is an error:

> The class 'Comparable' can't be extended outside of its library because it's an interface class.

So I modified it :
`class Bucket implements Comparable<Bucket>{...} // It's OK! I can only use 'implements' here.`

Then I defined a function as follows:
`void quickSort<E extends Comparable<E>>(List<E> a){...} // Note: only 'extends' can be used here.`
and test it:
```
void main() {
  var buckets = <Bucket>[...]; // implements the class Comparable
  quickSort(buckets); // Its generic parameterized type is restricted to subtypes of Comparable by 'extends' keyword.
  ...
}
```
There is no bug or error in above code. It works! But it seems having a discrepant problem about 'extends' and 'implement' keyword in use.Do we need to allow to use both 'implement' and 'extends' keywords when Restricting the parameterized type? e.g.
`class Foo<T extends SomeBaseClass>{...}`
or 
`class Foo<T implements SomeBaseClass>{...}`

**Comment by lrhn** [comment]
Correct.

The `extends` keyword has two uses in the Dart language:
- to declare the superclass of a `class` declaration.
- to declare the bound of a type variable.

Other than both being about subtyping, the two are unrelated, separate constructs which happen to reuse the same keyword.

And it reuses the keyword because Java did the same thing, and Dart was, originally, designed to be unsurprising to Java developers.

**Comment by munificent** [comment]
Closing this. I agree the use of `extends` is somewhat confusing, but it's probably not worth changing it (and I don't know what we'd change it to).

**Comment by Buerkut** [comment]
> Closing this. I agree the use of `extends` is somewhat confusing, but it's probably not worth changing it (and I don't know what we'd change it to).

No problem. I agree. I was just to mention it.
