### ISSUE TITLE
Mutations of ClassDeclaration

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#3429]
Returning to the question of "syntactic" vs "semantic" view of the macro application targets.

How does it work when we add for example interfaces to the class?

When running `AddInterfaceA` below we create and send `ClassDeclaration` for `X`.
We remember this instance for the `X` node, and also its element.
`ClassDeclaration` has `identifier` which we also remember to be associated with the `X` element.

So, when `AddClassB` (misnomer) runs on `X`, we return the same instance `ClassDeclaration`.
But it does not have the added interface.
So, we generate just `foo` instance of `fooA`.

If we stop caching `ClassDeclaration` and its `identifier`, we lose merging.
```dart
library augment 'test.dart';

import 'package:test/a.dart' as prefix0;

augment class X implements prefix0.A {
}
augment class X {
  void foo() {}
}
```

If we cache, it still does not work, no `fooA` because "syntactic" means syntactic, and we return only `interfaces` that were in the `X` itself, without the augmentation that adds `A`. Or should we return it with previous augmentations applied?

But do we re-create `ClassDeclaration` or not?

@jakemac53 

<details>
  <summary>Code is here</summary>

```dart
  solo_test_X() async {
    newFile('$testPackageLibPath/a.dart', r'''
class A {}
class B {}
''');

    newFile('$testPackageLibPath/b.dart', r'''
import 'dart:async';
import 'package:_fe_analyzer_shared/src/macros/api.dart';
import 'a.dart';

macro class AddInterfaceA implements ClassTypesMacro {
  const AddInterfaceA();

  FutureOr<void> buildTypesForClass(clazz, builder) async {
    builder.appendInterfaces([
      NamedTypeAnnotationCode(
        name: await builder.resolveIdentifier(
          Uri.parse('package:test/a.dart'),
          'A',
        ),
      ),
    ]);
  }
}

macro class AddClassB implements ClassDeclarationsMacro {
  const AddClassB();

  buildDeclarationsForClass(clazz, builder) async {
    final name = 'foo' + clazz.interfaces.map((e) => e.identifier.name).join();
print('name: $name');
    builder.declareInType(
      DeclarationCode.fromString('  void $name() {}'),
    );
  }
}
''');

    var library = await buildLibrary(r'''
import 'b.dart';

@AddInterfaceA()
@AddClassB()
class X {}
''');

    configuration
      ..withConstructors = false
      ..withMetadata = false
      ..withReferences = true;
    checkElementText(library, r'''
''');
  }
```  

</details>

Ignore for now the fact that the ordering is incorrect, I have not worked it yet in the analyzer.

**Comment by jakemac53** [comment]
Any augmentations performed by a macro are intended to be visible to macros that run later, even in the same phase. The "syntactic" view is intended to be a "merged" view - so it would include any augmentations (such as new interfaces).

Altering an existing ClassDeclaration will not work because we cache instances by ID (they are assumed to be immutable).

So, you would need to create a new ClassDeclaration whenever a class is altered by a macro in a way that would be visible through that API.

In terms of the merging, the code for creating augmentation libraries probably needs to be updated so that it can handle this.

**Comment by scheglov** [comment]
OK, thank you.
Reusing the identifier, and re-creating `ClassDeclaration` works.
