### ISSUE TITLE
Introspect members of other types in the declarations phase

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/language#3442]
`built_value` is one example of when this is needed, as it creates a new class with fields corresponding to, but not identical to, the macro target.

```
@BuiltValue()
class Foo {
  final int x;
}
```

-->

```
class FooBuilder {
  int? x;
}
```

This is problematic because the declaration phase can add as well as introspect declarations. One possible approach would be to make introspecting another type's members wait until the declaration phase of all macros have finished for that type.

**Comment by jakemac53** [comment]
cc @scheglov note that we could replace the somewhat weird rule about running macros on supertypes first with the rule that introspecting on a type (other than the current type) in the declarations phase waits for all the macros annotating that type to complete (in phase 2).

We would have to handle cycles and throw some sort of error, but it would be strictly more powerful than what we have today, even if certain things still weren't possible.

**Comment by scheglov** [comment]
@davidmorgan Could you elaborate? I don't see what is restricting in the given example. Aside from the fact that `@BuiltValue` does not look complete, missing `()`, there are no other macros, so it can generate the resulting code.

**Comment by davidmorgan** [comment]
@scheglov

Yes, it should have been `BuiltValue()`, thanks, fixed.

To generate the fields of `FooBuilder` we need to know the fields of `Foo`, but we don't get that information in the first (types) phase, when we add the `FooBuilder` type itself. We get it in the second (declarations) phase.

In the declarations phase only a macro running on `FooBuilder` can add fields to `FooBuilder`, but now we don't have access to `Foo` declarations so we don't know what fields to add.

**Comment by jakemac53** [comment]
@davidmorgan would you be interested in taking a shot at updating the spec to support this?

Specifically, this would mean:

- Removing the special case ordering rule [here](https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md#application-order) (the one specifying order for superclasses, mixins, and interfaces).
  - Also probably tweaking the last paragraph of that section since it wouldn't quite be accurate any more. 
- Updating the section on the [declarations phase](https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md#phase-2-declarations) to allow introspecting on any type instead of only superclasses.
  - Specify that instead when introspecting on a type, you won't get a response until macros on that type are done.
    - We need to be very explicit about what we mean here - note that _library_ macros that run in the declarations phase can also add declarations to types, but we probably can't want to wait for all of those to run too, because it would guarantee a cycle.
    - Can a macro running on a member declaration introspect on its declaring type? If so, what are the rules here?
  - Specify that if this creates a cyclic dependency an error is thrown (and ideally the type of error). Can macros catch this error and try and handle it?

**Comment by davidmorgan** [comment]
@jakemac53 Sure, let's see how far I get :) thanks.

**Comment by davidmorgan** [comment]
@jakemac53 I thought about it some :) and think it's maybe worth some more discussion before making a concrete change.

This feels like a big step away from the current "phases" structure: pretty much we turn phase 2 into a graph.

While pondering that, I realized/remembered that there is an argument that this doesn't go far enough. I believe `freezed` needs to introspect types during Phase 1--it generates a type corresponding to each field, for its [deep copy](https://pub.dev/packages/freezed#going-further-deep-copy) feature. (I asked on Discord to check).

My point is that if we go down this path then it may end with pushing (some) introspection all the way back to Phase 1, which would I guess involve turning phases 1-2 both into a graph. So now seems a good time to take a step back and ask just how much we are willing to complicate things here :) and what we should support / not support in the end.

What do you think, please?

**Comment by jakemac53** [comment]
> This feels like a big step away from the current "phases" structure

There definitely is a reason it currently doesn't work this way, the current rules are simpler and rely purely on known macro ordering constraints, and then it restricts features such that all the available APIs can give deterministic answers.

I do think that is compelling, but I also think the use case you presented is compelling, and the mockito use case is also compelling (although it could be solved by just allowing introspection on types from other library cycles which is probably an easier solution).

Phase 2 has always been a very tricky phase though, because we allow both introspection of members as well as emitting members within the same phase. So even though we can give deterministic answers they may be incomplete, which has always bothered me. I just simply don't have any better proposal, and I think that most of the time it won't actually matter. But I would love to hear your thoughts here.

> I believe `freezed` needs to introspect types during Phase 1--it generates a type corresponding to each field, for its [deep copy](https://pub.dev/packages/freezed#going-further-deep-copy) feature. (I asked on Discord to check).

We could allow introspecting on the members of only the current type (the one a macro is running on), in Phase 1. The main thing is that any members added in Phase 2 would not be visible.

That would also partially solve the mockito `GenerateNiceMocks` use case, although only one level deep.

> So now seems a good time to take a step back and ask just how much we are willing to complicate things here :) and what we should support / not support in the end.

We definitely don't have to support everything. I have often found in the past that when I encounter situations where an existing builder doesn't translate directly to a macro, you can still make a roughly equivalent macro, but  you may have to rethink the whole API to do so.

One interesting aspect of the built value case in particular is that the original macro is actually annotating the class you want to introspect on. So it feels like maybe there is a different solution for that kind of use case that could work, without overcomplicating things.

At the same time though, I do actually like the idea of just generally opening up introspection, and only throwing if we end up with a cycle.

**Comment by davidmorgan** [comment]
Thanks Jake!

It turns out I was wrong about the `freezed` case. It's true there are cases when it wants there to be a generated type corresponding to the type of a field. _But_, it's always the case that this field type is itself a `freezed`: the necessary codegen already ran in the `freezed` invocation for that other type, and the _current_ `freezed` invocation just assumes that it's available.

Concrete example: freezed class `Foo` has field of type `Bar`; `Bar` is also a `freezed` class; so `Foo` can assume that `$BarHelper` has already been generated.

I would like to dig into the mockito use case, I've been meaning to do that anyway, I will start a thread.

Digging more into this change as currently designed :) ...

Re: library macro applications that add declarations to types, let me see if I understood that correctly:

Library-level applications run last ("Macros are applied to inner declarations before outer ones."), so if a type-level macro asks for introspection on declarations it will just always not see declarations from library level macros.

How does introspection into declarations work for library-level macros? You said it's deterministic but I don't see how that works today if there are multiple library-level macros adding and introspecting declarations?

The doc for `DeclarationPhaseIntrospector.typeDeclarationOf` says it only returns `IntrospectableType` if the type is related to the type the macro annotated--does that mean never if called from a `LibraryDeclarationMacro` --> library macros can't introspect methods of types in the library anyway?

Thanks :)

**Comment by jakemac53** [comment]
> Library-level applications run last ("Macros are applied to inner declarations before outer ones."), so if a type-level macro asks for introspection on declarations it will just always not see declarations from library level macros.

Correct, if it asks this in the declarations phase.

> How does introspection into declarations work for library-level macros? You said it's deterministic but I don't see how that works today if there are multiple library-level macros adding and introspecting declarations?

If there are multiple macros on the same declaration (or library directive), they run in reverse source order (inside-out). They do not run in parallel (in the declarations phase). Library level macros always annotate a library directive so the order is well defined.... if you ignore library cycles (see next comment).

> The doc for `DeclarationPhaseIntrospector.typeDeclarationOf` says it only returns `IntrospectableType` if the type is related to the type the macro annotated--does that mean never if called from a `LibraryDeclarationMacro` --> library macros can't introspect methods of types in the library anyway?

This section likely needs an update for library level macros (they were only somewhat recently added).

I would love to say that for library level macros they get an `IntrospectableType` for everything, but it occurs to me that in the case of library cycles the ordering is not well defined between the libraries in the cycle.

We could however safely say that library level macros can introspect on any type defined in that library, and all super types of those types, even in the case of cycles.

But, this is another case where I would probably rather change how this works entirely, and remove these weird special cases, and in fact the `IntrospectableType` interface entirely, and instead rely on lazy cycle detection.

**Comment by yanok** [comment]
> We could allow introspecting on the members of only the current type (the one a macro is running on), in Phase 1. The main thing is that any members added in Phase 2 would not be visible.

Does that include inherited members? If I do something like

```dart
@Mock()
class MockA implements A {}
```

Will I get members of `A`?

> That would also partially solve the mockito GenerateNiceMocks use case, although only one level deep.

Or do you mean "one level of inheritance chain" here and I'll only get an empty set of members of `MockA`? And if not, what do you mean by "one level deep"?

**Comment by jakemac53** [comment]
> Does that include inherited members? If I do something like

No, it would not include inherited members

**Comment by davidmorgan** [comment]
@jakemac53 what is the recommended way to share a work-in-progress PR please? I figured I'd go ahead and create _something_ at least to help move things forward :)

https://github.com/dart-lang/language/commit/1b43d3cac669f00189adc32c3da3388f3b311c00

Here is one idea for how to proceed: we could start with "cycles are an error" then provide ways to deterministically break cycles in cases that turn out to be important.

For example we could say that if `B extends A` then we break the cycle by returning incomplete results for B so that A can finish first, much like the current "apply to super classes first" rule.

Other ideas:

 - maybe we allow a macro to say "I'm done with declarations that other macros in this phase should see" to break cycles
 -  it seems like in the limit case it's going to come down to what the macro is for, which we can't possibly know; so perhaps it just needs to be configurable ... e.g. a macro can say "I want to run before this other specific macro", "I want to run after this other specific macro" and if there are enough hints to break cycles the compile succeeds, this would allow widely used macros to settle their application order "by consensus" in cases that matter

My intuition is that cases that matter are going to be rare anyway.

Thanks :)

**Comment by jakemac53** [comment]
> @jakemac53 what is the recommended way to share a work-in-progress PR please? I figured I'd go ahead and create _something_ at least to help move things forward :)

After you create a PR, below the reviewers section you can mark it as a draft:

![image](https://github.com/dart-lang/language/assets/984921/03212ed2-8031-426f-b500-502751ad7657)

**Comment by jakemac53** [comment]
> * maybe we allow a macro to say "I'm done with declarations that other macros in this phase should see" to break cycles

We don't really have a notion of "declarations other macros should see" - if we went with this we would have to actually ensure those declarations never showed up in any introspection (at least during that phase) to keep things deterministic.

> * it seems like in the limit case it's going to come down to what the macro is for, which we can't possibly know; so perhaps it just needs to be configurable ... e.g. a macro can say "I want to run before this other specific macro", "I want to run after this other specific macro" and if there are enough hints to break cycles the compile succeeds, this would allow widely used macros to settle their application order "by consensus" in cases that matter

Imo the user needs to be able to specify this ordering for it to work, and not either macro author, since the macros can't know about all other macros they might be used in combination with (and shouldn't). The user might have some idea which should run first though.

I would propose that we release this as a follow-up feature if needed. But we might want to ensure we have some sort of design in place that could be added incrementally.

**Comment by davidmorgan** [comment]
Yes, "I'm done with declarations other macros should see" would take some work to implement--but I think it is a natural concept for macros.

One reason is, macros can want "macro private" code: it exists for the implementation purposes of the macro, for interactions _across_ macro applications. They can't be private because the macro applications can be in unrelated libraries. The `freezed` deep modification helper types are an example, they are referenced from the generated code of other `freezed` macro applications and nowhere else.

We could achieve that by convention, e.g. prefix the name with `$` or annotate `@NotVisibleToMacros()` and other macros are supposed to ignore it.

But when it comes to introspection order dependencies this "macro private" code is potentially a bonus for us because nobody has to wait for it.

Actually, maybe the annotation is really a way to implement it--declarations made after saying "I'm done with visible declarations" could be force-annotated with "@NotVisibleToMacros()`, and then we hide those always from introspection methods.

I think we should avoid pushing ordering to the user whenever we can: in cases where ordering matters there can be an ordering that always works and an ordering that always doesn't, and it depends on the _implementation details_ of each macro--why should each user figure that out? If they have to go and read a doc about the correct ordering for FooMacro used with BarMacro then we might as well put that in code and not a doc. We could think about ways to reduce the combinatorial explosion :) such as letting macros choose a priority class, priority number, etc, that is sufficient to decide ordering in most cases.

Anyway, 100% agreed re: skipping the details for now, how about we just leave a note that there can be rules added in future to allow cycles to be deterministically broken so the applications can succeed?

Thanks.

**Comment by jakemac53** [comment]
> Anyway, 100% agreed re: skipping the details for now, how about we just leave a note that there can be rules added in future to allow cycles to be deterministically broken so the applications can succeed?

SGTM

**Comment by davidmorgan** [comment]
@jakemac53 What's the next step for this one please--e.g. shall I look at updating the API to remove `Introspectable*`? Thanks.

**Comment by jakemac53** [comment]
Sorry been swamped this week, yes I think at this point we can very likely remove the `Introspectable*` APIs, which should clean up a fair bit and also make the compiler teams work easier. Feel free to go ahead with that, thanks!

**Comment by davidmorgan** [comment]
@jakemac53  SG, working on an attempt here:

https://dart-review.googlesource.com/c/sdk/+/339620

It's pretty much a search and replace, without any new checks, dropping the old "only allow introspection for Introspection*" checks, and without introducing waits for macros to complete, so this will be fairly broken even if I can make it pass all existing tests.

Next step would be to add the specified "wait for running macros; detect cycles and throw" behaviour. (...and test coverage).

Do you think it's okay to land this with those as TODOs; and if so, should I go on to look at actually making it correct, and/or maybe hand off the analyzer part to Konstantin? ...

Thanks :)

**Comment by jakemac53** [comment]
> Do you think it's okay to land this with those as TODOs; and if so, should I go on to look at actually making it correct, and/or maybe hand off the analyzer part to Konstantin? ...

Yes, feel free to leave any of that work to the implementation teams (or do it yourself too), it is fine if things are not fully correct right now.

**Comment by jakemac53** [comment]
> Jake, is this a correct example for something that should throw due to a cycle?

Yes, that should throw due to a cycle.

I would actually make it a language test, as opposed to a CFE specific test, as it should be quite general.

**Comment by davidmorgan** [comment]
Language test sounds good--any pointers on getting started with those please?

**Comment by jakemac53** [comment]
They live here https://github.com/dart-lang/sdk/tree/main/tests/language - we will want a new directory called `macros` in here.

You can see my previous attempt to add a few augmentation library tests here https://dart-review.googlesource.com/c/sdk/+/328600 (which I really need to get back to 🤣 ).

**Comment by jakemac53** [comment]
@davidmorgan I think we can close this now right?

**Comment by davidmorgan** [comment]
@jakemac53 Yes indeed, thanks!
