### ISSUE TITLE
Add arguments to ConstructorMetadataAnnotation

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#3443]
An oversight? A feature?
@jakemac53

**Comment by jakemac53** [comment]
Just not added yet :).

It should be a `Code` object.

**Comment by davidmorgan** [comment]
@jakemac53 hmm, looking at the existing `Code` types, I'm not seeing exactly what I need, here is my first guess for expanding them ... what do you think please? :)

New type `InvocationCode` would look a bit like existing `FunctionTypeAnnotationCode`, with `List<ArgumentCode> namedArguments` and `List<ArgumentCode> positionalArguments`.

Then new type `ArgumentCode` would look a bit like existing `ParameterCode` but with just `String? name` and `ExpressionCode argument` .

Then `ConstructorMetadataAnnotation` gains new required field `InvocationCode arguments`.

Thanks :)

**Comment by jakemac53** [comment]
What I was thinking was more along the lines of just adding `namedArguments` and `positionalArguments` as fields directly to `ConstructorMetadataAnnotation`.  Although we could add a new class to encapsulate those, it wouldn't implement `Code`.

Each of the individual arguments would just be `ExpressionCode` instances.

Basically, the goal is to allow you to be able to get the individual values of the arguments, but not the full code for how the argument was passed (or at least, I don't think that is necessary). The goal really is just to expose enough information such that  you could write a `MyMetadata.fromMetadata(ConstructorMetadataAnnotation annotation)` constructor.

**Comment by davidmorgan** [comment]
SGTM, thanks.
