### ISSUE TITLE
Introspection into macro invocations

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/language#3446]
The spec specifically says this isn't supported _yet_ https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md#are-macro-applications-introspectable with the implication that it might be supported at some point ;) I figured I'd file an issue commenting on how it can be useful.

For example for built_value, when a type is used as a field we want to go and check on the type to see it it's another built_value class. If so, it gets a "nested builder" by default, i.e. we leverage the generated builder type.

I figured that I could probably work around this by having the macro generate a marker "implements" clause or actually generating an annotation with the needed information--as far as I can see this should work, it's just extra implementation work and will necessarily pollute the (generated) namespace because generated "implements" or annotations would have to be public.

**Comment by jakemac53** [comment]
That sounds pretty reasonable, I don't think there should be any problem with exposing them, we had simply chosen not to because we didn't have a use case.

We might want to expose an extra flag or something on the metadata annotations APIs to indicate if it is a macro annotation.

**Comment by scheglov** [comment]
And I had to add special code to exclude annotations that are macro applications :-)

Why do we need a flag like this? When I think about introspecting annotations, I imagine that the macro will look for specific annotations, and ignore the rest.

**Comment by jakemac53** [comment]
> And I had to add special code to exclude annotations that are macro applications :-)

sorry!

> Why do we need a flag like this? When I think about introspecting annotations, I imagine that the macro will look for specific annotations, and ignore the rest.

I agree this is likely the case, and they already could (after phase 1) tell whether it is a macro annotation or not once they can navigate to the declaration. So maybe adding the flag would be premature :).
