### ISSUE TITLE
Type arguments are not introspectable

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#3451]
```dart
class A<T> {}

@IntrospectDeclarationsPhaseMacro(
  withDetailsFor: {'A', 'B'},
)
class X extends A<B> {}

@AddMethod('foo')
class B {}
```

The specification says: When applied to a class, enum, or mixin a macro in this phase can introspect on all of the members of that class and its superclasses, but it cannot introspect on the members of other types. For mixins, the on type is considered a superclass and is introspectable. Note that generic type arguments are not introspectable.

Do we want to make `B` in `A<B>` strictly not introspectable?

Or make it either introspectable or not depending on whether `class B {}` is located above or below `class X {}`, or more generally whether it has declarations phase macro applications that are not run yet?

Do we allow introspection of type arguments that are classes from outside the current library cycle? For these we definitely have already run all macros, so there is never ordering ambiguity.

@jakemac53

**Comment by davidmorgan** [comment]
FYI #3442 proposes expanding the scope of introspection in the declarations phase.

**Comment by jakemac53** [comment]
This also came up for mockito, I do think we will want to expand things one way or another.

**Comment by scheglov** [comment]
I agree.
Let's consider this issue as preliminary closed, and move the discussion into https://github.com/dart-lang/language/issues/3442.
