### ISSUE TITLE
[enhanced enums] Need new error about enum values and factory constructors

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3460]
Consider the following program:

```dart
enum E {
  e1,
  e2.foo();

  const E();
  const factory E.foo() = ET.foo;
}

extension type const ET(E it) implements E {
  const ET.foo() : this(E.e1);
}

void main() {
  print(identical(E.e1, E.e2));
}
```

This program is currently (DartPad based on Dart SDK 3.3.0-16.0.dev) accepted by the analyzer, and reported as a confusing error by the CFE

```
Error compiling to JavaScript:
lib/main.dart:3:6:
Error: Couldn't find constructor 'E.foo'.
  e2.foo();
     ^^^
Error: Compilation failed.
```

I would say that we need a new error on enum declarations, something like this:

> It is a compile-time error if _entry_ is a term derived from `<enumEntry>` that occurs as one of the entries of an enum declaration, and the constructor invoked in order to obtain that value is not generative.

The point is that a non-generative constructor (that is, a factory constructor) in an enum declaration may (and indeed always will) return an existing object, which is not the appropriate semantics for an `<enumEntry>`.

Obviously, we should briefly consider this case, too:

```dart
enum E {
  e1.foo();

  const E();
  const factory E.foo() = ET.foo;
}

extension type const ET(E it) implements E {
  const ET.foo() : this(E.e1);
}

void main() {
  print(E.e1);
}
```

This is the loop where the object `E.e1` is defined in terms of itself. The analyzer reports this as a cyclic dependency, which is fine, but it would also be prevented by the new error. It would probably be fine to report the new error and not report the cyclic dependency, because we could say that the cyclic dependency never comes into existence when we refuse to even consider calling the factory constructor in order to obtain `E.e1`.

**Comment by eernstg** [comment]
@dart-lang/language-team, WDYT? We should probably move rather quickly on this one in order to avoid having these surprising situations in real life when extension types are released.

**Comment by eernstg** [comment]
Spec update proposal here: https://github.com/dart-lang/language/pull/3461.

**Comment by lrhn** [comment]
Agree. And good catch.

It's a new issue due to extension types, so we should just make sure it's part of the extension types implementation.

It didn't use to be necessary to say, because it wasn't possible due to the other restrictions on enums.

**Comment by eernstg** [comment]
There will be a couple of new co19 tests; they might well be located in the [`Extension-Types` directory](https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Extension-types) because they will contain an extension type declaration. But they will be new co19 tests no matter where they go, so they would be executed and it will be noticed if they fail.

**Comment by eernstg** [comment]
**The language team decided** that we should have this new error: 

> It is a compile-time error if the constructor which is implicitly invoked by an `<enumEntry>` is not generative.

Note that it is in any case guaranteed to be a constructor declared by the enclosing `enum` declaration, because there is no syntax that will violate that requirement. Similarly, the constructor is guaranteed to be constant because it's again an error to invoke a non-constant constructor.

**Comment by eernstg** [comment]
Done in #3461.
