### ISSUE TITLE
WIP: split contexts

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#3469]
This is a placeholder for a language feature proposal I'm working on. I'll come back and update the description when the proposal is ready.

**Comment by mnordine** [comment]
Very cryptic, 😆

**Comment by stereotype441** [comment]
> Very cryptic, 😆

Yeah, sorry. I was trying to see if it was possible to rework the language's notion of an inference context so that we had a clean separation between a "required context" (an inference context that, if not satisfied, would lead to a compile-time error) and an "aspirational part" (an inference context that was desirable to satisfy, but not necessary). The work got very involved, because inference contexts are used so heavily throughout the language. Not only was it a lot of work to specify, but it was clear that it would be a very big undertaking to implement. After consultation with the language team, we decided to try another approach, where instead of splitting up the two kinds of contexts, we would simply get rid of aspirational contexts entirely. This is tracked in https://github.com/dart-lang/language/issues/3471.
