### ISSUE TITLE
Support transitive import/export

### ISSUE THREAD

**Issue by gisborne** [dart-lang/language#347]
Imports are currently not transitive: if I import a into main and b into a, I cannot access b in main.

Probably, in general, this is desirable behavior. But it would be nice in a situation where I am trying to manage access to a complex set of objects, that I can group them in files.

Probably some sort of extra or different keyword for import? 'import_export "package:…" '? or 'import "package:…" and export'?

**Comment by lrhn** [comment]
The current solution is to import *and* export the same library in two different declarations:
```dart
library a;
import "b.dart";
export "b.dart";
... use b ...
```

Keeping them separate also allows having different show/hide operations on the two, which can be useful:
```dart
library a;
import "src/b.dart";
export "src/b.dart" hide privateHelperFunction;
... privateHelperFunction(bThing) ...
```
That means that a combined import/export declaration won't even be used in all cases where you currently do both for the same library.

All in all, the current language has a sufficient solution for an issue which happens fairly rarely, so we have no current plan to add further language features to combine the import/export into one declaration.

**Comment by munificent** [comment]
Closing this because I think the language can already express what @gisborne requests.
