### ISSUE TITLE
Treat member access of a constant record as a constant expression.

### ISSUE THREAD

**Issue by water-mizuu** [dart-lang/language#3476]
Since a record's type is known at compile time, and if a record is constant then all of its members are constant, then we should just be able to use a constant record's members as a constant as well in my opinion.

```dart
const dimensions = (width: 250, height: 750);
const child = SizedBox(width: dimensions.width, height: dimensions.height);
```

**Comment by rubenferreira97** [comment]
I think these are duplicates #3004 and https://github.com/dart-lang/language/issues/2219#issuecomment-1490026741.

**Comment by water-mizuu** [comment]
> I think these are duplicates #3004 and [#2219 (comment)](https://github.com/dart-lang/language/issues/2219#issuecomment-1490026741).

Oh, that's my bad. Closing this one.
