### ISSUE TITLE
Type inference fails on switch expression but works on switch statement

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/language#3477]
This code does not compile:

```dart
import 'dart:convert';

class IntConverter extends Converter<String, int> {
  @override
  int convert(String s) => int.parse(s);
}
class DoubleConverter extends Converter<String, double> {
  @override
  double convert(String s) => double.parse(s);
}

Converter<Object?, Object?>? selectConverter(String name) {
  // OK
  Converter<Object?, Object?> c1 = IntConverter();
  // OK
  Converter<Object?, Object?> c2 = DoubleConverter();
  // NOT OK: 
  return switch(name) {
      'int' => IntConverter(),
      'double' => DoubleConverter(),
      _ => null,
  };
}
```

The error says:

> A value of type 'Object?' can't be returned from the function 'selectConverter' because it has a return type of 'Converter<Object?, Object?>?'.

However, as `c1` and `c2` show, the types should check.

Indeed, with a switch statement it works:

```dart
Converter<Object?, Object?>? selectConverter(String name) {
  switch(name) {
    case 'int': return  IntConverter();
    case 'double': return DoubleConverter();
    default: return null;
  }
}
```

It's a minor inconvenience, of course, but hopefully can be fixed.

**Comment by leafpetersen** [comment]
I believe this is an example of [this issue](https://github.com/dart-lang/language/issues/1618) (see my comment as of March 31).  There is work in progress to address this.  cc @stereotype441
