### ISSUE TITLE
Adjust specification regarding dynamic exceptions which happen when accessing deferred library which is not loaded 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/language#3481]
Section `19.1.2 Semantics of Imports` says the following about top-level functions 

```tex
  For every top level function $f$ named \id{} in
  \NamespaceName{\metavar{import},i},
  a corresponding function named \id{} with the same signature as $f$.
  % This error can occur because being-loaded is a dynamic property.
  Calling the function results in a dynamic error,
  and so does closurizing it
  (\ref{functionClosurization}).
```

This seems to imply that checking whether library is loaded or not happens on invocation and we have test `language/deferred/not_loaded_check_test` which tries to test that during evaluation of an expression `lib.f(sideEffect())` where `lib` is not loaded the following will happen:

1. `sideEffect` is executed
2. An `Error` is thrown. 

However CFE implements a different semantics (ever since it started to support deferred loading, see [CL](https://dart-review.googlesource.com/c/sdk/+/35100)): checking whether the library is loaded or not is done _before_ arguments are evaluated. 

I suggest we update specification to match the implementation. Test update CL: https://dart-review.googlesource.com/c/sdk/+/338125

Related issue https://github.com/dart-lang/sdk/issues/54151

**Comment by eernstg** [comment]
Presumably, we can specify the semantics where the dynamic error occurs before any actual arguments are evaluated, because (IIUC) the CFE determines the behavior of all backends in this case. So we don't even have to consider making it an implementation specific behavior, or in any way allowing for both orderings.

See https://github.com/dart-lang/language/pull/3483.

**Comment by lrhn** [comment]
I remember disgussing this before, somewhere.
The spec is completely off, and shouldn't be trusted.
You're not allowed to tear off a function, or constructor, from a library which hasn't been loaded yet, the _attempted access_ to any name through the deferred prefix should throw, as if `prefix.name...` was guarded by `!prefix._loaded ? throw ...an error... : prefix.name...`.

If that's not how it's specified, it should be.
