### ISSUE TITLE
Can`t mixin class with extended mixin

### ISSUE THREAD

**Issue by ChaserVasya** [dart-lang/language#3484]
my helper file
```
import 'dart:async';
import 'package:bloc/bloc.dart';

mixin MyEventInterceptor<E, S> on _EventHandlerIntercepted<E, S> {
  S createErrorState(AppException e);

  @override
  _interceptor(handler, emit) async {
...
  }
}

mixin _EventHandlerIntercepted<Event, State> on Bloc<Event, State> {
  @override
  void on<E extends Event>(
    handler, {
    transformer,
  }) {
    return super.on(
      (event, emit) => _interceptor(() => handler(event, emit), emit),
      transformer: transformer,
    );
  }

  FutureOr<void> _interceptor(
    FutureOr<void> Function() handler,
    Emitter<State> emit,
  );
}
```
my bloc code
```
class MyBloc
    extends Bloc<MyEvent, MyState>
    with MyEventInterceptor<MyEvent,   MyState> {
...
}
```

error:

```
'MyEventInterceptor<MyEvent, MyState>' can't be mixed onto 'Bloc<MyEvent, MyState>' because 'Bloc<MyEvent, MyState>' doesn't implement '_EventHandlerIntercepted<MyEvent, MyState>'. (Documentation)  Try extending the class 'MyEventInterceptor<MyEvent, MyState>'.
```

dart 3.2.0

**Comment by lrhn** [comment]
That is working as currently specified.
As the error says, `Bloc` doesn't implement `_EventHandlerIntercepted`, so you cannot apply `MyEventInterceptor` to it.

If you're asking for this to work, then it's really a request for composite mixins, where `MyEventInterceptor` would somehow be declared as _including_ the `_EventHandlerIntercepted` mixin, and mixing it in will apply both.
(That will require new syntax, the current declaration already has a specific meaning.)

**Comment by TekExplorer** [comment]
> That is working as currently specified. As the error says, `Bloc` doesn't implement `_EventHandlerIntercepted`, so you cannot apply `MyEventInterceptor` to it.
> 
> If you're asking for this to work, then it's really a request for composite mixins, where `MyEventInterceptor` would somehow be declared as _including_ the `_EventHandlerIntercepted` mixin, and mixing it in will apply both. (That will require new syntax, the current declaration already has a specific meaning.)
> 
> There is an existing issue for mixin composition, #540, do we'll defer to that.

Why would that need new syntax? wouldnt `mixin [class] MyMixin with OtherMixin, Mixin2 {}` be enough? It's a compiler error to do this now.

**Comment by lrhn** [comment]
Well, that *is* new syntax, since a `mixin` or `mixin class` cannot have a `with` clause today.
It doesn't have to very different new syntax, preferably not, just some syntax which doesn't already have a meaning that we'd have to change.
