### ISSUE TITLE
Soundness issue with cast patterns

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3488]
Consider the following program:

```dart
sealed class A {
  bool get b => true;
}

class B1 extends A {}
class B2 extends A {}

class Cheat implements B1, B2 {
  bool get b => false;
}

void main() {
  A a = Cheat();
  int i = switch (a) {
    B1(b: true) as B1 => 1,
    B2(b: true) as B2 => 2,
  };
  print(i); // 'null'.
}
```

The program contains a switch expression which is accepted at compile time, that is, its set of cases is classified as exhaustive. However, no case matches an object of type `A` whose `b` is false, such as an instance of `Cheat`.

The problem is that the first case is considered to handle every instance of `B2` (because they are assumed to cause the cast to `B1` to throw) and the second case is considered to handle every instance of `B1` (because they are assumed to cause the cast to `B2` to throw), but an instance of `Cheat` will complete both casts normally, and then be rejected by the requirement that its `b` must be true.

At first, this is an implementation issue.

However, the specification is so similar that we can construct a variant of the above example which shows that there is an issue with the specification as well. The rule about the space obtained for a cast pattern is as follows:

> Formally, the space union `spaces` for a cast pattern with cast type `C` is a union of:
>
> 1.  The lifted space union of the cast's subpattern in context `C`.
> 2.  For each space `E` in the *expanded spaces* (see below) of `M`:
>   a.  If `E` is not a *subset* (see below) of `C` and `C` is not a subset of `M`, then the lifted space union of `E`.

The actual implementation requires that `C` is a subtype of `M` in order to take (2) into account at all (the spec has no such requirement), and then the implementation requires that `E` is not a subtype of `C` and `C` is not a subtype of `E` (at the same point, the spec requires that `C` is not a subtype of `M`).

So we have a discrepancy between the implementation and the specification, and it will not suffice to adjust the specification such that it follows the implementation (because the implementation has a soundness issue, as shown above).

However, it is also not sufficient to change the implementation such that it follows the specification precisely. The following example has a similar soundness issue, and it would be accepted with the specified cast pattern space:

```dart
sealed class A {
  bool get b => true;
}

class C1 {}
class C2 {}

class B1 extends A, implements C1 {}
class B2 extends A, implements C2 {} 

class Cheat implements B1, B2 { bool get b => false; }

void main() {
  A a = Cheat();
  int i = switch (a) {
    B1(b: true) as C1 => 1,
    B2(b: true) as C2 => 2,
  };
}
```

In this case we don't require that the cast pattern is a subtype of the sealed type (so we can cast to `C1` or `C2` even though they aren't subtypes of `A`), but we still conclude that the first case covers all of `B2` (because it's assumed to cause the cast to `C1` to throw), and similarly we conclude that the second case covers all of `B1`, so the switch expression is exhaustive.

(Except, of course, that it isn't.)

All these computations in (2.a) are concerned with an approximation from below of the complement to the target type of the cast pattern (that is, we want to compute a space `S` that only contains objects that will definitely cause the cast to throw), but these examples show that the currently used criteria are too permissive: They allow some objects to be considered "throwing hence safe" even though they will _not_ cause the cast to throw.

In my comment [here](https://github.com/dart-lang/sdk/issues/54125#issuecomment-1829974572), I proposed a rule where no attempt is made to compute this approximation of the complement of the cast target type (so we get an approximation from below which is definitely sound: the empty set). We can start there, and then change it to a better approximation from below if we come up with some safe ways to include anything.

In particular, we could use information about disjointness of types (if `T1` and `T2` are disjoint then an instance of type `T1` will _definitely_ cause an exception to be thrown at a cast of the form `as T2`), but the rich support for creating subtypes of existing types makes it a little bit hard to show disjointness. Good candidates could be types that are final or otherwise known to have no other subtypes than a statically and locally known set. In any case, that's an improvement we can introduce later on, based on whatever we can come up with.

**Comment by lrhn** [comment]
I think we can safely account for the cast in one case: when matching the cast type implies matching the sub-pattern.

So, if _C_ \<: _S_, then the cast pattern does match `Object?`, it's a catchall pattern, where _S_ is the matched spaces of the sub-pattern.

That would account for a catchall like
`var i as int`, where `i` is inferred as `int`, so if we ignore the cast type, then it looks like it would only exhaust integers.

**Comment by eernstg** [comment]
> I think we can safely account for the cast in one case: when matching the cast type implies matching the sub-pattern.

Certainly yes, and that's also the middle item in the rule that I sketched out [here](https://github.com/dart-lang/sdk/issues/54125#issuecomment-1829974572):

> ...
> Otherwise, if `C` is a subset of `S` then the result is `M`.
> ...

This item is also included in [the CL](https://dart-review.googlesource.com/c/sdk/+/338760) from @johnniwinther, and it does already cover cases like the following:

```dart
sealed class M {}
class B extends M {}
class A extends M {}

method(o) => switch (o) {
      (A() || B()) as M => 0,
    };
```

In this example, the subpattern `A() || B()` is recognized at accepting every matched value of type `M`, which means that the CL already allows for non-trivial computations of the space of the subpattern (that is, we do not just handle `var x` or `M x`).

However, the behavior reported in this issue is orthogonal: The rule that causes the unsoundness is present both before said CL and after, and this means that it needs to be addressed separately.

**Comment by munificent** [comment]
This is a really great analysis! Thank you for digging into this and figuring it out. I agree the spec should be changed. I was trying to be too clever with cast patterns and sneak in some space-subtraction-like operation when clearly it doesn't make sense given that (by design!), sealed types are not required to be disjoint.

**Comment by eernstg** [comment]
The specification has been updated in https://github.com/dart-lang/language/pull/3490 and the (shared) implementation has been updated in https://dart-review.googlesource.com/c/sdk/+/338760.
