### ISSUE TITLE
Does dart support the loongarch64?

### ISSUE THREAD

**Issue by hoytluo** [dart-lang/language#3489]
On the https://dart.dev/get-dart website, Dart has Supported architectures: x64, IA32, ARM64, ARM, RISC-V (RV64GC).
Dose it support loongarch64(https://wiki.debian.org/LoongArch)? If yes, where can I download it. If not , does you have any plans to support it？

**Comment by mraleph** [comment]
Not supported at the moment and no concrete plans to support it.

**Comment by mraleph** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/53480

**Comment by mraleph** [comment]
cc @mit-mit
