### ISSUE TITLE
Support Object Deconstruction or Else Statements

### ISSUE THREAD

**Issue by mcmah309** [dart-lang/language#3506]
Given
```dart
sealed class ABC {}

final class A implements ABC {
  final int a;

  const A(this.a);
}

final class B implements ABC {
  final int b;

  const B(this.b);
}

final class C implements ABC {
  final int c;

  const C(this.c);
}

class Foo{
  final int bar;
  
  const Foo(this.bar);
}
```

Dart already supports object deconstruction:
```dart
void main(){
    final Foo(:bar) = Foo(1);
    //  can now use "bar"
}
```
And Dart supports If-Case statements:
```dart
void main(){
    ABC abc = A(1);
    if(abc case A(:final a)){
        // can now use "a"
    }
}
```
Therefore Dart should also support Object Deconstruction or Else Statements:
```dart
void main(){
    ABC abc = A(1);
    A(:final a) = abc else {
        // break, continue, return, or throw
    }
    // can now use "a"
}
```
This is effectively a pattern matching guard clause.

**Comment by mcmah309** [comment]
For reference, from another language: doc.rust-lang.org/rust-by-example/flow_control/let_else.html

**Comment by water-mizuu** [comment]
This seem similar to #2703. You can see the discussion there.

**Comment by mcmah309** [comment]
Different, but similar. This is specifically for object deconstruction and fits well into the existing syntax and does not require reserving a new keyword like "let". If "if-case" statements are one side of the coin, then "Object Deconstruction or Else" (open to a new name) is the other side of the coin.
Example with current syntax:
```dart
void main(){
  ABC abcA = A(1);
  int a;
  if(abcA case A()){
    a = abcA.a;
  }
  else {
    return;
  }
  // use a
}
```
Example with proposed syntax:
```dart
void main(){
  ABC abcA = A(1);
  A(:final a) = abc else {
    return;
  }
  // use a
}
```

**Comment by munificent** [comment]
I would like to have something like Swift's "guard let" or Rusts "let if" as well. I'm going to merge this issue with #2537, which discusses that more generally without being pinned to a specific syntax.
