### ISSUE TITLE
Subtyping in element type of generator function

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/language#3513]
The language spec states:

> It is a compile-time error if the declared return type of a function marked `sync*` is not a supertype of `Iterable<T>` for some type `T`. It is a compile-time error if the declared return type of a function marked `async*` is not a supertype of `Stream<T>` for some type `T`. It is a compile-time error if the declared return type of a function marked `sync*` or `async*` is `void`.

It then states:

> We define the *element type of a generator function `f`* as follows: Let `S` be the union-free type derived from the declared return type of `f`. If `f` is a synchronous generator and `S` implements `Iterable<U>` for some `U` then the element type of `f` is `U`. If `f` is an asynchronous generator and `S` implements `Stream<U>` for some `U` then the element type of `f` is `U`. Otherwise, if `f` is a generator (synchronous or asynchronous) and `S` is a supertype of `Object` (which includes `Object` itself) then the element type of `f` is `dynamic`.

I'll restrict to the `sync*` case, though similar considerations apply for `async*`.

The declared return type of a `sync*` function must be a non-`void` supertype of `Iterable<T>` for some `T`. So when we compute the element type, do we really need to check whether `S` *implements* `Iterable<U>` for some `U`, or is it sufficient to check whether it *is* `Iterable<U>` for some `U`?

Similarly, is there a reason the spec mentions checking if `S` is a supertype of `Object` rather than simply falling back to `dynamic` if the `Iterable` check fails? It does note that no other cases are possible.

**Comment by munificent** [comment]
> do we really need to check whether `S` _implements_ `Iterable<U>` for some `U`, or is it sufficient to check whether it _is_ `Iterable<U>` for some `U`?

As always, I defer to our spec-lord @eernstg, but your understanding sounds right to me. The only declared return type for a `sync*` function (after removing `?` and `FutureOr`) that implements `Iterable` and is a supertype of `Iterable` is just... `Iterable`.
