### ISSUE TITLE
Allow setter with a method of same name

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/language#3519]
In JS world you can set a method body in an object, ie:

```js
const foo = {bar: function() {}};

foo.bar = function() {}
```

This isn't possible in Dart:

```dart
class Foo {
  void foo() {}
  
  set foo(void Function() newFoo) { // the name foo is already defined
    print('Setter');
  }
}
```

This makes it hard to transpile JS bindings to Dart.  

Would be nice to allow a setter with the same name of a method.

**Comment by jakemac53** [comment]
How is this different from a mutable field with a function type?

**Comment by jodinathan** [comment]
> How is this different from a mutable field with a function type?

you can't have generics

**Comment by jakemac53** [comment]
You can, you can't _alter_ the static generics but that could never work anyways https://dartpad.dev/?id=6330079dc6bdd7b80d0bb9d52a460696

**Comment by jodinathan** [comment]
can you change to getter and setter please: 

```dart
class Foo<T> {
  T Function<F>(T v) foo = <F>(T v) {
    print('original $F');
    return v;
  };
}
```

**Comment by jodinathan** [comment]
I think I've got it.  

thanks
