### ISSUE TITLE
It is inconvenient to do pattern matching on "this"

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#3521]
One regular scenario when using extensions is to do pattern matching on `this`.

For example:

```dart
extension on num {
  void example() {
    if (this is int) doSomethingWithInts(this);
    else doSomethingWithDoubles(this);
  }
}
```

The problem is, `this` is not promoted after doing type-checks on it. This forces us to either use casts or dereference `this`.

For example a common pattern I've used is:

```dart
final that = this;
if (that is int)  doSomethingWithInts(that);
```

But this feels redundant. Would it be possible to promote `this` when doing type checks on it?

**Comment by halildurmus** [comment]
Duplicate of #1397

Reading the comments, it looks like this was supposed to be part of the promotion of the private final fields feature (#2020).

cc @stereotype441

**Comment by rrousselGit** [comment]
Closing since this is a dupp. Sorry I missed it
