### ISSUE TITLE
[extension] Allow extension to implement interfaces

### ISSUE THREAD

**Issue by medz** [dart-lang/language#3526]
Usually, we will define some interfaces:

```dart
abstract interface class Responsible {
   /// Converts self to a [Response] object.
   Future<Response> toResponse(Request request);
}
```

Especially when using dart for the backend, we usually use built-in data types such as String, int, list, map, etc. In the return value of a function, we usually require some type data of a specified interface, such as Responsible above. We can implement it with String like this:

```dart
extension StringResponsible on String implements Responsible {
   Future<Response> toResponse(Request request) async {
     return Response();
   }
}
```

A complete example:

```dart
abstract interface class Digitizable {
    int toInt();
}


extension on String implements Digitizable {
   int toInt() => int.parse(this);
}

extension on num implements Digitizable {}

void echo<T extends Digitizable>(T value) => print(value.toInt());

main() {
     echo(1); // Int 1
     echo(2.0) // Int 2
     echo("3") // 3
    echo([1]) // Error
}
```

The purpose of this is of course for specification and type safety.

**Comment by Wdestroier** [comment]
Looks effectively the same as Rust traits. I guess nobody created an issue specifically for that feature and previous discussion is spread around.

**Comment by mraleph** [comment]
Duplicate of https://github.com/dart-lang/language/issues/736
