### ISSUE TITLE
Macro applied to wrong place should be an error

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/language#3530]
> On the topic of where macros can be applied, a suggestion: should it be an error to apply a macro somewhere if it does not implement the corresponding interface? e.g. should @MyMacro() class Foo{} be an error if it does not implement any Class*Macro? I guess that should cut out a lot of cases where someone is holding it wrong and puzzled why nothing is happening, and I can't think of a downside. (I guess it could equally be a hint "macro does nothing here" instead of an error).

@jakemac53 I can take a shot at updating the spec if you like. Thanks!

**Comment by jakemac53** [comment]
SGTM!
