### ISSUE TITLE
[BUG]: I Discovered a Bug in Basic Arithmetic Operation  in Dart  

### ISSUE THREAD

**Issue by akm005** [dart-lang/language#3541]
- There is Bug in Dart which is very easy to replicate  
## My Installation Configuration
`Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "windows_x64"`
 The bug is Quite Simple :
While performing the following calculation the results are unexpected

`2.6207 -10 = -7.379300000000001`
`1.2599 -30 =  -28.740099999999998`

**Comment by PlugFox** [comment]
Report it to other programming languages as is too, please.

**Comment by lrhn** [comment]
That's working as intended, and it's inherent in the way IEEE-754 floating point numbers are designed.

Some numbers you can write as literals, cannot be represented precisely by 53 binary digits and an exponent.
The shortest example of that is `0.1`.
