### ISSUE TITLE
"The class doesn't implement the required class", although it does.

### ISSUE THREAD

**Issue by edward-a** [dart-lang/language#355]
I stumbled upon the following issue:

```dart
mixin M on A {
}

class A {
}

class B with M implements A {
}
```
The compiler complains about the "with M" part saying: "The class doesn't implement the required class 'A'", although it does because of "implements A"?

I was going to rely on the code above to implement a code generator that would by place M and A in a separate file. Using "extends A" instead of "implements A" is a serious limitation as you will not be able to inherit other classes with B.

**Comment by leafpetersen** [comment]
This is a dup of https://github.com/dart-lang/sdk/issues/36775 .  The error message has been fixed in bleeding edge.  Reading between the lines, I think you want to use `mixin M implements A` instead of what you wrote above (see my comments on the linked issue).

**Comment by edward-a** [comment]
> 
> 
> This is a dup of [dart-lang/sdk#36775](https://github.com/dart-lang/sdk/issues/36775) . The error message has been fixed in bleeding edge. Reading between the lines, I think you want to use `mixin M implements A` instead of what you wrote above (see my comments on the linked issue).

Yep, you are right. I am new to Dart, thanks for the hint!
