### ISSUE TITLE
TypeParameterDeclaration and library when inside FunctionTypeAnnotation

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#3559]
In the analyzer `TypeParameterElement` inside `FunctionType` does not have `library`. The reason is that `FunctionType` is just a type, not a declaration, it does not live in any specific library. But `TypeParameterDeclarationImpl.library` is not nullable.

@jakemac53

**Comment by jakemac53** [comment]
Interesting, I see what you are saying. There is a surrounding library in which the function type was written though, and the type parameter of the function type _is_ a declaration. I don't want to make `library` nullable for all declarations just because of this, if it is possible to figure out the library?

If it is not feasible to do so, we can look at maybe splitting up the interfaces or something.

**Comment by scheglov** [comment]
In the analyzer `FunctionType` does not know inside which library it was "written". I say "written" because it is not obvious to me what this means. If we have `void Function() a = ...;` in `a.dart`, and then `final b = a;` in `b.dart` - what is the library of the `b` type?

We have already a precedent, using `FunctionTypeParameter` for formal parameters in function types. So, we could have `FunctionTypeTypeParameter`, which also does not implement `Declaration`.

**Comment by jakemac53** [comment]
> In the analyzer `FunctionType` does not know inside which library it was "written". I say "written" because it is not obvious to me what this means. If we have `void Function() a = ...;` in `a.dart`, and then `final b = a;` in `b.dart` - what is the library of the `b` type?

I was assuming this would only apply for explicit types, but I see that this could come up when getting an inferred type.

> We have already a precedent, using FunctionTypeParameter for formal parameters in function types. So, we could have FunctionTypeTypeParameter, which also does not implement Declaration.

I am also realizing now, that you shouldn't be able to get an `Identifier` for these type parameter declarations. I think this is why regular function type parameters already do not implement `Declaration` as well. While it is sort of a declaration, it isn't one that you can ever reference, and really doesn't belong to a library.

So, I agree we should add `FunctionTypeTypeParameter`.

**Comment by jakemac53** [comment]
Note that https://dart-review.googlesource.com/c/sdk/+/346640 is the implementation for this

**Comment by jakemac53** [comment]
this has landed
