### ISSUE TITLE
Pleasant Surprise with assigning generic classes

### ISSUE THREAD

**Issue by AdamRose66** [dart-lang/language#3565]
It seems that generic classes are assignable if the generics are subtypes of each other:

```
abstract interface class A
{
  void a();
}

abstract interface class B
{
  void b();
}

abstract interface class combined implements A , B
{
}

class C<IF>
{
  IF? my_interface;
}

void main()
{
  C<combined> c_combined = C();
  C<A> c_a = c_combined;
}
```

I'm not complaining about this - it's very useful. But is this an accident, or a deliberate part of the specification ?

Thanks,
Adam.

**Comment by mraleph** [comment]
Dart generics are covariant by design. 

https://dart.dev/resources/faq#q-why-are-generics-covariant
