### ISSUE TITLE
Add containsAny to the Set API.

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/language#358]
Right now the Set API includes a [`containsAll`](https://github.com/dart-lang/sdk/blob/86c71659697b50c9921c2f3ac520ec867b7c14cc/sdk/lib/collection/set.dart#L90) method. It would be nice to have a similar `containsAny` method.

Example:
```dart
final foo = <String>{'a', 'b', 'c'};

foo.containsAny({'a', 'b'}); // Returns true.
foo.containsAny({'c', 'd'}); // Returns true.
foo.containsAny({'d', 'e'}); // Returns false.
```

I know the same can be accomplished with `foo.intersection({'c', 'd'}).isNotEmpty`, but `containsAny` would be a lot cleaner.

**Comment by mockturtl** [comment]
Another option is to pass [`contains`](https://api.dartlang.org/stable/2.3.0/dart-core/Iterable-class.html) to `any` (or `every`!) as the test function.

```dart
{1,2,3}.any({2,4,6}.contains)); // true
{1,2,3}.any({4,5,6}.contains)); // false
```

[dartpad](https://dartpad.dartlang.org/b51c02cd3050aa77617943dbe8ab7a8b)

**Comment by srawlins** [comment]
I don't think this is a Language request. This belongs at https://github.com/dart-lang/sdk/issues.

**Comment by johnsonmh** [comment]
Thanks for the suggestion @mockturtl !

I still think `containsAny` is easier to follow, but `foo.any(bar.contains)` is a step closer.

Good point @srawlins , I'll close this in favor of: https://github.com/dart-lang/sdk/issues/36985
