### ISSUE TITLE
Abandon "Value classes" proposal after macros are landing in dart

### ISSUE THREAD

**Issue by MohiuddinM** [dart-lang/language#3600]
[Values classes](https://github.com/dart-lang/language/tree/main/working/value-classes) proposal is superseded by [macros]( https://github.com/dart-lang/language/tree/main/working/macros), and macros are being added to dart.

**Comment by mraleph** [comment]
Changes to `identity` behavior and `copyWith` semantics as described in that proposal can't be implemented through macros. Macros can help generating the boilerplate though.

**Comment by munificent** [comment]
It's just a proposal, so we don't need to officially "abandon" it since all proposals default to being in a "not going to be shipped" state unless they get accepted. So I don't think there's anything we need to take action on for this issue.
