### ISSUE TITLE
Proposals for Dart 4.0

### ISSUE THREAD

**Issue by Ing-Brayan-Martinez** [dart-lang/language#3617]
# Introduction

Greetings to the Dart development team, I really want to thank you for the effort you have made during all this time as you have evolved the language from version 2.0 to 3.0. Personally, I have been a user of this language since 2015 and I have followed its history. I have always believed May this language go far

In these times that we live in another era, after the 2020 pandemic everything has changed, that is why I want to express everything that I have thought is something that obsesses me and that I must let go by expressing it in this way, artificial intelligence is now a very important actor. important and Google is making efforts and is achieving important results, they have managed to free Gemini, they are doing well. I like what they have done. In addition to AI, I think that the other card that Google must play to compete with Microsoft is cross-platform development, along with AI, it must be the most important thing. for google

I believe that the next level to overcome the Dart language is the consolidation of a much broader ecosystem than the current one, so that the world sees that Google uses its own language, and that it is really being useful because it generates competitive advantages in the market, currently. Dart is very far from the top 10 of the tiobe index, that is why you should think about the idea of creating the “Dart Platform” which would be equivalent to what .NET and C# are for Microsoft, with the same framework you can create all types of apps or technological solutions is not entirely crazy and is the way to go

# Proposals to improve Google

- The first thing I observe is the way in which Google uses its own language, I think that the use of the Dart language should be mandatory for all Google workers. For example, Microsoft invented C# around the year 2000 and all the creations of this company are made with C#, this forced them to develop the language, because they always used it, the more it is used, the more development it will have, because it will be possible to determine to what extent they can create technological solutions with this technology, I think that Dart should be equivalent for Google as C# is for Microsoft. Google products should be manufactured with Dart. I also think that Dart should be requested as a requirement when applying for a job for Google. I think that greater use should be invested in the development of the platform.

- Another point that I don't understand about Google is because most of this company's apps are not cross-platform, it would be interesting to see a desktop application for Gmail made with cross-platform Flutter. I personally use Windows MacOS and Ubuntu and there is no Gmail app for desktop. Microsoft is slowly moving into cross-platform development and is winning, but Google has everything to win because it has better technology. Flutter is better than MAUI by far. Google has a competitive advantage but it is not noticeable simply because you are not using its own technology.

- The fact that Dart is required as a requirement to work at Google forces new programmers to learn this technology. Many people dream of working at Google and will do whatever it takes to achieve that goal. This will make the Dart community start to grow and really It is necessary because it is an excellent technology with few users.

- Google has big challenges because the economic conditions are very difficult due to the increase in interest rates by the Federal Reserve and the tough competition, especially in the area of AI, Google is changing and I think the 2 flags to develop are the AI and cross-platform applications

- A Google product that feels abandoned is the Chrome Book. I think it is a totally wasted product. I think a relaunch of a Chrome Book based on an ARM chip equivalent to Apple's M1 with 16GB of ram and 1TB SSD with an operating system based on Android something like what Samsung does with the tablet Galaxy Tab, that has Desk mode if this is possible it is more than enough they have everything won ask people and they will see that if they would buy it this platform is important because they would be the basis to see why finally a Gmail app for desktop there would also be a version for Windows MacOS and Ubuntu which is better than its own ecosystem

- I think that all Google apps in their web version should have a drop-down menu next to where the Google account menu is that contains the famous buttons that point to the Windows Store, the App Store, the Snap Store and Google Play so that from the web version you can obtain the desktop version using the official stores, the idea is that with the same code base it can be deployed to many platforms and that the current GMail app becomes a multi-platform

- The biggest objective is to develop an ecosystem to attract many more users and ensure that the Dart language enters the top 10 of the tiobe index and maintains relevance as long as the Google platform is a reference for the company and gains the trust of community

# Proposals to improve Dart

- The advances in the Dart and Flutter graphics engine have been notable. I think that the approach to making Dart a better platform is to develop Flame or a proprietary Google framework to create cross-platform video games. This is the key, if we look at the video game industry. Many companies spend millions of dollars on ports of games to other platforms. The idea is to be able to create games at low cross-platform costs, that is, to be able to create a game for Playstation, Xbox, Seam or PC, Android and IOS. The idea is to support all the usual platforms. so that video game companies can trust that they can invest in Dart with licenses similar to those of Unity or Unread Engine that is a source of income for Google. Another important thing is the recovery of the Stadia brand as an association of indie video game studios and that Stadia provides the technology and distribution and support to video game studios to compete against Xbox. This is key to making Dart used in the video game industry expanding the ecosystem

- Google is already strongly developing AI thanks to Google Deep Mind and tools like tensorflow, owned by Google. I think that Python currently has the monopoly on the development of data science, for me Dart is a worthy opponent to create a script for data science so that this is It is possible that it is necessary to develop Dart to make it usable in this area, starting with [Google Colab](https://colab.research.google.com/). I don't know if it would be possible to create a kind of notebook equivalent to Jupyter, but instead of working with Python, it works with Dart. This allows Dart to be usable in science. Data is a very necessary feature to add more users to the platform and expand the ecosystem.

- In the year 2024, the Apple vision pro was launched, which represents the iPhone moment but in the VR AR industry. I think that Dart should open up to these new platforms to create apps that are usable in these new virtual reality glasses. Currently, the 2 strongest platforms are the [Apple Vision Pro](https://www.apple.com/apple-vision-pro/) and the [Meta Quest](https://www.meta.com/quest/). There are other companies that still need to consolidate, the point is that Dart is usable for app developers for VR glasses, adding more users and expanding the ecosystem

- Another important platform is Smart TV. Personally, I am a Google TV user and sometimes I don't understand why there are so few Google apps for this platform. If Google would be betting on AI and also on multiplatform, TV should be supported to attract more programmers who use it. Dart language and espanda the ecosystem

- To create applications it is necessary to use the cloud, Google has the GCP for the development of all types of backend solutions to be able to interact, it is necessary to develop a series of libraries that allow interacting with each of the services offered by the Google cloud. something that is equivalent to the [Azure SDK ](https://azure.microsoft.com/en-us/downloads/) that allows integration of Azure services in supported languages. Google must develop better support for Dart with an equivalent SDK to have more integration options in the Dart language ecosystem, currently you have FlutterFire to use Firebase but it is necessary to develop an SDK for the Google cloud, another point is the use of Dart to create cloud functions, and the use of Dart for the Google Cloud CLI with the help of the SDK all to expand the ecosystem

# Conclusions

After reading everything you will be thinking that this man "went crazy", I simply wanted to express my vision to the community and receive feedback, Google should use its own technology to generate trust and more companies use Dart my vision is like the famous viral meme " this can run Doom" the idea is that Dart can run anywhere creating a solid ecosystem Google's challenge is to improve its ecosystem I hope to be able to contribute positively to my favorite language greetings

**Comment by Ing-Brayan-Martinez** [comment]
This proposal completely excludes the web version because Flutter is not prepared to compete on the web, this is only for mobile and desktop platforms and the new platforms mentioned, it is necessary to clarify this. As a user, I dream that Google invests in bringing all its apps to the multi-platform and we have a desktop version of all Google Workspace apps powered by Duet AI and Geminis, this is the future we all hope for

**Comment by Ing-Brayan-Martinez** [comment]
I personally would pay a Google One subscription of $30 a month, to have all the Google desktop apps plus Duet AI with Gemini and 2TB of Google Drive in a single package for individual users as a pro version. These are the same plans offered by companies like Adove with the creative cloud subscription, or Jetbrains with the All products pack subscription, or the Microsoft 365 subscription that offers you all the old office products, Google has to generate income because There are liquidity problems, there is inflation, this is an opportunity.

**Comment by miyoyo** [comment]
Not to burst your bubble, but this is a repository for language improvements to Dart, such as changing syntax, behavior of existing structures, built-in libraries and so on.

The current issue is more of a cultural shift request than a language change request.

I'd encourage you to read other issues on this repository to understand what an actionable language proposal is.

**Comment by Ing-Brayan-Martinez** [comment]
You are right, the idea was to communicate to the community, generate a debate, and then create actionable proposals. The Dart language is a technology that at the syntax level is quite mature, it has a large number of very good tools, that is why it is my language major. I do business consulting, I am also a technology promoter, I always propose Dart and Flutter as an option for new projects, but I always receive the same response from companies. Many do not want to risk using Dart language, due to the shortage of programmers and the reduced ecosystem it offers. So what must evolve is the ecosystem, the syntax is already very good. Sometimes we must think about how companies seek profitability from the use of technology, they make everything work, they are the ones who pay the bills. We must gain the trust of companies so that technology has a better future

**Comment by nate-thegrate** [comment]
@Ing-Brayan-Martinez If you'd like to post this to a place where you can interact with the Dart/Flutter developer community, Reddit would be ideal. Check out [r/FlutterDev](https://www.reddit.com/r/FlutterDev/) or [r/DartLang](https://www.reddit.com/r/dartlang/) if you're interested.

**Comment by miyoyo** [comment]
Even beyond that, here's what actionable in your original post:
- Force Google employees to use dart (this is not up to the dart team) 
- Remake Gmail in Flutter (that is not up to the dart team)
- Make more powerful Chrome Books (that is not up to the dart team)
- Put a "download app" link in Google products (that is not up to the dart team)
- Make a Dart-based game-oriented engine (this is a brand new project, and would require a new team, aka, that is not up to the dart team)
- Make a Dart core for jupyter (see above)
- Support the vision pro (good news! Dart runs on the vision pro, flutter kinda does too, this *is* within the purvew of the flutter team, and already an issue)
- Smart TV support (Either its android, Web or tvOS, the last one isn't officially supported, but it's doable, hey, another one within the purview of the flutter team, and, just like above, already there)
- GCP sdk (that is not really up to the dart team)

Everything else is pretty much asking for a culture shift, and this is not something one can request, this is something that's up to you, as an individual, to further. 


You sound enthusiastic about flutter and dart, and that's great!
But you need to keep this issue list for appropriate requests, this is not Google's "you should run your company like this" inbox.

**Comment by Ing-Brayan-Martinez** [comment]
I understand. I am completely unaware of how Google is organized internally, I am only expressing my point of view, all these proposals are outside of its responsibilities and that is fine, the only thing you can do is meet as a team and talk to your superiors and pass this thread on to them. to see if their superiors help with the proposals by escalating the information, and that the people who have the power of decision find out that someone brought them a proposal that could be very beneficial for them. All of these people will decide what is most convenient for the organization. They have the resources to make the best decisions. The important thing is to get the information across.

**Comment by Ing-Brayan-Martinez** [comment]
Grateful for your attention and time, I only want the best for this technology, because it is the best they have been able to invent, I am 100% convinced it is excellent

**Comment by mraleph** [comment]
Thank you for your thoughts @Ing-Brayan-Martinez. 

As has already been explained above this is not the right place for this sort of discussion, so I am going ahead and close this issue and encourage you to continue discussion on the conversationally oriented channels like Discord and Reddit.

**Comment by Ing-Brayan-Martinez** [comment]
Time has passed, and I have seen how the industry has evolved, recently Microsoft withdrew support for Android applications, and for me it is an opportunity, since the idea that I mentioned about a laptop-type device with an ARM processor, for example with the Qualcomm Snapdragon and some Z so that they can study at the university or use it to work, since Google has a large number of applications for this purpose such as Google Class Room or Google Docs, a laptop that offers the Google ecosystem is what is needed to get closer to the real economy Google is a company that has a large amount of income from advertising or other types of contracts, Google's approach to people with products that go beyond entertainment or advertising if not also for companies, work, and study according to surveys in the US, generation Z prefer to use IOS than Android, especially for the ecosystem, Google must get closer to the real economy much more than it currently does, diversify its sources of income and not only depend on advertising, the manufacturing of Hardware is an expression of real economy and wealth generation. This is essential in an environment where the federal reserve has high interest rates and money is scarce. Google recently lost 90 billion dollars due to AI image generator errors. Gemini in conclusion, the development of a laptop and the entire ecosystem around it is the evolution of Google along with AI and cross-platform development with Flutter

**Comment by miyoyo** [comment]
@Ing-Brayan-Martinez Please heed the words of the closing message and keep this discussion somewhere else, this issue is not the place for it, as nobody at Google is going to read it.

**Comment by Ing-Brayan-Martinez** [comment]
Help me with the debate https://www.reddit.com/r/dartlang/comments/1bl9rkn/propose_support_for_dart_language_in_google_cloud/
