### ISSUE TITLE
Which macro support factory method?

### ISSUE THREAD

**Issue by Solido** [dart-lang/language#3631]
I need to work on a Class factory signature `factory Class.constructor(...params)`
but I'm unable to find a compatible Macro to implements as only functions and methods
seems to be supported following lint error. 
I tried both Method__Macro and Function__Macro classes without success.

`The macro can be applied only to a function or method.`

**Comment by jakemac53** [comment]
You should be able to use any of the `Funtion_Macro`, `Method_Macro`, or `Constructor_Macro` versions. The difference is how specific you want to be in terms of what you can apply to.

However, it is very possible that the implementations are not all the way there yet, as they are still a WIP.

**Comment by Solido** [comment]
I'm well aware of the macro state. Thank you for making all this happening.
I'm reporting while also learning and testing future scenario. 

https://github.com/rodydavis/signals.dart/discussions/160

**Comment by jakemac53** [comment]
I am going to close this for now - you can assume that function/method/constructor macros should work eventually.
