### ISSUE TITLE
Implicit creation/convertion

### ISSUE THREAD

**Issue by Solido** [dart-lang/language#3634]
Is there a place to support implicit creation using a list of parameters that match
a constructor parameters? 

I would use the extension to convert [String name, int size] to an instance.

Looking for a form of reverse destructuring relying on list or tuples.

Thanks!

**Comment by jakemac53** [comment]
Can you give an example of what you mean?

There is [Function.apply](https://api.dart.dev/stable/3.3.0/dart-core/Function/apply.html), but I don't think that is quite what you are asking for.

**Comment by jakemac53** [comment]
Invoking functions with a record whose shape matches the functions parameter shape has also been discussed but I don't think there is yet a concrete proposal for it.

**Comment by Solido** [comment]
Yes I'm trying to express my code as product. Thanks for clarifying Jake!
