### ISSUE TITLE
Lower the directory depth cost of packages

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/language#3641]
#### Light packages

A light package is a package that does not require the standard `lib/src` folder structure. A single `.dart` entry point file is used while other dart files in the packages are private unless explicitly exported by the entry point.

#### Motivation

Readability: When working with multiple packages, `lib/src` adds unnecessary depth / noise that makes a folder structure harder to read. 

```
/account
   /lib
      /src
          /create_account
             create_account_form.dart
             create_account_view.dart
          /edit_account
             edit_account_view.dart
      account_module.dart   
  pubspec.yaml
/package_payment
   /lib
      /src
         /add_payment_method
            add_payment_method_view.dart
         /pay
            payment_view.dart
      payment_module.dart   
  pubspec.yaml
```

With light packages this becomes:

```
/account
   /create_account
       create_account_form.dart
       create_account_view.dart
   /edit_account
       edit_account_view.dart
   account_module.dart   
   pubspec.yaml
/package_payment
   /add_payment_method
       add_payment_method_view.dart
   /pay
       payment_view.dart
   payment_module.dart   
   pubspec.yaml
```

#### Declaring a light package

TBD. Posibilities:

  - A light package is inferred from the folder structure.
  - Alternatively add `entrypoint` to pubspec. Which would allow multiple `entrypoints`

#### Testing

Test files end with `_test.dart`. 

```
/account
   /create_account
       create_account_form.dart
       create_account_view.dart
   /edit_account
       edit_account_view.dart
   account_module.dart   
   account_module_test.dart   // <===
   pubspec.yaml
```

Test files may collocate their respective source code:

```
/account
   /create_account
       create_account_form.dart
       create_account_view.dart
       create_account_view_test.dart  // <===
   /edit_account
       edit_account_view.dart
       edit_account_view_test.dart // <===
   account_module.dart   
   account_module_test.dart   // <===
   pubspec.yaml
```

#### Note regarding meta files

When creating a package additional files are often added, which could make the entry point harder to find:

   - README.md
   - pubspec_lock.
   - analysis_options.yaml
   - ...

IDE's allow nesting those such that it looks like the following:

```
/account
   /create_account
       create_account_form.dart
       create_account_view.dart
   account_module.dart   // entry point
   > pubspec.yaml   // <== can be expanded
```

**Comment by lrhn** [comment]
There is nothing language related in this request. Everything here is convention, not rules, so all it needs is the analyzer giving different warnings.

A simple approach to avoiding `src/` could be to make libraries with a name starting with `_` be considered private, just like libraries in `src/`. Same for any content of a directory starting with `_`. It's not that you can't import them, but you can _see_ that you shouldn't, and tools can tell you if you do. No need for a new set of conventions, that can just be in addition to the current behavior.

For tests, singing similar can be used. If the test runner currently runs be every file in `test/`, it could omit any stressing with `_`. Or it could check if any file ends in `_test.dart`, and if so, ignore Ford that don't.

Removing `lib/`, and `test/`, themselves is harder. 
The `lib/` directory is the delimiter between code that others can depend on, and code that can use dev -dependencies. Without that delimiter, we can't tell the difference between helper files for the package libraries, and helper files for the test libraries (or files in `bin/` or `example/`).
I guess that's what the pubspec "entry point" entry would do, day what files are package libraries, and all files reachable from those are included in that, and should not use dev-dependencies.

It makes resolving `package:` URIs harder. Currently, `package: foo/bar.dart` resolves to the `lib/bar.dart` path of the `foo` pub package directory. If the same directory holds non-package libraries, how can a different package easily tell whether importing that file is ok. It can't, without referencing the pubspec entry point entry. (Which is doable, it's information we can store in `package_config.json`.)

It makes everything much more complicated, and I'm not sure the benefit will be that big. It's hot like the current approach is hard to understand. You may not like the subdirectories, but I like the clear delineation between things that are fundamentally different. Losing that is a real cost in packager layout readability.

**Comment by cedvdb** [comment]
> A simple approach to avoiding `src/` could be to make libraries with a name starting with `_` be considered private, just like libraries in `src/`. Same for any content of a directory starting with `_`. It's not that you can't import them, but you can _see_ that you shouldn't, and tools can tell you if you do. No need for a new set of conventions, that can just be in addition to the current behavior.


@lrhn I'd absolutely love that, but not just for packages, everywhere. This would allow emulating modules somewhat.

The rule being that the `_` folder may be imported by a direct parent but not outside of that. 

```
/a
   /_inside_a
      b.dart  
   a_,module.dart
```

**Comment by munificent** [comment]
I really don't think this proposal carries its weight.

Lightweight packages as proposed here aren't significantly lighterweight that the current package layout guidelines, and having two ways to organize a package will just add complexity to all of our tools and force users to learn two different ways of organization.
