### ISSUE TITLE
Failing analysis of macro test prevents other actions

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3656]
The Dart CI log at https://github.com/dart-lang/language/actions/runs/8084567444/job/22725574044 shows a failure during the analyzer task `dart analyze --fatal-infos .`, in working/macros/example/benchmark/src/shared.dart:91:71 and elsewhere.

This causes other tasks to remain undone (in this case: no new PDF is created for the language specification when it is updated).

@jakemac53, would it be possible to fix the example, or somehow adjust the processing such that it doesn't block other tasks?

**Comment by jakemac53** [comment]
> @jakemac53, would it be possible to fix the example, or somehow adjust the processing such that it doesn't block other tasks?

Yes we can allow it to fail, I can do that

**Comment by lrhn** [comment]
(@davidmorgan Saw the "S" label. Consider if it can be combined with the ["small-feature"](https://github.com/dart-lang/language/issues?q=is%3Aissue+is%3Aopen+label%3Asmall-feature) label.)

**Comment by jakemac53** [comment]
The goal is to have unified labels for this across repos, and these aren't so much individual language features so I don't know that small-feature is a good fit.

**Comment by davidmorgan** [comment]
Thanks @lrhn :) as Jake says I think it's different, we'd like to have S/M/L/XL for project planning.
