### ISSUE TITLE
More Concise Syntax for Multiple Conditions

### ISSUE THREAD

**Issue by tilucasoli** [dart-lang/language#3662]
# Proposal:

In Dart, the current syntax for evaluating multiple conditions within an if statement requires the use of logical operators such as `&&` or `||`. This approach, while functional, can sometimes lead to verbose and less readable code, especially when dealing with a large number of conditions.

**Current Syntax:**

```dart
if (a > 5 && a < 10) {
 // some code...
}
```

## Proposed Syntax:

To streamline the process and improve code readability, I propose introducing a new syntax that allows for a more concise representation of multiple conditions within an if statement. This new syntax would involve listing conditions separated by commas.

**Example of Proposed Syntax:**

```dart
if (
 a > 5,
 a < 10,
) {
 // some code...
}
```

**Comment by Wdestroier** [comment]
Would an extension method help?

```dart
main() {
  var a = 7;
  
  final isNumberGreaterThanFive = a > 5;
  final isNumberLesserThanTen = a < 10;
  
  if (isNumberGreaterThanFive.and(isNumberLesserThanTen)) {}
}

extension NamedAndOperator on bool {
  bool and(bool other) => this && other;
}
```

Or is it more of a formatter feature request? Possibly related to #2885.
I wrote in the comments to (possibly) allow an optional comma before closing the if statement.

**Comment by lrhn** [comment]
So this is making `,` mean `&&`, so you have two ways to write the same thing.

And it only works in `if` and `while` conditions, maybe `for`?
Pendant not a good fit for conditional expression or `when` conditions which are not parenthesized.

Also uses syntax that could potentially be used for something else, for something that already has a working syntax.

Going to be a hard sell. Benefits so small the opportunity costs alone outweigh them.

**Comment by mraleph** [comment]
This suggests replacing an obvious and well understood thing (logical and `&&`) with a unobvious thing (comma `,`). What does comma even mean? Is it logical and? Is it logical or? Is it execute-all-expressions-and-take-just-the-last-result like in JavaScript or C++? 

I think this is not just a hard sell - it is pretty much a no-go. `&&` is clearly more readable then `,`. 

If condition is so complicated that it becomes hard to read - then the best strategy is to split it into variables instead.

**Comment by Mike278** [comment]
You could also write your example as:

```dart
if (a case > 5 && < 10) {
 // some code...
}
```

**Comment by MohiuddinM** [comment]
@tilucasoli wouldn't the pythonic way be better?
```
if (5 < a < 10) {
 // some code...
}
```

**Comment by MohiuddinM** [comment]
I think what @tilucasoli wants is the formatting because in Dart the commas are also used to nicely format across multiple lines. But I think formatting does not require any language changes and can be made to work with `&& `and `||` too just like commas.

**Comment by tilucasoli** [comment]
I concur with your perspective on the use of the comma `,` as an alternative to the `&&` operator. But what do you think 
if we use the comma operator as a new way to casting and unwrap optional values. Consider the following example:

```dart
void main() {
  Bar a = Foo();

if (
  a is Foo,
  a?.name == 'Bar' // Conditional check
) {
  // Inside this block, 'a' is promoted to 'Foo'
  // and can be used as such.
  print(a.name); // This is now safe and type-checked.
  } 
}

class Bar {}

class Foo extends Bar {
 String? name;
}


```

In this scenario, the comma operator allows for a more easier control flow. Unlike the `&&` operator, which evaluates both conditions together, the comma operator evaluates each condition separately. This means that after the type check `(a is Foo)`, the variable `a` is promoted to the type `Foo` within the scope of the if block. This promotion allows for the safe use of `a` as a `Foo` instance, enabling type-checked access to its properties and methods.

It simplifies the code by eliminating the need for explicit type casting or additional variable declarations.

@mraleph

**Comment by mateusfccp** [comment]
You can do the same with

```dart
void main() {
  Bar a = Foo();

  if (a case final Foo a when a.name == 'Bar') {
    // Inside this block, 'a' is promoted to 'Foo'
    // and can be used as such.
    print(a.name); // This is now safe and type-checked.
  } 
}

class Bar {}

class Foo extends Bar {
  String? name;
}

```

**Comment by munificent** [comment]
I'm going to close this out because I don't see it working out.
