### ISSUE TITLE
Performance cost of .every() vs loops?

### ISSUE THREAD

**Issue by yakagami** [dart-lang/language#3669]
I was reading this issue (https://github.com/flutter/flutter/issues/144156) in the flutter repo about using .every() in certain cases in the framework. Here's an example:

```dart

// before
bool visitDirectChildren(InlineSpanVisitor visitor) {
  final List<InlineSpan>? children = this.children;
  if (children != null) {
    for (final InlineSpan child in children) {
      if (!visitor(child)) {
        return false;
      }
    }
  }
  return true;
}


// after
bool visitDirectChildren(InlineSpanVisitor visitor) {
  return children?.every((InlineSpan child) => visitor(child)) ?? true;
}

```

In that issue, I found out that there could be (perhaps small) performance costs of using .every() vs. using loops. I would like to know if the compiler does or is potentially able to convert .every() to using loops and avoiding extra method calls and if so are there guarantees on when it will or will not be converted?

edit: looking at the implementation, this is just a question of inlining, right? And there should never be a reason for this function not to be inlined, right? Or am I missing something about when the compiler inlines functions?

implmentation: (as per https://api.flutter.dev/flutter/dart-core/Iterable/every.html)

```dart

bool every(bool test(E element)) {
  for (E element in this) {
    if (!test(element)) return false;
  }
  return true;
}

```

**Comment by Wdestroier** [comment]
The compiler might not be able to inline the method. Take a look at the following example:

```dart
import 'dart:math';

main() {
  Iterable<int> normalIterable = [1, 2, 3];
  Iterable<int> customIterable = MyIterable<int>();

  Iterable<int> it = Random().nextBool() ? normalIterable : customIterable;

  // Which is the implementation of every?
  print(it.every((element) => element > 0));
}

class MyIterable<E> extends Iterable<E> {
  @override
  Iterator<E> get iterator => _MyIterator<E>();

  @override
  bool every(bool test(E element)) => false;
}

class _MyIterator<E> implements Iterator<E> {
  E? _current;

  @override
  E get current => _current!;

  @override
  bool moveNext() => false;
}

```

**Comment by yakagami** [comment]
@Wdestroier Thanks for that insight. This is only an issue because we override `every`, correct? Do we know that it will inline `every` in the general case? Are there conditions where the compiler can prove that `every` is defined the same way? If so what conditions are necessary?

**Comment by munificent** [comment]
@lrhn is right. The short answer is, no, the language spec does not make performance guarantees about inlining (or much of anything, really). Whether the compilers in fact *do* inline some construct is an implementation detail that may change over time. There's no timeless guidance we can give about which constructs are faster than which others.

The only way to win the performance game is by profiling your actual code with an actual compiler. Everything else is guesswork.

I'm going to go ahead and close this issue because it was just a question. Thanks for bringing it up. :)
