### ISSUE TITLE
Require augmentation libraries to link to their main library, not the parent

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3675]
Consider the following library / augmentation library structure:

```dart
// --- Library 'a.dart'.
import augment 'b.dart';
import augment 'd.dart';

// --- Augmentation library 'b.dart'.
augment library 'a.dart';
import augment 'c.dart';

// --- Augmentation library 'c.dart'.
augment library 'b.dart';

// --- Augmentation library 'd.dart'.
augment library 'a.dart';
```

The current feature specification requires each node in the tree of augmentation libraries under a given augmented library to have a parent edge (which is shown as a dotted line in the figure), and it must be the inverse of an `import augment` edge in the parent:

```mermaid
graph TD;
  alibB --> alibC[c.dart]
  alibB -.- alibC
  main --> alibB[b.dart]
  main -.- alibB
  main --> alibD[d.dart]
  alibD -.- main[a.dart]
```

The augmentation library tree (that is, the arrows, based on the `import augment` directives) uniquely determines the order of the augmentations when the textual order inside each file is taken into account. Hence, the `augment library` directive is not needed in order to determine the ordering of the augmentations.

Conversely, the dotted edges (considered as arrows going upwards, based on the `augment library` directives) uniquely define the main library which is being augmented by each of the augmentation libraries.

I believe we're free to change the rules such that the `augment library` edges can go directly to the root, and this wouldn't change the semantics of the multi-file entity consisting of a library and some augmentation libraries.

```mermaid
graph TD;
  alibB --> alibC[c.dart]
  main -.- alibC
  main --> alibB[b.dart]
  main -.- alibB
  main --> alibD[d.dart]
  alibD -.- main[a.dart]
```

This changes only one directive (hence also only one edge in the graph):

```dart
// --- Augmentation library 'c.dart'.
augment library 'a.dart';
```

If we do this then we will have more freedom in the usage of the augmentation libraries. For example, we can replace internal nodes in the tree without editing more than one directive in the immediate parent:

```mermaid
graph TD;
  alibB --> alibC[c.dart]
  main -.- alibC
  main --> alibB[alternate_b.dart]
  main -.- alibB
  main --> alibD[d.dart]
  alibD -.- main[a.dart]
```

The rules may also be conceptually simpler because an `augment library` directive will always denote the _library_ which is being augmented, it will never denote another augmentation library, and said library is the library which is actually being augmented. Also, in order to understand the role played by any given augmentation (in particular, it's location in the ordering) it is necessary to find the root and compute the entire augmentation tree from there anyway.

**Comment by eernstg** [comment]
@dart-lang/language-team, WDYT? This structure seems more "modular" and flexible to me than the one which is created by the current rules, and I can't see that we are missing out on any expressive power by doing it.

**Comment by jakemac53** [comment]
I had this same thought when recently reading over this part, during the change to using the `library augmentation` terminology. I think it makes sense.

**Comment by jakemac53** [comment]
The downside I think is that if starting somewhere deep in the tree, it is difficult to figure out how that augmentation is applied. You can't follow it up the tree, only directly to the root, and then have to figure out your own way down.

**Comment by eernstg** [comment]
> You can't follow it up the tree,

True, but perhaps you'd need to compute the entire tree top-down anyway, in order to understand what's actually going on?

**Comment by jakemac53** [comment]
> True, but perhaps you'd need to compute the entire tree top-down anyway, in order to understand what's actually going on?

To get a full picture, sure, but to get a picture of exactly how the augmentation you are looking at is applied, I don't think so.

**Comment by davidmorgan** [comment]
I think the existing two-way link structure may work better from a UX point of view?

In the one-way link structure, if write a backwards link `c -> a` but do not add any direct or indirect link `a -> c`, the error message would have to say "please add some chain of forward links a -> c", which is not easily actionable because we can't tell you what file you should change.

**Comment by eernstg** [comment]
> if write a backwards link `c -> a` but do not add any direct or indirect link `a -> c`, the error message would have to say "please add some chain of forward links `a -> c`", which is not easily actionable because we can't tell you what file you should change.

Well, if you just add a backwards link to the intended parent (which would then be an augmentation library, say, `b`) and that parent isn't reachable from `a` then `c` will not be reachable anyway, and there's no error message to tell you about this issue.

So the error about a missing path from `a` to `c` may be harder to deal with, but it might actually be an improvement over the situation where every backwards link is to the direct parent.

**Comment by scheglov** [comment]
IIRC one of the motivations for augmentation libraries was that with `augment library 'b.dart';` you guarantee that the augmentation `c` is included exactly once, into `b`. Because you have to have this bi-directional link `b <-> c`. If we now allow / require `augment library 'a.dart'` (reference the library), you could have another `import augment 'c.dart';` inside the augment `b2`. This would require additional check that library augmentations are imports exactly once.

And already mentioned UX. I think it is surprising when the parent/child link is bi-directional, but not symmetric.

**Comment by eernstg** [comment]
> you guarantee that the augmentation `c` is included exactly once

Right. It would be a compile-time error anyway if `c.dart` contains at least one declaration which isn't an augmentation (there would be a name clash if a declaration with a given name `n` is added more than once to the same scope, and `c.dart` can't avoid doing that unless _everything_ in there is `augment` something). Hence, it's very unlikely that we'd want to support multiple inclusions of the same augmentation library into the same augmented library: In the end it should be a compile-time error, somehow.

It wouldn't be difficult, though, to make it a compile-time error if an augmentation library like `c.dart` occurs more than once in the tree of augmentation libraries under any given main library. So from that point of view we don't need the bi-directional `b <-> c` links, we can certainly have those errors either way.

> it is surprising when the parent/child link is bi-directional, but not symmetric.

This argument is more conceptual, and it would be more important and relevant to developers (I think).

However, we could also pose the opposite argument, still based on a conceptual perspective: It's confusing that a bunch of augmentation libraries _seem_ to be divided into the ones that are augmenting each other and the ones that are augmenting the main library, when the actual semantics is that they are all augmenting the main library. Besides, it's simply a conceptual misalignment if `c.dart` contains `augment library 'b.dart';`, and `b.dart` isn't a library in the first place!

Also, still with an emphasis on the conceptual perspective, for a developer who is reading the code of an augmentation library and trying to understand what it's doing &mdash; wouldn't it be necessary to find the main library and take the entire tree into account anyway?

---

The starting point for this proposal was actually the fact that a structure (1) which has a tree (down-arrows) together with uplinks to the root is equivalent to a structure (2) that has the same tree plus uplinks to the parent (if you have the former then it uniquely determines the latter, and vice versa).

However, the structure (1) that has root uplinks is more flexible than the structure (2) that has parent uplinks: We can reorganize the (1) tree arbitrarily without invalidating the root uplinks, but every change to the (2) tree would require a 1:1 set of changes to the parent uplinks.

I thought that the enhanced flexibility/simplicity could be convenient, e.g., during code generation.

**Comment by davidmorgan** [comment]
I believe this is obsolete with #3848 which removes augmentation libraries in favour of parts.

**Comment by davidmorgan** [comment]
Alternatively, if there is a related consideration for nested parts, please express it on #3848 and/or the PR linked from there :)
