### ISSUE TITLE
Augmentation of extensions seems to be difficult

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3687]
Thanks to @sgrekhov for bringing up this topic. Consider the following example:

```dart
// --- Library 'a.dart'.
import augment 'b.dart';

extension on int {...}
extension on String {...}

// --- Augmentation library 'b.dart'.
augment library 'a.dart';

augment extension {...}
```

First, we have

> It is a compile-time error if: ...
> - An augmenting extension declares an `on` clause.

so we can't have `augment extension on T ...` for any `T`. However, it's a syntax error if we _don't_ have an `on` clause. So, apparently, we just can't have an `augment` of an `extension` at all.

Next, if the extension is anonymous then it is considered to have a fresh, private name. This means that an anonymous extension augmentation will (presumably?) also have a fresh private name, which again implies that it never matches any other declaration (including any anonymous extensions or other extension augmentations).

In response to these considerations, I'd recommend that we make it an error to have an anonymous `augment extension` declaration. Moreover, we should change the grammar to allow an `augment extension` declaration to omit the `on` clause.

(We could also allow the `augment extension` declaration to have an `on` clause which is identical (in some sense) to the one which is given in the corresponding `extension` declaration, but that seems inconsistent with the treatment of other clauses in `augment` declarations.)

@dart-lang/language-team, WDYT?

**Comment by lrhn** [comment]
The grammar of `augment extension` should probably be tweaked to not have the `on` clause:
```ebnf
<extensionDeclaration> ::= 
   ( 'augment' 'extension' <typeIdentifierNotType> 
  | 'extension' <typeIdentifierNotType>? 'on' <type>)
     '{' (<metadata> <classMemberDeclaration>)* '}'
```
Which means only augmenting named extensions and without specifying an `on` clause.

**Comment by jakemac53** [comment]
> In response to these considerations, I'd recommend that we make it an error to have an anonymous `augment extension` declaration.

SGTM, even with `on` we couldn't reasonably match up extension augmentations without an explicit name, there could be multiple anonymous ones in the library with the same on type.

> The grammar of augment extension should probably be tweaked to not have the on clause:
> Which means only augmenting named extensions and without specifying an on clause.

The suggested grammar changes LGTM

**Comment by eernstg** [comment]
The difficulties raised in this issue have all been addressed in the following PR: https://github.com/dart-lang/language/pull/3701.

It changes the syntax of augmenting extension declarations such that they must have a name and cannot have an `on` clause. This means that the contradiction ("an `on` clause is a compile-time error and a missing `on` clause is a syntax error") is resolved, and the things we want to avoid are now syntax errors.

I'll close this issue because further discussions about this topic are handled as reviews on the PR.
