### ISSUE TITLE
What does `augment` mean when applied to an `enum` value?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3689]
[This section](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/feature-specification.md#augmenting-enum-values) specifies augmentation of `enum` values. However, it isn't obvious to me how we should understand an `augment` declaration of an `enum` value.

The occurrence of `augment first` in `augment enum A` in `a.dart` seems to fit this part of the description:

> An augmenting enum value is allowed to invoke a different constructor than the original enum value, or provide an argument list where none was present before.

We can include support for the special case where the `augment <identifier>` declaration doesn't actually specify a _different_ constructor, but just re-states that we should use the constructor which is already implied by the declaration in `main.dart`. If we do that then `augment first` is allowed. It doesn't _do_ anything, it just restates what was already specified in `main.dart`, but it also doesn't hurt (and it isn't inconsistent with other rules &mdash; for example, we can replace one method declaration by another one which is exactly identical).

However, the occurrences of `augment third` and `augment fourth` are confusing: They seem to augment existing declarations of values named `third` and `fourth`, but there are no such existing declarations. Perhaps they were intended to be a plain `third` and `fourth`, so we should simply delete those two occurrences of `augment`?

We might also add an example where the ability to invoke a different constructor is used, or the ability to pass different actual arguments to a constructor (the same or a different one).

In passing, the ability to switch from calling one constructor to calling another one (or the same one) with different actual arguments seem to be inconsistent with the general nature of augmentations: It discards some existing elements of a declaration, rather than just adding some previously missing ones. In that sense it's an "update existing knowledge" mechanism, rather than a "discover previously hidden knowledge" mechanism.

```dart
// --- Library 'main.dart'.
import augment 'a.dart';

enum E {
  one(true);
  const E(bool b);
}

// --- Augmentation library 'a.dart'.
augment library 'main.dart';

augment enum E {
  one(false); // Haha, thought it was `true`? Now it's `false`!
}
```

One way to simplify the situation would be to say that augmentations of `enum` values is impossible, an `enum` declaration can only be augmented by having new values added, and/or by having new members added or existing members augmented.

@munificent, @jakemac53, WDYT?

**Comment by jakemac53** [comment]
> However, the occurrences of `augment third` and `augment fourth` are confusing: They seem to augment existing declarations of values named `third` and `fourth`, but there are no such existing declarations. Perhaps they were intended to be a plain `third` and `fourth`, so we should simply delete those two occurrences of `augment`?

That sounds correct to me, those are new values and should not have `augment`, so we should just remove those.

> We might also add an example where the ability to invoke a different constructor is used, or the ability to pass different actual arguments to a constructor (the same or a different one).

Agreed we should add those.

> In passing, the ability to switch from calling one constructor to calling another one (or the same one) with different actual arguments seem to be inconsistent with the general nature of augmentations: It discards some existing elements of a declaration, rather than just adding some previously missing ones. In that sense it's an "update existing knowledge" mechanism, rather than a "discover previously hidden knowledge" mechanism.

I do tend to agree with this... I think the reason this capability was added is because there is an implicit invocation of the default unnamed constructor when you write a simple enum:

```dart
enum A {
  first;
}
```

And we wanted to allow a macro to be able to run on an enum like this, add some state (via fields) to the enum, a constructor which initializes that state, and then also update all the enum values to call that new constructor and pass in some value for those new fields.

But, maybe we could more explicitly call out exactly this scenario? Basically only allow you to add an argument list and constructor invocation where there was no explicit one at all previously?

> One way to simplify the situation would be to say that augmentations of `enum` values is impossible, an `enum` declaration can only be augmented by having new values added, and/or by having new members added or existing members augmented.

Honestly, I am probably fine with this choice too.
