### ISSUE TITLE
Inference of the declared type in a for-in statement differs from local variable declarations

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3696]
Consider the following program:

```dart
X whatever<X>() {
  print(X);
  return const <Never>[] as X;
}

void main() {
  for (final item in whatever()) {
    // item.doesNotExist(); // Error: the type of `item` isn't `dynamic`.
    item.expectStaticType<Exactly<Object?>>();
    // int i = item; // Error message confirms `Object?`.
  }
  
  final item = whatever();
  if (2 < 1) item.doesNotExist(); // OK: the type of `item` is `dynamic`.
}

typedef Exactly<X> = X Function(X);

extension<X> on X {
  X expectStaticType<Y extends Exactly<X>>() => this;
}
```

This program is accepted by the CFE as well as the analyzer, and the lines that are commented out have compile-time errors as stated in the comments.

This shows that a local variable is inferred to have type `dynamic` when no type annotation is given and the initializing expression can be inferred to have any type whatsoever, and the iteration variable of a for-in statement is inferred to have type `Object?`.

Is this difference intended? Is it useful? We could of course say "fewer situations where a type is `dynamic` is better, no matter what", but we have also used the opposite kind of reasoning, "let's be consistent first, and then later fix what we don't like simultaneously everywhere".

@dart-lang/language-team, WDYT?

**Comment by lrhn** [comment]
The difference is that `for`/`in` introduces a non-empty context type scheme for `whatever()`, where the variable does not.
(I can't find the specification for what the context type of the iterable expression of a `for`/`in` should be, though.)

The context type scheme seems one whose greatest closure is `Iterable<Object?>`.
```dart
void main() {
  // Compile-time error if catured context type is not `Iterable<Object?>`.
  for (var i in context(<Never>[])..chk(const Chk(TypeOf<Iterable<Object?>>))) {}
}
T context<T>([Object? value]) => value as T;
extension<T> on T {
  void chk(Chk<T> _) {}
}
class Chk<T> {
  const Chk(Type? typeId) : assert(identical(T, typeId));
}
typedef TypeOf<T> = T;
```

The `Iterable<Object?>` is most likely the greatest closure of `Iterable<_>`, which was found by taking the context type induced by the variable declaration and wrapping it in `Iterable<...>`.

**Comment by eernstg** [comment]
You're right, there is a significant difference between those two usages of `whatever()`, and in the relationship to the inferred type of the final variable `item`.

If we change the original example with adjustments that are intended to compensate for those differences, we get the same inferred type for `item`:

```dart
X whatever<X>() => const <Never>[] as X;

void main() {
  for (final item in [whatever()]) {
    if (2 < 1) item.doesNotExist(); // OK: the type of `item` is `dynamic`.
  }

  final item = whatever();
  if (2 < 1) item.doesNotExist(); // OK: the type of `item` is `dynamic`.
}

typedef Exactly<X> = X Function(X);

extension<X> on X {
  X expectStaticType<Y extends Exactly<X>>() => this;
}
```

I'll close the issue: I no longer think there's anything surprising about the observed behavior.

By the way: That `..chk(const Chk(myType))` approach is nice! ;-)
