### ISSUE TITLE
[Feature Request] Can we have syntactic sugar for calling super constructors?

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/language#370]
To make calling super constructors more beautiful, can we have this syntactic sugar?
Instead of:
```dart
class TextChatMessage extends ChatMessage{
 TextChatMessage({
    @required Timestamp timestamp,
    @required String senderId,
    @required this.body,
    DocumentReference documentReference,
  }) : super(
            messageType: MessageType.string,
            senderId: senderId,
            timestamp: timestamp, documentReference:documentReference);
}
```
I would like to be able to write:
```dart
class TextChatMessage extends ChatMessage{
 TextChatMessage({
    @required super.timestamp,
    @required super.senderId,
    @required super.body,
    this.documentReference,
  }): super(messageType: MessageType.string); // since this type of constructor will still be an option and this variable is hard-coded and not optional.
}
```

One could say "well you're still using the `super()` syntax so what's the difference?"
To that I'd say true, but using `this.messageType` in constructors is also syntactic sugar, but not a requirement either.

**Comment by natebosch** [comment]
What happened to `messageType` in the new version?

**Comment by ThinkDigitalRepair** [comment]
> What happened to `messageType` in the new version?

I forgot to put it in. 😄 I'll edit it

**Comment by mdebbar** [comment]
There's a similar issue here: https://github.com/dart-lang/language/issues/57
It would be nice to add your idea in there :)

**Comment by ThinkDigitalRepair** [comment]
> There's a similar issue here: #57
> It would be nice to add your idea in there :)

I was about to, but it's only related and not the same

**Comment by lrhn** [comment]
The behavior of such a short-hand should be *predictable*.
When we write:
```dart
TextChatMessage([super.timestamp, super.senderId, super.body} : super(messageType: ...);
```
it's fairly easy to define the behavior because the order of named arguments are unimportant. We can just append the super-arguments to get:
```dart
TextChatMessage([super.timestamp, super.senderId, super.body} : super(messageType: ...,
  timestamp: timestamp, senderId senderId, body: body);
```

It gets a little more complicated with positional parameters. Should the `super.x` parameters be prepended or appended to the super-invocation?

If appended:
```dart
 Gizmo(String name, super.price, super.cost) : super("Gizmo: $name");
```
would become
```dart
 Gizmo(String name, super.price, super.cost) : super("Gizmo: $name", price, cost);
```
If prepended, it would become:
```dart
 Gizmo(String name, super.price, super.cost) : super(price, cost, "Gizmo: $name");
```
Either makes sense. I'd say prepending is probably the best choice. Then a sub-class constructor would start with the same arguments as the super-class constructor, and extend it with more details.
It only works up to the first super-constructor argument that you need to modify instead of forward, after that, everything must be manual again.

Named parameters are easy :)

If you just want to forward *all* super-class parameters, then perhaps you can do:
```dart
  final String damageType;
  Gizmo(super, this.damageType);
```
and then `super` represents *all* super-parameters, named and positional (then you are currently restricted to not adding optional positional parameters if the superclass has a named parameter).

**Comment by eernstg** [comment]
https://github.com/dart-lang/language/blob/master/working/1855%20-%20super%20parameters/proposal.md may be relevant here.

**Comment by Levi-Lesches** [comment]
From that document: 

> ##### Desugaring
> 
> This was specified without trying to desugar into existing valid Dart code.
>
> We *can* desugar the desired behavior into existing Dart code, but that requires some amount of rewriting in the constructor body to enforce the “initializer-only” scope of variables introduced by initializing formals and super parameters. Example:
>
> ```dart
> C(super.x, this.y, {required super.z}) : super.foo() {
>   something(x, y, z);
> }
> ```
>
> *could* be (re)written as:
>
>```dart
>C(final TypeOfX x, final TypeOfY y, {final required TypeOfZ z}) 
>    : this.y = y, super(x, z: z) {
>  something(this.x, this,y, this.z);
>}
>```
>
>The change of `x, y, z` to `this.x, this.y, this.z` is necessary to ensure the body code still references the instance variables, not the newly-introduced “normal” parameters which are visible in the body unlike the variables introduced by initializing formals and, now, super-parameters.
>
>We so far prefer to avoid doing that kind of non-local rewriting, which means that we will need to treat this as a feature by itself, not something that can easily be “lowered” to existing code.

Specifically,
>The change of `x, y, z` to `this.x, this.y, this.z` is necessary to ensure the body code still references the instance variables, not the newly-introduced “normal” parameters which are visible in the body unlike the variables introduced by initializing formals and, now, super-parameters.

To clarify, is this what's being referred to?
```dart
class A {
  int x;
  bool z;
  A.foo(this.x, {required this.z});
}

class B extends A {
  String y;
  
  /// override A.x
  @override
  int get x => super.x + 1;
  
  // B(super.x, this.y, {required super.z}) : super.foo() {
  //   something(x, y, z);
  // }
  //
  // Translates to:
  B(x, this.y, {required z}) : super.foo(x, z: z) {
    something(x);       // the parameter of the constructor
    something(this.x);  // the getter
  }
  
  void something(int a) => print(a);
}

void main() {
  A b = B(42, "Hello, World!", z: true);  // prints 42 then 43
}
```

**Comment by eernstg** [comment]
No the point is that initializing formals (`this.y`) and super formals (`super.x`, `super.z`) induce a final local variable into the initializer list scope, which means that you can read their value using `x`, `y`, `z` in the initializer list. But in the _body_ of the constructor those local variables are not in scope, and this means that a reference to `x` in the body refers to the instance variable, not the local variable, and similarly for `y` and `z`.

Cf. https://github.com/dart-lang/language/blob/0f77128298ab2252494157b044490aaa13ada9aa/specification/dartLangSpec.tex#L3612.

**Comment by tolotrasamuel** [comment]
Isn't this already implemented?

**Comment by lrhn** [comment]
It is!
