### ISSUE TITLE
Some questions about augmentation errors

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3702]
Thanks to @sgrekhov for bringing up this issue!

The library augmentation feature specification does not seem to specify that there must be a compile-time error in situations like the following:

```dart
// Library 'main.dart'.
import augment 'augment.dart';

class C {
  void f(); // Allowed when implemented in augmentation.
}

// Library augmentation 'augment.dart'.
augment library 'main.dart';

augment class C {
  augment void f() {
    augmented(); // Compile-time error (not specified).
  }
}
```

This situation is similar to a superinvocation of a method where the superclass does not have an implementation of said method. The situation is fully known at compile-time so we should get a compile-time error (not an exception at run time).

We do have a suitable compile-time error in the case where a variable/getter/setter is augmented, [here](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/feature-specification.md#augmenting-variables-getters-and-setters), but the error should presumably be specified (using essentially the same words) in the section about augmenting functions.

Conversely, the section about augmenting variables/getters/setters has the following error:

> An `abstract` or `external` variable are augmented by a variable.

I'd say that the `abstract` case could be allowed: It should arguably be treated like an abstract getter declaration if `final`, and otherwise like an abstract getter and an abstract setter declaration, and they should certainly allow for an augmentation that adds a regular (`get` / `set`) implementation.

But why wouldn't we allow a variable declaration to be considered as a getter declaration with an implementation (plus a setter declaration with an implementation, if non-`final`)?

You could argue that this would bring up some less straightforward situations:

```dart
// Library 'main.dart'.
import augment 'augment.dart';

class C {
  abstract final int v1;
  abstract int v2;
  abstract final int v3;
}

// Library augmentation 'augment.dart'.
augment library 'main.dart';

class C {
  augment final int v1; // OK.
  augment final int v2; // OK, augments the getter.
  // Some other augmentation can augment the setter, should be OK.
  augment int v3; // Augments the getter, OK, but adds the setter (not OK?)
}
```

I'd tend to say that the straightforward cases should be allowed, and the questionable ones (like `augment int v3`) should be errors. But this is still more permissive than the current specification.

@jakemac53, @munificent, WDYT?

**Comment by lrhn** [comment]
About:
> An `abstract` or `external` variable are augmented by a variable.

We really need "declaration" after all those "variable"s.

It also suggests that one cannot augment an `abstract int x;` with `@metadata augment abstract int x;`, which does nothing but add metadata. That seems unnecessarily strict.

An abstract variable declaration is (syntactically) a variable declaration. It doesn't introduced a *variable*, which is probably confusing.

No matter how we do this, we need to have consistent phrasing for what we're working on, and I think it's mainly declarations, not their semantic meaning (which doesn't necessarily exist until all augmentations are applied).

**Comment by eernstg** [comment]
> We really need "declaration" after all those "variable"s.

True, I just added them to the PR in #3703.

**Comment by eernstg** [comment]
#3703 has now been landed.
