### ISSUE TITLE
Question: can augmentation define the rest of the method body?

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/language#3708]
To access variables defined in the method:

```dart
class AuthComponent {
  @Template('auth.html')
  augment void render(RenderContext context) {
    var user = context.provide<User>();
    var fullName = user.fullName;
    // the augmented body is generated from a template that uses the fullName variable
  }
}
```

**Comment by jakemac53** [comment]
No, an augmenting function cannot reference local variables from the function it augments. It is a _replacement_ for the function, with the ability to call back into the original function (sort of similar to an override and a super call).
