### ISSUE TITLE
404 link in macro spec

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/language#3709]
https://github.com/dart-lang/language/blob/badfd9c3baa5750fac54fc34203052178e4c829b/working/macros/feature-specification.md?plain=1#L647

![image](https://github.com/dart-lang/language/assets/111139605/d70ea6ea-959d-436d-9b21-3dafb989fc06)

Maybe just https://github.com/dart-lang/sdk/tree/main/pkg/_fe_analyzer_shared/lib/src/macros ?

**Comment by jakemac53** [comment]
Ah yes, thanks :). We moved these libraries a little bit ago.
