### ISSUE TITLE
448/5 = Dart Library is yielding a value of 89.60000000000001 ?? Why ?? What to do ?

### ISSUE THREAD

**Issue by pk-szt** [dart-lang/language#3733]
Include a permanent link to the error if possible.

void main (){
var student2 = Student();
  student2.percentage= 448; 
  print(student2.percentage);
  }
  
  class Student{
  double? _percent; 
  set percentage(double marks) => _percent = (marks / 500) * 100;
  double get percentage => _percent ?? 0;
}

**Comment by KinectTheUnknown** [comment]
It's just how the IEEE-754 specs are for floating point representation. You'll come across this in any language/compiler that follows this specification. Imo, the best solution is to avoid floats and use ints. For example, instead of representing USD in dollars, use cents.

**Comment by lrhn** [comment]
Agree. This is well documented behavior, and you'll see the same behavior in every other language that uses floating point numbers.

**Comment by mraleph** [comment]
Recommended reading: https://floating-point-gui.de/
