### ISSUE TITLE
Delegating constructors

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/language#3747]
Today on the `collection` package we need a [`DelegatingList<E>`](https://api.flutter.dev/flutter/package-collection_collection/DelegatingList-class.html) class. All it does is receive a list and, as the name suggests, delegate all calls to methods, getters, setters and such to that specific list.

This week I had the same problem/need but with a `FocusNode` class. And I had to delegate 48 getters and setters to a base `FocusNode`. I'd like to propose a delegating constructor of sorts.

I imagine the syntax to be something like:

```dart
class A extends FocusNode {
  A(FocusNode f) : super = f;
}
```

**Comment by FMorschel** [comment]
I _think_, I found what you were talking about https://github.com/dart-lang/sdk/issues/31483 (which being in the SDK could be why you didn't find it). I found the mention on #418 which is _similar_ but I don't think this is the exact thing.

Should I move this discussion to one of those issues if they're what you were thinking?

**Comment by lrhn** [comment]
I moved (now numbered) #3748 into the language repo, so let's defer to that.
