### ISSUE TITLE
Clarify cyclic dependency error for type aliases

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#375]
The language specification has the [following](https://github.com/dart-lang/language/blob/0e6111c01e7f35ad358c01570e5c865bd5269ce3/specification/dartLangSpec.tex#L14420):

```
Any self reference in a type alias,
either directly or recursively via another type declaration,
is a compile-time error.
```

This is ambiguous, because it could be taken to include cycles containing classes:

```dart
// Case 1.
class C<X> {
  A a;
}
typedef A = C<int>;

// Case 2.
class D<X extends B> {}
typedef B = D<Null>; // With NNBD: `D<Never>`.
```

Case 1 should definitely not be considered to be a dependency cycle; but case 2 rewrites in just one step to a form where `B` is never used (`D<X extends D<Null>>`), so that is also not required to be a cyclic dependency error.

The property that we wish to guarantee is that the rewriting system defined by type aliases can be run and will complete in finitely many steps (yielding a program with no type aliases, because they have all been "inlined").

This issue is concerned with finding a suitable measure which is guaranteed to strictly decrease for each rewrite step (that is, each time we replace `A<T1 .. Tk>` by `[T1/X1 .. Tk/Xk]B`, where `B` is the body of the type alias named `A` and `X1 .. Xk` are its formal type parameters).

**Comment by eernstg** [comment]
The following measure will work: For a type alias name _A_ and a term _t_ derived from `<type>`, let _size<sub>A</sub>(t)_ be the list of natural numbers _[m<sub>n</sub>, ..., m<sub>1</sub>, m<sub>0</sub>]_ such that _m<sub>0</sub>_ is the number of occurrences of _A_ at level 0 (which is just the identifier _A_, with no type argument list), _m<sub>1</sub>_ is the number of occurrences of _A_ at level 1 (an occurrence at level 1 is of the form _A&lt;id<sub>1</sub>, ... id<sub>n</sub>&gt;_ where _n >= 0_ and each _id<sub>j</sub>_ is an identifier), and so on, and _m<sub>k</sub> &gt; 0_.

*For example, for the type alias name `A` and the term `A<A<int>>`, the size for `A` is `[1,1,0]` and for `List<int>` the size for `A` is `[]`.*

Sizes are ordered lexicographically.

*For example, `[2] > [1]` and `[2, 0] > [1,1] > [1000000000] > [1] > []`, and `[]` is the least element.*

The measure is guaranteed to decrease for each rewrite step, that is:

Assume that `A` is a type alias name declared as

```dart
typedef A<X1 extends B1 ... Xk extends Bk> = B;
```

and `A<T1 .. Tk>` is a type term with size _[m<sub>n</sub>, ..., m<sub>1</sub>, m<sub>0</sub>]_. We know that _n_ is the syntactic depth of type argument lists (that is, the nesting depth of `<...>`) because there is an `A` at the top level, and everything in `T1 .. Tk` has a strictly lower nesting level than _n_.

The output from the rewriting step is `[T1/X1 .. Tk/Xk]B`. Given that Dart type variables cannot be higher-order, it is guaranteed that every occurrence of `Xj` in `B` is at level 0 (*that is, a type variable can only occur as a plain identifier, it doesn't have type arguments*). This means that `Tj` for all `j` occur at the same level before and after the rewrite, so each of the occurrences of `A` in there will contribute the same amount to the size as before (same level, same count). However, each `Xj` may occur zero or more times in `B`. So the new size will be _[s<sub>n-1</sub>*m<sub>n-1</sub>, ..., s<sub>1</sub>*m<sub>1</sub>, s<sub>0</sub>*m<sub>0</sub>]_, where _s<sub>j</sub>_ is a natural number, counting the number of occurrences of `Xj` in `B`. This is strictly smaller than before the rewrite because the highest level is now gone (that is, it is zero).

The crucial point is that the rewrite steps from `A<T1 .. Tk>` cannot produce anything that contains `A<S1 .. Sk>` with the same or bigger size in a positive number of steps, and this is ensured by defining a cyclic dependency constraint which basically says that `A` cannot occur in the body of `A` or in the body of any typedef `A1` which occurs in the body of `A`, plus a transitive closure which ensures that this also cannot happen indirectly.

**Comment by lrhn** [comment]
The rule sonuds very complicated. How about:

> A type alias *A* with type expression *T* **references** a type alias *A*<sub>2</sub> with name *id*<sub>2<.sub> if either:
> * *id*<sub>2</sub> occurs in in *T* denoting the type alias *A*<sub>2</sub>, or
> * an identifier *id*<sub>3</sub> occurs in *T* denoting a type alias *A*<sub>3</sub> and *A*<sub>3</sub> **references** *A*<sub>2</sub>.

With that definition, we then say:

> It is a compile time error if a type alias *A* references itself.

This avoids all talking about expanding the definitions, but it still guarantees that we don't have any cyclic structural type definitions.

**Comment by eernstg** [comment]
> How about a rule stated like;

> A type alias *A* with type expression *T* **references** a type alias *A*<sub>2</sub> with name *id*<sub>2</sub> if either:
> * *id*<sub>2</sub> occurs in in *T* denoting the type alias *A*<sub>2</sub>, or
> * an identifier *id*<sub>3</sub> occurs in *T* denoting a type alias *A*<sub>3</sub> and *A*<sub>3</sub> **references** *A*<sub>2</sub>.

That's very much the kind of rule that I'd use (where `T` would be the body of the type alias when it is expressed in the form that uses `=`).

I did not spell out the rule, but that was because I was focusing on establishing a sufficiently precise sketch of a proof to be able to conclude that it is indeed sufficient for termination of the expansion of type aliases that we constrain the program to not have such cycles. When we have reached that conclusion then all the 'size' stuff is pure background material.

Fun fact: this means that there is no need to constrain the use of the type alias `A` in the bounds of the formal type parameters of type alias `A`:

```dart
typedef A<X extends A<X>> = List<X>; // OK!
A<Null> xs; // OK!
```

We're probably not outlawing a huge amount of _useful_ code if we make that kind of self-reference an error, but we could in principle allow it.

**Comment by lrhn** [comment]
I fear what "instantiate to bounds" would do to that declaration.

I guess a super-bounded type alias is safe, as long as you don't try to instantiate it (`new A()`), so we just have to make sure that instantiating to bounds works correctly for all type aliases.

**Comment by eernstg** [comment]
About instantiation to bounds:
```dart
typedef A<X extends A<X>> = List<X>;
A xs; // OK.
```

Instantiation to bounds for type aliases includes the usual step to compute candidate values (where we get that the raw a `A` means `A<A<dynamic>>`), plus a step where we check that all types on the right hand side are well-bounded. The latter is trivial here, because `List` has no bounds. So the raw `A` is accepted.

Unfolding the type aliases in `A<A<dynamic>>` we get `List<List<dynamic>>`, so this is not a useless type, either, even though you could argue that it's a less than stellar way to express that type. So I don't see any particularly difficult issues with the permission to declare `A` in this way.

The fact that it introduces `dynamic` is typical for instantiation to bound. We may be able to tighten that up (just like NNBD will require explicit downcasts where we currently allow implicit ones), but that would be a topic that is concerned with instantiation to bound in general, not just type aliases.

For instantiation you could also argue that there is no way to explain what `new A()` means, unless we unfold the type alias and make it `List<List<dynamic>>`. But then we could also say that `new A()` is OK because `new List<List<dynamic>>()` is OK. There is no soundness issue, because `X extends A<X>` is never in scope for any executable code.

However, from a software engineering point of view I think it is justified to insist on viewing this through the type alias declaration and make `new A()` a compile-time error.

This simply means that we should keep the [rule that applies in this case](https://github.com/dart-lang/language/blob/0e6b07cba963a3cea76b148ccc90ddc0decb86e5/specification/dartLangSpec.tex#L5248) unchanged.

By the way, this argument would apply to an instance creation based on a type alias without the circularity just as well as it applies to circular ones like `A`.

So here is a software engineering argument why we'd want to keep the current rule unchanged: If a type alias denotes a class type then we should encapsulate that this is a type alias, that is, it should work the same as a class whenever possible.

For example, we might want to migrate a class from an older version which has no bounds on a type argument to a newer version with a bound. This might be because this allows the body of the class to have fewer casts or more informative return types etc., and/or because it gives rise to more informative types from type inference or from instantiation to bound. Here is the original version of the class:

```dart
// File 'libC.dart'.
class C<X> { ... }
```

We have lots of existing clients using `C`; here's one:

```dart
// File 'client.dart'.
import 'libC.dart';

C<X> f<X>() { ... return C<X>(); }
```

Now let's say that we want to change `C` such that its type parameter is `X extends T` rather than just `X` (`T` can be any type where this is not an error, e.g., `String` or `Comparable<X>`).

We can now give client libraries an opt-in approach for that new and more strict version of `C`:

```dart
// File 'libNewC.dart`.
import 'libC.dart' as p;
export 'libC.dart' hide C;

typedef C<X extends T> = p.C<X>;
```

To opt in, a client library would simply change `import 'libC.dart';` to `import 'libNewC.dart';`, and then they'd be able to refactor their code to fit the stronger constraints:

```dart
// Updated version of 'client.dart'.
import 'libNewC.dart';

C<X> f<X extends T>() { ... return C<X>(); }
```

At some point we could decide to force the change (so it's "forced in" rather than opt-in), by changing the class to `class C<X extends T> ..`, and we might then be able to improve on some signatures (say, some methods in `C` could now have more specific return types). And so on and so on.

The point is that it seems likely to be useful if we can use a type alias as a class as faithfully as possible, and that seems more important than it would be to provide the greatest possible flexibility that doesn't compromise soundness. So my recommendation is that we blindly reject super-bounded types for instance creations, whether or not it goes through a type alias.

**Comment by eernstg** [comment]
We decided to use the conservative approach where it is an error to have a cyclic dependency in a type alias, even in the case where the cycle involves the bound of a type parameter of the type alias.
