### ISSUE TITLE
No error if augmentation library contains part directive

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#3751]
According to the [Augmentation libraries specification](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/feature-specification.md#defining-an-augmentation)

> It is a compile-time error if:
> ...
> - An augmentation library contains any part directives.

But for now there is no an error in this case nor in CFE nor in the analyzer
```dart
// main_lib.dart
import augment 'aug_lib.dart';

main() {
}
// aug_lib.dart
library augment 'main_lib.dart';

part 'some_part.dart';

// some_part.dart
part of 'aug_lib.dart';
```
The code above produces no any errors.

Tested using `Dart SDK version: 3.4.0-194.0.dev (dev) (Sat Mar 2 00:04:28 2024 -0800) on "windows_x64"`

**Comment by davidmorgan** [comment]
I think this is obsoleted by #3848
