### ISSUE TITLE
Minor omission in metadata section of spec

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#3773]
Section 15 (Metadata) currently reads:

Metadata can appear before a library, part header, class, typedef, type parameter,
constructor, factory, function, field, parameter, or variable declaration
and before an import, export or part directive.

but this list is incomplete. It should include 'enum' in the list of declarations.

**Comment by lrhn** [comment]
And extension types now. 
Which suggests to make the text non-normative and refer to the grammar for where metadata can actually occur.

**Comment by eernstg** [comment]
> refer to the grammar

We should definitely do that! Done in https://github.com/dart-lang/language/pull/3787.
