### ISSUE TITLE
[Wildcard Variables][spec] Can a local function named `_` be referenced?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#3790]
Is this allowed under the wildcard feature?

```dart
void f() {
  _() {}
  _();
}
```

It is legal today. AFAIK, `_() {}` is not a _variable declaration_, but is a _local function declaration_.

[The spec](https://github.com/dart-lang/language/blob/main/working/wildcards/feature-specification.md) currently defines "A local declaration is..." with 5 cases, which do not include a local variable declaration.

@kallentu @munificent

**Comment by lrhn** [comment]
I would say that it should not be allowed.
There should not be a `_` bound in a local scope. 

We can make the function decoration allowed, but not introduce a name, but then the function is unreachable, so having it is likely a bug. 
That could also use be an analyzer warning (dead code).

Arguably, we can say the same for a local `var _ = expr;`, but it can at least have a side effect. (Still, just write it as `expr;`, if the code depends on having a context type, bit is only used for its side effect, it's really confusing code.)

**Comment by kallentu** [comment]
Closing. Updated [the spec](https://github.com/dart-lang/language/blob/main/working/wildcards/feature-specification.md) addressing these explicitly.
