### ISSUE TITLE
Recognizing the increment operator with a single identifier as part of assignableExpresion

### ISSUE THREAD

**Issue by idraper** [dart-lang/language#381]
I am trying to understand in the dart-lang specification how it is possible to get an `<incrementOperator>` with a single identifier either as a `<postfixExpression>` or as a prefix like so:
`++i` or `i++`.

Looking at the Dart Programming Language Specification ([v2.2](https://dart.dev/guides/language/specifications/DartLangSpec-v2.2.pdf) and v2.3-dev) the nonterminal `<incrementOperator>` is used as a terminal in only two locations, `<unaryExpression>` and `<postfixOperator>`.

With `<postfixOperator>` it is a nonterminal of `<postfixExpression>` in the case: `<assignableExpression> <postfixOperator>` (which would become `<assignableExpression> <incrementOperator>`).
With `<unaryExpression>` it is a nonterminal in the case: `<incrementOperator> <assignableExpression>`.

Thus, from what I can see, an `<incrementOperator>` always occurs (either before or after) an `<assignableExpression>`. This, of course, makes sense from just using the increment operator in many languages.

What I am having trouble with is understanding how `<assignableExpression>` can be just an `<identifier>` and nothing else (based on the spec). The three cases for an `<assignableExpression>` are:
- `<primary> <assignableSelectorPart>+`
- **super** `<unconditionalAssignableSelector>`
- `<constructorInvocation> <assignableSelectorPart>+ <identifier>`

None of these 3 cases (as far as I can see) lead to a case with an `<identifier>` all by itself since there must be at least one `<assignableSelectorPart>`.

I am thinking that the `+` after `<assignableSelectorPart>` should be a `*`, since it is possible to have an identifier (which comes from `<primary>` in this instance) with nothing after it. The way this is written, only `++someVar.anotherVar` or `++someVar?.anotherVar` or `++[someExpression]` is possible and there cannot be just an identifier by itself like `++i`.

I am hoping someone can help me either understand why I am wrong and what I missed, or verify what I found, thanks!.

**Comment by leafpetersen** [comment]
The grammar for `assignableExpression` has a bug in it.  I noticed this the other day and have a fix for it outstanding in an unrelated pull request.  The grammar should be:

```
<assignableExpression> ::= <primary> <assignableSelectorPart>+
  \alt \SUPER{} <unconditionalAssignableSelector>
  \alt <constructorInvocation> <assignableSelectorPart>+
  \alt <identifier>
```

I think that answers your question, re-open if I missed something..
