### ISSUE TITLE
Class inherit from generic parameter type?

### ISSUE THREAD

**Issue by hqakva** [dart-lang/language#3833]
Does Dart allow to create a class like this?

```dart
class GenericBased<T extends Object> extends T {
    final bool myProperties;

    const GenericBased({required this.myProperties})
}
```

**Comment by jakemac53** [comment]
No, Dart does not allow this.

**Comment by lrhn** [comment]
The closest thing is a mixin, but mixins cannot have the constructor you need. 
```dart
mixing My properties {
  bool my property = false;
}
```

Without a constructor, it cannot add a final variable that is initialized to different values in different places.

**Comment by mateusfccp** [comment]
Seems like this is a duplicate of #3552.
