### ISSUE TITLE
Unify "agumentation libraries" and part files

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/language#3848]

**Comment by lrhn** [comment]
See also #3576 for history.

**Comment by FMorschel** [comment]
I saw this was created because of [this #3800 comment](https://github.com/dart-lang/language/pull/3800/#issuecomment-2137864919):

> Whoops, I thought this was an issue; it's a PR. Opened #3848 so we have an issue for this.

And almost all issues related to that PR have been closed. Is this one waiting on anything else like #55329 (I see it referencing this above)?

**Comment by jakemac53** [comment]
I think this can be closed now, a few things to work out still but in general the main work of unification has landed

**Comment by davidmorgan** [comment]
We still need an issue to track the implementation and macros work, though :) maybe over in the macros repo?
