### ISSUE TITLE
Serializable `MacroExecutionResult` to allow rerunning subset of macros for a library cycle

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#3877]
Started as https://github.com/dart-lang/sdk/issues/55784

It is hard to know in advance, if inputs for all macros will be the same, so that the output also will be, and so that we can reuse the previous macro generated code. Macro applications in other files might generate different types, because their inputs might have changed, etc.

But at the end applying all macros means executing every phase for every macro application, and get code to generate a new augmentation file. If we see that inputs for this specific macro application (at this phase) are the same as they were at the time when we recorded this cached result, we can just reuse the code. We don't need to: (1) instantiate the macro; (2) run it and perform introspection via protocol; (3) run `buildAugmentationLibraryCode()`. We get the code for a new augmentation, and run it through the same processing as usually for the current phase - build elements, resolve types, etc.

This solves the problem: what if another macro generated some type that will shadow something that we used to see, and we don't know about this well in advance, so must be too conservative when decide whether we can reuse macro results. With per-application checks we see at every step exactly what the macro application will see if we run it. Think about it as shifting introspection from the macro back to the host.

Ideally, we can reuse all macro applications in the library without ever instantiating and running any macro. In this case we can also reuse the whole merge macro generated augmentation code, without ever using `MacroExecutionResult`.

And if there are changes to inputs, we fall back to running macros starting at this point. An issue here is that to get the merged augmentation code at the end, we need `MacroExecutionResult`s for all macro applications, including those for which we previously reused macro generated code. Which means that we need a way to serialize `MacroExecutionResult`s, so that we deserialize them if it turns out that we cannot get to the end without running any macro, for the library.

Don't know yet if we can continue reusing results for remaining macro applications, even after the one which we had to re-run. Theoretically if inputs are the same, the output also must be. The complication is to know that these macro applications are still there, or removed, or shifted, etc. Maybe not strictly necessary? I guess it depends if we expect. If we think that changes rarely leak out of a single library in a large library cycle, then re-running the library is not too bad. If we think that there might be often macros that cause cascading changes through at least one macro application in all libraries of the cycle, it would be beneficial to be able to avoid running macro applications even after we run one macro application.

Performance of this per-application dependencies should be probably on par with reusing the whole library cycle macro results. Mostly these are lookups into various name scopes, and checks for signatures of declarations like `ClassDeclaration`.

We might consider to have a shortcut: check the whole library cycle inputs, and if they are the same, reuse (without any additional checks later) macro application results for all libraries. This is what is implemented now.

**Comment by scheglov** [comment]
@jakemac53 @davidmorgan

**Comment by davidmorgan** [comment]
Update following our chat yesterday.

So `MacroExecutionResult` is marked `Serializable`, so you can certainly write _something_ to disk :)

But, it contains a lot of `Identifier` instances. If I understand correctly, when deserializing those need to restore an exact instance provided earlier by the analyzer. If the library has been reanalyzed, the instances are anyway not going to match the current structure. (This is what I observed when I remarked that the identifier IDs churn very quickly--new instances are created and new IDs issued whenever something changes).

So I think what's needed here is the same transformation `dart_model` is doing: materialize the IDs to values so they can be linked back into the "next round" analyzer structure?

It's not clear to me whether we actually need to do this in the current code, or just prove that it will work when serialization/deserialization is available.

**Comment by scheglov** [comment]
I have an implementation in the analyzer that does it, supports identifiers, etc.
I think this will be enough for me in the analyzer.
Do we want to have eventually some shared implementation?
Is it even useful for CFE?

**Comment by jakemac53** [comment]
> Is it even useful for CFE?

I assume for hot reload (and general incremental rebuilds) it would be useful for the same reasons it is useful in the analyzer?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/369842 has serialization implementation.

Of course `Identifier` serialization logic is analyzer specific, just as any other `Identifier` API.

As an implementation detail, it uses the same data writing mechanism that we use for other summary formats.
And it stores `Element`s as `Reference` instances.
