### ISSUE TITLE
Create the type `Monad` 

### ISSUE THREAD

**Issue by Ing-Brayan-Martinez** [dart-lang/language#3914]
Greetings, my proposal in this case is quite simple, the idea is to create an abstract class called `Monad` within the `dart:core` api to represent all the types that behave like a `Monad` to create a family of types under this concept, this will help improve the type hierarchy, avoid covarian errors and improve consistency. The `Monad` type would look like this

```dart
abstract class Monad {
}

```

### About types that are not `Monad`

The basic types of the Dart language are not candidates to be `Monad` since they do not have any operators that serve as `Functor`, which makes them incapable of wrapping data. This is necessary to define a `Monad`. The Dart language types that cannot be used for this purpose are:

-  String
-  num
-  int
-  double
-  bool
-  T?

### Types that behave like a `Monad`

In the Dart language there are some complex types that are fundamental and are compatible with the idea of ​​Monad, and that can be the basis for supporting functional programming in the language. First we must explain why they are candidates for a monad.

A type of language that is usable as 'Monad' is one that allows values ​​to be stored inside, that is, it serves as a wrapper, for this it must have a special operator that is used to wrap a simple type, this is known as a functor. It must also have a series of operators (map, filter, reduce, flat map) that allow the management of the involved value. Among the types of languages ​​that can meet this characteristic we have:

- DateTime
- List
- Map
- Set
- Future
- Stream
- Optional

All these types that behave like `Monad` could be checked as follows:

```dart
void main() {

 // example 1
 DateTime ex1 = DateTime.of(2014, 06, 12);

  if (ex1 is Monad) {
    print("If it's a Monad...");
  }

 // example 2
 List<int> ex2 = List.unmodifiable([1,2,3,4,5,6,7]);

  if (ex2 is Monad) {
    print("If it's a Monad...");
  }

 // example 3
 Map<String, int> ex3 = Map.unmodifiable({"key1":10, "key2": 22});

  if (ex3 is Monad) {
    print("If it's a Monad...");
  }

 // example 4
 Set<int> ex4 = Set.unmodifiable({1,2,3,4,5,6,7});

  if (ex4 is Monad) {
    print("If it's a Monad...");
  }

 // example 5
 Future<String> ex5 = Future.value("Hello...");

  if (ex5 is Monad) {
    print("If it's a Monad...");
  }

 // example 6
 Stream<String> ex6 = Stream.value("Hello...");

  if (ex6 is Monad) {
    print("If it's a Monad...");
  }

 // example 7
 Optional<String> ex7 = Optional.of("Hello...");

  if (ex7 is Monad) {
    print("If it's a Monad...");
  }
}
```
As you can see all these types inherit from the abstract class `Monad` in a consistent way.

**Comment by lrhn** [comment]
Nor sure `Monad` would work well without higher-order types or generic access to constructors.

A declaration would have to be something like:
```dart
abstract class Monad<T> {
  Monad.unit(T value) .... // what to write here?
  Monad<S? bind<S>(Monad<S> Function(T));
}
```

If `Future<T>` implements `Monad<T>`, then does it have a:
```dart
  Monad<S> bind<S>(Monad<S> Function(T));
```
or a
```dart
  Future<S> bind<S>(Future<S> Function(T));
```
It probably has to be the latter, because the function *will* be asynchronous. Which means that it's contravariant, and needs either a higher-order Self-type. We can try doing it with F-bounded polymorphism, but I can't type `bind` then. With a higher order type parameter one might be able to do:
````dart
abstract class Monad<T, M<X> extends Monad<X, M<X>>> {
  abstract Monad.unit(T value); // Abstract over constructors?
  M<S> bind<S>(M<S> Function(T) apply);
}
abstract class Future<T> implements Monad<T, <X> => Future<X>> {
  // ...
  factory Future.unit(T value) => Future<T>.value;
  Future<S> bind<S>(Future<S> Function(T) apply);
}
```

Without higher-order types/first-class classes it's non-trivial to implement `Monad`. You can implement a lot of individual monads, but you can't abstract over a generic type, and you can't abstract over statics or constructors, which are the two things a monad type wants.

**Comment by mraleph** [comment]
We have no plans to introduce monads or any other associated concepts into Dart language or core libraries.

Consequently I don't think we should keep this open.
