### ISSUE TITLE
Consider changing the context for the operand of `throw` to `Object`.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#3917]
Currently the context is `_`. But as Leaf notes in https://github.com/dart-lang/language/pull/3850#discussion_r1635563838:

> in general the context is intended to capture "what this thing should be", and what this thing (the operand to `throw`) should be is a subtype of `Object`, not a subtype of `Object?`.

I suspect the amount of real-world breakage from this change would be negligible, so we probably could do it through the breaking change process (we wouldn't need to use language versioning).

**Comment by lrhn** [comment]
Are there other paces where the expression has a requirement that doesn't match its context type?

The RHS of `==` seems to be `dynamic`/`_`, not parameter type of LHS's `operator==` made nullable.
That's probably a bug.

A cast like `e as T` doesn't give `e` a context of `T`. That's not a *requirement*, but it is a pretty good hint.
(Although if we change that, we should probably change `var (x as C) = ...` too.)

Also not a requirement, just an annoyance: `(null as C?) ?? e` gives `e` a context of `C?` not **NonNull**(`C?`).
(But probably not related.)


Examples:
```dart
void main() async {
  try {
    throw ctx(C(), "throw"); // Prints "throw: dynamic".
  } on C {
    // Expected.
  }

  C() == ctx(C(), "=="); // Prints "==: dynamic".
  ctx(C(), "as") as C; // Prints "as: dynamic"

  var (x as C) = ctx(C(), "(as)=");

  (null as C?) ?? (ctx(C(), "??")..st<E<C?>>());
  
  // Prints "Ctx: dynamic", then throws, and
  // "The declaration `st` isn't referenced"
  C() == (ctx(C(), "as")..st<E<C?>>());
}

class C {
  int get c => 1;
  set c(int? v) {}
  bool operator ==(covariant C _) => true;
  toString() => "C()";
}

T ctx<T>([Object? value, String name = "Ctx"]) {
  print("$name: $T ($value:${value.runtimeType})");
  return value as T;
}

extension<T> on T {
  void st<X extends E<T>>() {
    print("$this:$runtimeType @ $T");
  }
}

typedef E<T> = T Function(T);

```

**Comment by stereotype441** [comment]
@lrhn
> The RHS of `==` seems to be `dynamic`/`_`, not parameter type of LHS's `operator==` made nullable. That's probably a bug.

FWIW, I filed an issue about this earlier this year: https://github.com/dart-lang/language/issues/3653. I haven't gotten around to doing anything about it yet, though.

Off the top of my head, I can't think of any examples other than the ones you mentioned.

**Comment by stereotype441** [comment]
I [prototyped this](https://dart-review.googlesource.com/c/sdk/+/371982) and ran it through a full round of testing in google3. There were no failures, so I'm inclined to move forward on this using the breaking change process.

@dart-lang/language-team any objections?

**Comment by stereotype441** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/8e8a013baead4a5b6b4dfbfd538202a75d5b3c20.
