### ISSUE TITLE
Network paths don't work anymore with version 3.4.0

### ISSUE THREAD

**Issue by BananaMasterz** [dart-lang/language#3924]
(Not sure if this is the correct repo for the issue so pardon me if not)

Running the following code in dart 3.4.0 on **WINDOWS** raises `PathNotFoundException`

```dart
import 'dart:io';

void main() async {
  print(await File(r'\\my_srv\some_path\test.txt').exists());
  File(r'\\my_srv\some_path\test.txt').copy(r'C:\path\test.txt');
}
```

but works fine in earlier versions (like 3.3.4 and 3.0.0).

I see there have been some changes like this [one](https://github.com/dart-lang/sdk/commit/c2e9ceeb6b97329f75a84bd41e40b540dd40e7a4) (maybe some more) that could be the cause.

I also see that there are not tests set up for network paths so this isn't caught.

Finally I'm not sure why `File().exists())` returns `true` but `.copy()` can't see the file... shouldn't both methods resolve the paths in the same manner?

This is my OS:
```
Edition	Windows 11 Pro
Version	23H2
Installed on	‎27/‎3/‎2024
OS build	22631.3737
```

**Comment by SuperPenguin** [comment]
I think https://github.com/dart-lang/sdk/issues is the proper repo for this issue instead

**Comment by BananaMasterz** [comment]
> I think https://github.com/dart-lang/sdk/issues is the proper repo for this issue instead

You're probably right... Opened one there instead at

https://github.com/dart-lang/sdk/issues/56049
