### ISSUE TITLE
Allow pattern `case` conditions in `while` statements.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#3927]
Dart allows `if (e case p when c) ...`.
It should also allow `while (e case p when c) ...`.

The `true` branch is the loop body, which is where the bound values are available.

An example use could be finding the last element of a linked list:
```dart
  while (cursor.next case var next?) cursor = next;
```

Generally `if` and `while` are mostly symmetric, and the behavior here can be emulated by:
```dart
while (true) {
  if (cursor.next case var next?) cursor = next;
  else break;
}
```

(Even if Dart doesn't make `(e case p when c)` a general boolean expression, it can still safely and meaningfully be allowed in a few more cases, mainly [conditional expression][#2664] and `while` conditions. I doesn't make sense for `do`/`while` since the true branch isn't dominated by the condition.)

**Comment by rrousselGit** [comment]
What about `for`?

```dart
for (...; something case ... ;  ...) {

}
```

If we can do it for `while`, I think it'd make sense here too.

**Comment by lrhn** [comment]
The `for` should work too. It's a little crowded syntactically, and it's not completely clear whether any bound variables are in scope for the increment-expressions or not. Still, the check being true dominates the body and increments, so it should probably just work for those.

**Comment by leafpetersen** [comment]
I think this is already covered by #2536 .
