### ISSUE TITLE
References to the initializing expression of an augmented declaration?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3953]
Consider the following program:

```dart
class A {
  final int x = 1;
}

augment class A {
  @someAnnotation
  augment final x = 2;
}

augment class A {
  augment final x = augmented + 1;
}
```

The specification [indicates](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/feature-specification.md#augmenting-variables-getters-and-setters) that `augmented` in the second `augment class A` declaration refers to the initializing expression in the 'original' declaration. It might seem more natural to let it refer to the most recent earlier declaration (augmenting or original).

We might want to consider all occurrences of 'original' in that section. Maybe they are all intended to mean 'most recent' rather than 'first'?

@jakemac53, @munificent, WDYT?

**Comment by jakemac53** [comment]
Yes, we could also use the term "augmented delaration" - we have mostly converged on the terms "augmenting" and "augmented" to refer to these declarations.

It might be a bit confusing to use that term in the context of the `augmented` expression, or maybe it would actually be intuitive, not sure :).

**Comment by jakemac53** [comment]
I recently went though and updated most references to "original" to "augmented", which I believe fixed this one.
