### ISSUE TITLE
Allow an augmenting variable declaration without an initializer

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3957]
The augmentation specification says that

> Since the initializer expression is the only meaningful part of the augmenting declaration, an initializer expression must be provided

in the location where it specifies an augmenting variable declaration that augments a variable declaration. This means that the following is a compile-time error:

```dart
int x = 1;

/// A DartDoc comment.
@someMetadata
augment int x;
```

This seems benign to me, and potentially useful, so I'd recommend that we turn this into a non-error.

**Comment by jakemac53** [comment]
I agree, and I think there might be a few other similar mentions of errors?

When originally written we hadn't considered augmenting only to provide metadata or doc comments, but we do want to allow that.
