### ISSUE TITLE
Is future returned immediatelly from async call? Inconsistency in docs

### ISSUE THREAD

**Issue by ioma8** [dart-lang/language#3966]
I am trying to figure out whether Future is returned from async function immediatelly or only after the async function reaches the first await statement within its body. The documentation is inconsistent about this behaviour.

1) On this page of dart documentation it states that the Future is returned immediately and the function "queues up":
https://dart.dev/libraries/async/async-await#:~:text=When%20you%20call%20a%20function%20that%20returns%20a%20future%2C%20the%20function%20queues%20up%20work%20to%20be%20done%20and%20returns%20an%20uncompleted%20future.    
> When you call a function that returns a future, the function queues up work to be done and returns an uncompleted future.

2) On this page it states that that the Future is returned only after it reaches first await statement within it:
https://dart.dev/language/async#:~:text=Instead%2C%20the%20async%20function%20executes%20only%20until%20it%20encounters%20its%20first%20await%20expression.%20Then%20it%20returns%20a%20Future%20object%2C%20resuming%20execution%20only%20after%20the%20await%20expression%20completes.    
> Although an async function might perform time-consuming operations, it doesn't wait for those operations. Instead, the async function executes only until it encounters its first await expression. Then it returns a Future object, resuming execution only after the await expression completes.

Here is code whose behavior I want to determine:
```
void mySync() {
   myAsync();
   print("sync print after");
}

Future<void> myAsync() async {
  print("async print");
  await .... [next operations...]
}
```

If documentation statement 2 is true, then it is ensured that "async print" is printed BEFORE "sync print after."
However if statement 1 is true and Future is returned always immediately, then it is not determinable whether "async print" or "sync print after" would be printed first. Note that the myAsync is on purpose being called from synchronous function (thus without being waited on by await keyword).

Pls help me figure out this inconsistency in docs and what is the actual behaviour.

**Comment by mraleph** [comment]
> The documentation is inconsistent about this behaviour.

I would not say that documentation is inconsistent - though I must admit it is confusing. The first quote does not talk about `async` functions, it tries to make a generic statements about functions that return `Future`s. It tries to say something which amounts to 

> When you call a function which returns a `Future` it does _some work_ and then returns a (possibly yet not completed) `Future`. 

I don't think it is very helpful statement. It is a true statement - but it does not really tell you something you would not already know simply by looking at the code. 

The second quote you give describes semantics of `async` functions. When you call an asynchronous function it will execute synchronously until it reaches the first `await` (or `return` - whatever comes first) and then returns a `Future` to its synchronous caller. 

- If `await f` was reached then `async` function invocation is suspended until `f` completes. When `f` completes the invocation will resume from the point of suspension and run until next `await` or `return`;
- If `return v` was reached then `async` function invocation is complete and the future which was produced by it is completed with `v`.

(I am ignoring exceptions in this description not to muddy it too much).

> If documentation statement 2 is true, then it is ensured that "async print" is printed BEFORE "sync print after."

Yes, that's what will happen.

**Comment by ioma8** [comment]
@mraleph thank you for the explanation. Does it mean that when async function does not contain any awaits, it will act totally as synchronous function? Ie all its code will be run before next statement in the caller function? Now I am not thinking return types (I know in this case its return type still is future) I am talking about the sequence of events.

**Comment by mraleph** [comment]
@ioma8 that is correct. if `async` function has no `await` it will just run to the completion. 

You might also find this https://gist.github.com/mraleph/ab043fbde774e9d3d0bb7ebd305dc909 helpful.
