### ISSUE TITLE
Should digit separators be supported in int.fromEnvironment?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#3971]
If an environment variable (or `-D` defined variable, whatever) is set to `"1_000_000"`, should that be parsable as an int, with [int.fromEnvironment](https://api.dart.dev/stable/3.4.4/dart-core/int/int.fromEnvironment.html), under the digit separators feature?

The current support:

* hex (e.g. `"0x1000"`) is suppoted.
* exponential notation (e.g. `"10e2"`) is **not supported**.
* doubles are **not supported** (there is no `double.fromEnvironment`).

**Comment by lrhn** [comment]
No.

The supported inputs in `int.fromEnvironment` are those recognized by `int.parse`.
They're not Dart numerals.
