### ISSUE TITLE
Allow all variable augmentations to omit the initializing expression

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3974]
The augmentations [feature specification](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/feature-specification.md) has the following rule:

> **Augmenting a variable with a variable**: Augmenting a variable with a variable only alters its initializer. External and abstract variables cannot be augmented with variables, because they have no initializer expression to augment.
>
> Since the initializer expression is the only meaningful part of the augmenting declaration, an initializer expression must be provided.

In order to support augmentations whose purpose is to add documentation or add metadata, we should allow every augmenting variable declaration to omit the initializing expression.

The semantics would be as follows:
- a variable with no initializing expression which is augmented with no initializing expression still does not have an initializing expression.
- a variable with no initializing expression which is augmented with an initializing expression is augmented to have that initializing expression *(except for a `late final` variable, where this case is an error)*.
- a variable with an initializing expression which is augmented with no initializing expression is treated as if it had the initializing expression `augmented`.
- a variable with an initializing expression `e1` which is augmented with an initializing expression `e2` has `e2` as the initializing expression, and any occurrence of `augmented` in `e2` is evaluated by evaluating `e1`.

These rules are applied recursively in order to handle multiple augmentations of the same declaration.

The rules are applicable to variables with any set of modifiers, noting that `abstract` and `external` variables do not introduce a variable, they are just an abbreviated notation for a getter and possibly a setter.

In particular, a `late final` variable with an initializer can be augmented by a `late final` variable with no initializer. This does not mean that there will now be a setter (which is implied for the corresponding non-augmenting declaration), it just means that the augmenting declaration is treated as if it had an initializing expression of the form `augmented`.

**Comment by lrhn** [comment]
Agree, except that I wouldn't introduce an `augmented` expression for item 3, I'd just say that the result of augmenting has `e1` (the initializing expression of the signed variable) as initializing expression.

**Comment by jakemac53** [comment]
I believe that https://github.com/dart-lang/language/pull/3968 should cover this?
