### ISSUE TITLE
False negative `unreachable_switch_case` diagnostic when using `switch` statements

### ISSUE THREAD

**Issue by lucavenir** [dart-lang/language#3991]
I couldn't find this issue anywhere else, I just hope I'm opening this in the right place.
I'm not sure if it's a spec issue, a documentation issue, or a lint/analysis false negative.

TL;DR: given this `sealed class`

```dart
sealed class Z {
  Z();
  factory Z.random() => A();
}

class A extends Z {}
class B extends Z {}
class C extends Z {}
```

The following code behaves weird to me:

```dart
void kek() {
  final something = Z.random();

  final somethingElse = switch (something) {
    A() => 'a',
    B() => 'b',
    C() => 'c',
    _ => 'eheh', // unreachable_switch_case triggers correctly!
  };
  print(somethingElse);  // prints `a`

  switch (something) {
    case A():
      print('a');  // will print this
    case B():
      print('b');
    case C():
      print('c');
    default: // ??? no analysis issue?? I'd expect `unreachable_switch_case` to trigger here as well
      print('eheh');
  }
}
```

Both [the documentation](https://dart.dev/language/branches#exhaustiveness-checking) and the [diagnostic message](https://dart.dev/diagnostics/unreachable_switch_case) speak clearly about this so I'm not sure why no lint is triggered in that `default` clause.

By the way, at runtime everything goes as you'd expect. Two `a`s are printed.

I found out about this while reading [this other issue](https://github.com/grpc/grpc-dart/pull/718) with the help of @CLucera.

**Comment by stereotype441** [comment]
This is a known issue: https://github.com/dart-lang/sdk/issues/54575
