### ISSUE TITLE
Runtime Error when override a function where the parameter is a function that return a genetic type and the parameter is generic type.

### ISSUE THREAD

**Issue by MiniSuperDev** [dart-lang/language#3996]
Hello, 
I am trying to create a class that have an abstract function where the parameter is a function that return a genetic type and the parameter is generic type.

```dart
abstract class A {}

abstract class B<AType extends A> {
  void fun(AType Function(AType a) callback);
}
```
But when create the implementations and use it I get runtime errors.

Is there a way to make it work?

Thanks

**Error:**

```text
TypeError: Instance of '(A) => A': type '(A) => A' is not a subtype of type '(A1) => A1'
```

**(Not Working) Generic Return type and Generic Parameter:**

```dart
abstract class A {}

abstract class B<AType extends A> {
  void fun(AType Function(AType a) callback);
}

class A1 extends A {}

class B1 extends B<A1> {
  @override
  void fun(A1 Function(A1 a) callback) {
    callback(A1());
  }
}

void bHandler(B b){
   b.fun((a1) {
    print('b.fun');
    return a1;
  });
}

void main() {
  bHandler(B1()); 
}

```

I have 2 examples with other cases with generics that work as expected:

**(Working) Fixed return type like `void` and generic parameter:**

```dart
abstract class A {}

abstract class B<AType extends A> {
  void fun(void Function(AType) callback);
}

class A1 extends A {}

class B1 extends B<A1> {
  @override
  void fun(void Function(A1) callback) {
    callback(A1());
  }
}

void bHandler<BType extends B<A1>>(BType b) {
  b.fun((A1 a1) {
    print('b.fun');
    
  });
}

void main() {
  bHandler(B1());
}
```

**(Working) Generic return type and fixed return type like `int` or none:**

```dart
abstract class A {}

abstract class B<AType extends A> {
  void fun(AType Function(int i) callback);
}

class A1 extends A {}

class B1 extends B<A1> {
  @override
  void fun(A1 Function(int i) callback) {
    callback(1);
  }
}

void bHandler<BType extends B<A1>>(BType b) {
  b.fun((i) {
    print('b.fun');
    return A1();
  });
}

void main() {
  bHandler(B1());
}

```

**Comment by lrhn** [comment]
This is working as intended. 

The parameter of type `AType Function(AType)` is invariant in `AType`. When you up-cast a `B1` instance to `B`, and call it with an implicitly typed function `(a1) { print('b.fun'); return a1; }`, that function gets inferred to be an `A Function(A)`. Then you call the `B1` method with that function, which is not a valid argument to a method expecting `A1 Function(A1)`. Since it's a type parameter occurring covariantly, this is checked at runtime, and it throws like it should.
