### ISSUE TITLE
Free Venezuela 🇻🇪

### ISSUE THREAD

**Issue by Ing-Brayan-Martinez** [dart-lang/language#4001]
This is not intended to be a petition for issues related to this repository, just to ask for international help from anyone who has decision-making power at Google. Other companies have helped us and we are grateful.

I apologize for breaking the rules.

**Comment by mit-mit** [comment]
This kind or use of the issue tracker is not acceptable, and doesn't follow our code of conduct. Consider this a warning; we will issue a ban if there are repeat misuses.

**Comment by Ing-Brayan-Martinez** [comment]
It was what I expected, that is hypocrisy I remember when Google gave support in:

Ukraine
Palestine
LGBTQ groups

But in Venezuela there is a massacre because of the Maduro dictatorship and nobody supports only Mark Zuskeber and Elon Musk you alone are not human

We need international support we are fighting as we can
