### ISSUE TITLE
`?.` operator doen't infere null safety

### ISSUE THREAD

**Issue by feinstein** [dart-lang/language#4006]
Consider the following code:

```dart
final myList = getList();

if (myList?.isNotEmpty != null) {
  // Shows error
  myList.first;
}

if (myList != null && myList.isNotEmpty) {
  // doesn't show error
  myList.first;
}
```

The first case shows an error, saying I can't use `first` since `myList` can be `null`, but the second `if` doesn't show any error.

I imagine it's hard for the compiler to know which variable is not-null when we are chaining lots of access, like: `my?.method?.with?.lots?.of?.returns`, but for this simple case where we have only 1 variable, the compiler should be able to know it's not null past that check.

PS: I find `if (myList != null && myList.isNotEmpty)` more readable, but the shorter version should work too.

I am on dart 3.4.4

**Comment by lrhn** [comment]
This is not a new idea, so marking as duplicate of #1224, where it's been discussed a lot.
It's not a bad idea, but also non-trivial to implement and scope.

**Comment by feinstein** [comment]
Thanks @lrhn, I tried to search for a duplicate before opening this issue, but didn't find.

**Comment by lrhn** [comment]
GitHub search is ... not always useful. 
It's even harder when there is no good keyword to search for, and `?.` and `==` aren't words.

I found it on page 4 by searching for `promotion`. If I hadn't known it was there, I probably wouldn't have found it at all.

**Comment by feinstein** [comment]
Good to know, thanks for the tip!
