### ISSUE TITLE
Generic type with "extends" constraint falls back to dynamic if unspecified, rather than the declared "extends" base class

### ISSUE THREAD

**Issue by BenjiFarquhar** [dart-lang/language#4042]
I have this class:

```
abstract class VgnItmVm<FM extends FormModel<FV>, FV extends VgnItmFormValue<FM, FV, E>, E extends VgnItmEst,
    F extends FormFactory> with VpForm<FM, FV> {}
```

And you can see it being used in an `UnmodifiableListView<VgnItmVm> get vms` below, and when I hover over `vms` it is showing `FormModel<dynamic>`:

<img width="992" alt="Screenshot 2024-08-17 at 7 52 52 AM" src="https://github.com/user-attachments/assets/dcd778d9-1c18-4583-a324-3a8694d745f0">

but hovering over `VgnItmVm` just next to `vms` shows:

<img width="979" alt="Screenshot 2024-08-17 at 8 42 14 AM" src="https://github.com/user-attachments/assets/212b1b15-7683-48ca-9e30-b66d3fd8aa79">

It shows something different when hovering over the getter (a dynamic is in there), than when hovering over the return type of the getter, which has no dynamics in it. Is there any scenario where this should be able to happen? 

I am working around the dynamic by adding `.whereType<VgnItmVm<FormModel<VgnItmFormValue>, VgnItmFormValue, VgnItmEst, FormFactory>>()` where I read `vms`:

```
  bool get anyFormsNotEmpty => vms
      .where((element) => element is! TypeVm)
      // TODO: this shouldn't be neccessary - bug in dart?
      .whereType<VgnItmVm<FormModel<VgnItmFormValue>, VgnItmFormValue, VgnItmEst, FormFactory>>()
      .any((element) => !element.formModel.model.isEmpty);
```
I've tried to reproduce in a minimal example, but the types have always worked correctly in my minimal example (there is no dynamic shown when hovering).

**Comment by lrhn** [comment]
Your `vms` getter's type contains the "raw type" `VgnItmVm`, so the compiler has to introduce some instantiation. It does that using the "instantiate to bounds" algorithm.

The type
```dart
VgnItmVm<
    FM extends FormModel<FV>, 
    FV extends VgnItmFormValue<FM, FV, E>, 
    E extends VgnItmEst,
    F extends FormFactory>
```
is F-bounded. The type variable `FM` depends on `FV`, and `FV` depends on `FM` and `FV`.
Such cyclic dependencies means that it's non-trivial to give a default instantiation. Simply unfolding the bounds would give an infinite type. Doing anything less does not give a well-bounded type.

The instantiate to bounds algorithm will do one step of expansion of the cyclical your variables, then give up and insert `dynamic`, making the result a super-bounded type. 

In guessing that `VgnItemEst` is also generic, so the raw type occurring in the `E extends VgnItemEst` also gets instantiated to bounds.

This then explains the type you see as the return type of `vms`, it's the result of doing instantiate-to-bounds on the raw F-bounded type.

**Comment by BenjiFarquhar** [comment]
@lrhn That makes a lot of sense. It would be a never ending generic type loop if it didn't give up and use dynamic. Was a great explanation. Cheers!
