### ISSUE TITLE
Promote `obj` to non-null when checking `obj?.field == value`

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#4076]
Consider the following code:

```dart
void fn() {
  Class? obj = ...;
  if (obj?.field == 'value') {
    obj.method();
  }
}
```

Currently, this fails and requires to instead write:

```dart
if (obj != null && obj.field == 'value') {
  obj.method();
}
```

Could we consider `obj?.field == <non-nullable expression>` to be equivalent to `obj != null && obj.field == <expr>`?

**Comment by rrousselGit** [comment]
One exception would be extensions on nullable objects. The following shoudn't work:

```dart
extension on Object? {
  Object? get field;
}

if (obj?.field == 'value') {
  // `obj` shouldn't be promoted to non-null, as `null.field` is possible
}
```

**Comment by mateusfccp** [comment]
Seems like a duplicate of #1224.

**Comment by rrousselGit** [comment]
Seems like it
