### ISSUE TITLE
Dart Implicit Static Access

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#4080]
An unqualified identifier is looked up in the lexical scope. If that fails to find a binding, the identifier <code>*id*</code> is then treat as an instance member access on `this`, as if it was <code>this.*id*</code>. 

This only applies to instance member access. If the surrounding class has a static member with the same name, then it is always in the lexical scope. Until augmentations.

With augmentations, one `augment class C { … }` may want to reference a static member declared by *another* `augment class C { … }`.  As currently specified, only the declarations inside the current augmenting class declarations are in its *lexical* scope, so the former class would have to prefix a static access with `C.`.  Which is annoying.

This is a proposal to do a second level of scope lookup after the initial lexical scope lookup has failed to find anything. The lexical scope is based on the individual declarations, and the second scope tried is the combined scope of the *fully augmented* surrounding definitions instead.

This is intended to be introduced with, or just be part of, the augmentations specification.

## Proposal

To resolve an identifier *id*, do the following:

* Look up *id* in the surrounding lexical scope. If anything is found, then that's either an error or what the identifier denotes. _(An error can occur for example if a getter-lookup finding only a setter, or similar.)_
* Otherwise if the identifier occurs **inside** a `class`, `mixin`, `enum`, `extension` or `extension type` declaration _(the declarations that can have instance and static members)_, and the *fully augmented* definition for that declaration contains a static or instance declaration (not constructor) with base name *id*, then the identifier occurrence denotes a static or instance access to that member, just as if it had been found in the surrounding declaration in the lexical scope. _So equivalent to either <code>NameOfClass.*id*</code> or <code>this.*id*</code>, with possible down-stream errors if the only member found with that base name was a setter, or if it was an instance member but *id* occurred where `this` was not available._
* Otherwise the identifier denotes an instance member lookup on the `this` object at its static type. *(There may not be any member with that name in the interface of the static type of `this`, in which case the name may be resolved to an extension member. Or it may just be an error because there is no `this` in the current scope.)*

The "Inside" of such a name-space declaration is defined as:

* Anything inside the *body* of the declaration:

   * Anywhere in a member declaration of the namespace declaration.
   * Anywhere in an enum element declaration.

  If it's inside the `{…}`, it counts.

 * And the "primary constructor"/representation type and variable declaration of an extension type declaration. _(Not that that matters today, there are no valid places to use a static member reference, but if we we ever allow the representation variable parameter to be optional and have a default value, then that default value expression could refer to a static member. And if we introduce primary constructors in general, they should be included too.)_

## Consequences

**Lexical lookup still wins every time.** This fallback is only for names that are not in the lexical scope at all. It just has one more thing to try before defaulting to <code>this.*id*</code>: To check if *another fragment* of the current declaration declares the name, and if so use that, as if it had been in the current fragment too. And since different fragments of a namespace declaration cannot declare both an instance member and a static member with the same base name, it either finds a static member, and uses that, or it finds an instance member and uses that, or it finds nothing, and still considers it an instance member access. _Which means we *could* just say that it looks for a static member, and if it finds none, it falls back to <code>this.*id*</code>, but it fells more consistent to say that finding an instance member in the fully augmented definition makes the choice of using <code>this.*id*</code> deliberate, rather than just being a fallback._

The augmentation specification should state which names are in which lexical scopes. For example implicit declarations exist in are in the namespace of the declaration that introduce them. If an augmenting class declaration contains a variable declaration, it also contains the getter and setter names in its lexical scope. An extension type declaration contains the representation variable in its lexical scope for every declaration that repeats the declaration..

**This is a non-breaking change for existing code.** There are no cases in existing code where the fully-augmented definition member lookup would find something, and the initial lexical scope lookup wouldn't have found the same thing first.

**Static declarations beat inherited instance members.** If a class has a static member, and it inherits an instance member with the same name from a superclass, then an access to that name from another class declaration fragment than the ones declaring the static member will still resolve to the static member. The locally declared member takes precedence over the inherited instance member. _If we ever allow the same class to declare both a static and an instance member with the same basename, we should probably make it a conflict to have an unqualified access when both or neither are in the lexical scope of the access. If one of them is in the lexical scope, it wins._

**Does not affect extension member lookup.** The change only applies if there is a declaration in the (fully augmented) surrounding class-like declaration, in which case the name refers to that declaration. It's like a secondary "logical scope" lookup on the *entire* class-like declaration. _If we ever allow nested classes, we probably want to do a full "logical scope *chain*" lookup on the fully augmented inner class, then the fully augmented outer class, before falling back on the default. The concept here generalizes to more levels, we just don't have any … yet._ It's not "Lets try <Code>ClassName.id</code> and see if it means something".

Only when we have given up finding anything in *any* scope do we fall back on <code>this.*id*</code> which is resolved against the static type, not concrete declarations. at which point extensions may apply. You don't get to invoke *static extensions* on the current class without a class-name prefix. (Not unless we want to do that as a possible fallback along with <code>this.*id*</code>, but that'll be independent of, and orthogonal to, this feature.)

 
See also #4061 which this feature may alleviate the pains of.

**Comment by lrhn** [comment]
@dart-lang/language-team As discussed in overtime of the meeting. WDYT?

**Comment by jakemac53** [comment]
I do prefer this approach to a full merging of the instance and static scopes because it retains the lexical scoping always wins property which I think it is important to retain even if the actual scenarios where it would be violated are rare.

**Comment by lrhn** [comment]
Another way to look at this is repeated widening of the scope.

First we check the direct lexical scope, needed on the individual declarations. 

If that fails, we widen the scopes along the way to be the complete, fully augmented, declaration scopes, and try looking up again. (Which happens to only affect one level of the scope chain, the member scope, since function declarations can't add any new names in augmentations.)

If that fails, we widen the scope to include inherited members too. Which again only affects the member scope, and only instance members, since statics and constructors are not inherited.

And if that fails we widen the scope to also contain extension (instance) members to the member scope.(And if we give our own imports precedence there, we first widen with our own declared extensions, then with our own imported extensions, then with our parents file's extensions.)

At each step we add more members to the existing scope chain, it's just that we only do that if we already gained to find something in the old scope chain, so it looks like we're only looking in the new place.
If we had more nested augmentations, we could have been adding members to more than one level at each step. 

(And we could choose to cut things differently if we wanted to, fx checking the fully augmented member scope before checking the inherited import scope. I don't know if it makes sense, but it's possible.)

**Comment by lrhn** [comment]
The more I think of this, the more it feels inconsistent because it uses the entire library's declarations in the first step, but only the visible declarations in the second step.

So, consider *this* behavior instead:

> The scopes are defined as currently, except that:
> * The library declaration scope (still) contain all declarations from all files of a library, only
>     * any declaration which is declared *in the current file* is marked as *having priority*.
> * The member scope of a class-like declaration contains all members from all base or augmenting
>     declarations for the same class-like definition, and
>     * any member declaration which is declared *in the current class-like declaration* is marked as *having priority*.
> * All declarations in the file's import prefix scope are marked as *having priority*.
>
> When doing a lookup of an identifier *id* in a scope, the lookup takes an extra flag of "priority-only",
> which defaults to false (so we only say when it's not false).
> * If the scope contains a declaration with that base name, then we have a match, which may be the result.
>     * If the scope contains a declaration with that base name that is marked as *having priority*,
>        then lookup completes with that declaration as result.
>     * Otherwise if the "priority-only" flag as false, and the found declaration is a class-like declaration member,
>        a top-level member declaration or an import prefix (those that can have priority, but this one didn't):
>        * Do a lookup of *id* on the current scope's parent scope with "priority-only" set to true.
>            * If that lookup has a result, then lookup in this scope completes with that result.
>        * Otherwise lookup in this scope completes with a declaration from this scope as result.
>     * Otherwise fall through to next step.
> * Otherwise
>    * If this scope has a parent scope, perform lookup for *id* in the parent scope with the same "priority-only"
>       flag as the current lookup.
>       Then this lookup completes with the same result or lack of result as the parent scope lookup.
>    * Otherwise lookup completes with no result.

(Then there are all the details of what it the identifier reference means, when we know what *kind* of declaration it refers to, with getters/setters catching the same names, but not necessarily having a declaration of the correct kind. To be precise, a *lookup* should not return a declaration, but a "definition".)

In short: A name declared in the *current file* or *current class-like declaration* takes precedence over a name included in the same scope by a declaration in another file or declaration. Declarations in the current file include top-level declarations and import prefixes (which are not allowed to have the same name anyway).

It's not in the same file if it's a top-level declaration


This has no effect on existing code, and is backwards compatible.

It allows a member declaration from another file to be in scope, while still giving priority to a top-level declaration in the current scope. The scope chain effectively becomes:
* local scopes
* current-class-like-declaration member scope (declarations of current class-like declaration only)
* type parameter scope
* current-file library declaration scope (top-level declarations of current file)
* current file import-prefix scope (import prefixes introduced by current file)
* full class-like member scope (declarations of *all* augmenting or base declarations of the class-like definition)
* full library declaration scope (top-level declarations of all files of library)
* current-file import scope
* parent-file compined import scope

For existing pre-feature libraries, the current-file class-like member scope introduces the same members as the full member scope (because there is only one declaration containing all the members, so they're all current), so we can ignoore the "full class-like member scope", because any name in there has already been found earlier.
Also, only the library file can declare prefixes, and they can't have the same name as top-level declarations, so effectively the "current-file library declaration scope" and "full library declaration scope" are adjacent, and we can ignore the former.
That leaves an effective scope chain that is equivalent to the current behavior.

**Comment by lrhn** [comment]
@johnniwinther made the comment that if it's this hard to describe, maybe it's too complicated for its own good.

The simplest model is that every name in the fully augmented class declaration is in scope inside any declaration for that class (or class-like). It's consistent with how we handle top-level declarations (every name declared in the library is in scope).

It means that you can't rely on what you can see in the current file, but that was never true anyway. You couldn't see top-level declarations from other files or imported names.

I'm warming up to just doing that. (Like it was first specified before I argued to change it. By bad.)

**Comment by lrhn** [comment]
And to complete the monologue, the Dart team has decided to have every member of the class scope in scope for every declaration, augmenting or not. So it was written, so it shall be done.
