### ISSUE TITLE
Generic type as function return type  can't work 

### ISSUE THREAD

**Issue by sunflower-knight** [dart-lang/language#4097]
Include a permanent link to the error if possible.
code below can't compile ; compiler can't find the generic type although  i have use  create<Person>()
```dart 
class Person {
  Person() {
    print('Person created');
  }
}

T  create<T>() {
  return new T(); 
}

void main() {
 
  Person value = create<Person>();
  print(value.runtimeType); 
}
```

https://help.github.com/en/articles/getting-permanent-links-to-files

**Comment by julemand101** [comment]
Dart does not support creating new objects from Type objects (like generics) or call any static methods on types.

My suggested alternative here would be make your `create` method take a function as argument which can be used to create the object you want. By doing that, you could make:
```dart
class Person {
  Person() {
    print('Person created');
  }
}

T create<T>(T Function() create) {
  return create();
}

void main() {
  Person value = create(Person.new);
  print(value.runtimeType);
}
```

**Comment by lrhn** [comment]
What @julemand101 says.
Dart type parameters, like `<T>` only pass *types*, not *classes* or their static namespaces. You cannot access static methods or constructors through the type variable. It wouldn't be sound, because the type may not have that constructor.
