### ISSUE TITLE
let a callable object define `call` as a getter for a non-null Function type

### ISSUE THREAD

**Issue by TekExplorer** [dart-lang/language#4110]
I notice that, if i created a record like: `final it = (call: () {})`  and tried to call it with `it()` it fails.

but if I make an extension method that has a `call()` that forwards to a function record value, then it _is_ callable

dartpad errors and says that it isn't directly callable and that I can use .call, but the whole point of .call is the callable function-like syntax

A more specific example is that I was trying to emulate freezed's deep copy, which has `copyWith` actually be a getter returning an object that can be called like normal.

something in the shape of;
```dart
(...) get copyWith => (
  call: (Bar? bar) => Foo(bar ?? this.bar),
  bar: ... // some deep copy logic
);
```
which doesn't actually work at the call site.

i don't see why just calling a record wouldn't just be syntax sugar over invoking .call() for non-functions, so what am I missing?

**Comment by lrhn** [comment]
Implicit `call` invocation only works for methods, and record fields are getters.

This is a deliberate choice. It means that typed invocations don't have to worry about a getter returning another capable object, or before null safety getting a `null` value. A non-dynamic implicit `call` invocation can be implemented by inserting a single `.call`.

**Comment by TekExplorer** [comment]
ah, so its not specific to records?

Thats kind of annoying though.

it means that a: I need to manually define a `call` extension for every record I want to be used that way, and it means the same for if i want someone to "call" a class based on a generic function type, (`final T /* extends Function */ call;`) or B: i have to manually .call, which breaks the desired api.

surely it wouldn't need to "worry about a getter returning another capable object" if the static type of the getter is a non-nullable Function type? i don't mind if it doesn't allow `Callable get call;`, that's confusing anyway and probably bad code, but just Function types would give more options for API. otherwise, i'd need to make an extension method every time, which is kind of painful.

**Comment by TekExplorer** [comment]
a note: i would naively assume that callables `thing()` are just syntax sugar for `thing.call()`, which is clearly not true as this would work otherwise.

course, my naive "solution" would be to expand all `thing()` into `thing.call()` which does nothing to functions and method-callables, and just sort of works for getter types

**Comment by lrhn** [comment]
Yes, `thing()` is syntactic sugar for `thing.call()` *if and only if `thing` has a `call` method*.

This ensures that `thing.call` has a function type, and that doing the tear-off does not invoke any user code.
A getter could be typed as `Function` or `dynamic` or another class with a `call` member, and could do anything *while* creating that value.

I believe there are bugs that make `dynamic` invocations actually call getters on some (even most) platforms. That's not intended behavior. Even in a dynamic invocation, `(thing as dynamic)()` should act like `(thing as T)()` where `T` is the runtime type of `thing`, except that what would be static errors in the typed invocation are runtime errors in the dynamic invocation.

> i don't mind if it doesn't allow `Callable get call`

Why not?
If a `Callable` object is not as good as a function here, why is it as good as a function in a direct call?

The distinction between "method or not" is easy to make. If we have to distinguish between the return types of getters, then it becomes more complicated, and having to match those rules in dynamic invocations may be prohibitive.

If I have:
```dart
class C<T> {
  final T call;
  C(this.call);
}
var f = C<int Function(int)>((x) => x);
var g = f as C<Function>;
var o = f as C<Object>;
var d = f as C<dynamic>;
var sd = f as dynamic;
var so = C<Object>((int x) => x) as dynamic;
void main() {
  f(1);
  g(1);
  o(1);
  d(1);
  sd(1);
  so(1);
}
```
then which of those calls are valid?
(I can say that if "Callable" means having a method or a *function typed* getter, then `g(1)` shouldn't be allowed, `o(1)` should never be allowed, and ... well, as specified `d(1)` is also allowed, `dynamic` is not a function type. We may want "assignable to a function type" instead and allow `dynamic`?
The `sd(1)` will run.
The `so(1)` ... well, that depends. Should the static call have to check the *declared* return type of the `call` getter, or should it use the runtime type of the value. The former would be the consistent behavior, it's also more expensive.

>  if the static type of the getter is a non-nullable Function type?

The getter can still have arbitrary side-effects, and the specified behavior also has to work for dynamic invocations where nobody knows the declared type of the getter, and all that matters is which object it returns. Unless we actually have to check the return type of the getter, which would be really annoying, but the right thing to do.


"Methods only" is clear, there are no tricky edge cases.
It doesn't allow you to mock being a function using a getter, but that was not a goal to begin with.
Or to make a record pretend to be an object with methods. Just make a class to get that.

**Comment by TekExplorer** [comment]
- f: works. is a function
- g: works. is a function
- o: doesnt work - call returns an `Object`
- d: works - calls .call, which returns a dynamic. value happens to be a function, which works. if it _isnt_ a function, it throws.
- sd: works, .call statically exists. see d
- so: dynamically calls `call` as a getter. result is a Function. works.

do arbitrary side effects matter? i'd argue that's on the dev. would be easier if we could wrap the function itself dynamically, but that's a different issue.

> If a Callable object is not as good as a function here, why is it as good as a function in a direct call?

because its not a function. the syntax sugar has happened. it has occurred. it is done. we expect a Function, not an object. _nested_ callables is the result of bad code, in my opinion, and very difficult to logic around.

as mentioned above, dynamic invocations can be pretty simple.
for a `(x as dynamic)()`, we do `(x.call as Function).actuallyLiterallyInvoke()`
for a `Generic<call>` such that `Generic<dynamic>`, `(x as Generic<dynamic>)()` we do `(x.call as Function).actuallyLiterallyInvoke()`

we wouldn't even need to do anything to methods, since if we treat .call as a getter that expects a Function, it just works.

> It doesn't allow you to mock being a function using a getter, but that was not a goal to begin with.

that would be nice, but I can understand why that would be especially complicated. _this_ issue is about the `thing()` => `thing.call()` syntax sugar.

we can go ahead and ignore records for now, and focus more on generic function types with the name of `call`

I would say that, I would be satisfied with either
- the syntax sugar accepting this outright (this issue, and likely a simpler change)

or
- make it possible to generic-ize a method's parameters so we can forward them to the actual function stored somewhere. (field, map, provider, whatever) (a different issue entirely, likely involving record-type parameter lists.)

which would make it actually viable to have a callable with different parameters based on the generic, instead of requiring a subtype for every version via macros, which gets messy - especially when that's the only outwards facing difference, and the actual data might be in the same shape otherwise.

**Comment by munificent** [comment]
> it means that a: I need to manually define a `call` extension for every record I want to be used that way,

In short, yes. I think you're going against the grain of the language. Records are really intended to be used as data structures. If you want to use them more like prototype-based object-oriented programming, they are never going to do that job well. That's not what they're designed for.

Of course, it would be reasonable to design them to be used that way. But, ultimately, any programming language exists to have some opinions about how code should be modeled. And in Dart, the opinion is that if you want objects and behavior, that's what class declarations are for, and that's how the language works best.

Honestly, `.call()` and allowing objects to be used in functions in Dart was always a weird feature, was done well before Dart 2.0 when we had a much looser type system, and doesn't make much sense in Dart today. If we could, we would probably remove it entirely, but it's too breaking to do so.

**Comment by TekExplorer** [comment]
> > it means that a: I need to manually define a `call` extension for every record I want to be used that way,
> 
> In short, yes. I think you're going against the grain of the language. Records are really intended to be used as data structures. If you want to use them more like prototype-based object-oriented programming, they are never going to do that job well. That's not what they're designed for.
> 
> Of course, it would be reasonable to design them to be used that way. But, ultimately, any programming language exists to have some opinions about how code should be modeled. And in Dart, the opinion is that if you want objects and behavior, that's what class declarations are for, and that's how the language works best.
> 
> Honestly, `.call()` and allowing objects to be used in functions in Dart was always a weird feature, was done well before Dart 2.0 when we had a much looser type system, and doesn't make much sense in Dart today. If we could, we would probably remove it entirely, but it's too breaking to do so.
> 
> I'm going to go ahead and close this because it's very unlikely we're going to make `.call()` _more_ useful.

I don't really agree.

Callable objects are a normal thing to want and have - it lets you do awesome things like give "modifiers" (and sidecar functions and data) to what you would otherwise only consider as a function in most cases. it _is_ a function, until I need that one feature.

Without callables, I either need to nest the function in a class "normally", putting it at the same level as the rest, or sidecar another function or class.

Rust does this _beautifully_ with their Fn traits.

Dart just... seems inconsistent.

honestly, sometimes I end up wanting to have only closure variables instead of methods so I don't need to forward a method call to a stored function. I mean honestly, just look at `_IOOverridesScope` as an example. its one of the most bloated classes I've ever seen, and its just forwarding functions.

and while I can understand avoiding user code for a .call getter... don't. just let them do it. i think its a feature that's more valuable than it is likely to be abused.

**Comment by lrhn** [comment]
Maybe I'm biased, but I like that there is a clear distinction between functions values and class instances.
Having a function that is *also* a class instance lets you piggy-back data through an API that only allows functions, but that's almost always a *bad* idea. It means there is something at the other end which receives the function, typed as a function, and then tries to downcast it to the type it was expected to have. (Which works, but doing unconditional downcast is dangerous, and doing type-checks for downcasts is bad OO modelling.)
That's not special to functions, though, you shouldn't subclass an API type and then downcast it at the other end of the API either. I've seen that done with `Future` too.
(On the other hand, it's not like it's significantly worse design than having a map or `Expando` on the side, so if you're going to do it anyway, maybe we should just let you.)

The real issue that made Dart 2.0 not let classes have function types, is that Dart doesn't have contravariant generics.
A class like:
```dart
class Mapping<R extends Object, P> {
  Map<P, R> _mapping;
  Mapping(this._mapping);
  R call(P key) => _mapping[key] ?? (throw StateError("No value");
  bool hasValueFor(P key) => _mapping.hasKey(key);
}

```
cannot implement `R Function(P)`, because the parameter covariance goes in the wrong direction.
```dart
Mapping<num, num> map = Mapping<num, num>(...);
Mapping<Object, num> omap = map; // upcast.
Function(String, num) fmap = omap; // upcast.
``` 
(Although I guess the `call` method will be covariant-by-generics, so it accepts `Object?` and throws if it's not a `num`.
I remember there being something even more insidious, where we could go up and down in the type system and end up with something that was unsound and which didn't insert any type check.)

The biggest reason to not let `call`, or methods in general, be getters is that it hurts performance. Possibly even if you don't use it, unless the compiler can see that this function call (at this type) cannot possibly hit a getter.
If it can't, an instance member invocations is no longer a simple V-table invocations, it has  to read the getter, then call the object. Which may again be a callable object. Method invocation becomes more expensive if the compiler cannot assume that a method is just a method.
Having a clear separation between functions and objects allows optimizations.

**Comment by TekExplorer** [comment]
I suppose that makes sense, it can be more trouble than it's worth to make getter symmetry work for methods as the language stands.

That said, I do feel like we can do better at least for same-signature-forwarding, but I think that's a different issue.


That said, the .call thing... I don't see it. Frankly, I'm not sure that all of that optimization has anything to do with the .call sugar.

What exactly is stopping you from having the intermediary code just insert .call and let the resulting code be whatever it wants to be? We don't need to *do* anything, because it's just sugar.

It's not as if you couldn't have done .call() where call is a getter, so there's no real impact to optimization.

If it's a method, it gets vtable optimization, if not, then it aquires an object and calls it.

Normal stuff we can already do, just fancier. It just frustrates me that I need to work around this for what should be a straightforward convenience, which then results in me getting frustrated about passing parameters wholesale to the "real" function, which as I said is a different issue, and results in a pointlessly extra member that's just *adding* complexity, since the getter-call is happening *anyway* just elsewhere.

**Comment by munificent** [comment]
> It's not as if you couldn't have done .call() where call is a getter, so there's no real impact to optimization.

I think you're saying that whenever the language sees an expression followed by `(...)`, it inserts `.call`, so `foo(...)` becomes `foo.call(...)`. But if we also do that for getters, including getters which may be named `call`, then that means that `foo.call(...)` should also become `foo.call.call(...)`, which should become `foo.call.call.call(...)`, ad infinitum.

This is not just me being contrary. My recollection is that most Dart compilers would *not* do that if `call` turned out to be a getter, but DDC *would* just recursively iteratively invoke `call` on the result of the calling the `call` getter until it eventually (hopefully!) bottomed out on something that was a function.

The semantics for "just stick a `.call` in there" get *really* weird.

**Comment by TekExplorer** [comment]
> > It's not as if you couldn't have done .call() where call is a getter, so there's no real impact to optimization.
> 
> I think you're saying that whenever the language sees an expression followed by `(...)`, it inserts `.call`, so `foo(...)` becomes `foo.call(...)`. But if we also do that for getters, including getters which may be named `call`, then that means that `foo.call(...)` should also become `foo.call.call(...)`, which should become `foo.call.call.call(...)`, ad infinitum.
> 
> This is not just me being contrary. My recollection is that most Dart compilers would *not* do that if `call` turned out to be a getter, but DDC *would* just recursively iteratively invoke `call` on the result of the calling the `call` getter until it eventually (hopefully!) bottomed out on something that was a function.
> 
> The semantics for "just stick a `.call` in there" get *really* weird.
> 

It should only be allowed to be one layer deep

These are intuitively the same to me, as far as calling them should be concerned.
```dart
typedef VoidCallback = void Function();
class Foo {
  // Good, currently works
  void call();
}
class Foo2 {
  // Good, desired.
  VoidCallback call;
}
class Foo3 {
  // Bad, `get` the function instead
  Foo call;
}
class Foo4 {
  Foo foo;
  // Sure. Invoking the getter gives a function
  VoidCallback get call => foo.call;
}
```
Honestly, it should be simple enough. None of that should even matter - if it's a method, good. If it's a getter, check it's static type. Is it a function type? Allow it. Callable? Nope. Too deep. Anything else? Nope, not a function.

In all honesty, it's the cheapest possible thing we can do to enable apis like `thing()` and `thing.modifier()` while also allowing user-defined function shapes.

The more expensive option being to empower types enough to allow specifying the argument  list as its own type a-la records, which is a separate issue.

As it is, riverpods prospective v3 syntax is forced to have mutation state references and mutation invocations be on separate identifiers
```dart
class FooProvider with Provider<Foo> {
  late final create = ...

  late final deleteMut = mutation<void>();
  MutationCall<void> delete(p0, {param}) => mutate(deleteMut, (ref) async {
  // Do stuff
});
  // Used as
  // final state = ref.watch(fooProvider.deleteMut);
  // ref.invoke(fooProvider.delete(7, cond: 'str'))

  // Desired
  // Note the user defined params
  late final delete = mutation((p0, {param}) => (ref) {
    // Do stuff 
  });
  // Used as
  // final state = ref.watch(fooProvider.delete);
  // ref.invoke(fooProvider.delete(7, cond: 'str'))
}
```
Notice the shared name?
As it is, it's possible to make a custom class that allows this, but that's a lot of boilerplate.

We could do:
```dart
ref.watch(fooProvider.delete);
ref.watch(fooProvider.delete.run(0, cond: true));
```
But that's just changes the problem to worse UX

Alternatively, we could define a class that forwards a parameter, but now we're limited to exactly that shape, which is an even worse UX - call it the "riverpod family problem", if you would, which was only resolved with code gen prior.

Technically, families are fixed with the new syntax, but we _cant_ do the same with mutations.

I'm beginning to wonder if we need a pre-processor to be honest.
