### ISSUE TITLE
Add StringView / substring by reference to core library

### ISSUE THREAD

**Issue by hydro63** [dart-lang/language#4119]
I think it would be nice having a way to do substring without copying the entire string, thereby causing a both memory and performence overhead.
### Problem to solve
The problem that it solves is the fact that currently, the substring method copies the whole buffer of the string. This copying can potentially take a lot of time and allocate a lot of unnecessary resources, that have to be then collected. It can slow down the program significantly.

### Definition
The `StringView` would have all the same definitions of `String`, but instead of copying the whole buffer, it would just reference to the original / base string with some offset, with adjusted length. Strings are already immutable by default, meaning there is no problem with sideeffects that would potentially cause bugs.
```dart
class StringView extends String{
  String _base;
  int _length;
  int _start = 0;
  StringView(this._base) : _length = _base.length;
  StringView.from(this._base, this._start, this._end) : _length = _end - _start;

  @override
  String substring(int start, [int end]){
    if(end == null) end = _length;
    return StringView.from(_base, _start + start, _start + end);
  }

  @override
  bool operator==(String right){
    // ...
  }

  @override
  String operator[](int index){
    if(index >= _length || index < 0) throw RangeError();
    return _base[index];
  }
  
  // other things implemented;
}

var view = StringView(input);
view = view.substring(1); // start = 1
view = view.substring(1); // start = 2
```
### Motivation
The reason i brought it up was because i was doing some parsing, and i wanted to tokenize a string by continuously finding tokens and eating them from the start with `str.substring(1)`.
```dart
// if we use substring, the performence is horrible
// with StringView, there is no copying of the buffer, hence no significant slowdown
List<Token> tokenize(String input){
  var buffer = StringView(input);
  var tokens = <Token>[];
  Token? tokenIdent();
  Token? tokenString();
  Token? tokenWhite();
  Token? tokenNumber();
  // ...
  
  while(buffer.length > 0){
    Token? foundToken;
    if(tokenIdent() case var tok?) foundToken = tok;
    else if(tokenString() case var tok?) foundToken = tok;
    else if(tokenWhite() case var tok?) foundToken = tok;
    else if(tokenIdent() case var tok?) foundToken = tok;
    else throw "Unrecognised character > ${input[0]}";
    input = buffer.substring(foundToken.end);
  }

  return tokens;
}
```
It could also be used in conjuction with `RegExp` like `^\s+`, so that the `^` character refers to the start of the view, not start of the string. Currently:
```dart
var reg = RegExp("^hello");
reg.allMatches("hellohello", 0).firstOrNull // -> RegExpMatch
reg.allMatches("hellohello", 2).firstOrNull // -> null
reg.allMatches("hellohello", 5).firstOrNull // -> null <= I expected RegExpMatch, since it starts matching from index 5;
```

**Comment by rrousselGit** [comment]
This is more of an SDK issue than a language issue.


You should be able to use `extension type` to build your own StringView if you wished.

**Comment by hydro63** [comment]
@rrousselGit I am not able to add it myself, since String is a `final` class and i need to be able to use it with regex and other functions as a plain `String`. Since i want to be able to use it with regex, i cant do it with extensions, since extensions cant override the defined behaviour

PS > I will probably move this issue to the SDK repo, thanks for the suggestion
