### ISSUE TITLE
exporting files  in a single record and destructring each member

### ISSUE THREAD

**Issue by sanba-anass** [dart-lang/language#4122]
```dart  

  export (  'file1.dart', 'file2.dart ', 'file3.dart'  );
  final ( foo ,bar , baz )  = import('file.dart'); 

```

**Comment by hydro63** [comment]
Huh? Before posting some code, please explain the problem, the desired behaviour, and the proposed syntax.

PS > you can add syntax highlighting by doing \`\`\`dart ... \`\`\` instead of just \`\`\` ... \`\`\`

**Comment by lrhn** [comment]
As @hydro63 says:
Why? What problem are your trying to solve?
What? What does this syntax do?

Do the two lines occur in the same library?

If I guess currently at every question, My guess is that nested and exported namespaces, and a rename modifier on imports, would do what this is asking for, and be a better match for the current syntax. Unless it's also looking for local imports.
