### ISSUE TITLE
Map with Class has lower memory footprint than Map with Tuple - strange result 

### ISSUE THREAD

**Issue by AdamTechAcc** [dart-lang/language#4133]
Hello,

I'm searching for an optimal structure for caching user's online status in my app. I'm trying to find best solution to store up to 100 000 or even 1 000 000 records. 

I tried to check memory footprint for that. 

My first, natural option was:

```
class OnlineStatus {
  final bool isOnline;
  final DateTime timestamp;

  const OnlineStatus(this.isOnline, this.timestamp);
}

```
and creating Map:

`Map<int, OnlineStatus>`

My test is:

``
  final Map<int, OnlineStatus> _userOnlineStatus = {};

  for (int i = 0; i < nSize; i++) {
    _userOnlineStatus[i] = OnlineStatus(i % 2 == 0,
        DateTime.now().add(Duration(seconds: Random().nextInt(randomSize))));
  }
``

I checked memory footprint for my dart app process (builded on mac os x using command: dart compile exe app.dart -o app)

ps -o rss,vsz,pid,command -p PID
vmmap PID

Memory footprint was (1m elements):

```
Physical footprint:         102.2M
Physical footprint (peak):  102.3M
```

I thought that I can lower memory usage by simply changing class OnlineStatus to Tuple (bool, DateTime). 

I changed Map definition to:

`Map<int, (bool, DateTime)>`

and tested using the same method:

```
  final Map<int, (bool, DateTime)> _userOnlineStatus = {};

  for (int i = 0; i < nSize; i++) {
    _userOnlineStatus[i] = (
      i % 2 == 0,
      DateTime.now().add(Duration(seconds: Random().nextInt(randomSize))),
    );
  }
```

Memory footprint for theoretically simplest type (Tuple) was (1m elements):

```
Physical footprint:         188.3M
Physical footprint (peak):  190.7M
```

**100MB (Map<int, OnlineStatus>) vs 190MB (Map<int, (bool, DateTime)>)**

It's a strange result for me. Why Tuple hasn't a lower memory footprint?

❯ dart --version
Dart SDK version: 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64"

**Comment by mraleph** [comment]
> Why Tuple hasn't a lower memory footprint?

Why do you expect a record would have a lower memory footprint? Is there something in the documentation that lead you to this conclusion? Because if it was - then we need to fix this.

Record objects (as currently implemented) carry around additional information about their shape and field types - two additional fields. So they are larger then classes.

**Comment by scheglov** [comment]
You could use extension types to pack both the flag, and the `DataTime` information into a single `int`.

If there are many such objects, you also want to put these `int` objects into a single `Uint64List`, and create extension type wrapper on demand. If you want to take a hit on the time precision, you probably can pack it into `Uint32List`.

```dart
// @dart = 3.5

main() {
  var status = OnlineStatus(true, DateTime(2024, 10, 20, 16, 17, 23));
  print(status.isOnline);
  print(status.since);
}

extension type OnlineStatus._(int _packed) {
  static const int _milliseconds20240101 = 1704096000000;
  static const int _milliseconds100years = 100 * 365 * 24 * 3600 * 1000;

  factory OnlineStatus(bool isOnline, DateTime since) {
    var sinceMilliseconds = since.millisecondsSinceEpoch;
    var since20240101 = sinceMilliseconds - _milliseconds20240101;
    assert(since20240101 >= 0);
    assert(since20240101 < _milliseconds100years);
    var packed = (since20240101 << 1) | (isOnline ? 0x1 : 0x0);
    return OnlineStatus._(packed);
  }

  bool get isOnline {
    return (_packed & 0x1) != 0;
  }

  DateTime get since {
    var since20240101 = _packed >> 1;
    var milliseconds = _milliseconds20240101 + since20240101;
    return DateTime.fromMillisecondsSinceEpoch(milliseconds);
  }
}
```
