### ISSUE TITLE
Is there a reason why Iterable<E>.whereType<T> does not bound T to `extends E`?

### ISSUE THREAD

**Issue by FabrizioG202** [dart-lang/language#4134]
This is really just a minor inconvenience with the Iterable's API.

Take for example the following code snippet:

```
class WithInt {
  WithInt(this.a);
  final int a;
}

void main() {
  final objects = <WithInt>[
    WithInt(0),
    WithInt(1),
    WithInt(2),
    WithInt(3),
    WithInt(4)
  ];
  final sum = objects.whereType<int>().fold(0.0, (a, b) => a + b);
  print(sum);
}
```

We should know at compile time that the filtered iterable will always be empty since int is not a subtype of `WithInt`. This is a trivial example, but I found out that in more complex scenarios, especially when adding wrapper classes (such as WithInt) the code still compiles fine but suddenly filtering always yields no results. 

I was wondering, since dart supports syntax like `<T extends E>` while declaring type parameters on functions, why is this not used in the signature of the whereType method? Having something like that would make it so that the code above does not compile. Moreover, it looks like it should be a relatively easy fix.

Is there a reason behind this design?

**Comment by mateusfccp** [comment]
You don't always want this behavior. Bounding `T` to `T` extends `E` would prevent one to check against a supertype instead of a subtype.

**Comment by tatumizer** [comment]
You don't need a complicated example to demonstrate the phenomenon.
```dart
  if ("Hello" is int) { // no warning, no error
     print(0);
   }
/
```
in contrast
```dart
  if (!true) { // warning: dead code blah blah
    
  }
```
