### ISSUE TITLE
Enforce Generic Type Requirement for Raw Type Usage

### ISSUE THREAD

**Issue by stan-at-work** [dart-lang/language#4145]
### Description
In Dart/Flutter, I have a class that requires a generic type parameter, which must be provided when the class is used.

Example:

```dart
class CoreLoadFilterRepItemDefFromStorageIdentifier<STATE extends CoreBaseFilterState<STATE, CoreFilter>> extends CoreBaseIdentifier {
  CoreLoadFilterRepItemDefFromStorageIdentifier() 
      : super(ValueKey('CoreLoadFilterRepItemDefFromStorageIdentifier.${STATE.runtimeType}'));
}
```

Currently, the compiler enforces this requirement when an instance of the class is created without specifying a generic type. This throws an error, as expected:

![Type error](https://github.com/user-attachments/assets/0a7ff1e4-69a0-4361-b165-947216f7d89d)

### Issue
However, this check only occurs when an instance is created. If I use the class **as a raw type** (e.g., in a `Set<Type>`), no error is thrown, even if the generic type is not specified.

Example:

```dart
const {
  CoreUpdateFilterIdentifier<PickRitFilterCubitState>,
  CoreLoadFilterIdentifier<PickRitFilterCubitState>,
  CoreLoadFilterRepItemDefFromStorageIdentifier, // Should throw error but does not!
}
```

In this case, `CoreLoadFilterRepItemDefFromStorageIdentifier` should ideally throw an error for missing the required generic type, but it does not, because the check is bypassed when the type is used as a literal rather than an instance.

### Proposal
I propose that the generic type requirement check should also apply when a class is used as a raw type in contexts such as `Set<Type>` or other literals. This would enforce type safety consistently and prevent potential runtime issues.

---

Here’s an ideal example that demonstrates the desired behavior for enforcing generic types both when creating an instance and when using the type in a literal context.

### Desired Behavior Example

Suppose we have a class, `CoreLoadFilterRepItemDefFromStorageIdentifier`, which requires a generic type `STATE`:

```dart
class CoreLoadFilterRepItemDefFromStorageIdentifier<STATE extends CoreBaseFilterState<STATE, CoreFilter>> 
    extends CoreBaseIdentifier {
  CoreLoadFilterRepItemDefFromStorageIdentifier() 
      : super(ValueKey('CoreLoadFilterRepItemDefFromStorageIdentifier.${STATE.runtimeType}'));
}
```

#### 1. **Instance Creation with Missing Generic Type** – Correct Behavior
If we attempt to create an instance without specifying the generic type, the compiler should (and currently does) throw an error:

```dart
// This should throw an error because STATE is missing.
var myInstance = CoreLoadFilterRepItemDefFromStorageIdentifier();
```

Expected Compiler Error:
```
Error: The class 'CoreLoadFilterRepItemDefFromStorageIdentifier' requires a type argument for 'STATE'.
```

#### 2. **Using as Raw Type in Literal Collection** – Desired Behavior
When using `CoreLoadFilterRepItemDefFromStorageIdentifier` as a type in a `Set<Type>` or other collection literal without the required generic type, this should **also throw a compile-time error**, enforcing consistent type checking.

```dart
const Set<Type> identifiers = {
  CoreUpdateFilterIdentifier<PickRitFilterCubitState>,
  CoreLoadFilterIdentifier<PickRitFilterCubitState>,
  CoreLoadFilterRepItemDefFromStorageIdentifier, // Should throw error: missing <STATE> generic type!
};
```

Expected Compiler Error:
```
Error: The class 'CoreLoadFilterRepItemDefFromStorageIdentifier' requires a type argument for 'STATE' when used as a raw type.
```

#### 3. **Correct Usage with Specified Generic Type**
The correct usage would involve specifying the generic type even when used in a literal, ensuring type safety and avoiding potential runtime issues.

```dart
const Set<Type> identifiers = {
  CoreUpdateFilterIdentifier<PickRitFilterCubitState>,
  CoreLoadFilterIdentifier<PickRitFilterCubitState>,
  CoreLoadFilterRepItemDefFromStorageIdentifier<MyFilterState>, // Correct usage with generic type.
};
```

This behavior would ensure that generic type parameters are consistently enforced both for instance creation and when using types in raw form, improving type safety and code reliability.

**Comment by lrhn** [comment]
The language doesn't have any notion of "required type parameter", the only reason you get an error in the object instantiation case is that the type parameter is F-bounded (it's bound texted to the parameter itself), so the type inference cannot find a valid solution.

You don't get that error for type objects because types, unlike instances, are allowed to not satisfy the bound and be "super bounded".

The existing way to be warned about boot providing type arguments to types is they lint/mode [`strict_raw_types`](https://dart.dev/tools/analysis#enabling-additional-type-checks).
You can enable that, but you can't force your code's clients to do so.

**Comment by stan-at-work** [comment]
> The language doesn't have any notion of "required type parameter", the only reason you get an error in the object instantiation case is that the type parameter is F-bounded (it's bound texted to the parameter itself), so the type inference cannot find a valid solution.
> 
> You don't get that error for type objects because types, unlike instances, are allowed to not satisfy the bound and be "super bounded".
> 
> The existing way to be warned about boot providing type arguments to types is they lint/mode [`strict_raw_types`](https://dart.dev/tools/analysis#enabling-additional-type-checks). You can enable that, but you can't force your code's clients to do so.

Oke, thanks for the strict_raw_types suggestion 👍
