### ISSUE TITLE
How to use typedef inside a class with Generics?

### ISSUE THREAD

**Issue by tolotrasamuel** [dart-lang/language#4151]
How to use typedef with generics ? 

How to use typedef inside a class ?

I have the following class. 

    class Bar<T> {
      void bar() {
        print(T);
      }
    }
    
    class Foo<T> {
      Bar<T> merge(Bar<T> a, Bar<T> b, Bar<T> c) {
        a.bar();
        b.bar();
        return c;
      }
    }

To avoid repeating `Bar<T>` I want to use `typedef`

    
    class Foo<T> {

      typedef Baz = Bar<T>;
      
      Baz merge(Baz a, Baz b, Baz c) {
        a.bar();
        b.bar();
        return c;
      }
    }

But this is obviously not working with the current Dart. Is it supported ? I know I create an alias of the Bar to a shorter string but this does not remove the generic, the problem is in reality, the generic has several nested class like `Foo<Bar<Baz<Foz<Boz<T>>>>`

**Comment by mateusfccp** [comment]
> How to use typedef with generics ?

```dart
typedef Foo<T> = Bar<T>;
```

> How to use typedef inside a class ?

That's not possible, by definition.

A type alias is a top-level declaration, which means it can only appear [sic] in the top-level scope.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/27696e3c-ff84-4af5-9166-b4ba624ac4a4">

There's already an issue for this case: #2952, so I think this can be closed.
