### ISSUE TITLE
Proposal: Introduce <- operator for clean and composable transformations

### ISSUE THREAD

**Issue by andpush** [dart-lang/language#4170]
### Abstract
This proposal suggests adding the **<-** operator to Dart to facilitate concise and readable functional transformations. The operator allows for left-to-right application of functions to values, enhancing code composability and readability without adding undue complexity.
### Motivation
Dart lacks a concise syntax for chaining value transformations in a functional style. While the cascade operator (..) aids in object configuration (similar to Kotlin's apply), there is no equivalent for transforming values (like Kotlin's let). Introducing the <- operator addresses this gap, allowing developers to write more expressive and maintainable code.
#### Syntax
`expression <- function`
#### Behavior
- The left-hand expression is evaluated and passed as the first argument to the right-hand function.
- The operator supports chaining, enabling multiple transformations in a left-to-right flow.
#### Examples
```
var result = someString <- toUpperCase;
// Equivalent to:
// var result = toUpperCase(someString);
```
```
// lambdas can be used for more complex applications:
var result = someString
    <- toUpperCase
    <- (s) => '$s is amazing'
    <- print;
// Equivalent to:
// print('$toUpperCase(someString) is amazing');
```
```
// Handling multiple arguments
var result = value <- (v) => someFunction(v, additionalArg);
// Equivalent to:
// var result = someFunction(value, additionalArg);
```
```
// Handling curried functions
int add(int x, int y) => x + y;
var curriedAdd = (x) => (y) => add(x, y);
var result = 5 <- curriedAdd(10); // Result: 15
// Equivalent to:
// var result = curriedAdd(10)(5);
```
#### Benefits
- Improves readability by eliminating nested parentheses
- Makes the transformation pipeline clear and linear
- Improves composability
Compare:
`print(appendExclamation(toUpperCase(someString)));`
vs
`someString <- toUpperCase <- appendExclamation <- print;`
#### Choice of <-
- Visually applying expression on the left hence the left <- arrow
- Haskell pipeline operator |> looks not intuitive to me, << and >> may resemble bitwise operations
#### Precedence
- The <- operator has lower precedence than method invocation (.) and function calls (), but higher than assignment
- The operator is left-associative, ensuring expressions are evaluated from left to right

What do you think? 
Thanks!

**Comment by julemand101** [comment]
While different suggested syntax, it might be related to: https://github.com/dart-lang/language/issues/1246

**Comment by andpush** [comment]
Thank you for reviewing, I agree, it looks duplicate. 
The operator itself does not matter that much. For me -> would also be fine, though the opposite direction imo reflected the inversion of function and its argument. Also my variant avoided confusion with C++ arrow operator. Whatever the syntax hope that the functionality fits the Dart spirit and some day will be implemented.

**Comment by D-a-n-i-l-o** [comment]
Just in case somebody is wondering, the following functional style is already possible:

```dart
  "someString"
    .upperCase
    .map((s) => '$s is amazing')
    .print;
```

Example:
```dart
import 'dart:core';
import 'dart:core' as core;

void main() {
  print( 1.plus(2).plus(3) );
  print( 2.5.plus(2.6) );
  
  1.plus(2).plus(3).print;
  2.5.plus(2.6).print;
  
  ("-"*30).print;
  
  "aBcDeFg".upperCase.appendExclamation.print;

  ("-"*30).print;

  100.print;
  1.1.print;
  (1,2).print;

  ("-"*30).print;
  
  (8,7).add.print;
  (1.5,2.5).add.print;
  
  ("-"*30).print;
  
  final numbers = [1, 5, 10, 100];
  final result1 = numbers.map((num) => num * 3);
  result1.print;
  
  [1, 5, 10, 100].map((num) => num * 4).print;

  ("-"*30).print;
  
  "someString"
    .upperCase
    .map((s) => '$s is amazing')
    .print;

  ("-"*30).print;
  
  // Handling curried functions
  var result2 = 5.curriedAdd(10); // Result: 15
  var result3 = curriedAdd(6,11); // Result: 17
  result2.print;
  result3.print;
}

num add(num x, num y) => x + y;
num curriedAdd(x,y) => add(x, y);

extension on num {
  num      plus(num x) => this + x;
  void get print => core.print(this); // as getter
  //void     print() => core.print(this); // as function
  num curriedAdd(y) => add(this, y);
}

extension on String {
  String get upperCase => this.toUpperCase();
  String get appendExclamation => this+"!";
  void   get print => core.print(this);
  String map(String f(String input)) => f(this);
}

extension Printer<T> on T {
  void get print => core.print(this);
}

extension on (num,num) {
  num get add => this.$1 + this.$2;
}
```
