### ISSUE TITLE
Allow returning a value from a generator

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/language#4181]
It would be nice if `return x;` in a generator was syntactic sugar for `yield x; return;`. I'm currently writing a generator that has a chain of exit conditions like this:

```Dart
Iterable<int> generator() sync* {
  if (earlyExitCondition1) {
    yield 123;
    return;
  }

  if (earlyExitCondition2) {
    yield 456;
    return;
  }

  // ...
}
```

It could become:

```Dart
Iterable<int> generator() sync* {
  if (earlyExitCondition1) return 123;
  if (earlyExitCondition2) return 456;

  // ...
}
```

We could also consider `return* x;` as syntactic sugar for `yield* x; return;`.

**Comment by ykmnkmi** [comment]
`return yield 123;`?

**Comment by lrhn** [comment]
That sounds like a very small saving for a syntax that mixes idioms and night hide a mistake.

The rule that you can't have `return e;` in a generator ensures that you don't  convert a non-generator function to a generator, and then forget to remove a `return someIterable;`, or any number of other mistakes.

Having to write `yield e; return;` on two lines isn't a big enough cost that it makes sense to spend resources, and opportunity cost, on allowing you to write `return e;` instead. It's also not readable, it looks like it does something else, and writing `return yield e;` to make it clear is when less of a syntactic reduction. 

That is: I can pretty much guaranteed that this is not going to happen.

You can write your code as:
```dart
noEarlyExit:
{
  if (earlyExitCondition1) {
    yield response1;
  } else if (earlyExitCondition2) {
    yield response2;
  } else if (earlyExitCondition3) {
    yield response3;
  } else {
    break noEarlyExit;
  }
  return;
}
```
It's ok to be creative!

**Comment by munificent** [comment]
I think a problem with this is that it wouldn't be clear to users whether it behaves like an implicit *yield* or like a return from a non-generator. Given:

```dart
Iterable<Object> generator(bool early) sync* {
  if (early) return [1];
  yield 2;
}

main() {
  print(generator(true).toList());
}
```

I can see users being equally likely to expect that to print `[1]` or `[[1]]`. Without any clear reason to expect users to intuit one versus the other, I think it's better to force the user to be explicit.
