### ISSUE TITLE
Restrict Changes to Method Signatures When Overriding to Prevent Additional Optional Parameters

### ISSUE THREAD

**Issue by gsvianna** [dart-lang/language#4208]
## Description
Currently, Dart allows overridden methods to include additional optional parameters (`{}` or `[]`), which subtly alters the method signature compared to the base class. While this is functionally valid, it can lead to confusion and potential violations of the **Liskov Substitution Principle (LSP)**, especially in polymorphic scenarios.

Consider the following example:

```dart
class Parent {
  void greet(String name) {
    print("Hello, $name!");
  }
}

class Child extends Parent {
  @override
  void greet(String name, {String? title}) {
    print("Hello, ${title ?? ''} $name!");
  }
}

void main() {
  Parent parent = Child();
  parent.greet("Gustavo"); // Works: Hello, Gustavo!
// parent.greet("Gustavo", title: "Mr."); // ERROR: 'title' is not accessible!
}
```

In this case, the overridden method in `Child` introduces an additional optional parameter (`title`), but this parameter is **not accessible** when the method is invoked via a reference to the base class (`Parent`). This behavior can cause confusion for developers and tools like linters or static analyzers.

---

## Observed Problems

1. **Violation of the Liskov Substitution Principle (LSP):**  
   When overriding a method, it is expected to be substitutable in all contexts where the base class method is used. Adding optional parameters can lead to incompatibility in polymorphic scenarios.

2. **Confusion in Polymorphic Code:**  
   Additional optional parameters are not visible or usable when a method is called via a base class reference, which may lead to unexpected behavior.

3. **Challenges for Static Analysis Tools:**  
   Tools may struggle to interpret these subtle changes in method signatures, potentially leading to undetected issues or unexpected runtime errors.

---

## Proposed Solution

Restrict changes to method signatures when overriding methods, such that **no additional parameters (positional or named)** can be introduced in overridden methods. The compiler should throw an error or warning in these cases.

For example, the code above should result in an error such as:

```
Error: The overridden method 'greet' cannot introduce additional optional parameters compared to the base class method.
```

---

## Expected Impact

- Make the behavior of overridden methods more predictable and consistent with solid object-oriented programming principles.
- Prevent confusion caused by signature mismatches between base classes and subclasses.
- Improve compatibility for polymorphic use cases and enhance the reliability of static analysis tools.

---

## Additional Context

This proposal aims to align Dart with common object-oriented practices in languages like Java and C#, which enforce strict method signature consistency in overridden methods.

**Comment by julemand101** [comment]
This would be a huge breaking change for small theoretical benefits. The way it works now also have its benefits and by removing this, we are, in some cases, forced to make new methods instead of overriding which would cause API's needed to be redesigned and therefore package API's would need to changed which would require changes.

Very much against this proposal.

**Comment by rrousselGit** [comment]
This is probably more in the scope of a lint rule than a language change.

Static analysis should easily be able to warn when an override adds parameters to a method.
