### ISSUE TITLE
Default implementation of `Object.toString` is impediment for Exceptions

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/language#4209]
## The problem

I was using the package `flame_tiled` which parses xml files generated by the Tiled app and draws the results.  I was getting an exception when parsing the file, but the log to console and to the screen only read "Instance of 'Parsing Exception'".  With the stacktrace I was able to find the line of code generating the exception and see the exception class.  I noticed that it is taking in data related to the failure, but since it never overrode `Object.toString` that information was never reported back to me.  

By hacking the code in my `~/.pub-cache` I was able to edit the code and debug the problem.

code:
```dart
part of tiled;

class ParsingException implements Exception {
  final String name;
  final String? valueFound;
  final String reason;
  ParsingException(this.name, this.valueFound, this.reason);
}
```

screenshot:
<img width="801" alt="Screenshot 2024-12-16 at 9 46 57 AM" src="https://github.com/user-attachments/assets/4f0a34c1-5a94-47cf-b79c-381c1ea5332c" />

## Proposal

I think it is an error to subclass `Error` or `Exception` and not override `Object.toString`.  If someone wants the `Object.toString` they should explicitly have to opt into that, instead of getting it implicitly.  We should have an annotation that forces subclasses to override particular methods to accommodate for this case.

```dart
abstract interface class Exception {
  @force_override
  String toString();
}
```

## Alternatives considered

I don't think there is a good alternative using current language features.  Here are some thoughts:
1) Migrate people from using `Object.toString` by introducing a new abstract method, like `String what()`.  There is too much written code that relies on using `Object.toString`.
1) Make `Object.toString` abstract.  This is obviously super breaking.

**Comment by mateusfccp** [comment]
There's already an annotation that "requires" a method to be overriden: [`mustBeOverriden`](https://api.flutter.dev/flutter/meta/mustBeOverridden-constant.html).

Making it a change in the language/SDK would break the universe.

**Comment by gaaclarke** [comment]
> There's already an annotation that "requires" a method to be overriden: [`mustBeOverriden`](https://api.flutter.dev/flutter/meta/mustBeOverridden-constant.html).

Thanks, I'll move the suggestion to the sdk then.

**Comment by gaaclarke** [comment]
filed: https://github.com/dart-lang/sdk/issues/59729
