### ISSUE TITLE
Allow `return` in a `switch` expression

### ISSUE THREAD

**Issue by andrei-toterman** [dart-lang/language#4214]
This compiles just fine
```dart
void f(int x) {
  x = switch (x) {
      _ => throw Exception(),
  };
}
```
but this does not
```dart
void f(int x) {
  x = switch (x) {
      _ => return,
  };
}
```
But I think those should behave the same way, not assigning `x` any value and not caring about its type, since the function is about to be exited.

**Comment by julemand101** [comment]
I feel like this might be duplicate of https://github.com/dart-lang/language/issues/2025 or at least another case for that.

**Comment by andrei-toterman** [comment]
AH, yes, you are right. Thanks for pointing that out! I'll close this.
