### ISSUE TITLE
It is inconvenient to use a class by specifying only a single generic out of multiple

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#4217]
Consider a class with multiple generics, some with bounds, some without:

```dart
class Class<A extends num, B, C extends  Base> {}
```

Say we want to use `C` but only constraining one of those type-args, not all of them.
Currently we may have to do:

```dart
void function(
  Class<int, Object?, Base> parameter,
) {
  print(...);
}
```

Notice how, for the unused type-args, we have to use the broadest type to satisfy the constraints.   
This is quite tedious and possibly error prone. I've many times typed `Object` instead of `Object?` for instance, without doing it on purpose.   
It's also quite noisy. Only one of those constraints matter, but it's lost in the sea.

---

I think we'd benefit from an "I don't care" keyword here. Possibly `_` considering we'd use it in many other places.

We could have:

```dart
void function(
  Class<int, _, _> parameter,
) {
  print(...);
}
```

The closest we have is `dynamic`, but that's a bit misusing it.

**Comment by mateusfccp** [comment]
Duplicate of #1387?

**Comment by rrousselGit** [comment]
Indeed
