### ISSUE TITLE
Scope of extension methods

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#424]
The proposal for extension methods reads:

> Dart's static extension methods are scoped. They only apply to code where the extension itself is in scope. Being in scope means that the extension is declared or imported into a scope which is a parent scope of the current lexical scope.

Can an extension be "declared or imported" into any scope other than the library scope? If not, is this wording just future-proofing or does it serve another purpose?

**Comment by leafpetersen** [comment]
> Can an extension be "declared or imported" into any scope other than the library scope?

I think the answer is no, unless there's a technicality I'm missing.  You can bring an extension into scope by declaring it (at the top level only, we're not supporting function local extensions), or by importing it (either implicitly by importing an entire library, or via a "show" of the extension name).

**Comment by leafpetersen** [comment]
Closing, as I believe this is resolved.

**Comment by still-dreaming-1** [comment]
It would be nice if you could make certain extension methods only in scope within a specific block of code or only to one variable, sort of giving it a different role compared to other variables without actually recreating it as a different type.
