### ISSUE TITLE
Static extension methods: Should we allow `on Never`?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#437]
With NNBD we will have the type [`Never`](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#syntax).

It is a compile-time [error](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors) to access an instance member on a receiver of type `Never`.

We could allow for extension method invocations with a receiver expression whose static type is `Never`, but such an expression would never evaluate to an object (it would throw or loop forever), so the extension method invocation would never actually take place.

This could be taken to mean that we should make `extension E on Never ..` an error, too.

@lrhn, @leafpetersen, @munificent, WDYT?

**Comment by lrhn** [comment]
The current spec simply says that `extension E on Never` will never (ha-ha) be invoked. Since `Never` "has every member" (like dynamic, only at the other end of the type hierarchy), the typed member access will take precedence over any extension members.

This was implicitly assuming that we allowed invocations on `Never` (since it was dead code anyway). If we disallow the invocations, then the extension method spec should treat it more like `void` instead, which also disallows static member invocations because `voidTypedExpression.foo` is always an error (extensions or not, nobody should get the `void` typed value as `this` value).


If we allow the invocation to be *written* at all, then it becomes important that the arguments are not evaluated before the callee: `foo.returnsNever(shouldNotBeEvaluated)`. Here it is important that the `returnsNever` getter is evaluated *before* we evaluate the arguments. It becomes very visible if we don't.

So, I'd probably prefer to disallow any extension member invocation on an expression with type `Never` like we do on `void` already, rather than ignoring the extension member like we do for `dynamic`.

Either will work, though.

**Comment by eernstg** [comment]
> So, I'd probably prefer to disallow any extension member
> invocation on an expression with type `Never`

If we do that then it would make sense to say that `extension E on Never ..` is also an error.

**Comment by leafpetersen** [comment]
> If we do that then it would make sense to say that `extension E on Never ..` is also an error.

I don't really see any reason to disallow it.  It's not like someone is going to accidentally make an extension on `Never`.  It's not useful - lots of things aren't useful.

**Comment by eernstg** [comment]
We have made `extends dynamic` and a number of other special cases an error, presumably because the feature that would be the result of sorting out what it should mean wouldn't be useful.

But if we allow `extension E on Never ..`, shouldn't we also allow an invocation on a receiver of type `Never` to resolve as an extension method invocation?

**Comment by lrhn** [comment]
The `extends dynamic` is disallowed because `dynamic` is not a class, not because it's special. 

We allow `extension on T` for any type `T`, not just class or interface types, so disallowing `on Never` would be an explicit exception (`Never` is a type).

**Comment by eernstg** [comment]
You could just say that `dynamic` denotes the same class as `Object?`, which makes it much more "a class" than, say, `FutureOr`.

**Comment by leafpetersen** [comment]
There is some additional discussion of `Never` here: https://github.com/dart-lang/language/issues/262 .  Note that in the proposal there from @lrhn it is an error to call a method on error.  I'm not sure that's fully decided yet.

Specifically on the question of allowing `on Never`, I'm still opposed to making it an error.  It feels like a pointless special case that doesn't actually help users (probably doesn't hurt them but...).  Why disallow `on Never` but not `on List<Never>`?  What about `extension<T extends Never> on T` which is equivalent to `on Never`?  What about `extension<T> on T`, can `T` be instantiated to `Never` (e.g. via explicit instantiation, even if we say that `Never` has all methods and hence that you can't get it by implicit instantiation).

**Comment by eernstg** [comment]
OK, so we have a general preference for allowing `extension .. on Never`. Do you agree as well, @lrhn, @munificent?

The other question is whether it's an error to access a member of `Never`. If instance member accesses are allowed on a receiver of type `Never` at all, it seems likely that `Never` would "have all members, with all signatures", so no member access could ever be resolved as an extension method invocation. Alternatively (as proposed in #262, [here](https://github.com/dart-lang/language/issues/262#issue-419462407)), we could make instance member accesses an error and always proceed to resolve any member accesses to extension members (that is, from _any_ extension because `Never` always matches its `on` type).

**Comment by lrhn** [comment]
If we make accesses on `Never` an error (and I lean towards thinking we should), it would not fall through to checking extension members, same as for `void`.

**Comment by eernstg** [comment]
We could certainly choose to describe it as follows: `Never` has no members at all (breaking the normal rule that subtypes have member supersets, but `Never` can't follow normal rules anyway), so we proceed directly and try to resolve any member accesses as extension members.

Possible. Not necessarily useful. But we _could_ do it, in order to make Dart less complex because there are fewer exceptions (possibly, at least ;-).

**Comment by munificent** [comment]
I'm up for doing whatever keeps the language simplest with the fewest special cases here.

**Comment by eernstg** [comment]
Closing: I'll conclude that we **decided** that `extension .. on Never` is **allowed**.

The NNBD feature spec makes it an error to access members of `Never`, and changing that rule would be a different issue.
