### ISSUE TITLE
Should NNBD type promotion iterate to a fixed point?

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#441]
The NNBD type promotion algorithm, as currently prototyped, doesn't handle the following program as nicely as we would like:

```dart
class ListNode {
  ListNode? next;
  int value;
}
void f(ListNode? x) {
  if (x == null) {
    print('List is empty');
  } else {
    int total = 0;
    do {
      total += x.value;
      x = x.next;
    } while (x != null);
    print('List has a total value of $total');
  }
}
```
The problem is that in order to keep the algorithm fast, we operate in a single pass (with a limited amount of lookahead to look for assignments inside loops).  So although we promote the type of `x` to a non-nullable `ListNode` in the `else` branch, when we get to the top of the `do` loop, we have to demote it back to `ListNode?` (because we only look ahead enough to see that `x` is assigned later in the loop; we don't look ahead thoroughly enough to see that the loop condition restores the promotion to `ListNode`).  This means that the user will be forced to insert non-null assertions that seem unnecessary:
```dart
class ListNode {
  ListNode? next;
  int value;
}
void f(ListNode? x) {
  if (x == null) {
    print('List is empty');
  } else {
    int total = 0;
    do {
      total += x!.value; // `!` seems unnecessary
      x = x!.next;       // Here too
    } while (x != null);
    print('List has a total value of $total');
  }
}
```
We could avoid this problem by using an iterative algorithm for type promotion; the first time analyzing the loop we would assume the state from the code above; then, once we reached the bottom of the loop, we would see if the assumption holds; if it doesn't, we would back up and re-analyze the loop with less specific promoted types, repeating until no more changes are required.  To ensure termination we would make sure that every time we backtrack, we only remove type promotions; we don't add additional ones.

The backtracking has the potential to slow down compilation (though perhaps not by a significant amount for well-behaved programs).  It also requires more development effort, because type inference is intimately tied to type promotion, and both the front end and the analyzer currently implement type inference as a single pass over the source code.

**Comment by stereotype441** [comment]
@lrhn @leafpetersen FYI

**Comment by bwilkerson** [comment]
> ... we have to demote it back to `ListNode?` (because we only look ahead enough to see that `x` is assigned later in the loop; we don't look ahead thoroughly enough to see that the loop condition restores the promotion to `ListNode`).

I'm not familiar with the new type promotion algorithm, but in the current promotion algorithm the rules state things like "unless v is potentially mutated in s1". Is that restriction being (partially) lifted? It seems like any reference to `x` after the assignment in the loop should not be promoted, so does the new algorithm make a distinction about the promoted type before an assignment and the type after an assignment?

**Comment by scheglov** [comment]
Yes, we distinct before and after assignment.

See for example `test_binaryExpression_ifNull_rightUnPromote` in `TypePromotionTest`, which is not a pure demonstration of this, but still shows the feature.

The problem with cycles is that their bodies are executed multiple times, and if a variable is assigned anywhere in the body, we either revert any type promotions (as the prototypes does now), or need to prove that the variable is re-promoted.

**Comment by eernstg** [comment]
The do-while statement is special in that it performs the test at the end, and that test is used to establish the promotion, which is the reason why we have the need to use an iterating promotion analysis in the first place.

So let's consider a slight variation of the example:

```dart
class ListNode {
  ListNode? next;
  int value;
}
void f(ListNode? x) {
  if (x == null) {
    print('List is empty');
  } else {
    int total = 0;
    while (x != null) {
      total += x.value;
      x = x.next;
    }
    print('List has a total value of $total');
  }
}
```

It is not hard for a compiler to verify that [in]equality with null has no side-effects and will succeed, which means that we could avoid the redundant evaluation of the condition (just jump directly to the loop body the first time, which might actually amount to _omitting_ a jump, if the code is generated such that the test is at the end). A similar treatment could be given to `x is T`.

With that optimization in place there is no performance reason for preferring the do-while form, and the while form would presumably allow for a promotion analysis without iteration.

We could even let the compiler transform a do-while statement whose condition has no side-effects to the corresponding while statement (and it would only do so if the condition is provably true the first time, and it would then jump directly to the body).

This is a somewhat twisted way to avoid the need for iteration, but I suspect that using an iterative analysis is such a big step that it's worth considering whether it can be avoided in the first place.

So, having eliminated the relevant do-while statements, do we _still_ have any good examples where iteration comes up as the obvious solution?  ;-)

**Comment by leafpetersen** [comment]
Resolved, we will not do this.
