### ISSUE TITLE
Request for base tips extension

### ISSUE THREAD

**Issue by mich4s** [dart-lang/language#442]
Hello, from I have some request from ROR world. It would be great to have methods in base types like integer.days which returns Duration of days taken from int value. This could be great code shortener to avoid multiple constructors in code.

**Comment by lrhn** [comment]
I assume ROR here means Ruby-on-Rails.

While adding methods to `int` is definitely convenient, it doesn't scale very well. There are quite a lot of classes which can be constructed from an integer, and we can't put constructor functions for every one of those on the `int` class. So, not to adding instance members to the `int` class.

However, this sounds like a perfect use-case for extension methods (#41). 
You can declare your *domain-specific* extensions to the `int` class without tripping over other people's toes. For example:
```dart
extension DurationFromInt on int {
  Duration get d => Duration(days: this); 
  Duration get h => Duration(hours: this);
  Duration get m => Duration(minutes: this);
  Duration get s => Duration(seconds: this);
  Duration get ms => Duration(milliseconds: this);
}
```
Then you can write `2.d + 1.h + 4.m + 23.s + 12.ms`, and nobody else gets affected by that unless they deliberately import your `DurationFromInt` extension.

**Comment by mich4s** [comment]
Well I haven't found this future release before and because basic types can't be (by now) extended I thought this could be the option. #41 definitely fulfill my needs, so closing.
