### ISSUE TITLE
A variable declaration used only for interface purposes may be abstract

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#45]
This is a solution to #44.

## Proposed Syntax

We propose that instance variable declarations can include the modifier `abstract` as the first token. For instance:
```dart
abstract class A {
  abstract int x;
}
```

## Proposed Static Analysis and Dynamic Semantics

An abstract instance variable induces an abstract getter and setter, with the obvious signatures, but does not give rise to allocation of storage in the instance:
```dart
// Desugared meaning of the above `A`.
abstract class A {
  int get x;
  void set x(int value);
}
```
The rules for abstract instance variables follow directly from the desugaring. For instance, it is a compile-time error if an abstract instance variable declaration introduces an abstract getter and a concrete class has that getter in its interface but there is no implementation:
```dart
class B extends A {
  set x(value) => ...;
  // ERROR: `int get x` has no implementation.
}
```

## Additional Considerations

Obviously, the conciseness of abstract variables will be even better with multiple variables:
```dart
class A {
  abstract int a, b, c, d, e;
}
```

It may be appropriate to always use `abstract` instance variables for a type declaration which is only used as a supertype (today it could be any class which is intended to be used in that manner, in the future we may have a separate concept like `interface` where subtyping is the only supported usage). We could then make `int x` mean `abstract int x` when it occurs in an `interface`, or in a similar context where that default is useful.

**Comment by eernstg** [comment]
[Here](https://dart-review.googlesource.com/c/sdk/+/70268) is a proposed spec update.

**Comment by eernstg** [comment]
Yes, I think this could be a source of confusion. But we cannot use omissions of syntactic elements to indicate abstractness here: the forms `var x;` and `T x;` are already in use. So we need to put an explicit marker on a variable in order to make it abstract, and `abstract` should be a rather obvious choice for that. We used to have `abstract` on abstract method declarations, but we changed the syntax to just omit the body because nobody was happy about the need to write all those unnecessary `abstract` keywords. So I think it would be an absolute no-go to reintroduce an optional `abstract` keyword on abstract methods.

So even though I can see the conflict, I suspect that it will be difficult to find a better compromise than having `abstract` on the abstract fields, and not having it on methods.

**Comment by munificent** [comment]
Do we have data on how often users want abstract fields inside classes that are *not* intended to be interfaces? I find the proposed syntax kind of confusing, like @miyoyo. And, if we do add interface syntax, it will be redundant in those cases too, which makes it more confusing. If this feature would rarely be used outside of "interface-like" classes, maybe the better solution is to actually add interface syntax, like we did mixins.

Honestly, if we're touching this area of the language, I'd really like a proposal that addresses other pain points around getters/setters:

* Having to redundantly specify the name and type when defining both a getter and setter.
* It being unclear where to place the doc comment when you have both.
* The fact that a getter and setter don't visually line up when you have both.
* Having to come up with a mostly-obvious name for the value passed to the setter.
* The redundancy required when defining a getter and/or setter with private backing field.

**Comment by eernstg** [comment]
This feature is part of Dart today.
