### ISSUE TITLE
Are extension overrides required to have one argument?

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#453]
The [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md) doesn't appear to say so (I might be missing something), but I'm guessing it's an error if an extension override has either more than or fewer than one argument or if the single argument has a name:
```
extension E on String {
  int m() => 0;
}
main() {
  E().m(); // error
  E('a').m(); // valid
  E(receiver: 'a').m(); // error
  E('a', 'b').m(); // error
}
```

**Comment by leafpetersen** [comment]
Yes, it is an error.  As a general heuristic, given an extension `E on T`, a reference to `E` that resolves as an override should be treated as if were a call to a static function named `E` of type `void Function(T)`, with all of the corresponding errors and warnings.  Specifically:

- It is an error if there are more or less than 1 positional argument, or any named arguments

If the override is of the form `E(arg)` then:

- Inference is done using `T` as the downwards context for `arg` as usual
- It is an error if the inferred type of `arg` is not assignable to `T`

If the extension is generic, `E<X0, ..., Xn> on T`, a reference to `E` that resolves as an override should be treated as if were a call to a static function named `E` of type `void Function<X0, ..., Xn>(T)`, with all of the corresponding errors and warnings.

- It is an error if there are more or less than 1 positional argument, or any named arguments
- It is an error if there are type arguments provided, and the number of those type arguments is different from n-1
- It is an error if type arguments are provided and the type arguments do not satisfy their bounds

If the override is of the form `E(arg)`  then:

- Inference is done using `T` with `?` substituted for `X0, ..., Xn` as the downwards context for `arg` as usual
- The missing type arguments are inferred as usual for a generic function call
- It is an error if the inferred type of `arg` is not assignable to `T` with `X0, ..., Xn` replaced with the inferred type arguments 

If the override is of the form `E<S0, ..., Sn>(arg)`  then:

- Inference is done using `T` with `S0, ..., Sn` substituted for `X0, ..., Xn` as the downwards context for `arg` as usual
- It is an error if the inferred type of `arg` is not assignable to `T` with `X0, ..., Xn` replaced with `S0, ...., Sn` 

@lrhn anything I'm missing there?

**Comment by lrhn** [comment]
No, that looks right.

I generally think of an extension like:
```dart
extension Ext<T1..Tn> on OnType<T1..Tn> {
  extensionMethods
}
```
as if it was a wrapper class with a constructor like:
```dart
class Ext<T0...Tn> {
   final OnType<T0...Tn> _this;
   Ext(this._this);
   extensionMethods with `_this` instead of `this`.
}
```
If the invocation of the constructor `Ext(object)` would throw, then so would the extension override, and if not, the type inference happens in exactly the same way.

(Basically, I think of everything as if such a wrapper is implicitly or explicitly added to all extension member invocations, but the wrapper object can't possibly leak, so we don't have to create it. There are a few differences, like all resolution being static so you won't call an extension `noSuchMethod`, but it's a useful model).

**Comment by leafpetersen** [comment]
Closing this as resolved.
