### ISSUE TITLE
static extension methods lose information about the type of receiver?

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#457]
Consider an example:
```
T pr<T> (T x) {print(x); return x;}
void main() {
  var y = pr(1);
}
```
Here, the static type of `y` is `int` (due to type inference).
If we try to write the same function as 
```
extension on Object {
   Object pr() { print(this); return this; }
}
``` 
and then call it as 1.pr(), the return type will be "Object", not "int". So the information about receiver type is lost, and there's no way to even refer to the static type of receiver in the body of the extension. Is it so by design?

**Comment by leafpetersen** [comment]
If you want the receiver type, make the extension generic:

```dart
extension<T> on T {
   T pr() { print(this); return this; }
}
```

**Comment by tatumizer** [comment]
Thanks. So the equivalent of
```
T pr<T extends Iterable<int>> (T x) {print(x); return x;}
void main() {
  var y = [1, 2]; // type of y is List<int>
}
```
is 
```
extension<T extends Iterable<int>> on T {
   T pr() { print(this); return this; }
}
```
Right?

**Comment by leafpetersen** [comment]
Correct.
