### ISSUE TITLE
Building a new collection out of an existing one is too imperative

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#46]
Dart has a nice declarative syntax for creating new lists and maps (and eventually probably sets) from a series of elements:

```dart
var list = [1, 2, 3];
var map {key: value};
```

This works well when building a collection out of *individual* elements. But if you want to insert the contents of an existing collection, you are forced to use an imperative, mutating API:

```dart
var args = testArgs.toList()
  ..add('--packages=${PackageMap.globalPackagesPath}')
  ..add('-rexpanded')
  ..addAll(filePaths);
```

**Comment by kevmoo** [comment]
@munificent – could this issue be considered closed by the spread collection work?

**Comment by munificent** [comment]
Yes! This issue is the problem the feature was designed to solve.
