### ISSUE TITLE
Are extensions allowed to extend enums?

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#460]
The language specification says that it's an error to extend, mixin, or implement an enum, but the extension methods proposal doesn't explicitly mention enums. Is the following valid:

```
enum Color { red, green, blue }
extension ColorUtilities on Color {
  bool get isRed => this == Color.red;
}
```

**Comment by leafpetersen** [comment]
Yes - an enum introduces a type, and extensions can be added to any type.

**Comment by munificent** [comment]
Closing since the question was answered.
