### ISSUE TITLE
Need clarification for an error related to conflicts

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#472]
The proposal states

> If more than one extension applies to a specific member invocation, then we resort to a heuristic to choose one of the extensions to apply. If exactly one of them is "more specific" than all the others, that one is chosen. Otherwise it is a compile-time error.

I take "specific member invocation" to mean that there must be a reference to the member that is defined in the conflicting extensions.

The test https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-methods/extension_conflict_resolution_t06.dart expects that an error will be produced even in the absence of any reference to the conflicting members.

I need to know which interpretation is correct.

**Comment by leafpetersen** [comment]
Your interpretation is correct and that test is incorrect.  It is not an error to have potentially conflicting extension members in scope, it is only an error to have a reference that resolves to two or more conflicting extension members.

**Comment by bwilkerson** [comment]
Thanks. I'll open an issue with the co19 team.

**Comment by bwilkerson** [comment]
https://github.com/dart-lang/co19/issues/420
