### ISSUE TITLE
Static extension methods: implement abstract class

### ISSUE THREAD

**Issue by vanesyan** [dart-lang/language#475]
Will it be possible to static extension methods to implement some abstract classes (interfaces), like it possible extension to implement protocol in Swift, e.g.:
```swift
protocol Foo {
    func foo()
}

extension FooExt : Foo {
    func foo() {
        // some code
    }
}
```
Such a feature helps a lot to extend primitive type to use for framework's purposes. For example, imagine that we develop an http framework, we can extend String, Map, etc. to provide capability to return it as response to the request, e.g.:
```dart
abstract class HttpResponder {
  FutureOr<void> toResponse(Context context);
}

extension HttpStringExt on String implements HttpResponder {
  FutureOr<void> toResponse(Context context) => context.write(this);
}

typedef HttpHandler = HttpResponser Function(Context context);

HttpResponder strHandler() => 'Hello world';
```

**Comment by lrhn** [comment]
No, this will not be possible with static extension methods.
The static extensions are inherently static. There is no run-time component to them.

As such, passing a `String` extended by `HttpStringExt` to something expecting an `HttpResponder` will fail. At run-time you are passing a string where an `HttpResponder` is expected, and that must fail.

**Comment by vanesyan** [comment]
Thanks for the quick response 😊
Is it considered to be added to the language in the future? Are there any possibility of it?

**Comment by leafpetersen** [comment]
Some ideas in this space have been under discussion for a while, e.g. [here](https://github.com/dart-lang/language/issues/42).  I don't think there's any strong short term plans in that direction yet though.  I'm going to close this issue, since I think it's mostly covered by the issue referenced above - feel free to comment there on how that proposal sketch would/wouldn't address your use case.

**Comment by lukepighetti** [comment]
Just presenting a use case, I am porting some Swift code over to dart, and they make use of extensions to implement protocols on classes imported from other packages.

https://github.com/uber/RIBs/blob/master/ios/tutorials/tutorial1/TicTacToe/Root/RootComponent%2BLoggedOut.swift#L27

Something like:

```dart
class Foo {
  String get foo => "foo";
}

abstract class Protocol {
  String get bar;
}

extension on Foo implements Protocol {
  String get bar => "bar";
}
```

Is there a possibility this can be added in the future?

**Comment by rrousselGit** [comment]
^ That's not an extension anymore and is a completely different mechanism.

Extensions are purely optional. Some files may use an extension, while some other file may not. 
As such, it's not possible to implement an interface using Extensions.

**Comment by lukepighetti** [comment]
@rrousselGit I've noticed swift has a very large namespace by default, does that have any effect on why they are able to do implementations with extensions? It doesn't seem like it would at first glance, but your reply seems to allude that it might.

**Comment by rrousselGit** [comment]
My bad, ignore my previous comment. I've misread the code snippet.

I thought it was:

```dart
class Foo implements Protocol {
  String get foo => "foo";
  // bar not implemented
}

extension on Foo implements Protocol {
  // implement bar as an extension
  String get bar => "bar";
}
```

**Comment by lukepighetti** [comment]
Another question, not sure if this is the right place for this,

```dart
import 'package:flutter/widgets.dart';
import 'package:rxdart/rxdart.dart';

main() {}

extension on StreamBuilder<T> {
  static StreamBuilder<T> seeded({Key key, ValueObservable<T> stream, AsyncWidgetBuilder<T> builder}) =>
      StreamBuilder<T>(key: key, stream: stream, initialData: stream.value, builder: builder);
}

class FakeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<bool>.seeded(
      stream: Observable.just(true).shareValueSeeded(true),
      builder: (context, snapshot) {
        ///
      },
    );
  }
}
```

Possible to add static methods? Right now this is invalid, showing error

```
The class 'StreamBuilder' doesn't have a constructor named 'seeded'.
Try invoking a different constructor, or define a constructor named 'seeded'.dart(new_with_undefined_constructor)
```

**Comment by natebosch** [comment]
> Possible to add static methods? Right now this is invalid, showing error

No. You'd have to refer to the _extension_ name not the type it's on to invoke a static. As a consequence you can't call a static on an unnamed extension. I filed https://github.com/dart-lang/language/issues/617 to discuss whether we should make the definition a warning.

```dart
extension Seeded on StreamBuilder {
  static StreamBuilder<T> seeded<T>(...) =>;
}

// usage
return Seeded.seeded<bool>(...);
```

**Comment by shinayser** [comment]
Having some problems for auto completing extensions that are coming from other files.

For example, I have this extensions on the file **time.dart**:

```dart
extension IntTimeExtension on int {
   Duration get seconds => Duration(seconds: this);
}
```

My main is exactly like this:

![image](https://user-images.githubusercontent.com/1146982/66782185-8635c580-eeab-11e9-94f9-43e5def05764.png)

If I try to auto complete, it gives "no suggestions". I f I try to fix error it says:

![image](https://user-images.githubusercontent.com/1146982/66782228-9fd70d00-eeab-11e9-8ad2-ec8fca9394b1.png)


As soon as I move my extension to the same file as **main**, everything works:

![image](https://user-images.githubusercontent.com/1146982/66782292-c006cc00-eeab-11e9-9ac0-644ffef8aca3.png)

**Comment by lukepighetti** [comment]
Yeah for this specific case I can't find a way to make extensions improve over this style of implementation. If we could extend a class with a new constructor or create an extension with its own constructor or add a static method to the original class I believe it would be an objective improvement.

```dart
class ValueObservableBuilder<T> extends StreamBuilder<T> {
  ValueObservableBuilder({
    Key key,
    ValueObservable<T> valueObservable,
    AsyncWidgetBuilder<T> builder,
  }) : super(key: key, stream: valueObservable, initialData: valueObservable.value, builder: builder);
}
```

**Comment by izouxv** [comment]
just swift can do it .

**Comment by jejer** [comment]
Wish Dart could support this feature like Swift.
