### ISSUE TITLE
Implementation issue for unsigned/triple-shift >>> operator

### ISSUE THREAD

**Issue by floitschG** [dart-lang/language#478]
This is the implementation issue for the triple-shift `>>>` operator (unsigned shift), see language feature https://github.com/dart-lang/language/issues/120

The operator has the same precedence as `>>`. 
The expression `e1 >>> e2` is a compile-time constant expression if both `e1` and `e2` are compile-time constant expressions evaluating to integers (and `int` will implement the operator).
The symbol `#>>>` is valid (along with `const Symbol(">>>")`), as is `x >>>= e` as an expression.

Adding the new operator is non-breaking.

- [x] specification
- [x] Frontend https://github.com/dart-lang/sdk/issues/30888
- [ ] Analyzer https://github.com/dart-lang/sdk/issues/44908
- [x] dart2js https://github.com/dart-lang/sdk/issues/30890
- [ ] DDC https://github.com/dart-lang/sdk/issues/30891
- [x] VM https://github.com/dart-lang/sdk/issues/30892

**Comment by mit-mit** [comment]
Transferring and re-purposing to be the implementation issue for this feature.

**Comment by AKushWarrior** [comment]
Is there a status on this? It would be massively helpful for cryptography.

**Comment by AKushWarrior** [comment]
I don't think this would be too difficult. I haven't touched dart's internals, but I'm using a utility function. Converted to an operator, it would look like:

```dart
int operator >>> (int other) {
    return this >= 0 ? this >> n : ~(~this >> n);
}
```

**Comment by AKushWarrior** [comment]
Note that the above wouldn't work for JavaSvript compilation. I think it would need to use 32 instead of 64.

**Comment by AKushWarrior** [comment]
The code snippet I posted was wrong. I fixed it.

**Comment by AKushWarrior** [comment]
New code snippet, which works both on the VM and when trans-piled to JS.

```dart
int operator >>> (int count) {
    if (!isJS) {
      return (this >= 0) ? this >> count : ~(~this >> count);
    } else {
      var x = this & 0xFFFFFFFF;
      count &= 0x1f;
      if (this >= 0) {
        return (x >> count + 1);
      } else {
        return -(~x >> count + 1);
      }
    }
}

bool get isJS {
  // Some definition here...
}
```
I dunno about performance, but I use only bitwise operators, so it should be decent. It's tested on the VM and DartPad. All cases (negative, zero, positive) check out for both.

If someone could guide me through the process, I'd be happy to try and implement the >>> operator as a language feature.

**Comment by mpfaff** [comment]
@AKushWarrior what is `x` supposed to be in your code example?

**Comment by AKushWarrior** [comment]
> @AKushWarrior what is `x` supposed to be in your code example?

Nothing. It was a remnant from me testing the function in a different setup than the extension method presented here. It should be fixed now.

**Comment by mpfaff** [comment]
The JavaScript version works for me, but not the Dart VM version.

**Comment by AKushWarrior** [comment]
@mpfaff I'll review at some point. I'm kinda swamped and I didn't really test it super extensively, just with 10 or so test cases.

**Comment by AKushWarrior** [comment]
@mpfaff new DartPad code is below and seems to work fine on DartPad. If you could try to break it with more cases, that would be great. All test cases have been checked using TypeScript.

```dart
void main() {
  //positive
  print((3185753779 * 3185753779).tripleShift(32) == 2417635328);
  print(25.tripleShift(25) == 0);
  print(13123423.tripleShift(5) == 410106);
  
  //zero
  print(0.tripleShift(23) == 0);
  
  //negative
  print((-12245234).tripleShift(11) == 2091172);
  print((-2938648).tripleShift(4) == 268251790);
}

extension tripShift on int {
  int tripleShift (int count) {
    if (false) {
      return (this >= 0) ? this >> count : ~(~this >> count);
    } else {
      // assumes this > -4294967295, or -(2^32 -1)
      count &= 0x1f;
      if (this >= 0) {
        return (this >> count);
      } else {
        return (this >> count) ^ ((0xFFFFFFFF) ^ ((1 << (32-count)) - 1));
      }
    }
  }
}

**Comment by AKushWarrior** [comment]
There should be a difference between how zero-fill right shift works on the web and on the VM: 64-bit numbers which have been zero-fill right shifted are very different from 32-bit numbers of the same variety.

**Comment by AKushWarrior** [comment]
@mit-mit @Irhn is this on the roadmap for post-NNBD improvements?

**Comment by eernstg** [comment]
It is on a shortlist of small, useful features: https://github.com/dart-lang/language/issues/1077.

**Comment by Comevius** [comment]
@AKushWarrior 

Neither of your implementations work properly. Many of your tests also expects the wrong result:

```dart
(3185753779 * 3185753779) == -8297716933296770775;
// 1000110011011000100101100110100110010000000110100011000100101001
(3185753779 * 3185753779) >>> 32 == 2363004521;
// 10001100110110001001011001101001
(3185753779 * 3185753779) >>> 32 != 2417635328;
// 10010000000110100011000000000000
```

This is the correct implementation for Dart Native:

```dart
extension TripleShift on int {
  int tripleShift(int count) { 
    return (this >> count) & ~(-1 << (64 - count));
  }
}
```

**Comment by AKushWarrior** [comment]
> @AKushWarrior 
> 
> Neither of your implementations work properly. Many of your tests also expects the wrong result:
> 
> ```dart
> (3185753779 * 3185753779) == -8297716933296770775;
> // 1000110011011000100101100110100110010000000110100011000100101001
> (3185753779 * 3185753779) >>> 32 == 2363004521;
> // 10001100110110001001011001101001
> (3185753779 * 3185753779) >>> 32 != 2417635328;
> // 10010000000110100011000000000000
> ```
> 
> This is the correct implementation for Dart Native:
> 
> ```dart
> extension TripleShift on int {
>   int tripleShift(int count) { 
>     return (this >> count) & ~(-1 << (64 - count));
>   }
> }
> ```
> 

I'm matching the JS version. While you are mathematically right, a programmer is likely to be confused that using >>> in dart2js results in a different value than pure js.

**Comment by Comevius** [comment]
@AKushWarrior 

JavaScript only defines bitwise operations on 32-bit unsigned integers, so even when you do `>>>0` it lowers the precision of your already lowered precision 53-bit int to the 0 to 0xffffffff range.

You would need something like Int64 to emulate 64-bit values and operations:
https://pub.dev/documentation/fixnum/latest/fixnum/Int64/shiftRightUnsigned.html

BigInt would be another solution, but Dart is yet to support it.

**Comment by AKushWarrior** [comment]
@Comevius

Dart integers, when translated to JS, are 32 bit, not 53 bit. While I agree that we should have clearer types (or just standardize the fixnum types), that would break all existing code.

When using Dart for JS, you have to assume that all your integers are 32 bit, or just use https://pub.dev/packages/fixnum. Dart integers, to the best of my knowledge, are not meant to emulate 64 bit integers when transpiled to JS. 

Instead of trying to create a solution that produces the same results on both Native and JS, which doesn't make sense given the nature of both platforms, I created a separate version which matches the ES6 results for >>>. All those test cases were designed to be run on DartPad, which transpiles code to JS before running it.

**Comment by eernstg** [comment]
> Dart integers, when translated to JS, are 32 bit, not 53 bit.

Not quite: Dart numbers are represented as JavaScript numbers when compiled to JavaScript. A number `is int` if it has no fractional part, and it always `is double`. So that yields 53 bits of information for an `int`, but includes larger numbers where the "missing" low bits are treated as zeros (so `18014398509481982 is int`).

However, bitwise operations work on 32 bits and treat them as an unsigned number (cf. [this comment](https://github.com/dart-lang/sdk/issues/42892#issuecomment-667414031)). So `>>>` should work accordingly when compiled to JS, and in particular there will be differences between the results when the target language is native vs. when it is JS.

**Comment by AKushWarrior** [comment]
> > Dart integers, when translated to JS, are 32 bit, not 53 bit.
> 
> Not quite: Dart numbers are represented as JavaScript numbers when compiled to JavaScript. A number `is int` if it has no fractional part, and it always `is double`. So that yields 53 bits of information for an `int`, but includes larger numbers where the "missing" low bits are treated as zeros (so `18014398509481982 is int`).

Interesting. The only time I considered the bit length of integers was when doing bitwise ops, so I guess it never occurred to me.

> However, bitwise operations work on 32 bits and treat them as an unsigned number (cf. [this comment](https://github.com/dart-lang/sdk/issues/42892#issuecomment-667414031)). So `>>>` should work accordingly when compiled to JS, and in particular there will be differences between the results when the target language is native vs. when it is JS.

This is in line with my example. My newest DartPad example works with expected results from the target language (JS).

**Comment by srawlins** [comment]
Note: added analyzer subtask above https://github.com/dart-lang/sdk/issues/44908

**Comment by eernstg** [comment]
Closing: This feature was enabled by default in 2.14.
