### ISSUE TITLE
Member access through extension override

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#481]
The specification states:

> An expression of the form `MyList(object)` or `MyList<String>(object)` must only be used for extension member access.

but does not define whether that includes both instance and static members or only instance members. Could you clarify whether static members can be accessed this way?

The question arose because the co19 test LanguageFeatures/Extension-methods/static_member_t02.dart attempts to access a static member of an extension through an extension override:
```
Expect.equals(str, MySmart(str).smartHelper(str));
```

**Comment by leafpetersen** [comment]
@eernstg and @lrhn for their perspective, but my understanding is that this should not be allowed.  I don't see any reason to allow it (you can get the same behavior more simply just by using the usual static member access syntax), and allowing it would seem to be less forward compatible with other extensions we've thought of.

**Comment by eernstg** [comment]
I agree with @leafpetersen that the meaningful and future-safe rule is that static members can, and can only, be accessed by using the extension name as a prefix. 

But I also don't see any explicit language in the feature spec to the effect that `E(e).staticMemberOfE` would be an error. We do have [this](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#static-members-and-member-resolution) text:

> Static member declarations in the extension declaration can be accessed
> the same way as static members of a class

but that doesn't explicitly make other approaches an error. I created https://github.com/dart-lang/language/pull/483, which is a single-word change which makes it explicit that `E(e).staticMember` is an error.

**Comment by leafpetersen** [comment]
Closing this, since I think the question is resolved.
