### ISSUE TITLE
Several suggestions

### ISSUE THREAD

**Issue by isMeiying** [dart-lang/language#482]
> 1.Why not add a operator as simple as kotlin `when`, it works great, `switch` looks a bit stupid. #https://github.com/flutter/flutter/issues/36597#event-2497738692

> 2.I hope can remove `;`. Just like swift and kotlin. Every time you write a code, you need to add one `;` this is obviously very unfriendly to the developer and not elegant enough.

> 3.Is there a good way to make `,` disappear as much as possible, because dense symbols may make people feel uncomfortable...

> 4.Add methods like kotlin `extension function, let, with, run, apply, also`, they look great and can make the code further concise.

### I hope that dart can capture the best in other languages, which will make developers more love dart.

**Comment by modulovalue** [comment]
Take a look at the [Language Funnel](https://github.com/dart-lang/language/projects/1)

2 is discussed at #72
4 should be possible with #41

And I believe you'll have to be more precise with 1 and 3, "stupid" and "uncomfortable" are too ambiguous :)

**Comment by munificent** [comment]
Hi, I appreciate the suggestions, but a single issue requesting a whole slew of very large language features is not very actionable for us. Many of the features you request have separate issues already with a lot more detail, so it will be more useful to participate on those threads.
