### ISSUE TITLE
Short lambda function declaration

### ISSUE THREAD

**Issue by Claus1** [dart-lang/language#491]
It is possible to make a short lambda _ for functions with 1 argument (like Scala, ..)
Now
`var result = list.map((x) => convert(x));`
Possible
`var result = list.map(convert(_));`
Most containers methods work with such lambdas and it would dramatically reduce syntax noise (garbage) in complex code.

**Comment by srawlins** [comment]
Did you try

```dart
var result = list.map(convert);
```

?

**Comment by Claus1** [comment]
> Did you try

>var result = list.map(convert);
It works but short lambda _ has a direct reference to the object and such code is possible
`var result = list.map(convert(_.field));`
where the field is a field of argument.
or 
`var result = list.flter(_ > 0 && _ < 100);`

**Comment by eernstg** [comment]
Note that language issue #8 contains a summary of several ideas and discussions in this area.
