### ISSUE TITLE
wrong datetime claculations

### ISSUE THREAD

**Issue by SergeBerwert** [dart-lang/language#492]
Hi i think i found a bug in the Dart language:

I try to subtract 180 from a DateTime.  the result seems to be off by 1h. I ha the bug in a flutter project and reproduced it in the dartpad:

code:
```
void main() {
  var from = DateTime(2018,5,29);
  var to = from.subtract(Duration(days: 180));
    print('result - from: $from - to: $to');
}
```

output:
`result - from: 2018-05-29 00:00:00.000 - to: 2017-11-29 23:00:00.000`

expected result:
`result - from: 2018-05-29 00:00:00.000 - to: 2017-11-30 00:00:00.000`

**Comment by srawlins** [comment]
(This would not be a bug in the Dart language, but the core library, tracked separately at https://github.com/dart-lang/sdk)

The Duration constructor is a convenient way to calculate a span of time based on hours, days, etc. But the time is stored as a simple value of milliseconds or microseconds. See [the docs](https://api.dartlang.org/stable/2.4.0/dart-core/Duration-class.html):

> Durations are context independent. For example, a duration of 2 days is always 48 hours, even when it is added to a DateTime just when the time zone is about to do a daylight-savings switch. (See DateTime.add).

> Despite the same name, a Duration object does not implement "Durations" as specified by ISO 8601. In particular, a duration object does not keep track of the individually provided members (such as "days" or "hours"), but only uses these arguments to compute the length of the corresponding time interval.

Between 2017-11-30 and 2018-05-29, a daylight-savings time change likely occurred in your local time zone.
