### ISSUE TITLE
Extension methods impl plan missing Dartdoc generation

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#499]
The [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/implementation-plan.md) for extension methods should include a section for Dartdoc: extensions should be documented.

I suggest Phase 2, where Grok and editors are hanging out.

**Comment by leafpetersen** [comment]
@aadilmaan @devoncarew Is this accounted for anywhere?

**Comment by srawlins** [comment]
I don't think we've created SDK issues for many/most of the Phase 2 and beyond tasks in the implementation plan, but @keertip is planning on adding support for Extension Methods in dartdoc.

**Comment by keertip** [comment]
I have an OKR for extension methods support in dartdoc, we are missing a mention for it in the implementation plan and/or the related tracking bug.

**Comment by leafpetersen** [comment]
I filed an [issue for this](https://github.com/dart-lang/sdk/issues/37888).
