### ISSUE TITLE
Null operator ?..

### ISSUE THREAD

**Issue by AdalbertoLacruz** [dart-lang/language#500]
We have the ?. operator
  color?.type = 'rgb';

and the .. operator
  return color..type = 'rgb';

But we can't do both in the same sentence
  return color?.. = 'rgb';

Is possible to add ?.. operator to the dart language?

**Comment by eernstg** [comment]
It's coming: https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md. So we hope it's possible. ;-)

**Comment by AdalbertoLacruz** [comment]
Thanks. Interesting proposal.

**Comment by eernstg** [comment]
Thanks!
