### ISSUE TITLE
Extension method proposal needs to address bounds checking of type arguments.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#501]
The current extension method proposal does not make it explicit that the type argument to a generic extension method (whether inferred or explicit) may not be a super-bounded type.  

Edit for clarity:  It is valid to pass a super-bounded type as an argument to a generic extension *iff* the super-bounded type satisfies the bound.  So a better statement of the problem is that we need to make it clear that it is an error to pass a type argument which doesn't satisfy the bound.  We probably also should address whether it is valid to have the "on" type be a super-bounded type.  

cc @eernstg @lrhn @bwilkerson @johnniwinther

**Comment by leafpetersen** [comment]
Tests added here https://dart-review.googlesource.com/c/sdk/+/112149

**Comment by eernstg** [comment]
Soundness is endangered here with exactly the same argument as with constructor invocations: We cannot allow code to run where `X extends B` is in scope when the value of `X` can violate the declared bound. So I agree that a super-bounded type passed to "the extension as such" must be an error.

That is, considering `Ext<T>(e).m()` we require that `T` satisfies its bound, both when given explicitly and when given as `e.m()` and then desugared (assuming for a minute that we agree on viewing this type inference step as being defined in terms of desugaring to the explicitly resolved form).

For type parameters passed to the method invocation (e.g., `S` in `Ext<T>(e).m<S>()`) there should not be a need for any new rules: The language specification [requires](https://github.com/dart-lang/language/blob/dc35fd957e7896946a54b4a14083ba9ca4a74f51/specification/dartLangSpec.tex#L4834) actual type parameters passed in an invocation of an entity whose static type is a generic function type to satisfy the given bounds. However, it is of course possible to pass an actual type argument which is a superbounded type if it satisfies its bound, e.g.:

```dart
class C<X extends num> {}

void f<Y>() {}

main() {
  f<C<Object>>();
}
```

**Comment by leafpetersen** [comment]
Edited the title and the initial comment to make clear the distinction that @eernstg mentions above.

**Comment by vsmenon** [comment]
Is this resolved?  Do we need for D27?  It's listed as a dep for dart-lang/sdk#37350 .

**Comment by leafpetersen** [comment]
The tests I landed for this are passing, so I think the implementations are doing the right thing.  @lrhn do we need to make any changes to the feature spec for this?  In either case, I don't think this is blocking for the release.
