### ISSUE TITLE
run command issue

### ISSUE THREAD

**Issue by alexey-sanko** [dart-lang/language#505]
I ve got following issue, please help me.
report ID: 6016e28fb6d85f00

**Comment by eernstg** [comment]
Please describe the situation that you are reporting on in more detail!

Also, it seems likely that the issue would not be concerned with the _language_ Dart as such, it sounds more like some operation that failed (e.g., a tool that crashed). In that case it should go here: https://github.com/dart-lang/sdk/issues/new.
