### ISSUE TITLE
Pub cannot know the minimum required SDK version

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/language#507]
In [language versioning](https://github.com/dart-lang/language/blob/dc35fd957e7896946a54b4a14083ba9ca4a74f51/accepted/future-releases/language-versioning/feature-specification.md), we propose that:

> The `pub` tool reads the `pubspec.yaml` file of the current package, and all packages that this package recursively depends on (in many versions, then it uses constraint solving to pick a specific version of each), and writes the `pubspec.lock` and `.packages file`. Doing this, it can see the SDK requirement of each package that is available to the current package and can write the minimum required version into the `.packages` file.

For a `pubspec.yaml` as follows:
```yaml
name: hack
dependencies:
  other_pkg:
    path: ../other_pkg
environment:
  sdk: '>2.0.0 <=3.0.0'
```
We cannot know the minimum version, yet it seems unreasonable to not write a version as the Dart will then infer the language version from the latest SDK version.
If the `environment.sdk` key had been omitted it seems perfectly fair to leave out the `#dart=...` bit.

However, as I understand it, the `sdkVersion` in `#dart=<sdkVersion>` should be an inclusive lower bound, is that correct? @lrhn

**Comment by leafpetersen** [comment]
Just to clarify - the concern is that `>2.0.0`, tells you a min SDK that is *not* supported, but not the min SDK that *is* supported?  

Is there some predictable constraint we can generate that is guaranteed to be `>2.0.0` and `<=` to anything else?  Seems like `>=2.0.0-dev.0` would work?

**Comment by jonasfj** [comment]
We could do something like `2.0.0+1`, but if the SDK version was `+1` that won't work, so we would have to resort to adding "1" at the end of whatever "build version" it already has (or add a `+1` build version if there is none).

But this means that  `#dart=` isn't the minimum SDK version from `pubspec.yaml`, but rather an artificial approximation (at-least in this case). It probably won't matter, it just seems unfortunate to have such a corner case in the future.

I'm just noting that the change in https://github.com/dart-lang/language/pull/332 is hard to realize.

**Comment by natebosch** [comment]
To clarify, does pub consider `2.0.0+1` to match `>2.0.0`?


If we decide in https://github.com/dart-lang/language/issues/506#issuecomment-519701916 that we don't need to be so fine grained, does that make this easier?

**Comment by lrhn** [comment]
I'd say to pick the lower bound instead of the `min` in cases like this.
That is, choose the latest language version (major.minor) which is guaranteed to be supported by *any* SDK satisfying the environment.sdk constraint. In this case, it will be 2.0.

This is a safe choice. You cannot use any language feature which is not supported by all valid solutions to the version constraint, but you can use any feature before that. Since `2.0` is before `>2.0.0`, and no other language version is, that is your solution.

If there is no environment.sdk entry, you should also not write any version into the `.packages` file. Everything is running on the current SDK, and is assuming that will work. (It's the `dynamic` of versioning).

**Comment by jonasfj** [comment]
I took this up with @lrhn IRL, and the conclusion what that the SDK version that goes into `#dart=` is the largest lower bound.

Thus, when we have an exclusive lower bound `>2.0.0`, we simply write `#dart=2.0.0`.

I clarify that the version in the fragment is not the language version, but the SDK version from which the language version is derived. At-least that's what the language versioning document says after https://github.com/dart-lang/language/pull/332.
