### ISSUE TITLE
Should we change instantiate to bounds in the NNBD release?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#513]
Currently given a class definition of the form `class A<T>`, the raw type `A` is implicitly completed to `A<dynamic>`.  We've wanted in the past to change this to complete to `A<Object`>, but when we tested this out a few years ago, it was very breaking.  @srawlins has been rolling out the no-implicit-dynamic restrictions which force types like that to be written explicitly to work around this.  Should we consider making this change as part of the NNBD release?  An argument in favor is that we are already building migration tooling, and it should be straightforward for that tooling to replace any raw type `A` with `A<dynamic>` to preserve the current behavior, and then allow the user to remove the `dynamic` if desired.  

cc @vsmenon @matanlurey @srawlins @lrhn @munificent

**Comment by matanlurey** [comment]
+1.

**Comment by lrhn** [comment]
I would *very much* want `List x = <int>[1, 2];` to infer `List<int>` as the type of `x`. Would that be at all possible?

If not, I'm fine with picking `List<Object?>` as the top type instead of `dynamic` (it won't be `Object`, that's not a top type, so it's below the actual bound).

**Comment by eernstg** [comment]
I think this could be quite useful, and consistent with the development of Dart in general. Hopefully it won't be too hard to handle the breakage.

I think the main point is that it helps separating dynamism from the expression of general types.

Instantiation to bound (i2b) combines with covariance (unsound and with dynamic checks, as well as any upcoming sound kind of covariance) to provide a common supertype of all the types that explicit type arguments could have expressed (except for some superbounded ones).

This property is completely independent of the choice to use `dynamic` when i2b encounters a type variable with no bound: The use of a more general type can certainly be statically checked and sound, but any occurrence of `dynamic` in a type may give rise to dynamic member accesses.

It would make declarations like `List xs = e` largely impractical to work with, but that's a feature and not a bug ;-)

This makes raw types "general, but sound", which is a much better fit for current Dart than "dynamic whenever you haven't said anything".

**Comment by vsmenon** [comment]
Note, you can opt into this behavior today by using `Object` (or eventually `Object?`) as the explicit bound:

```
void foo<T extends Object>(...) { ... }
```

I found myself doing this last week to separate out the dynamism as @eernstg  put it and flush out dynamic call sites.  Assuming this would be the behavior, I think we get the semantics @lrhn prefers on lists as well.

I would prefer that the default be `Object`/`Object?` - i.e., that `dynamic` be the opt-in either at the call site or definition site.

E.g., given:

```dart
void foo<T extends Object>([T x]) {
  print(T);
}

void bar<T>([T x]) {
  print(T);
}

void baz<T extends dynamic>([T x]) {
  print(T);
}


void main() {
  foo();
  bar();
  baz();
  foo(13);
  bar(13);
  baz(13);
}
```

Today, we get:
```
Object
dynamic
dynamic
int
int
int
```

After, we'd get (+ `?` if NNBD):
```
Object
Object
dynamic
int
int
int
```

**Comment by leafpetersen** [comment]
> I would _very much_ want `List x = <int>[1, 2];` to infer `List<int>` as the type of `x`. Would that be at all possible?

Well, that particular example would be ok, but changing:

```
List x = [1, 2];
```

to infer `<int>` instead of `dynamic` for the reified type argument to the list literal would, almost certainly, be tremendously breaking in the worst way.  And it's not really toolable, because:

```
foo(List x) {}
foo([1, 2]);
```

so the tool would need to change the definition `foo` to keep the existing behavior, and that code may not be in the migrating package.

 So I think we'd need to specify it as doing inference the way that it currently does, and then only after we'd inferred the initializer, replace the `List` with `List<T>` where `T` is derived from the inferred type of the RHS.  Seems a bit complex.

**Comment by srawlins** [comment]
We could prepare existing code for this by changing all `class C<T>...` to `class C<T extends dynamic>...` (> 3000 cases internally), and enforce a lint, "Don't use default bounds" that would allow `C<T extends _anything_>` but ban `C<T>`." (Same for mixin and typedef.)

Alternatively you could _try_ to change each `C<T>` to `C<T extends Object>` and "see if something breaks", then fallback to the current default if it does, `C<T extends dynamic>`. _If_ you could automate that "see if something breaks" bit.

**Comment by leafpetersen** [comment]
My biggest concern is that any API that exposes a raw type must be rewritten to avoid a breaking change to downstream clients.  It put our "you can opt in without breaking packages that depend on you that haven't opted in" promise on thin ice: in order to get that behavior, you have to be sure that none of your APIs have raw types in them.  The migration tool could fix that for you if you ran it, but if not, you may get in trouble.  Example:

```
// Package A exports:
  List getList() => [2];
```

```
// Imports package a, does:
void test() {
  getList()[0].isEven;
}
```

If Package `A` opts in without changing `List getList` to `List<Object> get List`, then the downstream package will break, even though it has not opted in.

**Comment by eernstg** [comment]
@srawlins wrote:
> changing all `class C<T>...` to class `C<T extends dynamic>...`

That would preserve the default at `dynamic` as seen from outside the class, but it's more permissive than we might want for the body of the class (and it would presumably have performance implications):

```dart
class C<X extends dynamic> {
  bool foo(X x) => x.isEven; // Sure, OK!
}

main() => C().foo('qux');
```

> change each `C<T>` to `C<T extends Object>`

But that looks good! Maybe it could be applied to some very heavily used classes, as an experiment. It would amount to an emulation of changing the default, just for those classes, so we'll get a direct measurement of the impact of the change for that slice of the code.

When the coverage is "good enough" (that is, when the Dart community has adapted their code as needed, possibly eliminating some dynamism that they didn't want to have in the first place) then the switch at the language level would be much less breaking.

**Comment by lrhn** [comment]
So the current behavior is that `class C<T>` treats `T` as bounded by `Object` inside the class, but bounded by `dynamic` outside the class (only relevant wrt. i2b).

That's already subtly inconsistent, and means that neither `class C<T extends dynamic>` nor `class C<T extends Object>` matches the current behavior. 
So, we can't keep the current semantics by adding bounds unless we also change the treatment of bounds in some way.

I think my preference would be to let i2b instantiate to `Object?` *even if the bound is `dynamic`*, and migrate raw types to `TheThing<dynamic>` for backwards compatibility (and explicit dynamicness).

This is somewhat consistent with treating `dynamic` as `Object?` from the outside in any contravariant position (which I'd want in other places too).

I'd probably never want a bound of `T extends dynamic` to make `T` act dynamic inside the generic element. I'd be happy disallowing it, but obviously Flutter already uses the feature (`Tween<T extends dynamic>` performs dynamic `T * double` and ` T + T` operations).

**Comment by leafpetersen** [comment]
This is not planned for the current release.
