### ISSUE TITLE
Specify name conflicts for extension members

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#514]
The extension method specification does not make it explicit that the same errors around name conflicts for classes apply to extensions as well, such as:

- it is an error to have a static member and an instance member with the same base name
- it is an error to have to have two instance members with the same base name unless one is a setter and one is a getter
- it is an error to have two static members with the sam base name unless one is a setter and one is a getter

cc @scheglov

**Comment by scheglov** [comment]
When you say "to have", is it the same as "to define" when we are talking about extensions? Extensions don't have superclasses or mixing.

**Comment by leafpetersen** [comment]
Yes, precisely.

**Comment by leafpetersen** [comment]
https://dart-review.googlesource.com/c/sdk/+/112645

**Comment by eernstg** [comment]
This was specified in e6b5545bf9a49e5a9ea92d10bbabba61d3485f3a.
