### ISSUE TITLE
Do late final variables with an initializer induce a setter?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#523]
Based on input from @johnniwinther, we need to consider the following:

A late final variable may or may not have an initializer. With an initializer it supports lazy initialization; without an initializer it supports late initialization by assignment in the scope of the variable (but not subsequent mutation). But some corner cases aren't completely clear.

The NNBD feature specification says [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#late-fields-and-variables) that we have the following error:

> A write to a field or variable which is marked `final` and `late` is a runtime error
> unless the field or variable was declared with no initializer expression, and there
> have been no previous writes to the field or variable (including via an initializing
> formal or an initializer list entry).

Replacing 'unless' by 'if' and negating the tail we get this form:

A write to a field or variable which is marked `final` and `late` is a runtime error if

- the field or variable was declared with an initializer expression, or
- there have been a previous write to the field or variable (including via an initializing formal or an initializer list entry).

It seems unlikely that we'd want to make it a run-time error to write to a variable based on syntactic criteria, because this could obviously be detected statically.

So we might prefer to change this such that it is a compile-time error to write to such a variable when it has an initializer (e.g., when it is declared as `late final int? x = 12;`). The motivation for this rule would be that the variable _should_ be initialized by the given initializer, and it is not allowed to do it by a plain assignment. (I cannot find evidence that such a write is already an error.)

Alternatively, we could say that it is not a compile-time error to initialize a late final variable with an initializer by a plain assignment (in fact, such an error does not seem to be specified today), and also not a run-time error (which would be a change). In this case, the initializer is a _backup_ mechanism that will kick in if and only if no initialization was performed using a plain assignment, at the time when the variable is read for the first time.

The first alternative would improve on static safety (by detecting some errors earlier); the second alternative provides fewer static guarantees, but it could be useful in practice. 

The approach which is most consistent with previous decisions in Dart is probably the first alternative, given that we do not allow an instance variable with an initializer to be initialized in a constructor (via an initializing formal or an entry in the initializer list). So we have previously made the choice against a 'backup' semantics; the upside of this as that developers can read the initializer and trust it.

If we specify that a late final variable with an initializer does not induce a setter then we get the first alternative (any assignments will simply incur a  "no such setter" error). If we specify that it does induce a setter then we can get the second alternative (that setter would then enforce that the variable is never mutated, but it can be initialized, either by evaluating the initializer or by the first assignment).

So I'd propose that we specify that a late final variable with an initializer does _not_ induce a setter.

@munificent, @leafpetersen, @lrhn, WDYT?

**Comment by lrhn** [comment]
I think a final variable with an initializer should *only* be initialized to the value of the initializer.
It should be a static error as well as a run-time error to assign to that variable. As you say: You can read the code and trust it.

It's already a compile-time error to assign to the variable, but that only matters if we can *see* what we are assigning to. A dynamic setter invocation can't. It also matters when you need to implement the interface.

I think it should not have a setter. It should be treated like a *final* variable in all ways, only just one that is initialized late, exactly like a `static final x = 42;` is. The fact that it's late-init is an *implementation detail*.

```dart
class C { 
  late final x = 42;
  noSuchMethod(i) { 
    print("Woot!"); 
  }
}
main() {
  dynamic o = C();
  o.x = 10;  // not static error, does it print "Woot!" or does it throw?
}
class E implements C {
  final x = 42; 
  // missing setter?
}
```

A `late final x;` with no initializer must have a setter. It's slightly annoying that a "final" variable has a setter, but unavoidable for late-init write-once non-local variables.

**Comment by leafpetersen** [comment]
I would prefer that this not define a setter.

**Comment by eernstg** [comment]
Very good, I'll conclude that a `late final` variable with an initializer does not induce a setter, and a `late final` variable without an initializer does induce a setter.
