### ISSUE TITLE
Dart debugging in Visual Code throws handled exceptions as uncaught

### ISSUE THREAD

**Issue by cosinus84** [dart-lang/language#538]
I think this a serious problem when working with dart/flutter.
https://github.com/flutter/flutter/issues/33427

**Comment by munificent** [comment]
Hi, this repository is for working on the design of the Dart language itself. Issues related to Dart implementations like the VM should be filed here: https://github.com/dart-lang/sdk/issues. Issues related to the Flutter framework belong here: https://github.com/flutter/flutter/issues

Thanks!
