### ISSUE TITLE
static extension methods: clarification on noSuchMethod

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#539]
I think this sentence in the spec (section Extension Method resolution) should include the case of noSuchMethod :
"the language first checks whether the static type of x has a member with the same base name as the operation, *or overrides noSuchMethod*"

**Comment by leafpetersen** [comment]
If I have a method call `x.foo()` and the static type of `x` is T then:
  - if `T` is dynamic, then `x` has all methods, including `foo`, and so extension method resolution doesn't apply
  - if `T` is not dynamic, and has a method `foo`, then extension method resolution doesn't apply
  - if `T` is not dynamic, and does not have a method `foo`, then overriding `noSuchMethod` doesn't change anything - the call to `foo` would still be a static error, and so applying extension method resolution can only turn a static error into valid code.

So I don't see any issue here.

**Comment by tatumizer** [comment]
I meant the case when T is not dynamic, and does not have a method foo. but T (T itself, not an extension!) has noSuchMethod defined (overrides noSuchMethod inherited from Object), then x.foo() is NOT a static error right now. Therefore, if we define extension method foo for T, then this extension method will not be called. This case is not covered by current spec.

**Comment by leafpetersen** [comment]
> but T (T itself, not an extension!) has noSuchMethod defined (overrides noSuchMethod inherited from Object), then x.foo() is NOT a static error right now.

This is incorrect.  It IS a static error error right now.  :)  Try it!

**Comment by tatumizer** [comment]
Oh I see. Sorry. I was still living under illusion :)
