### ISSUE TITLE
Operator '[]=' for the class 'Object'

### ISSUE THREAD

**Issue by LeandroDoldan** [dart-lang/language#543]
### Problem
AFAIK, something like the following is impossible to implement:

```
class Updater<T> {
  T entity;

  Updater(this.entity);

  update(String key, dynamic value) {
    entity[key] = value;
  }
}
```

Because the following error is thrown:
```
The operator '[]=' isn't defined for the class 'Object'.
Try defining the operator '[]='.
```

### Request
Please, implement the operator '[]=' for the class 'Object'.

Regarding typing, this is a simple TypeScript-like suggestion:

```
class Updater<T> {
  T entity;

  Updater(this.entity);

  update<K keyof T>(K key, dynamic value) {
    entity[key] = value;
  }
}
```

Thank you!

**Comment by lrhn** [comment]
The `Object` class does not have any `[]` operator. I am assuming you want a behavior similar to JavaScript, but Dart is not JavaScript. You cannot look up members using `[]` and a string name `o["foo"]`, you have to write `o.foo`.
This is a deliberate choice, and if you want to access a member by a name that is only known as a string at runtime, that is reflection and you need to use `dart:mirrors` for it (on a platform supporting `dart:mirrors`).

There are no plans to allow reflection directly on `Object`.

Aside from that, it would break every other class which currently extend `Object` and implement `operator[]` (like `Map`).

**Comment by rakudrama** [comment]
@LeandroDoldan Something like this might work for you:

```dart
// T is the type of things held, instead of the type of the collection.
class Updater<T> {
  Map<String, T> entity;
  Updater(this.entity);
  update(String key, T value) {
    entity[key] = value;
  }
}
```

You could write dynamic code that is against the spirit of Dart. I would advise against this - dynamic invocation is often less efficient and you get no safety or code completion benefits that you would get with stronger typing.
```dart
class Updater<T> {
  T entity;
  Updater(this.entity);
  update(String key, T value) {
    (entity as dynamic)[key] = value;
  }
}
```

I do think it is an interesting idea to 'destructure' the type. If Dart had that feature it might look like

```dart
class Updater<T extends Map<K, V>> {
  T entity;
  Updater(this.entity);
  update(K key, V value) {
    entity[key] = value;
  }
}
```

@lrhn Sometimes it is awkward to 'pass around' several types as type parameters, perhaps the language could support that better.

**Comment by eernstg** [comment]
@rakudrama, just FYI, the 'destructure the type' feature is at the core of the type patterns proposal (#170).

That proposal is intended to be used by other constructs, e.g., a pattern matching `is` test that would amount to an 'existential open' operation:

```dart
void foo<X>(X x, Object y, Object z) {
  if (x is Map<var K, var V>) {
    // K, V denote exactly the value of the type arguments to the type of `x` at `Map`,
    // so this is safe:
    if (y is K && z is V) x[y] = z;
  }
}
```

A similar operation for the relationship between types could certainly be provided (`X isSubtypeOf Map<var K, var V>` would evaluate to true when such a subtype relationship exists for any `K` and `V`, and it would bind `K` and `V` to the actual type arguments of `X` at `Map`).

In the end we did not use type patterns for extension methods, but extension methods are still similar. (Basically, we didn't need type patterns because we decided to match extension type arguments with the statically known values, not the dynamic ones, and then the job can be done using standard type inference.) So you can use extensions for some static cases:

```dart
extension Updater<K, V> on Map<K, V> {
  void myUpdate(K key, V value) => this[key] = value;
}

main() {
  Map<int, int> map = {};
  map.myUpdate(3, 4);
}
```

This would also work in the case where the type of `map` is some subtype of `Map` where you cannot see the type arguments for `Map` directly (say, `class C extends Map<int, int> {...}`), and it does decompose the type in the sense that it allows us to refer to `K` and `V` as types in a scope which is outside the declaration of `Map` (and also outside the body of its subtypes where we could also have access to `K` and `V`).

**Comment by mraleph** [comment]
@LeandroDoldan 

> AFAIK, something like the following is impossible to implement:

I think the question that we should first and foremost ask here is: why do you want such pattern in the first place? 

Can you give a larger example on how you are planning to use such `Updater` class?

**Comment by Vatsboy** [comment]
import 'package:cloud_firestore/cloud_firestore.dart';

import 'dart:html';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(brightness: Brightness.dark, accentColor: Colors.white),
      home: MyApp(),
    ));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List todos = [];
  String input = "";

  createTodos() {
    DocumentReference documentReference =
        FirebaseFirestore.instance.collection("Todos").doc(input);

    Map<String, String> todos = {"todoTitle": input};
    documentReference.set(todos).whenComplete(() {
      print("$input created");
    });
  }

  deleteTodos() {}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("TODO APP"),
      ),
      floatingActionButton: FloatingActionButton(
          onPressed: () {
            showDialog(
                context: context,
                builder: (BuildContext context) {
                  return AlertDialog(
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(16)),
                    title: Text("Add Todo List"),
                    content: TextField(onChanged: (String value) {
                      input = value;
                    }),
                    actions: <Widget>[
                      ElevatedButton(
                          onPressed: () {
                            createTodos();
                            Navigator.of(context).pop();
                          },
                          child: Text("Add"))
                    ],
                  );
                });
          },
          child: Icon(
            Icons.add,
            color: Colors.black87,
          )),
      body: StreamBuilder<QuerySnapshot>(
          stream: FirebaseFirestore.instance.collection("Todos").snapshots(),
          builder: (context, snapshots) {
            return ListView.builder(
                 itemCount: snapshots.data!.docs.length,
                itemBuilder: (context, index) {
                  DocumentSnapshot documentSnapshot =
                      snapshots.data!.docs[index];
                  return Dismissible(
                      key: Key(index.toString()),
                      child: Card(
                        elevation: 4,
                        margin: EdgeInsets.all(8),
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(8)),
                        child:ListTile(
                          title: Text(snapshots.data!["todoTitle"]),             
                          trailing: IconButton(
                            
                            icon: Icon(
                              Icons.delete,
                              color: Colors.red,
                            ),
                            onPressed: () {
                              setState(() {
                                todos.removeAt(index);
                              });
                            },
                          ),
                        ),
                      ));
                });
          }),
    );
  }
}




#The operator '[]' isn't defined for the type 
                                                                                                                       'QuerySnapshot<Object?>'.
                                                                                                                         Try defining the operator '[]'.

**Comment by Vatsboy** [comment]
please help

**Comment by Levi-Lesches** [comment]
@Vatsboy, your error isn't related to this issue. Try posting it on StackOverflow.com for an explanation of your error.
