### ISSUE TITLE
Use Type() instance as a generic Type Parameter?

### ISSUE THREAD

**Issue by G5Becks** [dart-lang/language#549]
Let's say am storing functions with type information in a map

```
static final Map<int,Tuple2<Function,Type>> _taskToRunMap = <int,Tuple2<Function,Type>>{}
```

and I want to be able to convert them to their original type upon retrieval.

```
static Type _getTaskToRunType(int taskToRunHash) => _taskToRunMap[taskToRunHash].item2;

static T _getTaskToRun<T extends Function>(int taskToRunHash) => _taskToRunMap[taskToRunHash].item1 as T;

static Future<T> getExecutable<T extends Function>(int taskToRunHash) async {
    return _getTaskToRun<T>(taskToRunHash);
}
final taskType = _getTaskArgsType(12345);
getExcecutable<_taskType>(12345);
```

When I call getExecutable, then I will get an error saying that "taskType isn't a type so it can't be used as a type argument".

I do understand that Type() is a class, that, as explained in the API reference is a Runtime representation of a type.

So

```
final typeMap = <String,Type>{"string":String};
Type getType(String key) {
    return typeMap[key];
}


void main() {
  print(getType("string"));
}
```

Will return String, what I don't understand is why instances of Type can't be used as generic parameters.

Can someone please explain? Also, if there is a common workaround to this I'd appreciate it if someone could share.

Thanks.

**Comment by lrhn** [comment]
I answered [on StackOverflow](https://stackoverflow.com/questions/57679570/why-cant-i-use-type-instance-as-a-generic-type-parameter).

In short: Dart keeps type parameters static to improve static analysis and tree-shaking. Converting a run-time `Type` object to a type argument would foil that.
