### ISSUE TITLE
Specification: Eliminate the distinction between the static and instance scope of a class?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#550]
The language specification says (and has basically always said) that a class has the scope structure library scope > type-parameter scope > static scope > instance scope, where static/instance members live in the static/instance scope, respectively:

> A class has several scopes:
>
> - A type-parameter scope which is empty if the class is not generic.
>   The enclosing scope of the type-parameter scope of a class is the enclosing scope
>   of the class declaration.
> - A static scope. The enclosing scope of the static scope of a class is
>   the type parameter scope of the class.
> - An instance scope. The enclosing scope of a class' instance scope is the 
>   class' static scope.
>
> The enclosing scope of an instance member declaration is
> the instance scope of the class in which it is declared.
> 
> The enclosing scope of a static member declaration is
> the static scope of the class in which it is declared.

Surprisingly, constructors do not live in any scopes (I can't find an answer to that question in the specification, except that the question is raised in a couple of old comments). So that's one little thing to fix.

However, and more seriously: This implies that an instance member is simply not in scope inside a static declaration. In particular, it implies that the following program has no errors:

```dart
int x;

class A {
  String x;
  static foo() => x.isEven; // OK!
}
```

We have special rules about the treatment of names of the form `x` and `x=`, but in this case that makes no difference: As seen from the static scope of `A` there is only one declaration of `x` (and none named `x=`), and that's the top-level variable.

However, the common front end and the analyzer are (of course ;-) not happy about this program. First the response from the analyzer, commit 0c06fbd88fed6943959192932ca480d73db19377:

```
ERROR|COMPILE_TIME_ERROR|INSTANCE_MEMBER_ACCESS_FROM_STATIC|/usr/local/google/home/eernst/lang/dart/scratch/201908/n035.dart|5|19|1|Instance members can't be accessed from a static method.
ERROR|STATIC_TYPE_WARNING|UNDEFINED_GETTER|/usr/local/google/home/eernst/lang/dart/scratch/201908/n035.dart|5|21|6|The getter 'isEven' isn't defined for the class 'String'.
```

Similarly for `dart` from the same commit:

```
n035.dart:5:19: Error: Getter not found: 'x'.
  static foo() => x.isEven; // OK!
                  ^
```

I have no idea how the CFE arrives at the conclusion that there are too few getters around, but the point is that the currently specified scope structure is not what the implementations are using.

It seems much more reasonable to say that the tools are merging the static scope and the instance scope into one scope, and then there is a special rule that instance members cannot be accessed using the scope rules (but we of course can do things like `e.x` when `e` has type `A`).

So we have some freedom to change the specified scope structure, and still consider this to be a non-breaking change.

So here's a proposal:

- We eliminate the notion of 'the static scope' and 'the instance scope' of a class.
- We introduce the notion of 'the body scope' of a class, and let all static members, instance members, and constructors live in the body scope.
- Special rules are already in place in #548, ensuring that it is an error to access an instance member using implicit instance member access (such as an identifier reference or assignment, `myInstanceVariable`/`myInstanceVariable = "Hest"`; or an unqualified invocation `myInstanceMethod(42)`) from any location which is not in the body of an instance member or generative constructor (soon: or an initializing expression of a `late` instance variable).

@munificent, @lrhn, @leafpetersen, WDYT?

**Comment by lrhn** [comment]
Fix it!

**Comment by leafpetersen** [comment]
LGTM.

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/sdk/issues/38352#issuecomment-667447459, this change is aligned with recent changes to the analyzer, so it's unlikely that there is any breakage. It'll be done as part of the 2.8 stable version of the language specification.

**Comment by munificent** [comment]
LGTM+++++=100.

> We introduce the notion of 'the body scope' of a class, and let all static members, instance members, and constructors live in the body scope.

I would just call it the "class scope" if it were me.

> * Special rules are already in place in #548, ensuring that it is an error to access an instance member using implicit instance member access (such as an identifier reference or assignment, `myInstanceVariable`/`myInstanceVariable = "Hest"`; or an unqualified invocation `myInstanceMethod(42)`) from any location which is not in the body of an instance member or generative constructor (soon: or an initializing expression of a `late` instance variable).

I think there are also special rules for prohibiting you from accessing a type parameter from a static member:

```dart
class T {}

class Foo<T> {
  static bar() { <T>[]; } // Error.
}
```

So the idea of "in scope but can't use it" is pretty well established. :)

**Comment by eernstg** [comment]
Done in https://github.com/dart-lang/language/pull/1400.
