### ISSUE TITLE
Specify override inference special casing for operator == in legacy libraries

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#569]
The current signature of `Object.==` takes `dynamic` as the argument.  If we change this to `Object` in NNBD it will be by default a breaking change.  To work around this, we propose to special case override inference as follows:

```
In legacy mode, an override of operator== with no explicit parameter type inherits the parameter type of the overridden method if any override of operator== between the overriding method and Object.== has an explicit parameter type.  Otherwise, the parameter type of the overriding method is dynamic.
```

I think that makes it non-breaking to:
  - change Object.== to take Object
  - remove the `dynamic` parameter type on Duration, Point, and Rectangle.

cc @stereotype441 @lrhn

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/124284

**Comment by a-siva** [comment]
@johnniwinther is there a tracking issue in CFE for implementing this special casing, building a SDK with opted in core libraries is currently blocked on CFE implementing this.

**Comment by johnniwinther** [comment]
I've created https://github.com/dart-lang/sdk/issues/40334 for the CFE

**Comment by leafpetersen** [comment]
PR out with the spec for this.
