### ISSUE TITLE
Feature request:  Can we use 'vw', 'vh' and so on when setting widget size?

### ISSUE THREAD

**Issue by gzf6** [dart-lang/language#587]
## Use case

As we all know, if we want the flutter app to run on a high resolution device, we must handle the size If we want to get a correct proportion. For example, handle the size by the flutter_screenutil package. Or we can calculate ’vw‘ by the following method:

`1vw = window.physicalSize.width / window.devicePixelRatio / 100`

We can define a function like this to use it in everywhere:

```
double vw(double widthPer) {
  return widthPer * 1vw ;
}

Future main() {
  runApp(MyApp());
}

// some widget
Container(
  width: vw(50);
);
```

## Proposal

So can we have a built-in unit like ’vw‘?  Then we can use it like this:

```
Container(
  width: 50vw;
);
```

**Comment by munificent** [comment]
This feature request is a little out of scope for this repository. Here, we track changes to the Dart language and its built-in libraries. The language and core library aren't tied to any particular Flutter package, so we wouldn't be able to support this in the core library.

However, we are adding extension methods to the language. With those, a third-party package could define a `vw` getter on `num`, like so:

```dart
extension WindowUnits on num {
  double get vw => this * window.physicalSize.width / window.devicePixelRatio / 100;
}
```

Then you can use it like:

```dart
Container(
  width: 50.vw;
);
```
