### ISSUE TITLE
Better way to use null operator and check length at the same time?

### ISSUE THREAD

**Issue by jdeltoft** [dart-lang/language#598]
Sometimes I want to use the null operator on my inherited data to avoid using it if it's null. So I'll do something like this:

`if ((SessionInfo.of(context).myCommissionData == null) || (SessionInfo.of(context).myCommissionData.length == 0)) { ... }
`

But is there a better way to do something like this:

`if (SessionInfo.of(context).myCommissionData?.length > 0) { ... }
`

This complains, since you can't compare "null" to zero with > .

**Comment by natebosch** [comment]
The idiomatic approach is:

```dart
if (SessionInfo.of(context).myComissionData?.isNotEmpty ?? false) {
```

https://dart.dev/guides/language/effective-dart/usage#dont-use-length-to-see-if-a-collection-is-empty
https://dart.dev/guides/language/effective-dart/usage#do-use--to-convert-null-to-a-boolean-value
