### ISSUE TITLE
Why doesn't Dart have destructors? 

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/language#603]
Hi,
I really could use a destructor sometime when writing Flutter code.
Why doesn't Dart have them?
Especially for closing Streams it would be helpful.

Cheers
Thomas

**Comment by mraleph** [comment]
Because among many other things you would not be able to compile this feature into JavaScript.

Also I recommend using mailing list (like dart-misc) for asking language questions - rather then filing issues.
