### ISSUE TITLE
Switch statement issues

### ISSUE THREAD

**Issue by akkinenirajesh** [dart-lang/language#618]
Why single empty case will fall through but not more than one?
`switch(x){
  case 'a':
  case 'b': return 'B';
}
`
Above code works... but
`switch(x){
  case 'a':
  case 'b':
  case 'c': return 'B';
}
`
Does not work. What is the reasoning behind this strange design decision?
Why does case needs a break statement in following code?
`switch(x){
  case 'c': 
    if(y){ return 'B'; }else{ return 'C' }
    break;
}`
Without that `break;` it does not seem to work?

**Comment by lrhn** [comment]
How does
```dart
switch(x){ case 'a': case 'b': case 'c': return 'B'; }
```
not work?

The specification is that it should return `B` if `x` is any of the strings `"a"`, `"b"` or `"c"`, and as far as I can see, it does that consistently.

So, no strange design decision there, it should work.


As for why the `break` is needed: Dart is currently not very clever about switch cases. They *must not* fall through to the end of the case, but the compiler can only recognize that it doesn't if the case itself ends with a control flow statement like `break` or `return`. It's not smart enough to see into the `if` statement to check that both branches end in control flow statements. We hope that the control flow analysis added for non-nullable types will also be usable to improve this case.

**Comment by akkinenirajesh** [comment]
Thanks. It was my mistake in checking the first issue.
