### ISSUE TITLE
@required ignored for named parameters in Function types

### ISSUE THREAD

**Issue by vr19860507** [dart-lang/language#619]
This code should not work, but it works!
```
import 'package:meta/meta.dart';

int Function({@required int a}) f1 = ({int a}) => 1;
int Function({int a}) f2 = ({@required int a}) => 1;

void main() {
  print(f1 is int Function({@required int a})); // true
  print(f1 is int Function({int a})); // true
  print(f2 is int Function({@required int a})); // true
  print(f2 is int Function({int a})); // true
}
```

**Comment by lrhn** [comment]
It should work.

The Dart language does not have a notion of required named parameters (yet), and the `@required` annotation has no effect on running Dart code. 

The annotation tells the analyzer that you intend the argument to be required, even if you can't force it in the language. The only thing the analyzer can do is to give a static warning if it's not satisfied. Annotations have no effect at run-time, so there is no way it can affect a run-time type check. 

To the language, and the run-time system, your two function types are completely equivalent.

With non-nullable types, Dart will also get `required` named parameters  as a *language* feature. At that time, you will be able to make the distinction at run-time. We needed that feature to allow non-nullable named parameters with no default value, which is what the current `@required` parameters will likely become with non-nullable types.

**Comment by vr19860507** [comment]
> Dart will also get required named parameters as a language feature. 

This is great.
Thank you!
