### ISSUE TITLE
Generic type inference issue 

### ISSUE THREAD

**Issue by siqwin** [dart-lang/language#623]
There is an issue with type inference:

```
class ConcreteA {}
class ConcreteB {}

abstract class BaseBuilder<A, B> {
  A build(B b);
}

class ConcreteBuilder extends BaseBuilder {
  @override
  ConcreteA build(ConcreteB b) {
    return ConcreteA();
  }
}
```

Get an error:

`Error: 'ConcreteBuilder.build' ('ConcreteA Function(ConcreteB)') isn't a valid override of 'BaseBuilder.build' ('build')`

It eliminated only by explicitly specifying the generic types of the base class.
At the same time, I note that the next code works, and the type is inference correctly:

```
class ConcreteA {}

abstract class BaseBuilder<A> {
  A build();
}

class SomeBuilder extends BaseBuilder {
  @override
  ConcreteA build() {
    return ConcreteA();
  }
}
```

Thus, if a generic type is used as the return value of a function, then it is inference correctly. If it is used as a function parameter, an error occurs. So the question is it possible to inference types for parameters of functions in generic classes or there any hidden problems with it?

**Comment by eernstg** [comment]
This working as intended, because it is not a safe override: the caller can't know that you require a `ConcreteB` argument when the receiver type is `BaseBuilder<Object, Object>`.

**Comment by eernstg** [comment]
@siqwin, do you wish to turn this into a language proposal for some kind of type argument inference on superinterfaces? Otherwise I believe we can close the issue because the current behavior matches the intended behavior.

**Comment by siqwin** [comment]
@eernstg No, it works correctly, you really helped me to understand it. Many thanks!

**Comment by eernstg** [comment]
Thank you!
