### ISSUE TITLE
Grammar does not allow configurableUri in deferred import, but tests do

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#627]
The language specification has the following grammar rules for import clauses:

```
<importSpecification> ::= \gnewline{}
  \IMPORT{} <configurableUri> (\AS{} <identifier>)? <combinator>* `;'
  \alt \IMPORT{} <uri> \DEFERRED{} \AS{} <identifier> <combinator>* `;'
```

This implies that it is a syntax error to use a `<configurableUri>` in a deferred import. However, the following language tests use such a deferred configurable uri:

- [conditional_import_test](https://github.com/dart-lang/sdk/blob/a61c775db81ef2a389d5aee6236176362b082d58/tests/language_2/conditional_import_test.dart#L11)
- [conditional_import_string_test](https://github.com/dart-lang/sdk/blob/a61c775db81ef2a389d5aee6236176362b082d58/tests/language_2/conditional_import_string_test.dart#L11)

We should allow this in the grammar if we want to have it, or we should remove the use of the feature in the tests.

@lrhn?

**Comment by lrhn** [comment]
It's a spec bug, so we should allow it.

**Comment by eernstg** [comment]
Fine. Fixed this and a few more grammar bugs in [this PR](https://github.com/dart-lang/language/pull/628).
