### ISSUE TITLE
How strict should override inference be?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#634]
Cf. SDK issue https://github.com/dart-lang/sdk/issues/39030.

Override inference provides type annotations to parts of an instance member declaration where they have been omitted. For instance:

```dart
abstract class A { num get g; }
abstract class B implements A { get g => 1; }
```

The return type of `B.g` can be inferred as `num`, based on the signature of `A.g`. Similarly for parameter types. A local analysis of `B.g` could give rise to the return type `int`, but a member signature which is based on superinterfaces is a safer choice because (1) it works for parameters as well, and (2) it is concerned with the public interface of the enclosing class, which is a more robust foundation than the implementation of any given member.

In the case where multiple signatures are provided by multiple superinterfaces, the computation of the interface of the class proceeds by computing the combined member signature for each member that isn't overridden:

```dart
abstract class I {
  num f(int i);
  Object get g;
}
abstract class J { 
  int f(num n);
  dynamic get g;
}
abstract class A implements I, J {
  String get g;
}
```

For `g` we use the declaration in `A`, and it gets the signature `String get g`. For `f` there is no declaration in `A`, so we compute the member signatures in `I` and `J` and select the most specific one (which is `int f(num)`, because `int Function(num)` is a subtype of `num Function(int)`). If there are multiple most-specific signatures then we take the one that is provided by the textually first superinterface.

The computation of a combined member signature may fail: There could be multiple signatures from superinterfaces, but none of them is the most specific. In that case a compile-time error occurs, and the developer who's writing class `A` must add a declaration (possibly abstract) in order to disambiguate that member signature.

For override inference we currently have some discrepancies: Issue https://github.com/dart-lang/sdk/issues/39030 shows an example where the analyzer obtains a member signature, but the common front end reports an error.

The common front end behavior seems to be based on a rule whereby override inference refuses to provide any type annotations in a member signature in the case where there are distinct member signatures in the superinterfaces. (So if there is exactly one member signature for a member name `m` then we use it, and if there are several identical signatures for `m` then we still use it, but if there are several non-identical signatures then we just stop and report an override inference error).

I cannot see any documentation for this choice, so it's not obvious whether the analyzer or the common front end does "the right thing".

It should be noted that the strict behavior (like the common front end) is safer in the pragmatic sense that a developer who is working with a member `m` in a class `C` could read the code in _any_ direct superinterface `S` of `C` and trust that if a type annotation is present in the declaration of `m` in `S` then if override inference has occurred for that type annotation in `C` then it must have used that type (modulo the transition from `C` to `S` where type parameters of `C` could be passed to `S` in many ways).

On the other hand, we could use an approach which is more like the computation of the interface of a class: If there is a most specific member signature _s_ for `m` in the direct superinterfaces of `C` then override inference for `m` in `C` can use _s_ to infer return/parameter types for `m` in `C`. This would allow for less verbose software, because override inference is available in a larger set of cases, which may be helpful for both readers and writers of code, especially when IDE support can show the actual signature at locations where it is inferred.

Given that the strict behavior still requires the reader to compute the actual type arguments, the benefits of using the strict approach may not be particularly tangible. For instance:

```dart
abstract class A<X> { X get g; }
abstract class B<X> extends A<List<X>> { get g => []; }
```

In this case the reader of the code may look up `A` and see the signature `X get g`, but we must still compute the resulting signature for `B.g` as `List<X> get g` based on the superinterface declaration `A<List<X>>`. So having an IDE show `List<X>` when hovering over `B.g` is more practical than looking up `A.g` and computing the type manually.

On the other hand, I do not think it would be a good idea to introduce yet another concept (say, "the combined type annotation for each formal parameter"), even if that would allow override inference to take place in an even greater set of circumstances. This follows our usual guideline of not inventing complex entities (we would invent a member signature rather than reusing one that exists in the program already).

So which way do we want to go? Require member signatures to be identical, or compute the combined member signature and use that? Or some third thing?

@lrhn, @munificent, @leafpetersen, WDYT?

**Comment by lrhn** [comment]
Whenever you omit types and expect to inherit them from the super-interfaces, there must be a single canonical and predictable super-interface signature that you inherit from.

Whichever algorithm we use to figure out the unified, canonical, most-specific signature that you would inherit from the super-interface if you did not have a declaration, we should use the same algorithm (and same compile-time error causing failures to find a solution) for the inherited types.
There should only be one algorithm, the "find best signature among superinterfaces".
(The same algorithm we use to unify the super-interfaces of mixins too).

So "compute the combined member signature and use that".

(I don't want to introduce a new algorithm for just finding the most specific return type, if the return type is the only type you omit. I'd also be perfectly happy to completely remove the "type inheritance" feature.)

**Comment by eernstg** [comment]
> compute the combined member signature and use that

Sounds good! That's exactly my preferred approach. ;-)

**Comment by eernstg** [comment]
Closing: Today we're consistently using the combined member signature when a member signature is required and none is declared in the receiver class itself. Also, the combined member signature uses `NNBD_TOP_MERGE` to compute which top type to use whenever there is a top type in the signature, which is different from the approach described above. (The described approach was used in 2019, but the specification and implementation have been changed since then).
