### ISSUE TITLE
Should we allow type variables as potentially constant expressions as part of NNBD?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#640]
We will remove implicit downcasts as part of the NNBD release.  This will require users to make implicit downcasts explicit.  This is currently not possible if the implicit downcast occurs in a constant constructor and the target type is a generic type variable.  Example:

```dart
const num three = 3;

class Foo<T extends num> {
  final T w;
  const Foo() : w = three /* as T */;
}

void main() {
  print(const Foo<int>());
  /* print(const Foo<double>()); */ // Cast will fail
}
```

This example is currently accepted, and an implicit cast is inserted on the initialization of `w`.  However, making the cast explicit by adding `as T` to the initialization expression is not allowed, since `T` is not considered a constant expression.

Should we consider allowing "potentially constant" types in casts?  That is, change:

```
\item An expression of the form \code{$e$\,\,as\,\,$T$} is potentially constant
  if $e$ is a potentially constant expression
  and $T$ is a constant type expression,
  and it is further constant if $e$ is constant.
```
to say "and $T$ is a potentially constant type expression" where "potentially constant type expression" is defined exactly as "constant type expression" with the addition that a type variable is allowed as a "potentially constant type expression".

cc @vsmenon @jakemac53 @lrhn @eernstg @munificent

**Comment by eernstg** [comment]
Sounds good! I think we can allow for an explicit `as S` (and presumably `is S` as well) where `S` is a type that is potentially constant in that sense (so it may contain type variables from the enclosing class).

It is a subtle area, of course, so it could be useful to note where we usually put the fence. When requests have been made for more powerful constant expressions, we have used a couple of properties as outer limits for their power (arguing that we don't want Turing completeness, and not even recursion, in compile-time computations).

One of those properties is that we do not allow for composite constant expressions to have more than one corresponding object; for instance, a syntactic occurrence like `const C(e)` must correspond to _one_ object at runtime. So `e` must be a constant expression, and in particular it can't contain formal parameters of an enclosing constant constructor.

If we wish to preserve that property then we would at least have to prevent type variables from the enclosing class from occurring in composite terms like list literals and constant constructors:

```dart
class C<X> {
  final List<X> xs;
  final List<bool> ys;
  final C<X> c;
  const C(): xs = <X>[], [2 is X], const C<List<X>>();
}
```

I think the proposed change does enforce this constraint. Can you think of other ways to extract powerful computation from the permission to have these new potentially constant expressions?

**Comment by lrhn** [comment]
I do want that. 
I doubt it will be essential in that many cases, because casts are typically unsafe, and you rarely do unsafe things in const constructors, but there will be the occasional case where you know something the type system doesn't.

The only workaround that I have found is to go through dynamic (because we *do* allow downcast from dynamic, and we can cast to dynamic using `as dynamic` because that is compile-time constant).

**Comment by leafpetersen** [comment]
This is specified.
