### ISSUE TITLE
Cannot do explicit downcasts (or type checks) in const constructor initializer list.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#642]
Some code patterns, especially around numbers, may need to do downcasts or type checks during const object construction.
Say:
```dart
class C<T extends num> {
  T positiveNum;
  const C(T value) : positiveNum = value < 0 ? value * 0 : value;
}
```
There is existing code written like this (it's an obscure case, but there are perhaps less obscure cases too).

The static type of `value * 0` is `num` which is not assignable to `T` without implicit downcasts.

The workarounds would be `(value * 0) as T`, but that requires an explicit downcast with a non-compile-time constant type, which is also not allowed.

So, perhaps we should allow `as T` (and `is T`) as potentially constant expressions when `T` is a "potentially constant type" (meaning a type argument to the class being constructed).

**Comment by eernstg** [comment]
Duplicate of #640?

**Comment by lrhn** [comment]
Yes.
I should read before writing. :)
