### ISSUE TITLE
Allow no default on an optional parameter with nullable type for abstract method

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#655]
In an instance method declaration, we **require a default value for each optional parameter whose type is potentially non-nullable** (alternatively, the parameter can be marked as `required`).

The reason for this is that an invocation of said method can no longer use `null` as the default value when the parameter has no default value clause.

However, there is no need to have a default value for such a parameter when the method declaration is abstract; that situation is actually rather similar to that of a function type where we do not require (and do not allow) default values to be specified.

So we could **lift this restriction in abstract method declarations**.

Here is an example:

```dart
abstract class A<X> {
  void f([X x]);
}

class B1 implements A<int> {
  void f([int i = 2]) {}
}

class B2 implements A<double> {
  void f([double d = 2.0]) {}
}

class B3<X extends Widget> implements A<X> {
  // If we can't come up with a reasonable default, null is always a possible backup.
  void f([X? x]) {}
}

main() {}
```

This could be helpful in some situations: With the current rules, it is not possible to specify a default value for `x` in `A.f` (because we don't have a notion of "the default value of type `X`", and it wouldn't be trivial to add support for any such feature), and it might be inconvenient to use the parameter declaration `X? x` in `A.f`, because it introduces the need for code that handles null in all subclasses of `A`. With the relaxation proposed here, it could be declared as shown above.

We only relax the treatment of abstract declarations&mdash;the requirement is still enforced for every _implementation_ of the method: So `B1.f` and `B2.f` must provide a suitable default value for the parameter, or they must change the type to be nullable like `B3.f` (which is always allowed because parameter types are contravariant, and `X <: X?`).

Of course, with this relaxation we have to interpret abstract method declarations accordingly: A named parameter is required if and only if it has the modifier `required`. I believe that the NNBD feature spec does not make this explicit, but language tests imply that a named parameter with a potentially non-nullable type and no default value is an error (it doesn't implicitly become a `required` parameter). So allowing an optional parameter with no default to have a potentially non-nullable type in an abstract method declaration would be a non-breaking change.

WDYT, @munificent, @leafpetersen, @lrhn?

**Comment by lrhn** [comment]
Seems reasonable. I can't find any holes in the arguments.

The requirement that the potentially non-nullable optional parameter must have a default value comes from the requirement that a non-nullable variable must have a value when it's accessed. If you omit the argument, then the parameter would not have any reasonable value.
An abstract method doesn't access its arguments, so that requirement is irrelevant.

**Comment by leafpetersen** [comment]
I have added this to a pull request on the specification, any objections?  @lrhn @eernstg @munificent ?

**Comment by eernstg** [comment]
No ;-)

**Comment by munificent** [comment]
I already gave it the old thumbs up. It's a good change. :)

**Comment by lrhn** [comment]
Ship it!

**Comment by rrousselGit** [comment]
Would that work with named parameters?

```dart
abstract class Base<T> {
  void someMethod({T value});
}

class Concrete extends Base<int> {
  void someMethod({int value = 2}) {}
}

class Concrete2<T extends Widget> extends Base<T> {
  void someMethod({T? value}) {}
}
```

**Comment by leafpetersen** [comment]
> Would that work with named parameters?

Yes.

**Comment by leafpetersen** [comment]
This is specified.
