### ISSUE TITLE
Specify that the null aware cascade operator applies to the entire sequence.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#659]
The following program should be accepted: the feature spec should be clearer on the treatment of cascade sequences.

```dart
void main() {
  int? x = null;
  x?..isEven; // ok
  x?..isEven..isEven; // ok.
}
```

**Comment by stereotype441** [comment]
To make sure I understand the consequences of what you're proposing here, consider this program:

```dart
extension E on int? {
  void f(int n) { print('${this}.f($n)'); }
}
main() {
  int? x = null;
  var y = x..f(1)?..f(2)..f(3);      // (A)
  var z = x?..f(4)?..f(5);           // (B)
}
```

I believe that `(A)` would be valid, and would desugar to something like:
```dart
  var tmp = x;
  E(tmp).f(1);
  if (x != null) {
    E(tmp).f(2);
    E(tmp).f(3);
  }
  var y = tmp;
```
Therefore it would cause `null.f(1)` to be printed, and nothing else.

And I believe that `(B)` would be valid, and would desugar to something like:
```dart
  var tmp = x;
  if (x != null) {
    E(tmp).f(4);
    if (x != null) {
      E(tmp).f(5);
    }
  }
  var z = tmp;
```
Therefore it would cause nothing to be printed.  (Note that the second `if` is redundant but I don't see any reason to disallow it).

Does this sound correct?

**Comment by eernstg** [comment]
The repeated `?..` is actually a syntax error according to the specification and the common front end, so the analyzer should reject it on that basis. With parentheses we'd have `(x..f(1))?..f(2)..f(3)`, which would be OK and print 'null.f(1)', and `(x?..f(4))?..f(5)` is OK and doesn't print anything.

**Comment by stereotype441** [comment]
> The repeated/non-innermost `?..` is actually a syntax error according to the specification and the common front end, so the analyzer should reject it on that basis. With parentheses we'd have `(x..f(1))?..f(2)..f(3)`, which would be OK and print 'null.f(1)', and `(x?..f(4))?..f(5)` is OK and doesn't print anything.

Got it, thanks!
