### ISSUE TITLE
Should we allow demotion to the non nullable version of a previously promoted type?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#688]
In the NNBD promotion proposal, a non-initializing assignment of an expression of type `T` to a variable `x` demotes to the most precise type `S` that is a supertype of `T` and that is one of the previously promoted types of `x`.  This means that the following code is valid, since the assignment of `2.0` to `x` demotes to `num`.

```dart
void main () {
  Object? x = 4;
  if (x is num) {
    if (x is int) {
      x = 2.0;
      x.isFinite;
  }}
}
```

However, if the first check on `x` is changed to `x is num?` the demotion no longer demotes to `num`, since `num` is not one of the previously promoted types of `x`:

```dart
void main () {
  Object? x = 4;
  if (x is num?) {
    if (x is int) {
      x = 2.0;
      x.isFinite; // Error
  }}
}
```

Should we allow demoting to the non-nullable version of previously promoted types?

cc @lrhn @eernstg @munificent @johnniwinther @stereotype441

**Comment by lrhn** [comment]
I vote yes.

If we let any assignment do non-`null`-promotion, and we allow any assignment to do demotion, then `x = 2.0;` can reasonably be seen as first demoting to `num?` and then also promoting that to `num`.

If we don't do that, then replacing `x = 2.0;` with `x = 2.0; x = 2.0;` would still work (I think). 
The first assignment type-of-interest-demotes `x` to `num?` from `int` with the types-of-interest `Object?`, `num?`, and `int`. 
The second assignment non-null-promotes `x` to `num` from `num?`.

That should probably work with one assignment too.

**Comment by eernstg** [comment]
Yes, too. I think we have agreed that if `T?` is of interest then `T` is also of interest (and even in the case where `T` is a potentially nullable type like `X extends num?` we do recognize that promotion can yield a non-nullable type). So we could adjust the rule from

> the most precise type `S` that is a supertype of `T` and that is one of
> the previously promoted types of `x`

to ' the most precise type `S` that is a supertype of `T` and that is a type of interest for `x`' then we'll get the promotion.

**Comment by leafpetersen** [comment]
This change has landed in the flow analysis spec.
