### ISSUE TITLE
Uniform tear-off syntax

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#691]
(based on discussion in #376)
Proposing new syntax for tear-offs to cover several use cases. General form: `obj.(thing-to-tear-off)`
Examples:
a.(+) // operator tear-off
a.(unary-)
a.(get x) // getter tear-off
a.(set x) // setter tear-off
Foo.(new) // default constructor tear-off
Foo.(new named) // named constructor tear-off

**Comment by eernstg** [comment]
Cf. [this discussion on dart-misc](https://groups.google.com/a/dartlang.org/d/msgid/misc/3f92ef96-1744-4268-a2cd-2dac7134bed7%40dartlang.org?utm_medium=email&utm_source=footer):

It would also be useful to consider tear-offs of instance methods independently of the receiver. That is, a method with `k` positional arguments is torn off as a function with `k + 1` positional arguments, and the first argument is the receiver.

Getters and setters could be handled as described above, we'd just change `a` from an expression denoting an instance to a type literal: `Class.(thing-to-tear-off-with-receiver-argument)`.

**Comment by tatumizer** [comment]
Yes! The syntax will become even more uniform then! :-)

**Comment by rrousselGit** [comment]
I don't see myself ever using `a.(get x)` when I can write `() => a.x`.

They take the same number of characters, but the closure approach is easier to refactor.

**Comment by tatumizer** [comment]
@rrousselGit : #Foo is already a Symbol

**Comment by rrousselGit** [comment]
The character doesn't really matter.
We can change it to something else, like `~` or `::`

**Comment by tatumizer** [comment]
@rrousselGit : this issue has a long history. Please notice that without parentheses, compiler can't resolve the ambiguity while parsing `::Foo.named` - it can as well be `(::Foo).named` - that is, extension method 'named` called on Function.

@eernstg : the syntax can be expanded also in another direction, e.g. if f is a function, then we can implement currying like this: `f.(curry "hello", color: Color.red)`. Just a thought :)

**Comment by natebosch** [comment]
> It would also be useful to consider tear-offs of instance methods independently of the receiver.

Does this have the semantics of picking a concrete implementation statically? Or will it have the semantics of wrapping with a closure and the concrete implementation is still picked at runtime?

I don't think the former would work:

```dart
class Foo {
  int get _private => 1;

  int get public => 2;

  void doStuff() {
    print(_private + public);
  }
}

// Some other library.
class Bar implements Foo {
  @override
  void doStuff() {}

  @override
  int get public => 3;

  // No override of _private possible
}

void main() {
  void Function(Foo) tornOff = Foo::doStuff;
  tornOff(Foo()); // OK
  tornOff(Bar()); // throws? What would the error be?
}
```

I think the latter would be fine. Effectively `Foo::doStuff` is syntactic sugar for `(Foo f, <other args>) => f.doStuff(<other args>);`

**Comment by eernstg** [comment]
> Does this have the semantics of picking a concrete implementation statically?

No, the idea is simply that with `abstract class C { S foo(T); }` a tear-off like `myC.foo` yields something that works like `(T t) => myC.foo(t)`, and `C.foo` yields `(C self, T t) => self.foo(t)`. So that's what you call 'the latter'.

**Comment by kasperpeulen** [comment]
What about a default first parameter name called `it`

```
=> a + it // operator tear-off
=> a - it
=> a.x // getter tear-off
=> a.x = it // setter tear-off
=> Foo(it) // default constructor tear-off
=> Foo.named(it) // named constructor tear-off
```

**Comment by tatumizer** [comment]
@kasperpeulen : 
In #265, this syntax is proposed for a different purpose. (There's also discussion #712 that suggests replacing `it` with `$0`,  but it's not relevant here). You would probably agree that "tearoff" is not the first idea that comes to mind when one looks at expression `=> a + it` :-)

**Comment by kasperpeulen** [comment]
Right, my point is that I don`t think we really need new tear-off syntax, if we have #265.

**Comment by eernstg** [comment]
There is one thing that a tear-off is capable of doing that we can't emulate with a manual rewrite, namely the special behavior for equality tests (operator `==`): Two tear-offs of the same method will test equal iff they were torn off the same receiver (`o1.foo == o2.foo` iff `identical(o1, o2)`). This property could be carried over to the new kind of tear-off (where we tear an instance method off of a class, yielding a function that adds an extra positional argument accepting the receiver): They could be equal iff they tear off the same method of the same statically known receiver type. A similar property could be defined for getters and setters and constructors.

**Comment by tatumizer** [comment]
Another approach to constructor tear-offs will be: introduce *partial function application* mechanism (pseudo-method `bind`, instrinsified by a compiler) that works for functions as well as constructors, e.g. 
```
foo(int x, int y) {...}
Function foo1=foo.bind(0); // returns 1-arg function
bar(int x, {int y}) {...}
Function bar1=bar.bind(y:0); // returns 1-arg function
class A {
   A(int x, {int y}) {...};
}
Function a1 = A.bind(); // returns 2-arg function with the same parameters as constructor
Function a2 = A.bind(y: 0); // partial application
```

This mechanism opens new possibilities for writing Flutter literals- see [this example](https://github.com/flutter/flutter/issues/47793#issuecomment-570948537)

**Comment by RedHatter** [comment]
Isn't this the same functionality of [this proposal](https://github.com/gbracha/generalizedTearOffs/blob/master/proposal.md) that was [aproved](https://news.dartlang.org/2015/06/null-aware-operators-and-generalized.html) back in 2015?

**Comment by eernstg** [comment]
It is similar, but the generalized tear-offs as described in said proposal are not supported in Dart today (not in the specification, not in the implementation).

**Comment by fzyzcjy** [comment]
Any updates after a year? This question may be related: https://stackoverflow.com/questions/67534998/getter-setter-method-passed-as-a-pseudo-function-pointer-in-dart?noredirect=1#comment119380290_67534998

**Comment by fzyzcjy** [comment]
@tatumizer Hi is it implemented? (I see it closed) thanks

**Comment by tatumizer** [comment]
I see zero chance that it will ever be implemented.
Closed to unclutter the issue tracker.

**Comment by fzyzcjy** [comment]
@tatumizer :(

**Comment by micimize** [comment]
@tatumizer can you clarify/expand on that some? For instance, do you mean:
1. A uniform tear-off approach will never be implemented but each kind of tear-off may be taken turn (e.g. now we have `Foo.new`, we may eventually have some equivalent to `Foo.(set bar)`).
2. Tear-offs for operators, getters, and/or setters will never be implemented.

If the latter, could we have some insight into the discussion that led to that decision?

**Comment by tatumizer** [comment]
I'm not part of dart team. Not even close :-)
I opened the issue, it got no traction - so I closed it.
You can reopen it, if you wish, or resubmit with a different proposal, or something.
