### ISSUE TITLE
Never available in opted out code; hide it?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#697]
The following program is accepted by `dartanalyzer` and `dartanalyzer --enable-experiment=no-non-nullable` (note: it is _disabling_ nnbd):

```dart
main() {
  dynamic d = 42;
  Never n = d;
}
```

The nnbd spec does not make it entirely explicit how to treat identifier `Never` (when it is not just the name of a regular user-written declaration). It [says](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#legacy-libraries):

> Static checking for a library which has not opted into this feature
> (a legacy library) is done using the semantics as of the last version
> of the language before this feature ships (or the last version to which
> it has opted in, if that is different)

This would imply that 'dart:core' does not declare and export `Never`, and a program like the above should simply treat `Never` as an undefined name.

This is mostly benign, but we have made it an error to use any syntactic construct which is nnbd specific, so allowing the use of `Never` (as a type exported by 'dart:core') in opted-out code (even if it is taken to mean `Null`) is misleading:

Consider a developer who starts porting a library _L_ to nnbd, adding `?` to some types etc. It would be really confusing if all the changes are ignored because _L_ is considered to be opted out, so all the changes appear to be working (and no further nnbd issues are reported, because _L_ isn't nnbd).

So I'd recommend that we _also_ make it an error to use `Never` in an opted out library.

Technically, this could be done by adding an implicit `hide Never` to every import into an opted-out library that would otherwise import the name `Never` denoting the declaration of the bottom type in 'dart:core'.

@lrhn agreed that hiding `Never` in this manner would give developers the most consistent experience. @leafpetersen, @munificent, WDYT?

**Comment by munificent** [comment]
If do we hide the name in legacy libraries, what happens if you do:

```dart
// opted_in.dart
export 'dart:core' show Never;

// legacy.dart
import 'opted_in.dart' as wat;

main() {
  wat.Never n; // ???
}
```

**Comment by leafpetersen** [comment]
I had intended that `Never` was simply not available to opted out libraries, since otherwise they could in principle ship packages that break on older versions of dart.  Bob's example doesn't worry me with respect to that - the fact that legacy.dart gets `Never` via an opted in library guarantees that any version of dart that can compile the package will be sufficiently new.

cc @stereotype441

**Comment by eernstg** [comment]
`import 'opted_in.dart' as wat;` would be well-defined if we define an import in an opted-out library to implicitly have a `hide Never` whenever that name would otherwise have imported the name `Never` as a name of the bottom type. It doesn't matter where the hide clause occurs in the list of hides/shows. I think this will do what we want, also in that case.

With non-function type aliases we could also import `Never` under a different name (with `typedef Foo = Never;` in an opted-in library that we import into an opted-out library), but I think that's a marginal case and non-function type aliases won't be released a lot earlier than nnbd, so I'd recommend that we ignore this.

**Comment by lrhn** [comment]
The `dart:core` library exports `Never` as a type, both in legacy and null-safe libraries.
Writing `Never` in a legacy library means `Never*` as usual, which is a subtype and supertype of both `Never` and `Null`/`Never?`.
