### ISSUE TITLE
Conditionals inside nested expressions

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/language#70]
Flutter code contains UI descriptions that are naturally ordered, with a set of arguments typically specified in the rough order they appear on the screen, e.g.:

```dart
  Widget buildBody() {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        Text('Text 1'),
        Text('Text 2'),
        Text('Text 3'),
      ],
    );
  }
```

However, when some of these elements need to be conditionally shown, the developer is forced to restructure the method "backwards"; with the conditional code first, and then the code for what surrounds the conditional code:

```dart
  Widget buildBody() {
    List<Widget> children;
    children.add(Text('Text 1'));
    if (someCondition == true) {
      children.add(Text('Text 2'));
    }
    children.add(Text('Text 3'));

    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: children,
    );
  }
``` 

The present issue requests support for some way of writing conditional code "as part of the statements".

**Comment by mdebbar** [comment]
@mit-mit you might find the `ui-as-code` project interesting. It covers several issues like this one. See https://github.com/munificent/ui-as-code/blob/master/Motivation.md#p1-conditionally-omitting-content.

cc @munificent

**Comment by mit-mit** [comment]
Yes, I'm very aware of that effort. This issue more formally tracks one of the parts from it.

**Comment by munificent** [comment]
Do we need both this issue and #62? They seem like duplicates.

**Comment by munificent** [comment]
I guess we can close this now that we have collection-if. :)
