### ISSUE TITLE
[Extension Methods] Extensions on Object not applying to dynamic

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/language#708]
The following extension method works on typed objects, but not on dynamic objects.

```dart
main() {
  int a;
  print(a.isNull); // True.
  int b = 1;
  print(b.isNull); // False.
  var c = 1;
  print(c.isNull); // False.
  var d;
  print(d.isNull); // Error.
  dynamic e;
  print(e.isNull); // Error.
  dynamic f = 1;
  print(f.isNull); // Error.
}

extension BasicsIterable on Object {
  bool get isNull => this.runtimeType == Null;
}
```

I would expect none of the above examples to throw an error.

**Comment by natebosch** [comment]
Your example does not have any variables of type `Null`. The extension would apply with a variable defined as `Null g;`. All of the examples you gave with an error have a static type of `dynamic`.

I _think_ it's intended that a static `dynamic` has no access to extensions.

**Comment by munificent** [comment]
> I _think_ it's intended that a static `dynamic` has no access to extensions.

That's correct. They are *static* extension methods. The intent is that they are purely syntactic sugar for a completely statically-resolved function invocation.

**Comment by tatumizer** [comment]
Nitpick: compiler allows extensions on `dynamic`:
```
main() {
  print(null.isNull); // true
  print(1.isNull); // false
  print((1 as dynamic).isNull); // runtime error
}

extension on dynamic {
  bool get isNull => this as dynamic == null;
}
```

This program shouldn't compile IMO, otherwise it's hard to explain why `dynamic` does not match `dynamic`.

Compiler also allows extensions on `void`  - not sure whether this is intentional
```
main() {
  print(null.isNull); // true.
  print(1.isNull); // false
}

extension on void {
  bool get isNull => this as dynamic == null;
}
```

**Comment by eernstg** [comment]
> Nitpick: compiler allows extensions on `dynamic`

Cf. #716, also for `void`.

> hard to explain why `dynamic` does not match `dynamic`.

No, the point is that we never ask whether `dynamic` matches `dynamic` (which it does, e.g., when a receiver of type `List<dynamic>` is considered for an extension `on List<dynamic>`), we just note that _every_ member access is an instance member access on a receiver of type `dynamic`, so we never proceed to even consider whether it could be an extension member access.
