### ISSUE TITLE
.isNotNull  AND .isNotNullOrEmpty

### ISSUE THREAD

**Issue by jamiethain** [dart-lang/language#714]
I write a significant amount of Dart Code that form wrappers around other code including but not limited to Column's and other properties. 

null to me is a special condition when you have the control in some form of state where your not modifying the variable or property. You intend it to be null, however there is also therefore a considerable amount of null and empty checking at the dart level. 

Class 
  method  ({String someParamater, ClassMech someClassMech)

InLineFunction 
  function ({String someParamater, ClassMech someClassMech)
  
Either way even when setting class variables I tend to do a lot of this type of code, 
  if (someParameter != null && someParameter.isNotEmpty ) 
     {
         someParameter = someParameterManipulation(someParameter); 
         someList.add(someParameter) 
     }

Maybe there is a shortcut I don't already understand but this could be cut to 

 if (someParameter.isNotNullOrEmpty) 
      someList.add(someParameterManipulation(someParameter) 

Of course it would be added in Dart Core. 

Or is there a way I can add it just for me. 

Describe the new syntax or language feature you'd like to see incorporated into
Dart. Ideally you can relate this to a `request` issue filed separately.

**Comment by tatumizer** [comment]
You can do it with the upcoming extension methods, but it would be a bit type-unsafe (probably tolerable)
```
extension MyExt<T> on T {
  bool get isEmptyOrNull {
    if (this == null) {
      return true;
    } else if (this is String) {
      return (this as String).isEmpty;  // compiler can't figure out the type for some reason
    } else {
      throw CastError();
    }
  }
  bool get isNotEmptyOrNull => !this.isEmptyOrNull; 
}
main() {
  print(null.isEmptyOrNull);     // true
  print(null.isNotEmptyOrNull);  // false
  print("".isEmptyOrNull);       // true
  print("".isNotEmptyOrNull);    // false
  print("x".isEmptyOrNull);      // false
  print("x".isNotEmptyOrNull);   // true
  print(5.isEmptyOrNull);        // Uncaught Error: Instance of 'CastError'
  print(5.isNotEmptyOrNull);     // Uncaught Error: Instance of 'CastError'
}
```

**Comment by jamiethain** [comment]
Ok that will be great -- I would like it for every type though.

**Comment by lrhn** [comment]
@tatumizer 
> You have to write `extension MyExt<T> on T` rather than more obvious `extension MyExt on Object` because the latter will (probably) stop working after NNBD release.

You can write:
```dart
extension MyExt on dynamic { ... }
```
now and it will keep working post-NNBD. Just avoid using that `this` is `dynamic` to do dynamic invocations - promoting to `String` like you do is fine.

**Comment by lrhn** [comment]
A different approach is:
```dart
extension EmptyString on String {
  bool get isNullOrEmpty => this == null || this.isEmpty;
}
extension EmptyIterable on Iterable {
  bool get isNullOrEmpty => this == null || this.isEmpty;
}
extension EmptyMap on Map {
  bool get isNullOrEmpty => this == null || this.isEmpty;
}
```
That covers all strings, iterables and maps, which are all the types (IIRC) which have a synchronous `isNotEmpty` in the platform libraries.

**Comment by tatumizer** [comment]
@lrhn: Will `extension EmptyString on String` be applicable to `String?` and `Null` types after NNBD?

**Comment by munificent** [comment]
> Will `extension EmptyString on String` be applicable to `String?` and `Null` types after NNBD?

No, but this extension would apply:

```dart
extension EmptyString on String? {
  bool get isNullOrEmpty => this == null || this.isEmpty;
}
```

**Comment by lrhn** [comment]
As Bob says, extension declarations need to be migrated to NNBD like all other code.

In the interregnum between non-NNBD and NNBD, non-migrated code will still be usable from migrated code, and a non-migrated `extension Foo on String` will apply to `String?` expressions in a migrated library.

**Comment by lrhn** [comment]
Extension methods solve this problem, now with null safety as well, so I'm closing the issue.

**Comment by OtabekgithubJava** [comment]
This article is nothing but a wast of time
