### ISSUE TITLE
Warnings for redundant `?.` should not apply to legacy receivers

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#715]
The nnbd specification says that

> It is a warning to use a null aware operator (`?.`, `?..`, `??`, `??=`, or `...?`)
> on a non-nullable value.

However, a legacy value (e.g., a result returned from an invocation of a function/method declared in an opted-out library) will have a type of the form `I*` where `I` is an interface type, and that's a non-nullable type unless `I` is `Null`.

It is perfectly reasonable for a developer to handle a potential null by using `e?.m()` rather than `e.m()` in the case where `e` has a legacy type. So we should probably change this to say that the warning does not apply to legacy typed receivers.

I believe that there are no concepts covering exactly this set of types, but we could replace 'on a non-nullable value' by something like 'on a receiver (`?.`, `?..`), operand (`...?`), or left hand side (`??`, `??=`) whose static type `T` is non-nullable, unless `T` is of the form `S*`'.

Also, we might want to include `e1?.[e2]` and `e1?.[e2] = e3` (and all the `op=`) among the cases for including the warning, and excepting legacy receivers.

@leafpetersen, @lrhn, @munificent, WDYT?

**Comment by lrhn** [comment]
It should definitely not be disallowed.

Do we define `int*` as non-nullable? If so, I guess our problem is that we intended that definition as permissive; `int*` can be used where a non-nullable type is required *and* where a nullable type is required.

So, the text should probably say:

> It is a warning to use a null aware operator (?., ?.., ??, ??=, or ...?)
> unless it is on a potentially nullable value.

Then `int*`, which is *both* nullable and non-nullable, is allowed.

So, I believe this is just an accident of phrasing.

**Comment by eernstg** [comment]
`int*` is non-nullable (we have `int* <: Object`), which is useful because it allows for member accesses on receivers whose static type is legacy. But `int*` is not nullable (because `int* <: Object` prevents that). This means that it is 'potentially non-nullable', but it isn't 'potentially nullable', because that means 'not non-nullable'.

But _every_ non-nullable type is potentially non-nullable, so we can't use that to tease out just the legacy types. (Assume that `T` non-nullable, that is: `T <: Object`; to see that `T` is potentially non-nullable, that is, `T` is not nullable: assume that `T` _is_ nullable, then it is false that `T <: Object`: contradiction).

So we will probably have to say 'unless `T` is of the form `S*` for some `S`'.

**Comment by leafpetersen** [comment]
Good catch.  I think we want something like unless "T <: Object" and not `Null <: T`.

**Comment by eernstg** [comment]
Of course. ;-)

**Comment by leafpetersen** [comment]
Fix out for review [here](https://github.com/dart-lang/language/pull/721).

**Comment by leafpetersen** [comment]
Fix for this has landed.

**Comment by leafpetersen** [comment]
cc @scheglov @johnniwinther @stefantsov on this change.
