### ISSUE TITLE
Use the context type for the type of conditional expressions instead of computing a least upper bound.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#732]
Computing a least upper bound for the arms of a conditional expression when we have a context type can cause unnecessary implicit downcasts, which become errors in the NNBD release.  We should instead use the context type as the type of the conditional expression.  Example:

```dart
class I1 {}
class I2 {}
class A implements I1, I2 {}
class B implements I1, I2 {}

void test(bool p) {
  A a = new A();
  B b = new B();
  // The LUB of A and B is Object, so this induces an implicit downcast.  
  I1 x = p ? a : b;
}
```

**Comment by eernstg** [comment]
There may be corner cases of interest:
```dart
dynamic x = (myBool ? "Hello" : true)..isEven; // OK.
```

**Comment by lrhn** [comment]
That case doesn't worry me. You asked for `dynamic`, and you got it.

I'm all for using the context type on each branch, and giving errors individually if they fail to satisfy their context type. It won't save bad code, but it will allow `double x = test ? someValue : 0;` to work.

**Comment by eernstg** [comment]
> You asked for `dynamic`, and you got it.

Sure, but I think I'd expect a compile-time error (especially for an nnbd setting where implicit downcasts are gone) for this:

```dart
// Far, far away, in some library that I haven't looked at.
void foo(x) {...}

// My code. Innocent. ;-)
main() {
  foo((myBool ? "Hello" : true)..isEven);
}
```

Wouldn't it be a surprise that the subexpression `myBool ? "Hello" : true` is suddenly unchecked, just because of the parameter type of `foo`?

**Comment by leafpetersen** [comment]
We will look into doing this, with either a special case for `dynamic`, or simply by treating a context type of `dynamic` as `?`.

**Comment by lrhn** [comment]
Using `?` for `dynamic` as context type is likely a *good* idea in general. The way `dynamic` is generally used is as "I can't write a type here", and using that as a manifest type is giving it too much importance.

**Comment by leafpetersen** [comment]
Not planned.
