### ISSUE TITLE
super.call sugar?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#734]
Thanks to @sgrekhov for noticing this! Consider the following program:

```dart
class A {
  String call() => "A.call!";
}

class B extends A {
  String foo() => super();
}

main() => print(B().foo());
```

The analyzer accepts the program, but the CFE (`dart`) rejects it, both from commit bbd850eac875a065d2dfcbb53c60cd7b61a86dc1:

```
n013.dart:6:19: Error: Can't use 'super' as an expression.
To delegate a constructor to a super constructor, put the super call as an initializer.
  String foo() => super();
                  ^
```

Do we expect an expression of the form `super(...)` to be treated as if it were `super.call(...)`? That does seem to be a consistent interpretation of the treatment of function invocations, but the specification does not justify that the desugaring of `f(...)` to `f.call(...)` is applicable when `f` is the reserved word `super` (many cases are spelled out, but this one isn't there).

So do we want to add support for this case to the CFE, or should the analyzer start rejecting it?

@leafpetersen, @munificent, @lrhn, WDYT?

**Comment by leafpetersen** [comment]
I vote the latter (make it uniformly an error).  I'm surprised it's not a parse error, actually.

**Comment by lrhn** [comment]
It's not currently in the grammar. I'd add it, for parity with `super[x]`, but probably not now.

**Comment by eernstg** [comment]
Closing: We can revise the language later on if desired. But for now the tools are following the spec, so we have a consistent situation, and no strong desire to change it.
