### ISSUE TITLE
Async can be used as override for void methods

### ISSUE THREAD

**Issue by ayporos** [dart-lang/language#735]
Currently it's possible to override a void method by providing an `Future<void> async` implementation of it. In my opinion it can lead to false assumptions and 'unexpected' behaviour.
Example:

```dart
abstract class Foo {
  void test();
}

class Bar extends Foo {
  @override
  void test() {
    print('Bar');
  }
}

class Baz extends Foo {
  @override
  Future<void> test() async {
    return Future.delayed(Duration(seconds: 3), () => print('Baz'));
  }
}

void main() {
  Foo instance = Bar();
  instance.test();
  
  instance = Baz();
  instance.test();
}
```

**Comment by rrousselGit** [comment]
That sounds logical to me.

To begin with, we can write:

```dart
void example() async {
  await something;
}
```

If you don't want that, instead of `void` you can use `Null`.

```dart
abstract class Foo {
  Null test();
}

class Bar extends Foo {
  @override
  Null test() {
    print('Bar');
  }
}

class Baz extends Foo {
  @override
  Null test() async { /// won't compile
    return Future.delayed(Duration(seconds: 3), () => print('Baz'));
  }
}
```

**Comment by ayporos** [comment]
As a user of 'interface' (Foo) how can I know if it's async or not to use `await`?

**Comment by rrousselGit** [comment]
You can do:

```dart
abstract class Foo {
  void test();
}

void main() {
  Foo foo;

  final dynamic res = foo.test();

  if (res is Future) {
    await res;
  }
}
```

**Comment by ayporos** [comment]
Are you suggesting to wrap every call inside something like:

**Comment by eernstg** [comment]
@ayporos wrote:
> Currently it's possible to override a void method by providing an
> `Future<void> async` implementation of it.

This is true. The type `void` in Dart is a top type (so _every_ object can be typed as `void`), but it is associated with static constraints ensuring that such values are generally not used. You can force it (say, `myVoidExpression as dynamic` will allow you to use the value of `myVoidExpression`), and there is nothing wrong with such objects (they don't violate the language invariants), but the use of the type `void` is an indicator from developer to developer that it is a mistake to believe that this object is meaningful.

So when you override a method `m` returning `void` by a method returning some other type, it should be interpreted as something like "in the supertype you should ignore the returned result, but different subtypes can return something useful". This makes sense if it is OK to call `m` and ignore the returned result on a receiver whose static type is the supertype, but if the receiver has one of the subtypes then you can call `m` and use the return value correctly and safely.

This clashes with a special property of `Future`: Ignoring this particular kind of return value is quite likely to be a bug! Cf. https://dart-lang.github.io/linter/lints/unawaited_futures.html.

So it's a really bad idea to override return type `void` by return type `Future<void>` (or `Future<T>` for any `T`).

However, imperative languages typically allow the result of an expression evaluation to be discarded (e.g., `printf("%d", 42)` in C returns an `int`; but you can ignore the returned value, and the compiler won't complain). This is an extremely common situation, and it's not likely to be helpful to start flagging locations where values are discarded.

So we can basically only catch the situation where a future is discarded when it has a type where it is immediately known that it is a future. For instance, it won't apply to an expression of type `X` where `X` is a type variable:

```dart
import 'dart:async';

void foo<X>(X x) {}

Future<void> main() async {
  foo(Future.value(1));
}
```

In this situation the future is discarded, but local analysis of `foo` doesn't reveal that the discarded value could be a future, so there is no warning/lint in `foo` itself, and from `main` it looks just like the future is not being discarded.

I believe there is nothing to fix in the language here, but a lint against overriding return type `void` by return type `Future<T>` for any `T` would be helpful.

**Comment by ayporos** [comment]
Thank you for an explanation. 
Actually I read [this article](https://medium.com/dartlang/future-void-vs-future-null-whats-the-difference-84a42d616e7d) today and got an idea that every object can be typed to void because it's save (no way anyone would be able to use it anyway).
I'm new to the language so code I provided in the first post felt like breaking the contract and leaking implementation details in case of `Baz`. 
But linting sounds like a good solution. Should I close this issue then?

**Comment by eernstg** [comment]
Ah, I didn't see the question

> Should I close this issue then?

I think it's fine to close it, so I'll do that now.
