### ISSUE TITLE
Make StackTrace non-nullable in async code.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#747]
The current migration of async code (`Future`, `Stream`, `Completer`, `StreamController`, `Zone.handleUncaughtError`, `Zone.errorCallback` and similar) generally have to treat `StackTrace` as *optional* (aka. nullable).

That's *highly annoying* when you write async code manually (you keep forgetting the `?` on `StackTrace`), and confusing when you do a `catch (e, s)` in `async` code and end up with a `null` stack trace.
It has been an issue for migrating code already, and the fact that an `async` `catch(e,s)` can end up with a `null` `s` is suprising, and possibly not well supported. It means that the static type of that `s` is `StackTrace?`, where a synchronous catch would have `StackTrace`, which is inconsistent and error-prone. Someone capturing `StackTraces` would likely get hit by this.

*I recommend* that we change this design and make `StackTrace` non-nullable when *reading* from a future/stream. That means all the `onError`/`catchError`/async `try`/`catch` functionality will always see *some* stack trace. 

You can still complete a future without specifying a stack trace (the parameter is optional), but if you do so, a stack trace will be supplied for you (perhaps the `error.stackTrace` if the error object is an `Error`, or `StackTrace.current` or some default `StackTrace.empty` if not).

This is a breaking change in the case where someone creates an async error with no stack trace, and depends on there being no stack trace where it's caught. That's hopefully not a common situation.

**Comment by eernstg** [comment]
> _I recommend_ that we change this design and make `StackTrace` non-nullable
> when reading from a future/stream.

Agreed, assuming that this will not imply any significant performance overhead.

**Comment by lrhn** [comment]
I do not expect a any performance overhead. The difference is that where users _input_ a null `StackTrace`, we replace it with a default `StackTrace` (`StackTrace.empty` defined as `static const StackTrace empty = _StringStackTrace("");`, and we can totally bike-shed the string).

It ensures that the remaining async error processing can assume that there are no `null` stack traces, and users can write their error handlers as `(Object error, StackTrace stack) { ... }` without getting an error because it doens't accept a `null` stack.

**Comment by leafpetersen** [comment]
LGTM.

**Comment by leafpetersen** [comment]
This has landed.  Closing.
