### ISSUE TITLE
Grammar seems to require `;` to terminate function expressions

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#752]
`specification/dartLangSpec.tex` contains the following grammar declarations:
```
<primary> ::= <thisExpression>
  \alt \SUPER{} <unconditionalAssignableSelector>
  \alt <functionExpression>
  \alt <literal>
  \alt <identifier>
  \alt <newExpression>
  \alt <constObjectExpression>
  \alt `(' <expression> `)'
<functionExpression> ::= <formalParameterPart> <functionBody>
<functionBody> ::= \ASYNC{}? `=>' <expression> `;'
  \alt (\ASYNC{} | \ASYNC `*' | \SYNC `*')? <block>
```
If I'm understanding this correctly, this means that a `=>` style function expression should be terminated with a `;`, e.g.:
```dart
var x = y.map((x) => x + 1;);
```
But the extra `;` shouldn't be there.  It should be:
```dart
var x = y.map((x) => x + 1);
```

**Comment by eernstg** [comment]
I can't find exactly those grammar rules, could it be an older version of dartLangSpec.tex? Here's what I can see:

```
<functionExpression> ::= <formalParameterPart> <functionExpressionBody>

<functionExpressionBody> ::= \ASYNC? `=>' <expression>
  \alt (\ASYNC{} `*'? | \SYNC{} `*')? <block>
```

**Comment by stereotype441** [comment]
Thanks, @eernstg.  I see it now--I did indeed have an older version of dartLangSpec.tex checked out.  Sorry for the noise!
