### ISSUE TITLE
Proposal: adding value to 'break' statement

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#762]
The idea is to modernize `break` statement in every construct where it's currently defined by adding a new parameter `value`. The general form of break statement becomes: `break label->value;` In this extended form, the keyword `break` can be omitted (it becomes redundant when `->` is present), so we can write it as `label->value`, which further degenerates into `->value` if the label is omitted.

Now every construct that currently supports `break` might be used as an expression:
```
final String numericString =
   switch (integer) {  
      case 1 : -> "uno";
      case 2 : print("debug print"); ->"dos";
      case 3 : -> "tres";
      default :-> "N/A";
   };
var x = for (int i=0; i<10; i++) {  
   if (someCondition(i)) -> i;
} 
if (x!=null) { // if the search is not successful, x is null
   // do something
}
// same for "while" block
```

It would probably make sense to also add support for "when" block (as a statement and  as an expression):
```
var x = ...;
var y = when {
   case x <= 5: -> "a";
   case x > 5 && x < 10: -> "b"; 
   case x >= 10 && x < 20: -> "c"
   default: ->"d";
}
```

NOTE: the natural idea would be to extend the proposed syntax to block statement `{...}` thus turning it into block-expression, but it doesn't quite work out: block supports `break` only in a form `break label`. However, the following syntax is not valid in dart:
`var x=label: {statements... break label; ...}` 

Anyway, block-expressions won't add too much power to the language: if anonymous methods (#260) are implemented, then we can always find a suitable receiver to achieve the same effect via anonymous method call `obj.{...}` that returns the result using a standard `return` statement.

**Comment by lrhn** [comment]
This would fit better into a setting where *all* statements have a value and can be used as expressions.
Then `var x = label: { for (var something in somewhat) if (test) label -> value;};` could work.

We are a little hampered by labels not being in the same namespace as everything else. Otherwise we could just use `break label value` with both label and value being optional.

**Comment by tatumizer** [comment]
>... we could just use break label value with both label and value being optional.

I think it's a good idea. No special operators. Just `break value` - it will "rhyme" with "return value".
In case of a name conflict between a label and a variable - error. How many existing programs will be broken? My wild guess is: about zero. Statements `break label` are very rare. It would be too bad to discard a good feature because of imaginary conflicts that never occur in practice.

As an aside: it came as a surprise to me that we can break from "if" statement if you label it:
```
label:
if (cond) {
   if (cond1) break label;
   print("hello");
}
```

**Comment by tatumizer** [comment]
Further, `break value` can be allowed only in contexts where this value gets assigned (or passed as a parameter), e.g.
```
for (int i=0; i<10; i++) if (cond) break i; // ERROR
var x = for (int i=0; i<10; i++) if (cond) break i; // OK
```
With this rule in place, no existing program will be broken.
(We already have precedents: `{5};` is an error, but `var x = {5};` is not)

**Comment by tatumizer** [comment]
I see no chance for it to be ever implemented.
I closed it to unclutter the issue tracker.
