### ISSUE TITLE
“reveal”, a private member access proposal

### ISSUE THREAD

**Issue by icatalud** [dart-lang/language#766]
The `reveal` keyword can only be used over classes and packages. It reveals the private scope of them in the local scope where it is used. Revealing a package does not reveal the private members of the classes.
When reveal is used in a class, it's private var context superimposes over the default scope.

**Use cases:** Apps that tweak some Flutter internals or generally accessing some private fields that where not thought to be useful at the moment of creation of the library.
**Requirement:** A fixed version of the revealed library in the pubspec.

```dart
Library lib;

int _counter = 0;
class _Foo() {
  int _id = _counter++;
}
///
import .... as lib;
reveal lib;

var count = lib._counter; 

class A extends lib._Foo {
  final _id = 'id';
  int id() {
    print(_id);       // 'id'
    reveal lib._Foo;     // places _Foo var context on top
    return _id++;
  }

  String strId() {
    return _id;
  }
}

class B extends lib._Foo {
  reveal lib._PrivateClass; 
  String _id;      // invalid
}
```

**Comment by tatumizer** [comment]
What if you write a script `reveal.sh libraryName identifier`, which goes into the library subdirectory under `packages` and finds and replaces all occurrences of the `_counter` (whole word only) to, say, `revealed_counter` thus making the variable public.
The script doesn't need to really parse anything, just do a text replacement - if the library has two or more `_counter` vars, the replacement won't hurt (what worked before, will work after).

Maybe I'm missing something, but if the trick works, then it's much easier (IMO) to get what you want this way, no?
