### ISSUE TITLE
Switch null warning too aggressive?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#792]
The nnbd specification [states](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings) that it is a warning

> ... if a switch over a nullable type does not handle null either explicitly or via a default.

However, this is surprisingly strict. Completeness is generally not checked unless the type of the expression that we're switching over is an `enum`, but just for null we now require that it is covered:

```dart
// Opted in.

void main() {
  int i = 42;
  switch (i) {
    case 41: print("Match!");
  }
}
```

This is fine. But we get a warning if we change `int` to `int?`. Why would we complain that there is no case for null, given that it is not a warning that there is no case for 42, and several other `int` values?

We could restrict the rule as follows: 'it is a warning if a switch over a nullable _enum_ type does not handle null either explicitly or via a default'. In that case it seems very natural.

You could also ask whether the warning should be governed by a slightly different criterion with respect to the possibility that the value can be null: If we use 'nullable' then it fails to catch some uncertain cases covered by 'potentially nullable'.

Of course a 'potentially nullable enum type' may be a unicorn (`X extends MyEnum?` isn't terribly useful), but if that's the most precise way to say what we want, we could say it.

We could then extend the other cases about enum types to include `E` as well as `E?` and `E*` where `E` is an enum type.

We could also say that a legacy typed expression may yield null, so the warning should be emitted also when we switch over an expression of type, say, `int*`. An argument _against_ that is that we allow member accesses with legacy typed receivers, so the underlying rationale could be "you are touching legacy land, so you may have unexpected nulls", and that would motivate both the member access and the switch-that-ignores-null. So I'd suggest that we use 'potentially nullable' and let the legacy types ignore the null.

@munificent, @leafpetersen, @lrhn, WDYT?

**Comment by lrhn** [comment]
I'm not particularly fond of any "must handle case" rule, not even for enums.

It effectively means you have to add an empty `default:` clause if you *don't* want to handle the values. An empty default clause looks like an error, so you'll probably have to write a comment too:
```dart
switch (day) {  // enum switch.
  case Day.monday: return manic();
  case Day.sunday: return bloody();
  default: 
    // Avoid incomplete enum match warning.
}
```
I think that any rule that requires you to add comments to explain your workaround to get out of it, is inherently flawed. I'd like it to be opt-in, not on by default.

That also extends to a "must handle null" rule, and as Erik points out, that one doesn't even try to be complete to begin with. No switch over integers can ever be complete, so why single out `null` as an unhandled case. If there is no `default` case, we're going to fall through no matter what.

I can see that it's an easy case to *forget* (well, as easy as many other things), but either that doesn't matter, or the code below will see the same nullable type and deal with it.

Also, it's a warning, and I don't want warnings in the language by default. Either make it an error, or let the user be in charge (then they can opt in to warnings in the analyzer, but they can also choose not to). 


But, assuming that we keep the current rule for enums, we could expand *just that* that to nullable enums too. That would mean that if the type of the switch expression is `T?` where `T` is an enum type, then the cases must cover all enum values *and* null.
I guess that's not much worse than what we already do for enums. I'm not sure it's worth it, but I'm also not opposed to that.
The more I think about the general "must handle null" rule, the more I *am* against that.

**Comment by eernstg** [comment]
Agreed, @lrhn!

I think, though, that the default case in the switch can be written and have a comment like `// Nothing to do in remaining cases.`, maybe ending in `because <some-specific-reason>`, and that would be just fine with me, given that we're only talking about enums, with or without null.

We might want to check that we treat `bool` consistently (because it has a finite extension as well, like an enum). But we don't: We do not support an "evenmoreelse" case for null, we just make it an error for the condition of an `if` statement to be potentially nullable; and we do not complain when an `if` statement has no `else` branch.

Still, if someone really wants to use a three-way logical domain based on `bool?`, we could say that this is essentially an enum switch, so there's a warning unless there is a matching case for each of true, false, and null.

Similarly for `Null` itself: There must be a case. ;-)

**Comment by leafpetersen** [comment]
I'm fine with restricting the exhaustiveness error to nullable enums.  @munificent thoughts here?

**Comment by leafpetersen** [comment]
I've made this change.

**Comment by sgrekhov** [comment]
@leafpetersen where can I see the change?

**Comment by eernstg** [comment]
The change occurred [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-and-warnings).
