### ISSUE TITLE
Instantiate to bounds update for NNBD

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#804]
I believe we need to modify the i2b algorithm for NNBD. Specifically, we should probably change this to use `Never` for the bottom type instead of `Null`, since `Null` is not valid in all cases.  @eernstg do you agree that this is the correct change here?

cc @scheglov @stefantsov

**Comment by lrhn** [comment]
It seems reasonable. We use `Null` in contravariant positions only because it is the maximally permissive type there, and with NNBD, the maximally permissive type is `Never`.

**Comment by eernstg** [comment]
Yes, I'd definitely expect that `Null` should be replaced by `Never` whenever the i2b rules intend to use the bottom type.

I see only two occurrences of `Null` in section 'Instantiation to bound' (including subsections, up to 'Metadata'), and they're both intended to denote the bottom type. So changing those occurrences to `Never` would match the intentions as well as avoid the errors.

We have two occurrences of `dynamic` (in normative text, plus some more in examples/commentary), and they are intended to denote a top type, which is still correct.

So unless we wish to change that top type (say, to `Object?`), I believe that the rest of the algorithm should work.

I can't immediately think of other things that need to be adjusted. For instance, `List?` should be subject to instantiation to bound yielding `List<dynamic>?`, but this would presumably "just work": `List?` is a composite term where `List` is a raw type which is subject to i2b (using the current definition of raw types), and `?` is just an operator on that type.

**Comment by leafpetersen** [comment]
This has been specified.
