### ISSUE TITLE
Async programming await does not return future immediately

### ISSUE THREAD

**Issue by PandaGeek1024** [dart-lang/language#808]
From the dart tour, I have alway rely async programming on this paragraph
`Although an async function might perform time-consuming operations, it doesn’t wait for those operations. Instead, the async function executes only until it encounters its first await expression (details). Then it returns a Future object, resuming execution only after the await expression completes.`

My understanding of this paragraph means when the async function reach await, it should return a future to upper non-async function immediately. which put into example as below:

```  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    runTest();
    print("done");
  }

  Future<void> runTest() async {
    await runTest1();
    print("runTest");
  }
  Future<void> runTest1() async {
    await runTest2();
    print("runTest1");
  }

  Future<void> runTest2() async {
    print("runTest2");
  }
```
**Expected results:** 
It should print
```
done
runTest2
runTest1
runTest
```

**Actual results:**
```
runTest2
done
runTest1
runTest
```

when I learn flutter at the beginning(a year ago?), I normally see things go with expected result, but now Im seeing the actual result now. The async function did not return a future immediately and went straight to the end of the async chain. Am I missing something or maybe the await behaviour has already changed?

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G2022, locale en-NZ)
    • Flutter version 1.12.13+hotfix.7 at /Users/jayhuang/Development/flutter/sdk
    • Framework revision 9f5ff2306b (4 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jayhuang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/jayhuang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • MotoG3            • ZY2222HDH5                               • android-arm • Android 6.0 (API 23)
    • Pengfei's iPhone  • 2256178a00be70a423115c0eeb12af7720c3f928 • ios         • iOS 12.3.1
    • iPhone 11 Pro Max • F8D17509-18C5-4B58-83DD-5A16B787C17A     • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

```

**Comment by lrhn** [comment]
The observed behavior is correct.
The description you quote is ambiguous (or perhaps even misleading) in that it says that the `async`  function stops when it reaches an `await` expression. That's not entirely correct. 

It stops when it executes the `await` of an `await` expression.

That means that for:
```dart
Future<void> runTest() async {
    await runTest1();
    print("runTest");
  }
```
an invocation actually performs the call to `runTest1()` before stopping. Which means that `runTest1` also calls `runtTest2` immediately, and then `runTest2` prints "runTest2" and returns a future. *Then* `runTest1` blocks awaiting that future and returns its own future, and then `runTest` blocks on that and returns its own future.
So, the print order I would expect is: `runTest2`, `done`, `runTest1`, `runTest`, which is also what you see.

**Comment by PandaGeek1024** [comment]
@lrhn Thank you for your clear explanation. But there is one question come up in my head that how do you write an async function to perform heavy tasks then? For example, print 10 thousand lines asynchronously. 
It is confusing because it wouldn't return until await, but when there is await it will loop through until it finds future. It seems like there is not a simple way to do that.

**Comment by lrhn** [comment]
If you want to perform a long-running computation without blocking everybody else, you'll need to insert awaits into the task. 

Dart is *single-threaded*, so any long-running loop will block all other code from running. You have to allow the code to return to the event loop. One way to do that is to break the task into smaller chunks and insert an await between them, for example:
```dart
Future<Result> longRunningTask(int count) {
  var result = intialValue;
  for (int i = 0; i < count; i++) {
     result = computePart(i, result);
     await Future.delayed(Duration.zero);
  }          
  return result;
}
```
If each `computePart` is "not too long", then this inserts gaps between those parts that other code can use to run. If there was no `await` inside the loop, then the entire computation would complete before anyone else would get a chance to run.

**Comment by PandaGeek1024** [comment]
@Irhn thanks for the solution!
