### ISSUE TITLE
Treating the type Never as the type Null may be too aggressive.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#825]
The nnbd specification [specifies](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#legacy-libraries) that if _Li_ is an opted-in library imported by _Lo_ which is opted out, declarations in _Li_ are

> viewed by the legacy library [_Lo_] with nullability related features erased from their APIs

and this is supported by an itemized list including this bullet:

> The type `Never` is treated as the type `Null`

We have decided that 'dart:core' exports the type `Never`, which means that it is allowed for _Lo_ to use the name `Never` and have it resolved to the declaration in 'dart:core', but whenever that occurs, the syntax (which could be `Never` or `p.Never` where `p` is a prefix) will of course denote the type `Never*`, which implies that it is a subtype of `Never`.

I believe it could be useful to drop the bullet mentioned above. In particular, consider the following example:

```dart
// Opted-in library 'in.dart'.
class C<X extends Never> {}

// Opted-out library.
import 'in.dart';

void main() {
  C(); // Error!
}
```

If we treat `X extends Never` as `X extends Null` when viewed from the opted-out library then inference would turn the instance creation in `main` into `C<Null*>()`, but we cannot prove `Null* <: Never`, so the instantiation is an error.

We could write `C<Never>()`, meaning `C<Never*>()`, and in this case we can use the subtype rule [Left Legacy](https://github.com/dart-lang/language/blob/master/resources/type-system/subtyping.md#rules) and succeed.

I suspect that the rules would be more convenient if we remove that bullet and simply rely on the fact that a legacy library is allowed to refer to `Never`, and the usual treatment of types in a legacy library will suffice when applied to the outcome of type inference.

So WDYT @munificent, @lrhn, @leafpetersen, can we delete that sentence? Should we?

**Comment by eernstg** [comment]
Just found this [here](https://github.com/dart-lang/sdk/issues/39917#issuecomment-575430331):

> Let's just parse `Never` as `Never`, regardless of where it occurs.
> I see no benefit to doing otherwise.

which is at least compatible with my proposal above.

**Comment by eernstg** [comment]
Created #826 to do this, considering that it seems to have support already.

**Comment by leafpetersen** [comment]
> but we cannot prove `Null* <: Never`, so the instantiation is an error.

No it's not.  That subtyping holds in weak mode.  

The sentence referenced above is important - opted in inference may produce `Never` in places where it previously produced `Null`, and it's important that this not break opted out libraries.

**Comment by eernstg** [comment]
>> but we cannot prove `Null* <: Never`, ..

> That subtyping holds in weak mode

Ah yes, even for the bounds check we "treat `Never` as `Null`" when it is seen from a legacy library, so the check is actually `Null* <: Null`, and it succeeds.

(But I suspect that you mean 'as seen from a legacy library' rather than 'in weak mode'. I don't see any evidence for having different rules for subtyping during static analysis, depending on whether the program is going to be compiled for weak or strong mode execution.)

**Comment by leafpetersen** [comment]
> But I suspect that you mean 'as seen from a legacy library' rather than 'in weak mode'.

Yes, thanks.  Though it also applies to weak mode execution if the check was done dynamically.

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/sdk/issues/41804, here's an example where an error arises because each occurrence of `Never` that is located in a legacy library is treated as `Null`, but the required subtype relationship is `Null* <: Never` and not `LEGACY_SUBTYPE(...)` because it arises in a library with null-safety, namely 'test.dart':

```dart
// 'test_out_lib.dart'.
// @dart = 2.6

class A1<X> { X Function(X) get f => throw 1; }
class out_Never extends A1<Never> {}
```

```dart
// 'test.dart'.
import 'test_out_lib.dart';

class A2<X> { X Function(X) get f => throw 2; }
class B extends A2<Never> {}
class C extends B implements out_Never {}
```

So do we want to make it impossible for `out_Never` to be compatible with class `B` and `C`?
Of course, we could just tell the authors of `test.dart` to change `B` to use `A2<Null>`.

If we do not wish to take that path then we may still want to stop treating `Never` as `Null` in legacy libraries.

@leafpetersen, WDYT? And @lrhn and @munificent?

**Comment by eernstg** [comment]
FYI, status: The question asked in this issue was answered with "no". So the type `Never` is indeed treated as `Null` when that identifier is used in a legacy library and it resolves to the type declared in 'dart:core'.

This has been enshrined in the analyzer implementation as of https://dart-review.googlesource.com/c/sdk/+/149260, 'Instantiate Never as Null* in legacy libraries'.
