### ISSUE TITLE
Enforce assignability in yield/yield* for each element

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#829]
Cf. https://github.com/dart-lang/sdk/issues/40538: The current language specification relies on the `Stream`/`Iterable` type for type checks on `yield` statements. This means that with nnbd we will reject yielding an expression of type `dynamic` (because, say, `Iterable<dynamic>` isn't assignable to `Iterable<int>`, even though `dynamic` is assignable to `int`).

It seems reasonable to treat `yield e` in a `sync*` function with return type `Iterable<T>` in a way which is similar to `return e` in a regular (non-generator) function with return type `T`. But the latter will allow us to return a `dynamic` expression whereas the current language specification wording will make it an error to yield a `dynamic` expression.

This PR changes the language specification to rely on the element type rather than the type of the sequence for yield statements, such that the switch to nnbd will not cause this unintended error to arise.

With `yield*` it may seem justified to allow yielding an expression with static type `dynamic`, but reject an expression with static type `Iterable<dynamic>`/`Stream<dynamic>`, unless the declared return type is a supertype thereof. So we might not want to adjust the specification of `yield*` to rely on the element type.

However, we have made a different decision when it comes to `for-in` statements: They are specified to be desugared in a way that allows iteration over an `Iterable<dynamic>` resp. a `Stream<dynamic>`, in which case a cast will be applied for each element. Consistent with this, the analyzer allows the following:

```dart
void main() {
  Iterable<dynamic> ds = <dynamic>[1, 2, 3];
  for (int i in ds) print(i);
}
```

Similarly for `await for` and `Stream`: The dynamic check can be applied for each element. I think we should strive to keep `yield*` and `for-in` consistent.

This PR makes adjustments to the sections 'Yield' and 'Yield-Each' to get there.

@lrhn, @munificent, @leafpetersen, WDYT?

**Comment by lrhn** [comment]
I think our decision on `for`-`in` was correct. You are *iterating over the iterable*. If the iterable is an `Iterable<dynamic>` then you get a lot of `dynamic` values, and then you might downcast those if you want to.
I think `await for` should do the same thing and check for element assignability, not stream assignability.

For `yield`, it should definitely work like return. I think it already does, apart from an unrelated extra static type check.

I'm not so sure about `yield*`. It feels more like `addAll` than `forEach`, and I'd expect the type of the container to be checked. Maybe that's just me knowing that someone is eventually going to call `StreamController.addStream` and that will check the type of the stream, not the elements. Also, there is no hook to hang the type errors on. If I `yield*` a `Stream<dynamic>` inside a `Stream<int>` `async*` function, what happens to the type error. Will it be thrown at the `yield*` or end up in the stream? Likely the former. 
That means that `yield* s` will work like `await for (var _ in s) yield _;`. That's not a bad description either, it's easily understandable, and the story works for `sync*` too.

**Comment by eernstg** [comment]
@lrhn, it sounds like you actually ended up concluding that also `yield*` should admit element type `dynamic` and perform a per-element dynamic check?

**Comment by lrhn** [comment]
I did. `yield* foo` should allow `Stream<dynamic>`/`Iterable<dynamic>` because each element is assignable the generator's element type.

**Comment by eernstg** [comment]
Done in #830.
