### ISSUE TITLE
Should there be a way to control the language version for non-package libraries?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#838]
The language versioning spec associates a version for each library like so:

> * Assigning a default language version to each Dart package.
> * Assigning each Dart library to at most one Dart package.
> * Making each library inherit its package’s default language version unless it specifies a library-specific language version override.
> * Defaulting to the most recent language version if there is no other hint.

Or, in other words:

1. You can set the language version of a specific library by editing the library file itself and putting `// @dart=` in it.

2. Otherwise, you can set the language version of every library in a package by setting the version in the package config or using the latest version if the config does not set it.

3. Otherwise (the library is not in a package), you get the latest version.

There is no mechanism for setting the language version for a library that is *not* in a package without editing the library file itself. Should there be? It seems like a potentially useful affordance.

## Context

We ran into this problem with the SDK language and core library tests on analyzer. We have thousands of test libraries across several directories and many subdirectories. The legacy ones need to be at version 2.7 and the NNBD ones should use the current version.

Our initial plan to set the versions for the legacy tests was to make a package_config.json file that treated each legacy test directory like a "package" with a default version set. That *sort of* worked, but fell down when generated multitests came into play, since those generated files are outside of the "package"'s directory.

So we tried generated a package_config.json for those multitest files. But that put the test runner in a confused state because it wasn't architected to handle different tests in the same suite needing different package configurations.

Ultimately, it felt like treating the tests as being in some sort of faux package just so that we could control their version using a package config was going against the grain of the system.

## Default language version

Instead, we added a (currently hidden and unsupported) command line argument to analyzer, `--default-language-version`. If you pass that, you can specify what version any library not in a package uses. So far, it seems like a simple, clean solution to the problem.

This makes me wonder if this is useful enough for other end user problems to make an officially supported part of the language feature. Our giant pile of SDK tests is kind of an unusual situation, so it's not clear that an experience based on that generalizes.

Thoughts?

@leafpetersen @lrhn @eernstg @stereotype441

**Comment by eernstg** [comment]
Reading the description of the situation, I was thinking about a tool option like `--default-language-version` as the obvious approach. I can't see how it would hurt anyone to make this an "official" feature.

By the way, would a tool emit a message (warning) if `--default-language-version` is specified, but it has no effect? Should it (ever) be able to override the specification obtained from other sources? (It is a rather common choice to give command line arguments a higher priority than specifications obtained from other sources, but in this case the feature seems to be defined to have lower priority than all other ways to specify the language version, so we'd probably just leave it at that).

**Comment by lrhn** [comment]
You can edit the `package_config.json` file and introduce a package just for that library.

In the SDK situation, we should generate into separate directories, and include those generated directories in the fake package list.
Is that a viable approach? 

The SDK is special in that it is not a package itself. We generate test files into semi-arbitrary directories (why not into a `.generated` directory below the test directory, with `.generated` put into `.gitignore`?).

I think we can go a long way by cleaning up our act a little :)

**Comment by munificent** [comment]
> In the SDK situation, we should generate into separate directories, and include those generated directories in the fake package list.

I tried that with [this change](https://dart-review.googlesource.com/c/sdk/+/134873) but it ended up breaking other things. It meant that within a single test suite run by the test runner you had some tests using one package config and other tests using another package config. In principle, there's nothing wrong with that as far as the language goes. But the test runner has a fairly deeply embedded assumption that all tests in the same test suite have the same package configuration.

In general, synthesizing a package config to pretend that generated multitests were in some faux "package" felt kind of weird and brittle. The language tests—and further the generated multitests—aren't really like any normal notion of package, so pretending they are just to control the language felt like a bad fit.

> (why not into a `.generated` directory below the test directory, with `.generated` put into `.gitignore`?).

We could do that, but we would have to be *very* careful to ensure that any files generated into there instead of into a build directory in no way depend on any data that is build-configuration specific. Otherwise if you built say, "ReleaseX64" and then "DebugX64" the latter could clobber output from the former and generate files that are not identical. Giving each configuration its own hermetic build directory avoids those risks.

> I think we can go a long way by cleaning up our act a little :)

Yes, possibly! The language tests and the SDK repo are weird in many ways and it may be that `--default-language-version` is not generally useful and is just an artifact of our own weirdness.

**Comment by lrhn** [comment]
You can use `// @dart = 2.9` in every library if necessary.
