### ISSUE TITLE
Should mitigated legacy type arguments be used as the run-time value?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#841]
Cf. the nnbd spec, [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#classes-defined-in-opted-in-libraries), specifies that 

> If a class `C` in an opted-in library implements the same generic class
> `I` more than once as `I0`, .., `In`, and at least one of the `Ii` is not
> syntactically equal to the others, then it is an error if
> `NNBD_TOP_MERGE(S0, ..., Sn)` is not defined where `Si` is `NORM(Ii)`.
> Otherwise, for the purposes of runtime subtyping checks, `C` is considered
> to implement the canonical interface given by `NNBD_TOP_MERGE(S0, ..., Sn)`.

For example:

```dart
// Opted in.
class A<X> { void foo() { print(X); }} // Assume that it prints `int`, `int?`, or `int*`.
class B1 extends A<int?> {}
class B2 extends A<int> {}

// Opted out.
class C extends B1 implements B2 {}

// Opted in.
class D extends C {}

void main() {
  D().foo(); // 'int*' or 'int?'?
}
```

The simplest model seems to be that the superclass chain determines the actual value of the type variable `X` of an instance of `D`, so it prints `int?`.

This approach is currently taken by the vm, cf. https://github.com/dart-lang/sdk/issues/40553, and there may be things that depend on this choice:

```dart
// Opted in.
class E<X> { void foo(X x) {}}
class F1 extends E<int?> {
  // Could contain an implicitly generated version of `foo` where the type
  // check on the argument `x` is optimized into `x is int?`.
}
class F2 extends E<int> {
  // Ditto, with `x is int`.
}
```

So we would at least need to detect whether there are any optimizations depending on having the type argument value which is passed up the superclass chain (e.g., `int?` from `F1` to `E`), if we change that value.

However, a client of `D` ought to be able to treat such objects according to the _interface_ of that class (where we note that `D` implements `A<int*>`, because of normalization and `NNBD_TOP_MERGE`), and it would be an anomaly if developers need to start referring to the _superclass_ structure in order to determine what variant of `A` it "actually" implements. So, from a software engineering point of view (and simply because it seems more consistent), it might be better if the printout above were `int*`.

This is consistent with the following wording in the [nnbd spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#classes-defined-in-legacy-libraries):

> The canonical interface which `C` is chosen to implement for the purposes of runtime
> type checks is `I<int*>`.

**This would imply** both that the run-time type reported by an instance of `C` in the example above would be `A<int*>`, and presumably also that the value of `X` as obtained by code in `A` should be `int*`, cf. the example with `E`, `F1` and `F2` above.

Similarly, the class `D` in the example would statically implement `I<int*>`. When we discussed switching to a consolidated model (where each class has its own complete interface, and we don't search the entire superinterface graph for each member signature), a main argument was that the blame for the conflict should be assigned to the legacy class when it is migrated, not to all subtypes while the legacy class remains legacy:

That class (here: `C`) will _have_ to be corrected when it is migrated to nnbd, but until then it would silently prevent any subclasses from being migrated (there are no errors on `C` itself). For instance, if `D` were an error just for having `C` as a superinterface, directly or indirectly, then any such silent conflict in upstream legacy code would block migration of the library containing `D`, and there is nothing the maintainers of `D` can do until the maintainers of `C` agree to fix a class that seems to have no errors.

Cf. https://github.com/dart-lang/sdk/issues/40553, where I've asked for further input on the implementation efforts.

@leafpetersen, @lrhn, @munificent, WDYT?

**Comment by lrhn** [comment]
I don't know what we have actually specified, so caveat lector.

The class `C` imlpements `A` at some type. I think that type should be `int*` because `C` is declared in a non-null-safe library. Even without looking at the superclasses, I'd want that. Looking at the superclasses, it's also the only valid answer.

Class D must implement `A` at some type too. 

I'd be happy making `D` a compile-time error because it cannot implement both `A<int?>` and `A<int>` - which means that its type must be the "same" as all supertypes at `A` (with `int*` being the same as both `int` and `int?`), and there is no null-safe type satisfying that. So, there is no null-safe valid migration of class `D`. Tough, but no choice of migration of `C` will preserve the class hierarchy and make `D` valid (or `C` for that matter), so it's not like you are doing anything except postponing the pain.
I do not care if `C` might be "migrated" to not implement either `B1` or `B2`. That's a *rewrite*, and then we promise nothing.

If we want `D` to not be an immediate compile-time error, then there is only one valid choice, which is `int*`. It's confusing that a null-safe library introduces a non-null-safe type, but it does get it from its superclass.

If we pick `int?` then we get:
```dart
B2 x = D(); // Super-type assignment between null-safe types.
A<int> a = x;  // If `x` is A<int?>, then this is unsafe.
```
which contains only instances of objects declared in opted in libraries, and yet it's non null-safe.

That's what I think.

**Comment by eernstg** [comment]
Here are a couple of additional reasons why we would want to specify that the actual run-time value of a type argument for an object at a given superinterface should be the "mitigated" one (like `List<int*>` in the examples) rather than the one that is passed directly via the superclass chain.

First, if we just use the one from the superclass chain then we well get some surprising dynamic errors:

```dart
// In a nullsafe library.
class A<X> {}
class B1 extends A<int?> {}
class B2 extends A<int> {}

// In a not-nullsafe library, importing the above.
class C extends B1 implements B2 {}

// In a nullsafe library, importing the above.
class D extends C {}

main() => [D()]; // Throws!
```

So we assume that we just use the actual type argument passed along the superclass chain, which means that _static_ analysis considers `D` to implement `A<int*>`, but the actual instance reports that it implements `A<int?>`. The static type is used to infer the type argument of the list literal, yielding the type argument `int`, but at run-time the instance of `D` reports that it implements `A<int?>` and that (with strong nnbd checking) causes a dynamic error, because `A<int?>` is not a subtype of `A<int>`.

If the dynamic type of an instance of `D` were to report that its type argument at `A` is `int*` then we wouldn't have this dynamic error, which seems to be a more reasonable behavior.

Another issue is that any given object needs to be able to report that it has a specific value for a given type argument at a given type&mdash;it shouldn't have several different values. But consider the following example:

```dart
// In a nullsafe library.
mixin M<X> { late X x; }
class A with M<int?> {}

// In a not-nullsafe library.
class B extends A {}

// In a nullsafe library.
class C extends B with M<int> {}

void main() {
  C c = C();
  A<int> a1 = c;
  A<int?> a2 = c;
}
```

Both initializing expressions are accepted if we consider `C` to implement `A<int*>`. If we stipulate that the value of the type variable `X` at the type `A` for an instance of `C` is taken from the actual type parameter passed to the superclass, we have an ambiguity: The superclass of `A` is `Object with M<int?>`, so we're passing `int?`; but the superclass of `C is `B with M<int>` so we're passing `int`.

OK, we could say that there are two separate subobjects of the instance of `C` for `M`: First the one which is added by `A`, and later (at bigger offsets, typically) the one that is added by `C`. So we could argue that "of course they can have different values for `X`: Each of them have their own copy of whatever state is in scope to use `X`, e.g., `x`. (It's late just so we don't need to worry about initialization.)

But that won't work from the client perspective: We could have an instance variable `X x`, and the object layout for an instance of `C` could contain storage for both one and the other, and they could have different type, but we can't distinguish between one and the other getter at a call site, and the same for the setter, so we can't read/write both of those variables.

Instead, one getter overrides the other, and similarly for the setter. In this case the setter in the superclass of C is not a correct override of the setter in the superclass of A, which is a problem that is difficult to avoid (when we have both a setter and a getter, any change in the type will create an issue; we might be able to fix it with `covariant`, but we can't add that in a mixin application).

But the main point is that we shouldn't maintain multiple actual values of each type variable in a superinterface: This is a new and non-trivial concept, and it is not likely to be helpful to sort out the technical issues with that.

So I'd recommend, again, that we stick to a single value, and using the same conflict resolution that we have specified for the static analysis would make sense: So the instance of `C` would then have the value `int*` for the type variable `X` at the type `A`.

**Comment by crelier** [comment]
This proposal makes sense and can be implemented in the VM.
The output of `D().foo()` in the first example becomes `int*` as expected.

However, I still have questions about the other examples.
Why would `main() => [D()];` throw? It does not currently. Should it really?

The example involving mixins does not seem well formed.
Class `A` is not generic, so the types `A<int>` and `A<int?>` are properly rejected by CFE.
Was the intent to make `A` generic and propagate its type parameter to the mixin? Or rather to use `M<int>` and `M<int?>` as the static types of `a1` and `a2`?

If I use the latter, both assignments of `a1` and `a2` succeed, without needing to implement the feature of this proposal.

It would be good to clarify the mixin example.

Otherwise, the proposal is good. Intuitively, it seems that this mitigation of type arguments should also be applied to interfaces (which are only used in type tests in the VM) and not just to super types.

**Comment by crelier** [comment]
Here is an example showing the effect of mitigation of type arguments applied to interfaces.

```
// Opted in.
class A<X> {}
class B extends A<int?> {}

// Opted out.
class C implements B {}

// Opted in.
class D extends C {}

void main() {
  print(D() is A<int>);
  print(D() is A<int?>);
}
```

Without mitigation, this would print:
```
false
true
```
but with mitigation:
```
true
true
```

Here is a [CL](https://dart-review.googlesource.com/c/sdk/+/143009) implementing this proposal (including mitigation for interfaces) in the VM.

**Comment by leafpetersen** [comment]
> but at run-time the instance of `D` reports that it implements `A<int?>` and that (with strong nnbd checking) causes a dynamic error, because `A<int?>` is not a subtype of `A<int>`.

What strong nnbd checking are you referring to?  There is no specified dynamic check there, and that program should (and does) run correctly.

I don't really understand what is being proposed here, and I don't think it matches well with my understanding of how this should work.  It seems quite well-defined to me how type arguments should flow up the super-class chain, and I don't really understand what it means to mitigate them at the instance level.  That seems to imply that the same class needs to have different values for its type variables depending on where it occurs.

```
// Opted in
class A<T> {
  void f() { print(T); }
}

class B extends A<int?> {
}

// Opted out
class C extends B implements A<int> {}

// Opted in

void test() {
  new C().f();
  new B().f(); 
}
```
I think under this proposal the two calls are supposed to print different things?

**Comment by crelier** [comment]
Just answering the last question:

> I think under this proposal the two calls are supposed to print different things?

Yes, under this proposal, the calls print:
```
int*
int?
```
instead of printing:
```
int?
int?
```

Note that the `implements` clause in the example is not relevant here and its omission does not change the result. Note also that without the flag `--show-internal-names` passed to the VM, `int` would be printed instead of `int*`.

**Comment by leafpetersen** [comment]
> Here is an example showing the effect of mitigation of type arguments applied to interfaces.

@crelier I believe that your example should print `true` twice regardless of mitigation **in weak mode**, correct, since we use LEGACY_SUBTYPE.  And we are proposing to forbid strong mode execution of mixed mode programs, so I'm wondering how observable this would be by users.  I think *externally* to the class it's close to unobservable.  Internally to the class, it is of course observable either by printing out the type argument, or by testing `null is T`.

My thinking is that the given the following program:

```dart
// opted_in.dart
class A<T> {
  void f() { print("null is $T -> ${null is T}"); }
}

class B<T> extends A<int?> {
  void g() { print("null is $T -> ${null is T}"); }
}

// Opted out
// @dart = 2.7
import 'opted_in.dart';

class D<T> extends B<T> {
  void g() { print("null is $T -> ${null is T}"); }
}

class C extends D<int> implements A<int> {
}

// Opted in
import 'opted_in.dart';
import 'opted_out.dart';

void main() {
  new C().f();
  new B<int>().f(); 

  new B<int>().g();
  new D<int>().g(); 
}  
```

Should print (in weak mode)
```
null is int? -> true
null is int? -> true
null is int -> false
null is int* -> false
```

This is the behavior that I see in the VM and in DDC.  Currently dart2js prints:

```
null is int -> false
null is int? -> true
null is int -> false
null is int -> false
```

@rakudrama I think this is basically the question you and I discussed the other day.  cc @fishythefish

**Comment by eernstg** [comment]
@crelier wrote:
> Why would `main() => [D()];` throw? It does not currently. Should it really?

No, that was before we changed the mitigated implemented interfaces to be used for static checks as well as for the dynamic checks. No problem today.

> The example involving mixins does not seem well formed

Right, it should be `M<...>` in main rather than `A<...>`. Here is the current status:

```dart
// In a nullsafe library.
mixin M<X> { late X x; }
class A with M<int?> {}

// In a not-nullsafe library.
class B extends A {}

// In a nullsafe library.
class C extends B with M<int> {}

void main() {
  C c = C();
  M<int> a1 = c;
  M<int?> a2 = c;
}
```

The program is accepted by the CFE, based on the implementation changes that makes it pass the new tests 'language/nnbd/mixed_inheritance/legacy_*', corresponding to the spec update #897. The program is rejected by the analyzer because it does not yet implement this update.

Note that `C` implements `M<int>`, not `M<int*>`, but it is still true that it is assignable to both `a1` and `a2`.

About mitigation for interfaces: The example [here](https://github.com/dart-lang/language/issues/841#issuecomment-611812677) should indeed print `true` twice.

However, this issue is about the run-time value of type variables inherited from classes where mitigation has not yet occurred (like `A.foo` in the first example, which evaluates `X`), I considered the question about mitigation for interfaces to have been resolved already (#897).

@leafpetersen wrote:

> I think under this proposal the two calls are supposed to print different things?

about the following example:

```dart
// Opted in
class A<T> {
  void f() { print(T); }
}

class B extends A<int?> {
}

// Opted out
class C extends B implements A<int> {}

// Opted in

void test() {
  new C().f();
  new B().f(); 
}
```

The issue _is_ a question, and today I think the answer should be "no". ;-)

However, if we answer "yes" then I agree that `C().f()` should print `int*` (or `int`, if that's how `int*` prints) and `B().f()` should print `int?`.

I think the language semantics will be more manageable (and migration less painful) if we say "no", that is, if we use inherited method implementations that rely on the locally known value of type parameters. This means that an instance of `C` above may report that it implements `A<int*>`, and yet the implementation of `f` that it inherits from `A` behaves as if it implements `A<int?>`, because this is what we find by traversing its superclass chain. In other words, inherited method implementations will simply ignore the mitigation.

I agree that with the answer "no" to the question in this issue (which is what I prefer), we should get the following response to the program [here](https://github.com/dart-lang/language/issues/841#issuecomment-615528974):

```dart
null is int? -> true
null is int? -> true
null is int -> false
null is int* -> false
```

So **maybe we can conclude** this issue as follows:

The run-time value of a type parameter `X` in an instance `o` of a subclass `C` of a generic class `B` as seen from a method implementation `B.m` is determined by the type arguments passed in the superclass chain from `C` to `B`.

In particular, mitigation obtained via `NNTP_TOP_MERGE` may require `o` to behave in such a way that it is considered to implement `B` with a different value for `X`, but this is ignored during executions of `B.m`.

@leafpetersen, how do you like that? @munificent, @lrhn, WDYT?

**Comment by crelier** [comment]
> @crelier I believe that your example should print true twice regardless of mitigation in weak mode, correct, since we use LEGACY_SUBTYPE.

@leafpetersen My example indeed prints true twice in weak mode on the VM regardless of mitigation.

@eernstg The corrected mixin example passes on the VM regardless of mitigation.

> About mitigation for interfaces: The example [here](https://github.com/dart-lang/language/issues/841#issuecomment-611812677) should indeed print true twice.
> ...
> I considered the question about mitigation for interfaces to have been resolved already (#897).

@eernstg This example prints true twice without mitigation in weak mode, as noted above. In strong mode, it prints false and true, unless the pending CL applying mitigation to interfaces is used. But I understand that strong mode will now be disallowed in this mixed configuration.

> So maybe we can conclude this issue as follows:
> ...

I agree. This corresponds to the current state without implementing the changes proposed in this issue.

**Comment by leafpetersen** [comment]
Ok, it sounds like we can consider this issue resolved, except in so far as we should have test coverage for this.

**Comment by eernstg** [comment]
Cool! The main point in this issue was to establish what the semantics should actually be, and I think this is a good solution. I'll write some tests.
