### ISSUE TITLE
Super mixin. Extending

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#85]
Super mixin specification reads

> A mixin declaration introduces a mixin and an interface, but not a class

If mixin defines and interface, then it can be implemented. The following code works (Dart VM version: 2.1.0-dev.8.0 (Unknown timestamp) on "linux_x64")
```dart
class C {
}

mixin M on C {
}

class MA implements M {}

main() {
  MA m = new MA();
}
```
But what about extending? I didn't find a statement in a dart specification that an interface cannot be extended. No this statement in a Super mixin specification as well. But in the current implementation
```dart
class C {
}

mixin M on C {
}

class MA extends M {} // Error: The type 'M' can't be used as supertype.

main() {
  MA m = new MA();
}
```
If this (implementation) is correct, then, does it make sense to add a clear statement to the Super mixin specification that "Mixin cannot be extended"?

**Comment by eernstg** [comment]
It is definitely the intention that `extends M` is a compile-time error when `M` is declared as a `mixin`. I've included this issue on my work list to ensure that this fact will be stated explicitly when the [mixin feature specification](https://github.com/dart-lang/language/blob/master/accepted/2.1/super-mixins/feature-specification.md) is integrated into the language specification.
