### ISSUE TITLE
Specification for 2.2^

### ISSUE THREAD

**Issue by sashvoncurtis** [dart-lang/language#850]
Hey,

As the spec has gracefully evolved beyond 2.2 (stable release is 2.7.x) would it be possible to get a newer version?
The latest version is hosted here - https://dart.dev/guides/language/spec 

Thanks

**Comment by eernstg** [comment]
Yes, we aim to release a spec version 2.7; the main thing will be to integrate the static extension methods feature.

**Comment by sashvoncurtis** [comment]
Looking forward to it :)

**Comment by sashvoncurtis** [comment]
5th edition draft is out at 2.8.0-dev. great to see! 
closing this.
