### ISSUE TITLE
Null safety: The role of bounds in generic function type equality

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#880]
In commit 7c46a84c0db34cf5fc893bb650364d7bc49c7260, the following item is included in the list of changes:

```
- Change the notion of type equality for generic function bounds to mutual subtyping.
```

However, the corresponding change to the document appears to have been omitted, and it is also not done in any later commit. So if we maintain this decision then the change should be made, and otherwise the change log entry should be removed.

@leafpetersen, WDYT?

**Comment by nshahan** [comment]
Using mutual sub-typing in type object equality operations isn't feasible in both web compilers at this time. They both rely on the native behavior of JS constructs like switch statements that require equality to mean reference equality.

**Comment by leafpetersen** [comment]
> However, the corresponding change to the document appears to have been omitted, and it is also not done in any later commit.

The commit that you point to contains this exact change.

**Comment by nshahan** [comment]
It seems we (maybe just me, but not sure) are conflating the notion of type equality in the subtyping document with the equality operator on runtime type objects.

I believe the change @leafpetersen made was for the definition of equality of bounds when performing subtype checks, which the web compilers do fully support. 

@eernstg AFAIK the tests I added in https://dart-review.googlesource.com/c/sdk/+/139160 (your comment linked me here) are as [specified](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#runtime-type-equality-operator) in that the runtime type objects themselves should not be considered equal if the bounds differ. We follow the normalization and legacy erasure described in the feature spec so we can rely on reference equality at runtime.

**Comment by eernstg** [comment]
@leafpetersen wrote:
> The commit that you point to contains [this exact change](https://github.com/dart-lang/language/commit/7c46a84c0db34cf5fc893bb650364d7bc49c7260#diff-021e3a3a39f2b66e4aecb2ff8383ffedR94).

Aha, that's the reason why I didn't find it: The change log entry occurs in 'nnbd/feature-specification.md', but the actual change was made in 'resources/type-system/subtyping.md'. It didn't occur to me that it could be in a different file.

@nshahan wrote:
> conflating the notion of type equality in the subtyping document with the equality
> operator on runtime type objects.

I should have made that more explicit: It's about the subtype rules for generic function types. So there is no conflict in having different rules for equality among instances of `Type` which are obtained as reified types.

But the issue has now been resolved: The text in the change log entry actually reflect a corresponding change in the underlying main text, and generic function type subtyping does indeed use mutual subtyping of type variable bounds during subtype checks.

Closing.
