### ISSUE TITLE
type mismatch in dart can't be found when build;

### ISSUE THREAD

**Issue by wanjm** [dart-lang/language#881]
```
void main(List<String> args) {
  String left;
  int seconds = 60;
  left = seconds == 60 ? 11 : "1";
  print(left);
}
```

left is String， but 11 is not; but it can't be reported;

**Comment by eernstg** [comment]
What you see is an implicit downcast that succeeds in current Dart, but which will not be supported when we add the null safety feature (which is a huge part of what we're doing these days). So it is a known issue in particular with `?:` that it may give rise to "wild" casts (that are unlikely to succeed at run time), but this issue will disappear with upcoming versions of Dart.
