### ISSUE TITLE
Confusing argument_type_not_assignable

### ISSUE THREAD

**Issue by awhitford** [dart-lang/language#885]
The following code does not compile:
```dart
extension Iterables<E> on Iterable<E> {
  Map<K, List<E>> groupBy<E, K>(K Function(E) keyFunction) => fold(
      <K, List<E>>{},
      (Map<K, List<E>> map, E value) =>
          map..putIfAbsent(keyFunction(value), () => <E>[]).add(value));
}
```

Line 4 causes the following error:

> The argument type 'Map<K, List<E>> Function(Map<K, List<E>>, E)' can't be assigned to the parameter type 'Map<K, List<E>> Function(Map<K, List<E>>, E)'.dart(argument_type_not_assignable)

The compiler output looks like:
```
../lib/extensions/iterables.dart:4:7: Error: The argument type 'Map<K, List<E>> Function(Map<K, List<E>>, E)' can't be assigned to the parameter type 'Map<K, List<E>> Function(Map<K, List<E>>, #E)'.
 - 'Map' is from 'dart:core'.
 - 'List' is from 'dart:core'.
      (Map<K, List<E>> map, E value) =>
      ^
```

What is the significance of the **#E**?
What is invalid with the above code?

**Comment by natebosch** [comment]
There are two `E` in this example. There is `Iterables<E>` and `groupBy<E, K>`. The second one shadows the first one. So the `E` and `#E` are two different generic types with the same name, I think the `#` disambiguates them.

The lint [avoid_shadowing_type_parameters](https://dart-lang.github.io/linter/lints/avoid_shadowing_type_parameters.html) is intended to help with this, but it looks like it doesn't currently work in extensions. I filed an issue at https://github.com/dart-lang/linter/issues/2033

To fix, change to `groupBy<K>`.

**Comment by awhitford** [comment]
Bingo!  Thank you!
