### ISSUE TITLE
Should we do "definite re-assignment" analysis for late final global variables?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#887]
The following code has no specified errors:

```dart
late final Map<String, int> configuration;

void main() {
 configuration = {};
 configuration = {'a': 1};
 configuration = {'b': 2};
 
 print(configuration.length);
 print(configuration['b']);
}
```

In general, we don't track definite assignment for late final globals, since any side-effecting operation could perform a hidden assignment.  However, for the purposes of static errors around late final variables, it seems like it's in principle feasible to use the existing definite assignment mechanism to track late final globals which are "definitely re-assigned".  That is, we would add any late final global variable that is assigned to on any control path to the set of "definitely assigned" variables, and then issue an error if we saw a re-assignment to a late final global that is known to have already been assigned.

I'm not convinced the bang for the buck here is very high - this will only catch very obviously wrong code that is guaranteed to throw if that path is ever executed.  But it does seem feasible, and might be low enough effort to be worth it.

@johnniwinther @stereotype441 @scheglov @lrhn @munificent @eernstg  for thoughts?

cc @johnpryan

**Comment by stereotype441** [comment]
Personally I don't think it's worth it for several reasons:
- The kinds of bugs this would catch are going to be rare and pretty easy to debug even without the feature.
- The analysis would be so weak compared to what humans can intuitively do that I worry about people assuming they're getting extra compile-time safety that really isn't there.  (E.g. someone writes a small test program like in your example above, sees that the compiler catches the bug, and then assumes that the compiler will do similar analysis across function boundaries).
- All indications are that NNBD is going to be difficult to complete on schedule.  I don't think we should be adding features right now without a strong justification.

**Comment by lrhn** [comment]
I think the story that "definite assignment only works for local variables" is easier to tell than having very limited exceptions. 

On the other hand, this is an "obvious" case that any human can spot. I wouldn't mind if the analyzer detects more definitely wrong code than what the specification requires.

(If we're going to do something, I think recognizing final late instance variables definitely assigned in all constructor *bodies* would be more valuable).

**Comment by eernstg** [comment]
I agree that the bang for the buck may be a bit too small. The analysis would be intraprocedural, presumably, and it seems likely to me that the more important bugs of this kind (certainly harder, probably also more common) would arise because a scattered set of locations update the variable, and the control flow that reaches those locations could be complex. So it would have to be a really low-hanging fruit. ;)

**Comment by leafpetersen** [comment]
This is not planned.
