### ISSUE TITLE
Automatically insert ! for property access

### ISSUE THREAD

**Issue by xvrh** [dart-lang/language#894]
I am trying the non-nullable experiment flag 

I find a lot of warnings for code like:
```dart
class FillContent {
  final ShapeFill fill;
  double _rotation;
  //...

  void draw() {
    if (fill.color == null) {
      return;
    }
    _paint.colorFilter = fill.color.value;

    if (_rotation != null) {
      _matrix.rotateZ(_rotation);
    }
  }
}
```

To convert it, I have to refactor the code to use a local variable like that:
```dart
  void draw() {
    var color = fill.color;
    if (color == null) {
      return;
    }
     _paint.color = color.value;

    var rotation = _rotation;
    if (rotation != null) {
      _matrix.rotateZ(rotation);
    }
  }
```

Or more simply, since I know that my properties are not changing. Use the ! operator.
```dart
  void draw() {
    if (fill.color == null) {
      return;
    }
    _paint.color = fill.color!.value;

    if (_rotation != null) {
      _matrix.rotateZ(_rotation!);
    }
  }
```

I understand why the warnings are there: a property can be mutated between the check and the usage (it can be a getter that changes at every call).

But even is it is "unsafe", I'm sure everyone will chose the second option eventually. So why not make it automatic? And benefit from the "flow analysis" of local variable.

If a "selector" has already been checked against null (ie: `_myProperty != null` or `myVar.myProperty == null`, transparently insert a "!" for the next accesses to the "selector".

It looks better without those hundreds of `!`, it's intuitive and equally unsafe.

**Comment by munificent** [comment]
>  since I know that my properties are not changing.

If you know the properties will not change or be null, can you declare them to have non-nullable types? Does using `late` help?

**Comment by xvrh** [comment]
@munificent those properties will change. But not between the null check and the actual usage.

My idea is to use every null check guard as a strong signal from the developer that say "I know better than the compiler what I'm doing" :-)

**Comment by munificent** [comment]
> My idea is to use every null check guard as a strong signal from the developer that say "I know better than the compiler what I'm doing" :-)

Yes, that is what `!` is for in general. But I think if you know what better than the compiler what you're dong, it's good for *other people reading your code* to see that too, which is why we require you to explicitly write the `!`. Otherwise, the code is really saying "the *runtime* thinks it knows better than the compiler what it's doing but who knows whether or not the *human* does."

**Comment by xvrh** [comment]
I get your point that `!` is to explicitly correct the compiler.

I feel like the local type promotion is super powerful and it's a shame that we can't have it for properties.
When:
- The developer explicitly gives its intent with the surrounding null check
- The compiler understands the null check and the code flow

So it's sad that we have to repeat the intent a second time with the `!` operator.

**Comment by leafpetersen** [comment]
> I feel like the local type promotion is super powerful and it's a shame that we can't have it for properties.

Just to be clear, I think all of us agree with this - it's the largest pain point in migration by far.  At the same time, we all also fairly strongly feel that silently adding implicit checks that can fail at runtime is moving the language in a direction that we've had pretty clear feedback from users that they don't like.  Implicit cast failures and implicit covariance check failures are all frequently cited pain points in the issue tracker and elsewhere.  We thought pretty hard about how we could thread this needle, and just haven't come up with a solution we love.  You can imagine having a different kind of `is` check which promotes fields (so it's textually clear that something unsafe is happening), or having a different kind of property access syntax, or having an implicit variable bound to the promoted value or any of a number of things, but so far none of these ideas have really panned out, at least in my mind.

I still hold out hope that some of the ideas that @munificent has been looking at with patterns and de-structuring might give us a nice syntax for a more Swift-like approach in which guarded variable binding is syntactically lighter, but that remains to be seen.

**Comment by xvrh** [comment]
Thanks. 
I'm sure we are in good hands, you will find a good solution for this.

I'll close this issue since this is too specific and you already have preferred alternatives.
