### ISSUE TITLE
Can we call an expression whose type is a type parameter?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#896]
Cf. https://github.com/dart-lang/sdk/issues/41218. A compile-time error is [specified](https://github.com/dart-lang/language/blob/35ce3873ec46480b318020828c0d9553e6e595ac/specification/dartLangSpec.tex#L10377) in the language specification for the invocation of an expression of any type `T` which is not `dynamic`, not `Function`, and not a function type. In particular, when `X` is a type parameter whose bound is a function type, it is an error to invoke an expression of type `X`. Example:

```dart
// Situation reported in #41218
class C<X, Y extends void Function(X)> {
  final Y f;
  C(this.f);
  void m(X value) => f(value); // Error in some configurations, but not in most.
}

// Rewrite.
class D<X> {
  final void Function(X) f; // No error, but highly questionable use of `X`.
  D(this.f);
  void m(X value) => f(value); // Unsafe (but very common) use of `X`.
}

// Improved rewrite, come declaration-site variance support.
class E<in X> {
  final void Function(X) f; // Safe.
  E(this.f);
  void m(X value) => f(value); // Safe.
}
```

This error turns out to be reported in dartpad.dev, but not on the command line with `dart`, `dartanalyzer`, nor `dart2js` (version 2.8.0-dev.17.0).

Conceptually, we could say that it is a natural expectation in a language with subtyping to allow every operation on an entity of static type `S` whenever the same operation is allowed on a non-`dynamic` type `T` such that `S <: T`.

However that makes sense for objects and member accesses, because a subtype would generally mean "possibly some additional members, and at least the same, with compatible types". But with a function type `F` there are no other subtypes than `Never` (with null-safety, and `Null` as of today) and other function types, so "additional members" does not count as a justification.

Being able to specify a proper subtype of the given bound in a subtype of class `C` would offer additional affordances:

```dart
class C1<X> implements C<X, Y extends void Function(Object?)> {
  final Y f;
  C(this.f);
  void m(X value) => f(42); // OK, we know that `f` accepts any argument.
}
```

So should we stick with the strict reading of the current specification and get this error implemented everywhere, or should we allow invoking an expression whose type is a type parameter whose bound is a function type? Is there a killer example which will justify that those additional affordances really matter?

Here's a good example why it might be worthwhile to allow it: https://github.com/dart-lang/sdk/issues/41218#issuecomment-604347478.

@munificent, @leafpetersen, @lrhn, WDYT?

**Comment by lrhn** [comment]
In all places where a type variable occurs covariantly inside its scope, it should be treated as its bound wrt. capabilities. You should be able to call a type variable with a function type as bound. You can't call it in any way except as the bound, even though it could accept more optional parameters.

(And where it occurs contravariantly, it's going to need run-time checks until we get variance control).

I consider this a bug.

**Comment by eernstg** [comment]
So you'd prefer that the specification said:

```
otherwise, it is a compile-time error if the static type of $f$ is not a subtype of a function type.
```

**Comment by lrhn** [comment]
That would probably be sufficient, yes.

Do we allow dynamic invocations on `X extends dynamic`? If so, we should also allow dynamic calls on `X extends Function`.

**Comment by eernstg** [comment]
We should probably say `a subtype of` for all the allowed cases.

**Comment by leafpetersen** [comment]
I think that if `X extends Function` and `f` of type `X`, then:
  - `f(args)` is valid for any argument list `args`, and has type `dynamic`
  - `f.call` is a valid tear-off, of type `Function`
  - `f.call(args)` is a valid method invocation for any argument list `args`, and has type `dynamic`.

Does that match everyone's interpretation?

**Comment by lrhn** [comment]
That pretty much sums up `Function`.
It's how something typed `Function` behaves, so it should also be how `X extends Function` or `X & Function` (or `X & Y & Z & Function` or `X & (Y extends Function)`) should behave.

Similar rules apply for `dynamic` (with `dynamic` instead of `Function`) and `Never` (with `Never` instead of `Function` and `dynamic`).

**Comment by eernstg** [comment]
Specification changes landed as https://github.com/dart-lang/language/commit/1feae06ff82e55b380c3858a3b497faf8021f96b.
