### ISSUE TITLE
Simplified imports with inferred filenames?

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/language#899]
Most of the time, my Dart imports look like:

```dart
import 'dart:foo';

import 'package:bar/bar.dart';
import 'package:baz/baz.dart';
import 'package:some_descriptively_named_package/some_descriptively_named_package.dart';
```

1. `package:` imports very often have a lot of redundancy.
2. `package:` imports aren't consistent with `dart:` imports.

It's a minor cosmetic nit, but could we allow a simpler form where the filename is inferred?  That is, `import 'package:NAME'` would be syntactic sugar for `import 'package:NAME/NAME.dart'`.

**Comment by srawlins** [comment]
This looks like a duplicate of https://github.com/dart-lang/language/issues/649

**Comment by jamesderlin** [comment]
Ah, thanks.  I somehow couldn't manage to find that when searching.
