### ISSUE TITLE
use Integer as bool

### ISSUE THREAD

**Issue by aymanrs** [dart-lang/language#901]
Like in C language, if n is an integer instead of using `if(n != 0)` or `while(n != 0)` I'd like to to use `if(n)` and `while(n)`. This also helps to do something n times by using `while(n--)`

**Comment by lrhn** [comment]
The reason Dart does not have implicit conversion between types is that it can mask errors.
You have to use `bool` values in conditions, and that ensures that if you accidentally use the wrong variable, or forget to write `> 0` or `< 0` after the integer variable, the code isn't silently accepted.
If all types are accepted in conditions, it's impossible to detect whether you made a mistake or not.

We have no plans to change that at the current time, so you will have to continue writing `!= 0` after your `n`.
