### ISSUE TITLE
Mathematical operation resulting in an integer larger than 64 bits returns 0

### ISSUE THREAD

**Issue by MichaelM97** [dart-lang/language#905]
I am writing a program which works with large numbers that result from a shift operation.

For example
```dart
48 << 64
```

The resulting value should be `885443715538058477568` , however, Dart returns `0`. As no  error was thrown, it took a while to identify this issue was actually occuring, rather than it being an issue with the code I had written.

Should an exception be thrown here rather than silently returning 0? Or should a double be returned, which can hold a value of this size.

If anything, I think an exception that is similar to what is shown when you attempt to declare an integer with this value should be shown:
<img width="856" alt="Screenshot 2020-03-31 at 18 09 58" src="https://user-images.githubusercontent.com/22373058/78055223-22308c00-737b-11ea-9365-d8820d13c5c7.png">

**Comment by mraleph** [comment]
This is [documented behavior](https://api.dart.dev/stable/2.7.2/dart-core/int-class.html):

> The default implementation of `int` is 64-bit two's complement integers with operations that wrap to that range on overflow. 

Checking results of operations for overflow and throwing exceptions would have negative impact on code size and performance.

Overflowing into double would introduce polymorphism of representation and similarly affect code size and performance.

That is why the current implementation was chosen. 

I don't think I know any widely used language that actually would throw in such situation.
