### ISSUE TITLE
Change default type arguments passed to dynamically invoked generic functions?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#908]
Consider the following program:

```dart
Type foo<X>() => X;
List<X> bar<X extends C<X>>(X x) => [x];

class C<X extends C<X>> {}

void main() {
  var type = (foo as dynamic)();
  var list = (bar as dynamic)(24);
}
```

Tools are currently using instantiation to bound (i2b) to select default values for type arguments which are omitted at a dynamic call site for a generic function.

It is a dynamic error if i2b fails to find a regular-bounded type argument list (that is, if i2b fails overall, or if it succeeds but yields a type argument list where some type arguments do not satisfy the declared bound, which could in other situations yield a super-bounded type).

With null-safety, i2b will (still) use `dynamic` in the case where the type parameter has no bound, but [greatest closure](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#least-and-greatest-closure) will use `Object?`.

This difference is observable, because equality for reified types does not equate `Object?` and `dynamic`.

So **maybe we should use greatest closure** rather than i2b when we select the actual type arguments to a dynamic invocation of a generic function with no type arguments? After all, this choice of default type arguments seems to be related to expression type inference (where we otherwise use least/greatest closure).

The trybot runs in https://dart-review.googlesource.com/c/sdk/+/141702 seem to indicate that all tools use i2b, except DDC.

However, the types chosen as actual type arguments for a dynamically checked function invocation are never used during the static analysis, so there is little value in choosing `Object?` rather than `dynamic` from a static safety point of view.

So I'd recommend that we continue to use i2b for this purpose (because most tools do this), and get DDC adjusted to do the same.

Note that if we change i2b to use `Object?` rather than `dynamic` then this case would be included, but that change would be a very substantial breaking change in any case.

@munificent, @leafpetersen, @lrhn, WDYT?

**Comment by leafpetersen** [comment]
I don't see a lot of value in the change.  It gives us no additional static guarantees, and in so far as it is observable at runtime, it makes the result of a dynamic invocation differ from the equivalent static invocation.

Currently the following program:
```dart
Type foo<X>() => X;

void main() {
  print((foo as dynamic)());
  print(foo()); 
}
```

prints dynamic for both invocation.  It feels weird to make the first print `Object?`.

**Comment by eernstg** [comment]
I still can't tease out of [inference.md](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md) why `print(foo())` would print 'dynamic' rather than 'Object?'.

But I think we could conclude that we're not making any changes right now, and DDC should be adjusted such that the failures in https://dart-review.googlesource.com/c/sdk/+/141702 go away.

@leafpetersen, would you support that conclusion? (@lrhn, in a brief vacation from vacation? ;-)

**Comment by leafpetersen** [comment]
Yes, agreed.
