### ISSUE TITLE
(Set Literals) Language Tests

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/language#91]
***** Request: 
As per implementation Plan:

Task13 : (Language tests)
Language tests written.

****************
Tracked in this [Issue](https://github.com/dart-lang/language/issues/90)
[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md), see ETA in this issue too.
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)

**Comment by lrhn** [comment]
Landed as https://github.com/dart-lang/sdk/commit/095d694add117382a96edaa4d8448c985f06045b
