### ISSUE TITLE
How does the special "principle type" rule for Null closure parameter inference work in NNBD?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#910]
I'm trying to figure out how [#31546](https://github.com/dart-lang/sdk/issues/31546) interacts with null-safety. In particular, I'm migrating tests/language_2/closure/param_null_to_object_test.dart to null-safety and I'm not sure what the desired behavior is.

To help clarify, consider this example opted-in program:

```dart
void Function(Null) f = (x) {
  var list = [x];
  list.add("not null"); // (1)
};

(f as void Function(Object?))("not null"); // (2)

void Function(Never) g = (y) {
  var list = [y];
  list.add("not null"); // (3)
};

(g as void Function(Object?))("not null"); // (4)
```

Given that:

1. Is the *static type of the parameter* `x` `Null` or `Object?`? The former implies that line `(1)` is a compile error, while the latter would make it allowed.

2. Is the *runtime type of the function* `f` `void Function(Null)` or `void Function(Object?)`? The former implies that the `as` cast on `(2)` fails and throws an exception. The latter says it is allowed.

3. Is the *static type of the parameter* `y` `Never` or `Object?`? The former implies that line `(3)` is a compile error, while the latter would make it allowed.

4. Is the *runtime type of the function* `g` `void Function(Never)` or `void Function(Object?)`? The former implies that the `as` cast on `(4)` fails and throws an exception. The latter says it is allowed.

5. Do any of these answers change between weak and strong mode?

6. Did I get anything wrong in this example?

cc @nshahan @eernstg

**Comment by leafpetersen** [comment]
> * Is the _static type of the parameter_ `x` `Null` or `Object?`? The former implies that line `(1)` is a compile error, while the latter would make it allowed.

It should be `Object?`.  Both CFE and analyzer do the right hting here.

> * Is the _runtime type of the function_ `f` `void Function(Null)` or `void Function(Object?)`? The former implies that the `as` cast on `(2)` fails and throws an exception. The latter says it is allowed.

The latter.  The CFE does the right thing here.

> * Is the _static type of the parameter_ `y` `Never` or `Object?`? The former implies that line `(3)` is a compile error, while the latter would make it allowed.

We never fully resolved this, but I think it makes sense to say `Object?`.  The analyzer does this, the CFE does not.

> * Is the _runtime type of the function_ `g` `void Function(Never)` or `void Function(Object?)`? The former implies that the `as` cast on `(4)` fails and throws an exception. The latter says it is allowed.

It should be consistent with the static type, which I propose above should be the latter.

> * Do any of these answers change between weak and strong mode?

No.

> * Did I get anything wrong in this example?

Nope!

I have a TODO to add this to the spec.

cc @eernstg

**Comment by munificent** [comment]
Thanks! I'll take this into account in the test. I agree with your sentiment about Never and I'll add test coverage for that.

**Comment by munificent** [comment]
Can you sanity check my test changes [here](https://dart-review.googlesource.com/c/sdk/+/141702/7/tests/language/closure/param_null_to_object_test.dart) and [here](https://dart-review.googlesource.com/c/sdk/+/141702/7/tests/language/closure/param_null_to_object_weak_test.dart)?

**Comment by leafpetersen** [comment]
Done.

**Comment by eernstg** [comment]
@munificent wrote:
>> Is the static type of the parameter `y` `Never` or `Object?`? The
>>  former implies that line (3) is a compile error, while the latter would
>> make it allowed.

@leafpetersen wrote:
> We never fully resolved this, but I think it makes sense to say `Object?`.
> The analyzer does this, the CFE does not.

+1! There is no soundness reason for not using `Object?`, and `Object?` yields a more convenient situation for the developer who is writing the body of the function literal.

**Comment by johnniwinther** [comment]
What about the case `void Function(Never?) f = (x) {}` ? What is static/runtime type of `x` ?

**Comment by leafpetersen** [comment]
> What about the case `void Function(Never?) f = (x) {}` ? What is static/runtime type of `x` ?

@johnniwinther What do you think about specifying this as applying whenever the type in question (here `Never?`) is a subtype of `Null`?

**Comment by johnniwinther** [comment]
Sounds good.

**Comment by leafpetersen** [comment]
This has landed in the spec, closing this out.
