### ISSUE TITLE
Adding a universal comment for all programming languages

### ISSUE THREAD

**Issue by garbageoverflow** [dart-lang/language#912]
I am suggesting this to more developers, maybe someone will come with the perfect solution and everyone will add it in their programming language. _Thanks_

**Comment by birdbrainswagtrain** [comment]
What does this mean, and why would such a thing be useful?

**Comment by mateusfccp** [comment]
I think it has something to do with this repo: https://github.com/xss2bruh/UniversalComment

Which is empty, by the way.

**Comment by mraleph** [comment]
I think this is non actionable, so I am going to close this. `//` and `/*` are pretty universal to begin with given how many languages use them.
