### ISSUE TITLE
Can an NNBD library catch dynamic?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#916]
As I was migrating language_2/exception/try_catch_optimized5_test.dart, I ran into an interesting failure. Given:

```dart
main() {
  try {
    throw "ok";
  } on dynamic catch (error) {
    print(error);
  }
}
```

It runs fine in the VM:

```
$ dart --null-safety --enable-experiment=non-nullable temp.dart
ok
```

But analyzer does not like it:

```
$ dartanalyzer --enable-experiment=non-nullable temp.dart
Analyzing temp.dart...
  error • A nullable type can't be used in an 'on' clause because it isn't valid to throw 'null'. • temp.dart:4:8 • nullable_type_in_catch_clause
1 error found.
```

I don't see anything in the NNBD spec related to catching non-nullable types so I don't know which tool is behavior correctly. My hunch is that we probably do want to treat dynamic specially and allow that in a catch clause even though it's technically nullable?

A related question is around type parameters:

```dart
main<T>() {
  try {
    throw "ok";
  } on T catch (error) {
    print(error);
  }
}
```

Analyzer currently considers that an error, but does allow:

```dart
main<T extends Object>() {
  try {
    throw "ok";
  } on T catch (error) {
    print(error);
  }
}
```

cc @stereotype441 @scheglov @johnniwinther

**Comment by leafpetersen** [comment]
The type of the `on` clause may be nullable.  We discussed this [here](https://github.com/dart-lang/language/issues/385) with the decision to allow it.  The spec was landed [here](https://github.com/dart-lang/language/pull/293) in that state, but an interim draft specified an [error for potentially nullable](https://github.com/dart-lang/language/pull/293/commits/e721716748fe95927e7bce5bbb81aebd722b5ea9) on clauses, which is perhaps where the analyzer error originates.

**Comment by munificent** [comment]
OK, thanks! Filed https://github.com/dart-lang/sdk/issues/41378 to track fixing analyzer.
