### ISSUE TITLE
Should legacy type aliases define types with no top level nullability?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#927]
Consider the following program (consisting of 2 libraries, as indicated in comments):

```dart
// Library 'legacy.dart'.
// @dart = 2.6

typedef F = int Function();

// Library 'main.dart'.
import 'dart:async';
import 'legacy.dart';

main() {
  FutureOr<F> x = null;
}
```

https://github.com/dart-lang/sdk/issues/41501 raises the question about the nullability of the type introduced by `F`. Is it `int* Function()*` or `int* Function()`?

The analyzer and the common front end differ in this respect: The front end accepts 'main.dart' with no errors (so `F` is considered to denote `int* Function()*`), and the analyzer emits a compile-time error at the initialization of `x` in `main` (so `F` is considered to denote `int* Function()`).

If we consider a type alias like `F` to be similar to other type declarations then it introduces `F` into the library namespace denoting a type with no nullability.

For instance, with `class C {}` in a legacy library, a variable declared in a library with null-safety as `List<C> cs;` declares `cs` to have type `List<C>`, not `List<C*>`. Consequently, it is an error to have, say, `List<C> cs = [null];`.

On the other hand, any type which is not at the top level in the body of the legacy type alias should implicitly have the nullability `*`, because there is no other way for the legacy code to specify a proper legacy type. For example:

```dart
// Library 'legacy2.dart'.
// @dart = 2.6

typedef F = List<int> Function();

// Library 'main2.dart'.
import 'legacy2.dart';

main() {
  F f = ...; // List<int*>* Function().
  f().add(null); // OK.
}
```

I believe we should consider the analyzer behavior as correct, and request that the common front end is adjusted to remove the nullability from the top level of a type defined by a type alias in a legacy library.

@leafpetersen, @lrhn, @munificent, WDYT?

**Comment by lrhn** [comment]
Agree that the type of a type alias should not be pre-`*`'ed.

Any occurrence of the type alias in legacy mode will be given a `*` anyway, but it makes it possible for null-safe code to use the type alias meaningfully.

**Comment by eernstg** [comment]
Found this comment: https://github.com/dart-lang/language/issues/868#issuecomment-600999013. It already contains support from @leafpetersen and @lrhn for the where the type alias is considered to denote a type with no nullability operators at the top level. So I'll close this and create an issue on the CFE to ask for an implementation.
