### ISSUE TITLE
When should we warn about different default values for a parameter?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#928]
It is currently a warning when an override specifies a different default value for an optional parameter:

```dart
class A { void m({int i = 1}) {} }
class B implements A { void m({int i = 2}) {} } // Warning.
```

Neither `dartanalyzer` nor the common front end emit any diagnostic messages if the change is from "missing" to "present":

```dart
class A { void m({int i}) {} }
class B extends A { void m({int i = 1}) {} } // OK.
```

This is important because it occurs in situations where the overridden method is abstract and no default value can be specified, so the transition from "missing" to "present" cannot be avoided:

```dart
abstract class A<X extends num> { void m({X x}); }
abstract class B1 implements A<int> { void m({int x = 0}); }
abstract class B2 implements A<double> { void m({double x = 0.0}); }
```

(PS: a plain `0` double doesn't improve readability ;-). 

In contrast, `dartanalyzer` warns when the change is from "present" to "missing", both with a concrete and with an abstract overriding declaration:

```dart
class A {
  void m({int i = 1}) {}
  void m1({int i = 1}) {}
}

class B extends A {
  void m({int i}) {} // Warning.
  void m1({int i}); // Warning.
}
```

The latter becomes a problem with the decision in #812 to allow a required named parameter to override an optional named parameter with a legacy type:

```dart
// Legacy library.
// @dart = 2.6

class A {
  void m({int i = 0}) {}
}

// Library with null-safety.

class B implements A {
  void m({required int i}) {} // Warning.
}
```

It is an error to specify a default value for a required named parameter, so there is again no way to avoid the situation when the two libraries are not maintained by the same organization.

Conceptually, the omitted default value in an abstract method declaration can be seen as an existential property: A default value must be given in all concrete declarations (unless, of course, they contravariantly change the type to something nullable), but it is not known at the location where the abstract method is declared, and given that it could be several different values it is not even possible to know it in some situations. This supports the perspective that a missing default value in an abstract method has no conflict with _any_ given value, so there should not be a warning.

In contrast, a missing default value for an optional parameter in a concrete method declaration is just a concise way to specify that the default value is null (and if that's not allowed then it is simply an error to omit the default value).

Given the above, the question arises whether we should eliminate the warning in some cases.

I'd recommend that the warning is issued as follows: A missing default value for an optional parameter in a concrete method  declaration is considered to be `= null` (so it's not missing). Then, a warning is emitted for each case where two non-missing default values for the same parameter are different, but no warnings are emitted when one or two of the default values are missing.

This approach seems consistent and conceptually justified, but it will _introduce_ a warning when a concrete method is overridden such that we transition from "missing" to "present", so we may wish to omit the warning in that particular case, in order to ensure that the change is non-breaking.

@munificent, @lrhn, @leafpetersen, WDYT?

**Comment by lrhn** [comment]
I see no real problem here.

You can override a non-required legacy parameter with a required null-safe parameter because you *expect* the legacy parameter to be migrated to a required parameter eventually (perhaps because it's annotated with `@required`). If it's not migrated to a required parameter, your code will become invalid. Predictive migration works when you predict correctly.

If the legacy parameter has a default value, then it's probably not really required.

So there is only a problem if you migrate before your superclass, and you are likely to be doing it wrong. And it's only a warning.

**Comment by eernstg** [comment]
In some contexts a warning may cause a build to fail, so it may make a difference if we keep all of them.

**Comment by leafpetersen** [comment]
I don't see any reason to change anything based on this.  Out of order migration is a corner case that we handle with best effort, and this is a corner case of a corner case.  The user can either wait to migrate, or not make the parameter required.

**Comment by leafpetersen** [comment]
Closing this out, no changes planned.
