### ISSUE TITLE
Specification: Incorrect type check rule for `async` return.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#929]
The rules in the language specification about return statements in an `async` function include the [following](https://github.com/dart-lang/language/blob/780cd5a8be92e88e8c2c74ed282785a2e8eda393/specification/dartLangSpec.tex#L15497):

```
It is a compile-time error if $s$ is \code{\RETURN{} $e$;},
\flatten{S} is not \VOID,
and \code{Future<\flatten{S}>} is not assignable to $T$.
```

The context for this rule is that we are considering `return e;` where the static type of `e` is `$S$` (written as `S` when already in math mode), in an `async` function `$f$` with declared return type `$T$`. A typical example would be the following:

```dart
Future<num> f() async {
  return Future<int>.value(42);
}
```

This is allowed, because `$S$` as well as `\code{Future<\flatten{S}>}` is `Future<int>`, and `$T$` is `Future<num>`. Similarly, `return 42` is allowed because `\code{Future<\flatten{S}>}` is again `Future<int>`.

However, the following should be allowed, but is currently specified to be a compile-time error:

```dart
Future<Future<int>> g() async {
  return Future<int>.value(42);
}
```

Here, `\code{Future<\flatten{S}>}` is `Future<int>` and `$T$` is `Future<Future<int>>`, and the former is not assignable to the latter.

So we must change this rule.

Note that the vm and dart2js already run the following code with no issues:

```dart
import 'dart:async';

Future<Future<int>> g() async {
  return Future<int>.value(42);
}

void main() async {
  print(await await g()); // Prints '42'.
}
```

The analyzer currently rejects this program, but it is a non-breaking change to allow it. Also, the analyzer reports the following:

```
Analyzing n026.dart...
  error • A value of type 'int' can't be returned from function 'g' because it has a return type of 'Future<int>'. • n026.dart:4:10 • return_of_invalid_type
1 error found.
```

which is wrong with respect to the type of the returned expression as well as the declared return type, so there would be a need to take a look at the relevant code for this check in any case.

**Comment by ili** [comment]
5 cents, if you allow: it would be better to deny using `async` without `await`, because this causes missunderstood about how does it works.

**Comment by eernstg** [comment]
Hello @ili! There's nothing that prevents writing an `async` function that does not contain any asynchrony:

```dart
Future<int> foo() async => 1;
```

So what would it mean to deny using `async` without `await` in that situation?

**Comment by leafpetersen** [comment]
> So we must change this rule.

I'm not sure about must - there's nothing wrong with the rule.  I'm happy to consider changing it though.  Is this just a sub-issue for your revisit of the return rules?

**Comment by eernstg** [comment]
I don't understand why you do not think that the following is a bug in the specification:

> The following should be allowed, but is currently specified to be a compile-time error:

```dart
Future<Future<int>> g() async {
  return Future<int>.value(42);
}
```

> Here, `\code{Future<\flatten{S}>}` is `Future<int>` and `$T$` is `Future<Future<int>>`, > and the former is not assignable to the latter.

As I see it, it is obviously a spec bug when it is a compile-time error to return an expression of type `U` in an `async` function with return type `Future<U>`.

**Comment by eernstg** [comment]
Closing: #941 and #948 landed corrections for this in the null-safety specification.
