### ISSUE TITLE
Make it an error to `await voidExpression`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#932]
For the release of Dart 2, it turned out to be a more seriously breaking change than anticipated to make it an error to `await e` in the case where `e` has static type `void`.

Shouldn't we fix this now where null-safety is being introduced?

```dart
void foo() => null;

void main() async {
  await foo(); // Error, cannot await an expression of type `void`.
}
```

@leafpetersen, @lrhn, @munificent, WDYT?

**Comment by leafpetersen** [comment]
It's fine by me.  If @lrhn agrees with this change, we'd need a volunteer to spec it, write tests and file implementation issues.

**Comment by lrhn** [comment]
I'm always fine with disallowing use of `void`!

**Comment by eernstg** [comment]
Spec update in https://github.com/dart-lang/language/pull/933.

**Comment by eernstg** [comment]
Tests added in https://dart-review.googlesource.com/c/sdk/+/144140.

**Comment by eernstg** [comment]
Created issues for the analyzer and CFE implementation.

**Comment by leafpetersen** [comment]
Tests and spec have landed, issues filed.  I'm going to close this out.
