### ISSUE TITLE
How to encode string to RFC 3986 in Dart

### ISSUE THREAD

**Issue by hamza39460** [dart-lang/language#942]
I am trying to encode a string to RFC 3986. I have found the method Uri.encodeComponent but that encodes the string to RFC 2396. Basically, I am looking for an alternate method for a method in PHP i.e rawurlencode. In php this method encode the string to RFC 3986. Kindly, tell me how to do it in Dart

**Comment by mateusfccp** [comment]
I don't think this belongs here, as this repository is responsible for discussion about the language, and your request is related with Dart core.

Please, open an issue here: https://github.com/dart-lang/sdk.

**Comment by hamza39460** [comment]
> I don't think this belongs here, as this repository is responsible for discussion about the language, and your request is related with Dart core.
> 
> Please, open an issue here: https://github.com/dart-lang/sdk.

Thanks for referring me to there I found the solution in few minutes
