### ISSUE TITLE
Should `==` respect the left operand's `operator==` parameter type.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#949]
The `==` operator ends up calling the `operator==` method on the left operand if neither operand is `null`. It's not the *same* as calling `operator==`, but it behaves mostly the same. Prior to Null Safety, the typing could have been treated as if it was a direct call to the method.

The current specification does not use the parameter type of that `operator==` method for anything. Originally it never had to because `Object` declares `bool operator==(Object)` (or `dynamic` traditionally), so all subclasses are supposed to use a top-type as parameter type as well.
There was no need to check anything. So, `a == b` is treated like a unique thing which ends up calling `a.operator==` effectively dynamically (no static checks).

With the introduction of `covariant` parameters, it stopped being true that subclasses had to accept the same parameters. It's possible to write a class like:
```dart
class C {
  bool operator ==(covariant C other) => identical(this, other);
}
```
If you call `C() == 1` you get a run-time error. 

The analyzer is a bit smarter and recognizes that `C() == 1` will fail, and makes it a static error, just as if it was invoking a normal covariant method. Perhaps they are just treating it as a normal method invocation of `operator==`.

The CFE does not do this, it follows the specification as written and allows `a == b` for all objects `a` and `b`, no matter what the signature of `a.operator==` is.

With Null Safety, there is a need to look at cases like `Object? x = ...; x == x`. If we do type checking of the argument, then we need to remove the nullability from both operators before checking the right operand  against the parameter of the left operand, because `==` only calls that if neither is `null`. That's why this issue came up.

So, while we are updating the spec anyway, should we embrace the Analyzer approach of checking the left operand, or should we keep the specification as written and not check anything.

**Comment by lrhn** [comment]
My opinion: Keep the specification. Potentially add more restrictions.

The contract of `Object.operator==` (now `"Top".operator==`) is that it should gracefully accept any object as argument and return `true` or `false`. As such `bool operator==(covariant C ...)` is not implementing the contract. We should not make any effort to support that.

Actively supporting covariant parameters feels like a way to suggest that it is actually encouraged.
Why write the extra text to ensure that you get static warnings for something if it's not intended to be used.
Maybe some users will actually *want* to use covariant equals to get type checks against unrelated equals checks (https://dart-lang.github.io/linter/lints/unrelated_type_equality_checks.html).
Should we stop them?

This is indirectly enforcing the contract, something we don't do anywhere else (you can badly override any method using `covariant`, and all it hurts is yourself and your clients, but we don't try to prevent that elsewhere). 
We could more directly enforce that contract (fx require that no implementation of `operator==` has a parameter type which is not a supertype of `Object`).
Or we could indirectly enforce it by adding a lint to the same effect.
Simply not catching the run-time error at static type checking time is a passive sort of non-support, so maybe we can do better.

(This all comes back to `==` being an operator which shouldn't be virtual because a superclass cannot know how its subclasses think of equality. So, people will do whatever they can to work around that, including checking `runtimeType` and they will probably also try covariant arguments as a poor man's self type).

**Comment by eernstg** [comment]
We could make it a compile-time error to _declare_ an `operator ==` whose formal parameter is marked `covariant`.

But I think it's unhelpful to _allow_ this kind of declaration and then silently accept the construct for which we know statically that the right operand has a type which is not assignable to the statically known parameter type:

```
class A {
  int x;
  operator <(Object other) => other is A ? x < other.x : true;
}

class B extends A {
  operator ==(covariant B other) => super == other;
  operator <(covariant B other) => x < other.x;
}

void main() {
  B b = B();
  b < b; // OK.
  b < 2; // Compile-time error.
  b == b; // OK.
  b == 2; // (*)
}
```

So the question is whether (*) should be an error, and I think it's unhelpful to keep the known failure a secret at compile-time.

**Comment by leafpetersen** [comment]
> The CFE does not do this, it follows the specification as written and allows `a == b` for all objects `a` and `b`, no matter what the signature of `a.operator==` is.

@lrhn Where are you seeing this?  I see this as an error on every platform (see below).


// test.dart
```dart
class A {
  operator ==(covariant int x) => false;
}

void main() {
  var x = new A();
  x == "hello";
}
```


```
leafp-macbookpro:packages leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64NNBD/dart-sdk/bin/dart  ~/tmp/test.dart
../../../tmp/test.dart:7:8: Error: The argument type 'String' can't be assigned to the parameter type 'int'.
  x == "hello";
       ^
leafp-macbookpro:packages leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64NNBD/dart-sdk/bin/dartanalyzer  ~/tmp/test.dart
Analyzing /Users/leafp/tmp/test.dart...
  error • The argument type 'String' can't be assigned to the parameter type 'int'. • /Users/leafp/tmp/test.dart:7:8 • argument_type_not_assignable
1 error found.
```

**Comment by leafpetersen** [comment]
> or should we keep the specification as written and not check anything.

The specification as written, in my opinion, implies the behavior currently implemented.  operator == desugars into a something involving a method call, and method calls have specified errors and warnings.  If the specification intended for normal errors and warnings to be suppressed for operator ==, it should have been written to say so.  In the absence of such explicit language, it is 100% a reasonable reading of the spec to see it as implying the normal errors and warnings.  If asked **I would have said that this was the correct reading**.  If the specification was intended to be read otherwise, this is a **bug in the specification not the implementations**.

**Comment by leafpetersen** [comment]
To the original question: I don't have strong feelings.  In so far as I have thoughts:
  - I think it's quite odd to allow a covariant override of operator == and then ignore it.
  - I think it's a bit odd to disallow covariant override of operator == and not other things. 
  - The consistent thing to me seems to be to just do what the user asked for.
 
Note that there is (a small amount of) internal code which uses covariant overrides of operator ==.

**Comment by leafpetersen** [comment]
cc @munificent for thoughts.

**Comment by lrhn** [comment]
> @lrhn Where are you seeing this?

I'm using [DartPad](https://dartpad.dartlang.org/3e63fd1ae9b4453b618cd0c908d7b32c). Example:
```dart
class C {
  operator==(covariant C other) => identical(other,this);
}
main() {
  C c = C();
  try {
    print(c == 2);
  } catch (e) {
    print(e);
  }
}
```
compiles and prints:
```
TypeError: 2: type 'JSInt' is not a subtype of type 'C'
```
Same result for my local "Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "windows_x64".

So, if the CFE has an error now, it is a recent change.

**Comment by lrhn** [comment]
It's true that `e1 == e2` is defined as, after checking for `null`s, being equivalent to the method invocation `e1'.==(e2')`.

When the specification use the words "equivalent to", it's traditionally somewhat inconsistent, but generally when the phrase occurs as part of the *dynamic* semantics, it means that the *run-time* semantics are the same, but the static semantics are specified separately.

For the actual example:
```latex
Evaluation of an equality expression $ee$ of the form \code{$e_1$ == $e_2$} proceeds as follows:
\begin{itemize}
\item The expression $e_1$ is evaluated to an object $o_1$.
\item The expression $e_2$ is evaluated to an object $o_2$.
\item If either $o_1$ or $o_2$ is the null object (\ref{null}), then $ee$ evaluates to \TRUE{} if both $o_1$ and $o_2$ are the null object and to \FALSE{} otherwise.
Otherwise,
\item evaluation of $ee$ is equivalent to the method invocation \code{$o_1$.==($o_2$)}.
\end{itemize}
```
The `Otherwise` is guarded by dynamic checks, so there is no way the "equivalent to the method invocation ..." can be referring to static semantics.
The example:
```dart
class C { operator==(covariant int x) => true; }
main() {
  String y = null;
  print(C() == y);
}
```
should, by the given semantics, evaluate to `false`. The algorithm never gets to the item where it is equivalent to a method call. So, whether that method call would cause a static error or not, the specification does not say that the equality should do the same.

The static semantics for `e1 == e2` is currently just the line "... has the static type `bool`". The specification does not provide any way for an `==` expression to have a type error.

We can argue whether it should, but it hasn't so far.

**Comment by lrhn** [comment]
As for 

> * I think it's quite odd to allow a covariant override of operator == and then ignore it.
> * I think it's a bit odd to disallow covariant override of operator == and not other things.
> * The consistent thing to me seems to be to just do what the user asked for.

Those are good arguments. I'm somewhat OK with ignoring the declared type, but it's not great.
Disallowing having other parameter types is very specific. If we go that way, we should perhaps also lock down `noSuchMethod` so it can't accept a non-`Invocation`. Also not great.

Considering `noSuchMethod`, it's another "system method" which is invoked by the language semantics, not the user directly (although it *can* be called directly unlike `operator==`). 
We never check whether the argument to `noSuchMethod` is valid, we just call it with an `Invocation` and let it throw if it's covariantly not accepting an `Invocation`.

It's not the same as `operator==` because you don't actually call `noSuchMethod` "directly" (you don't call `operator==` directly either, but you do control the argument being called with).


Allowing users to write covariant parameters and then checking them statically is ... I guess consistent. They did write it. It will (probably) throw if the parameter type isn't satisfied.
It's also not a good feature, but we can't prevent anyone from making their `operator==` throw to being with, and `covariant` is an unsafe feature that should be used judiciously.


It's not a change that I would have made to begin with, but if the analyzer and CFE have already implemented it, then I guess it's a reasonable behavior.

**Comment by leafpetersen** [comment]
> The specification does not provide any way for an `==` expression to have a static type error.

I should file an implementation bug then: both implementations incorrectly report a static error on the following code:

```dart
void main() {
  void f;
  int x;
  x == f;
}
```

But of course, there is intended to be a static error there, because the specification doesn't work the way that you imply above.  It's one of the things that I really dislike about the current form of the spec: it's entirely non-local.  If you want to understand the static semantics of `operator ==` there's no one place that says "this is the static semantics of operator ==`.  Instead, there are lots of places that "patch in" bits and pieces. 

As a result of this, a reader of the spec must interpret it through those lenses.  And there are probably 100+ places where we say something of the form "X is equivalent to Y".

```
The expression $!e$ is treated as
(\ref{notation})
\code{($e$\,?\,\FALSE\,:\,\TRUE)}.
```
```
An expression of the form \code{++$e$} is treated as
\code{($e$\,+=\,1)}.
```
```
An \ON{}-\CATCH{} clause of the form \code{\ON{} $T$ $s$} is equivalent to an \ON{}-\CATCH{} clause \code{\ON{} $T$ \CATCH{} ($p_1$, $p_2$) $s$} where $p_1$ and $p_2$ are fresh identifiers.
```

None of these say anything about the static errors.  It's assumed that `!3` is an error because `3 ? false : true` is an error, `true++` is an error because `true += 1` is an error,  etc.
 
Expecting a user to understand that you do *not* intend for `operator ==` to be viewed through this lens is simply unreasonable.  It is specified as a desugaring into a method call, it is an entirely reasonable reading to assume that the intention is that the normal method call static checking applies.  If something else is intended the right thing to do is to make that clear.  

**This is a bug in the spec**.

**Comment by leafpetersen** [comment]
> We never check whether the argument to `noSuchMethod` is valid, we just call it with an `Invocation` and let it throw if it's covariantly not accepting an `Invocation`.

If we do want to restrict this, maybe saying that covariant overrides of the `Object` methods are uniformly disallowed would be better.  It certainly feels less ad hoc to me.

**Comment by lrhn** [comment]
I agree that the spec is somewhat impenetrable on this, and we should make things clear where possible. 

The spec is at least *partially* consistent in that "evaluation of `e` is equivalent to evaluation of `e'`" means only the dynamic semantics, and "expression `e` is equivalent to expression `e'`" (or similar for other *syntactic* categories) means dynamic and static semantics. I even think Erik has been fixing things to be consistent in that way.

I'd prefer to remove "equivalent" from evaluation entirely, and simply say:
> Otherwise perform the method invocation (\ref{something}) of the `operator==` method on *o1* with *o2* as the positional argument. Let *r* be the resulting value.

No equivalence, reference to a *semantic* operation (no static checking involved).

Then specify the static semantics on the side, in whatever shape we actually want it to have.

**Comment by lrhn** [comment]
But, to sum it up. If we already have both implementations doing the same thing, and it's not an entirely unreasonable behavior, then we should probably just specify it.

I'm not sure it's a desirable behavior, and by us doing extra work to explicitly make it work, we are implicitly saying that covariant equals methods are OK to use. Otherwise, why would we make the change.

**Comment by munificent** [comment]
> But, to sum it up. If we already have both implementations doing the same thing, and it's not an entirely unreasonable behavior, then we should probably just specify it.

Me too. Having the spec and implementations disagree is always bad for us and for users.

My generally feeling is that if the implementations agree and users haven't complained, the spec should probably just follow.

> I'm not sure it's a desirable behavior, and by us doing extra work to explicitly make it work, we are implicitly saying that covariant equals methods are OK to use. Otherwise, why would we make the change.

I think there are two models a user might have for `==` when defining a class:

* The `==` operator is declared by Object to work with all types. Instances of my subclass *are* Objects, so Liskov tells me I am obliged to fully support that policy and accept all objects as the RHS in my implementation. Pragmatically, this means instances of my class can always be used in this like Set<Object> and Map<Object, Whatever>. In other words, Object defines the `==` policy.

* The `==` operator is declared by Object mostly to allow heterogeneous collections but Object itself makes no real policy claims. If my subclass wants to only support equality with specific types (usually instances of the same class) and fail at runtime if you try to use it with other types, that's up to my subclass. If you throw a bunch of instances of my class in a Set, it will work, but if you mix them with other random classes, all bets are off. In other words, Object defines the `==` mechanism, but each subclass gets to decide its own policy.

I think of it as the strong and weak form of Liskov substitutability. The strong form says every subclass must support all superclass operations and they should *work*. The weak form allows a subclass to "support" an operation by detecting and reporting an error at runtime. It's substitutable to the degree that you can *try* the operation, but it might not succeed.

I don't think we can or should take a strong stance that `==` adheres to the strong form. That's too strict of a policy to apply to all possible Dart classes everywhere, and in practice can have performance implications that do matter for some users. Given that, if we do accept that it's OK for a `==` implement to fail on some operand types, then `covariant` is a nice, clean, self-documenting way to accomplish that.

**Comment by leafpetersen** [comment]
> I agree that the spec is somewhat impenetrable on this, and we should make things clear where possible.

👍 

On reflection, I should clarify that I don't think that the way that the `void` errors are specified is necessarily bad, even though it's "non-local".  I think it's reasonable to say "there are a class of errors around void expressions, and every expression is subject to the following rules".  Otherwise you literally have to add a section talking about void errors to every single construct, which is painful.  But if we use that style, it's important that we be very careful and very explicit in both defining our terms, how they interact, and when we wish them not to interact.

**Comment by leafpetersen** [comment]
> But, to sum it up. If we already have both implementations doing the same thing, and it's not an entirely unreasonable behavior, then we should probably just specify it.

To be clear, I'm willing to make a change here - I don't like covariant, and I don't think it's a commonly used feature.  But I do feel like carving out ad hoc restrictions on it for `==` isn't the way to go - it feels odd.

**Comment by lrhn** [comment]
@munificent 
> My generally feeling is that if the implementations agree and users haven't complained, the spec should probably just follow.

I don't think the vast majority of users will notice either way.

The thing is that we haven't actually *published* the behavior in question in any stable release yet.

In Dart 2.7.2, the latest stable, neither the analyzer nor the CFE (running `dart`) gave any warning on
```dart
class C {
  bool operator(covariant int x) => x == 42;
}
main() {
 C() == "a";
}
```
On tip of tree, both give errors.

The CFE changes were made one month ago in https://dart-review.googlesource.com/c/sdk/+/142145 based on a bug report which (IMO) is wrong. It assumes that `a == b` uses `a.operator==` for static checking which (IMO again) the specification doesn't say.
(I can see that I should also have read https://github.com/dart-lang/sdk/issues/39428 more thoroughly so I could disagree with getting static warnings using `covariant` at that point too).

I'm not sure when the analyzer changed (can't find a CL specifically mentioning the change), but I'm guessing it was part of some NNBD changes, perhaps around the "type of `Object.operator==` in legacy/strong mode" hack.

There *are* users doing covariant equals methods (because they could!), but they have so far gotten no advantage from it other than throwing at run-time.

So, the behavior here here *is* new. It has not been in any stable Dart release, and it was not required by the specification at any point, nor was it intended the way it is currently written (I was the one who [wrote](https://codereview.chromium.org/2998173002) the `\item evaluation of $ee$ is equivalent to the method invocation \code{$o_1$.==($o_2$)}` line). 


It is a change. Now, the change has been made to both front-ends and the specification has been written, so it's effectively a free change now. I wouldn't have used time on it, but now it's a sunk cost and we'd have to spend time turning it off again, so the question is whether the change is desirable, or at least so undesirable that it's worth disabling it.

It is probably not important at all. Which suggests keeping it.

I agree that it is, in some way, *consistent*. As if the `e1 == e2` operator was syntactic sugar for:
```dart
 let t1 = e1 in let t2 = e2 in t1 == null ? t2 == null : t2 != null && t1.==(t2)
```
And if we thought of it that way, then we would probably type-check typeof(`e1`).operator==.
That may very well be how users are thinking of it, even if I wasn't. (And from looking back, it seems both Erik and Leaf were thinking that's how it was supposed to work too, so I might be in a very singular minority here).

My main worry is that by making this change, which we didn't need to, we are actively encouraging people writing covariant `==` operators (or at least that it will be perceived as such). And that people will latch onto that as a "fix" for all the real problems that a virtual `==` has, which it isn't. You might get some extra static checks, but very likely it's just making some things less safe.

Yes, it's unsafe, but it says so right there with the `covariant` marker, and no more unsafe than other covariant methods. It'll throw at run-time if you misuse it, but that's what `covariant` means.


All in all, let's keep the new implementation. Embrace it and see what people will actually do with it.
(But remember that it is a breaking change because it does introduce errors where there weren't any before).

**Comment by eernstg** [comment]
### On the discussions about the spec

@lrhn wrote, about desugaring:
> I even think Erik has been fixing things to be consistent in that way.

Yes, I've been rather careful to make the distinction between evaluation and static analysis and its relationship with desugaring, but I haven't scanned through the entire language specification for this so you will surely be able to find exceptions.

Another example where we are relying on a desugaring step to produce code which is used to specify the dynamic semantics as well as the static analysis is 'for-in' statements, where it is [explicitly mentioned](https://github.com/dart-lang/language/blob/8924565f33ac9443b9501bbcd7fb825ff8c96f72/specification/dartLangSpec.tex#L14882) that desugared code may be used to determine that a compile-time error exists.

Another thing I've been doing, gradually, is to replace the apparently symmetric phrase 'is equivalent to' by the clearly asymmetric phrase 'is treated as', in order to clarify that desugaring has a direction, it is not an equivalence relation between programs.

@leafpetersen wrote:
> On reflection, I should clarify that I don't think that the way
> that the void errors are specified is necessarily bad, even
> though it's "non-local". 

The need to find information in more than one location in the language specification in order to answer a seemingly simple question about a snippet of code was a complaint that was raised several times about the language specification in the survey we had a few months ago. So that's obviously important.

I think the ability of even very small snippets of code to bring out many different parts of the language makes it very difficult to avoid this kind of non-locality. But one element that might be helpful (and that we can expand) is references, with clickable links, from one to another part of the spec. Another helpful device is the index (I use it quite often, at least ;-).

**Comment by leafpetersen** [comment]
> In Dart 2.7.2, the latest stable, neither the analyzer nor the CFE (running `dart`) gave any 
warning on

I don't have a copy of 2.7.2 handy, but the analyzer gives an error on this in version 2.6.0 and in 2.7.0, so if it fails to do so in 2.7.2 that was a regression.

```
leafp-macbookpro:dart leafp$ cat ~/tmp/test.dart
class C {
  bool operator ==(covariant C other) => identical(this, other);
}

void main() {
  var c = new C();
  c == 3;
}
leafp-macbookpro:dart leafp$ ~/dart/dart-sdk/bin/dartanalyzer --version
dartanalyzer version 2.6.0
leafp-macbookpro:dart leafp$ ~/dart/dart-sdk/bin/dartanalyzer ~/tmp/test.dart
Analyzing /Users/leafp/tmp/test.dart...
  error • The argument type 'int' can't be assigned to the parameter type 'C?'. • /Users/leafp/tmp/test.dart:7:8 • argument_type_not_assignable
1 error found.
leafp-macbookpro:dart leafp$ ~/dart/dart-2.7.0/bin/dartanalyzer --version
dartanalyzer version 2.7.0
leafp-macbookpro:dart leafp$ ~/dart/dart-2.7.0/bin/dartanalyzer ~/tmp/test.dart
Analyzing /Users/leafp/tmp/test.dart...
  error • The argument type 'int' can't be assigned to the parameter type 'C?'. • /Users/leafp/tmp/test.dart:7:8 • argument_type_not_assignable
1 error found.
```

> There _are_ users doing covariant equals methods (because they could!), but they have so far gotten no advantage from it other than throwing at run-time.

This is not true, see above.

**Comment by scheglov** [comment]
The code in https://github.com/dart-lang/language/issues/949#issuecomment-623995690 has a typo, it does not include the name `==` of the operator, so defines a *method* named `operator`. When fixed, the bleeding edge reports a compile-time error.

```dart
class C {
  bool operator==(covariant int x) => x == 42;
}

main() {
  C() == "a";
}
```
```
error: The argument type 'String' can't be assigned to the parameter type 'int?'. (argument_type_not_assignable at [test] bin/test.dart:6)
```

**Comment by lrhn** [comment]
Ack, my bad. Yes, the analyzer has been giving the warning all along then, and I can't type.

So, the analyzer has consistently treated `==` as a simple call to `operator==`, which makes perfect sense for static analysis (at least until Null Safety). I can argue that it's not what the spec said, but since nobody reads the spec anyway, it's safe to say that Dart has supported the behavior since the beginning. (Checked 2.0.0 and 1.24.3, the latter with an example which overrides `operator==` with a more specific parameter type, which you could in Dart 1).

That also means that no further harm should come from keeping it supported, and it's not a breaking change.

So, closing this issue. We'll do what the analyzer was doing, and what the CFE is now doing, and specify that.
