### ISSUE TITLE
Stream low frame rate behind reverse proxy

### ISSUE THREAD

**Issue by dubbelpunt** [dart-lang/language#950]
Hi,

I'm using https://pub.dev/packages/flutter_mjpeg in flutter to stream ip camera's. This uses the http Client() library. I noticed when I put the stream behind a reverse proxy from Nginx, the frame rate is very low. I have only 1 frame after x seconds. Direct url of the cgi-stream, works perfect. Opening the reverse proxy url from the browser also works perfect.

Example:
http://ip_ipcam/videostream.cgi ==> works perfect with Mjpeg() via flutter.

reverse proxy rpserver conf:
Location /ipcam1 {
    proxy_pass http://ip_ipcam/videostream.cgi
}

http://rpserver/ipcam1 ==> very low framerate with Mjpeg() via flutter. In the browser, this works perfect.

**Comment by mraleph** [comment]
This issue should be filed on the Flutter issue tracker - this repository is for Dart _language_ issues.
