### ISSUE TITLE
Fields should behave as private setters

### ISSUE THREAD

**Issue by skytect** [dart-lang/language#958]
Most of the time, we want fields of an object to behave as public getters but private setters. Setting a field from outside an object is generally a sign of bad practice, as state should be altered using "methods" instead.

However, in dart, one would need to declare the field as such to prevent it from being set from outside the object:
```dart
int _val;
int get val => _val;
```
This tedious boilerplate can slowly accumulate and create room for error.

### Why not default to private setter behaviour instead?

With private setter behaviour:
```dart
class Tail {
  int length = 0;

  void grow() {
    ++length;
  }
}

final tail = Tail();
tail.grow();
print(tail.length); // prints '1'
tail.length = 5; // raises compile error
```

### What if I need public setter behaviour?

If you need to set a field from outside the object, you are most likely implementing functionality that warrants for explicit setters.

**Comment by lrhn** [comment]
> Most of the time, we want fields of an object to behave as public getters but private setters

While somewhat common, I'm not sure that's actually most of the time. 
It might be a matter of what kind of code you are working on.
(I'd also prefer to keep the private getter as well, so I'm sure it won't be overridden in a subclass).

It is true that the `Foo _foo; Foo get foo => _foo;` pattern occurs often enough that it would be nice to have a shorter way to write the same thing. 

Maybe if we had a way to explicitly *add* setters and getters to an existing field.
```dart
Foo _foo { get foo; } // Field `_foo` also has getter `foo`. 
```
or
```dart
Foo { get foo; set _foo; }
```
(This syntax conflicts with something else I want to do about getters and setters, though).

**Comment by skytect** [comment]
@lrhn

> Having a public field with a getter and a setter is pretty common in data classes.

Hmm I did not think of that...

> (This syntax conflicts with something else I want to do about getters and setters, though).

May I know what that might be?

**Comment by lrhn** [comment]
> May I know what that might be?

Just considering a way to write getters and setters without having to repeat the type, using a C# like syntax like 
```dart
Foo _foo;
Foo foo { 
  get => _foo; 
  set => _foo = value;
} // Declares `foo` getter and setter.
Bar bar { get; set; }  // Declares *abstract* `bar` getter and setter.
```

**Comment by skytect** [comment]
Closing this issue as I no longer believe it should be implemented. A shortcut for creating fields with public getters and private setters can still be considered though, but that should be raised as a separate issue.
