### ISSUE TITLE
Dart forcing me to implement a non abstract method

### ISSUE THREAD

**Issue by swapnilrdx** [dart-lang/language#959]
I am trying abstract classes I found one issue that I have to implement the non-abstract method having a body in child classes

code:
abstract class Animal{
  void breathe(); //abstract method

  void makeNoise(){
   //non abstract method
    print('making animal noises!');
  }
}

abstract class IsFunny{
  void makePeopleLaugh();//abstract method
}

class TVShow implements IsFunny{
  String name;

  @override
  void makePeopleLaugh() {
    // TODO: implement makePeopleLaugh
    print("TV show is funny and make people laugh");
  }
}

class Comedian extends Person implements IsFunny{
  Comedian(String name, String nation) : super(name, nation);

  @override
  void makePeopleLaugh() {
    // TODO: implement makePeopleLaugh
    print('make people laugh');
  }
}

class Person implements Animal{
  String name,nation;

  Person(this.name,this.nation);

  //we must implement all the methods present in Abstract class and child should override the abstract methods
  @override
  void breathe() {
    // TODO: implement breathe
    print('person breathing through nostrils!');
  }

  //there should be no compulsion to override non abstract method
  @override
  void makeNoise() {
    // TODO: implement makeNoise
    print('shouting!');
  }

}

void main(List<String> arguments) {
  var swapnil=new Person('swapnil','India');
  swapnil.makeNoise();
  swapnil.breathe();
  print('${swapnil.name},${swapnil.nation}');
}

----------------------------------------------
here I am trying not to implement makeNoise method in my Person class but it gives error and says abstract method must be implemented.

Is this bug or I am getting concept wrong

**Comment by karlklose** [comment]
You are required to implement Person.makeNoise because Person **implements** Animal. If it **extends** Animal instead, it will inherit the implementation of makeNoise
