### ISSUE TITLE
Future<void> return type

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#960]
This code should not an error according to the spec, but both Analyzer and CFE don't report it now in legacy mode.

```dart
Future<void> foo() async {
  return 0;
}
```

![image](https://user-images.githubusercontent.com/384794/81733383-c4499680-9446-11ea-9afa-78031000b365.png)

I will use this issue to document the deviation from the spec in Analyzer, to let the readers of the code understand why they don't match.

**Comment by leafpetersen** [comment]
The spec is incorrect on this - an error was introduced [here](https://dart-review.googlesource.com/c/sdk/+/85959/16/docs/language/dartLangSpec.tex#11669).
