### ISSUE TITLE
operator []= isn't supposed to return a value

### ISSUE THREAD

**Issue by feinstein** [dart-lang/language#962]
Maybe I got this wrong, but the operator `[]=` has the following signature:

```dart
void operator []=(K key, V value);
```

So it accepts a `key`, a `value` and returns `void`, **nothing**.

But running some tests I can see that it indeed returns the `value`:

```dart
Map<String, int> map = {'a': 1};
int i = map['b'] = 2;
print(i); // prints 2
```

As if the operator's signature was:

```dart
V operator []=(K key, V value);
```

Is this an undocumented behavior or is it a bug in the operator's signature?

**Comment by rrousselGit** [comment]
```dart
int i = map['b'] = 2;
```
Is equal to:

```dart
map['b'] = 2;
int i = 2;
```

This doesn't use the return value of []=

**Comment by feinstein** [comment]
Oh, so like in C the `=` is chained? Like:

```C
a = b = c =1;
```

**Comment by rrousselGit** [comment]
Yes

**Comment by feinstein** [comment]
Oh thanks @rrousselGit, have been a while since I used this.
