### ISSUE TITLE
Call .toList() implicitely when converting from Iterable<T> to List<T>

### ISSUE THREAD

**Issue by ChristianKleineidam** [dart-lang/language#965]
My Flutter code is full of:
```
Column(
	children: listOfMyObjects.map((object) => MyWidget(object)).toList()
)
```
Frequently, I forget to type the `.toList()` and while the code compiles I get greated by an error on RunTime.

Similarly to how Flutter code looks cleaner since new is optional, I think it would make the code cleaner to make the call to  `.toList()` optional as well.

**Comment by mateusfccp** [comment]
Instead, I would prefer the compiler to throw an error (instead of getting it in runtime).

**Comment by rrousselGit** [comment]
The language already makes it a compilation error.
But you need to disable the `implicit-cast` feature.

This is done by adding the following to the file analysis_options.yaml:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

**Comment by Cat-sushi** [comment]
see also #108

**Comment by leafpetersen** [comment]
If we were to do something around this, it would be something more general, e.g. the proposal linked in the previous comment.  Given that this is already tracked, I'm going to close this out.

Note that the case that you forget to call `toList` will become an (opt-in) error in the upcoming null safety release, so at least you will get help from the compiler when you forget going forward.
