### ISSUE TITLE
Support Anonymous Types

### ISSUE THREAD

**Issue by vr19860507** [dart-lang/language#967]
Do you have plans to add anonymous types like in C# ?
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/anonymous-types

```
var v = new { Amount = 108, Message = "Hello" };  

Console.WriteLine(v.Amount + v.Message);
```

This is a very necessary thing! When I worked as a .net programmer, I constantly used this.

For example, you can use this syntax:

```
final obj = ({int a = 7, int b = 8});
```

**Comment by asyncsus** [comment]
> This is a very necessary thing!

May I ask why? If you posted some example programs, that would be great. I like anonymous types too, but I've never missed them so far.

**Comment by mateusfccp** [comment]
I don't really see any benefit for this...

**Comment by vr19860507** [comment]
> > This is a very necessary thing!
> 
> May I ask why? If you posted some example programs, that would be great. I like anonymous types too, but I've never missed them so far.

```
class AnonymousType {
  List<User> users;
  int minAge;
  int maxAge;

  AnonymousType({
    this.users,
    this.minAge,
    this.maxAge,
  });
}

void main() {
  final users = [
    User('A0', 47),
    User('A1', 12),
    User('A2', 34),
    User('A3', 56),
    User('A4', 3),
    User('A5', 99),
    User('A6', 34),
    User('A7', 7),
    User('A8', 76),
    User('A9', 3),
    User('B0', 47),
    User('B1', 12),
    User('B2', 34),
    User('B3', 56),
    User('B4', 3),
    User('B5', 99),
    User('B6', 34),
    User('B7', 7),
    User('B8', 76),
    User('B9', 3),
  ];

  print(users);

  final result = users.fold<AnonymousType>(
      AnonymousType(
        users: [],
        minAge: 999,
        maxAge: 0,
      ), (acc, x) {
    if (x.name.startsWith('A')) {
      acc.users.add(x);
    }
    if (x.age > acc.maxAge) {
      acc.maxAge = x.age;
    }
    if (x.age < acc.minAge) {
      acc.minAge = x.age;
    }

    return acc;
  });

  print(result.minAge);
  print(result.maxAge);
  print(result.users);
}
```

**Comment by munificent** [comment]
Yes, there are a number of tracking issues that essentially are synonymous with tuples/records/anonymous classes. I'm going go close this in favor of #207 but they are all circling the same topic.
