### ISSUE TITLE
Error concatenating .where .map .where on a List

### ISSUE THREAD

**Issue by camillo777** [dart-lang/language#977]
Hello, I am trying to filter some results of a List of Lists using a concatenation of "where" and "map" methods.

This is the simple code with a JSON sample.

```
import 'dart:convert';

final String body = """
  {
    "success": true,
    "data": [{
            "id": 4,
            "userId": 11,
            "active": true,
            "affiliations": [{
                    "id": 3,
                    "deptId": 1,
                    "active": true,
                    "createdAt": "2020-04-28T05:28:12.065Z",
                    "updatedAt": "2020-04-28T05:28:12.065Z"
                },
                {
                    "id": 4,
                    "deptId": 2,
                    "active": true,
                    "createdAt": "2020-04-28T05:28:12.065Z",
                    "updatedAt": "2020-04-28T05:28:12.065Z"
                }
            ]
        },
        {
            "id": 5,
            "userId": 6,
            "active": true,
            "affiliations": [{
                "id": 5,
                "deptId": 1,
                "active": true,
                "createdAt": "2020-04-28T05:28:12.065Z",
                "updatedAt": "2020-04-28T05:28:12.065Z"
            }]
        },
        {
            "id": 7,
            "userId": 11,
            "active": true,
            "affiliations": [{
                "id": 6,
                "deptId": 1,
                "active": true,
                "createdAt": "2020-04-28T05:28:12.065Z",
                "updatedAt": "2020-04-28T05:28:12.065Z"
            }]
        }
    ]
}
  """;

void main() {
  Map snap = jsonDecode(body);

  List list = snap["data"]
      .where((d) => d["active"] == true)
      .toList()
      .map((d) => (d["affiliations"]).where((dd) => dd["deptId"] == 1))
      .toList();

  list.forEach((el) => print(el["id"]));
}

``` 

I would expect at the end to see printed the filtered IDs.

But I have a runtime error:

in DartPad:
`Uncaught TypeError: J.getInterceptor$as(...).$index is not a functionError: TypeError: J.getInterceptor$as(...).$index is not a function`

on Android:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: Class 'WhereIterable<dynamic>' has no instance method '[]'.
E/flutter (17507): Receiver: Instance of 'WhereIterable<dynamic>'
E/flutter (17507): Tried calling: [](Instance(length:1) of '_GrowableList')
E/flutter (17507): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
E/flutter (17507): #1      main.<anonymous closure> 
package:mytest/main.dart:68
E/flutter (17507): #2      List.forEach  (dart:core-patch/growable_array.dart:282:8)
E/flutter (17507): #3      main 
```

I do not understand why.

What I see if I print the result is:
`[({id: 3, deptId: 1, active: true, createdAt: 2020-04-28T05:28:12.065Z, updatedAt: 2020-04-28T05:28:12.065Z}), ({id: 5, deptId: 1, active: true, createdAt: 2020-04-28T05:28:12.065Z, updatedAt: 2020-04-28T05:28:12.065Z}), ({id: 6, deptId: 1, active: true, createdAt: 2020-04-28T05:28:12.065Z, updatedAt: 2020-04-28T05:28:12.065Z})]`
I do not get why there is a "(" ")" around the JSON object.

It is a List if this type: 
`WhereIterable<dynamic>`

Thank you
Camillo

**Comment by leafpetersen** [comment]
This isn't really the right forum for this (this github repo is for discussion of changes to the language itself), but to answer your question, in this snippet:

```dart
  List list = snap["data"]
      .where((d) => d["active"] == true)
      .toList()
      .map((d) => (d["affiliations"]).where((dd) => dd["deptId"] == 1))
      .toList();
```

You are missing a `.toList()` on the result of `.where` here `      .map((d) => (d["affiliations"]).where((dd) => dd["deptId"] == 1))`, and so you are ending up with a list of Iterables, which can't be subscripted.  Once you fix that, you still have the problem that in your `print` statement at the end, you're subscripting in to a `List` using a string as an index.

```
void main() {
  Map snap = jsonDecode(body) as Map;

  List<List<dynamic>> list = (snap["data"] as List<dynamic>)
      .where((d) => d["active"] == true)
      .map((d) => (d["affiliations"] as List<dynamic>).where((dd) => dd["deptId"] == 1).toList())
      .toList();

  list.forEach((el) => print(el["id"]));
}
```

Unfortunately, json decoding is still very dynamically typed in Dart and hard to work with.  It's on the agenda to provide a better solution.
