### ISSUE TITLE
null flow analysis acts inconsistently with first vs later assignments

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/language#978]
```dart
void main(List<String> args) {
  int? a = 5;
  print(a.sign);
  a = 5;
  print(a.sign);
}
```

I get it, but it seems weird to get an error in the first case (line 3) and not the 2nd case (line 5).

```
error: An expression whose value can be 'null' must be null-checked before it can be dereferenced. (unchecked_use_of_nullable_value at [null_safety_sample_package] lib/main_example.dart:3)
```

**Comment by leafpetersen** [comment]
This is working as specified, so transferring it to a language issue.  It's not unreasonable to allow promotion on the initializer, I can see how it could be useful.  We already treat the non-nullable version of a type as being "of interest", so I think it would be a small change. It's a little weirder with `final` though:

```dart
final int? x = 3;
int.isEven;  // Is this ok?  It's weird, but consistent.
```

**Comment by jakemac53** [comment]
Note that the pattern here is the only way currently to convert a legacy type to a nullable type, if that got promoted it would be bad.

**Comment by eernstg** [comment]
@johnniwinther once mentioned a situation where it makes sense to do something similar, though a bit more subtle: A variable may get an inferred type which is obtained from a promoted type variable type (`X & T`) by stripping it off to the second operand, and then immediately promoting the variable to the promoted type:

```dart
void foo<X>(X x) {
  if (x is int) {
    var y = x; // `y` gets type `int` and is promoted to `X & int`.
    X x2 = y; // OK, `y` can be used where `X` is required.
    y + y; // OK, `y` can be used where `int` is required.
    print([y].runtimeType); // Prints `List<int>`.
  }
}

void main() {
  foo(10);
}
```

The point is that it is error prone to allow the type of a variable like `y` to be of the form `X & T`, and it is inconvenient if `y` is simply given the type `X` or `T` (here: `int`).

The current behavior (in nullsafety.dartpad.dev) is to make `y + y` a compile-time error and (if that's commented out) to print `List<int>` in the next line, which is rather confusing.

@johnniwinther, do you have further comments on this topic?

**Comment by johnniwinther** [comment]
I think in the example from @eernstg that `y` should be inferred to have type `X` (as it is now) and the proposal is to immediately promote it to `X & int` on initialization.

If you change the call-site to `foo<num>(10)` the print-out is `List<num>` showing that the type of `y` is indeed `X` and not `int`.

**Comment by munificent** [comment]
> It's a little weirder with `final` though:
> 
> ```dart
> final int? x = 3;
> x.isEven;  // Is this ok?  It's weird, but consistent.
> ```

I think this actually agrees with my intuition. In a world with definite assignment analysis, I think a variable initializer is equivalent to an assignment immediately after the declaration:

```dart
// This:
int i = 3;

// Means the same as:
int i; i = 3;
```

Allowing promotion based on the initializer aligns with that model. And in your example, my intuition is that, yes, you can use the variable. It was assigned after all. Further, I would expect:

```dart
final int? x = 3;
x.isEven;  // OK.
x = 4; // Error. Can't reassign to definitely assigned final.
```

**Comment by leafpetersen** [comment]
Note: I have proposed treating initializers for mutable variables as immediately promoting assignments in my initial definite assignment proposal [here](https://github.com/dart-lang/language/pull/991).  I have not proposed doing so for `final` variables, but am open to changing that.

**Comment by leafpetersen** [comment]
Spec for this landed.
