### ISSUE TITLE
add a new extension method for Bool

### ISSUE THREAD

**Issue by s4saurabhmishra** [dart-lang/language#986]
Since I am from iOS background while developing in dart , I am missing that amazing .toggle of swift. 
I want to create an extension method for Boolean type variable which will be responsible to toggle the current state of variable.

`bool isVisible = false;
isVisible.toggle(); // this will toogle the state to true`

**Comment by lrhn** [comment]
As Erik is saying, the requested feature is not possible in the current Dart language.

I'm not sure exactly which feature would make it possible (macros or reference parameters, perhaps), but it's not something that's on our short or medium term plans.
