### ISSUE TITLE
double as constant is set literals

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#99]
Please see https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md

> It is a compile-time error if any of the values of the constant element expressions override Object.operator== unless they are instances of int or String, objects implementing Symbol originally created by a symbol literal or a constant invocation of the Symbol constructor, or objects implementing Type originally created by a constant type literal expression.

What about double?

**Comment by lrhn** [comment]
Doubles are deliberately omitted from that list. They were also omitted in the existing specification, so this is not new.

Dart has never allowed constant maps or switch case expressions that are doubles.
The analyzer catches this, but it's still a "missing error" in the front-end.
