### ISSUE TITLE
Could we have an `await?` keyword?

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/language#994]
Could we perhaps add an `await?` keyword such that:

```dart
await? future;
```
is syntactic sugar for:

```dart
if (future != null) {
  await future;
}
```

## Motivation:
I not infrequently find myself trying to avoid overlapping asynchronous operations by using a `Future` as a lock:

```dart
class Foo {
  Future<void> pendingOperation;

  Future<void> doWork() async {
    if (pendingOperation != null) {
      await pendingOperation;
    }

    Future<void> doWorkInternal() {
      // ...
    }

    return pendingOperation = doWorkInternal();
  }
}
```

I could remove the `pendingOperation != null` check and unconditionally do `await pendingOperation`, but my understanding is that `await` *always* yields, which is unnecessary if `pendingOperation` is `null`.

Admittedly adding an explicit `if` check is not too inconvenient, but I don't think it's any less inconvenient than most cases that existing null-aware operators address.  Additionally, the existence of an `await?` keyword could emphasize that `await` always yields.

I mostly care about avoiding `await null`, but conceivably an `await?` keyword could also not yield on other non-`Future`s (and could avoid yielding on a `FutureOr<T>` that is actually a `T`).  I suppose not yielding on a `Future` that is already complete would also be a nice, but maybe that's a stretch.

**Comment by lrhn** [comment]
This sounds a little too specialized for a language feature.

If we disallowed `await` on values that are neither a `Future` or a `FutureOr` (nor `dynamic`), then it would make sense to have an `await?` operator. 
Having it only to avoid an asynchronous delay probably doesn't carry its own weight, especially when the workaround is *more* readable - it doesn't hide that there is a conditional `await` operation.
