### ISSUE TITLE
Types that are inferred from `dynamic` cannot recognize extension

### ISSUE THREAD

**Issue by wurikiji** [dart-lang/language#995]
# problem

```dart
main () {
  dynamic test = '1010';
  int intString = test.asInt(); // <- error `String` has no instance method `asInt`
  int intString2 = '1011'.asInt(); // no error
}

extension AsIntX on String {
   int asInt() => int.parse(this);
}

**Comment by leafpetersen** [comment]
This is working as intended and specified.  There is some discussion of the reasoning behind this in the feature specification [here](https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md).
