### ISSUE TITLE
'GoogleHttpClient.send' ('Future<StreamedResponse> Function(BaseRequest)') isn't a valid override of 'IOClient.send'

### ISSUE THREAD

**Issue by santoshakil** [dart-lang/language#998]
In my code, there is an error with "send". here is my code.

```
class GoogleHttpClient extends IOClient {
  Map<String, String> _headers;

  GoogleHttpClient(this._headers) : super();

  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) =>
      super.send(request..headers.addAll(_headers));

  @override
  Future<http.Response> head(Object url, {Map<String, String> headers}) =>
      super.head(url, headers: headers..addAll(_headers));
}
```

when I  hover mouse on the error which is on "send" then it shows:

'GoogleHttpClient.send' ('Future<StreamedResponse> Function(BaseRequest)') isn't a valid override of 'IOClient.send' ('Future<IOStreamedResponse> Function(BaseRequest)').dart(invalid_override)
![Screenshot_20200530_124945](https://user-images.githubusercontent.com/22114787/83321815-3ce88980-a274-11ea-9c74-b143b1bf20fc.png)

**Comment by munificent** [comment]
I think you want to change your return type to `Future<IOStreamedResponse>` instead of `Future<StreamedResponse>`.

(And, for issues like this in the future, the [SDK repository](https://github.com/dart-lang/sdk/issues) is a better place to file them. This repo is mainly for working on the design of the Dart language.)

**Comment by natebosch** [comment]
It looks like this was an unintentional breaking change in https://github.com/dart-lang/http/pull/388 sorry about that! We typically expect extending `BaseClient` or implementing `Client`, but I hadn't anticipated extending or implementing` IOClient`. I'll try to keep that in mind in the future.
